### ISSUE TITLE
类似这种方法，该怎么通过trace去查看？

### ISSUE THREAD

**Issue by NGLSL** [alibaba/arthas#1000]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： lastst
* Arthas 版本: 3.1.7
* 操作系统版本: centos 7.4
* 目标进程的JVM版本: 25.231-b11
* 执行`arthas-boot`的版本: lastst

### 重现问题的步骤

1. 通过`trace -n 10 org.springframework.data.redis.core.DefaultValueOperations get '#cost>50'` 查看耗时最多的方法。

结果：
```Text
---ts=2020-01-06 11:50:00;thread_name=From UserThreadFactory's MixtureHandler-Worker-18;id=dec;is_daemon=false;priority=10;TCCL=org.springframework.boot.loader.LaunchedURLClassLoader@49c2faae
    `---[202.065748ms] org.springframework.data.redis.core.DefaultValueOperations:get()
        +---[0.001555ms] org.springframework.data.redis.core.DefaultValueOperations$1:<init>() #53
        `---[202.033555ms] org.springframework.data.redis.core.DefaultValueOperations:execute() #53
```

2. 再通过`trace -n 10 org.springframework.data.redis.core.DefaultValueOperations execute '#cost>50'`

却提示：

```Text
[arthas@8805]$ trace -n 10 org.springframework.data.redis.core.DefaultValueOperations execute '#cost>50'
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. check arthas log: /root/logs/arthas/arthas.log
4. visit https://github.com/alibaba/arthas/issues/47 for more detail
```

### 期望的结果

像`trace -n 10 org.springframework.data.redis.core.DefaultValueOperations execute '#cost>50'` 调用的一样，查看耗时时间。

### 实际运行的结果

```Text
[arthas@8805]$ trace -n 10 org.springframework.data.redis.core.DefaultValueOperations execute '#cost>50'
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. check arthas log: /root/logs/arthas/arthas.log
4. visit https://github.com/alibaba/arthas/issues/47 for more detail
```

**Comment by hengyunabc** [comment]
试下直接 `trace  org.springframework.data.redis.core.DefaultValueOperations execute` ，可能有参数不对。

**Comment by NGLSL** [comment]
> 试下直接 `trace org.springframework.data.redis.core.DefaultValueOperations execute` ，可能有参数不对。

还是不行

```Text
[arthas@19392]$ trace org.springframework.data.redis.core.DefaultZSetOperations execute                       No class or method is affected, try:                                                                          1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).                                                                                                    2. reset CLASS_NAME and try again, your method body might be too large.                                       3. check arthas log: C:\Users\Administrator\logs\arthas\arthas.log                                            4. visit https://github.com/alibaba/arthas/issues/47 for more details.
```

代码的截图

![image](https://user-images.githubusercontent.com/40338580/71811948-e7d38d80-30b0-11ea-9e1b-aa9121169907.png)

**Comment by NGLSL** [comment]
> 试下直接 `trace org.springframework.data.redis.core.DefaultValueOperations execute` ，可能有参数不对。

但是我点击进去，找到相对应的代码确是可以

`trace -n 10 org.springframework.data.redis.core.RedisTemplate execute`

![image](https://user-images.githubusercontent.com/40338580/71812126-59abd700-30b1-11ea-9f8f-efd03b419e18.png)


![image](https://user-images.githubusercontent.com/40338580/71812183-7cd68680-30b1-11ea-8f91-15b61174f621.png)

![image](https://user-images.githubusercontent.com/40338580/71812187-819b3a80-30b1-11ea-8dc1-70c2ee450a6f.png)

找到最后调用的方法，就可以直接执行

**Comment by hengyunabc** [comment]
。。可能是的确没有方法的吧。。    sm 命令查看下。或者 jad 命令反编译看下。

**Comment by NGLSL** [comment]
这个问题，也算是自己解决了...不过arthas不支持这么操作，可能还要需要找到具体的类和方法才行。
