### ISSUE TITLE
logger使用后不显示

### ISSUE THREAD

**Issue by yangtao198536** [alibaba/arthas#1001]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 
* Arthas 版本: 3.1.7
* 操作系统版本: centos6.7
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: jdk1.8

### 重现问题的步骤

1. 我的项目使用的logback.xml,项目中的的日志打印都没有问题，而我使用logger后没有显示？
2.部分配置
<configuration scan="true" scanPeriod="60 seconds" debug="false">
	
	
     <property name="log_path" value="../log" />
     <property name="log_name" value="GameServer" />
     
	 <property name="maxHistory" value="7" />
	 
	 <property name="maxHistory1" value="48" />
    
    
    <property name="LOG_HOME" value="${log_path}" />
    
      
    <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">  
        <encoder>
            <pattern>%d [Thread:%thread] %-36logger{36} L%-4line %-5level - %m%n</pattern>
            <charset>UTF-8</charset>
        </encoder>
    </appender>

	<appender name="ServerFile" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">  
            <level>INFO</level>
        </filter>  
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${log_path}/${log_name}_%d{yyyy-MM-dd}.log</fileNamePattern>
            <maxHistory>${maxHistory}</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>%d [Thread:%thread] %-36logger{36} L%-4line %-5level - %m%n</pattern>
            <charset>UTF-8</charset>
        </encoder>
    </appender> 

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

[arthas@1544]$ logger 
[arthas@1544]$

把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
最好提供可运行的demo，不然没法下手。

**Comment by ztojs** [comment]
看看你的logback.xml文件中有没有这样的配置：
<logger name="com.xxxxxx.xxxxxx" level="DEBUG">
        <appender-ref ref="Console"/>
</logger>
如果有的话，先注释掉再试试。

我遇到同样的情况，把这样的配置注释掉之后就可以了。
