### ISSUE TITLE
Arthas启动后session没有显示AgentId

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/arthas#1002]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： arthas-boot.jar
* Arthas 版本: 3.1.7
* 操作系统版本: Linux
* 目标进程的JVM版本: JDK1.8
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1. 我想用tunnel-server控制台界面去使用Arthas,已经在A机器启动了.
2. 在B机器启动Arthas,然后attach了一个进程,想用session命令查看AgentId
3. 然而没有出现,使用--agent-id也没有用

![image](https://user-images.githubusercontent.com/3397316/71803396-a5538600-309b-11ea-8576-fe5825182dd7.png)

### 期望的结果

想在B机器显示AgentId后再到tunnel-server控制台界面去连接操作Arthas.

### 实际运行的结果

缺失AgentId无法连接过去.

```
无异常
```

**Comment by hengyunabc** [comment]
查看 ~/logs/arthas/arthas.log ，看有没有错误信息。  另外，手动测试下目标网络 7777 端口 是否连通的。

**Comment by cookiejoo** [comment]
> 查看 ~/logs/arthas/arthas.log ，看有没有错误信息。 另外，手动测试下目标网络 7777 端口 是否连通的。

日志没有异常,你可能理解错了.
使用tunnel-server.jar包这个控制台.肯定要先启动Arthas包里面的Arthas-boot.jar,再拿出来这个attach的进程里面的agentId吧,session命令没有出现agentId这个信息.所以启动tunnel-server.jar包没啥用.tunnel-server.jar页面里面有AgentID是必填的.

所以不知道什么情况,我是按照web-console文档里面的说明搞的.

![image](https://user-images.githubusercontent.com/3397316/71806313-73deb880-30a3-11ea-8439-93b3a05d0859.png)

**Comment by wangyu625** [comment]
我也是这样  看不到agentid

**Comment by hengyunabc** [comment]
按文档执行：

```
./as.sh --tunnel-server 'ws://47.75.156.201:7777/ws'
```

看测试服务器能不能连上，能连上就是正常的。 

连不上就检查：

* 是否自己部署的tunnel-server有问题
* 是否自己的网络有问题
* 是否启动脚本参数配置有问题。执行 `bash -x ./as.sh  --tunnel-server 'ws://47.75.156.201:7777/ws'` 查看具体的脚本参数是否传递正确

**Comment by cookiejoo** [comment]
> 按文档执行：
> 
> ```
> ./as.sh --tunnel-server 'ws://47.75.156.201:7777/ws'
> ```
> 
> 看测试服务器能不能连上，能连上就是正常的。
> 
> 连不上就检查：
> 
> * 是否自己部署的tunnel-server有问题
> * 是否自己的网络有问题
> * 是否启动脚本参数配置有问题。执行 `bash -x ./as.sh  --tunnel-server 'ws://47.75.156.201:7777/ws'` 查看具体的脚本参数是否传递正确

我大概知道什么原因了,文档说明需要更明确一些,很多人第一次弄这个东西基本上都不知道咋回事

**Comment by hengyunabc** [comment]
@cookiejoo 欢迎提PR改进： https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/web-console.md

**Comment by cookiejoo** [comment]
> @cookiejoo 欢迎提PR改进： https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/web-console.md

好的,我先多研究一下这个web控制台,抽空写个我自己使用和理解的文档出来,或许也能帮助到一些同学使用.

**Comment by cookiejoo** [comment]
整个web-console的使用心得我已整合到博客上了,欢迎交流经验
https://blog.csdn.net/caodegao/article/details/104016095

**Comment by cookiejoo** [comment]
> @cookiejoo 欢迎提PR改进： https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/web-console.md

整个web-console的使用心得我已整合到博客上了,欢迎交流经验
https://blog.csdn.net/caodegao/article/details/104016095
