### ISSUE TITLE
Arthas IDEA插件

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1004]
插件地址： https://plugins.jetbrains.com/plugin/13581-arthas-idea

使用文档： https://www.yuque.com/docs/share/fa77c7b4-c016-4de6-9fa3-58ef25a97948?#

感谢 @WangJi92 的工作。

**Comment by li24361** [comment]
厉害,刚需啊

**Comment by mostcool** [comment]
可以再厉害点，不要复制命令了，直接把命令在idea -> terminal -> arthas 里执行就更好了。

**Comment by huozhicheng** [comment]
很棒

**Comment by WangJi92** [comment]
> 插件地址： https://plugins.jetbrains.com/plugin/13581-arthas-idea
> 
> 使用文档： https://www.yuque.com/docs/share/fa77c7b4-c016-4de6-9fa3-58ef25a97948?#
> 
> 感谢 @WangJi92 的工作。

主要感谢arthas的开源，才让线上发现线上bug更加容易，小伙伴们都很喜欢❤️

**Comment by trey-tao** [comment]
赞

**Comment by hongjiev** [comment]
这个就厉害了，赞 👍

**Comment by pigxcloud** [comment]
nice

**Comment by WangJi92** [comment]
> nice

欢迎使用啊，现在支持了获取环境变量，设置静态变量等等 ，有需求可以一起搞

**Comment by enjoyDay** [comment]
强啊，可以在arthas官网来个标题专门介绍一下了

**Comment by WangJi92** [comment]
arthas idea plugin 增加了体验的demo，结合视频进行走一遍demo的内容，会更加的了解使用arthas ，让你线上排查问题更加速度，喜欢的可以分享给你们的同事。 https://github.com/WangJi92/arthas-plugin-demo

**Comment by ambition0802** [comment]
老哥太棒了，这个插件配合arthas简直就是如虎添翼，牛逼就完事了。

**Comment by 1000-7** [comment]
赞啊赞啊

**Comment by cherryBlossomss** [comment]
直接生成指令，cv就行，牛逼，牛逼
