### ISSUE TITLE
不支持glassfish

### ISSUE THREAD

**Issue by leonard-wu** [alibaba/arthas#1005]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： v3.1.7
* Arthas 版本: v3.1.7
* 操作系统版本: ubuntu
* 目标进程的JVM版本: :java-1.8.0-openjdk-1.8.0.121
* 执行`arthas-boot`的版本: v3.1.7

### 重现问题的步骤

1. 在glassfish4.1 server中执行 java -jar arthas-boot.jar

### 期望的结果

显示的所有java进程中，所有的进程中之一有包含用sc命令能够查到自己系统的类的进程

### 实际运行的结果

显示的所有java进程中，所有的进程中都没有包含用sc命令能够查到自己系统的类的进程

**Comment by hengyunabc** [comment]
试下最新版本。
