### ISSUE TITLE
死锁问题能不能和jstack一样显示deadlock，而不是blocked呢？

### ISSUE THREAD

**Issue by happy-xjb** [alibaba/arthas#1007]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by jiangwh** [comment]
deadlock 需要对所有线程栈分析，如果有thread相互等待，那么才会deadlock。单个线程的状态不存在deadlock，只有有blocked，blocked状态下线程不能说明线程存在问题。
