### ISSUE TITLE
--attach-only是个什么命令?其作用是什么?

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/arthas#1008]
请问一下--attach-only是个什么命令,像个后台执行arthas一样,日志打印不够详细,不知道是否正attach到了进程.
帮助文档也没有一个详细的说明,看不懂该命令的作用,有人知道怎么用这个命令吗?
个人尝试了一下,执行后就跳出attach的控制界面了.

**Comment by hengyunabc** [comment]
只 attach，不启动 telnet去连接。 比如只想启动 webconsole的端口，然后用户再用浏览器去连接。

**Comment by cookiejoo** [comment]
> 只 attach，不启动 telnet去连接。 比如只想启动 webconsole的端口，然后用户再用浏览器去连接。

噢噢噢,明白了,但是有个问题,就是attach不到webconsole端没有任何报错,这个咋判断呢?
比如arthas-tunnel-server不启动,用了这个命令就没有任何异常情况出现,无法判断是否能注册到server端了,这个问题如何解决?

**Comment by hengyunabc** [comment]
这个参数设计出来就这个作用，不考虑其它的问题。任何操作都有可能失败的。

**Comment by cookiejoo** [comment]
整个web-console的使用心得我已整合到博客上了,欢迎交流经验
https://blog.csdn.net/caodegao/article/details/104016095
