### ISSUE TITLE
我想要监控线上应用所有代码的执行覆盖率，通过一定时间，检测dead code，arthas能实现吗？

### ISSUE THREAD

**Issue by Ted-Engineer** [alibaba/arthas#1011]
我想要监控线上应用所有代码的执行覆盖率，通过一定时间，检测dead code，arthas能实现吗？

**Comment by hengyunabc** [comment]
不能。用 jcoco agent之类的  https://www.eclemma.org/jacoco/trunk/doc/agent.html
