### ISSUE TITLE
生成火焰图输入命令：profiler start，提示：Can not find libasyncProfiler so, please check the arthas directory.

### ISSUE THREAD

**Issue by mayanyun1986** [alibaba/arthas#1012]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: linux centos7.0
* 目标进程的JVM版本: 1.8.0_181
* 执行`arthas-boot`的版本: 3.1.7

如题：提示找不到libasyncProfiler  so，但是安装包目录中有，是需要做什么配置吗？

**Comment by hengyunabc** [comment]
贴出具体的信息，也有一个参数可以指定 so文件加载的。  profiler -h 看下

**Comment by brzone** [comment]
我也发现这样一个问题。
在docker里面，
wiki      https://alibaba.github.io/arthas                                      
tutorials https://alibaba.github.io/arthas/arthas-tutorials                     
version   3.1.7                                                                 
pid       22                                                                    
time      2020-03-17 18:22:50                                                   

[arthas@22]$ profiler start 
/root/.arthas/lib/3.1.7/arthas/async-profiler/libasyncProfiler-linux-x64.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/.arthas/lib/3.1.7/arthas/async-profiler/libasyncProfiler-linux-x64.so)

但是在docker里面确实有文件：
~/.arthas/lib/3.1.7/arthas/async-profiler # pwd
/root/.arthas/lib/3.1.7/arthas/async-profiler
~/.arthas/lib/3.1.7/arthas/async-profiler # ls
libasyncProfiler-linux-x64.so  libasyncProfiler-mac-x64.so
~/.arthas/lib/3.1.7/arthas/async-profiler #

**Comment by hengyunabc** [comment]
> 我也发现这样一个问题。
> 在docker里面，
> wiki https://alibaba.github.io/arthas
> tutorials https://alibaba.github.io/arthas/arthas-tutorials
> version 3.1.7
> pid 22
> time 2020-03-17 18:22:50
> 
> [arthas@22]$ profiler start
> /root/.arthas/lib/3.1.7/arthas/async-profiler/libasyncProfiler-linux-x64.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/.arthas/lib/3.1.7/arthas/async-profiler/libasyncProfiler-linux-x64.so)
> 
> 但是在docker里面确实有文件：
> ~/.arthas/lib/3.1.7/arthas/async-profiler # pwd
> /root/.arthas/lib/3.1.7/arthas/async-profiler
> ~/.arthas/lib/3.1.7/arthas/async-profiler # ls
> libasyncProfiler-linux-x64.so libasyncProfiler-mac-x64.so
> ~/.arthas/lib/3.1.7/arthas/async-profiler #

https://stackoverflow.com/questions/11471722/libstdc-so-6-cannot-open-shared-object-file-no-such-file-or-directory
