### ISSUE TITLE
tt -i 命令结果中，函数的参数 int类型变成Integer类型

### ISSUE THREAD

**Issue by wupflove** [alibaba/arthas#1016]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.8-SNAPSHOT
* Arthas 版本: 3.1.8-SNAPSHOT
* 操作系统版本: WIN10
* 目标进程的JVM版本: 1.8.0_231
* 执行`arthas-boot`的版本:  3.1.8-SNAPSHOT

### 重现问题的步骤

1. java -jar arthas-boot.jar
2. tt -t com.unitspirit.* *
3. tt -i 1019

### 期望的结果

PARAMETERS[0]  @int[12]

### 实际运行的结果

PARAMETERS[0]  @Integer[12]

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

[arthas@4396]$ tt -i 1019
 INDEX          1019
 GMT-CREATE     2020-01-30 10:22:54
 COST(ms)       4.3462
 OBJECT         0x4524411f
 CLASS          com.unitspirit.sqp.tt.samples.Job
 METHOD         doAddpublic
 IS-RETURN      true
 IS-EXCEPTION   false
 PARAMETERS[0]  @Integer[12]
 PARAMETERS[1]  @String[public]
 PARAMETERS[2]  @Long[11]
 PARAMETERS[3]  @Job[
                    log=@Logger[com.unitspirit.sqp.tt.samples.Job:DEBUG in 73d16e93],
                    x=@Integer[1],
                    str=@String[job],
                ]
 PARAMETERS[4]  @Main[
                    log=@Logger[agent.Main:DEBUG in 73d16e93],
                    x=@Integer[1],
                    y=@Integer[2],
                ]
 PARAMETERS[5]  @Double[0.11]
 RETURN-OBJ     @Integer[14]
Affect(row-cnt:1) cost in 5 ms.
把异常信息贴到这里

 PARAMETERS[0]  @Integer[12] 
这个地方源码对应的是int 类型，从tt -i 看过来，类型发生变化

**Comment by hengyunabc** [comment]
因为增强的字节码里，把params等传到后面是Object，最终展示出来就是 Integer了

**Comment by wupflove** [comment]
谢谢
