### ISSUE TITLE
使用watch命令查看方法返回值中文乱码

### ISSUE THREAD

**Issue by KTjinpeng** [alibaba/arthas#1022]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.7
* 操作系统版本: win10 1909
* 目标进程的JVM版本: 1.8.0_191
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1. 在我数据库有一张表我要把数据展示在页面上
2. 使用浏览器查看没有乱码
3. 使用arthas的watch命令返回结果乱码
watch cn.enjoy.service.lmpl.ProductServiceImpl list returnObj

### 期望的结果

看到需要的数据

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
[arthas@18008]$ watch cn.enjoy.service.lmpl.ProductServiceImpl list returnObj
Press Q or Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 28 ms.
ts=2020-02-11 22:14:21; [cost=4.6667ms] result=@ArrayList[
    @Product[Product{productId=1, productName='java缂栫▼', productDesc='springcloud'}],
    @Product[Product{productId=2, productName='Springboot', productDesc='springcloud'}],
    @Product[Product{productId=3, productName='瑗挎父璁?', productDesc='springcloud'}],
    @Product[Product{productId=4, productName='姘存祾浼?', productDesc='springcloud'}],
    @Product[Product{productId=5, productName='瑗垮帰璁?', productDesc='springcloud'}],
    @Product[Product{productId=6, productName='lison-1574404173069', productDesc='springcloud'}],
]
ts=2020-02-11 22:14:22; [cost=1.0976ms] result=@ArrayList[
    @Product[Product{productId=1, productName='java缂栫▼', productDesc='springcloud'}],
    @Product[Product{productId=2, productName='Springboot', productDesc='springcloud'}],
    @Product[Product{productId=3, productName='瑗挎父璁?', productDesc='springcloud'}],
    @Product[Product{productId=4, productName='姘存祾浼?', productDesc='springcloud'}],
    @Product[Product{productId=5, productName='瑗垮帰璁?', productDesc='springcloud'}],
    @Product[Product{productId=6, productName='lison-1574404173069', productDesc='springcloud'}],
]
ts=2020-02-11 22:14:22; [cost=1.0248ms] result=@ArrayList[
    @Product[Product{productId=1, productName='java缂栫▼', productDesc='springcloud'}],
    @Product[Product{productId=2, productName='Springboot', productDesc='springcloud'}],
    @Product[Product{productId=3, productName='瑗挎父璁?', productDesc='springcloud'}],
    @Product[Product{productId=4, productName='姘存祾浼?', productDesc='springcloud'}],
    @Product[Product{productId=5, productName='瑗垮帰璁?', productDesc='springcloud'}],
    @Product[Product{productId=6, productName='lison-1574404173069', productDesc='springcloud'}],
]
ts=2020-02-11 22:14:23; [cost=0.9727ms] result=@ArrayList[
    @Product[Product{productId=1, productName='java缂栫▼', productDesc='springcloud'}],
    @Product[Product{productId=2, productName='Springboot', productDesc='springcloud'}],
    @Product[Product{productId=3, productName='瑗挎父璁?', productDesc='springcloud'}],
    @Product[Product{productId=4, productName='姘存祾浼?', productDesc='springcloud'}],
    @Product[Product{productId=5, productName='瑗垮帰璁?', productDesc='springcloud'}],
    @Product[Product{productId=6, productName='lison-1574404173069', productDesc='springcloud'}],
]
ts=2020-02-11 22:14:31; [cost=1.4142ms] result=@ArrayList[
    @Product[Product{productId=1, productName='java缂栫▼', productDesc='springcloud'}],
    @Product[Product{productId=2, productName='Springboot', productDesc='springcloud'}],
    @Product[Product{productId=3, productName='瑗挎父璁?', productDesc='springcloud'}],
    @Product[Product{productId=4, productName='姘存祾浼?', productDesc='springcloud'}],
    @Product[Product{productId=5, productName='瑗垮帰璁?', productDesc='springcloud'}],
    @Product[Product{productId=6, productName='lison-1574404173069', productDesc='springcloud'}],
]
ts=2020-02-11 22:14:32; [cost=1.2598ms] result=@ArrayList[
    @Product[Product{productId=1, productName='java缂栫▼', productDesc='springcloud'}],
    @Product[Product{productId=2, productName='Springboot', productDesc='springcloud'}],
    @Product[Product{productId=3, productName='瑗挎父璁?', productDesc='springcloud'}],
    @Product[Product{productId=4, productName='姘存祾浼?', productDesc='springcloud'}],
    @Product[Product{productId=5, productName='瑗垮帰璁?', productDesc='springcloud'}],
    @Product[Product{productId=6, productName='lison-1574404173069', productDesc='springcloud'}],
]
ts=2020-02-11 22:14:33; [cost=1.1058ms] result=@ArrayList[
    @Product[Product{productId=1, productName='java缂栫▼', productDesc='springcloud'}],
    @Product[Product{productId=2, productName='Springboot', productDesc='springcloud'}],
    @Product[Product{productId=3, productName='瑗挎父璁?', productDesc='springcloud'}],
    @Product[Product{productId=4, productName='姘存祾浼?', productDesc='springcloud'}],
    @Product[Product{productId=5, productName='瑗垮帰璁?', productDesc='springcloud'}],
    @Product[Product{productId=6, productName='lison-1574404173069', productDesc='springcloud'}],
]
ts=2020-02-11 22:14:33; [cost=0.9465ms] result=@ArrayList[
    @Product[Product{productId=1, productName='java缂栫▼', productDesc='springcloud'}],
    @Product[Product{productId=2, productName='Springboot', productDesc='springcloud'}],
    @Product[Product{productId=3, productName='瑗挎父璁?', productDesc='springcloud'}],
    @Product[Product{productId=4, productName='姘存祾浼?', productDesc='springcloud'}],
    @Product[Product{productId=5, productName='瑗垮帰璁?', productDesc='springcloud'}],
    @Product[Product{productId=6, productName='lison-1574404173069', productDesc='springcloud'}],
]
```
把异常信息贴到这里
```

**Comment by kylixs** [comment]
请参考 #950 
> 这个问题是watch 方法参数值包含中文时，输出到shell显示乱码
> 建议使用Arthas telnet client并设置为UTF-8编码，启动命令：
> java -Dfile.encoding=UTF-8 -jar arthas-boot.jar
> java -Dfile.encoding=UTF-8 -jar arthas-boot.jar <pid>
