### ISSUE TITLE
support yaml configuration 

### ISSUE THREAD

**Issue by Roger3581321** [alibaba/arthas#1027]
由于.yaml较流行，很多工程师在使用，更友好。

用户配置也可以写在.yaml中，进行二次开发。
参考spring boot中的：
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-yaml

(项目其他地方也可以使用yaml配置，利用snakeYaml解析)

**Comment by hengyunabc** [comment]
这个要增加新的依赖。对于java应用来说，properties还是最常用的配置方式。有必要才考虑加yaml的支持。

**Comment by Roger3581321** [comment]
OK
