### ISSUE TITLE
dump -E这个参数怎么使用，没有看懂

### ISSUE THREAD

**Issue by aitangyong** [alibaba/arthas#1028]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： as.sh
* Arthas 版本: 3.1.7
* 操作系统版本: centos
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1. dump -E 这个正则是做什么的呢？什么场景下有用呢
2. 如果只是dump符合条件的类，class-pattern也支持

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
`dump -h ` 帮助信息和wiki文档都很清楚，表示用正则表达式来匹配。

**Comment by aitangyong** [comment]
> `dump -h ` 帮助信息和wiki文档都很清楚，表示用正则表达式来匹配。

dump -E org\\.slf4j\\.*  这个命令会报错，提示没有传class-pattern
dump org.slf4j.* 先忽略超过了默认的限制5个的问题，这个class-pattern已经是正则了。

也就是说如果我想导出符合条件的类字节码，完全可以通过class-pattern实现，那-E指定的正则又是做啥呢？

**Comment by hengyunabc** [comment]
> > `dump -h ` 帮助信息和wiki文档都很清楚，表示用正则表达式来匹配。
> 
> dump -E org\.slf4j\.* 这个命令会报错，提示没有传class-pattern
> dump org.slf4j.* 先忽略超过了默认的限制5个的问题，这个class-pattern已经是正则了。
> 
> 也就是说如果我想导出符合条件的类字节码，完全可以通过class-pattern实现，那-E指定的正则又是做啥呢？

这里的确有问题，是上游cli依赖的bug，加上`flag=true` 才能生效。 目前要显式配置，比如 

```
dump -E true org\\.apache\\.commons\\.lang\\.StringUtils
```

默认只是 `.`, `*` 的通配，并不是正则。

**Comment by aitangyong** [comment]
好的感谢解答，我的疑问已解决！后续可以修复这个问题，3.1.7文档上可以备注下
