### ISSUE TITLE
Support print PerfCounter

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1029]
```
jcmd $pid PerfCounter.print
```

**Comment by Roger3581321** [comment]
您好，横云老师，
   我调查了下，官方的tool sun.tools.jcmd.JCmd中main方法（传入pid，PerfCounter.print）可以实现功能，但是返回值是void，输出到console。如果要实现arthas支持jcmd，由于JCmd类中其他方法都为private，可能要考虑开源实现jcmd。
