### ISSUE TITLE
有没有简洁的命令查询最占内存的对象，以及实例数很多且每个对象内存很大的对象。

### ISSUE THREAD

**Issue by hegphegp** [alibaba/arthas#1035]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

* 线上系统，事先是不知道哪些对象哪些方法占内存，占CPU，用 monitor、watch、trace、stack  这些命令，要输入类路径，类名称。但是事先不知道是哪些类，只能盲人摸石过河，一个个去试，效率很低，运维人员很痛苦，看到眼睛都花，脑袋晕了，客户拼命地催，有时候三更半夜了，分析了几个小时，找不到问题，人都崩溃了。

**Comment by hengyunabc** [comment]
搞错方向了，headdump，然后找个软件分析。 arthas没办法分析jvm内存。
