### ISSUE TITLE
如何使用xterm.js发送命令

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/arthas#1037]
xterm.js 怎么发送命令的.是不是还需要attach.js这个文件?我看xterm.js要安装才能用,但是我们没有arthas-tunnel-server的页面文件源码.
我的需求是屏蔽掉手工输入项,做一些功能提供按钮即可.
我想弄一个根据按钮点击去发送命令,我调用xterm.write(cmd);没事用,只是打印到黑板上而已.
![image](https://user-images.githubusercontent.com/3397316/75332348-320e0980-58bf-11ea-9b95-a0fc3ecdfc46.png)

**Comment by cookiejoo** [comment]
已解决

**Comment by leslie199212** [comment]
怎么解决的？

**Comment by cookiejoo** [comment]
> 怎么解决的？

ws.send()方法就是,只是要拼接 \n 等于回车一起发送过去
