### ISSUE TITLE
使用jad  --source-only 反编译，用mc编译报错

### ISSUE THREAD

**Issue by gaonico** [alibaba/arthas#1039]
[arthas@131]$ mc -c 18b4aac2 tmp/CoreOrderService.java -d tmp
Memory compiler error, exception message: Compilation Error
line: 234 , message: illegal start of expression ,
line: 234 , message: illegal start of expression ,
line: 234 , message: ';' expected ,
line: 234 , message: not a statement ,
line: 234 , message: ';' expected ,
line: 273 , message: illegal start of expression ,
line: 279 , message: illegal start of expression ,
line: 288 , message: illegal start of expression ,
line: 297 , message: illegal start of expression ,
line: 312 , message: illegal start of expression ,
line: 315 , message: illegal start of expression ,
line: 316 , message: illegal start of expression ,
line: 318 , message: illegal start of expression ,
line: 320 , message: illegal start of expression ,
line: 360 , message: illegal start of expression ,
line: 369 , message: illegal start of expression ,
line: 383 , message: illegal start of expression ,
line: 384 , message: illegal start of expression ,
line: 423 , message: illegal start of expression ,
line: 423 , message: illegal start of expression ,
line: 423 , message: ';' expected ,
line: 424 , message: ']' expected ,
line: 424 , message: illegal start of expression ,
line: 500 , message: illegal start of expression ,
line: 501 , message: illegal start of expression ,
line: 502 , message: illegal start of expression ,
line: 514 , message: illegal start of expression ,
line: 515 , message: illegal start of expression ,
line: 525 , message: illegal start of expression ,
line: 528 , message: illegal start of expression ,
line: 529 , message: illegal start of expression ,
line: 530 , message: illegal start of expression ,
line: 541 , message: illegal start of expression ,
line: 553 , message: illegal start of expression ,
line: 554 , message: illegal start of expression ,
line: 555 , message: illegal start of expression ,
line: 562 , message: illegal start of expression ,
line: 585 , message: illegal start of expression ,
line: 586 , message: illegal start of expression ,
line: 587 , message: illegal start of expression ,
line: 590 , message: illegal start of expression ,
line: 591 , message: illegal start of expression ,
line: 620 , message: illegal start of expression ,
line: 621 , message: illegal start of expression ,
line: 646 , message: illegal start of expression ,
line: 647 , message: illegal start of expression ,
line: 648 , message: illegal start of expression ,
line: 649 , message: illegal start of expression ,
line: 650 , message: illegal start of expression ,
line: 651 , message: illegal start of expression ,
line: 688 , message: illegal start of expression ,
line: 689 , message: illegal start of expression ,
line: 690 , message: illegal start of expression ,
line: 691 , message: illegal start of expression ,
line: 692 , message: illegal start of expression ,
line: 704 , message: illegal start of expression ,
line: 705 , message: illegal start of expression ,
line: 757 , message: ')' expected ,
line: 757 , message: ';' expected ,
line: 757 , message: ';' expected ,
line: 757 , message: ')' expected ,
line: 757 , message: illegal start of expression ,
line: 757 , message: ';' expected ,
line: 757 , message: not a statement ,
line: 757 , message: ';' expected ,
line: 757 , message: not a statement ,
line: 757 , message: illegal start of expression ,
line: 757 , message: not a statement ,
line: 757 , message: ';' expected ,
line: 757 , message: not a statement ,
line: 757 , message: ';' expected ,
line: 757 , message: not a statement ,
line: 757 , message: ';' expected ,
line: 769 , message: illegal start of expression ,
line: 769 , message: illegal start of expression ,
line: 769 , message: ';' expected ,
line: 769 , message: not a statement ,
line: 769 , message: ';' expected ,
line: 776 , message: ')' expected ,
line: 776 , message: ';' expected ,
line: 776 , message: ';' expected ,
line: 776 , message: ')' expected ,
line: 776 , message: illegal start of expression ,
line: 776 , message: ';' expected ,
line: 776 , message: not a statement ,
line: 776 , message: ';' expected ,
line: 776 , message: not a statement ,
line: 776 , message: illegal start of expression ,
line: 776 , message: not a statement ,
line: 776 , message: ';' expected ,
line: 776 , message: not a statement ,
line: 776 , message: ';' expected ,
line: 776 , message: not a statement ,
line: 776 , message: ';' expected ,
line: 784 , message: ')' expected ,
line: 784 , message: ';' expected ,
line: 784 , message: ';' expected ,
line: 784 , message: ')' expected ,
line: 784 , message: illegal start of expression ,
line: 784 , message: ';' expected ,

**Comment by hengyunabc** [comment]
https://arthas.gitee.io/mc
