### ISSUE TITLE
profiler 输出的html结果文件为空

### ISSUE THREAD

**Issue by nicegdhj** [alibaba/arthas#1040]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.7
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. profiler start --event alloc
2. 等待5分钟
3. profiler stop --file /tmp/result.html 

### 期望的结果

/tem目录下应该有alloc信息的文件result.html

### 实际运行的结果
-rw-r----- 1 hadoop      hadoop        0 Mar  1 21:47 result.html

result.html 文件内容为空的

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
因为数据是采样到的，所以可能要等一段时间才能采到结果。如果程序本身没负载的话，也可能没数据。
