### ISSUE TITLE
Feature request tunnel-server 支持浏览 flamegraph

### ISSUE THREAD

**Issue by athom** [alibaba/arthas#1041]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 目的和构思
profiler的火焰图功能很实用, 但是生成的图片保存在本机, 预览比较麻烦, 需要scp出来. 
如果在容器里面, 则更麻烦. 
为了方便使用体验, 有两个思路可以改善
1. 在tunnel-server集成对保存火焰图的目标机器打通访问, 使得可以在tunnel-server有地方可以预览图片
2. profiler 增加上传功能, 可以把图片传输到tunnel-server的静态目录下
3. profiler 增加传输到s3, oss, cos之类的地方的命令, 如果不介意信息安全, 甚至可以配置一些免费的第三方图床, 上传成功在终端打印地址, 即可快速访问, 查看效果. 这个可能需要目标的环境具备可以访问外网的条件

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: `Linux version 4.19.76-linuxkit (root@d203b39a3d78) (gcc version 8.3.0 (Alpine 8.3.0)) #1 SMP Thu Oct 17 19:31:58 UTC 2019`
* 目标进程的JVM版本: 
```
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10, mixed mode)
```
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤
1. 目标机器进行profiler
2. profiler stop之后,把结果保存到目标机器的目录
3. 目标机器访问 http://xxxx: 3658 可以查看刚生成的火焰图图片, 但是通过tunnel-server却不行

### 期望的结果

tunnel-server可以访问到目标机器生成的火焰图图片

### 实际运行的结果

tunnel-server不可以访问到目标机器生成的火焰图图片

**Comment by hengyunabc** [comment]
这个需求的确存在。这个要求 tunnel server实现 http的反向代理，有点复杂。

**Comment by hengyunabc** [comment]
已经支持了。
