### ISSUE TITLE
tunnel-server无法注册到不同的IP服务端

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/arthas#1042]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: c-6
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1. 执行java -jar /home/q/arthas/arthas-boot.jar 7 --tunnel-server 'ws://10.145.40.200:7777/ws' --agent-id '10.209.154.219'
10.145.40.200是arthas-tunnel-server的服务,容器化部署,ip会有变化.

2. 10.209.154.219是目标机器,想诊断这台机器的性能.

3. 问题是第一次注册到arthas-tunnel-server没问题,可以在页面中使用,但如果我重建了arthas-tunnel-server服务端,ip就变了,再次到10.209.154.219这台机器注册到新IP的arthas-tunnel-server,显示是注册成功的,但是新arthas-tunnel-server控制台只提示无法连接.
![image](https://user-images.githubusercontent.com/3397316/75757444-565d6080-5d6d-11ea-8971-1ed1d25e420f.png)
打开actuator/arthas 确实也没有agent注册进来.
{"clientConnections":{},"version":null,"properties":{"server":{"host":null,"port":7777,"ssl":false}},"agents":{}}

4. 如果我在10.209.154.219这台机器再次执行命令,进入arthas-boot控制台,然后执行stop命令后,才能正常再次注册到新的arthas-tunnel-server服务端.

这个问题是,一旦注册了一个服务端了,没有执行过stop,这台机器就无法再次注册到其他的server机器了.

### 期望的结果

能够支持注册到不同的IP,或者有没有其他办法,我在执行注册之前可以先清理缓存什么的,或者先执行stop命令杀掉有可能已经注册过的server段IP.
好像也不支持java -jar arthas-boot.jar --stop这种命令

**Comment by hengyunabc** [comment]
。。 tunnel-server ip当然要固定，或者配置一个域名，哪有什么都是动态化的。。 写代码的人肯定不会考虑这种什么都要动态改变的需求。

**Comment by cookiejoo** [comment]
> 。。 tunnel-server ip当然要固定，或者配置一个域名，哪有什么都是动态化的。。 写代码的人肯定不会考虑这种什么都要动态改变的需求。

域名吗,可以,我试试.

**Comment by cookiejoo** [comment]
> 。。 tunnel-server ip当然要固定，或者配置一个域名，哪有什么都是动态化的。。 写代码的人肯定不会考虑这种什么都要动态改变的需求。

我试了一下域名,也不行,因为容器下的实例ip是会变的.
但我认为这也不合理,因为我注册到那台机器就算是固定ip,也可能会机器坏掉的情况,到时候也会换其他机器部署.
为何不支持换ip呢?不要注册一个就只能在这个server上使用啊.
就像我登录了一个账号,如果我在另外一台机器上登录,可以把之前的踢下线.
你觉得呢?

**Comment by cookiejoo** [comment]
> 。。 tunnel-server ip当然要固定，或者配置一个域名，哪有什么都是动态化的。。 写代码的人肯定不会考虑这种什么都要动态改变的需求。

已找到stop的方式,我的解决方法是调用arthas-client.jar的命令先执行stop,再开启新的注册.这样内存就没久的信息滞留了.
