### ISSUE TITLE
得亏了arthas，我才把潜藏那么深的Bug挖出来

### ISSUE THREAD

**Issue by yinjihuan** [alibaba/arthas#1043]
使用经验分享：http://cxytiandi.com/blog/detail/36435

**Comment by hengyunabc** [comment]
最好是把完整的文章贴过来，方便直接查看。

**Comment by xindoo** [comment]
我们也是用arthas挖出来一个jdk11 zgc的性能bug，不过这个bug已经不是我们首发了

**Comment by hengyunabc** [comment]
> 我们也是用arthas挖出来一个jdk11 zgc的性能bug，不过这个bug已经不是我们首发了

欢迎写文章分享:）

**Comment by goldpumpkin** [comment]
> 使用经验分享：http://cxytiandi.com/blog/detail/36435

看了你的文章想问一下，没有引入第三方jar包，那编译这么通过的呢？IDE都会都有红线吧？
