### ISSUE TITLE
批处理时执行classloader,返回信息丢失

### ISSUE THREAD

**Issue by LillianChen** [alibaba/arthas#1046]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: Linux alios7.x86_64
* 目标进程的JVM版本: 1.8.0_212
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1. 创建 test.as，内容：classloader
2. 批处理方式执行 sh as.sh <pid> -b -f test.as
3. 查看输出

### 期望的结果

![image](https://user-images.githubusercontent.com/440962/75955591-22ab4380-5ef1-11ea-8c3e-e861572bf36b.png)

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
![image](https://user-images.githubusercontent.com/440962/75955539-fd1e3a00-5ef0-11ea-84d8-b09e20151e72.png)

实例和加载类数量的信息全部丢失。怀疑是有特殊字符导致不输出。

**Comment by kylixs** [comment]
这个问题与terminal终端宽度有关，可以在命令行设置显示宽度，如： 
`./as.sh --width 160  -f test.as  <pid>`
