### ISSUE TITLE
as.sh -b 批处理参数解析异常

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1048]
- [ Y] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* 操作系统版本: windows 10 + git bash
* 目标进程的JVM版本: jdk 1.8 212
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1、执行失败的命令：
./as.sh -b --width 50 -f test.as 27328

2、调整参数顺序，将-b 放到pid后执行成功
./as.sh --width 50 -f test.as 27328  -b

### 期望的结果

What do you expected from the above steps？
期望可以正确注入目标JVM进程
![image](https://user-images.githubusercontent.com/5483385/75973387-079bfc00-5f10-11ea-92f6-7125518b6a88.png)

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
出现注入失败的错误，提示pid解析错误： The value '-b' is not accepted by 'pid'
![image](https://user-images.githubusercontent.com/5483385/75973227-cc013200-5f0f-11ea-8da5-e15f40fb3d6f.png)

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
已修复，参考： https://github.com/alibaba/arthas/issues/1072
