### ISSUE TITLE
关于restful-api 功能的计划

### ISSUE THREAD

**Issue by shellsniper** [alibaba/arthas#1051]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

关注这个项目很久了，功能十分强大，感谢你们的付出！我想了解一下贵项目今后有没有开发基于 MVC 的 restful-api 功能的计划？如果有 restful-api，在一些测试项目中就可以更加灵活使用。谢谢！

**Comment by hengyunabc** [comment]
规划中，开始部分代码了。

**Comment by hengyunabc** [comment]
参考： https://arthas.aliyun.com/doc/http-api.html
