### ISSUE TITLE
返回错误的 content-type，导致Edge浏览器访问arthas-output页面异常

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1052]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.8
* Arthas 版本: 3.1.8
* 操作系统版本: windows 10 + Microsoft Edge 44.18362.449.0
* 目标进程的JVM版本: jdk1.8.0_212
* 执行`arthas-boot`的版本: 3.1.8

### 重现问题的步骤

1. 在Edge中打开链接http://localhost:3658/arthas-output/ 或 http://localhost:8563/arthas-output/

### 期望的结果

What do you expected from the above steps？

期望显示文件浏览页面

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
浏览器提示打开或者下载文件，没有打开页面。
![image](https://user-images.githubusercontent.com/5483385/76393564-c2177d00-63ae-11ea-841b-a1225617e986.png)

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
打开调试窗口，看下是否 `content-type: content-type: text/html; charset=utf-8`。
