### ISSUE TITLE
在使用trace跟踪某个方法的内部调用时间时，有些方法没有跟踪到，这个应该怎么解决？

### ISSUE THREAD

**Issue by hezhiqiang** [alibaba/arthas#1053]
在使用trace跟踪某个方法的内部调用时间时，有些方法没有跟踪到，这个应该怎么解决？

**Comment by hezhiqiang** [comment]
如果能够跟踪多层调用就更好了~

**Comment by hengyunabc** [comment]
trace 只有一层，在 issue里搜下。trace都是有代价的。

**Comment by wrkaiser** [comment]
同问，我在跟踪ElasticSearch中自己实现的插件中的方法时，能trace上，但是请求调用的时候，没有打印调用栈和cost（我确定该方法实际被调用了），官方同学有遇到过这种情况么？

**Comment by hengyunabc** [comment]
@wrkaiser es 有权限问题，最好试下把 security 的配置全去掉再跑

**Comment by useraddZYB** [comment]
> 如果能够跟踪多层调用就更好了~

看下这个
https://github.com/useraddZYB/time-tracker

**Comment by hengyunabc** [comment]
@useraddZYB 大哥，别来打广告了。用户自己会用脚投票。

**Comment by useraddZYB** [comment]
@hengyunabc 别激动，只是就事论事提供个参考方案，希望能帮助解决这种问题而已。觉得是打广告，以后不回复了就是。

**Comment by hengyunabc** [comment]
> @hengyunabc 别激动，只是就事论事提供个参考方案，希望能帮助解决这种问题而已。觉得是打广告，以后不回复了就是。

1. 你发这个不止一次了，超码5次以上
2. 就算你要打宣传，也应该去类似静态理点的社区去宣传
3. 你直接在项目里“对比”arthas，arthas是一个运行时诊断工具，和静态理点工具差十万八千里。你应该对比的是 zipkin , skywalking之类的。
4. 好项目用户自己会用脚投票，而不是去别的社区打广告

自己在项目里这样子写，还好意思来打广告，我也是服了。

![image](https://user-images.githubusercontent.com/1683936/78775759-57fff100-79c9-11ea-97a1-9d9f8348aacc.png)

**Comment by useraddZYB** [comment]
@hengyunabc 您的疑问，我挨个回复下。我也认识到这么回复欠妥，承诺不回复了
1，发几次我不清楚，我是看对于trace的使用场景疑问的issue，也确实是为了优化我的项目，遇到非常对口的我回复过。我印象中两三次
2、3，你说的对，我确实在最开始就做了，提过建议，不是什么宣传。其次，为什么在arthas里回复，是因为确实有同行们会有这类问题这类需求，我知道跟arthas不是一类东西，但是提供了trace，用户又有需求，而需求在某些场景不是很好满足，所以我只针对这个场景回复。
4，不是要争什么，你别激动，只是解决问题
5，我项目里的评论，就是我对arthas的认识，我也用它解决过一个特殊场景的问题。开源项目，可以评论吧，不能只认褒奖吧？也是建议，希望能够整合一些，建议对不对收不收另说
