### ISSUE TITLE
WebConsole中如果能复制粘贴就更棒了~

### ISSUE THREAD

**Issue by hezhiqiang** [alibaba/arthas#1056]
WebConsole中如果能复制粘贴就更棒了~

**Comment by hengyunabc** [comment]
说明具体的浏览器，os。 试下chrome

**Comment by hezhiqiang** [comment]
用的是QQ浏览器~

**Comment by tonylit** [comment]
chrome浏览器 +1，需求复制

**Comment by lixueyu001** [comment]
webconsole的复制粘贴需要快捷键：复制Ctrl+Insert/粘贴Shift+Insert 或Ctrl+Shift+c/Ctrl+Shift+v

**Comment by kylixs** [comment]
Windows 10 + Chrome 80 下验证结果：
鼠标选择文字，Ctrl+Insert可以复制，但Ctrl+Shift+c与Chrome快捷键冲突，不能使用。
Shift+Insert  或者 Ctrl+Shift+v 都可以粘贴内容

**Comment by kylixs** [comment]
操作环境：macOS 10.15.4 + Chrome 81
两种复制粘贴的快捷键都无效
Ctrl+Insert / Shift+Insert， Ctrl+Shift+c/Ctrl+Shift+v都无效

**Comment by sunchanglei** [comment]
arthas 怎么不退出切换监控目标进程呀？
