### ISSUE TITLE
使用monitor命令正则匹配类后会导致字节码增强错误

### ISSUE THREAD

**Issue by AIFEINIK** [alibaba/arthas#1057]
1. 问题原因：如下执行monitor命令，class-pattern参数通过正则匹配，命令执行后可以输出正确的具体观察结果，但是当stop后，会导致原有代码操作异常问题，通过reset重置还原被增强的类也无法解决，只能通过重新编译源代码。
$ monitor \*TradeOrder\* \*search\*

**Comment by hengyunabc** [comment]
最好有可以重现的demo
