### ISSUE TITLE
启动arthas 出错

### ISSUE THREAD

**Issue by rbscau** [alibaba/arthas#1058]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本:  3.1.7
* 操作系统版本: redhat7.0
* 目标进程的JVM版本: 1.7.0_51
* 执行`arthas-boot`的版本:  3.1.7

### 重现问题的步骤

1.  ps -ef | grp java  
找对对应的java进程号
2. java -jar arthas-boot.jar [进程号]

### 期望的结果
启动arthas

### 实际运行的结果
出错，命令行回显如下：

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
命令行回显
[INFO] arthas-boot version: 3.1.7
[ERROR] Can not read maven-metadata.xml from: http://repo1.maven.org/maven2/com/taobao/arthas/arthas-packaging/maven-metadata.xml
[ERROR] Can not find Arthas under local: /root/.arthas/lib and remote maven repo mirror: center
[ERROR] Unable to download arthas from remote server, please download the full package according to wiki: https://github.com/alibaba/arthas

**Comment by hengyunabc** [comment]
网络不通，直接下载全量包，解压使用。
