### ISSUE TITLE
Jad反编译可以显示行号吗

### ISSUE THREAD

**Issue by xjt2016** [alibaba/arthas#1061]
Jad反编译可以显示行号吗

**Comment by liuzhengyang** [comment]
我有点好奇，显示行号需求是显示反编译后的代码在源文件中的行号，还是在显示出反编译的代码的每一行在当前反编译结果里的行位置。我最近做了一个工具用[Procyon](https://bitbucket.org/mstrobel/procyon/wiki/Home) 可以获取到一部分行号信息。
![image](https://user-images.githubusercontent.com/7070174/76956886-cebc4800-694f-11ea-8bf4-2b16d49ebb24.png)

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/1

**Comment by xjt2016** [comment]
这个是有需求场景的，毕竟线上出问题的逻辑行号，可能在版本机源码当中，早就被更新掉了，如果要下载生产环境的jar到本地编译，那工作量并没有减少
