### ISSUE TITLE
CPU 1000%+

### ISSUE THREAD

**Issue by zhongshan0525** [alibaba/arthas#1062]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：
* Arthas 版本: 最新
* 操作系统版本: 阿里ecs
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: 最新

### 重现问题的步骤

1. CPU跑一断程序就飙高
![image](https://user-images.githubusercontent.com/3916061/76955948-16da6b00-694e-11ea-9103-ce2aa5af886c.png)
![image](https://user-images.githubusercontent.com/3916061/76955985-278ae100-694e-11ea-90cf-15e8b654dd49.png)

![image](https://user-images.githubusercontent.com/3916061/76956011-32457600-694e-11ea-9726-c6d367a542a1.png)
![image](https://user-images.githubusercontent.com/3916061/76956022-37a2c080-694e-11ea-9458-20965279a5ec.png)

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
24core
```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
没看出怎么 1000% 了。 统计的线程百分比是jvm内部的，并非OS线程的。
