### ISSUE TITLE
如何查看一个java类有几个实例化对象

### ISSUE THREAD

**Issue by youmustbekiddingme** [alibaba/arthas#1064]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本:win10
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

如何查看一个java 类 有几个实例化对象？？？

**Comment by hengyunabc** [comment]
没有这功能。可以heapdump后用工具分析， OQL 语句查询。

**Comment by youmustbekiddingme** [comment]
tks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hengyunabc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月21日(星期六) 凌晨0:36
收件人:&nbsp;"alibaba/arthas"<arthas@noreply.github.com&gt;;
抄送:&nbsp;"孔雀东南飞"<545018520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/arthas] 如何查看一个java类有几个实例化对象 (#1064)





 
没有这功能。可以heapdump后用工具分析， OQL 语句查询。
