### ISSUE TITLE
通过tunnle server使用arthas，怎么上传class文件到服务器

### ISSUE THREAD

**Issue by hezkvectory** [alibaba/arthas#1066]
现在无法登录到服务器，请问怎么上传class文件，tunnle server能通过agentid连接使用

**Comment by hezkvectory** [comment]
能否支持 echo > index.txt << EOF这样的操作

**Comment by hengyunabc** [comment]
现在利用 echo命令应该是可以传文件的，不过就是有点邪恶。   echo "xxx" > /tmp/test.txt
