### ISSUE TITLE
采用Arthas和采用Java提供的命令数据不一致

### ISSUE THREAD

**Issue by mgljava** [alibaba/arthas#1068]
-  我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar`
* Arthas 版本: 3.1.7
* 操作系统版本: Linux 3.10.0-957.el7.x86_64
* 目标进程的JVM版本: 1.8.0_221

在使用JDK提供的jstat命令时
![image](https://user-images.githubusercontent.com/17683844/77392419-d8bdcb00-6dd5-11ea-9009-0947bf788c73.png)

在使用Arthas诊断JVMGC时
![image](https://user-images.githubusercontent.com/17683844/77392504-115da480-6dd6-11ea-898c-af2191b48ced.png)

GC日志统计结果不一致，从jstat统计的结果来看，YGC发生了3890次，而Arthas统计只发生了86次。FGC也不对。是由于统计的时间段不同引起的么？

**Comment by hengyunabc** [comment]
jvm本身数据可能也会不一样，参考 DashboardCommand.java ，是通过jmx获取到的数据。
