### ISSUE TITLE
提供一个新的命令，反编译结果支持行号，只支持jdk 8；或者把原来的jad命令命名为别的，仍然支持jdk6

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1073]

**Comment by lzc-alioo** [comment]
arthas目前使用的是cfr反编译工具,而cfr命令中我没有找到反编译显式行号的参数呢

**Comment by hengyunabc** [comment]
> arthas目前使用的是cfr反编译工具,而cfr命令中我没有找到反编译显式行号的参数呢

cfr 目前不支持行号，所以要考虑别的反编译库。
