### ISSUE TITLE
技术征文 | 那些年，我用 Arthas 排查过的问题

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1079]
![640](https://user-images.githubusercontent.com/1683936/77732005-f9d52480-703e-11ea-84dc-02faa546b86b.jpg)

为了让更多开发者开始用上 Arthas 这个Java 诊断神器，这一次我们联合 JetBrains 推出这次有奖征文活动，聊聊这些年你和 Arthas 之间的那些事儿。第一期征文活动将于 3 月 26 日 —— 4 月 26 日举办，后续征文活动将持续至 2020 年 12 月。

在此次活动中，大家可以尽情表达自己的声音，你可以将使用 Arthas 过程中积累的经验及感悟整理成一篇文章分享给大家，或者也可以把你对 Arthas 提出的建议汇总成稿给到我们，我们将在多个渠道发布。当然更欢迎你直接参与 Arthas 开源贡献，star 一下，成为社区的 Contributor！

* https://mp.weixin.qq.com/s/gJ4ZVvFBuiXbirjTxjwGeQ
* https://developer.aliyun.com/article/751641

**Comment by yunzhongfan** [comment]
Arthas 能查询特定入参的方法，方法栈调用耗时吗

**Comment by yhf20071** [comment]
[利用Arthas解决启动StandbyNameNode加载EditLog慢的问题 #1566](https://github.com/alibaba/arthas/issues/1566)

**Comment by jujunchen** [comment]
[SBA集成Arthas实践](https://github.com/alibaba/arthas/issues/1601)

**Comment by password36** [comment]
- [SBA2.0版本集成实践](http://21.129.49.2:10080/)https://github.com/alibaba/arthas/issues/1736#issue-831683781

**Comment by hengyunabc** [comment]
@password36 直接到这里提交哈： http://alibabacloud.mikecrm.com/9khcRrs 。

另外可以在QQ群/钉钉群 联系下我们不？ https://arthas.aliyun.com/doc/contact-us.html

**Comment by 18310781743** [comment]
arthas连接springboot项目源码解析
https://blog.csdn.net/weixin_45191798/article/details/112061851

**Comment by yjqg6666** [comment]
利用Arthas 动态调整Pinpoint的采样率 reference: https://github.com/pinpoint-apm/pinpoint/pull/8002

**Comment by yjqg6666** [comment]
利用Arthas 动态调整Pinpoint采样率 https://github.com/pinpoint-apm/pinpoint/pull/8002
