### ISSUE TITLE
jdk8/maven3.6.1/ agent 和core  MANIFEST.MF 文件相关属性不能正确写入

### ISSUE THREAD

**Issue by javazhangyi** [alibaba/arthas#1081]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 重现问题的步骤

1. jdk8
2.maven3.6.1
3.idea
4.windos10直接构建

### 期望的结果

arthas-agent 生成的 MANIFEST.MF缺少：
                       <Premain-Class>com.taobao.arthas.agent.AgentBootstrap</Premain-Class>
                       <Agent-Class>com.taobao.arthas.agent.AgentBootstrap</Agent-Class>
                       <Can-Redefine-Classes>true</Can-Redefine-Classes>
                       <Can-Retransform-Classes>true</Can-Retransform-Classes>

arthas-core生成的 MANIFEST.MF缺少：
                        <mainClass>com.taobao.arthas.core.Arthas</mainClass>

                                    

```
把异常信息贴到这里
```

 arthas-core 生成的MANIFEST.MF

Manifest-Version: 1.0
Implementation-Title: arthas-core
Implementation-Version: 3.1.8-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: zy
Specification-Title: arthas-core
Implementation-Vendor-Id: com.taobao.arthas
Created-By: Apache Maven 3.6.1
Build-Jdk: 1.8.0_152
Specification-Version: 3.1.8-SNAPSHOT

 arthas-agent生成的MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: arthas-agent
Implementation-Version: 3.1.8-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: zy
Specification-Title: arthas-agent
Implementation-Vendor-Id: com.taobao.arthas
Created-By: Apache Maven 3.6.1
Build-Jdk: 1.8.0_152
Specification-Version: 3.1.8-SNAPSHOT

**Comment by hengyunabc** [comment]
没有windows的环境，可以试下装一个 cygwin ，然后用 as-package.sh 来打包
