### ISSUE TITLE
使用premain方式加载arthas-agent

### ISSUE THREAD

**Issue by thineagle** [alibaba/arthas#1083]
如果我选择使用-javaagent方式加载arthas，有相关资料可参考吗

**Comment by hengyunabc** [comment]
目前没有支持，后面会支持，已在开发计划里。

**Comment by thineagle** [comment]
有大概的时间点吗？ 准备用这种方式集成arthas，可以进行相关方面的测试

**Comment by Bruce012356** [comment]
我看com.taobao.arthas.agent.AgentBootstrap#premain
方法有这种能力，是不是编译出agent的jar，使用-javaagent参数随应用启动就可以了；

**Comment by hengyunabc** [comment]
已经 支持，测试版本： [arthas-3.1.9-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/4458082/arthas-3.1.9-SNAPSHOT-bin.zip)

解压之后，`java -javaagent:/tmp/test/arthas-agent.jar` 指定agent就可以了。 默认的配置在 arthas.properties 里。

**Comment by thineagle** [comment]
好的， 我们开始测试下
