### ISSUE TITLE
使用疑问: 有可能实现热更新增加method/class吗？

### ISSUE THREAD

**Issue by levoncf** [alibaba/arthas#1087]
在实际使用过程中有时候如果能热更新method会更加方便，比如Jrebel可以实现热更新method的功能。从技术的角度来说，这个功能可能实现吗？

谢谢！

**Comment by hengyunabc** [comment]
`redefine -h ` ，目前只支持类。 只更新某个method是可行的，不过有点复杂，暂时没做。

**Comment by levoncf** [comment]
嗯嗯，其实我的意思是从技术角度上来说能否支持 在反编译后的class中 新增method， 然后进行热更新？当前版本如果新增method的话会报错class redefinition failed: attempted to add a method

**Comment by hengyunabc** [comment]
> 嗯嗯，其实我的意思是从技术角度上来说能否支持 在反编译后的class中 新增method， 然后进行热更新？当前版本如果新增method的话会报错class redefinition failed: attempted to add a method

新增method是不现实的，jrebel是非常复杂的改装了class达到的，可以搜下相关的原理文章。

**Comment by levoncf** [comment]
好的 我去了解下 谢谢！
