### ISSUE TITLE
代码修改建议

### ISSUE THREAD

**Issue by zhengb0** [alibaba/arthas#1091]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

arthas/boot/src/main/java/com/taobao/arthas/boot/DownloadUtils.java
146行的(String) 强转没有意义，因为143行的List<String> values

**Comment by hengyunabc** [comment]
欢迎提 PR修复~

**Comment by zhengb0** [comment]
> 欢迎提 PR修复~

好的
