### ISSUE TITLE
pid choose wrong

### ISSUE THREAD

**Issue by Glaha** [alibaba/arthas#1092]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.8
* Arthas 版本: 3.1.8
* 操作系统版本: 
Linux version 4.12.14-150.47-default (geeko@buildhost) (gcc version 7.4.1 20190905 [gcc-7-branch revision 275407] (SUSE Linux) ) #1 SMP Wed Dec 18 15:05:52 UTC 2019 (8162e25)
* 目标进程的JVM版本:  
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)

* 执行`arthas-boot`的版本: 3.1.8

### 重现问题的步骤

1. ps -ef|grep java
bash-4.4$ ps -ef|grep java
appuser       1      0  1 08:35 ?        00:00:27 java -jar xxxxxxx
appuser     209      1  0 08:44 ?        00:00:01 java -jar arthas-demo.jar

2. java -jar arthas-boot.jar
             
[INFO] arthas-boot version: 3.1.8
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 1 /usr/local/jetty/jetty-runner.jar
  [2]: 209 arthas-demo.jar
**input** 2
still use pid 1, not pid 209

### 期望的结果

version   3.1.8                                                                 
pid       209                                                                    
time      2020-04-03 08:36:07                                                   

[arthas@209]$ 

### 实际运行的结果

[INFO] arthas home: /var/lib/jetty/arthas
[INFO] Try to attach process 209
[INFO] Attach process 209 success.
[INFO] arthas-client connect 127.0.0.1 3658
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki      https://alibaba.github.io/arthas                                      
tutorials https://alibaba.github.io/arthas/arthas-tutorials                     
version   3.1.8                                                                 
pid       1                                                                     
time      2020-04-03 08:36:07       

[arthas@1]$

**Comment by Glaha** [comment]
And no use to add param <pid> in cli .
java -jar arthas-boot.jar 209

**Comment by hengyunabc** [comment]
先连接到原来的进程上，执行 `stop` ，再重新attach。
