### ISSUE TITLE
arthas能排查启动过慢问题么

### ISSUE THREAD

**Issue by sdoseabow** [alibaba/arthas#1096]
![load2](https://user-images.githubusercontent.com/8435664/78754003-56263580-79a9-11ea-8ac5-e690e53f398b.png)
现在公司服务启动springboot项目启动，一句序列化加载日志能卡10分钟然后才能启动 必现，能用arthas排查么？ trace cost是否一定要依附在已经启动的进程，正在启动的可以么

**Comment by hengyunabc** [comment]
可以用debug的方式启动，可以先在 main函数打个断点。再用arthas attach上去。

可以试下火焰图， `profiler -h` 。

**Comment by kailbin** [comment]
应用启动耗时分析 : http://kail.xyz/Troubleshooting/docs/Arthas/Case/Slow-Start/

**Comment by hengyunabc** [comment]
@kailbin 欢迎投稿： https://github.com/alibaba/arthas/issues/1079

**Comment by WangJi92** [comment]
>  
脚本太麻烦了，idea 下启动thread debug 更简单
[idea 下如何简单的应用启动耗时分析](https://www.yuque.com/arthas-idea-plugin/help/xbzyo9)

**Comment by courage007** [comment]
> 应用启动耗时分析 : http://kail.xyz/Troubleshooting/docs/Arthas/Case/Slow-Start/

404 error
