### ISSUE TITLE
mc命令编辑包含返回值有泛型的方法的类失败

### ISSUE THREAD

**Issue by KATKrazy** [alibaba/arthas#1101]
Memory compiler error, exception message: Compilation Error
line: 73 , message: incompatible types: inference variable T has incompatible bounds
    equality constraints: com.xxx
    lower bounds: java.lang.Object , 

方法的返回值是Result<T>类型。

ps：服务可以正常启动。

**Comment by hengyunabc** [comment]
mc 不保证能成功，看wiki: https://arthas.gitee.io/mc
