### ISSUE TITLE
Arthas的火焰图采集不完成

### ISSUE THREAD

**Issue by lebron374** [alibaba/arthas#1102]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.8
* 操作系统版本: mac os
* 目标进程的JVM版本: jdk1.8.0_191
* 执行`arthas-boot`的版本: 3.1.4

### 重现问题的步骤

执行下面代码

```
public class ArthasTest {

    public static void main(String[] args) throws Exception {

        while (true) {
            Calculate.doCalculate();

            Calculate.doSleep();
        }
    }
}


public class Calculate {

    public static void doCalculate() {
        for (int i = 0; i < 10000000; i++) {
            int d = i * i;
        }
    }

    public static void doSleep() {
        for (int i = 0; i < 10; i++) {
            int d = i * i;
        }
    }
}
```
### 期望的结果

火焰图展示出doCalculate和doSleep的CPU使用率

### 实际运行的结果

只展示到ArthasTest.main一层
![image](https://user-images.githubusercontent.com/5032169/78890375-20ac4580-7a98-11ea-9952-3348f6e698d3.png)

**Comment by hengyunabc** [comment]
可以到 https://github.com/jvm-profiling-tools/async-profiler 里提问
