### ISSUE TITLE
docker openjdk11 alpine基础镜像，跑火焰图异常

### ISSUE THREAD

**Issue by yangtaoThirdBoy** [alibaba/arthas#1109]
- [ yes] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
- 存在一个类似的issue，系统是centos，我在aliyun ecs centos系统上跑是OK的，所以想请教下alpine下可以如何解决

### 环境信息

* k8s下，容器环境为alpine，jdk环境由openjdk11精简而来
* 直接在容器内部按arthas demo操作流程执行，arthas成功启动，跑火焰图报错
### 重现问题的步骤
arthas 成功启动并执行跑火焰图的命令
![image](https://user-images.githubusercontent.com/18020588/79301098-351a9300-7f1b-11ea-8703-815dd06fd084.png)
发现以上错误之后，查找‘libstdc++.so.6’包并安装
![image](https://user-images.githubusercontent.com/18020588/79301264-b07c4480-7f1b-11ea-98b9-40dbb750adee.png)
跑火焰图仍旧抛出同样的错误

### 期望的结果

alpine 环境镜像，火焰图能正常使用

**Comment by hengyunabc** [comment]
有没有重启java进程？可能要重启才能生效。
