### ISSUE TITLE
arthas在docker 容器中启动后报错too many arguments，选择应用后也报错

### ISSUE THREAD

**Issue by esolve** [alibaba/arthas#1110]
我用alpine+jdk8构建spring项目镜像
利用 COPY --from=hengyunabc/arthas:latest /opt/arthas /opt/arthas
 引入了arthas

容器启动后，使用arthas报错
如下，怎么回事啊？如何解决啊？

`
bash-4.4# /opt/arthas/as.sh
Arthas script version: 3.1.7
[INFO] JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk
/opt/arthas/as.sh: line 618: [: too many arguments
/opt/arthas/as.sh: line 624: [: too many arguments
Found existing java process, please choose one and hit RETURN.
* [1]: 6 /app/pica-zuul.jar
6
[ERROR] Target process  is not the process using port 3658, you will connect to an unexpected process.
[ERROR] 1. Try to restart as.sh, select process 1 /bin/busybox /dev/null 1 /bin/busybox pipe:[246167406] 1 /bin/busybox pipe:[246167407] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /dev/null 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java pipe:[246167406] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java pipe:[246167407] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /usr/lib/jvm/java-1.8-openjdk/jre/lib/rt.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /app/pica-zuul.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /app/pica-zuul.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /app/logs/zuul.log 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /usr/lib/jvm/java-1.8-openjdk/jre/lib/charsets.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java socket:[246168739] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java socket:[246168268] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /usr/lib/jvm/java-1.8-openjdk/jre/lib/jsse.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /dev/random 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /dev/urandom 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /dev/random 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /dev/random 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /dev/urandom 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /dev/urandom 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/cldrdata.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/localedata.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java socket:[246168225] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /usr/lib/jvm/java-1.8-openjdk/jre/lib/jce.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/sunec.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java /usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/sunjce_provider.jar 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java socket:[246168745] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java pipe:[246168284] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java pipe:[246168284] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java anon_inode:[eventpoll] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java pipe:[246168746] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java pipe:[246168746] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java anon_inode:[eventpoll] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java pipe:[246168747] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java pipe:[246168747] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java anon_inode:[eventpoll] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java socket:[246168782] 6 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java socket:[246168771] 66 /bin/bash /dev/pts/0 66 /bin/bash /dev/pts/0 66 /bin/bash /dev/pts/0 66 /bin/bash /dev/pts/0 74 /bin/bash /dev/pts/0 74 /bin/bash /dev/pts/0 74 /bin/bash /dev/pts/0 74 /bin/bash pipe:[246169619] 74 /bin/bash /opt/arthas/as.sh 124 /bin/bash /dev/pts/0 124 /bin/bash pipe:[246169619] 124 /bin/bash /dev/pts/0 124 /bin/bash pipe:[246168915] 126 /bin/bash /dev/pts/0 126 /bin/bash pipe:[246168915] 126 /bin/bash /dev/pts/0, shutdown it first with running the 'stop' command.
[ERROR] 2. Try to use different telnet port, for example: as.sh --telnet-port 9998 --http-port -1
`

**Comment by hengyunabc** [comment]
好像是 alpine 里少一些linux的命令，用 `java -jar arthas-boot.jar`方式启动
