### ISSUE TITLE
如何恢复会话

### ISSUE THREAD

**Issue by KimShen** [alibaba/arthas#1114]
### 环境信息
arthas-boot.jar 3.2.0
mac os

### 重现问题的步骤
trace Test test & 后如果退出arthas，如何恢复到执行trace的会话？否则执行fb时会提示会话不一致

**Comment by KimShen** [comment]
补充：如果使用ctrl + z退出了arthas，但arthas-boot进程依然在，如果没办法恢复会话，kill掉会有问题么

**Comment by hengyunabc** [comment]
ctrl + z 是 bash的睡眠任务功能，进程当然还在跑。

看wiki , `quit` 和`stop` 是不一样的。 用`quit`退出。
