### ISSUE TITLE
绑到项目1，quit命令退出，重启输入命令绑定到项目2，可最终还是绑定到项目1上

### ISSUE THREAD

**Issue by wangdayewjf** [alibaba/arthas#1115]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： arthas-boot.jar version   3.2.0
* Arthas 版本: xxx
* 操作系统版本: CentOS Linux release 7.4.1708 (Core)
* 目标进程的JVM版本: 1.8.0_171
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 绑到项目1，quit命令退出
2. 输入命令绑定到项目2

### 期望的结果
期望绑定到项目1
What do you expected from the above steps？

### 实际运行的结果

`[INFO] Try to attach process 18601
[INFO] Attach process 18601 success.
[INFO] arthas-client connect 127.0.0.1 3658
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki      https://alibaba.github.io/arthas                                      
tutorials https://alibaba.github.io/arthas/arthas-tutorials                     
version   3.2.0                                                                 
pid       3238                                                                  
time      2020-04-16 22:22:22                                                   

[arthas@3238]$ `
```

**Comment by hengyunabc** [comment]
到原来的进程上，执行 `stop` 。
