### ISSUE TITLE
Call for test cases

### ISSUE THREAD

**Issue by ralf0131** [alibaba/arthas#112]
Hi community,

As we all know that this project lack of unit tests. For an open source project, unit test means quality and stability. I am planning to improve the test cases. If you would like to help please comment on this issue.

Some of the codes may be difficult to be tested, we need a framework to bootstrap that. But we can start from simple tests.

I would suggest to start from package `com.taobao.arthas.core.view` and `com.taobao.arthas.core.util`

**Comment by richPurba** [comment]
Hi @ralf0131 I think i can help for making the test cases. I saw the code source recently, and was thinking to start with package `com.taobao.arthas.core.shell`. Unless there are many uncovered unit tests in the `view` and `util`. 
Let me know, and i need some explanation about on functional level for `shell`, what it is and it does?
