### ISSUE TITLE
启动后, 选择pid报java.lang.IllegalArgumentException: 2: command not found

### ISSUE THREAD

**Issue by a40885948** [alibaba/arthas#1124]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: centos 7
* 目标进程的JVM版本: java 8
* 执行`arthas-boot`的版本: 3.2.0

### 重现问题的步骤

1. nohup java -jar arthas-demo.jar &
2. java -jar arthas-boot.jar
3. 输入2，再输入回车/enter

### 期望的结果

文档上说输出如下日志：
[INFO] Try to attach process 71560
[INFO] Attach process 71560 success.
[INFO] arthas-client connect 127.0.0.1 3658

### 实际运行的结果
我机器上输出的日志：
java.lang.IllegalArgumentException: 3: command not found
文档地址：https://alibaba.github.io/arthas/quick-start.html
没有搞明白为啥我一选择就报这个异常

**Comment by hengyunabc** [comment]
跑在线教程有问题不？

https://alibaba.github.io/arthas/arthas-tutorials?language=cn
