### ISSUE TITLE
切换命令trace无法打印全日志

### ISSUE THREAD

**Issue by yugj** [alibaba/arthas#1133]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.2.0
* 操作系统版本: macos 10.14.6
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.2.0

### 重现问题的步骤

1，执行：trace cn.xxx.handler.JoinRoomHandler joinRoom '#cost > 100'

首次可以打印方法内部全部执行时间日志

2，切换一个命令，比如dashboard

3，再执行：trace cn.xxx.handler.JoinRoomHandler joinRoom '#cost > 100'

然后只能看到当前方法trace日志，方法内部的统计就没了

```shell
[arthas@56355]$ trace cn.xxx.JoinRoomHandler joinRoom '#cost > 100'
Press Q or Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:2) cost in 313 ms.
`---ts=2020-04-22 15:17:00;thread_name=http-nio-18002-exec-2;id=9b;is_daemon=true;priority=5;TCCL=org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader@12313cf1
    `---[1110.092618ms] cn.xxx.JoinRoomHandler$$EnhancerBySpringCGLIB$$2211f995:joinRoom()
        `---[1105.677501ms] org.springframework.cglib.proxy.MethodInterceptor:intercept() #0
```

4，执行stop命令 重新运行arthas，重新执行trace命令，可以查到方法内部执行trace日志

5，不切换ctrl + c 重新运行是正常的

### 期望的结果

What do you expected from the above steps？
切换执行其他命令，不执行stop命令也可以直接使用trace，并且可以打印完整trace日志

### 实际运行的结果

不执行stop命令只打印了当前整个方法的执行时间，内部trace没有打印

```
[arthas@56355]$ trace cn.xxx.JoinRoomHandler joinRoom '#cost > 100'
Press Q or Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:2) cost in 313 ms.
`---ts=2020-04-22 15:17:00;thread_name=http-nio-18002-exec-2;id=9b;is_daemon=true;priority=5;TCCL=org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader@12313cf1
    `---[1110.092618ms] cn.xxx.JoinRoomHandler$$EnhancerBySpringCGLIB$$2211f995:joinRoom()
        `---[1105.677501ms] org.springframework.cglib.proxy.MethodInterceptor:intercept() #0
```

**Comment by dzh6699** [comment]
我也碰到一个trace的问题，如果方法a调用某个方法b，方法b 里面用到多线程，那么trace方法a后，只会记录到方法b那一行，不知道这个是不是bug还是设计如此

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/597

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/717

**Comment by dzh6699** [comment]
> #597

方法 A中调用了   b 、c、d三个方法，trace A，只打印了b的方法耗时，没有打印c和d的方法耗时
我是这个意思

**Comment by yugj** [comment]
@hengyunabc issue #597 貌似和我描述的不一样，我这边问题是首次trace A方法（里面调用b c d）是可以打印出日志的，但是切换一下命令 ，比如dashboard，然后再回来执行trace A方法，就无法统计到b c d方法调用，必须手动执行stop 然后重新开启arthas 才行  
这个是设计就这样吗

**Comment by hengyunabc** [comment]
> > #597
> 
> 方法 A中调用了 b 、c、d三个方法，trace A，只打印了b的方法耗时，没有打印c和d的方法耗时
> 我是这个意思

提供可重现的demo

**Comment by hengyunabc** [comment]
> @hengyunabc issue #597 貌似和我描述的不一样，我这边问题是首次trace A方法（里面调用b c d）是可以打印出日志的，但是切换一下命令 ，比如dashboard，然后再回来执行trace A方法，就无法统计到b c d方法调用，必须手动执行stop 然后重新开启arthas 才行
> 这个是设计就这样吗

不是。提供可重现的demo
