### ISSUE TITLE
dashboard命令thread cpu取样时间太短影响准确性

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1137]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: all
* 目标进程的JVM版本: all
* 执行`arthas-boot`的版本: 3.2.0

### 重现问题的步骤

1. 查看代码发现dashboard命令thread cpu 计算的采样间隔时间为100ms，没有提供设置采样间隔时间的参数
2. JVM get thread cpu time的数据是并不是实时更新的，不同操作系统下的更新间隔不一样，100ms的间隔时间可能还没有更新cpu时间，造成线程cpu增量时间计算不准确，排序结果不准确。
3. 建议修改统计方式，记录最近一次采样数据，默认采样间隔2s，对比上次采样数据计算增量，而不是在一次更新中sleep等待间隔时间采样2次。
4. 提供设置更新间隔时间（同为采样间隔时间），类似top命令
5. 线程的CPU是线程增量cpu占比，没有具体的时间信息，不能用于判断系统繁忙程度，建议增加cpu增量时间或者改为cpu占比=线程cpu时间/采样间隔

**Comment by tz826** [comment]
不是有个  -i 参数吗

**Comment by ubyyj** [comment]
我这边会看到非常高的%CPU, 比如49046.42, 提高-i参数也不起作用。哪位讲解一下。
用的java为java17， 在pod里面用

**Comment by kylixs** [comment]
> 我这边会看到非常高的%CPU, 比如49046.42, 提高-i参数也不起作用。哪位讲解一下。
> 用的java为java17， 在pod里面用

建议创建新的问题，最好可以提供详细的信息
