### ISSUE TITLE
dashboard对Tomcat识别不准确

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1139]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
* Arthas 版本: 3.2.0

### 重现问题的步骤

1. dashboard代码中探测是否为tomcat应用是通过访问 http://localhost:8006 链接，根据请求结果是否成功
2. tomcat的管理端口是可以在server.xml修改的，这个检测方法不稳定
    Tomcat独立部署版本中两个管理的默认端口是8005，8009 
3. 建议修改为其它方式，如MXBean的方式

**Comment by hengyunabc** [comment]
dashboard 里的 tomcat判断是alibaba内部的逻辑，开源部分没有这个功能。

**Comment by hengyunabc** [comment]
dashboard.png 已更新： https://github.com/alibaba/arthas/blob/b89bc1b4008dd374a145cd4b597ba6ebfaa33d86/site/src/site/sphinx/_static/dashboard.png
