### ISSUE TITLE
vmoption疑问

### ISSUE THREAD

**Issue by stephen222** [alibaba/arthas#1145]
在jvm运行时修改参数
执行如下命令成功
vmoption PrintGC true
vmoption PrintGCDetails true

无法在运行时指定gc日志的目录，请问默认的gc日志路径是在哪里看的？

**Comment by hengyunabc** [comment]
应该在应用本身的标准输出里。

**Comment by stephen222** [comment]
方便的话能否指教下 如何查看应用的标准输出目录？目前就是开启了gc日志，但是由于没有指定目录，发找不到这部分日志，比较头疼

**Comment by hengyunabc** [comment]
@stephen222 不清楚这个参数是否动态有效的。没有具体测试过。也可能只是启动时有效。

应用的标准输出就是 System.out 。
