### ISSUE TITLE
trace/watch/stack关于观察表达式/条件表达式文档不一致？

### ISSUE THREAD

**Issue by uvletter** [alibaba/arthas#1148]
watch的参数列表里同时提到观察表达式express和条件表达式condition-express，但是参数说明里只提及观察表达式。
trace和stack的参数列表里提及条件表达式condition-express，但是参数说明里是观察表达式。
更新API麻烦文档一并更新。
另外观察表达式和条件表达式的定义最好给出一下，条件表达式可以通过名字理解是条件的过滤语法，但是观察表达式从名字上完全看不出含义，而且直译英文observation-express似乎更准确。

**Comment by uvletter** [comment]
问题二：trace示例里似乎没有提及条件表达式condition-express，可能情况：1. 条件表达式condition-express是可选参数；2. 实现上没有支持条件表达式。如果是情形1，参数列表的condition-express需要加方括号。情形二则要删去condition-express

**Comment by uvletter** [comment]
另外trace如何区分重载方法，我没看到明确说明。 #577 #434 提到用表达式，我试过
```java
trace Hello test params.length=1
```
和
```java
trace Hello test params params.length=1
```
似乎都不奏效，能否请教下观察表达式/条件表达式的正确使用姿势
version: 3.2.0
![image](https://user-images.githubusercontent.com/18381436/80859020-2dcfe500-8c90-11ea-981f-2c7c91e09f4f.png)

**Comment by hengyunabc** [comment]
@uvletter 欢迎提PR改进文档。

应该用 `params.length==1` 。  

trace只支持条件表达式。

**Comment by uvletter** [comment]
但是如我截图第一个命令所示，method-cnt显示2，并没有过滤
