### ISSUE TITLE
windowns系统上，启动报错Can not find java process. Try to pass <pid> in command line.

### ISSUE THREAD

**Issue by applehub** [alibaba/arthas#1156]
C:\Users\Administrator\Desktop>java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.2.0
[INFO] Can not find java process. Try to pass <pid> in command line.
Please select an available pid.

网上说是启动arthas的用户要和java进程的用户一样，可是系统也就只有一个用户

**Comment by J-Cod3r** [comment]
windows下使用方式：as.bat <pid>
参考文档：https://alibaba.github.io/arthas/manual-install.html

**Comment by applehub** [comment]
昨天可以了，但是今天又出现这个问题，这个是telnet端口被占用了吗？
![image](https://user-images.githubusercontent.com/30278353/81467095-e0f88b00-9208-11ea-97eb-f36fe36cb762.png)
