### ISSUE TITLE
redefine无效

### ISSUE THREAD

**Issue by 1ibo** [alibaba/arthas#1161]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: Linux  4.18.0-80.11.2.el8_0.x86_64     
* 目标进程的JVM版本: 1.8.0_144
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 在编译器更新代码，上传class文件到服务器
代码修改如下
```
#修改前
···
    return RpcUtil.createBizResult(baseParam, WxPayNotifyResponse.success("OK"));
···
#修改后
···
     String returnMsg = "<xml><return_code><![CDATA[SUCCESS]]></return_code><return_msg><![CDATA[OK]]></return_msg></xml>";
    return RpcUtil.createBizResult(baseParam, returnMsg);
       
···

```
2. 执行redefine命令，提示成功
3. 用trace跟踪，发现修改的地方没有生效

### 期望的结果

不再执行 WxPayNotifyResponse.success("OK"));方法

### 实际运行的结果
还是打印调用了WxPayNotifyResponse:success()
```
 +---[52.891379ms] com.github.binarywang.wxpay.bean.notify.WxPayNotifyResponse:success() #753 
```

**Comment by hengyunabc** [comment]
redefine 和 trace 是JVM里两套不同的工作机制，会互相冲突。 redefine之后，再trace就会冲掉redefine的内容。

https://github.com/alibaba/arthas/issues/597

**Comment by 1ibo** [comment]
好的，谢谢
