### ISSUE TITLE
如何查看类的成员变量信息？

### ISSUE THREAD

**Issue by yancheng199287** [alibaba/arthas#1164]
public class WebSocketService{
   private    Map<String, WebSocketSession> webSocketSessionMap = messageTextWebSocketHandler.webSocketSessionMap;

}

怎么查看这个map里面的数据信息？

**Comment by 15256500312** [comment]
ognl表达式了解以下

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/71
