### ISSUE TITLE
jad 代码里面的中文编程unicode怎么办？

### ISSUE THREAD

**Issue by 15256500312** [alibaba/arthas#1169]

**Comment by hengyunabc** [comment]
上游的 cfr 反编译器不支持，目前可以自己本地转换下。。

**Comment by leibnitz27** [comment]
btw, cfr != jad ;)

**Comment by hengyunabc** [comment]
@leibnitz27 JAD means: java decompiler. In the first version, JD-GUI was used, later switch to the better CFR. Thank you very much for the great decompiler library. CFR would be perfect if it supported printed line numbers :)
