### ISSUE TITLE
monitor的输出，如果类名太长，会被截断的问题

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1170]

**Comment by Huangxuny1** [comment]
这个问题应该是因为 

调用 [`com.taobao.text.ui.TableLineRenderer# reader(final int width, final int height)`](https://github.com/alibaba/text-ui/blob/fcb684423a41026a8b7cc383ee73839ce1679f12/src/main/java/com/taobao/text/ui/TableLineRenderer.java#L134)
```java
 // Note that we may have a different widths != eltWidths according to the layout algorithm
    final int[] widths = columnLayout.compute(separator != null, width - (border != null ? 2 : 0), eltWidths, eltMinWidths);
```
时 , 由于 `总长度` > `tty 的长度` , 会通过如下循环进行修剪

[`com.taobao.text.ui.Layout`](https://github.com/alibaba/text-ui/blob/fcb684423a41026a8b7cc383ee73839ce1679f12/src/main/java/com/taobao/text/ui/Layout.java#L180-L199)
```java
 //
      int index = minLengths.length - 1;
      while (totalLength > length && index >= 0) {
        int delta = totalLength - length;
        int bar = actualLengths[index] - minLengths[index];
        if (delta <= bar) {
          // We are done
          totalLength = length;
          ret[index] -= delta;
        } else {
          int foo = actualLengths[index];
          if (spaced) {
            if (index > 0) {
              foo++;
            }
          }
          totalLength -= foo;
          ret[index] = 0;
          index--;
        }
      }
```
结果 原本有 长度为 `8` 的数组 被修剪成了 `2`
![image](https://user-images.githubusercontent.com/21981606/82522557-66126700-9b5c-11ea-911f-3116dbfadb66.png)

原本结果应该是 类似于 
![image](https://user-images.githubusercontent.com/21981606/82522582-788ca080-9b5c-11ea-922a-d341dc7477f7.png)




我在debug的时候手动修改了一下数据  , 结果哦就正常了

![image](https://user-images.githubusercontent.com/21981606/82522246-7249f480-9b5b-11ea-902d-493edb0e202d.png)

**Comment by hengyunabc** [comment]
谢谢 @Huangxuny1 找到真正的原因 https://github.com/alibaba/text-ui/pull/1#issuecomment-634439835 ，已经用你的 author 提交修复了。
