### ISSUE TITLE
优化建议：在线教程进阶篇第7小节中ognl学习教程

### ISSUE THREAD

**Issue by lov3r** [alibaba/arthas#1173]
### 问题描述
在线教程进阶篇第7小节中ognl学习教程中提示错误如下：
``` 
[arthas@37]$ ognl -c 1be6f5c3 @com.example.demo.arthas.user.UserController@logger
Can not find classloader with hashCode: 1be6f5c3.
```
### 期望的效果
正确执行，应优化调整文档内容内容：加入先通过sc查询classloader的hash值再执行上述语句

### 文档位置
![image](https://user-images.githubusercontent.com/33676682/82005242-7081bc00-9697-11ea-9a1e-c41d2c8644d0.png)

**Comment by hengyunabc** [comment]
谢谢指出，更新了： https://github.com/hengyunabc/katacoda-scenarios/commit/b662cced7efc50379163f91402252cdacc4c7c84
