### ISSUE TITLE
Command "ognl" not found.

### ISSUE THREAD

**Issue by ericYc** [alibaba/arthas#1180]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: CentOS 7.1.1503
* 目标进程的JVM版本: jdk1.7.0_76
* 执行`arthas-boot`的版本: 3.2.0

### 重现问题的步骤

1. ognl

### 可以执行命令

What do you expected from the above steps？

### 实际运行的结果

Command "ognl" not found.

```
把异常信息贴到这里
```

**Comment by ericYc** [comment]
本地运行可以出来欢迎页面
Arthas home: /Users/yangchao/Desktop/arthas
Calculating attach execution time...
Attaching to 19421 using version /Users/yangchao/Desktop/arthas...

real	0m1.026s
user	0m0.375s
sys	0m0.045s
Attach success.
telnet connecting to arthas server... current timestamp is 1589864649
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'


wiki      https://alibaba.github.io/arthas
tutorials https://alibaba.github.io/arthas/arthas-tutorials
version   3.2.0
pid       19421
time      2020-05-19 13:04:08

**Comment by ericYc** [comment]
服务器上运行出不来

Arthas script version: 3.2.0
[INFO] JAVA_HOME: /usr/local/jdk1.7.0_76
[INFO] Process 76705 already using port 3658
[INFO] Process  already using port 8563
Arthas home: /home/sankuai
Calculating attach execution time...
Attaching to 76705 using version /home/sankuai...

real	0m0.488s
user	0m0.890s
sys	0m0.099s
Attach success.
telnet connecting to arthas server... current timestamp is 1589865546
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

**Comment by hengyunabc** [comment]
检查 `~/logs/arthas/arthas.log` 。

另外，试下直接 telnet localhost 3658

**Comment by ericYc** [comment]
Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.NoSuchMethodException: com.taobao.arthas.core.server.ArthasBootstrap.bind(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1670)
	at com.taobao.arthas.agent3.AgentBootstrap.bind(AgentBootstrap.java:199)
	at com.taobao.arthas.agent3.AgentBootstrap.access$000(AgentBootstrap.java:21)
	at com.taobao.arthas.agent3.AgentBootstrap$1.run(AgentBootstrap.java:164)
Arthas server agent start...
Arthas start to bind...
Arthas server port binding failed! Please check $HOME/logs/arthas/arthas.log for more details.
java.lang.NoSuchMethodException: com.taobao.arthas.core.server.ArthasBootstrap.bind(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1670)
	at com.taobao.arthas.agent3.AgentBootstrap.bind(AgentBootstrap.java:199)
	at com.taobao.arthas.agent3.AgentBootstrap.access$000(AgentBootstrap.java:21)
	at com.taobao.arthas.agent3.AgentBootstrap$1.run(AgentBootstrap.java:164)
Arthas server agent start...

telnet refuse

**Comment by hengyunabc** [comment]
可能混用了旧版本的。要重启进程，再用arthas。 或者换台机器试下。

**Comment by ericYc** [comment]
确实是，我之前先跑了greys，换了台机器就没有问题了
