### ISSUE TITLE
trace没有返回详细的信息

### ISSUE THREAD

**Issue by Jipon** [alibaba/arthas#1181]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

![微信截图_20200519142546](https://user-images.githubusercontent.com/22913504/82292405-6f28fa00-99dd-11ea-8b03-307abea3f70a.png)

只返回了这一行，没有ts等其他信息了

### 期望的结果

难道不应该是这样子的吗？

$ trace demo.MathGame run
--
  | Press Q or Ctrl+C to abort.
  | Affect(class-cnt:1 , method-cnt:1) cost in 28 ms.
  | `---ts=2019-12-04 00:45:08;thread_name=main;id=1;is_daemon=false;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@3d4eac69
  | `---[0.617465ms] demo.MathGame:run()
  | `---[0.078946ms] demo.MathGame:primeFactors() #24 [throws Exception]
  |  
  | `---ts=2019-12-04 00:45:09;thread_name=main;id=1;is_daemon=false;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@3d4eac69
  | `---[1.276874ms] demo.MathGame:run()
  | `---[0.03752ms] demo.MathGame:primeFactors() #24 [throws Exception]

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/597

**Comment by hengyunabc** [comment]
另外，你图里没有打印出新的内容，原因是函数没有被调用。可以自己本地写个demo测试下。
