### ISSUE TITLE
加载的term设备信息太多，浪费较大内存

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1186]
terminfo 默认加载了2600多个设备信息，占用了11MB内存，而Arthas只使用“xterm”这一个设备。
详情请查看：https://github.com/alibaba/termd/issues/35

**Comment by kylixs** [comment]
改进思路：
1）termd TermInfo 提供从指定文件加载device的接口，默认不能全部加载
2）arthas中提供一份精简的"terminfo.src"，只需要包含xterm

**Comment by lzc-alioo** [comment]
我想认领下这个issue，你提到的2个方案中都需要有个前提，比如改进思路中提到的

> 精简的"terminfo.src"

，这个可以从哪里知道呢

**Comment by lzc-alioo** [comment]
搜索了一下代码库，发现只有一处调用 
`    this.device = TermInfo.defaultInfo().getDevice("xterm"); // For now use xterm
`
是不是只加载xterm就可以了？  @kylixs 

![image](https://user-images.githubusercontent.com/33567235/82818584-867e5080-9ed1-11ea-95bb-7e6bec894647.png)

**Comment by kylixs** [comment]
@lzc-alioo 大概有几点要注意
1）https://github.com/alibaba/termd 项目io.termd.core.term.TermInfo#loadDefault() 默认加载了全部的device，占用过多内存。因为有依赖termd的其它项目，考虑到兼容性，故这个方法的功能不能改变，而是改为lazy方式加载。

2）termd项目提供一个新的加载device的接口，可以指定资源文件，如
TermInfo termInfo = TermInfo.loadDevices("myterminfo.src");

3）抽取精简版的terminfo.src，只包含Readline 使用的xterm，在Readline中只通过第2点的接口单独加载。

**Comment by hengyunabc** [comment]
有一个简单的方案：

* 在 termd项目里有一个 terminfo.src 的静态资源，要把这里arthas用到的提取出来成为一个新的 terminfo.src
* 把新的 terminfo.src 放到 arthas工程里，arthas 最终会把 termd 打包到 arthas-core.jar 里，所以只要在 arthas里的 core模块打包里，覆盖掉原来 termd里的 terminfo.src 就可以了。

**Comment by lzc-alioo** [comment]
结合2位大佬的建议 @hengyunabc @kylixs ，略改了下TermInfo.loadDefault方法，让其兼容2个目录去加载terminfo.src文件，分别是classpath://terminfo.src ，classpath://io/termd/core/term/terminfo.src，如果前者存在则忽略后者。

**Comment by hengyunabc** [comment]
@lzc-alioo 不需要改 termd 仓库里的代码，只要把新的 `terminfo.src` 放到 arthas仓库里，然后修改下 arthas core模块里的打包就可以了。

**Comment by lzc-alioo** [comment]
> @lzc-alioo 不需要改 termd 仓库里的代码，只要把新的 `terminfo.src` 放到 arthas仓库里，然后修改下 arthas core模块里的打包就可以了。

不改代码的话就要求按照如下方式存放文件src/main/resources/io/termd/core/term/terminfo.src ，我修改之后直接放置到src/main/resources/terminfo.src就可以了，会不会简单点?

**Comment by hengyunabc** [comment]
@lzc-alioo 没有必要的话，不用修改 termd的代码。保留原来的路径适配会更合理。

也可以试下直接把新的 `terminfo.src`放到 arthas-core 的 `src/main/resources/io/termd/core/term/terminfo.src `。也许这样就能解决问题了。
