### ISSUE TITLE
WebConsole 连接泄漏

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1187]
#748 # 环境信息

* Arthas 版本: 3.2.1-SNAPSHOT
* 操作系统版本: macOS 10.15.4
* 目标进程的JVM版本: jdk1.8.0_151

### 重现问题的步骤

1. 浏览器访问 http://localhost:8563 打开WebConsole
2. 执行几条命令，关闭标签
3. jmap dump 

### 期望的结果
What do you expected from the above steps？
期望关闭标签后触发连接关闭事件： io.termd.core.http.HttpTtyConnection#close()
TtyWebSocketFrameHandler$1#close()

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
实际上没有执行close()方法，资源没有被释放，强制GC后仍然不能释放。
![image](https://user-images.githubusercontent.com/5483385/82436621-b17b3580-9ac8-11ea-842f-b7445a7535b0.png)

**Comment by kylixs** [comment]
已经在http api分支修复

**Comment by lzc-alioo** [comment]
大佬牛

**Comment by jiangwh** [comment]
牛。能发现这样的问题非常了解不起。
