### ISSUE TITLE
关闭会话后没有及时释放资源

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1189]
### 环境信息
* Arthas 版本: 3.2.1

### 重现问题的步骤
 
1. telnet 127.0.0.1 3658  或者 浏览器访问WebConsole http://localhost:8563/
2. 执行quit，关闭会话
3. jmap dump

### 期望的结果
What do you expected from the above steps？

期望在关闭会话后释放相关对象资源，包括Term、连接对象等。

### 实际运行的结果
实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

dump分析发现Term 和 Connection对象都没有释放，跟踪了一下，发现与任务执行超时检查的jobTimeoutTask有关，关闭会话没有清理此timer。
![image](https://user-images.githubusercontent.com/5483385/82440619-35d0b700-9acf-11ea-8f3f-69b7c0b18645.png)

![image](https://user-images.githubusercontent.com/5483385/82452415-cadcab80-9ae1-11ea-93b4-3f61d914b3a2.png)

**Comment by hengyunabc** [comment]
刚合并到master里的代码把这一块统一掉了，应该有close掉了。

**Comment by kylixs** [comment]
检查了一下master上的版本0476c61af98f51b9815a33d83b1643c0d2f3017e，仍然存在这个问题
