### ISSUE TITLE
Arthas profiler是否可以指定采集时间，到时间后自动停止。

### ISSUE THREAD

**Issue by during3a3** [alibaba/arthas#1197]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
Arthas的profiler命令是否提供了像./profiler.sh -d 300 pid这样的命令，即采集规定时间后自动停止。

**Comment by abelzhou** [comment]
@hengyunabc profiler start -d 的特性是在哪个release版本当中支持了？
