### ISSUE TITLE
为什么trace 总的时间与下面的时间相加不等

### ISSUE THREAD

**Issue by FellSoCold** [alibaba/arthas#1199]
`---[1413.798092ms] com.uama.api.community.web.v37.MineAppsController$$EnhancerBySpringCGLIB$$dd380ce5:mineAllAppsList()
        `---[1413.616436ms] org.springframework.cglib.proxy.MethodInterceptor:intercept() #0
            `---[1412.926481ms] com.uama.api.community.web.v37.MineAppsController:mineAllAppsList()
                +---[0.038759ms] com.uama.api.community.support.CurrentContext:getUserId() #73
                +---[0.003966ms] com.uama.api.community.support.CurrentContext:getCurCommunityId() #74
                +---[0.001822ms] com.uama.api.community.support.CurrentContext:getRoomIdIfNull() #75
                +---[0.002218ms] com.uama.api.community.support.CurrentContext:getAreaCode() #76
                +---[0.042951ms] com.uama.api.community.support.CurrentContext:getLatitude() #77
                +---[0.00261ms] com.uama.api.community.support.CurrentContext:getLongitude() #78
                +---[0.001835ms] com.uama.api.community.support.CurrentContext:getCurOrgId() #79
                +---[0.025191ms] com.uama.framework.core.DynamicDataSourceContextHolder:getDataSourceType() #80
                +---[0.004635ms] com.uama.microservices.api.life.model.newlife.form.MLifeLocationF:<init>() #81
                +---[0.003186ms] com.uama.microservices.api.life.model.newlife.form.MLifeLocationF:setUserId() #82
                +---[0.002346ms] com.uama.microservices.api.life.model.newlife.form.MLifeLocationF:setAreaCode() #83
                +---[0.010474ms] com.uama.api.community.support.CurrentContext:getLatitude() #84
                +---[0.002714ms] com.uama.microservices.api.life.model.newlife.form.MLifeLocationF:setLatitude() #84
                +---[0.001059ms] com.uama.api.community.support.CurrentContext:getLongitude() #85
                +---[0.002286ms] com.uama.microservices.api.life.model.newlife.form.MLifeLocationF:setLongitude() #85
                +---[20.733578ms] com.uama.microservices.api.life.service.v1.newlife.StoreServiceV1:getStoreList() #86
                +---[4.380271ms] com.uama.microservices.api.base.service.v1.OwnerAssetServiceV1:listCommunityLocationByUserId() #91
                +---[0.010518ms] com.uama.api.community.util.CollectionUtils:isNotEmpty() #93
                +---[0.003823ms] com.uama.microservices.api.base.model.vo.MBaseCommunityLocationV:getCommunityId() #95
                +---[0.007823ms] com.uama.framework.util.lang.StringUtils:isNotBlank() #96
                +---[4.530382ms] com.uama.microservices.api.base.service.v1.OrgInfoServiceV1:getOrgLabelList() #108
                +---[0.007862ms] com.uama.api.community.model.vo.mineapps.ALifeMineAppsAllV:<init>() #110
                +---[0.624223ms] com.uama.api.community.async.AsyncServerService:getMineAppsList() #113
                +---[0.007454ms] com.uama.api.community.model.enums.ESubjectRecommendEnum:getCode() #118
                +---[0.208992ms] com.uama.api.community.async.AsyncServerService:recommendForYouApps() #117
                +---[0.256114ms] com.uama.api.community.async.AsyncServerService:getAllSubject() #126
                +---[0.008398ms] com.uama.api.community.model.vo.mineapps.ALifeMineAppsAllV:setAllApps() #133
                +---[0.004157ms] com.uama.api.community.model.vo.mineapps.ALifeMineAppsAllV:setMineApps() #134
                +---[0.012426ms] com.uama.api.community.support.ApiResult:ok() #136
                `---[0.00548ms] com.uama.api.community.support.ApiResult:data() #136

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/597

**Comment by ljp190** [comment]
时间花在了线程调度上，或许是初始化线程，时间长点正常
要么是并发线程数不足，导致tomcat或者undertow等待其它线程释放。所以虽然本身方法时间很少，但最终响应时长上去了。
