### ISSUE TITLE
is it possible to list all currently loaded jar files?

### ISSUE THREAD

**Issue by echo-of-wind** [alibaba/arthas#1208]

**Comment by Huangxuny1** [comment]
Yes,of cause , we know that there is a command `classloader` , so we can get all `classloader ` 

`classloader` -> `ucp` -> `path` can show all `URL` , which is the jar path

![image](https://user-images.githubusercontent.com/21981606/82771570-0f17d500-9e6f-11ea-8527-5d12ef38cc86.png)

**Comment by hengyunabc** [comment]
https://alibaba.github.io/arthas/en/classloader
