### ISSUE TITLE
jad命令 无返回

### ISSUE THREAD

**Issue by zhangyyii** [alibaba/arthas#1209]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本: 3.2.0
* 操作系统版本: macos 10.15.2
* 目标进程的JVM版本: java version "1.8.0_221"
* 执行`arthas-boot`的版本: arthas3.2.0

### 重现问题的步骤

1. 启动应用
2. 启动arthas 并 attach
3. telnet 链接到 arthas 然后  执行  jad java.lang.String

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```




```
```
[arthas@2795]$ jad java.lang.String
Affect(row-cnt:0) cost in 78 ms.
[arthas@2795]$ version
3.2.0
[arthas@2795]$ sc java.lang.String
java.lang.String
Affect(row-cnt:1) cost in 18 ms.
[arthas@2795]$ jad java.lang.String format
Affect(row-cnt:0) cost in 73 ms.
[arthas@2795]$
```

**Comment by hengyunabc** [comment]
启动 arthas-demo.jar 测试有没有问题？ 另外，检查下 `~/logs/arthas/arthas.log`

**Comment by hengyunabc** [comment]
可以试下最新版本。
