### ISSUE TITLE
AsyncProfiler不适宜放到arthas-spy.jar中

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1220]
AsyncProfiler放到arthas-spy.jar中将导致被加载到BootstrapClassLoader，无法动态更新替换。

**Comment by hengyunabc** [comment]
AsyncProfiler 本身是不能动态更新的，只能放到 BootstrapClassLoader 或者 SystemClassLoader里。否则会有 so 的加载问题。 在jvm 里 so 文件是和加载它的 classloader 关联的。

**Comment by kylixs** [comment]
最根本的原因是so/dll 不能动态更新/重复加载
