### ISSUE TITLE
是否可以基于retransformClasses实现redefine命令，避免redefineClasses的冲突问题

### ISSUE THREAD

**Issue by kylixs** [alibaba/arthas#1222]
通过retransformClasses也可以替换class字节码，是否可以实现redefineClasses相同的效果。
这样做的目的是避免使用redefineClasses，避免redefine命令与trace/watch/monitor/tt/jad冲突。
想到的要点：
1）将redefine的ClassFileTransformer插入到TransformerManager.mTransformerList的最前面，可能需要通过类反射进行操作；
2）调用retransformClasses()，先执行redefine替换class字节码，然后执行后面的其它transformer修改字节码（trace / watch / apm ）
3）删除redefine的transformer

**Comment by hengyunabc** [comment]
统一用 TransformerManager 管理 ClassFileTransformer 就是这个目的。不过还没来得及做。

ClassFileTransformer 要加入 order的概念。 

Origin Jad > redefine > trace/watch >  final Jad 。 插件化之后，还要据不同插件的功能来定义 order。

**Comment by hengyunabc** [comment]
done.

**Comment by fhyfhy17** [comment]
> done.

在哪个版里，没看到release note

**Comment by hengyunabc** [comment]
> > done.
> 
> 在哪个版里，没看到release note

用最新版本 https://arthas.aliyun.com/doc/retransform.html
