### ISSUE TITLE
感觉 trace 结果有误

### ISSUE THREAD

**Issue by wswx** [alibaba/arthas#1230]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.2.0
* 操作系统版本: Ubuntu 5.4.0-6ubuntu1~16.04.12
* 目标进程的JVM版本: Java HotSpot(TM) 64-Bit Server VM 

### 重现问题的步骤
trace xxx method
### 期望的结果

我希望看到方法调用时长

### 实际运行的结果

![image](https://user-images.githubusercontent.com/35282496/83706603-7d684e80-a64a-11ea-9ab1-9dccf08069a0.png)

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
可以提供可重现的demo不？

**Comment by wswx** [comment]
抱歉，我调试的是公司的项目，无法提供给你

**Comment by hengyunabc** [comment]
> 抱歉，我调试的是公司的项目，无法提供给你

试下 `stop` 后，用 3.2.0 版本。  `./as.sh --use-version 3.2.0`

**Comment by lis19930** [comment]
下载了3.2.0版本，参数也是负数！

**Comment by wswx** [comment]
我在本地用 java -jar arthas-boot.jar尝试了多次，对同一个程序同一方法进行调试，当重现的时候，重启程序可能恢复正常
使用./as.sh --use-version 3.2.0 这种方式在线上服务器业恢复正常

**Comment by hengyunabc** [comment]
应该在 3.3.3里修复掉了： https://github.com/alibaba/arthas/issues/1246
