### ISSUE TITLE
请问dashboard里内存信息max那一栏是什么意思？和jmap的利用率算的不一样

### ISSUE THREAD

**Issue by k9990009** [alibaba/arthas#1233]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
我在文档里找了，没找到这个max的解释。这个max到底是有没申请内存？应用在top里显示RES确实占到4G。jmap看老年代都占用90%+了，但没有触发老年代gc

### 环境信息

* 操作系统版本: centos7
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 最新的

### 重现问题的步骤

![微信截图_20200604150857](https://user-images.githubusercontent.com/40509647/83726086-963a2980-a675-11ea-88bd-0f851479cea0.png)

![微信截图_20200604151031](https://user-images.githubusercontent.com/40509647/83726149-af42da80-a675-11ea-9b68-6cef5c0667af.png)

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/blob/arthas-all-3.3.2/core/src/main/java/com/taobao/arthas/core/command/monitor200/DashboardCommand.java

**Comment by k9990009** [comment]
好的

**Comment by jinxuan-LY** [comment]
所以大佬们，dashboard memory 中max 一列是什么含义。

**Comment by lizhecao** [comment]
> 所以大佬们，dashboard memory 中max 一列是什么含义。

max这一列的意思就是jvm的最大可用内存数

**Comment by yydzxz** [comment]
原来如此
