### ISSUE TITLE
为什么BusinessAppAccountController.createAppAccount 应traces 不展示详细信息

### ISSUE THREAD

**Issue by yudongya** [alibaba/arthas#1247]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. trace cn.joyi.obdp.api.usercenter.controller.BusinessAppAccountController createAppAccount
2. xxx
3. xxx

### 期望的结果
出现耗时路径
What do you expected from the above steps？

### 实际运行的结果
不展示

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
![图片](https://user-images.githubusercontent.com/21274199/83989667-ba4d8180-a979-11ea-8ec7-0f052916802b.png)

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
没有被调用。。

**Comment by yudongya** [comment]
不加run 正常






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hengyunabc"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 中午11:59
收件人: "alibaba/arthas"<arthas@noreply.github.com&gt;; 
抄送: "crystal plan"<975387401@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/arthas] 为什么BusinessAppAccountController.createAppAccount 应traces 不展示详细信息 (#1247)





 
没有被调用。。
