### ISSUE TITLE
希望新增记录所有调用方法功能

### ISSUE THREAD

**Issue by gcxtx** [alibaba/arthas#1250]
有时候分析一个大型框架，对其不太了解，想知道执行某一个操作的时候会调用到哪些类的哪些方法，这样就需要记录方法的调用，如果arthas能加上这样的功能就太棒了。

**Comment by kylixs** [comment]
想到的几种思路：
1）指定增强某几个包下的所有class的所有方法
     优点：  
          使用Java语言统计记录调用栈，比C/Rust编码低   
     缺点：   
          增强的class比较多，转换的时间太长，和jprofiler 的instrumentation 模式类似   
  
2）通过JVMTI agent 监控方法调用   
     优点：   
          不需要增强class，启动速度快
     缺点:   
         C/Rust 处理复杂逻辑编码难度较大   
         所有method调用都会触发回调，处理的方法数量太多，处理效率要优化
