### ISSUE TITLE
windows环境下方向键快捷键无效

### ISSUE THREAD

**Issue by oicq1699** [alibaba/arthas#1258]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.3
* Arthas 版本: 3.3.3
* 操作系统版本: windows 10
* 目标进程的JVM版本: jdk8
* 执行`arthas-boot`的版本: 3.3.3

### 重现问题的步骤

1. java -jar arthas-boot.jar
2.执行任意命令
3. 按 上，下，左，右 任意键盘方向键

### 期望的结果
左右键，为前进后退一个字符
上下键，为上一条，下一条命令

### 实际运行的结果

完全无效，没任何反应

**Comment by googleweb** [comment]
win10 jdk8 arthas3.3.9 同意问题，上下左右无效

**Comment by ytfrdfiw** [comment]
win10 jdk8 arthas3.3.9 同意问题，上下左右无效

**Comment by 2608027102** [comment]
使用telnet连接arthas可以实现上下方向键
```bash
telnet 127.0.0.1 3658
```

**Comment by hengyunabc** [comment]
试下最新的 3.4.3 版本，应该支持 cmd里各种快捷键了。
