### ISSUE TITLE
使用trace命令，返回“No class or method is affected”

### ISSUE THREAD

**Issue by lichunyang5156** [alibaba/arthas#1273]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 的版本： 3.3.3
* Arthas 版本: 3.3.3
* 操作系统版本: 3.10.0-957.27.2.el7.x86_64
* 目标进程的JVM版本: 1.8.0_11-b12
* 执行`arthas-boot`的版本: 3.3.3

### 重现问题的步骤

1.使用trace命令，查看测试环境springboot项目，返回如题问题。

2.按照前面大神提供的解决思路，都排查了，没发现问题，类已加载

**Comment by hengyunabc** [comment]
贴出具体的日志。最好有可重现的demo。

**Comment by lichunyang5156** [comment]
![image](https://user-images.githubusercontent.com/25053631/85969486-607d2c00-b9fa-11ea-9389-e9748da33d24.png)

**Comment by hengyunabc** [comment]
没有匹配到 run 函数，按提示说明排查。或者 jdk 反编译，查看代码是否有 run 函数。
