### ISSUE TITLE
有没有类似API一类的东西，使用上遇到了困难。

### ISSUE THREAD

**Issue by mirrorxue** [alibaba/arthas#1277]
想要通过PID来查询指定的JVM信息，但是并没有找到有类似的说明，但是Arthas实际上是具备这个功能的。

**Comment by hengyunabc** [comment]
目前没有。后面会有http api。 你是希望有什么api？怎样使用？

**Comment by hengyunabc** [comment]
参考： https://arthas.aliyun.com/doc/http-api.html
