### ISSUE TITLE
找不到tools.jar #187

### ISSUE THREAD

**Issue by dcz0622** [alibaba/arthas#1289]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.3.6
* 操作系统版本: CentOS Linux 7
* 目标进程的JVM版本: java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64
* 执行`arthas-boot`的版本: 同上, java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64

### 重现问题的步骤

```
java -jar arthas-boot.jar
```

### 期望的结果

Arthas正常启动。

### 实际运行的结果

```
Exception in thread "main" java.lang.IllegalArgumentException: Can not find tools.jar under java home: /xxx/xxx/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64/jre, please try to start arthas-boot with full path java. Such as /opt/jdk/bin/java -jar arthas-boot.jar
	at com.taobao.arthas.boot.ProcessUtils.findJavaHome(ProcessUtils.java:222)
	at com.taobao.arthas.boot.ProcessUtils.startArthasCore(ProcessUtils.java:233)
	at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:515)
```

### 使用疑问

* 目标进程的JVM是openjdk的JRE，不是JDK，没有tools.jar。而且我没有权限把tools.jar复制到JAVA_HOME文件夹里。请问在启动Arthas的时候可以手动指定tools.jar的路径吗？类似这样：
  ```
  java -jar arthas-boot.jar -Dtools.jar=./tools.jar
  ```
* 我可以用另外一个JVM版本运行Arthas吗？这样的话Arthas的JVM和目标进程的JVM不同。这样做有什么后果吗？

感谢！

**Comment by hengyunabc** [comment]
可以试下 

* 设置 JAVA_HOME 为新的带 tools.jar 的jdk 目录
* 试下用 全路径的  ,新的带 tools.jar 的jdk 来启动 arthas-boot.jar

**Comment by dcz0622** [comment]
更新：可以用另外一个带tools.jar的jdk来启动arthas-boot.jar

**Comment by bearxsh** [comment]
> 更新：可以用另外一个带tools.jar的jdk来启动arthas-boot.jar

请问怎么下载带tools.jar的jdk啊

**Comment by dcz0622** [comment]
@bearxsh 在Oracle或者openjdk官网下载。注意是jdk不是jre。

**Comment by bearxsh** [comment]
> @bearxsh 在Oracle或者openjdk官网下载。注意是jdk不是jre。

谢谢，已经解决了^_^

**Comment by pwjack** [comment]
我的mac电脑，jdk的版本是1.8.0_271，也出现了这个问题。
解决方案：
设置一下JAVA_HOME就解决了。
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home

**Comment by amadisme** [comment]
macos需要把java home放在文件的最前面才形
