### ISSUE TITLE
arthas 如何配合nohup命令在后台运行？

### ISSUE THREAD

**Issue by JoneZhu** [alibaba/arthas#1295]
### 环境信息

* `arthas-boot.jar`  的版本： 3.3.6 
* Arthas 版本: 3.3.6 
* 操作系统版本: macOS 10.15.5 (19F101)
* 目标进程的JVM版本: build 1.8.0_151-b12

### 重现问题的步骤

1. 下载arthas-demo.jar 和arthas-boot.jar
wget https://alibaba.github.io/arthas/arthas-demo.jar
wget https://arthas.gitee.io/arthas-boot.jar
2. nohup java -jar arthas-demo.jar > myout.file 2>&1 &  运行arthas-demo.jar
3. nohup java -jar arthas-boot.jar 1138 &  运行arthas-boot.jar,1138 是arthas-demo.jar的进程id
4. 运行jobs 命令输出 
[1]    running    nohup java -jar arthas-demo.jar > myout.file 2>&1
[2]  + suspended (tty output)  nohup java -jar arthas-boot.jar 1138

### 期望的结果

arthas 能够正常在后台运行

### 实际运行的结果
arthas 的进程被挂起

```
➜  ~ nohup java -jar arthas-boot.jar 1138 &
[2] 2090
appending output to nohup.out                                                                                                                        
➜  ~ 
[2]  + 2090 suspended (tty output)  nohup java -jar arthas-boot.jar 1138
```

**Comment by kaixinbaba** [comment]
arthas这个脚本后台运行有什么实际的用途吗？

**Comment by yinwoods** [comment]
启动arthas的时候加一个 --attach-only 就可以了

**Comment by yulaixing** [comment]
> --attach-only

你好，这个参数的意思是什么 ，方便介绍下么。
## 仅附加目标进程，不连接，这是什么意思 ，多谢

**Comment by hengyunabc** [comment]
>  仅附加目标进程，不连接，这是什么意思 ，多谢

arthas有两个过程：

1. attach到目标机器上
2. 使用telnet去连接

在第2点会占据当前窗口。使用`--attach-only`参数之后，就不执行第2步了。
