### ISSUE TITLE
3.1.7 trace cost 无法监控到private方法

### ISSUE THREAD

**Issue by sdoseabow** [alibaba/arthas#1297]
我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
 生产排查过慢方法 打开2个终端 一个显示执行方法A入口  一个显示执行方法里的一个private方法B ，A打印B耗时150ms 但是B终端没显示trace cost信息

**Comment by hengyunabc** [comment]
用最新版，3.2.0 和 之前的版本，开多个窗口都有可能冲突。
