### ISSUE TITLE
openjdk14 Can not find java process. Try to pass <pid> in command line.

### ISSUE THREAD

**Issue by java2python** [alibaba/arthas#1300]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
--------------------------------------------------
Containers: 35
 Running: 34
 Paused: 0
 Stopped: 1
Images: 270
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.74GiB
Name: datapoint-node1
ID: XCZP:ROWM:HGUR:OEVE:ZKEG:JVYC:7SUW:PGSY:YFBC:IH6H:4W62:PHID
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### 重现问题的步骤

docker  exec -it  0d1089b20c98 /bin/bash -c "curl -O  https://alibaba.github.io/arthas/arthas-boot.jar && java -jar arthas-boot.jar"

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

```
[INFO] arthas-boot version: 3.3.6
[INFO] Can not find java process. Try to pass <pid> in command line.
Please select an available pid.
```

**Comment by java2python** [comment]
`# docker  exec -it  0d1089b20c98 /bin/bash -c "curl -O  https://alibaba.github.io/arthas/arthas-boot.jar && java -jar arthas-boot.jar 25"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  135k  100  135k    0     0  97032      0  0:00:01  0:00:01 --:--:-- 97032
[INFO] arthas-boot version: 3.3.6
[INFO] arthas home: /root/.arthas/lib/3.3.6/arthas
[INFO] Try to attach process 25
java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
[ERROR] Start arthas failed, exception stack trace:
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:74)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:124)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
[ERROR] attach fail, targetPid: 25`

**Comment by java2python** [comment]
```
# docker  exec -it  0d1089b20c98 /bin/bash -c "curl -O  https://alibaba.github.io/arthas/arthas-boot.jar && java -jar arthas-boot.jar 25"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  135k  100  135k    0     0  97032      0  0:00:01  0:00:01 --:--:-- 97032
[INFO] arthas-boot version: 3.3.6
[INFO] arthas home: /root/.arthas/lib/3.3.6/arthas
[INFO] Try to attach process 25
java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
[ERROR] Start arthas failed, exception stack trace:
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:74)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:124)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
[ERROR] attach fail, targetPid: 25

```

**Comment by hengyunabc** [comment]
试下单独执行 `docker  exec -it  0d1089b20c98 /bin/bash` ，进到docker里，再执行 `java -version` ，查看版本。

另外，检查安装是否完整的JDK。

**Comment by java2python** [comment]
谢谢支持, 安装的不是完整JDK
