### ISSUE TITLE
docker环境使用arthas中的mc命令报错【程序包..不存在】本地启动，进行mc编译不存在此问题

### ISSUE THREAD

**Issue by zhangbingxiao** [alibaba/arthas#1302]
报错信息：
[arthas@1]$ mc /tmp/TestController.java
Memory compiler error, exception message: Compilation Error
line: 12 , message: 程序包com.daihuowang.common.result不存在 ,
line: 13 , message: 程序包org.springframework.web.bind.annotation不存在 ,
line: 14 , message: 程序包org.springframework.web.bind.annotation不存在 ,
line: 15 , message: 程序包org.springframework.web.bind.annotation不存在 ,
line: 17 , message: 找不到符号
  符号: 类 RestController ,
line: 18 , message: 找不到符号
  符号: 类 RequestMapping ,
line: 21 , message: 找不到符号

去看arthas.log日志提示以下信息：
01 2020-07-10 09:48:44.479 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xd0c3ecc0, L:/127.0.0.1:3658] READ: [id: 0x12a2a10f, L:/127.0.0.1:3658 - R:/127.0.0.1:57760]
01 2020-07-10 09:48:44.482 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0xd0c3ecc0, L:/127.0.0.1:3658] READ COMPLETE
01 2020-07-10 09:48:44.486 INFO [nioEventLoopGroup-2-3:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2020-07-10 09:53:49.249 WARN [as-command-execute-daemon:arthas] [] [] [] Memory compiler error
com.taobao.arthas.compiler.DynamicCompilerException: Compilation Error
line: 12 , message: 程序包com.daihuowang.common.result不存在 ,
line: 13 , message: 程序包org.springframework.web.bind.annotation不存在 ,
line: 14 , message: 程序包org.springframework.web.bind.annotation不存在 ,
line: 15 , message: 程序包org.springframework.web.bind.annotation不存在 ,
line: 17 , message: 找不到符号

结束

**Comment by hengyunabc** [comment]
用 sc -d 查找类的 classloader hash。 mc 时用 -c 指定classloader。
