### ISSUE TITLE
 Unable to add JAR file to system class path

### ISSUE THREAD

**Issue by li-shaoke** [alibaba/arthas#1307]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.6
* Arthas 版本: 3.3.6
* 操作系统版本: windows 10
* 目标进程的JVM版本:jdk14, Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
* 执行`arthas-boot`的版本: 3.3.6

### 重现问题的步骤

1. java -jar arthas-boot.jar
2. 12 Then hit ENTER.
3. ERROR

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

```
D:\dev_software\arthas>java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.3.6
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 3924 org/netbeans/Main
  [2]: 5804 arthas-demo.jar
2
[INFO] arthas home: C:\Users\lsk\.arthas\lib\3.3.6\arthas
[INFO] Try to attach process 5804
com.sun.tools.attach.AgentLoadException: Unable to add JAR file to system class path
[ERROR] Start arthas failed, exception stack trace:
        at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:162)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:105)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:124)
[ERROR] attach fail, targetPid: 5804
```

**Comment by hengyunabc** [comment]
检查下jvm 参数，或者进程参数，或者环境变量里有没有 禁止加 jar到 SystemClassLoader的。

**Comment by hengyunabc** [comment]
可能是应用启用了 SecurityManager，参考： https://github.com/alibaba/arthas/issues/156

**Comment by hengyunabc** [comment]
这个有两种可能。

1. 一种是 windows下的安全策略，可能阻止了jdk的某些行为。

2. 一种是arthas-boot可能是在 windows cygwin下启动的，然后它的路径可能会在jdk代码访问时有问题。

解决办法： 

* 在cygwin下面，可以尝试下载arthas全量包，然后解压到cygwin里的目录再使用。
* 注意要attach的java进程要保证也是在 cygwin下面启动的
