### ISSUE TITLE
java -jar arthas-boot.jar  启动找不到进程

### ISSUE THREAD

**Issue by 253845280** [alibaba/arthas#1324]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.6
* Arthas 版本: 3.3.6
* 操作系统版本: Linux  3.10.0-862.el7.x86_64 
* 目标进程的JVM版本: 8
* 执行`arthas-boot`的版本: 

### 重现问题的步骤

1. 启动的时候  /tmp/poifiles/  进程不存在
2. ps -ef | grep java 存在

### 期望的结果
  修改启动检查进程的方式 改成 不要从 /tmp/poifiles/ 读取
  
### 实际运行的结果
   直接启动  java -jar arthas-boot.jar   没有可选进程

**Comment by xiongwenjia** [comment]
1. 查看下java进程 与当前操作arthas 的用户是否一致。 
2. 在java所在jdk目录下执行 jps，查看是否有该进程。

**Comment by 253845280** [comment]
> 1. 查看下java进程 与当前操作arthas 的用户是否一致。
> 2. 在java所在jdk目录下执行 jps，查看是否有该进程。
