### ISSUE TITLE
启动脚本报错

### ISSUE THREAD

**Issue by tengwei-lewis** [alibaba/arthas#133]
启动报错：Arthas script version: 3.0.2
Try out Arthas online: /arthas/web-console
awk: can't open $2>"1.5"{print $2}
illegal ENV, please set $JAVA_HOME to JDK6+

当前服务器上的jdk是1.7   JAVA_HOME也是有的，不懂为什么这样，求大神解答

**Comment by ralf0131** [comment]
Hi, 

Your `as.sh` is 3.0.2 which is out-of-date, please re-install the latest `as.sh` (3.0.4) and try again.

**Comment by tengwei-lewis** [comment]
Arthas script version: 3.0.4
awk: can't open $2>"1.5"{print $2}
illegal ENV, please set $JAVA_HOME to JDK6+
换成新版本也是这样

**Comment by GaoJean** [comment]
我也遇到同样的问题
Java version: openjdk version "1.8.0_181"

Arthas script version: 3.0.4
illegal ENV, please set $JAVA_HOME to JDK6+

不懂，求解答

**Comment by hengyunabc** [comment]
@tengwei-lewis @GaoJean  `bash -x ./as.sh` 来执行，看具体哪里出错。 在命令行` echo $JAVA_HOME` 看结果

**Comment by tengwei-lewis** [comment]
![image](https://user-images.githubusercontent.com/18061331/46242130-377bd180-c3f7-11e8-80c7-dba5963e4e4d.png)
会不会是操作系统的语法不同 ，我这边使用的是solaris
