### ISSUE TITLE
arthas进不了tomcat应用

### ISSUE THREAD

**Issue by RecursionHs** [alibaba/arthas#1333]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息 redhat7.3 jdk8

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1和3.3.3
* 操作系统版本: redhat7.3
* 目标进程的JVM版本: 8

### 重现问题的步骤

1. ./as.sh或java -jar arthas-boot.jar
2. 随便选择一个端口
3. 长久时间都进入不了相应的程序，程序是tomcat应用，同一套代码都进不去。没有任何报错，就是卡在那里

### 期望的结果
为什么这一套代码不能进去？可能是我们自己代码什么引起的呢？跟tomcat版本应该没关系，同一版本的tomcat其它应用能够进去！

就是没有报错，看了arthas日志也没有报错就提示Bind什么什么的，没报错！

**Comment by hengyunabc** [comment]
ps aux | grep java ，检查有没有 arthas 的进程，再用 jstack 查看具体的进程的栈，看阻塞在哪里。

另外，检查应用本身是否在调试状态，可能到断点了。

另外，试下 arthas-demo.jar ，看能成功不。
