### ISSUE TITLE
Why still use 'telnet' protocol ?

### ISSUE THREAD

**Issue by zhanggang807** [alibaba/arthas#134]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: xxx
* Operating System version: xxx
* Java version of target JVM: xxx
* Java version of JVM used to attach: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by ralf0131** [comment]
What protocol do you expect?

**Comment by zhanggang807** [comment]
ssh
