### ISSUE TITLE
NullPointerException at WildcardMatcher

### ISSUE THREAD

**Issue by earayu** [alibaba/arthas#135]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.x
* Operating System version: MAC OS X 10.13.4
* Java version of target JVM: 1.8
* Java version of JVM used to attach: 1.8

### Actual Result

Didn't check NULL for inputs at `com.taobao.arthas.core.util.matcher.WildcardMatcher#match(String string,String pattern,int stringStartNdx,int patternStartNdx)`.
maybe the method should return false, if `string` or `pattern` is NULL. just like the logic in `RegexMatcher`

```
java.lang.NullPointerException
	at com.taobao.arthas.core.util.matcher.WildcardMatcher.match(WildcardMatcher.java:27)
	at com.taobao.arthas.core.util.matcher.WildcardMatcher.matching(WildcardMatcher.java:18)
	at com.taobao.arthas.core.util.matcher.WildcardMatcherTest.testMatchingWithNullInputs(WildcardMatcherTest.java:13)
```

**Comment by ralf0131** [comment]
Hi, could you please send a pull request to fix it?

**Comment by earayu** [comment]
> Hi, could you please send a pull request to fix it?

pleasure to

**Comment by earayu** [comment]
I'am wondering what we would like to behave when the inputs for `matchers` are null.
* `EqualsMatcher` returns true for params:`pattern=null, target=null`
* `RegexMatcher` returns false for params:`pattern=null, target=null`
maybe we should just throw an exception if the pattern is null at RegexMatcher and WildcardMatcher

**Comment by earayu** [comment]
@ralf0131

**Comment by ralf0131** [comment]
thrown Exception in Match looks expensive to me.

If pattern or target is null, return false for `RegexMatch` or `WildcardMatcher` seems a good choice.

**Comment by earayu** [comment]
> thrown Exception in Match looks expensive to me.
> 
> If pattern or target is null, return false for `RegexMatch` or `WildcardMatcher` seems a good choice.

ok, I can do that

**Comment by ralf0131** [comment]
Fixed.
