### ISSUE TITLE
功能建议：jad命令能否支持反编译jar包？

### ISSUE THREAD

**Issue by yx91490** [alibaba/arthas#1353]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.3
* Arthas 版本: 3.3.3
* 操作系统版本: CentOS
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.3.3

### 重现问题的步骤

无

### 期望的结果

jad命令能够反编译静态的jar包里面的类

### 实际运行的结果

只能反编译JVM运行时的类

```
无
```

**Comment by hengyunabc** [comment]
直接下个 cfr： https://github.com/leibnitz27/cfr

**Comment by yx91490** [comment]
> 直接下个 cfr： https://github.com/leibnitz27/cfr

也不失为达到目的的一种方法，但是还是想一套东西全搞定，哈哈

**Comment by kylixs** [comment]
可以给jad增加一个选项，指定外部的class文件路径或者jar + class name，反编译外部类，比如dump出来的增强类。
