### ISSUE TITLE
as.sh中version_gt函数在mac下执行结果不能达到预期

### ISSUE THREAD

**Issue by lzc-alioo** [alibaba/arthas#1366]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.7
* Arthas 版本: 3.3.7
* 操作系统版本: macOS 10.15.6
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: 3.3.7

### 重现问题的步骤

1. 查看本地之前下载过的arthas版本
```

% pwd
/Users/mac/.arthas/lib
% ll
total 0
drwxr-xr-x  4 mac  staff  128 Jul 24 17:49 .
drwxr-xr-x  4 mac  staff  128 Oct 30  2019 ..
drwxr-xr-x  3 mac  staff   96 Jun  3 08:53 3.3.2
drwxr-xr-x  3 mac  staff   96 Jul  4 23:34 3.3.6
```

2. pull arthas 最新代码,执行 sh -x as.sh 这里没有附加任何参数，选择一个pid后回车
```
        local remote_version=$(get_remote_version)
        local arthas_local_version=$(get_local_version)
        if $(version_gt $remote_version $arthas_local_version) ; then
            update_if_necessary "${remote_version}" || echo "update fail, ignore this update." 1>&2
        fi

```
执行version_gt函数之前，可以知道remote_version=3.3.7 ,arthas_local_version=3.3.6

3. version_gt函数如下，可以看出来原作者的意思是比较下2个版本，
当remote_version ($1)大于arthas_local_version($2) 时返回值是0
```
version_gt()
{
    [[ $1 == $2 ]] && return 1
    local gtVersion=`echo -e "$1\n$2" | sort | tail -1`
    [[ $gtVersion == $1 ]] && return 0 || return 1
}
```

### 期望的结果

根据上面的数据remote_version=3.3.7 ,arthas_local_version=3.3.6，执行了version_gt()应该返回0才对，然后就会执行这个if里面的update_if_necessary函数代码逻辑
```

        if $(version_gt $remote_version $arthas_local_version) ; then
            update_if_necessary "${remote_version}" || echo "update fail, ignore this update." 1>&2
        fi
```

### 实际运行的结果

实际上压根就没有执行update_if_necessary函数，我使用sh -x as.sh执行结果如下

```
++ version_gt 3.3.7 3.3.6
++ [[ 3.3.7 == 3.3.6 ]]
+++ echo -e '3.3.7\n3.3.6'
+++ sort
+++ tail -1
++ local gtVersion=3.3.6
++ [[ 3.3.6 == 3.3.7 ]]
++ return 1
++ get_local_version

```
可以看到version_gt函数出参结果是1，没有达到预期造成的。

---

基于上面的情况我做了一下实验，修改了一下versio_gt函数
说明，只是将  local gtVersion=`echo -e "$1\n$2" | sort | tail -1` 修改成了 local gtVersion=`echo  "$1\n$2" | sort | tail -1`
```

version_gt()
{
    [[ $1 == $2 ]] && return 1
    local gtVersion=`echo  "$1\n$2" | sort | tail -1`
    [[ $gtVersion == $1 ]] && return 0 || return 1
}
```

再次执行sh -x as.sh结果就是正确的（version_gt函数返回值是0，也执行了被这个if包含的update_if_necessary函数了）

**Comment by hengyunabc** [comment]
欢迎提交PR来修复

**Comment by lzc-alioo** [comment]
进一步验证发现mac下使用zsh 才会有上述问题，默认bash就没有这个问题，这里写了一个简单的脚本version_test.sh来说明下：

```
% more version_test.sh

version_test()
{

remote_version=3.3.7
arthas_local_version=3.3.6

local gtVersion=`echo -e "$remote_version\n$arthas_local_version" | sort | tail -1`
echo gtVersion:$gtVersion

}

version_test
```

![image](https://user-images.githubusercontent.com/33567235/88385894-ddc17400-cde1-11ea-8279-eeb1d75bcc7c.png)

**Comment by lzc-alioo** [comment]
> 欢迎提交PR来修复

没问题

**Comment by lzc-alioo** [comment]
解决这个问题的思路：我首先想到的是在shell下识别当前是bash还zsh环境，然后根据环境提供执行不同的语句就可以了
```
bash:
local gtVersion=`echo -e "$remote_version\n$arthas_local_version" | sort | tail -1`
zsh:
local gtVersion=`echo "$remote_version\n$arthas_local_version" | sort | tail -1`
```
然而在识别bash还zsh环境时，查阅了很多资料，都没有找到合适的语句，网上常见的方式
1.比如使用$0，如果直接在命令行中执行是可以的，但是当放置到shell脚本中，$0的值被重写了，就变成了当前shell脚本的名字，只好放弃
2.比如使用echo $SHELL，这种方式我在测试时无论bash还zsh环境时，执行结果都是相同的，也只好放弃

困惑之后，回到这个问题本身，就是为了比较2个字符串的大小而已，就干脆不使用echo -e了，也就绕过了这个兼容性的问题，另外相比之前使用了2次判断，1次排序，现在只使用了1次判断就搞定了，重写之后的代码如下：
```
version_gt()
{
    local remote_version=$1
    local arthas_local_version=$2
    [[ "$remote_version" > "$arthas_local_version" ]] && return 0 || return 1
}


```
