### ISSUE TITLE
教程文档无法打开

### ISSUE THREAD

**Issue by wangj3081** [alibaba/arthas#1392]
[基础教程](https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-basics)
[进阶教程](https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-advanced)

这两个教程文档链接都无法打开

**Comment by hengyunabc** [comment]
试下国内的镜像站： https://arthas.gitee.io/arthas-tutorials?language=cn&id=arthas-basics

**Comment by hengyunabc** [comment]
换了个 js的cdn，现在速度应该上去了。
