### ISSUE TITLE
mac本地, 当arthas调试的程序停止以后,arthas再次启动无法使用,选择pid后就卡死

### ISSUE THREAD

**Issue by gzdzss** [alibaba/arthas#1396]
### 环境信息

* Arthas 版本: 3.3.7
* 操作系统版本: mac os 10.15.3
* 目标进程的JVM版本: 1.8.0_231-b11
* 执行`arthas-boot`的版本: 3.3.7

### 重现问题的步骤

1.  启动一个java 服务 [ demo.jar]
2.  java -jar arthas-boot.jar   选择 上面启动的服务
3.  停止 [demo.jar] ,此时 arthas 会自动退出.
4.  再次  启动 [demo.jar]
5.  java -jar arthas-boot.jar 启动以后 选择 任何一个pid 都会卡死在选择页面

### 期望的结果

可正常使用

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

2020-07-30 18:57:14 [arthas-binding-thread] INFO  c.t.a.core.server.ArthasBootstrap -as-server started in 180 ms

Arthas server already bind.

**Comment by kylixs** [comment]
运行的arthas-boot.jar是什么shell？

**Comment by gzdzss** [comment]
/bin/zsh

**Comment by gzdzss** [comment]
关闭终端,重新打开再启动 arthas-boot.jar即可~
