### ISSUE TITLE
为什么web console页面不支持复制 粘贴呀

### ISSUE THREAD

**Issue by Daiqiangdeveloper** [alibaba/arthas#1397]
为什么web console页面不支持复制 粘贴呀   操作好不方便

**Comment by hengyunabc** [comment]
具体OS和浏览器版本，试下用 chrome 。

**Comment by jasonfjtian** [comment]
可以试试使用IE浏览器试试，我也是使用chrome 、edge、firefox都不能粘贴，然后换了IE试了下可以！

**Comment by huogithub** [comment]
使用cmd  telnet 命令可以复制

**Comment by kylixs** [comment]
请参考：https://github.com/alibaba/arthas/issues/1056
