### ISSUE TITLE
在执行命令的时候，有的时候我想通过点击方向键上，或者下来切换历史指令不生效，甚至点击方向键左右移动也不生效，不是特别方便

### ISSUE THREAD

**Issue by XudongFu** [alibaba/arthas#1398]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.7
* Arthas 版本: xxx
* 操作系统版本: win 10
* 目标进程的JVM版本: 1.8.0_71-b15
* 执行`arthas-boot`的版本: xxx

### 期望的结果
按上下方向键可以切换历史指令

**Comment by xiaozhiliaoo** [comment]
@XudongFu  你是linux系统还是windows，我的linux系统可以上下查看历史记录，但是windows的cmder里面和你的现象一样，上下切换历史命令不生效。

**Comment by 2608027102** [comment]
使用telnet连接arthas可以实现上下方向键
```bash
telnet 127.0.0.1 3658
```

**Comment by hengyunabc** [comment]
试下最新的 3.4.3 版本。
