### ISSUE TITLE
trace命令查找耗时百分比不方便

### ISSUE THREAD

**Issue by xiaozhiliaoo** [alibaba/arthas#1402]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

我希望在trace命令跟踪方法耗时时候，可以看到耗时百分比，这样对优化比较有指导，全部一个一个看比较麻烦。

**Comment by hengyunabc** [comment]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/1683936/186845033-7ea1e6cb-cbf3-4878-9d0b-683f0bfa82a5.png">
已支持。
