### ISSUE TITLE
执行arthas-client.jar -c stop卡住无法退出进程

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/arthas#1409]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.3
* Arthas 版本: 3.3.3
* 操作系统版本: linux6
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 1.8

### 重现问题的步骤

1. 我用的是3.3.7 arthas-tunnel-server去做web attach进程功能,web-console部署是3.3.7版本,目标机器是3.3.3版本;
attach前先停止当前的arthas,避免其他进程已经连接
第一次:sudo -i -u finloan java -jar /home/q/arthas/arthas-client.jar -c stop
第二次:sudo -i -u finloan java -jar /home/q/arthas/arthas-boot.jar 31523 --tunnel-server 'ws://10.221.24.76:7777/ws' --agent-id '10.209.20.238' --attach-only

当我再次执行上面的命令时
然而执行stop的时候停止了没反应,当我再次执行的时候也是这样
ps命令查看有很多执行的进程在,也没有自动销毁
![批注 2020-08-07 163109](https://user-images.githubusercontent.com/3397316/89626486-1bd39300-d8cc-11ea-8a26-4c83fa45b88f.png)

2. 我kill掉所有的stop命令后,发现还是一样的结果

3. 我用java -jar arthas-boot.jar进去发现显示已经连接了,然后就报连接错误
![image](https://user-images.githubusercontent.com/3397316/89627142-fa26db80-d8cc-11ea-84e5-e6367bab63fd.png)

### 期望的结果

能正常退出arthas
可能是第一和第二的脚本我执行快了,导致attach到内部卡住了,我现在只能停止我的应用进程才能释放的掉arthas的命令进程.
否则我kill arthas的进程一点用都没有.

再次请教是否有其他命令方式能正常退出的?

### 再补充一下
我的命令是通过shell脚本执行的,不知道是否是脚本执行导致的,也麻烦帮忙分析分析
./arthas.sh stop > stop.log > 2>&1 &

**Comment by hengyunabc** [comment]
试下最新的 3.3.7 版本

**Comment by cookiejoo** [comment]
> 试下最新的 3.3.7 版本

当前的情况有啥版本可以退出不?我现在只能重启应用才能正常使用arthas了
