### ISSUE TITLE
Profiler的问题

### ISSUE THREAD

**Issue by HashZhang** [alibaba/arthas#1410]
我在docker镜像里面使用arthas，profiler命令报错：
```
Perf events unavailable.
```
这个是什么命令缺失么

**Comment by kylixs** [comment]
请参考Async profiler的排查文档: 
https://github.com/jvm-profiling-tools/async-profiler#troubleshooting
https://github.com/jvm-profiling-tools/async-profiler#profiling-java-in-a-container

**Comment by HashZhang** [comment]
ok
