### ISSUE TITLE
3.3.0 版本之后，使用 arthas-boot 去 attach，执行任意命令之后，再退出，本地的 terminal会卡住

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1412]
重现过程：

1. 启动arthas-demo 
2. 下载 3.3.0 版本， https://arthas.aliyun.com/download/3.3.0?mirrot=aliyun 解压，cd 到目录里，执行 java -jar ./arthas-boot.jar
3. attach arthas-demo.jar ，然后执行命令，再q退出

多次重复上面3步，很容易重现。

3.2.0 不能复现，应该是 这个 pr 引起的： https://github.com/alibaba/arthas/pull/1119/files 。

并且 `as.sh` 不能复现。

可能是这里引起的： https://github.com/alibaba/arthas/blob/arthas-all-3.3.0/boot/src/main/java/com/taobao/arthas/boot/ProcessUtils.java#L348

**Comment by Huangxuny1** [comment]
我记得 `as.sh`  也会遇到这个问题 . 这是我  2020/6月时候截的图. 聊天记录过期了比较模糊
![image](https://user-images.githubusercontent.com/21981606/89853541-3eafc100-dbc4-11ea-9b43-552befa712a4.png)

如果没记错的话 `JSTACK` 卡在 `scanner.readline()` 

在 shell 里 `CTRL-Z`  再 `reset` 可以临时解决

**Comment by hengyunabc** [comment]
`as.sh`里有 telnet 时应该是优先用原生的，试下改 telnet 脚本，默认用 arthas-client.jar 看能不能重现。

但是单独执行 `java -jar ./arthas-client.jar`不能重现。

**Comment by kylixs** [comment]
找到一个可能产生此问题的改动： 3.3.0版本arthas-boot.jar增加telnet 端口检测功能，调用了两次arthas-client的函数：

* 检测端口时调用：com.taobao.arthas.client.TelnetConsole#process(java.lang.String[])
* 连接Arthas时调用： com.taobao.arthas.client.TelnetConsole#main(String[] args) ->  TelnetConsole#process()

调用了两次TelnetConsole#process()。其中有一段是jline的`Ctrl+c`按键处理，执行了两次，但没有还原terminal设置，导致执行arthas-boot.jar后，terminal shell的`Ctrl+c`按键失效。可能是因为此原因导致第二次运行arthas-boot.jar后，`Enter`输入无效，出现这种情况时，`Enter`输入变成`^M`字符，不是换行符，scanner.readLine()没法完成。

fix pr: https://github.com/alibaba/arthas/pull/1413
macOS + zsh 验证，反复执行arthas-boot.jar attach和退出，没有再出现卡住的问题。

**Comment by Huangxuny1** [comment]
![image](https://user-images.githubusercontent.com/21981606/89856439-dbc22800-dbcb-11ea-85cf-1d75e0998407.png)
这个也是之前的截图. 但是现在似乎也已经修复了 .  印象中是 一直 attach stop attach stop  会出现的问题 .

**Comment by Huangxuny1** [comment]
问题似乎依旧存在  
![image](https://user-images.githubusercontent.com/21981606/89864060-de2d7d80-dbdd-11ea-827e-bf64ac604313.png)

**Comment by hengyunabc** [comment]
@Huangxuny1 
可以稳定重现不？具体重现步骤？

**Comment by Huangxuny1** [comment]
1.  `cd ~/.arthas/lib/3.3.9.20200811141134/arthas`
2.  `nohup java -jar arthas-demo.jar & `
3.  `java -jar arthas-boot.jar `
4.  attach demo 
5.  `trace demo.MathGame print ` 
6.  有内容输出后  stop 

7.  goto 3

![image](https://user-images.githubusercontent.com/21981606/89865084-a7586700-dbdf-11ea-8fa5-3c78638403bb.png)
![image](https://user-images.githubusercontent.com/21981606/89865100-af180b80-dbdf-11ea-9d6d-7253c0adaee6.png)

ENV

```
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)


Ubuntu 18.04.4 LTS   阿里云  使用vscode remote 连接
```

**Comment by kylixs** [comment]
执行arthas-boot.jar出现问题的shell：
 
```bash
 % stty
speed 9600 baud;
lflags: echoe echoke echoctl pendin
iflags: -icrnl -ixon iutf8
oflags: -oxtabs
cflags: cs8 -parenb
dsusp   
<undef> 
```


正常的shell：

```bash
% stty
speed 9600 baud;
lflags: echoe echoke echoctl pendin
iflags: iutf8
oflags: -oxtabs
cflags: cs8 -parenb
```

**Comment by kylixs** [comment]
@Huangxuny1  改进了restore terminal的方式 #1415，请测试一下master分支。
我本地重复执行arthas-boot.jar - attach - stop ，没有出现卡住了。

**Comment by Huangxuny1** [comment]
> @Huangxuny1 改进了restore terminal的方式 #1415，请测试一下master分支。
> 我本地重复执行arthas-boot.jar - attach - stop ，没有出现卡住了。

ok , perfect !
