### ISSUE TITLE
用jvm查看命令的时候  INPUT-ARGUMENTS中显示的参数有重复的是怎么回事

### ISSUE THREAD

**Issue by bbf13** [alibaba/arthas#1425]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

![cf](https://user-images.githubusercontent.com/37948929/90109507-811cfd80-dd7e-11ea-9d4b-14528c968f8a.png)

**Comment by nickChenyx** [comment]
看这个是你运行时传入的参数，是不是你们自己的部署脚本写错了。
