### ISSUE TITLE
trace命令无响应，直到30分钟超时，什么原因？

### ISSUE THREAD

**Issue by deepeye** [alibaba/arthas#1430]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.7
* Arthas 版本: 3.3.9
* 操作系统版本: centos7.6
* 目标进程的JVM版本: 1.8.0_201
* 执行`arthas-boot`的版本: 1.8.0_201

### 重现问题的步骤

trace com.socialallstar.userdts.schdule.DouyinPromotionsConsumer reciveDouyinPromotions
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 474 ms, listenerId: 7

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

session (4642108b-2600-4e23-9ff5-25ba25706c6e) is closed because session is inactive for 30 min(s).

**Comment by kylixs** [comment]
目标方法是否被调用？查看一下日志文件是否有错误信息
