### ISSUE TITLE
关于min、max、total、count概念的理解？

### ISSUE THREAD

**Issue by deepeye** [alibaba/arthas#1432]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.3.7
* Arthas 版本: 3.3.9
* 操作系统版本: centos7.6
* 目标进程的JVM版本: 
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤
count是指当前方法 执行了22次吗？
+---[min=8.796872ms,max=34.456621ms,total=321.617817ms,count=22] com.socialallstar.userdts.oss.AliyunCloudStorageService:uploadFile() #165

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
`---ts=2020-08-14 16:17:45;thread_name=org.springframework.kafka.KafkaListenerEndpointContainer#0-1-C-1;id=86;is_daemon=false;priority=5;TCCL=org.springframework.boot.loader.LaunchedURLClassLoader@31cefde0
    `---[769.879322ms] com.socialallstar.userdts.schdule.DouyinAwemeConsumer:reciveDouyinAweme()
        +---[0.006062ms] org.apache.kafka.clients.consumer.ConsumerRecord:value() #52
        +---[7.767392ms] org.json.JSONObject:<init>() #56
        +---[0.003173ms] org.json.JSONObject:getJSONObject() #57
        +---[0.002331ms] org.json.JSONObject:getJSONObject() #58
        +---[0.002455ms] org.json.JSONObject:getLong() #59
        +---[0.002846ms] org.json.JSONObject:isNull() #60
        +---[0.002996ms] org.json.JSONObject:getJSONArray() #67
        +---[min=0.0016ms,max=0.003076ms,total=0.044217ms,count=23] org.json.JSONArray:length() #75
        +---[min=0.001587ms,max=0.00318ms,total=0.042133ms,count=22] com.socialallstar.userdts.domain.DouyinAweme:<init>() #77
```

**Comment by nickChenyx** [comment]
应该是吧，[文档](https://alibaba.github.io/arthas/trace.html#id6)中描述的是

> [0,0,0ms,11]xxx:yyy() [throws Exception]，对该方法中相同的方法调用进行了合并，0,0,0ms,11 表示方法调用耗时，min,max,total,count；throws Exception 表明该方法调用中存在异常返回

这里的 count 就是函数的运行次数，min 最小运行时间，max 最大运行时间，total 是这个函数的总耗时吧

**Comment by deepeye** [comment]
> 应该是吧，[文档](https://alibaba.github.io/arthas/trace.html#id6)中描述的是
> 
> > [0,0,0ms,11]xxx:yyy() [throws Exception]，对该方法中相同的方法调用进行了合并，0,0,0ms,11 表示方法调用耗时，min,max,total,count；throws Exception 表明该方法调用中存在异常返回
> 
> 这里的 count 就是函数的运行次数，min 最小运行时间，max 最大运行时间，total 是这个函数的总耗时吧

之前我也是 这么理解，但是上面方法只完成一次调用，为何显示22次这？

**Comment by kaixinbaba** [comment]
我也有这个疑惑，我外层方法只调用了一次但是显示的count是20，而且不管调用几次都是20，我源码中肉眼debug也没看到这个20是怎么来的
