### ISSUE TITLE
The telnet port 3658 is used by process 3490 instead of target process 4050, you will connect to an unexpected process.

### ISSUE THREAD

**Issue by chenguangwu** [alibaba/arthas#1441]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.9
* Arthas 版本: 3.3.9
* 操作系统版本: CentOS 7
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.3.9

### 重现问题的步骤

1. 系统运行多个jar.
2. 启动arthas,选择一个进程,操作完成后退出.
3. 重新启动arthas, 选择另外一个进程,提示报错

### 期望的结果

可以自由切换进程

### 实际运行的结果

[INFO] arthas home: /root/.arthas/lib/3.3.9/arthas
[ERROR] The telnet port 3658 is used by process 3490 instead of target process 4050, you will connect to an unexpected process.
[ERROR] 1. Try to restart arthas-boot, select process 3490, shutdown it first with running the 'stop' command.
[ERROR] 2. Or try to stop the existing arthas instance: java -jar arthas-client.jar 127.0.0.1 3658 -c "stop"
[ERROR] 3. Or try to use different telnet port, for example: java -jar arthas-boot.jar --telnet-port 9998 --http-port -1

**Comment by chenguangwu** [comment]
重新启动arthas,还可以选择第一次操作的进程, 选择其他进程会报错.

**Comment by hengyunabc** [comment]
提示很清楚啊 ，连上原来的进程，执行`stop`，停止。 

或者设置不同的端口。

**Comment by supery-chen** [comment]
我无法连接上原来的进程,应该怎么😲
