### ISSUE TITLE
请问 arthas-spring-boot-starter 的主要作用是什么呢? 怎么使用呢

### ISSUE THREAD

**Issue by ifuncat** [alibaba/arthas#1442]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
让应用在启动时，就直接开启 arthas，不需要再动态attach。 

* 比如一些分布式应用，像流计算等，进程是动态启动的。用户没办法确定是哪个进程跑在哪个机器上。
* 比如有一些公司不允许开发登陆机器上执行脚本

这时，如果在公司内部部署了一个 tunnel server，这样子直接可以在线诊断应用。

**Comment by sealdoomer** [comment]
我集成了arthas spring boot starter, 启动能把进程启起来，但是连不上tunnel-server,请问有同学知道怎么解决吗
