### ISSUE TITLE
arthas starter 非spring boot应用使用疑问

### ISSUE THREAD

**Issue by zhizhanxue** [alibaba/arthas#1449]
非spring boot项目启东arthasAgent，连接不上tunnel-server
gradle:
  compile group: 'com.taobao.arthas', name: 'arthas-agent-attach', version: '3.3.9'
  compile group: 'com.taobao.arthas', name: 'arthas-packaging', version: '3.3.9'
  compile group: 'net.bytebuddy', name: 'byte-buddy-agent', version: '1.10.12'
方式1：java code:
Map<String, String> configMap = new HashMap<>();
configMap.put("arthas.tunnel-server","ws://10.203.6.102:7777/ws");
configMap.put("arthas.agent-id","zhanxue123");
new ArthasAgent(configMap, null, false, null).init();
方式2：/resource/arthas.properties:
arthas.tunnel-server = ws://10.203.6.102:7777/ws
arthas.agent-id = 123test

试用以上两种方式配置，http://127.0.0.1:3658/  session命令结果没都有agentId，推测没有连上。
telnet  10.203.6.102 7777可正常访问

**Comment by zhizhanxue** [comment]
![image](https://user-images.githubusercontent.com/46948444/90596787-55889000-e222-11ea-88f4-6aa7615e687d.png)
本地测试，3658和8080端口均可以访问

**Comment by hengyunabc** [comment]
直接用原生的arthas zip，解压后有 arhtas.properties， 试下修改里面的配置，再启动。看下是否能连接。

确认是具体问题在哪个环节。

**Comment by zhizhanxue** [comment]
使用原生的arthas zip启动，可以连上tunnel server。应用里依赖jar包，无agentId

**Comment by zhizhanxue** [comment]
使用原生的arthas zip启动，可以连上tunnel server。应用里依赖jar包,配置arthas.properties，ArthasAgent.attach();启动连不上tunnel server

**Comment by hengyunabc** [comment]
#1471
