### ISSUE TITLE
arthas-tunnel-server没有过期释放连接

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/arthas#1450]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

环境信息
arthas-boot.jar 或者 as.sh 的版本： 3.3.3
Arthas 版本: 3.3.3
操作系统版本: linux6
目标进程的JVM版本: 1.8
执行arthas-boot的版本: 1.8

java -jar /home/q/arthas/arthas-boot.jar 31523 --tunnel-server 'ws://10.221.24.76:7777/ws' --agent-id '10.209.20.238' --attach-only
我的问题是我用arthas-tunnel-server连接了目标机器,但是一天都没有操作了,下次打开页面还是直接连接着.
这连接了以后不会释放连接吗?释放会存在性能影响?

**Comment by hengyunabc** [comment]
agent到 tunnel server是会自动重连的。  web console到  tunnel server应该是没有超时的。 这个对性能没啥影响。

参考： https://github.com/alibaba/arthas/tree/master/tunnel-server
