### ISSUE TITLE
tunnel-server支持登录才能访问吗

### ISSUE THREAD

**Issue by billysAnna** [alibaba/arthas#1462]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* arthas-spring-boot-starter: 3.3.9
* arthas-tunnel-server版本: 3.3.9

### 重现问题的步骤

1. 访问<http://127.0.0.1:8080>可直接访问到页面

### 期望的结果

希望必须输入用户名/密码才能访问

### 说明

- 看到arthas-tunnel-server-3.3.9.jar中的application.properties中有`spring.security.user.name=arthas`，但不知道怎么使用。
- 尽管访问<http://127.0.0.1:8080>后必须输入IP/Port/AgentId才能连接使用，但是不想让未登录用户看到任何页面。

**Comment by hengyunabc** [comment]
tunnel-server就是一个简单的spring boot web应用，权限需要自己开发。 也欢迎提交相关的PR。

**Comment by dreamcasher** [comment]
> tunnel-server就是一个简单的spring boot web应用，权限需要自己开发。 也欢迎提交相关的PR。

tunnel-server本身是引入了security，是想使用该框架的鉴权功能，依据如下：com.alibaba.arthas.tunnel.server.endpoint.ActuatorSecurity这个类的功能是为了防止endpoint的请求被security拦截。
问题在于该代码里面使用了anyRequest().permitAll()，导致除了endpoint的其他请求全部不用鉴权，可以修改成anyRequest().authenticated()

**Comment by hengyunabc** [comment]
> > tunnel-server就是一个简单的spring boot web应用，权限需要自己开发。 也欢迎提交相关的PR。
> 
> tunnel-server本身是引入了security，是想使用该框架的鉴权功能，依据如下：com.alibaba.arthas.tunnel.server.endpoint.ActuatorSecurity这个类的功能是为了防止endpoint的请求被security拦截。
> 问题在于该代码里面使用了anyRequest().permitAll()，导致除了endpoint的其他请求全部不用鉴权，可以修改成anyRequest().authenticated()

欢迎提交PR修改😀
