### ISSUE TITLE
同一机器启用多个arthas-spring-boot-starter 提示3586 端口被占用

### ISSUE THREAD

**Issue by weson** [alibaba/arthas#1464]

**Comment by RecursionHs** [comment]
退出arthas时，用shutdown退出，你可以进入第一次进入的PID里面使用shutdown即可。

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/1467#issuecomment-685694205

**Comment by hengyunabc** [comment]
参考： https://arthas.aliyun.com/doc/arthas-properties.html
