### ISSUE TITLE
jad 反编译类失败

### ISSUE THREAD

**Issue by dijia478** [alibaba/arthas#1465]
- [√ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.3.9
* 操作系统版本: Linux version 4.4.135-1.el7.elrepo.x86_64
* 目标进程的JVM版本: 1.8.0_91
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 将arthas复制到docker容器中
2. 在容器中切换目标服务的用户
3. 在容器中启动arthas
4. 用jad命令反编译类

### 期望的结果

What do you expected from the above steps？
反编译容器中java服务的类成功

### 实际运行的结果

![image](https://user-images.githubusercontent.com/30929521/91511817-2ef9e180-e913-11ea-8102-5b2fa5e32005.png)

尝试过反编译其他类，都是失败。换了几个容器服务，也是一样的情况。
但是sc命令，trace命令，watch命令都成功的。服务本身也是正常的

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

没有异常日志，显示一切正常

![image](https://user-images.githubusercontent.com/30929521/91511906-5781db80-e913-11ea-89a7-c24eac4c8e57.png)

**Comment by dijia478** [comment]
![image](https://user-images.githubusercontent.com/30929521/91512035-a3cd1b80-e913-11ea-8c86-079d6e7695a1.png)
类是被加载的，sc命令是正常的

**Comment by hengyunabc** [comment]
试下 `dump` 命令，看能dump出来字节码不。

**Comment by dijia478** [comment]
> dump

![image](https://user-images.githubusercontent.com/30929521/91514456-67042300-e919-11ea-849d-45110c9b3221.png)
看上去是没有的

**Comment by dijia478** [comment]
> 试下 `dump` 命令，看能dump出来字节码不。

![image](https://user-images.githubusercontent.com/30929521/91514568-aa5e9180-e919-11ea-89b4-4e86cc841c06.png)
看上去是没有的

**Comment by hengyunabc** [comment]
试下调试具体的实现： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#%E5%BC%80%E5%8F%91%E8%80%85%E7%9B%B8%E5%85%B3 

`JadCommand`, `DumpCommand`。

**Comment by hengyunabc** [comment]
另外，dump其它非 jdk 里的类，看有没有问题；检查下进程有没有配置 security manager。

**Comment by dijia478** [comment]
> 另外，dump其它非 jdk 里的类，看有没有问题；检查下进程有没有配置 security manager。

dump，jad其他非jdk的类都是不行的
![image](https://user-images.githubusercontent.com/30929521/91516045-1c84a580-e91d-11ea-8b35-c223dd35d6da.png)

服务如果不在docker中启动，而在本地启动，那么jad命令是可以正常使用的
![image](https://user-images.githubusercontent.com/30929521/91516035-11ca1080-e91d-11ea-9852-5f33aa85a0d2.png)

**Comment by hengyunabc** [comment]
可能有写文件失败，dump/jad，实际都是要把 `.class` 文件写到磁盘。

**Comment by dijia478** [comment]
> 可能有写文件失败，dump/jad，实际都是要把 `.class` 文件写到磁盘。

因为我docker容器中，启动服务的用户，并不是root用户。所以进入arthas前是要切换用户的，那么该用户确实有可能在某个目录下没有写权限。那么请问是默认是写到哪个目录呢？我尝试修改下目录读写权限

**Comment by hengyunabc** [comment]
dump 目录默认是 `~/logs/arthas/classdump/` ，也可以用参数指定位置

**Comment by dijia478** [comment]
> dump 目录默认是 `~/logs/arthas/classdump/` ，也可以用参数指定位置

确实是这个原因。我用root用户，将~目录赋予所有用户写权限，然后jad命令和dump命令就可以用了

**Comment by hengyunabc** [comment]
从代码来看，创建目录失败，或者写数据失败是有打印日志的啊，检查下没有没

https://github.com/alibaba/arthas/blob/arthas-all-3.3.9/core/src/main/java/com/taobao/arthas/core/command/klass100/ClassDumpTransformer.java#L67

**Comment by dijia478** [comment]
> 从代码来看，创建目录失败，或者写数据失败是有打印日志的啊，检查下没有没
> 
> https://github.com/alibaba/arthas/blob/arthas-all-3.3.9/core/src/main/java/com/taobao/arthas/core/command/klass100/ClassDumpTransformer.java#L67

反编译arthas-core.jar看到，是有这行代码的
![image](https://user-images.githubusercontent.com/30929521/91545027-20cbb580-e953-11ea-8c50-481ca72be95d.png)

不清楚有没有走到这行代码，但是从日志里确实是没有看到这个日志
![image](https://user-images.githubusercontent.com/30929521/91544664-9e42f600-e952-11ea-971d-fe6d38338ff7.png)

我解决问题的步骤是，在docker容器中，切换回root用户，在home目录下，创建A名称的文件（A用户），执行命令chmod 777 A，然后切换A用户，启动arthas，再执行jad，dump，即正常了。
![image](https://user-images.githubusercontent.com/30929521/91545548-c3843400-e953-11ea-952b-1acf8ab633eb.png)

**Comment by dijia478** [comment]
> 从代码来看，创建目录失败，或者写数据失败是有打印日志的啊，检查下没有没
> 
> https://github.com/alibaba/arthas/blob/arthas-all-3.3.9/core/src/main/java/com/taobao/arthas/core/command/klass100/ClassDumpTransformer.java#L67

反编译arthas-core.jar看到，是有这行代码的
![image](https://user-images.githubusercontent.com/30929521/91545763-10680a80-e954-11ea-8d2c-f042be542e11.png)

不清楚有没有走到这行代码，但是从日志里确实是没有看到这个日志
![image](https://user-images.githubusercontent.com/30929521/91545923-4efdc500-e954-11ea-9eed-14b07957fbfd.png)

**Comment by dijia478** [comment]
> 从代码来看，创建目录失败，或者写数据失败是有打印日志的啊，检查下没有没
> 
> https://github.com/alibaba/arthas/blob/arthas-all-3.3.9/core/src/main/java/com/taobao/arthas/core/command/klass100/ClassDumpTransformer.java#L67

我解决问题的步骤是，在docker容器中，切换回root用户，在home目录下，创建A名称的文件（A用户），执行命令chmod 777 A，然后切换A用户，启动arthas，再执行jad，dump，即正常了。
![image](https://user-images.githubusercontent.com/30929521/91546068-7eaccd00-e954-11ea-9b22-b2bf52b14493.png)
