### ISSUE TITLE
请问 profiler 生成的火焰图 frame_buffer_overflow 占比高是什么意思，需要调整什么参数吗？

### ISSUE THREAD

**Issue by daoshenzzg** [alibaba/arthas#1466]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

操作步骤：
1、java -jar arthas-boot.jar 进入操作界面，选择对应 java 进程
2、profiler start 开始采集
3、等待约120秒后，profiler stop 得到火焰图报告
如图：
![image](https://user-images.githubusercontent.com/7531802/91518768-899b3980-e923-11ea-82b3-7900781af069.png)

**Comment by hengyunabc** [comment]
在async-profiler 本身的文档里有： https://github.com/jvm-profiling-tools/async-profiler

**Comment by daoshenzzg** [comment]
好滴，感谢！
