### ISSUE TITLE
CommandProcessImpl 的register方法 listener是不是应该赋值？，目前listener没有赋值的地方

### ISSUE THREAD

**Issue by duHtiGGitHub** [alibaba/arthas#1468]
CommandProcessImpl 的register方法 listener是不是应该赋值？，目前listener没有赋值的地方

        @Override
        public void register(AdviceListener listener, ClassFileTransformer transformer) {
            if (listener instanceof ProcessAware) {
                ProcessAware processAware = (ProcessAware) listener;
                // listener 有可能是其它 command 创建的
                if (processAware.getProcess() == null) {
                    processAware.setProcess(this.process);
                }
            }
            AdviceWeaver.reg(listener);

            this.transformer = transformer;
        }

        @Override
        public void unregister() {
            if (transformer != null) {
                ArthasBootstrap.getInstance().getTransformerManager().removeTransformer(transformer);
            }

            if (listener instanceof ProcessAware) {
                // listener有可能其它 command 创建的，所以不能unRge
                if (this.process.equals(((ProcessAware) listener).getProcess())) {
                    AdviceWeaver.unReg(listener);
                }
            } else {
                AdviceWeaver.unReg(listener);
            }
        }

**Comment by hengyunabc** [comment]
的确是个简单的错误，谢谢指出，已修正。
