### ISSUE TITLE
Arthas 自动退出，端口被占用

### ISSUE THREAD

**Issue by buerbl** [alibaba/arthas#1469]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 打开Arthas，不进行操作，过段时间后，Arthas 会自动退出
2. 再次打开Arthas ，会提示端口占用

### 期望的结果

Arthas 自动退出，释放端口占用

### 实际运行的结果

返回拒接连接，端口占用

日志为
```
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.
Arthas server already stared, skip attach.

```

**Comment by hengyunabc** [comment]
直接连原来的进程是可以连接上的。或者直接 `telnet localhost  3658` 。连上去执行`stop`彻底退出。

**Comment by buerbl** [comment]
多谢
