### ISSUE TITLE
请问这个怎么远程连接docker容器呢？

### ISSUE THREAD

**Issue by sl520311** [alibaba/arthas#147]
因为现在服务是放在docker容器里面运行的，我现在试着用了主机的ip加端口和容器的虚拟ip加端口，都连接不上，报了以下错误:
Connection closed by foreign host!

请问这个能够远程连接docker吗？怎么连接呢？

**Comment by hengyunabc** [comment]
参考这个： https://alibaba.github.io/arthas/start-arthas.html  

1. 先确认端口是开放的，arthas默认的端口是3658
2. 在docker内启动arthas后，先检查在docker内能不能连接上
3. 在外部尝试直接用telnet来连接

**Comment by sl520311** [comment]
你的意思是arthas和服务实例要在同一个docker容器里面启动吗

**Comment by cfmui** [comment]
怎么样让arthas运行在docker容器里面呢？我还有个问题，直接执行as.sh pid，提示错误连接失败，但是会把docker容器里的进程给杀掉了，这是什么原因？执行情况如下：
root@ubuntu-30-35:/data/arthas# ./as.sh 20384
Arthas script version: 3.0.4
Calculating attach execution time...
Attaching to 20384 using version 3.0.4...
Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:213)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:67)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:96)
attach to target jvm (20384) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
进程20384执行完了就被杀掉了

**Comment by hengyunabc** [comment]
@cfmui arthas本身要在docker里执行，不能在宿主机执行。

**Comment by cfmui** [comment]
> @cfmui arthas本身要在docker里执行，不能在宿主机执行。

怎么样在docker里面运行啊，我是新手还请指教 @hengyunabc

**Comment by hengyunabc** [comment]
@cfmui 搜索 docker exec bash 相关的内容，得到一个docker里的shell，再执行arthas
