### ISSUE TITLE
Bug：在redefine的已经成功生效情况下，jad的源代码仍是原来最初的，不是最新的

### ISSUE THREAD

**Issue by zyplanke** [alibaba/arthas#1474]
Bug发现过程：
  1、 jad 反编译得到原来的source code
  2、 通过redefine 加载修改后的字节码， 通过执行结果发现新字节码已经生效。
  3、在新字节码已经生效的情况下， 这时再执行jad仍反编译为原来最初的source code

Bug总结： jad反编译应以JVM内存中最新字节码，进行反编译，得到最新的source code

**Comment by hengyunabc** [comment]
是两种不同的机制，会冲突： https://arthas.aliyun.com/doc/redefine

**Comment by zyplanke** [comment]
好。建议把文档中： https://arthas.aliyun.com/doc/redefine   提到的“字节码重置”，“冲突”等文字描述调整细化下，以便文档说明更加清晰具体，容易理解。

**Comment by hengyunabc** [comment]
> 好。建议把文档中： https://arthas.aliyun.com/doc/redefine 提到的“字节码重置”，“冲突”等文字描述调整细化下，以便文档说明更加清晰具体，容易理解。

欢迎提交PR改进。
