### ISSUE TITLE
使用maven依赖引入arthas，不能通过java -jar arthas-boot-xxx.jar的方式启动

### ISSUE THREAD

**Issue by jounzhang** [alibaba/arthas#1498]
我是maven项目，使用maven引入arthas，希望能直接通过java -jar arthas-boot-xxx.jar的方式启动，但是jar包中没有Main-class相关的东西，启动不了。

需要单独下载jar包执行，造成要么需要更改jenkins打包配置，要么手动将jar包拷贝到生产环境，但是项目特别多，此方式实际操作可行性较低，不是很方便。

**Comment by hengyunabc** [comment]
没理解，如果是编程方式引用，可以参考这个： https://arthas.aliyun.com/doc/spring-boot-starter.html#spring-boot

**Comment by jounzhang** [comment]
我们想实现的效果：
让arthar-boot.jar默认就存在项目中，而不需要每次要用了再拷贝过去使用。使用方式依然是java -jar arthar-boot-xxx.jar来运行。

目前我们使用的docker镜像，所有依赖的jar包都打在lib目录下，现在加了arthar的maven依赖，里面就有了arthar-boot.jar了，但是发现maven依赖下载下来的arthar-boot-xxx.jar不能通过java -jar arthar-boot-xxx.jar的方式运行，提示找不到Main方法。

目前已经通过其他方式解决了，使用：
java -cp lib/* com.taobao.arthas.boot.Bootstrap

手工指定main方法可以运行。
只是没有 java -jar arthar-boot-xxx.jar 方便而已。

**Comment by hengyunabc** [comment]
fat jar在maven仓库里也是有的，可以用这个依赖：

```xml
<dependency>
    <groupId>com.taobao.arthas</groupId>
    <artifactId>arthas-boot</artifactId>
    <version>3.4.1</version>
    <classifier>jar-with-dependencies</classifier>
</dependency>
```

http://search.maven.org/classic/#search%7Cga%7C1%7Carthas-boot

**Comment by jounzhang** [comment]
亲测可用，感谢！
