### ISSUE TITLE
以agent方式启动时，logback的配置问题

### ISSUE THREAD

**Issue by zjh-coder** [alibaba/arthas#1499]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* arthas-boot.jar 或者 as.sh 的版本： arthas-spring-boot-starter 3.4.0
* Arthas 版本: 3.4.0
* 操作系统版本: 16.04.1-Ubuntu
* 目标进程的JVM版本: OpenJDK Runtime Environment (build 1.8.0_265-b01)
* 执行arthas-boot的版本: OpenJDK Runtime Environment (build 1.8.0_265-b01)

### 重现问题的步骤

1. 修改arthas-bin目录下的logback,xml,使其只输出到stdout
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="debug">
        <appender-ref ref="STDOUT" />
    </root>

</configuration>
2. 以java agent的方式启动服务

### 期望的结果

可以在服务正常运行的log输出中，找到arthas的log

### 实际运行的结果

没有在服务正常运行的log输出中，找到arthas的log

**Comment by hengyunabc** [comment]
`ch.qos.logback.core.ConsoleAppender` 这个类名不对，要用 arthas repackage的： `com.alibaba.arthas.deps.ch.qos.logback.core.ConsoleAppender` 。所有相关的类都要类似配置。

**Comment by zjh-coder** [comment]
感谢回复，问题已经解决。
