### ISSUE TITLE
telnet: connect to address 127.0.0.1: Connection refused

### ISSUE THREAD

**Issue by yincn** [alibaba/arthas#1500]
# 下载的是 arthas-arthas-all-3.4.1.tar.gz，上传到阿里云服务器(CentOS release 6.10 (Final))，通过 tar -zxvf arthas-arthas-all-3.4.1.tar.gz 解压，改名为 arthas，进入 arthas 目录，执行 bin/as.sh 后，日志信息如下：

[root@VGP_Beta_VAUapp01 arthas]# bin/as.sh 
Arthas script version: 3.4.1
[INFO] JAVA_HOME: /project/tools/jdk/jdk1.8.0_181
Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 17616 microservice-eureka.jar
  [2]: 18242 microservice-provider-mockaccount.jar
  [3]: 26371 microservice-synchdb.jar
  [4]: 22835 vt-nontrade.jar
  [5]: 3290 microservice-schedule.jar
  [6]: 6092 microservice-provider-realaccount.jar
  [7]: 14302 microservice-consumer.jar
7
Arthas home: /root/.arthas/lib/3.4.1/arthas
Calculating attach execution time...
Attaching to 14302 using version /root/.arthas/lib/3.4.1/arthas...

real	0m0.333s
user	0m0.474s
sys	0m0.045s
Attach success.
telnet connecting to arthas server... current timestamp is 1600132580
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused

# 补充说明：其它服务器启动没问题。麻烦高手帮忙看看，感谢！
# 在当前无法启动的服务器上和能够成功启动的服务器上执行 telnet 127.0.0.1 结果都是如下：
[root@VGP_Beta_VAUapp01 arthas]# telnet 127.0.0.1
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused

**Comment by yincn** [comment]
已经解决

**Comment by Zhangdeli1993** [comment]
怎么解决的,我window也是这样

**Comment by yincn** [comment]
把应用和arthas全部重启一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zdl"<notifications@github.com&gt;; 
发送时间: 2020年11月2日(星期一) 下午4:36
收件人: "alibaba/arthas"<arthas@noreply.github.com&gt;; 
抄送: "传宁"<1478181311@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [alibaba/arthas] telnet: connect to address 127.0.0.1: Connection refused (#1500)





 
怎么解决的,我window也是这样

**Comment by Fallen7eaves** [comment]
可以检查下Class Heap空间情况, 我遇到的是报错OOM Compressed class space, 此时无法使用arthas
因为arthas本身也要加载一些类, 但如果JVM类空间已经满了, 会导致arthas无法正常初始化和附加进程
