### ISSUE TITLE
docker容器中热更新代码，redefine成功后，再次执行任何arthas命令，热更新代码失效

### ISSUE THREAD

**Issue by chowsanity2** [alibaba/arthas#1507]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.2-SNAPSHOT
* Arthas 版本: 3.4.1
* 操作系统版本: CentOS Linux release 8.1.1911
* 目标进程的JVM版本: 1.8.0_252
* 执行`arthas-boot`的版本: 3.4.1
* docker 版本:19.03.9

### 重现问题的步骤

1. 根据官方demo，创建容器启动springboot项目, arthas监听该项目
2. jad反编译，修改java文件（接口代码）并依次执行sc，mc，redefine命令，提示成功（官方文档步骤https://arthas.aliyun.com/doc/arthas-tutorials.html?language=cn&id=arthas-advanced）
3. 容器中访问curl，返回结果为【热更新后】代码的返回值，再次执行其他arthas命令（watch, jad等）

### 期望的结果

1. jad该字节码文件为修改之后的代码
2.再次curl此接口，返回结果为【热更新后】代码的返回值

### 实际运行的结果
1. jad该字节码文件为修改之前的代码
2.再次curl此接口，返回结果为【热更新前】代码的返回值

**Comment by hengyunabc** [comment]
https://arthas.aliyun.com/doc/redefine#id1
