### ISSUE TITLE
windows环境下arthas如何远程调用trace?

### ISSUE THREAD

**Issue by andyclock** [alibaba/arthas#1515]
公司要做自动化监控，只能在powershell一个界面下操作，由于sh.bat 只带一个pid参数，无法把trace指令带入，要监控的程序是Tomcat服务加在windows service的web系统，有没有其它方法完成trace这个动作?

**Comment by kylixs** [comment]
1、使用as-service.bat -pid <pid> 启动arthas 注入windows 服务的java/tomcat进程
2、可以用下面的方式执行命令
```
  java -jar arthas-client.jar -c 'dashboard -n 1'
  java -jar arthas-client.jar -f batch.as 127.0.0.1
``
