### ISSUE TITLE
watch配合stack查看调用链

### ISSUE THREAD

**Issue by saytime** [alibaba/arthas#1525]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.2
* Arthas 版本: 3.4.2
* 操作系统版本: Linux
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.4.2

### 重现问题的步骤

使用watch命令观察到某异常方法后，如果想知道调用链，如何进一步使用stack查看调用链
watch demo.MathGame primeFactors "{params[0],throwExp}" -e -x 2

### 期望的结果

能进一步使用stack查看调用链

### 实际运行的结果

不支持

**Comment by RayneHwang** [comment]
```
watch demo.MathGame primeFactors "{params[0], throwExp, @java.lang.Thread@currentThread().getStackTrace()}" -e -x 2
```

**Comment by saytime** [comment]
thanks

**Comment by hengyunabc** [comment]
也可以结合动态trace： https://arthas.aliyun.com/doc/trace#id8
