### ISSUE TITLE
trace 命令增加耗时百分比

### ISSUE THREAD

**Issue by kingsmao** [alibaba/arthas#1528]
在业务越来越复杂时，对接口的优化是必不可少的。
使用_trace_来追踪链路时没有耗时百分比，数据不直观，建议增加如下的耗时百分比。

[arthas@1]$ trace demo.Test test
    `---[10.0ms] demo.Test()
        +---[1.0ms **_10%_**] demo.Test t1()
        +---[3.0ms **_30%_**] demo.Test t2()
        +---[1.0ms **_10%_**] demo.Test t3()
        +---[5.0ms **_50%_**] demo.Test t4()

**Comment by mzzsfy** [comment]
有这个需求

**Comment by yqxzy** [comment]
I would like to fix this issue.

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/pull/2156
