### ISSUE TITLE
Kubernetes(k8s)且应用集群部署环境下agent-id该如何配置

### ISSUE THREAD

**Issue by uzdz** [alibaba/arthas#1530]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.2
* Arthas 版本: 3.4.2
* 操作系统版本: macos
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.4.2

期望采用`arthas-spring-boot-starter`方式进行`Arthas tunnel client` 与 `Arthas tunnel server`的管理与注册。但是在生产环境中，服务器肯定不会部署一台，所以无法`spring.application.name`来定义`agent-id`，而且由于ip会随着容器重启而发生变化，所以也不能写死。

面对这种情况，我该如何设置或配置`agent-id`呢？

**Comment by hengyunabc** [comment]
arthas starter里的代码其实很简单的，可以自己封装下，自己决定怎么生成 agentId 。 

或者利用 k8s /docker本身的功能，设置一些环境变量，然后注入到spring env里来做为 agent id。

或者自己开发下 tunnel server，反查出应用和 agent之间的关系。
