### ISSUE TITLE
版本没有更新

### ISSUE THREAD

**Issue by yangtao198536** [alibaba/arthas#1537]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

我之前的版本是3.4.0，我切换到arthas的home目录，执行 curl -O https://arthas.aliyun.com/arthas-boot.jar，之后启动显示的是3.4.3，但是用version命令执行后，显示的是3.4.0

### 期望的结果

应该自动更新的最新版本，清除本地的缓存的旧版本

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
判断的逻辑是： 如果 arthas home就是当前目录，则不会自动更新。 所以cd到一个其它的目录，再下载 arthas-boot 启动，就会自动更新
