### ISSUE TITLE
工商银行打造在线诊断平台的探索与实践

### ISSUE THREAD

**Issue by lyghzh** [alibaba/arthas#1538]
[工商银行打造在线诊断平台的探索与实践](https://github.com/lyghzh/pub/blob/main/doc/%E5%B7%A5%E5%95%86%E9%93%B6%E8%A1%8C%E6%89%93%E9%80%A0%E5%9C%A8%E7%BA%BF%E8%AF%8A%E6%96%AD%E5%B9%B3%E5%8F%B0%E7%9A%84%E6%8E%A2%E7%B4%A2%E4%B8%8E%E5%AE%9E%E8%B7%B5.md)

**Comment by sunryan** [comment]
牛逼啊

**Comment by Grt1228** [comment]
厉害

**Comment by XXMY** [comment]
可以开源出来不

**Comment by password36** [comment]
支持开源啊，特别是web console和命令封装部分得~

**Comment by lyghzh** [comment]
谢谢支持。开源目前公司层面还没有计划。

**Comment by munan56** [comment]
棒！

**Comment by zhugeburu** [comment]
不错

**Comment by wanghuigithub** [comment]
在以容器云为基础设施。和devops为指导的情况下。好像文章中的好多痛点就没有特别明显了。
文章写的很精彩。但是对于这件事情的「WHY」好像稍微会让人有一点点想挑战。
自己的一点戳建，欢迎吐槽

**Comment by a724918491** [comment]
优秀

**Comment by chendongcse** [comment]
iCBC牛逼

**Comment by lyghzh** [comment]
> 在以容器云为基础设施。和devops为指导的情况下。好像文章中的好多痛点就没有特别明显了。
> 文章写的很精彩。但是对于这件事情的「WHY」好像稍微会让人有一点点想挑战。
> 自己的一点拙见，欢迎吐槽
主要目的还是面对不同的基础环境，以及水平参差不齐的技术人员，提供产品化的能力，也更方便和公司内部运维系统集成。arthas新版本提供的restful接口以及更强大的web控制台，相信跟我们的目的是一致的。

**Comment by wanghuigithub** [comment]
> > 在以容器云为基础设施。和devops为指导的情况下。好像文章中的好多痛点就没有特别明显了。
> > 文章写的很精彩。但是对于这件事情的「WHY」好像稍微会让人有一点点想挑战。
> > 自己的一点拙见，欢迎吐槽
> 
> 主要目的还是面对不同的基础环境，以及水平参差不齐的技术人员，提供产品化的能力，也更方便和公司内部运维系统集成。arthas新版本提供的restful接口以及更强大的web控制台，相信跟我们的目的是一致的。

赞，在本文启发下，我们公司也刚刚集成了arthas（命令行方式），方便开发在线诊断

**Comment by hengyunabc** [comment]
@wanghuigithub 欢迎分享你们的经验，还可以投稿到这里： https://github.com/alibaba/arthas/issues/1079

**Comment by wanghuigithub** [comment]
> @wanghuigithub 欢迎分享你们的经验，还可以投稿到这里： #1079

👌

**Comment by 1228857713** [comment]
https://github.com/qunarcorp/bistoury
你这个是不是和这个有类似之处

**Comment by password36** [comment]
> https://github.com/qunarcorp/bistoury
> 你这个是不是和这个有类似之处

这个不错，和工银这个类似，在基础功能上提供了应用视图和实际工程应用管理，准备试试

**Comment by lyghzh** [comment]
> https://github.com/qunarcorp/bistoury
> 你这个是不是和这个有类似之处

这是去哪儿开源的工具，原理类似

**Comment by AaronMegs** [comment]
不错

**Comment by pli2014** [comment]
抓紧开源，做个最小集合，造福大家~

**Comment by Aristohack** [comment]
太强了

**Comment by nyingping** [comment]
开源了踢一下，蟹蟹

**Comment by a724918491** [comment]
收到，谢谢！

**Comment by a724918491** [comment]
收到，谢谢！

**Comment by qwe1290670214** [comment]
牛逼

**Comment by a724918491** [comment]
收到，谢谢！

**Comment by cuixianyu-github** [comment]
什么时候准备开源一下啊？还在坐等

**Comment by a724918491** [comment]
收到，谢谢！

**Comment by vudsen** [comment]
兄弟们，我自己抽空做了个开源的：https://github.com/vudsen/spectre

基于 arthas http api，同样有鉴权和一键连接功能，不过结果输出的展示还不全，正在慢慢补齐中

**Comment by a724918491** [comment]
收到，谢谢！
