### ISSUE TITLE
direct memory是否属于堆外内存？

### ISSUE THREAD

**Issue by tonyjia87** [alibaba/arthas#1552]
- [x ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: centos7.4
* 目标进程的JVM版本: 1.8 161
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

![image](https://user-images.githubusercontent.com/5828609/96977152-463dff80-154f-11eb-9868-1cb8c0ea2c70.png)

### 期望的结果

图中 direct 是什么， nonheap 是否就是 包括 code_cache,metaspace,compressed_class_space,direct,mapped 几种类型？

原本我的需求是研发想看堆外内存使用情况，想netty这类框架会用到。 我看工具有显示direct 是否就是堆外内存？

通过设置应用测试XX:MaxDirectMemorySize参数看到 direct有增长，但是我不能诊断是否就是。

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/blob/arthas-all-3.4.3/core/src/main/java/com/taobao/arthas/core/command/monitor200/DashboardCommand.java

**Comment by tonyjia87** [comment]
虽然没有用到这个，但是谢谢支持

> 参考： https://github.com/alibaba/arthas/blob/arthas-all-3.4.3/core/src/main/java/com/taobao/arthas/core/command/monitor200/DashboardCommand.java

**Comment by stevenniu9527** [comment]
https://docs.oracle.com/javase/7/docs/api/java/lang/management/BufferPoolMXBean.html

**Comment by chamcyl** [comment]
我是通过这个方法查看netty的DirectMemory
`ognl  '@io.netty.util.internal.PlatformDependent@usedDirectMemory()'`

**Comment by Liudapeng** [comment]
> 我是通过这个方法查看netty的DirectMemory 。 （和 dashboard 上看到的 direct 是不同的值） `ognl '@io.netty.util.internal.PlatformDependent@usedDirectMemory()'`

netty 是自己提供的堆外内存实现，要自己写代码获取,  试试看 PlatformDependent.usedDirectMemory() 这个值

**Comment by chongchaoyu** [comment]
The Java virtual machine manages memory other than the heap (referred as non-heap memory). The non-heap memory includes the method area and memory required for the internal processing or optimization for the Java virtual machine. It stores per-class structures such as a runtime constant pool, field and method data, and the code for methods and constructors.

**Comment by stevenniu9527** [comment]
邮件已经收到，我会尽快查看，谢谢
