### ISSUE TITLE
centos7  3.4.3版本 Profiler 报 AsyncProfiler error

### ISSUE THREAD

**Issue by gepengjun** [alibaba/arthas#1555]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.4.3
* Arthas 版本: 3.4.3
* 操作系统版本: Linux-3.10.0-1062.el7.x86_64
* 目标进程的JVM版本: Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)
* 执行`arthas-boot`的版本: 3.4.3

### 重现问题的步骤
运行 java -jar arthas-demo.jar
运行 java -jar arthas-boot.jar
查看profiler的版本  profiler version 
### 期望的结果
显示profiler的版本

### 实际运行的结果
AsyncProfiler error: /usr/local/softwareInstaller/arthas/async-profiler/libasyncProfiler-linux-x64.so: /usr/local/softwareInstaller/arthas/async-profiler/libasyncProfiler-linux-x64.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)

**Comment by hengyunabc** [comment]
可能是32位的os，只支持64位的。参考 async-profiler 目录下的文件。

**Comment by gepengjun** [comment]
> 可能是32位的os，只支持64位的。参考 async-profiler 目录下的文件。

可是我装的是64位的os额,  Linux-3.10.0-1062.el7.x86_64

**Comment by kylixs** [comment]
jdk 是32位的？ 看信息中没有`64-Bit`

**Comment by gepengjun** [comment]
> jdk 是32位的？ 看信息中没有`64-Bit`

谢谢, 懂了. 应该是我装的jdk是32位的问题. 谢谢啦
