### ISSUE TITLE
arthas有没有类似visualvm的内存抽样器

### ISSUE THREAD

**Issue by lovejj1994** [alibaba/arthas#1559]
- [x ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 期望的结果

可以实时看到有哪些对象新增，个数，大小是多少，方便定位问题代码

![image](https://user-images.githubusercontent.com/14882338/97775471-d3123a00-1b9b-11eb-93d4-598b643176bb.png)

**Comment by hengyunabc** [comment]
不支持，这类工具实际上都是 heapdump分析。arthas只是一个命令行工具。 也可以试下用 arthas profiler命令生成火焰图。
