### ISSUE TITLE
想请教一下，如何使用Arthas打印出http请求的完整调用

### ISSUE THREAD

**Issue by Skevdv** [alibaba/arthas#1570]
我想要找出Tomcat、Jetty、Resin等中间件接收http请求的完整调用，然后在http请求进入filter之前做一些Hook

目前我找到的Tomcat的hook函数是:
apache.catalina.core.ApplicationFilterChain.doFilter()

Jetty的hook函数是:
org.eclipse.jetty.server.handler.HandlerWrapper.handle() 

想请教一下，能否用Arthas来寻找这些hook函数，不胜感激！

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/429

**Comment by Skevdv** [comment]
> #429

感谢！我看到这里是通过trace来定位servlet，我希望找到web中间件源码当中在进入servlet之前的接收http请求的函数，不知道应该如何寻找呢？

**Comment by Skevdv** [comment]
> #429

感谢！
