### ISSUE TITLE
watch抽象类的方法，类名参数 必须指定为父类

### ISSUE THREAD

**Issue by baobinghai** [alibaba/arthas#1572]
watch抽象类的方法，类名参数 必须指定为父类，这是什么原理？
1  按照java的原则，抽象类无法被实例化，那又怎么被监控到

**Comment by kylixs** [comment]
这个问题不好解决，Arthas目前是分为两个步骤：
1）枚举Instrumentation 的class列表中，找到匹配classname-pattern的class集合；
2）通过调用retransformClasses 传入上面找到的class集合，进行增强处理。
相关代码： com.taobao.arthas.core.advisor.Enhancer#enhance(java.lang.instrument.Instrumentation)


目前在第一步没有加入父类，所以后面增强是没法对父类进行处理。
