### ISSUE TITLE
解压执行sh   as.sh 报127.0.0.1  Connection refused

### ISSUE THREAD

**Issue by happyapple668** [alibaba/arthas#1577]
这是什么情况,版本3.4.4

**Comment by hengyunabc** [comment]
贴出更多，更详细的日志。 或者试下在线教程 https://arthas.aliyun.com/doc/arthas-tutorials.html?language=cn

**Comment by happyapple668** [comment]
可能与下载的包有关,在github上下载的可以,文档里的不行

**Comment by hengyunabc** [comment]
> 可能与下载的包有关,在github上下载的可以,文档里的不行

检查文件是否下载成功了，或者试下载全量包，再解压。  另外，试下本地启动 arthas-demo 来试下
