### ISSUE TITLE
sh脚本问题

### ISSUE THREAD

**Issue by qiaob** [alibaba/arthas#158]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: xxx
* Operating System version: xxx
* Java version of target JVM: xxx
* Java version of JVM used to attach: xxx

### Steps to reproduce this issue

1. 第一次执行as.sh，如果服务器没有unzip命令，解压会失败，但是并没有清除${ARTHAS_LIB_DIR}/${update_version} 这个文件夹，导致之后不会再重新下载zip包

```
if [ ! -d ${ARTHAS_LIB_DIR}/${update_version} ]; then
        echo "updating version ${update_version} ..."
```

**Comment by ralf0131** [comment]
Hi, would you please send a pull request to improve it?

**Comment by ralf0131** [comment]
This issue has been fixed.
