### ISSUE TITLE
avg-rt(ms) 值不正常

### ISSUE THREAD

**Issue by woohanhan** [alibaba/arthas#1580]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.2.0
* Arthas 版本:  3.4.4
* 操作系统版本: cent os 8
* 目标进程的JVM版本: oracle jdk 1.8.0_181

* 执行`arthas-boot`的版本: 3.2.0

### 重现问题的步骤

1. monitor com.xxx.core.common.RedisHandler getTaskPoolTel -n 10 --cycle 120 'params[0]==3457986494546704L'

### 期望的结果

What do you expected from the above steps？
正确的avg-rt(ms)

### 实际运行的结果

![1605857900(1)](https://user-images.githubusercontent.com/42365596/99772834-7674c000-2b46-11eb-8911-edc804e591bd.jpg)

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
无
```

**Comment by woohanhan** [comment]
经常出现monitor命令在第一个循环周期统计的avg耗时明显错误，第二个周期则正常，旧版本没问题

**Comment by Colin678** [comment]
我今天也发现了

**Comment by hengyunabc** [comment]
@woohanhan @Colin678 试下最新版本

**Comment by MolyXl** [comment]
![image](https://user-images.githubusercontent.com/24529707/192991783-c44b5357-2803-42fc-a4eb-570cfb37f70a.png)
没有解决吧，怎么关了呢，3.6.6版本

**Comment by yanye666** [comment]
<img width="1805" height="156" alt="Image" src="https://github.com/user-attachments/assets/24cc5348-1ce7-4b6e-8854-25f3318ee482" />

现在还有问题。

**Comment by yanye666** [comment]
@hengyunabc
