### ISSUE TITLE
Why failed startup when download latest version since I was using jar file?

### ISSUE THREAD

**Issue by helloworlde** [alibaba/arthas#1581]
In most company environment, external internet is not allowed to access, so I download and upload the latest verison to server, but when startup, it access https://arthas.aliyun.com/api/latest_version and failed!!!
Is there anybody thinked about this issue? Why need failed? If can't get latest_version, why I can't use it?

**Comment by hengyunabc** [comment]
Try to download full package: https://arthas.aliyun.com/doc/en/download.html
