### ISSUE TITLE
定位问题咨询

### ISSUE THREAD

**Issue by szw906689771** [alibaba/arthas#1584]
private static int getresult(int[] s, int i) {
		try {
			return s[i];
		}catch(Exception e) {
			return -1;
		}
		
	}
像这样的代码，异常在方法内被捕获了，有办法打印查看这个异常信息吗？

**Comment by hengyunabc** [comment]
不支持，可以试下 redefine 命令 ，或者用 jmc，里面有异常信息的统计。
