### ISSUE TITLE
jad反编译后，使用mc编译java文件，目标文件依赖了WEB-INF/lib下的jar包中的类。

### ISSUE THREAD

**Issue by dads546** [alibaba/arthas#1588]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.4

### 重现问题的步骤

1. jad 反编译文件输出.java
2. 修改.java
3. mc进行编译

### 期望的结果

编译成功

### 实际运行的结果

编译异常

```
java.lang.ClassCastException: weblogic.utils.zip.ZipURLConnection cannot be cast to java.net.JarURLConnection
 at com.taobao.arthas.compiler.PackageInternalsFinder.
```

无法读取WEB-INF/lib下的jar文件信息。使用web容器为weblogic12。java环境jdk8

**Comment by hengyunabc** [comment]
代码里是直接认为是 URLClassLoader里取出来的，直接是 JarURLConnection 。如果类型不对，或者自己注册了一些处理URL的handler，的确可能会出错。

可以直接本地编译出 `.class`，再上传到服务器上redefine。

**Comment by vampire007** [comment]
> 代码里是直接认为是 URLClassLoader里取出来的，直接是 JarURLConnection 。如果类型不对，或者自己注册了一些处理URL的handler，的确可能会出错。
> 
> 可以直接本地编译出 `.class`，再上传到服务器上redefine。

您好，本地编译为 class 文件上传到服务器之后，refine 的时候报错：redefine error! java.lang.UnsupportedOperationException: class redefinition failed: attempted to delete a method

**Comment by dads546** [comment]
你这个很明显是 操作不被允许，删除方法无法通过redefine的方式来重新注册的。
