### ISSUE TITLE
trace命令导致springboot服务崩溃

### ISSUE THREAD

**Issue by zuolovezhai** [alibaba/arthas#1589]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.4.4
* 操作系统版本: Red Hat Enterprise Linux Server release 6.4
* 目标进程的JVM版本: 1.8.0_11
* springboot版本: 2.1.3

### 重现问题的步骤
trace com.administrator.dashboard.cluster.controller.ClusterSQLController getClusterQPS
### 实际运行的结果

```
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x0000000000000000, pid=93687, tid=140325724477184
JRE version: Java(TM) SE Runtime Environment (8.0_11-b12) (build 1.8.0_11-b12)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.11-b03 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  0x0000000000000000

 Failed to write core dump. Core dumps have been disabled.To enable core dumping, try "ulimit -c unlimited" before starting Java again
If you would like to submit a bug report, please visit:
http://bugreport.sun.com/bugreport/crash.jsp
```

**Comment by hengyunabc** [comment]
可以提供能重现的demo不？没有demo比较难排查。

**Comment by zuolovezhai** [comment]
> 可以提供能重现的demo不？没有demo比较难排查。

我单独写了个springboot工程进行测试,但是发现没有崩溃,有可能是某一个jar包导致的崩溃.对于这种问题的排查有没有可供参考的方案

**Comment by hengyunabc** [comment]
@zuolovezhai 
1. 看能不能稳定复现
2. 检查下有没有同时用了多个java agent

**Comment by zuolovezhai** [comment]
> 可以提供能重现的demo不？没有demo比较难排查。

可以提供一个简单jar包

**Comment by hengyunabc** [comment]
> > 可以提供能重现的demo不？没有demo比较难排查。
> 
> 可以提供一个简单jar包,如何提供提供给你?

可以加群，然后找管理员，就可以看到了。 https://arthas.aliyun.com/doc/contact-us.html

**Comment by zuolovezhai** [comment]
> > > 可以提供能重现的demo不？没有demo比较难排查。
> > 
> > 
> > 可以提供一个简单jar包,如何提供提供给你?
> 
> 可以加群，然后找管理员，就可以看到了。 https://arthas.aliyun.com/doc/contact-us.html

好的

**Comment by zuolovezhai** [comment]
jvm版本问题导致

**Comment by unluckyBear** [comment]
请问这个问题如何解决的呢

**Comment by hengyunabc** [comment]
> 请问这个问题如何解决的呢

升级到最新版本的jdk，或者提供可重现demo。

**Comment by syshenyao** [comment]
我也遇到这个问题，业务系统遇到了，demo不弄，但感觉不是jdk版本问题，其他应用不会奔溃
