### ISSUE TITLE
Unable to access jarfile /root/.arthas/lib/3.0.4/arthas/arthas-core.jar

### ISSUE THREAD

**Issue by Mindsetimportant** [alibaba/arthas#159]
运行./as.sh时出错
[root@localhost ~]# ./as.sh 
Arthas script version: 3.0.4
Found existing java process, please choose one and hit RETURN.
* [1]: 1180 org.apache.catalina.startup.Bootstrap
1
Calculating attach execution time...
Attaching to 1180 using version 3.0.4...
Error: Unable to access jarfile /root/.arthas/lib/3.0.4/arthas/arthas-core.jar
attach to target jvm (1180) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.

JDK
[root@localhost ~]# java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by Mindsetimportant** [comment]
以解决。。。

**Comment by FS1360472174** [comment]
也于东了，什么问题，权限？

**Comment by Mindsetimportant** [comment]
自认为问题的有二个
        JDK的问题，在as.sh脚本中的，JDK的位置是在/opt/taobao/java
        在下载后，安装时运行as.sh脚本没有加$PATH参数
On 9/25/2018 18:28，hengyunabc<notifications@github.com> wrote：

可以说下具体什么原因不？ 很多人提过这个问题

**Comment by Mindsetimportant** [comment]
JDK的位置




On 9/26/2018 11:30，stoneFang<notifications@github.com> wrote：

也于东了，什么问题，权限？

**Comment by shibinfei** [comment]
遇到了相同的问题

**Comment by Mindsetimportant** [comment]
有没有加$PATH参数
On 10/8/2018 19:21，shibinfei<notifications@github.com> wrote：

我的原因是, 确实没有这个文件, 没下载下来 arthas-core.jar
