### ISSUE TITLE
请教一下arthas build的问题

### ISSUE THREAD

**Issue by kuailelijuan** [alibaba/arthas#1590]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.0
* Arthas 版本: 3.4.0
* 操作系统版本: 3.4.0
* 目标进程的JVM版本: 3.4.0
* 执行`arthas-boot`的版本: 3.4.0

### 重现问题的步骤

jdk 版本1.6
mvn 版本 3.2.5
编译不通过，已参考 https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#

![image](https://user-images.githubusercontent.com/10428780/100042926-63643780-2e47-11eb-8e04-5c22846e6c9b.png)

请问下这块编译的一些问题。

**Comment by hengyunabc** [comment]
1. 编译时要用 jdk7 以上。 
2. 打包出来一个zip之后，可以放到jdk6机器上运行，可以诊断 jdk6的进程。
