### ISSUE TITLE
启动报错：insufficient memory or insuffcient privileges to attach 

### ISSUE THREAD

**Issue by lifei636** [alibaba/arthas#1591]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4
* Arthas 版本: 3.4
* 操作系统版本: windows service2008
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.4

### 重现问题的步骤

1. java程序部署到tomcat8
2. 把tomcat8 安装到服务
3. 启动服务，查询进程pid，
4.java -jar arthas-boot.jar pid
5.报错

### 期望的结果

正常启动arthas

### 实际运行的结果

Com.sun.tools .attach.AttachNotSupportedException: Insufficient memory or insuffcientpriu ileges to attach
![5)IFZ%{L5VQPF$5_WG2@F_Y](https://user-images.githubusercontent.com/39741572/100170022-bb5e7500-2eff-11eb-81ba-3de8cc2db0c9.png)

**Comment by kylixs** [comment]
tomcat是用cmd启动 还是windows服务？如果是windows服务需要使用as-service.bat脚本启动注入arthas。请参考：https://arthas.aliyun.com/doc/manual-install.html?highlight=as-service.bat#windows

> 使用以下命令诊断windows服务模式运行的Java进程 (–interact 打开服务UI交互模式，方便诊断问题)：
> ```
> as-service.bat -port <port>
> as-service.bat -pid <pid>
> as-service.bat -pid <pid> --interact
> ```

**Comment by lifei636** [comment]
@kylixs 你好，重新下载您给的链接里的包，用您说的3个命令，均提示此时不应有 \\as.bat 
注：cmd命令窗口已获得管理员权限
![image](https://user-images.githubusercontent.com/39741572/100184501-99bfb680-2f1c-11eb-9a1e-d7338d2fc5f5.png)

**Comment by kylixs** [comment]
修改一下目录名称，把空格和小括号去掉，再试试
