### ISSUE TITLE
Used to monitor whether HDFS-Namenode affects NN performance

### ISSUE THREAD

**Issue by WindyGao** [alibaba/arthas#1594]
- [x] I have been in the [issues] (https://github.com/alibaba/arthas/issues) in the search，There is no repeated issue

### Environmental information

* `arthas-boot.jar` or `as.sh` version： 3.4.4
* Arthas version: 3.4.4
* hadoop version: 3.1.0
* `arthas-boot`version: 3.4.4

### background
1. Recently, it is slow to delete the recycle station of NameNode and slow to restart the Report block, so I want to monitor Arthas, but I don't know whether it will affect NameNode in production, so I would like to consult you

### Desired outcome

NN is not affected by expecting to monitor Name Node using arthas. If so, please specify the reason, thank you

**Comment by WindyGao** [comment]
我怕把NN跑挂了。。。毕竟生产上的NN在删除大量文件时RPC已经很不稳定了，基本在100-2000ms左右飘，arthas对于这个java程序的监控会影响内部RPC的调用吗？我担心加剧RPC高延迟的现象

**Comment by WindyGao** [comment]
我监控的动作只是trace method

**Comment by WindyGao** [comment]
It is best not to monitor when NN RPC latency is high or NN operations are frequent, as this will likely cause NN to stop service

**Comment by hengyunabc** [comment]
参考： https://arthas.aliyun.com/doc/faq.html
