### ISSUE TITLE
用watch时碰到类包名里有中文字符，arthas无法准确定位到指定的类和方法

### ISSUE THREAD

**Issue by holylinlhl** [alibaba/arthas#1597]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.4
* Arthas 版本: 3.4.4
* 操作系统版本: windows 10
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: jdk1.8

### 重现问题的步骤

用watch时碰到类包名里有中文字符,录入中文时会出现乱码，造成arthas无法准确定位到指定的类和方法；
用sc是可以找到要定位的类的，而且中文也显示正常。
试过Dfile.encoding=UTF-8或者Dfile.encoding=GBK或者Dinput.encoding=GBK(看源码默认就是UTF-8)都无效

### 期望的结果

在录入watch  com.xxxx.中文.UserClass method "{params,returnObj}" -x 2
 在arthas的命令窗口中，录入的中文能够正确显示，且能让arthas准确找到指定的类和方法

### 实际运行的结果

录入的中文是乱码，比如输入法里录入“中”，控制台会显示“脰脨”

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
重复了，先close掉： https://github.com/alibaba/arthas/issues/1643
