### ISSUE TITLE
执行java -jar arthas-boot.jar PID报错

### ISSUE THREAD

**Issue by fighting0510** [alibaba/arthas#1599]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.3
* Arthas 版本: 3.4.3
* 操作系统版本: SUSE12
* 目标进程的JVM版本: openJdk1.8.0_232
* 执行`arthas-boot`的版本: 3.4.3

### 期望结果
下图中PID 7493 跟 28275都可以正常展示ARTHAS logo

### 实际运行的结果

下图中PID 7493正常展示ARTHAS logo，但是28275报错

![微信图片_20201202175627](https://user-images.githubusercontent.com/19368331/100857887-38718780-34c8-11eb-9f68-19fb378f0a94.jpg)

**Comment by hengyunabc** [comment]
可能混用了不同版本。试下用最新的 3.4.4， 把原来的文件都删掉。进程也重启下。
