### ISSUE TITLE
利用Arthas排查Spring Boot应用NoSuchMethodError

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#160]
## 前言

有时spring boot应用会遇到`java.lang.NoSuchMethodError`的问题，下面以具体的demo来说明怎样利用[arthas](https://github.com/alibaba/arthas)来排查。

Demo: https://github.com/hengyunabc/spring-boot-inside/tree/master/demo-NoSuchMethodError

## 在应用的main函数里catch住异常，保证进程不退出

很多时候当应用抛出异常后，进程退出了，就比较难排查问题。可以先改下main函数，把异常catch住：

```java
	public static void main(String[] args) throws IOException {
		try {
			SpringApplication.run(DemoNoSuchMethodErrorApplication.class, args);
		} catch (Throwable e) {
			e.printStackTrace();
		}
		// block
		System.in.read();
	}
```

Demo启动之后，抛出的异常是：

```java
java.lang.NoSuchMethodError: org.springframework.core.annotation.AnnotationAwareOrderComparator.sort(Ljava/util/List;)V
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:394)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:383)
	at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:249)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:225)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.example.demoNoSuchMethodError.DemoNoSuchMethodErrorApplication.main(DemoNoSuchMethodErrorApplication.java:13)
```

显然，异常的意思是`AnnotationAwareOrderComparator`缺少`sort(Ljava/util/List;)V`这个函数。

## 安装arthas

参考：https://alibaba.github.io/arthas/install-detail.html

## 使用sc命令查找类所在的jar包

应用需要抛出了异常，但是进程还没有退出，我们用arthas来attach上去。比如在mac下面：

```bash
./as.sh
```

然后选择`com.example.demoNoSuchMethodError.DemoNoSuchMethodErrorApplication`进程。

再执行[sc](https://alibaba.github.io/arthas/sc.html)命令来查找类：

```java
$ sc -d org.springframework.core.annotation.AnnotationAwareOrderComparator
 class-info        org.springframework.core.annotation.AnnotationAwareOrderComparator
 code-source       /Users/hengyunabc/.m2/repository/org/springframework/spring/2.5.6.SEC03/spring-2.5.6.SEC03.jar
 name              org.springframework.core.annotation.AnnotationAwareOrderComparator
 isInterface       false
 isAnnotation      false
 isEnum            false
 isAnonymousClass  false
 isArray           false
 isLocalClass      false
 isMemberClass     false
 isPrimitive       false
 isSynthetic       false
 simple-name       AnnotationAwareOrderComparator
 modifier          public
 annotation
 interfaces
 super-class       +-org.springframework.core.OrderComparator
                     +-java.lang.Object
 class-loader      +-sun.misc.Launcher$AppClassLoader@5c647e05
                     +-sun.misc.Launcher$ExtClassLoader@689e3d07
 classLoaderHash   5c647e05

Affect(row-cnt:1) cost in 41 ms.
```

可以看到`AnnotationAwareOrderComparator`是从`spring-2.5.6.SEC03.jar`里加载的。

## 使用jad查看反编绎的源代码

下面使用[jad](https://alibaba.github.io/arthas/jad.html)命令来查看`AnnotationAwareOrderComparator`的源代码

```
$ jad org.springframework.core.annotation.AnnotationAwareOrderComparator

ClassLoader:
+-sun.misc.Launcher$AppClassLoader@5c647e05
  +-sun.misc.Launcher$ExtClassLoader@689e3d07

Location:
/Users/hengyunabc/.m2/repository/org/springframework/spring/2.5.6.SEC03/spring-2.5.6.SEC03.jar

/*
 * Decompiled with CFR 0_132.
 */
package org.springframework.core.annotation;

import java.lang.annotation.Annotation;
import org.springframework.core.OrderComparator;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;

public class AnnotationAwareOrderComparator
extends OrderComparator {
    protected int getOrder(Object obj) {
        Order order;
        if (obj instanceof Ordered) {
            return ((Ordered)obj).getOrder();
        }
        if (obj != null && (order = obj.getClass().getAnnotation(Order.class)) != null) {
            return order.value();
        }
        return Integer.MAX_VALUE;
    }
}

Affect(row-cnt:1) cost in 286 ms.
```

可见，`AnnotationAwareOrderComparator`的确没有`sort(Ljava/util/List;)V`函数。

## 排掉依赖，解决问题

从上面的排查里，可以确定

* `AnnotationAwareOrderComparator`来自`spring-2.5.6.SEC03.jar`，的确没有`sort(Ljava/util/List;)V`函数。

所以，可以检查maven依赖，把spring 2的jar包排掉，这样子就可以解决问题了。

## 总结

* 仔细看`NoSuchMethodError`的异常信息，了解是什么类缺少了什么函数
* 利用arthas来查找类，反编绎源码，确认问题

## 链接

* [Arthas--Alibaba开源Java诊断利器](https://alibaba.github.io/arthas)

**Comment by wangmeng1314** [comment]
给力

**Comment by yooocen** [comment]
给力

**Comment by dong4j** [comment]
给力

**Comment by fangsh2015** [comment]
牛逼

**Comment by hzdavid** [comment]
上面的issue是系统已经出现了NoSuchMethodError，如果想知道系统里还有哪些类，可能会造成NoSuchMethodError呢？ 能否在maven打包时就能发现呢？

借这个issue机会，推广一下自己的插件。 https://github.com/hzdavid/findConflicts
使用步骤相当简单：

git clone https://github.com/hzdavid/findConflicts
mvn install 

然后在自己工程的pom.xml中，比如上面的Demo: https://github.com/hengyunabc/spring-boot-inside/tree/master/demo-NoSuchMethodError
pom.xml里配置插件 
`<plugin>
         <groupId>findconflicts</groupId>
         <artifactId>fc-maven-plugin</artifactId>
         <version>1.0.0-SNAPSHOT</version>
         <executions>
                 <execution>
                         <phase>package</phase>
                         <goals><goal>go</goal></goals>
                 </execution>
         </executions>
         <configuration>
                 <versionCheckConfig>${basedir}/versionCheck.pb</versionCheckConfig>
         </configuration>
       </plugin>`

然后mvn fc:go -Dshow.class.conflicts=true

类冲突，jar冲突，日志冲突一览无余.


刚才试过，AnnotationAwareOrderComparator 这个冲突类，这个插件就找到了。 

希望楼主不要删除这个comment啊，偶可是arthas忠实fans。


have fun!

**Comment by MoPei** [comment]
这种问题一般都应该是包冲突造成的，一般的包用idea 的插件Maven Helper就能解决，阿尔萨斯应该在线上或回归环境定位诡异的问题才能体现她的价值吧

**Comment by wenlaizhou** [comment]
> 上面的issue是系统已经出现了NoSuchMethodError，如果想知道系统里还有哪些类，可能会造成NoSuchMethodError呢？ 能否在maven打包时就能发现呢？
> 
> 借这个issue机会，推广一下自己的插件。 https://github.com/hzdavid/findConflicts
> 使用步骤相当简单：
> 
> git clone https://github.com/hzdavid/findConflicts
> cd findConflicts
> mvn install
> 
> 然后在自己工程的pom.xml中，比如上面的Demo: https://github.com/hengyunabc/spring-boot-inside/tree/master/demo-NoSuchMethodError
> pom.xml里配置插件
> `<plugin> <groupId>findconflicts</groupId> <artifactId>fc-maven-plugin</artifactId> <version>1.0.0-SNAPSHOT</version> <executions> <execution> <phase>package</phase> <goals><goal>go</goal></goals> </execution> </executions> <configuration> <versionCheckConfig>${basedir}/versionCheck.pb</versionCheckConfig> </configuration> </plugin>`
> 
> 然后mvn fc:go -Dshow.class.conflicts=true
> 
> 类冲突，jar冲突，日志冲突一览无余.
> 
> 刚才试过，AnnotationAwareOrderComparator 这个冲突类，这个插件就找到了。
> 
> 希望楼主不要删除这个comment啊，偶可是arthas忠实fans。
> 
> have fun!

请教一下哈, dependence tree 能不能解决这个问题呢?

**Comment by hzdavid** [comment]
> > 上面的issue是系统已经出现了NoSuchMethodError，如果想知道系统里还有哪些类，可能会造成NoSuchMethodError呢？ 能否在maven打包时就能发现呢？
> > 借这个issue机会，推广一下自己的插件。 https://github.com/hzdavid/findConflicts
> > 使用步骤相当简单：
> > git clone https://github.com/hzdavid/findConflicts
> > cd findConflicts
> > mvn install
> > 然后在自己工程的pom.xml中，比如上面的Demo: https://github.com/hengyunabc/spring-boot-inside/tree/master/demo-NoSuchMethodError
> > pom.xml里配置插件
> > `<plugin> <groupId>findconflicts</groupId> <artifactId>fc-maven-plugin</artifactId> <version>1.0.0-SNAPSHOT</version> <executions> <execution> <phase>package</phase> <goals><goal>go</goal></goals> </execution> </executions> <configuration> <versionCheckConfig>${basedir}/versionCheck.pb</versionCheckConfig> </configuration> </plugin>`
> > 然后mvn fc:go -Dshow.class.conflicts=true
> > 类冲突，jar冲突，日志冲突一览无余.
> > 刚才试过，AnnotationAwareOrderComparator 这个冲突类，这个插件就找到了。
> > 希望楼主不要删除这个comment啊，偶可是arthas忠实fans。
> > have fun!
> 
> 请教一下哈, dependence tree 能不能解决这个问题呢?

 dependence tree解决不了，dependence tree只能显示最终的jar依赖结果，这些jar有没有冲突，它并不知道。

**Comment by linkingli** [comment]
**点赞**

**Comment by allankin** [comment]
请问下我现在通过Idea运行com.example.demoNoSuchMethodError.DemoNoSuchMethodErrorApplication#main 没有报错啊， 没有java.lang.NoSuchMethodError:异常的 怎么回事？

**Comment by einverne** [comment]
maven enforcer 可以在引入依赖时就去发现冲突，而不是非要等到线上出现问题。

**Comment by 924936307** [comment]
牛气！

**Comment by weiguojian** [comment]
> 上面的issue是系统已经出现了NoSuchMethodError，如果想知道系统里还有哪些类，可能会造成NoSuchMethodError呢？ 能否在maven打包时就能发现呢？
> 
> 借这个issue机会，推广一下自己的插件。 https://github.com/hzdavid/findConflicts
> 使用步骤相当简单：
> 
> git clone https://github.com/hzdavid/findConflicts
> cd findConflicts
> mvn install
> 
> 然后在自己工程的pom.xml中，比如上面的Demo: https://github.com/hengyunabc/spring-boot-inside/tree/master/demo-NoSuchMethodError
> pom.xml里配置插件
> `<plugin> <groupId>findconflicts</groupId> <artifactId>fc-maven-plugin</artifactId> <version>1.0.0-SNAPSHOT</version> <executions> <execution> <phase>package</phase> <goals><goal>go</goal></goals> </execution> </executions> <configuration> <versionCheckConfig>${basedir}/versionCheck.pb</versionCheckConfig> </configuration> </plugin>`
> 
> 然后mvn fc:go -Dshow.class.conflicts=true
> 
> 类冲突，jar冲突，日志冲突一览无余.
> 
> 刚才试过，AnnotationAwareOrderComparator 这个冲突类，这个插件就找到了。
> 
> 希望楼主不要删除这个comment啊，偶可是arthas忠实fans。
> 
> have fun!

在我的场景下 java.lang.NoSuchMethodError: org.springframework.core.annotation.AnnotationAwareOrderComparator.sort(Ljava/util/List;)V， 使用你的插件找不到具体冲突包啊
