### ISSUE TITLE
使用profiler生成alloc事件类型的jfr，结果使用Jprofiler打开后只有CPU事件类型的数据

### ISSUE THREAD

**Issue by Xue2015** [alibaba/arthas#1616]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.3.7
* Arthas 版本: xxx
* 操作系统版本: centos
* 目标进程的JVM版本: openjdk8
* 执行`arthas-boot`的版本: 3.3.7

### 重现问题的步骤

1. 在arthas命令行，使用命令生成jfr文件
[arthas@69]$ profiler start --event alloc --duration 300 --file /tmp/alloc.jfr
Started [alloc] profiling
profiler will silent stop after 300 seconds.
profiler output file will be: /tmp/alloc.jfr
2. 使用jprofiler菜单的open snapshot打开jfr文件

### 期望的结果
应该看到内存的数据

### 实际运行的结果
只能看到CPU的信息，内存的信息是空的
```
把异常信息贴到这里
```

**Comment by DreamLettuce** [comment]
遇到同样的问题，请问有进展吗？

**Comment by astorm-z** [comment]
+1
