### ISSUE TITLE
想给开发组同学提个需求，在watch命令上能否添加condition

### ISSUE THREAD

**Issue by newShiJ** [alibaba/arthas#1617]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 期望的结果
现在使用arthas时会遇到的情况是使用watch命令监控函数调用，但是除了自己在调试以为还有很多其他的流量，导致很难观察最终还是需要自己手动打log。能不能做一个类似debug condition 的功能，指打印输出符合条件的数据，方便查看，

**Comment by hengyunabc** [comment]
https://arthas.aliyun.com/doc/watch  

watch命令本身就支持条件表达式。
