### ISSUE TITLE
arthas-packaging里提供一个Linux环境的解压即用的as.sh

### ISSUE THREAD

**Issue by calvin1978** [alibaba/arthas#162]
因为在生产环境并不能再随便上网下载，因此基本是固定版本使用的。

所以希望类似Windows环境的as.bat，不需要install-local.sh, 也不需要额外的as.sh --use-version 的命令行参数 ，而是提供一个可以直接执行的as-local.sh.

**Comment by hengyunabc** [comment]
#130 目前的 as.sh 已经优先从本地所在的文件夹下面找 jar包，并设置为arthas home了。
