### ISSUE TITLE
想请问一下trace命令打印出来的请求树，默认标红的代表什么意思？

### ISSUE THREAD

**Issue by Skevdv** [alibaba/arthas#1634]
我在用trace命令进行跟踪的时候，打印出来的请求树中有标红的行。
想请问一下标红代表什么意思呢？有什么特殊含义吗？
例如下图：
![18596F04-B766-4FFC-9726-B6D02674712D](https://user-images.githubusercontent.com/59410890/102733562-93382980-4378-11eb-9c05-f889dfed194c.png)

**Comment by lxyyouxiang123** [comment]
同一级耗时最大的一个执行方法
