### ISSUE TITLE
 trace org.apache.phoenix.schema.MetaDataClient addColumn 无法找到匹配的方法

### ISSUE THREAD

**Issue by penglin** [alibaba/arthas#1635]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：  3.1.4  
* Arthas 版本:  3.1.4  
* 操作系统版本: CentOS Linux release 7.2.1511
* 目标进程的JVM版本: Hotspot 1.8.0_121
* 执行`arthas-boot`的版本: 3.1.4  

### 重现问题的步骤

1. 执行 trace org.apache.phoenix.schema.MetaDataClient addColumn
出现 addColumn 方法找不到
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. check arthas log: /data/penglin/logs/arthas/arthas.log
4. visit https://github.com/alibaba/arthas/issues/47 for more details.

实际上是有该方法的
org.apache.phoenix.schema.MetaDataClient addColumn(Lorg/apache/phoenix/parse/AddColumnStatement;)Lorg/apache/phoenix/execute/MutationState;
org.apache.phoenix.schema.MetaDataClient addColumn(Lorg/apache/phoenix/schema/PTable;Ljava/util/List;Lorg/apache/phoenix/shaded/com/google/common/collect/ListMultimap;ZZLorg/apache/phoenix/parse/NamedTableNode;Lorg/apache/phoenix/schema/PTableType;)Lorg/apache/phoenix/execute/MutationState;

另外使用stack 和 watch 检测 addColumn方式是没有问题的

**Comment by hengyunabc** [comment]
sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).

**Comment by penglin** [comment]
arthas  3.4.5   不出现这个问题

**Comment by penglin** [comment]
> sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).

org.apache.phoenix.schema.MetaDataClient addColumn(Lorg/apache/phoenix/parse/AddColumnStatement;)Lorg/apache/phoenix/execute/MutationState;
org.apache.phoenix.schema.MetaDataClient addColumn(Lorg/apache/phoenix/schema/PTable;Ljava/util/List;Lorg/apache/phoenix/shaded/com/google/common/collect/ListMultimap;ZZLorg/apache/phoenix/parse/NamedTableNode;Lorg/apache/phoenix/schema/PTableType;)Lorg/apache/phoenix/execute/MutationState;

上面的内容就是sm 查出来的

**Comment by hengyunabc** [comment]
> arthas 3.4.5 不出现这个问题

额，旧版本的bug就不查了。。
