### ISSUE TITLE
关于thread看板的time字段的疑问

### ISSUE THREAD

**Issue by yuke0929** [alibaba/arthas#1639]
### 环境信息

* `arthas-boot.jar`版本：3.1.0
* Arthas 版本: 3.4.5
* 操作系统版本: Linux version 4.19.113-300.el7.x86_64
* 目标进程的JVM版本: jdk1.8.0_211
* 执行`arthas-boot`的版本: 3.1.0

使用thread命令查看线程执行情况
前一天看了下某个线程的time 是1388
第二天同一时间点看了下 是1700 时间大概过去22小时左右
如果time是分钟，则过去312分钟 说不过去啊。
有个新开了90分钟的线程 看了下time是24，初步统计出来time的一个时间单位是4分钟左右

查了下文档说time的格式是minute:secord，怎么感觉不像呢？
前一天18:00：
![image](https://user-images.githubusercontent.com/16641263/103129847-35d40d80-46d5-11eb-9fd1-2b3fb697a407.png)
第二天16:30
![image](https://user-images.githubusercontent.com/16641263/103129889-5ac88080-46d5-11eb-8d31-4f8167bdf01d.png)

**Comment by who7708** [comment]
这个time应该是计算的此线程运行的总时间, 而不是存在的总时间, "如果time是分钟，则过去312分钟 " 这个300多分钟指的是系统大概一天的时间, 此线程运行了大概300分钟.

**Comment by who7708** [comment]
> ### 环境信息
> * `arthas-boot.jar`版本：3.1.0
> * Arthas 版本: 3.4.5
> * 操作系统版本: Linux version 4.19.113-300.el7.x86_64
> * 目标进程的JVM版本: jdk1.8.0_211
> * 执行`arthas-boot`的版本: 3.1.0
> 
> 使用thread命令查看线程执行情况
> 前一天看了下某个线程的time 是1388
> 第二天同一时间点看了下 是1700 时间大概过去22小时左右
> 如果time是分钟，则过去312分钟 说不过去啊。
> 有个新开了90分钟的线程 看了下time是24，初步统计出来time的一个时间单位是4分钟左右
> 
> 查了下文档说time的格式是minute:secord，怎么感觉不像呢？
> 前一天18:00：
> ![image](https://user-images.githubusercontent.com/16641263/103129847-35d40d80-46d5-11eb-9fd1-2b3fb697a407.png)
> 第二天16:30
> ![image](https://user-images.githubusercontent.com/16641263/103129889-5ac88080-46d5-11eb-8d31-4f8167bdf01d.png)

这个time应该是计算的此线程运行的总时间, 而不是存在的总时间, "如果time是分钟，则过去312分钟 " 这个300多分钟指的是系统大概一天的时间, 此线程运行了大概300分钟.
