### ISSUE TITLE
对HashMap的containsKey和get方法进行trace产生的疑问

### ISSUE THREAD

**Issue by yingqin678** [alibaba/arthas#164]
trace的方法如下：

```java

public void changeConfValue(String key, String value){
        if (transConfigMap.containsKey(key))
        {
            Configuration.setConfValue(key,ParseUtil.parseValue(transConfigMap.get(key), value));
        }
        else
        {
            Configuration.setConfValue(key, value);
        }
}
```

对结果分析发现containsKey耗时明显会比get要长一些，但是查看源码，两个方法的实现基本一致，会不会是trace的时候，影响了方法的耗时呢？
trace日志在下方

**Comment by yingqin678** [comment]
$ trace com.***.zookeeper.AbstractNotificationConfValueChangeService changeConfValue
Press Ctrl+C to abort.lue
Affect(class-cnt:2 , method-cnt:1) cost in 96 ms.
`---ts=2018-09-26 19:50:20;thread_name=ZKConfigHolder-reviseTask;id=2d;is_daemon

=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@301769e4
    `---[0.887158ms] com.***.zookeeper.AbstractNotification

ConfValueChangeService:changeConfValue()
        +---[0.136633ms] java.util.Map:containsKey()
        +---[0.036884ms] java.util.Map:get()
        +---[0.02181ms] com.***.util.ParseUtil:parseValue()

        `---[0.099749ms] com.***.zookeeper.Configuration:se

tConfValue()

`---ts=2018-09-26 19:56:51;thread_name=ZKConfigHolder-reviseTask;id=2d;is_daemon

=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@301769e4
    `---[0.279362ms] com.***.zookeeper.AbstractNotification

ConfValueChangeService:changeConfValue()
        +---[0.009622ms] java.util.Map:containsKey()
        +---[0.005773ms] java.util.Map:get()
        +---[0.013151ms] com.***.util.ParseUtil:parseValue(

)
        `---[0.009622ms] com.***.zookeeper.Configuration:se

tConfValue()

`---ts=2018-09-26 19:57:08;thread_name=ZKConfigHolder-reviseTask;id=2d;is_daemon

=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@301769e4
    `---[0.277758ms] com.***.zookeeper.AbstractNotification

ConfValueChangeService:changeConfValue()
        +---[0.010584ms] java.util.Map:containsKey()
        +---[0.006736ms] java.util.Map:get()
        +---[0.011226ms] com.***.util.ParseUtil:parseValue(

)
        `---[0.00898ms] com.***.zookeeper.Configuration:set

ConfValue()

`---ts=2018-09-26 19:57:19;thread_name=ZKConfigHolder-reviseTask;id=2d;is_daemon

=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@301769e4
    `---[9.79113ms] com.***.zookeeper.AbstractNotificationC

onfValueChangeService:changeConfValue()
        +---[0.008981ms] java.util.Map:containsKey()
        +---[0.005132ms] java.util.Map:get()
        +---[0.009943ms] com.***.util.ParseUtil:parseValue(

)
        `---[0.732563ms] com.***.zookeeper.Configuration:se

tConfValue()

`---ts=2018-09-26 19:57:34;thread_name=ZKConfigHolder-reviseTask;id=2d;is_daemon

=true;priority=5;TCCL=org.apache.catalina.loader.WebappClassLoader@301769e4
    `---[0.662001ms] com.***.zookeeper.AbstractNotification

ConfValueChangeService:changeConfValue()
        +---[0.045545ms] java.util.Map:containsKey()
        +---[0.009301ms] java.util.Map:get()
        +---[0.031753ms] com.***.util.ParseUtil:parseValue(

)
        `---[0.009301ms] com.***.zookeeper.Configuration:se

tConfValue()

**Comment by yingqin678** [comment]
将containsKey替换为get方法，两个get方法一共的耗时查看是正常的

**Comment by hengyunabc** [comment]
调用耗时太短，意义不大。trace增加的消耗可能比函数调用本身的开销都大。
