### ISSUE TITLE
telnet/websocket 都不支持输入中文

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1643]
attach成功之后，尝试直接原生 telnet连接，或者用 arthas-client.jar 去连接，或者在webconsole输入，都没办法输入中文。

可能是termd后端处理的问题。

**Comment by hengyunabc** [comment]
https://xtermjs.org/docs/guides/encoding/

**Comment by chenshun00** [comment]
应该是telnet协议后端不支持中文，xtermjs 本身也是在模拟数据展现在终端.

**Comment by a6513375** [comment]
三年了 请问解决了吗
