### ISSUE TITLE
dashboard上的内存中mapped占用很高，意义是什么？

### ISSUE THREAD

**Issue by fengqjJoy** [alibaba/arthas#1656]
在你们的官网说明上没列出来

**Comment by who7708** [comment]
mapped 是 内存映射缓冲区. 估计是程序频繁读写文件了吧.

**Comment by fengqjJoy** [comment]
谢谢，是这样，已经解决了，非常感谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;who7708&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月15日(星期五) 晚上10:01
收件人:&nbsp;&quot;alibaba/arthas&quot;<arthas@noreply.github.com&gt;;
抄送:&nbsp;&quot;Joy&quot;<409902978@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/arthas] dashboard上的内存中mapped占用很高，意义是什么？ (#1656)

**Comment by jiankunking** [comment]
> 谢谢，是这样，已经解决了，非常感谢------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;who7708&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月15日(星期五) 晚上10:01 收件人:&nbsp;&quot;alibaba/arthas&quot;<arthas@noreply.github.com&gt;; 抄送:&nbsp;&quot;Joy&quot;<409902978@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [alibaba/arthas] dashboard上的内存中mapped占用很高，意义是什么？ (#1656)

你好 如何解决的呢？我也遇到了一个类似的问题
https://stackoverflow.com/questions/70799585/kafka-broker-memory-imbalance

**Comment by fengqjJoy** [comment]
来信已收到，谢谢！
