### ISSUE TITLE
watch的返回结果命令,好像只返回子类的属性,父类型的没有显示

### ISSUE THREAD

**Issue by sky-lft** [alibaba/arthas#1663]
watch com.demo.treeService findOrgTrees returnObj -x 4

结果如下:
ts=2021-01-12 17:15:33; [cost=3.912033ms] result=@ArrayList[
    @OrgTreeBo[
        industryCode=null,
        organType=null,
        catalogTypeName=null,
    ],
    @OrgTreeBo[
        industryCode=null,
        organType=null,
        catalogTypeName=null,
    ],
    @OrgTreeBo[
        industryCode=null,
        organType=null,
        catalogTypeName=null,
    ]
]

**Comment by hengyunabc** [comment]
用最新版本。 options -h 里有一个选项 是否打印 parent field，默认应该是true的。
