### ISSUE TITLE
启动脚本报错

### ISSUE THREAD

**Issue by vancfbruce** [alibaba/arthas#167]
我执行启动脚本报错 syntax error at line 93:`(' is not expected 我的arthas是3.0.4 系统是hp-ux

**Comment by vancfbruce** [comment]
改成 bash也没用

**Comment by hengyunabc** [comment]
`bash -version` 看下具体是什么版本。 `as.sh`只支持 bash ，有可能系统上的bash是sh链接过去的。

不行的话，可以尝试用手动拼接的方式来启动： https://alibaba.github.io/arthas/install-detail.html#
