### ISSUE TITLE
Maven中arthas-spring-boot-starter的使用疑问

### ISSUE THREAD

**Issue by MentosL** [alibaba/arthas#1670]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

spring-parent >=2.0
arthas-spring-boot-starter  3.4.6

### 疑惑点

1. 想询问下 是不是增加了对应的arthas依赖之后，必须结合arthas-tunnel-server才可以进行使用？
2. 单纯的一个springboot 服务不结合tunnel-server是否可以支持使用，（官网文档查看过了，但是没有查到对应的demo或者使用文章）

**Comment by hengyunabc** [comment]
加入 maven依赖之后，直接启动应用，就用 attach自身，就可以查看了。 `telnet localhost 3658` 或者访问web： https://arthas.aliyun.com/doc/web-console.html

**Comment by hengyunabc** [comment]
arthas-tunnel-server 是管理个节点时使用的。节点和正常使用的 arthas没区别。

**Comment by MentosL** [comment]
> arthas-tunnel-server 是管理个节点时使用的。节点和正常使用的 arthas没区别。

好的 谢谢大佬解惑
