### ISSUE TITLE
发现一个彩蛋命令july

### ISSUE THREAD

**Issue by zimaoo** [alibaba/arthas#1673]
内容为[Kelly Clarkson](https://en.wikipedia.org/wiki/Kelly_Clarkson)专辑《[Breakaway](https://music.163.com/album?id=1496726)》名曲《[Because of You](https://music.163.com/song?id=16232634)》

**Comment by xiaobaobao007** [comment]
有趣~

**Comment by RichurLiu** [comment]
有趣~~

**Comment by goshcc** [comment]
> 有趣~~

wo lei

**Comment by hengyunabc** [comment]
这个彩蛋实际上来自 greys，保留下来了。
