### ISSUE TITLE
无法启动，报错Connection refused: connect

### ISSUE THREAD

**Issue by GideonZhao** [alibaba/arthas#1683]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.6
* Arthas 版本: 3.4.6
* 操作系统版本: Windows 10 Pro 19042.746
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 11

### 重现问题的步骤

1. 下载arthas-boot.jar
2. 运行arthas-boot.jar

### 期望的结果

进入arthas交互界面

### 实际运行的结果

PS D:\Utils\arthas> java -jar .\arthas-boot.jar
[INFO] arthas-boot version: 3.4.6
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 23264 .\jd-gui-1.6.6-min.jar
1
[INFO] arthas home: C:\Users\gideo\.arthas\lib\3.4.6\arthas
[INFO] Try to attach process 23264
[INFO] Attach process 23264 success.
[INFO] arthas-client connect 127.0.0.1 3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused: connect
        at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
        at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
        at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:309)
        at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:566)
Usage: arthas-client [-w <value>] [-f <value>] [-c <value>] [--help] [-h
       <value>] [-t <value>] [target-ip] [port]

Arthas Telnet Client

EXAMPLES:
  java -jar arthas-client.jar 127.0.0.1 3658
  java -jar arthas-client.jar -c 'dashboard -n 1'
  java -jar arthas-client.jar -f batch.as 127.0.0.1

Options and Arguments:
 -w,--width <value>               The terminal width
 -f,--batch-file <value>          The batch file to execute
 -c,--command <value>             Command to execute, multiple commands
                                  separated by ;
    --help                        Print usage
 -h,--height <value>              The terminal height
 -t,--execution-timeout <value>   The timeout (ms) of execute commands or batch
                                  file
 <target-ip>                      Target ip
 <port>                           The remote server port

3658端口没有被占用

在WSL中使用正常 只在Windws命令行中出错

在用户目录(C:\Users\gideo)中没有找到logs文件夹

尝试过使用Administrators权限启动

**Comment by hengyunabc** [comment]
试下启动 arthas-demo.jar ，看可以工作不。

**Comment by GideonZhao** [comment]
> 试下启动 arthas-demo.jar ，看可以工作不。

arthas-demo.jar可以正常工作 使用arthas-boot.jar attch到arthas-demo.jar依旧报错Connection refused: connect

**Comment by hengyunabc** [comment]
试下 jstack 命令能不能工作。

**Comment by GideonZhao** [comment]
> 试下 jstack 命令能不能工作。

这个是arthas-boot.jar在attch过程中的jstack结果

> PS C:\Users\gideo> jstack 22244
> 2021-01-28 09:58:06
> Full thread dump OpenJDK 64-Bit Server VM (11+28 mixed mode):
> 
> Threads class SMR info:
> _java_thread_list=0x000002874c38a940, length=14, elements={
> 0x000002871cec0000, 0x000002874bb13000, 0x000002874bb14800, 0x000002874bba6800,
> 0x000002874bba7800, 0x000002874bbac000, 0x000002874bbaf000, 0x000002874bbb3000,
> 0x000002874bd63800, 0x000002874bd69800, 0x000002874c353800, 0x000002874c546000,
> 0x000002874c56d800, 0x000002874c30f000
> }
> 
> "main" #1 prio=5 os_prio=0 cpu=437.50ms elapsed=17.44s tid=0x000002871cec0000 nid=0x68b0 runnable  [0x00000093bf7fe000]
>    java.lang.Thread.State: RUNNABLE
>         at java.net.PlainSocketImpl.waitForConnect(java.base@11/Native Method)
>         at java.net.PlainSocketImpl.socketConnect(java.base@11/PlainSocketImpl.java:107)
>         at java.net.AbstractPlainSocketImpl.doConnect(java.base@11/AbstractPlainSocketImpl.java:399)
>         - locked <0x0000000620804fa8> (a java.net.SocksSocketImpl)
>         at java.net.AbstractPlainSocketImpl.connectToAddress(java.base@11/AbstractPlainSocketImpl.java:242)
>         at java.net.AbstractPlainSocketImpl.connect(java.base@11/AbstractPlainSocketImpl.java:224)
>         at java.net.SocksSocketImpl.connect(java.base@11/SocksSocketImpl.java:403)
>         at java.net.Socket.connect(java.base@11/Socket.java:591)
>         at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
>         at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
>         at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:309)
>         at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11/Native Method)
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11/NativeMethodAccessorImpl.java:62)
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11/DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(java.base@11/Method.java:566)
>         at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:566)
> 
> "Reference Handler" #2 daemon prio=10 os_prio=2 cpu=0.00ms elapsed=17.42s tid=0x000002874bb13000 nid=0x6788 waiting on condition  [0x00000093bfeff000]
>    java.lang.Thread.State: RUNNABLE
>         at java.lang.ref.Reference.waitForReferencePendingList(java.base@11/Native Method)
>         at java.lang.ref.Reference.processPendingReferences(java.base@11/Reference.java:241)
>         at java.lang.ref.Reference$ReferenceHandler.run(java.base@11/Reference.java:213)
> 
> "Finalizer" #3 daemon prio=8 os_prio=1 cpu=0.00ms elapsed=17.42s tid=0x000002874bb14800 nid=0x6be4 in Object.wait()  [0x00000093bffff000]
>    java.lang.Thread.State: WAITING (on object monitor)
>         at java.lang.Object.wait(java.base@11/Native Method)
>         - waiting on <0x0000000621e08f10> (a java.lang.ref.ReferenceQueue$Lock)
>         at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
>         - waiting to re-lock in wait() <0x0000000621e08f10> (a java.lang.ref.ReferenceQueue$Lock)
>         at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:176)
>         at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11/Finalizer.java:170)
> 
> "Signal Dispatcher" #4 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=17.41s tid=0x000002874bba6800 nid=0x76a8 runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Attach Listener" #5 daemon prio=5 os_prio=2 cpu=0.00ms elapsed=17.41s tid=0x000002874bba7800 nid=0x6ac0 waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "C2 CompilerThread0" #6 daemon prio=9 os_prio=2 cpu=109.38ms elapsed=17.41s tid=0x000002874bbac000 nid=0x6bd0 waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
>    No compile task
> 
> "C1 CompilerThread0" #14 daemon prio=9 os_prio=2 cpu=140.63ms elapsed=17.41s tid=0x000002874bbaf000 nid=0x5374 waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
>    No compile task
> 
> "Sweeper thread" #18 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=17.41s tid=0x000002874bbb3000 nid=0x66e8 runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Service Thread" #19 daemon prio=9 os_prio=0 cpu=0.00ms elapsed=17.39s tid=0x000002874bd63800 nid=0x4a6c runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Common-Cleaner" #20 daemon prio=8 os_prio=1 cpu=0.00ms elapsed=17.39s tid=0x000002874bd69800 nid=0x35fc in Object.wait()  [0x00000093c08ff000]
>    java.lang.Thread.State: TIMED_WAITING (on object monitor)
>         at java.lang.Object.wait(java.base@11/Native Method)
>         - waiting on <0x0000000621ff2260> (a java.lang.ref.ReferenceQueue$Lock)
>         at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
>         - waiting to re-lock in wait() <0x0000000621ff2260> (a java.lang.ref.ReferenceQueue$Lock)
>         at jdk.internal.ref.CleanerImpl.run(java.base@11/CleanerImpl.java:148)
>         at java.lang.Thread.run(java.base@11/Thread.java:834)
>         at jdk.internal.misc.InnocuousThread.run(java.base@11/InnocuousThread.java:134)
> 
> "C1 CompilerThread1" #15 daemon prio=9 os_prio=2 cpu=15.63ms elapsed=3.29s tid=0x000002874c353800 nid=0x4b00 waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
>    No compile task
> 
> "Keep-Alive-Timer" #22 daemon prio=8 os_prio=1 cpu=0.00ms elapsed=2.94s tid=0x000002874c546000 nid=0x75a0 waiting on condition  [0x00000093c09fe000]
>    java.lang.Thread.State: TIMED_WAITING (sleeping)
>         at java.lang.Thread.sleep(java.base@11/Native Method)
>         at sun.net.www.http.KeepAliveCache.run(java.base@11/KeepAliveCache.java:168)
>         at java.lang.Thread.run(java.base@11/Thread.java:834)
>         at jdk.internal.misc.InnocuousThread.run(java.base@11/InnocuousThread.java:134)
> 
> "NonBlockingInputStreamThread" #24 daemon prio=5 os_prio=0 cpu=0.00ms elapsed=2.86s tid=0x000002874c56d800 nid=0xe68 in Object.wait()  [0x00000093c0afe000]
>    java.lang.Thread.State: WAITING (on object monitor)
>         at java.lang.Object.wait(java.base@11/Native Method)
>         - waiting on <0x0000000620d989c8> (a jline.internal.NonBlockingInputStream)
>         at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
>         - waiting to re-lock in wait() <0x0000000620d989c8> (a jline.internal.NonBlockingInputStream)
>         at java.lang.Thread.run(java.base@11/Thread.java:834)
> 
> "NonBlockingInputStreamThread" #26 daemon prio=5 os_prio=0 cpu=0.00ms elapsed=0.73s tid=0x000002874c30f000 nid=0x7258 in Object.wait()  [0x00000093c05ff000]
>    java.lang.Thread.State: WAITING (on object monitor)
>         at java.lang.Object.wait(java.base@11/Native Method)
>         - waiting on <0x0000000620b9bcf8> (a jline.internal.NonBlockingInputStream)
>         at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
>         - waiting to re-lock in wait() <0x0000000620b9bcf8> (a jline.internal.NonBlockingInputStream)
>         at java.lang.Thread.run(java.base@11/Thread.java:834)
> 
> "VM Thread" os_prio=2 cpu=0.00ms elapsed=17.42s tid=0x000002874bb11800 nid=0x43b0 runnable
> 
> "GC Thread#0" os_prio=2 cpu=0.00ms elapsed=17.44s tid=0x000002871ced3000 nid=0x7bac runnable
> 
> "G1 Main Marker" os_prio=2 cpu=0.00ms elapsed=17.44s tid=0x000002871cf54000 nid=0x7450 runnable
> 
> "G1 Conc#0" os_prio=2 cpu=0.00ms elapsed=17.44s tid=0x000002871cf59800 nid=0xe54 runnable
> 
> "G1 Refine#0" os_prio=2 cpu=0.00ms elapsed=17.43s tid=0x000002874b172000 nid=0x3218 runnable
> 
> "G1 Young RemSet Sampling" os_prio=2 cpu=0.00ms elapsed=17.43s tid=0x000002874b173000 nid=0x602c runnable
> "VM Periodic Task Thread" os_prio=2 cpu=0.00ms elapsed=17.39s tid=0x000002874bd65800 nid=0x7004 waiting on condition
> 
> JNI global refs: 26, weak refs: 0

**Comment by hengyunabc** [comment]
@GideonZhao 是对目标进程进行 jstack 。比如 arthas-demo 进程。

**Comment by GideonZhao** [comment]
> @GideonZhao 是对目标进程进行 jstack 。比如 arthas-demo 进程。

结果如下

> PS C:\Users\gideo> jstack 30388
> 2021-01-28 11:10:56
> Full thread dump OpenJDK 64-Bit Server VM (11+28 mixed mode):
> 
> Threads class SMR info:
> _java_thread_list=0x000001acfb3d51a0, length=10, elements={
> 0x000001accc4bf800, 0x000001acfb124000, 0x000001acfb14d800, 0x000001acfb1b8800,
> 0x000001acfb1b9800, 0x000001acfb1be800, 0x000001acfb1c1800, 0x000001acfb1c2800,
> 0x000001acfb385000, 0x000001acfb367800
> }
> 
> "main" #1 prio=5 os_prio=0 cpu=109.38ms elapsed=8.07s tid=0x000001accc4bf800 nid=0x4ad0 waiting on condition  [0x0000002700fff000]
>    java.lang.Thread.State: TIMED_WAITING (sleeping)
>         at java.lang.Thread.sleep(java.base@11/Native Method)
>         at java.lang.Thread.sleep(java.base@11/Thread.java:339)
>         at java.util.concurrent.TimeUnit.sleep(java.base@11/TimeUnit.java:446)
>         at demo.MathGame.main(MathGame.java:17)
> 
> "Reference Handler" #2 daemon prio=10 os_prio=2 cpu=0.00ms elapsed=8.06s tid=0x000001acfb124000 nid=0x5684 waiting on condition  [0x00000027016fe000]
>    java.lang.Thread.State: RUNNABLE
>         at java.lang.ref.Reference.waitForReferencePendingList(java.base@11/Native Method)
>         at java.lang.ref.Reference.processPendingReferences(java.base@11/Reference.java:241)
>         at java.lang.ref.Reference$ReferenceHandler.run(java.base@11/Reference.java:213)
> 
> "Finalizer" #3 daemon prio=8 os_prio=1 cpu=0.00ms elapsed=8.06s tid=0x000001acfb14d800 nid=0x79b8 in Object.wait()  [0x00000027017ff000]
>    java.lang.Thread.State: WAITING (on object monitor)
>         at java.lang.Object.wait(java.base@11/Native Method)
>         - waiting on <0x0000000621e08f10> (a java.lang.ref.ReferenceQueue$Lock)
>         at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
>         - waiting to re-lock in wait() <0x0000000621e08f10> (a java.lang.ref.ReferenceQueue$Lock)
>         at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:176)
>         at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11/Finalizer.java:170)
> 
> "Signal Dispatcher" #4 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=8.04s tid=0x000001acfb1b8800 nid=0x50d8 runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Attach Listener" #5 daemon prio=5 os_prio=2 cpu=0.00ms elapsed=8.04s tid=0x000001acfb1b9800 nid=0x7038 waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "C2 CompilerThread0" #6 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=8.04s tid=0x000001acfb1be800 nid=0x161c waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
>    No compile task
> 
> "C1 CompilerThread0" #14 daemon prio=9 os_prio=2 cpu=31.25ms elapsed=8.04s tid=0x000001acfb1c1800 nid=0x515c waiting on condition  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
>    No compile task
> 
> "Sweeper thread" #18 daemon prio=9 os_prio=2 cpu=0.00ms elapsed=8.04s tid=0x000001acfb1c2800 nid=0x655c runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Service Thread" #19 daemon prio=9 os_prio=0 cpu=0.00ms elapsed=8.03s tid=0x000001acfb385000 nid=0x55b8 runnable  [0x0000000000000000]
>    java.lang.Thread.State: RUNNABLE
> 
> "Common-Cleaner" #20 daemon prio=8 os_prio=1 cpu=15.63ms elapsed=8.03s tid=0x000001acfb367800 nid=0x4a6c in Object.wait()  [0x00000027020ff000]
>    java.lang.Thread.State: TIMED_WAITING (on object monitor)
>         at java.lang.Object.wait(java.base@11/Native Method)
>         - waiting on <0x0000000621ff2248> (a java.lang.ref.ReferenceQueue$Lock)
>         at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
>         - waiting to re-lock in wait() <0x0000000621ff2248> (a java.lang.ref.ReferenceQueue$Lock)
>         at jdk.internal.ref.CleanerImpl.run(java.base@11/CleanerImpl.java:148)
>         at java.lang.Thread.run(java.base@11/Thread.java:834)
>         at jdk.internal.misc.InnocuousThread.run(java.base@11/InnocuousThread.java:134)
> 
> "VM Thread" os_prio=2 cpu=0.00ms elapsed=8.06s tid=0x000001acfb122800 nid=0x75a4 runnable
> 
> "GC Thread#0" os_prio=2 cpu=0.00ms elapsed=8.07s tid=0x000001accc4d2800 nid=0x5214 runnable
> 
> "G1 Main Marker" os_prio=2 cpu=0.00ms elapsed=8.07s tid=0x000001accc555000 nid=0x21b0 runnable
> 
> "G1 Conc#0" os_prio=2 cpu=0.00ms elapsed=8.07s tid=0x000001accc558800 nid=0x7314 runnable
> 
> "G1 Refine#0" os_prio=2 cpu=0.00ms elapsed=8.07s tid=0x000001acfa459800 nid=0x45d0 runnable
> 
> "G1 Young RemSet Sampling" os_prio=2 cpu=0.00ms elapsed=8.07s tid=0x000001acfa45a000 nid=0x2ee4 runnable
> "VM Periodic Task Thread" os_prio=2 cpu=0.00ms elapsed=8.03s tid=0x000001acfb386800 nid=0x4678 waiting on condition
> 
> JNI global refs: 17, weak refs: 0

**Comment by hengyunabc** [comment]
> 目标进程的JVM版本: 1.8
> 执行arthas-boot的版本: 11

要用目标进程的jvm来启动。

**Comment by GideonZhao** [comment]
> > 目标进程的JVM版本: 1.8
> > 执行arthas-boot的版本: 11
> 
> 要用目标进程的jvm来启动。

@hengyunabc 最开始需要attch的进程是JDK 1.8的 但是后续使用arthas-demo.jar测试时 用的是相同的JDK 都是11。

> PS D:\Utils\arthas> java -version
> openjdk version "11" 2018-09-25
> OpenJDK Runtime Environment 18.9 (build 11+28)
> OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
> PS D:\Utils\arthas> java -jar .\arthas-demo.jar
> 90604=2*2*22651
> 167682=2*3*27947

> PS D:\Utils\arthas> java -version
> openjdk version "11" 2018-09-25
> OpenJDK Runtime Environment 18.9 (build 11+28)
> OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
> PS D:\Utils\arthas> java -jar .\arthas-boot.jar
> [INFO] arthas-boot version: 3.4.6
> [INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
> * [1]: 23264 .\jd-gui-1.6.6-min.jar
>   [2]: 28748
>   [3]: 6204 .\arthas-demo.jar
> 3
> [INFO] arthas home: C:\Users\gideo\.arthas\lib\3.4.6\arthas
> [INFO] Try to attach process 6204
> [INFO] Attach process 6204 success.
> [INFO] arthas-client connect 127.0.0.1 3658
> Connect to telnet server error: 127.0.0.1 3658
> java.net.ConnectException: Connection refused: connect
>         at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
>         at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
>         at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
>         at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
>         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
>         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
>         at java.base/java.net.Socket.connect(Socket.java:591)
>         at org.apache.commons.net.SocketClient.connect(SocketClient.java:188)
>         at org.apache.commons.net.SocketClient.connect(SocketClient.java:209)
>         at com.taobao.arthas.client.TelnetConsole.process(TelnetConsole.java:309)
>         at com.taobao.arthas.client.TelnetConsole.main(TelnetConsole.java:166)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at com.taobao.arthas.boot.Bootstrap.main(Bootstrap.java:566)
> Usage: arthas-client [--help] [-c <value>] [-f <value>] [-w <value>] [-t
>        <value>] [-h <value>] [target-ip] [port]
> 
> Arthas Telnet Client
> 
> EXAMPLES:
>   java -jar arthas-client.jar 127.0.0.1 3658
>   java -jar arthas-client.jar -c 'dashboard -n 1'
>   java -jar arthas-client.jar -f batch.as 127.0.0.1
> 
> Options and Arguments:
>     --help                        Print usage
>  -c,--command <value>             Command to execute, multiple commands
>                                   separated by ;
>  -f,--batch-file <value>          The batch file to execute
>  -w,--width <value>               The terminal width
>  -t,--execution-timeout <value>   The timeout (ms) of execute commands or batch
>                                   file
>  -h,--height <value>              The terminal height
>  <target-ip>                      Target ip
>  <port>                           The remote server port

**Comment by maodou38** [comment]
我在docker中使用也是 connection refused。jstack正常

**Comment by tyzou** [comment]
请问最后怎么解决的？

**Comment by zheng-zy** [comment]
请问最后怎么解决的？

**Comment by GideonZhao** [comment]
> 请问最后怎么解决的？

没再继续看下去了。只知道跟Telnet Server有关系，比如没启动之类的。
