### ISSUE TITLE
【使用咨询】arthas能否实现未使用类的扫描功能

### ISSUE THREAD

**Issue by windskya** [alibaba/arthas#1684]
一个项目随着编码量的不断增加，代码维护变得越来越困难，许多类即使长期未使用，也不敢放心把它删除，项目体积变得越来越大。arthas是否有这样一种功能，通过JVM底层监控，找出项目中未运行的、未使用到的类，之后开发人员可以把这些未用到的类删除，使项目更加简洁。

之前使用过UCDetector、ProGuard等IDE插件扫描未使用的类，但效果较为一般，也不够准确。

求指教arthas是否也能实现未使用类的扫描功能，感谢~

**Comment by hengyunabc** [comment]
arthas的classloader命令可以把所有加载的类信息导出来。可以自己再分析相关的信息。

**Comment by windskya** [comment]
> arthas的classloader命令可以把所有加载的类信息导出来。可以自己再分析相关的信息。

在使用classloader命令的时候，会输出数量庞大的类列表，是否可以在使用该命令的时候做一个限制，比如只输出com.hello.*包下面的类，然后把结果输出成一个文档。
您能否指导一下？谢谢

**Comment by hengyunabc** [comment]
可以把输出结果重定向到文件，然后再自己写个简单程序分析。 或者试下 http api。
