### ISSUE TITLE
arthas-shell-server 这个线程池，退出arthas后一直存在吗？

### ISSUE THREAD

**Issue by hellomsg** [alibaba/arthas#1688]
![image](https://user-images.githubusercontent.com/8427859/106428197-8b08f900-64a3-11eb-8ef9-e4a4b41cd03e.png)

**Comment by hengyunabc** [comment]
执行 `stop` 才是彻底退出。

**Comment by hellomsg** [comment]
> 执行 `stop` 才是彻底退出。

谢谢，明白了。
