### ISSUE TITLE
同节点多个相同java进程不好识别

### ISSUE THREAD

**Issue by jokimina** [alibaba/arthas#169]
同节点多个相同java进程(比如多个tomcat)不好识别, as.sh中jps可否加上-v选项或可传递的可选选项,

**Comment by hengyunabc** [comment]
加下 `-v` 输出太长了。不过可以考虑后续给 `as.sh`加上一个`-v`，然后传给 `jps`。

**Comment by hengyunabc** [comment]
e1e15e8 加了 -v 参数
