### ISSUE TITLE
arthas tunnel server web端花屏

### ISSUE THREAD

**Issue by Crysmart** [alibaba/arthas#1693]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.6
* Arthas 版本: 3.4.6
* 操作系统版本: windows10 
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.4.6

### 重现问题的步骤

1. 不晓得怎么冒出来的
2. command line 花屏

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
![avatar](https://s3.ax1x.com/2021/02/06/yYjRyT.png)

**Comment by hengyunabc** [comment]
试下换个浏览器。或者检查下是不是有配置了浏览器样式之类的，或者装了某些插件。

**Comment by Crysmart** [comment]
要得，是切换了web选项卡花屏的，回来看时的间隔有点长
