### ISSUE TITLE
arthas tunnel server管理远程的agent（以命令行的模式操作，而非web console）

### ISSUE THREAD

**Issue by huangjiamei** [alibaba/arthas#1703]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 在机器1上启动arthas-demo.jar：java -jar arthas-demo.jar
2. 在机器2上启动arthas-tunnel-server-3.4.6-fatjar.jar： java -jar  arthas-tunnel-server-3.4.6-fatjar.jar 
3. 在机器1上启动arthas-boot.jar并连接到tunnel server：java -jar arthas-boot.jar --tunnel-server 'ws://127.0.0.1:7777/ws'
![image](https://user-images.githubusercontent.com/14937535/108691560-9ac1ad80-7536-11eb-98f8-d87d28ef3a27.png)
4. 在机器2上通过命令行的方式，通过已注册的agetnid连接到机器1的arthas agent
![image](https://user-images.githubusercontent.com/14937535/108691594-a2815200-7536-11eb-90c2-145cd6125223.png)

### 期望的结果

在机器2上可通过命令行的方式管理机器1的agent

### 实际运行的结果

在机器2上输入命令没有反应
![image](https://user-images.githubusercontent.com/14937535/108691838-e4aa9380-7536-11eb-8bb9-a9056209ec0d.png)

**Comment by hengyunabc** [comment]
祼的websocket肯定不能工作。实际上是 https://github.com/xtermjs/xterm.js/ 的协议。

**Comment by huangjiamei** [comment]
> 祼的websocket肯定不能工作。实际上是 https://github.com/xtermjs/xterm.js/ 的协议。
下面是我的机器2通过curl命令来发送的websocket请求命令，那请问如果我想用命令行的方式来实现通信，具体步骤应该怎么做呢？
curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: http://127.0.0.1:7777" \
     --header "Origin: http://localhost" \
     --header "Sec-WebSocket-Key: NVwjmQUcWCenfWu98asDmg==" \
     --header "Sec-WebSocket-Version: 13" \
     http://127.0.0.1:7777/ws?method=connectArthas\&id=CQTVOPEG3CVDGXLITFZ2

**Comment by hengyunabc** [comment]
这个意义不大。 具体的数据包，看 xterm本身的协议文档，或者用 wireshark 抓下包。

**Comment by huangjiamei** [comment]
> 这个意义不大。 具体的数据包，看 xterm本身的协议文档，或者用 wireshark 抓下包。

因为我想在两台机器上进行通信，在一台机器上管理另一台机器上的agent，请问有什么推荐的办法吗？

**Comment by hengyunabc** [comment]
> > 这个意义不大。 具体的数据包，看 xterm本身的协议文档，或者用 wireshark 抓下包。
> 
> 因为我想在两台机器上进行通信，在一台机器上管理另一台机器上的agent，请问有什么推荐的办法吗？

tunnel server本身就是一个集中式的管理。
