### ISSUE TITLE
进程监控失败

### ISSUE THREAD

**Issue by wmq930626** [alibaba/arthas#1708]
arthas正常启动
[INFO] arthas-boot version: 3.4.6
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.

选择监控id[1] 报如下错误

[ERROR] Can not read arthas version from: https://arthas.aliyun.com/api/latest_version
[ERROR] Can not find Arthas under local: /home/xiaoju/.arthas/lib and remote repo mirror: aliyun
[ERROR] Unable to download arthas from remote server, please download the full package according to wiki: https://github.com/alibaba/arthas

**Comment by hengyunabc** [comment]
网络不通，下载全量包解压使用。

**Comment by wmq930626** [comment]
感谢大佬解惑，已解决
