### ISSUE TITLE
是否可以统计一段时间内的新增和销毁的线程信息？

### ISSUE THREAD

**Issue by GungnirLaevatain** [alibaba/arthas#1718]
希望 **thread** 命令能够支持检测展示一段时间内的线程创建和摧毁情况及对应的线程详情，从而可以帮助排查判断是否存在线程泄露

**Comment by hengyunabc** [comment]
这个不好做，因为纯是 new  Thread的话，应该很容易排查到。要是 ThreadPool的话，可能有各种各样的ThreadPool实现。
需要有具体的实现路径。
