### ISSUE TITLE
trace 方法总耗时不等于其调用的所有方法之和

### ISSUE THREAD

**Issue by shernupup** [alibaba/arthas#1721]
您好：
    在使用arthas分析线上问题的时候，发现trace某个方法时，总耗时不等于其调用的所有方法之和。
    具体问题描述如下文所示，还望社区大佬们帮忙看看，多谢！

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: xxx
* 目标进程的JVM版本: openjdk 1.8.0_202
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. trace 某方法查看耗时截图如下：
![image](https://user-images.githubusercontent.com/9914539/109753418-316c2980-7c1d-11eb-9ed4-ed4338b571da.png)

因为涉敏，我将部分全路径类名打了马赛克，但是不影响问题描述。
总耗时：1554ms  不等于其调用的所有方法之和。

### 期望的结果

方法总耗时等于所有调用的方法耗时之和。

### 实际运行的结果

方法总耗时不等于所有调用的方法耗时之和。

**Comment by hengyunabc** [comment]
https://arthas.aliyun.com/doc/trace#id10

**Comment by shernupup** [comment]
hi，这个参数的使用是否对arthas版本有要求？
是增加后，有报错：
![image](https://user-images.githubusercontent.com/9914539/109765151-697c6800-7c2f-11eb-9219-a37b5856426e.png)


看了下arthas日志：
![image](https://user-images.githubusercontent.com/9914539/109765093-56699800-7c2f-11eb-907e-c9c0d8774ab6.png)
