### ISSUE TITLE
k8s内使用对pid为1时不能使用

### ISSUE THREAD

**Issue by jjzhang789** [alibaba/arthas#1723]
在k8s集群中，pod内java进程pid为1，运行arthas失败。jdk版本1.8 arthas版本3.1.3 
![image](https://user-images.githubusercontent.com/25922125/109940256-d44fa100-7d0c-11eb-8f40-e27991f7aae9.png)

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/362
