### ISSUE TITLE
java命令是符号链接的时候，不设置JAVA_HOME，脚本无法通过过滤启动的java进程自己设置JAVA_HOME

### ISSUE THREAD

**Issue by muzinian** [alibaba/arthas#173]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: macOS high Sierra 10.13.6 
* Java version of target JVM: jdk_1.8.0_181
* Java version of JVM used to attach: jdk_1.8.0_181

### Steps to reproduce this issue
1. 不设置JAVA_HOME 且 java命令时符号连接
2. 使用java命令启动 jar 例如 java -jar zipkin.jar
3. 启动 arthas，报没有正确设置 JAVA_HOME

### Expected Result

What do you expected from the above steps？
可以正确启动arthas
### Actual Result

What actually happens?
由于java命令是一个符号连接而不是直接设置到PATH，如果没有在环境变量中设置JAVA_HOME，在脚本中通过过滤java进程设置JAVA_HOME有可能无法设置成功
If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by Hearen** [comment]
@muzinian Would you elaborate your **re-produce** part? 

How to achieve them step by step? 

It would be better if you could just paste the related **commands** to ease the re-producing job.

**Comment by muzinian** [comment]
@hengyunabc  你好，这个脚本是哪个分支/Tags下的呢，我在master分支下的没有看到呢

**Comment by hengyunabc** [comment]
@muzinian 直接保存为 as.sh 就可以了，还没有提交

**Comment by hengyunabc** [comment]
@muzinian is the new test `as.sh` ok?

**Comment by muzinian** [comment]
@hengyunabc  还是报错
这是执行 `bash -x as.sh`的输出
+ ARTHAS_SCRIPT_VERSION=3.0.4
+ ARTHAS_HOME=/Users/mxj/.arthas
+ ARTHAS_LIB_DIR=/Users/mxj/.arthas/lib
+ TMP_DIR=/tmp
+ ARTHAS_VERSION=
+ ARTHAS_REMOTE_VERSION_URL='http://search.maven.org/solrsearch/select?q=g:%22com.taobao.arthas%22+AND+a:%22arthas-packaging%22'
+ ARTHAS_REMOTE_DOWNLOAD_URL='http://search.maven.org/classic/remotecontent?filepath=com/taobao/arthas/arthas-packaging'
+ SO_TIMEOUT=5
+ DEFAULT_TARGET_IP=127.0.0.1
+ DEFAULT_TELNET_PORT=3658
+ DEFAULT_HTTP_PORT=8563
+ JVM_OPTS=
+ BATCH_MODE=false
+ ATTACH_ONLY=false
+ BATCH_SCRIPT=
+ ARTHAS_OPTS=-Djava.awt.headless=true
+ OS_TYPE=
+ case "$(uname -s)" in
++ uname -s
+ OS_TYPE=Mac
++ command -v curl
+ '[' -x /usr/bin/curl ']'
++ command -v grep
+ '[' -x /usr/bin/grep ']'
++ command -v awk
+ '[' -x /usr/bin/awk ']'
++ command -v telnet
+ '[' -x /usr/local/bin/telnet ']'
++ command -v unzip
+ '[' -x /usr/bin/unzip ']'
+ main
+ echo 'Arthas script version: 3.0.4'
Arthas script version: 3.0.4
+ check_permission
+ '[' '!' -w /Users/mxj ']'
+ reset_for_env
+ mkdir -p /Users/mxj/.arthas/lib
+ '[' -z '' ']'
+ JAVA_HOME=/opt/taobao/java
+ '[' '!' -d /opt/taobao/java ']'
+ JAVA_HOME_CANDIDATES=($(ps aux | grep java | grep -v 'grep java' | awk '{print $11}' | sed -n 's/\/bin\/java$//p'))
++ ps aux
++ grep java
++ grep -v 'grep java'
++ awk '{print $11}'
++ sed -n 's/\/bin\/java$//p'
+ for JAVA_HOME_TEMP in '${JAVA_HOME_CANDIDATES[@]}'
+ '[' -f /usr/lib/tools.jar ']'
+ local JAVA_VERSION
+ local 'IFS=
'
++ /opt/taobao/java/bin/java -version
++ tr '\r' '\n'
+ local 'lines=as2.sh: line 205: /opt/taobao/java/bin/java: No such file or directory'
+ for line in '$lines'
+ [[ -z '' ]]
+ [[ as2.sh: line 205: /opt/taobao/java/bin/java: No such file or directory = *\v\e\r\s\i\o\n\ \"* ]]
+ [[ '' -lt 9 ]]
+ '[' '!' -f /opt/taobao/java/lib/tools.jar ']'
+ exit_on_err 1 '/opt/taobao/java/lib/tools.jar does not exist, arthas could not be launched!'
+ [[ ! -z /opt/taobao/java/lib/tools.jar does not exist, arthas could not be launched! ]]
+ echo '/opt/taobao/java/lib/tools.jar does not exist, arthas could not be launched!'
/opt/taobao/java/lib/tools.jar does not exist, arthas could not be launched!
+ exit 1

**Comment by hengyunabc** [comment]
@muzinian 旧版本的 `as.sh` ， 执行 `bash -x as.sh` 结果是什么呢？

旧版本的没有走 `/opt/taobao/java` 的逻辑？

**Comment by hengyunabc** [comment]
@muzinian 提供了一个commit fca9a6e ，支持read link。但是即使是这样，你跑起来应该还是会出错。

因为你启动的命令是 `java xxx` ，这样子是没有办法找到 JAVA_HOME的。 

实际上更多人的需求是从 `type -p java` 里读取到JAVA_HOME 。

**Comment by muzinian** [comment]
@hengyunabc  不好意思才看到，这是旧版不包含解决符号链接的as.sh输出日志
```
+ ARTHAS_SCRIPT_VERSION=3.0.4
+ ARTHAS_HOME=/Users/mxj/.arthas
+ ARTHAS_LIB_DIR=/Users/mxj/.arthas/lib
+ TMP_DIR=/tmp
+ ARTHAS_VERSION=
+ ARTHAS_REMOTE_VERSION_URL='http://search.maven.org/solrsearch/select?q=g:%22com.taobao.arthas%22+AND+a:%22arthas-packaging%22'
+ ARTHAS_REMOTE_DOWNLOAD_URL='http://search.maven.org/classic/remotecontent?filepath=com/taobao/arthas/arthas-packaging'
+ SO_TIMEOUT=5
+ DEFAULT_TARGET_IP=127.0.0.1
+ DEFAULT_TELNET_PORT=3658
+ DEFAULT_HTTP_PORT=8563
+ JVM_OPTS=
+ BATCH_MODE=false
+ ATTACH_ONLY=false
+ BATCH_SCRIPT=
+ ARTHAS_OPTS=-Djava.awt.headless=true
+ main
+ echo 'Arthas script version: 3.0.4'
Arthas script version: 3.0.4
+ check_permission
+ '[' '!' -w /Users/mxj ']'
+ reset_for_env
+ mkdir -p /Users/mxj/.arthas/lib
+ '[' -z ']'
+ JAVA_HOME=/opt/taobao/java
+ '[' '!' -d /opt/taobao/java ']'
+ JAVA_HOME_CANDIDATES=($(ps aux | grep java | grep -v 'grep java' | awk '{print $11}' | sed -n 's/\/bin\/java$//p'))
++ ps aux
++ grep java
++ grep -v 'grep java'
++ awk '{print $11}'
++ sed -n 's/\/bin\/java$//p'
+ for JAVA_HOME_TEMP in '${JAVA_HOME_CANDIDATES[@]}'
+ '[' -f /usr/lib/tools.jar ']'
++ /opt/taobao/java/bin/java -version
++ awk -F '"' '$2>"1.5"{print $2}'
+ local JAVA_VERSION_STR=
+ [[ ! -x /opt/taobao/java ]]
+ exit_on_err 1 'illegal ENV, please set $JAVA_HOME to JDK6+'
+ [[ ! -z illegal ENV, please set $JAVA_HOME to JDK6+ ]]
+ echo 'illegal ENV, please set $JAVA_HOME to JDK6+'
illegal ENV, please set $JAVA_HOME to JDK6+
+ exit 1
```
我电脑上执行`type -p java`的结果和执行`java xxx`时`as.sh`获取的java路径是一致的，都是`/usr/bin/java`，这是我下载的最新的`as.sh`执行`bash -x as.sh`的结果
```
+ ARTHAS_SCRIPT_VERSION=3.0.4
+ ARTHAS_HOME=/Users/mxj/.arthas
+ ARTHAS_LIB_DIR=/Users/mxj/.arthas/lib
+ TMP_DIR=/tmp
+ ARTHAS_VERSION=
+ ARTHAS_REMOTE_VERSION_URL='http://search.maven.org/solrsearch/select?q=g:%22com.taobao.arthas%22+AND+a:%22arthas-packaging%22'
+ ARTHAS_REMOTE_DOWNLOAD_URL='http://search.maven.org/classic/remotecontent?filepath=com/taobao/arthas/arthas-packaging'
+ SO_TIMEOUT=5
+ DEFAULT_TARGET_IP=127.0.0.1
+ DEFAULT_TELNET_PORT=3658
+ DEFAULT_HTTP_PORT=8563
+ JVM_OPTS=
+ BATCH_MODE=false
+ ATTACH_ONLY=false
+ BATCH_SCRIPT=
+ ARTHAS_OPTS=-Djava.awt.headless=true
+ OS_TYPE=
+ case "$(uname -s)" in
++ uname -s
+ OS_TYPE=Mac
++ command -v curl
+ '[' -x /usr/bin/curl ']'
++ command -v grep
+ '[' -x /usr/bin/grep ']'
++ command -v awk
+ '[' -x /usr/bin/awk ']'
++ command -v telnet
+ '[' -x /usr/local/bin/telnet ']'
++ command -v unzip
+ '[' -x /usr/bin/unzip ']'
+ main
+ echo 'Arthas script version: 3.0.4'
Arthas script version: 3.0.4
+ check_permission
+ '[' '!' -w /Users/mxj ']'
+ reset_for_env
+ mkdir -p /Users/mxj/.arthas/lib
+ '[' -z '' ']'
+ '[' -d /opt/taobao/java ']'
+ '[' -z '' ']'
+++ type -p java
++ rreadlink /usr/bin/java
++ target=/usr/bin/java
++ fname=
++ targetDir=
++ CDPATH=
++ '[' -n '' ']'
++ :
++ '[' -L /usr/bin/java ']'
+++ command dirname -- /usr/bin/java
+++ dirname -- /usr/bin/java
++ command cd /usr/bin
++ cd /usr/bin
+++ command basename -- /usr/bin/java
+++ basename -- /usr/bin/java
++ fname=java
++ '[' java = / ']'
++ '[' -L java ']'
+++ command ls -l java
+++ ls -l java
++ target='lrwxr-xr-x  1 root  wheel  74  8 29 10:27 java -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java'
++ target=/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
++ continue
++ :
++ '[' -L /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java ']'
++ '[' -e /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java ']'
+++ command dirname -- /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
+++ dirname -- /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
++ command cd /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands
++ cd /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands
+++ command basename -- /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
+++ basename -- /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
++ fname=java
++ '[' java = / ']'
++ '[' -L java ']'
++ break
+++ command pwd -P
+++ pwd -P
++ targetDir=/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands
++ '[' java = . ']'
++ '[' java = .. ']'
++ command printf '%s\n' /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java
++ printf '%s\n' /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java
+ local JAVA_COMMAND_PATH=/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java
++ echo /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java
++ sed -n 's/\/bin\/java$//p'
+ JAVA_HOME=
+ '[' '!' -d '' ']'
+ JAVA_HOME_CANDIDATES=($(ps aux | grep java | grep -v 'grep java' | awk '{print $11}' | sed -n 's/\/bin\/java$//p'))
++ ps aux
++ grep java
++ grep -v 'grep java'
++ awk '{print $11}'
++ sed -n 's/\/bin\/java$//p'
+ for JAVA_HOME_TEMP in '${JAVA_HOME_CANDIDATES[@]}'
+ '[' -f /usr/lib/tools.jar ']'
+ '[' -z '' ']'
+ exit_on_err 1 'Can not find JAVA_HOME, please set $JAVA_HOME bash env first.'
+ [[ ! -z Can not find JAVA_HOME, please set $JAVA_HOME bash env first. ]]
+ echo 'Can not find JAVA_HOME, please set $JAVA_HOME bash env first.'
Can not find JAVA_HOME, please set $JAVA_HOME bash env first.
+ exit 1
```
日志里面显示最终设置的路径是`JAVA_COMMAND_PATH=/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java`然后通过`sed -n 's/\/bin\/java$//p'`截取了路径是截取不到的。不过，通过这个[链接](https://stackoverflow.com/questions/18144660/what-is-path-of-jdk-on-mac)应该mac下可以通过`/usr/libexec/java_home`这个命令去到正确的`JAVA_HOME`，不知道这样可否解决问题，不过这个问题其实只要正确设置了JAVA_HOME就可以解决，从已启动的应用中获取JAVA的路径只是兜底方案

**Comment by hengyunabc** [comment]
@muzinian `as.sh`增加了 java_home 的支持。
