### ISSUE TITLE
jdk6 不支持 heapdump 命令/使用heapdump导出时heap dump error

### ISSUE THREAD

**Issue by lxy2732532** [alibaba/arthas#1730]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.4.8
* Arthas 版本: 3.4.8
* 操作系统版本: win10企业版
* 目标进程的JVM版本: 1.6.0_45
* 执行`arthas-boot`的版本: 1.6.0_45或jdk1.8.0_152

### 重现问题的步骤

使用案例运行时，输入heapdump  E:/1.hprof异常

### 实际运行的结果

Dumping heap to /1.hprof ...
heap dump error: java.lang.management.ManagementFactory.getPlatformMXBean(Ljava/lang/Class;)Ljava/lang/management/PlatformManagedObject;

但是使用jmap时导出正常

将目标进程的JVM更换为1.8后导出无异常，但是显然无法解决生产情况下的问题

**Comment by hengyunabc** [comment]
jdk6 本身没有这个 java mbean，所以不支持。
