### ISSUE TITLE
dashboard中memory的direct项突然不见了

### ISSUE THREAD

**Issue by kimnwuchong** [alibaba/arthas#1733]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.6
* Arthas 版本: xxx
* 操作系统版本: linux
* 目标进程的JVM版本: jdk-10

### 重现问题的步骤

执行java -jar arthas-boot.jar
进入dashboard
memory 栏显示如下

### 期望的结果
![image](https://user-images.githubusercontent.com/72748129/110786929-b43d5600-82a7-11eb-8e2f-1b0d61846c2e.png)

### 实际运行的结果
![image](https://user-images.githubusercontent.com/72748129/110786882-9ff95900-82a7-11eb-835a-c768bd68dbad.png)

```
把异常信息贴到这里
```

**Comment by kylixs** [comment]
mapped 的上一行换行，向下挤了一行，mapped下面的direct没显示出来。
解决办法： 拉大命令窗口，增加宽度和高度

**Comment by kimnwuchong** [comment]
> mapped 的上一行换行，向下挤了一行，mapped下面的direct没显示出来。
> 解决办法： 拉大命令窗口，增加宽度和高度

关键是里面这个窗口列没法调整，窗口怎么改都没用

**Comment by kylixs** [comment]
> 关键是里面这个窗口列没法调整，窗口怎么改都没用

java -jar arthas-boot.jar 启动时使用的是arthas-client带的Telnet client，没法自适应窗口变化。请使用操作系统的telnet客户端连接，如telnet localhost 3658

**Comment by kimnwuchong** [comment]
> > 关键是里面这个窗口列没法调整，窗口怎么改都没用
> 
> java -jar arthas-boot.jar 启动时使用的是arthas-client带的Telnet client，没法自适应窗口变化。请使用操作系统的telnet客户端连接，如telnet localhost 3658

多谢指导，确实是窗口的问题
