### ISSUE TITLE
启动arthas并attach到机器主进程后，访问服务的接口，cpu猛增且持续较高，服务崩溃挂掉。

### ISSUE THREAD

**Issue by huangjiamei** [alibaba/arthas#1734]
1、4c8G的机器，启动arthas并attach到该机器的主进程；
![image](https://user-images.githubusercontent.com/14937535/110800567-4567f900-82b7-11eb-9846-68e0d112064e.png)
2、启动arthas时，cpu接近100%，后续降到50%左右；
3、连续访问某接口，cpu持续50%，访问几次后服务器崩溃，挂了（p.s. 不使用arthas时正常情况下访问接口未出现过问题）。

**Comment by hengyunabc** [comment]
attach之后，有没有执行过命令？

试下下载全量包，解压后，把`arthas.properties`里的这个配置注释掉，再执行as.sh启动arthas。

```
#arthas.enhanceLoaders=java.lang.ClassLoader
```

**Comment by huangjiamei** [comment]
> attach之后，有没有执行过命令？
> 
> 试下下载全量包，解压后，把`arthas.properties`里的这个配置注释掉，再执行as.sh启动arthas。
> 
> ```
> #arthas.enhanceLoaders=java.lang.ClassLoader
> ```

刚用这个方法试了以下，attach之后，若不执行命令，服务不会挂；但是执行trace命令后，访问一次接口服务就挂了，这是什么原因呢？

**Comment by huangjiamei** [comment]
arthas 3.5.0/3.2.0/3.1.8的版本我都试过了，执行一次trace命令，服务就挂一次。求大神指点，主要就是想用trace方法，这样没法用呀。

**Comment by huangjiamei** [comment]
> 1. 检查有没有其它的java agent
> 2. jvm挂掉之后，会生成一个err log，分析下里面的内容
> 3. 检查下jdk版本，试下新一点的版本，比如jdk8最新版本

1. 没有其他java agent
2. err log路径是在哪儿呀
3. 我们的jdk是1.8.2
4. 刚我又试了一下，可以trace几次，然后又挂了

**Comment by hengyunabc** [comment]
可以用这个参数显式设置： `-XX:ErrorFile=/path/hs_error%p.log`

**Comment by huangjiamei** [comment]
> 可以用这个参数显式设置： `-XX:ErrorFile=/path/hs_error%p.log`

这是日志里的报错信息
![image](https://user-images.githubusercontent.com/14937535/110903094-dbe0fc80-8341-11eb-957a-4122497ac0f1.png)

**Comment by kylixs** [comment]
可以提供一个可重新此问题的demo吗？
hs_error log 最前面的一段有crash的信息，请发出来看一下

**Comment by huangjiamei** [comment]
> 可以提供一个可重新此问题的demo吗？
> hs_error log 最前面的一段有crash的信息，请发出来看一下

这段吗
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7279ff0f48, pid=143010, tid=140129658177280
#
# JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00007f7279ff0f48
#
# Core dump written.

**Comment by kylixs** [comment]
后面还有一段是标记出现错误的线程调用栈，这个很关键，大概知道是哪里发生的错误

**Comment by huangjiamei** [comment]
> 可以提供一个可重新此问题的demo吗？
> hs_error log 最前面的一段有crash的信息，请发出来看一下

这段吗
 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f7279ff0f48, pid=143010, tid=140129658177280

 JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  0x00007f7279ff0f48

 Core dump written.

**Comment by huangjiamei** [comment]
> 后面还有一段是标记出现错误的线程调用栈，这个很关键，大概知道是哪里发生的错误

Java Threads: ( => current thread )
  0x00007f6d94008800 JavaThread "http-nio-8001-exec-10" daemon [_thread_blocked, id=145062, stack(0x00007f72792e8000,0x00007f72793e9000)]
  0x00007f6d88011000 JavaThread "http-nio-8001-exec-9" daemon [_thread_blocked, id=145048, stack(0x00007f72793e9000,0x00007f72794ea000)]
  0x00007f6e50002000 JavaThread "Keep-Alive-Timer" daemon [_thread_blocked, id=145045, stack(0x00007f72794ea000,0x00007f72795eb000)]
  0x00007f6d94006800 JavaThread "http-nio-8001-exec-8" daemon [_thread_blocked, id=145030, stack(0x00007f72795eb000,0x00007f72796ec000)]
  0x00007f6d8800f000 JavaThread "http-nio-8001-exec-7" daemon [_thread_blocked, id=145028, stack(0x00007f72796ec000,0x00007f72797ed000)]
  0x00007f6d94005000 JavaThread "http-nio-8001-exec-6" daemon [_thread_blocked, id=145025, stack(0x00007f72797ed000,0x00007f72798ee000)]
  0x00007f6d8800d800 JavaThread "http-nio-8001-exec-5" daemon [_thread_blocked, id=145010, stack(0x00007f72798ee000,0x00007f72799ef000)]
  0x00007f6d94003800 JavaThread "http-nio-8001-exec-4" daemon [_thread_blocked, id=145007, stack(0x00007f72799ef000,0x00007f7279af0000)]
  0x00007f6d8800d000 JavaThread "http-nio-8001-exec-3" daemon [_thread_blocked, id=144990, stack(0x00007f728a4e5000,0x00007f728a5e6000)]
  0x00007f6d94002800 JavaThread "http-nio-8001-exec-2" daemon [_thread_blocked, id=144953, stack(0x00007f72a17c6000,0x00007f72a18c7000)]
  0x00007f6d6c4ca800 JavaThread "Jst-LogDaemon-Thread" daemon [_thread_blocked, id=144748, stack(0x00007f7279cf0000,0x00007f7279df1000)]
  0x00007f6d6c484800 JavaThread "Jst-AsyncAppender-Thread-BizLog" daemon [_thread_blocked, id=144745, stack(0x00007f7279ff1000,0x00007f727a0f2000)]
  0x00007f6d6c452000 JavaThread "Jst-TPCache-Thread-Timer" daemon [_thread_blocked, id=144744, stack(0x00007f727a0f2000,0x00007f727a1f3000)]
  0x00007f6d6c41d800 JavaThread "Jst-AsyncAppender-Thread-cglog" daemon [_thread_blocked, id=144743, stack(0x00007f727a1f3000,0x00007f727a2f4000)]
  0x00007f6d6c406000 JavaThread "Jst-CGConfSender-Thread" daemon [_thread_blocked, id=144742, stack(0x00007f727a2f4000,0x00007f727a3f5000)]
  0x00007f6d6c3f0000 JavaThread "Jst-Heartbeater-Thread" daemon [_thread_blocked, id=144741, stack(0x00007f727a3f5000,0x00007f727a4f6000)]
  0x00007f6d6c3d0000 JavaThread "Jst-AsyncReceiver-Thread" daemon [_thread_in_native, id=144740, stack(0x00007f727a4f6000,0x00007f727a5f7000)]
  0x00007f6d6c373000 JavaThread "SystemClock" daemon [_thread_blocked, id=144739, stack(0x00007f727a5f7000,0x00007f727a6f8000)]
=>0x00007f6d88008000 JavaThread "http-nio-8001-exec-1" daemon [_thread_in_Java, id=144737, stack(0x00007f727a6f8000,0x00007f727a7f9000)]
  0x00007f6f6c001000 JavaThread "elasticsearch[Abigail Brand][generic][T#2]" daemon [_thread_blocked, id=144673, stack(0x00007f72b0ee0000,0x00007f72b0fe1000)]
  0x00007f70ec0b8000 JavaThread "arthas-command-execute" daemon [_thread_blocked, id=144671, stack(0x00007f72a34e1000,0x00007f72a35e2000)]
  0x00007f6d84009000 JavaThread "arthas-NettyHttpTelnetBootstrap-3-2" daemon [_thread_in_native, id=144656, stack(0x00007f72a1ac9000,0x00007f72a1bca000)]
  0x00007f70ee7a6000 JavaThread "arthas-UserStat" daemon [_thread_blocked, id=144650, stack(0x00007f727b9fa000,0x00007f727bafb000)]
  0x00007f70ee7a0000 JavaThread "arthas-session-manager" daemon [_thread_blocked, id=144649, stack(0x00007f727bafb000,0x00007f727bbfc000)]
  0x00007f70ee79d800 JavaThread "arthas-shell-server" daemon [_thread_blocked, id=144648, stack(0x00007f727bbfc000,0x00007f727bcfd000)]
  0x00007f70ee79c800 JavaThread "arthas-NettyWebsocketTtyBootstrap-4-2" daemon [_thread_in_native, id=144647, stack(0x00007f727bcfd000,0x00007f727bdfe000)]
  0x00007f70edb18800 JavaThread "arthas-NettyWebsocketTtyBootstrap-4-1" daemon [_thread_in_native, id=144646, stack(0x00007f727bdfe000,0x00007f727beff000)]
  0x00007f70edb16000 JavaThread "arthas-NettyHttpTelnetBootstrap-3-1" daemon [_thread_in_native, id=144645, stack(0x00007f727beff000,0x00007f727c000000)]
  0x00007f70ec056000 JavaThread "arthas-timer" daemon [_thread_blocked, id=144641, stack(0x00007f72b18d8000,0x00007f72b19d9000)]
  0x00007f71e0001000 JavaThread "Attach Listener" daemon [_thread_blocked, id=144638, stack(0x00007f72b19d9000,0x00007f72b1ada000)]
......

**Comment by kylixs** [comment]
参考一下这个，找出崩溃时的线程调用栈：
![image](https://user-images.githubusercontent.com/5483385/110905284-33cd3280-8345-11eb-9389-ffa6f88d5467.png)
https://www.jianshu.com/p/bc98f1b4e221

**Comment by huangjiamei** [comment]
> 参考一下这个，找出崩溃时的线程调用栈：
> ![image](https://user-images.githubusercontent.com/5483385/110905284-33cd3280-8345-11eb-9389-ffa6f88d5467.png)
![image](https://user-images.githubusercontent.com/14937535/110906183-8f4bf000-8346-11eb-9789-41cc971b728b.png)

**Comment by huangjiamei** [comment]
> 参考一下这个，找出崩溃时的线程调用栈：
> ![image](https://user-images.githubusercontent.com/5483385/110905284-33cd3280-8345-11eb-9389-ffa6f88d5467.png)
> https://www.jianshu.com/p/bc98f1b4e221

![image](https://user-images.githubusercontent.com/14937535/110906328-c3271580-8346-11eb-83b0-1d5e5f8fca88.png)

![image](https://user-images.githubusercontent.com/14937535/110906256-ac80be80-8346-11eb-9738-64d2d2df925c.png)

**Comment by huangjiamei** [comment]
栈的调用记录只有这一条

**Comment by kylixs** [comment]
> 栈的调用记录只有这一条
> 我查阅了前几次的报错记录，有的是这样
> ![image](https://user-images.githubusercontent.com/14937535/110909957-aa6d2e80-834b-11eb-87ae-664b03654780.png)

没看到明显的问题，看能不能提供一个重现问题的demo，可以用调试方式启动Java进程跑一下，比较容易找到问题

**Comment by huangjiamei** [comment]
这个报错呢？
![image](https://user-images.githubusercontent.com/14937535/110934015-6fc5bf00-8368-11eb-8739-f4b4474ce936.png)

**Comment by huangjiamei** [comment]
已解决：服务器jdk版本是1.8.0_20；需更改成1.8.0_60

**Comment by kuailelijuan** [comment]
服务器jdk版本是1.8.0_20 为什么 需更改成1.8.0_60？1.8.0_20 为什么会崩溃呢？

**Comment by xiezhaokun** [comment]
> 完整的hs_err_log文件还在吗？
