### ISSUE TITLE
当Object输出时，可能会抛出异常，打印 ERROR DATA!!! exception message:  null

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1740]
缺少具体的信息和异常栈，不好查问题。

**Comment by 6westboy9** [comment]
我也遇到了类似的问题，使用watch命令时，返回结果也是这样，这个不是业务异常吧
![image](https://user-images.githubusercontent.com/39526241/218919097-adb470c2-052f-489e-a836-f6805ea3ae39.png)
