### ISSUE TITLE
8080端口被其他应用占用 如何更改arthas-tunnel-server-3.5.0-fatjar.jar的8080端口

### ISSUE THREAD

**Issue by Mars626** [alibaba/arthas#1747]
arthas-tunnel-server-3.5.0-fatjar.jar

**Comment by Mars626** [comment]
arthas tunnel server的web端口是`8080`  请问下这个端口是在哪个配置文件中配置的

**Comment by hengyunabc** [comment]
看spring boot本身的文档，可以配置在spring boot的 application.properties，也可以 `-D`参数配置。
