### ISSUE TITLE
在线教程文档命令tab切换内容不变

### ISSUE THREAD

**Issue by fwk1010** [alibaba/arthas#1752]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

直接访问 https://arthas.aliyun.com/doc/arthas-tutorials.html?language=cn&id=command-cls

### 期望的结果
出现对应命令的详细说明

### 实际运行的结果
还是停留在介绍说明

```
把异常信息贴到这里
```
![image](https://user-images.githubusercontent.com/10340097/112798182-2206c180-909f-11eb-8d84-ea4e604d1970.png)

**Comment by hengyunabc** [comment]
没理解`tab切换内容`是指什么。 是指打开第二个 terminal 没反应？这个可能是katacoda本身比较卡的原因，可能要等一会。

**Comment by fwk1010** [comment]
不好意思，可能描述有点简单。是这些下拉选择，跳转的页面内容不正确。@hengyunabc
![image](https://user-images.githubusercontent.com/10340097/112804192-b0327600-90a6-11eb-8c9b-50071d7b7a58.png)

**Comment by hengyunabc** [comment]
@fwk1010 不好意思，还是没有理解到😂。可以再详细点一步步说明不？

**Comment by fwk1010** [comment]
@hengyunabc 是我想使用这个在线教程文档看下有哪些命令，具体怎么使用和效果。但是发现点击顶部不同的tab，图中红框显示的内容都是不变的。
![image](https://user-images.githubusercontent.com/10340097/112818427-196db580-90b6-11eb-8a61-2a7db00dcc8c.png)

**Comment by hengyunabc** [comment]
@fwk1010 因为开始的文案内容差不多😂，点下一页，就会变了。
