### ISSUE TITLE
Enhancer的方法匹配和类匹配参数定义为string，

### ISSUE THREAD

**Issue by tuhanbao** [alibaba/arthas#1753]
Enhancer的isIgnore方法匹配method的时候传的是方法名，如果我想重写一个Method的Matcher，根据method的注解等其他进行过滤就很难做到，需要修改大量的类。建议class和method的Matcher接口类传参分别定义为Class和Method对象，然后实现一个根据类名或method名过滤的模板类，兼容以前传string的实现。

**Comment by hengyunabc** [comment]
取得 `java.lang.reflect.Method` 的代价是很昂贵的，并且还可能引起额外的类加载。
