### ISSUE TITLE
profiler start 执行报错：can not find libasyncProfiler so, please check the arthas directory.

### ISSUE THREAD

**Issue by dmego** [alibaba/arthas#1756]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.0
* Arthas 版本: 3.5.0
* 操作系统版本: SUSE Linux 12.3
* 目标进程的JVM版本: 1.8.0_172
* 执行`arthas-boot`的版本: 3.5.0

执行 profiler start 命令报错：`can not find libasyncProfiler so, please check the arthas directory`.  检查 `async-profiler` 目录下有`.so`文件。

**Comment by dmego** [comment]
找到原因了

**Comment by zhanglijun1217** [comment]
遇到一样的问题 原因是什么呢 @dmego

**Comment by dmego** [comment]
@zhanglijun1217 我的是因为 `async-profiler` 目录名不对，你可以检查一下看看

**Comment by zhanglijun1217** [comment]
刚接触 要在~/.arthas目录下有async-profiler目录？还是要安装别的东西

**Comment by hengyunabc** [comment]
@zhanglijun1217 正常应该在这个目录下面： `~/.arthas/lib/3.5.2/arthas/async-profiler/` 。

@dmego 可以补充下细节不？具体目录名不对的情况。

**Comment by zhanglijun1217** [comment]
> @zhanglijun1217 正常应该在这个目录下面： `~/.arthas/lib/3.5.2/arthas/async-profiler/` 。
> 
> @dmego 可以补充下细节不？具体目录名不对的情况。

OK 我看了都没有lib目录 只有history的历史命令文件  我问下安装arthas插件的运维吧 感谢大佬~
