### ISSUE TITLE
去掉默认配置项 arthas.enhanceLoaders=java.lang.ClassLoader ，避免attach后导致系统负载飙升

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1757]
参考： https://github.com/alibaba/arthas/issues/44#issuecomment-815437399 

有遇到classloader加载问题的应用，可以自行下载后修改配置启用。

**Comment by DrizzleRisk** [comment]
支持命令行启动的方式修改这个配置项吗？
