### ISSUE TITLE
arthas可以trace到接口的实现类吗

### ISSUE THREAD

**Issue by huangjiamei** [alibaba/arthas#1760]

**Comment by hengyunabc** [comment]
当然可以。。把在线教程跑一遍： https://arthas.aliyun.com/doc/trace

**Comment by huangjiamei** [comment]
> 当然可以。。把在线教程跑一遍： https://arthas.aliyun.com/doc/trace

可能我说得不够明确，我是在用多层trace的时候发现吗没有trace到接口的实现类里面的函数。

**Comment by hengyunabc** [comment]
> > 当然可以。。把在线教程跑一遍： https://arthas.aliyun.com/doc/trace
> 
> 可能我说得不够明确，我是在用多层trace的时候发现吗没有trace到接口的实现类里面的函数。

最好给出可能运行的具体demo。
