### ISSUE TITLE
tunnel server 部署集群 ，Agent和Web Console如何进行消息流转

### ISSUE THREAD

**Issue by XiaoWeiKIN** [alibaba/arthas#1761]
长连接不在一个服务器上怎么处理

**Comment by hengyunabc** [comment]
前端用 nginx转发下，然后ngnix设置 ip 保持转发到同一个server。 这个配置略复杂，有空我做一个实例demo。

**Comment by kakayu** [comment]
> 前端用 nginx转发下，然后ngnix设置 ip 保持转发到同一个server。 这个配置略复杂，有空我做一个实例demo。

大佬，请问这个demo有了么？

**Comment by zqw961025** [comment]
各位大佬，有没有demo可以参考。

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/2340#issuecomment-1314728733
