### ISSUE TITLE
arthas-spring-boot-starter依赖启动的应用stop后无法再重连

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/arthas#1763]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.0
* Arthas 版本:  3.5.0
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 依赖arthas-spring-boot-starter
2. 在tenner-server控制台里面连接
3. 在输入stop命令退出
4. 再连接就出现黑框框，没有直接attach进去了

### 期望的结果

能再次进入使用arthas界面

请问这种情况怎么解决？除非屏蔽stop命令，否则无法再次使用，只能重启应用才行。

**Comment by hengyunabc** [comment]
目前是stop之后，就不能再连了。后面考虑在 starter情况下，禁用掉stop命令。

**Comment by hengyunabc** [comment]
3.5.2 的版本里， starter启动的 arthas已经默认禁止 stop命令了。

**Comment by LockiJiang** [comment]
> 
> 
> 3.5.2 的版本里， starter启动的 arthas已经默认禁止 stop命令了。

刚才使用，默认配置下，stop仍旧被停止了

**Comment by hengyunabc** [comment]
> > 3.5.2 的版本里， starter启动的 arthas已经默认禁止 stop命令了。
> 
> 刚才使用，默认配置下，stop仍旧被停止了

仔细检查版本，实测是工作的：

![image](https://user-images.githubusercontent.com/1683936/124858741-36812100-dfe1-11eb-8c1c-5cd6f8e275d8.png)

**Comment by LockiJiang** [comment]
> 
> 
> > > 3.5.2 的版本里， starter启动的 arthas已经默认禁止 stop命令了。
> > 
> > 
> > 刚才使用，默认配置下，stop仍旧被停止了
> 
> 仔细检查版本，实测是工作的：
> 

感谢回复！
最终测试结果如下
## 一、application.yml不做任何配置，全部以arthas默认配置运行，stop未被禁止
![图片](https://user-images.githubusercontent.com/16129287/124859907-4f8ad180-dfe3-11eb-9f9f-007551891848.png)

## 二、application.yml中配置disabledCommands，stop命令被阻止
![图片](https://user-images.githubusercontent.com/16129287/124860368-1d2da400-dfe4-11eb-9b6d-76e963d9436b.png)

## 综上，arthas默认配置不生效，原因是ArthasProperties中配置信息未放进mapWithPrefix
![图片](https://user-images.githubusercontent.com/16129287/124860459-451d0780-dfe4-11eb-8578-ba82cedc25e7.png)

![图片](https://user-images.githubusercontent.com/16129287/124860720-be1c5f00-dfe4-11eb-87dc-346b93c3f7b3.png)

**Comment by hengyunabc** [comment]
@LockiJiang 谢谢测试，具体原因参考： https://github.com/alibaba/arthas/issues/1853
