### ISSUE TITLE
arthas command "jvm" can't show the right jvm version

### ISSUE THREAD

**Issue by zlzhang0122** [alibaba/arthas#1765]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: linux
* Java version of target JVM: 1.8.0.202
* Java version of JVM used to attach: 1.8.0.202

### Steps to reproduce this issue

1. install openjdk 1.8.0.232
2. use openjdk 1.8.0.202 start a process 1
3. use openjdk 1.8.0.232 start other process 2
4. start the arthas process on process 1
5. use jvm command to see the jvm version

### Expected Result

What do you expected from the above steps？
the jvm version should be 1.8.0.202

### Actual Result

What actually happens?
the jvm version shows 1.8.0.232

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by hengyunabc** [comment]
这个基本不可能。因为代码里直接调用的 System.getProperties() 来取的数据。可能arthas连接到是旧的进程上，先执行 stop，再重新attach。 另外，这个Arthas的版本太老了，最好用最新版。

**Comment by zlzhang0122** [comment]
@hengyunabc 
下图是我用jcmd显示的java版本，显示的是1.8.0.202：
![2021-04-14 09-50-09 的屏幕截图](https://user-images.githubusercontent.com/5321584/114666613-0b17ce80-9d31-11eb-8291-f62e3c405a6e.png)
下图是我用arthas显示的java版本，显示的是1.8.0.232：
![2021-04-14 09-50-35 的屏幕截图](https://user-images.githubusercontent.com/5321584/114666821-4c0fe300-9d31-11eb-9158-488bb3662e15.png)
或者说，jvm这个命令展示的不是进程的java版本，而是运行arthas的java版本？
但是我的JAVA_HOME指向的是1.8.0.202，默认应该用这个，这里显示的1.8.0.232是从哪里得到得呢？

**Comment by hengyunabc** [comment]
是连错进程了，连到之前已attach过的进程上了。 图里显示了 `pid: 167241` 。

**Comment by zlzhang0122** [comment]
@hengyunabc 好吧，但是我看也没报什么错，怎么突然连到别的进程了呢

**Comment by hengyunabc** [comment]
> @hengyunabc 好吧，但是我看也没报什么错，怎么突然连到别的进程了呢，这应该也属于bug吧

arthas本质上是在应用进程内开了一个 3658 端口。 以前的没关掉，新的attach上去就会 listen失败。然后 telnet 连接到的是以前的进程。

新版本脚本做了一些增强判断，有冲突的话会提示。
