### ISSUE TITLE
jad的一个小小的显示问题

### ISSUE THREAD

**Issue by ljh19971113** [alibaba/arthas#1767]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.0
* Arthas 版本: 3.5.0
* 操作系统版本: win10
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 1.8

### 重现问题的步骤
我在使用jad命令获取一个包内的所有类信息时候，出现如下显示
![image](https://user-images.githubusercontent.com/32218468/114667877-99d91b00-9d32-11eb-8695-eb4635811322.png)
因为发现这个显示和官方文档中的示例不太一致，于是对源码进行查看，发现可能是因为如下方法默认宽度为80，而我的类名太长导致
![image](https://user-images.githubusercontent.com/32218468/114668149-f6d4d100-9d32-11eb-98e3-ca22a4a0216f.png)
当我将这个方法修改为process.write(RenderUtil.render(table,200)).write("\n")，命令行界面的显示就和我的预期结果一致了，如下：
![image](https://user-images.githubusercontent.com/32218468/114668723-a27e2100-9d33-11eb-909d-eab53cc6d05f.png)

### 期望的结果

大佬能不能把这个方法宽度改成自适应的：）

### 备注
Found more than one class for: com.arthas.example.testapp.*, Please use jad -c <hashcode> com.arthas.example.testapp.*
这个信息在前后都打印了，感觉有点多余

**Comment by hengyunabc** [comment]
谢谢指出，下个版本修复。
