### ISSUE TITLE
怎么反编译匿名内部类

### ISSUE THREAD

**Issue by xu1009** [alibaba/arthas#1770]
- [ 1] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.4.6

使用sc 定位到匿名内部类 

 class-info        xxxxx$$Lambda$686/633530683
 code-source       file:/xxxxx.jar!/BOOT-INF/classes!/
 name              xxxxxx$$Lambda$686/633530683
 isInterface       false
 isAnnotation      false
 isEnum            false
 isAnonymousClass  false
 isArray           false
 isLocalClass      false
 isMemberClass     false
 isPrimitive       false
 isSynthetic       true
 simple-name       XXXXX$$Lambda$686/633530683
 modifier          final
 annotation
 interfaces        java.lang.Runnable
 super-class       +-java.lang.Object
 class-loader      +-org.springframework.boot.loader.LaunchedURLClassLoader@7829b776
                     +-sun.misc.Launcher$AppClassLoader@18b4aac2
                       +-sun.misc.Launcher$ExtClassLoader@7adf9f5f
 classLoaderHash   7829b776

再使用 反编译 命令时 

jad  xxxxx$$Lambda$686/633530683

jad: fail to decompile class: xxxx$$Lambda$686/633530683

这里不支持反编译匿名内部类吗

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/675
