### ISSUE TITLE
[Question] Why Cpu load value is negative number.

### ISSUE THREAD

**Issue by horizonzy** [alibaba/arthas#1774]
### 环境信息 

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.0
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: jdk 1.8
* 执行`arthas-boot`的版本: jdk 1.8

![](https://user-images.githubusercontent.com/22524871/115352824-60992300-a1ea-11eb-8c4c-14bafcc6bebb.png)

**Comment by hengyunabc** [comment]
可以稳定重现不？

**Comment by horizonzy** [comment]
不确定是否能重现，没有进行重启。这个zk线程是用kotlin进行初始化的，是不是会影响统计。
