### ISSUE TITLE
能否支持Root用户去attach其他用户的java进程？

### ISSUE THREAD

**Issue by horizonzy** [alibaba/arthas#1777]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

在root用户下，是能够看到其他用户的tmp文件的，但是无法attach。能不能支持只要有对应文件的访问权限，就能去attch。

**Comment by hengyunabc** [comment]
这个是jvm自身的机制，估计是不行的。
