### ISSUE TITLE
本地clone后启动arthas-boot 执行dashboard卡住

### ISSUE THREAD

**Issue by lailaihaochu** [alibaba/arthas#1780]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5
* Arthas 版本: 3.5
* 操作系统版本: win10
* 目标进程的JVM版本: jdk11
* 执行`arthas-boot`的版本: 3.5

### 重现问题的步骤

1. 本地clone arthas
2. maven build->maven install
3. 启动arthas-boot java程序->执行dashboard卡住了

### 期望的结果

期望可以正常运行

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
启动之后卡住图片
![image](https://user-images.githubusercontent.com/30614940/116038825-89169680-a69c-11eb-97ce-d7f65b68f9a1.png)

把异常信息贴到这里
没异常

**Comment by hengyunabc** [comment]
用 jstack 看下 执行 dashboard 的线程阻塞在哪里。

**Comment by lailaihaochu** [comment]
![image](https://user-images.githubusercontent.com/30614940/116198195-41f5d780-a768-11eb-8a33-5edc85339a51.png)
![image](https://user-images.githubusercontent.com/30614940/116198229-48844f00-a768-11eb-8380-d9e7a0acf462.png)
![image](https://user-images.githubusercontent.com/30614940/116198255-4f12c680-a768-11eb-948d-6d094ec4643f.png)
![image](https://user-images.githubusercontent.com/30614940/116198277-5639d480-a768-11eb-81fa-458676f953d2.png)
使用jstack查看后貌似没有阻塞的情况

**Comment by hengyunabc** [comment]
能不能稳定重现，或者给出重现的demo？ 可能是 ide启动，打了断点。

**Comment by lailaihaochu** [comment]
是idea启动的，如果使用下载下来的jar包启动并没有这个问题

**Comment by hengyunabc** [comment]
可能是 idea的 terminal 问题。试下用原生的 终端。

**Comment by lailaihaochu** [comment]
原生终端的话我这里本地不太好搞！目前jar包是ok暂时可以使用我再看看吧！谢谢hengyunabc 帮我分析和解决，我个人只是想了解源码才进行本地clone和debug跑，如果是使用的话down jar包是没问题的就ok了。
