### ISSUE TITLE
tt命令 得到的cost 巨大 代表什么含义

### ISSUE THREAD

**Issue by covered** [alibaba/arthas#1790]
* Arthas 3.5.0
* arthas-boot version: 3.5.0
* java 
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)

[arthas@4932]$ tt -i 8309
 INDEX         8309
 GMT-CREATE    2021-05-10 08:20:34
 COST(ms)      2.435956792151126E9
 OBJECT        0x2da67b59
 CLASS         com.sgck.model.Machine
 METHOD        getRemoteRTChannelList
 IS-RETURN     true
 IS-EXCEPTION  false
 RETURN-OBJ    null
Affect(row-cnt:1) cost in 1 ms.

请问 ：其中的COST 这么大的数值 代表什么意思？

**Comment by hengyunabc** [comment]
指这个？ `COST(ms) 2.435956792151126E9` 科学计数法。

**Comment by covered** [comment]
> 指这个？ `COST(ms) 2.435956792151126E9` 科学计数法。

科学计算法 没问题， 只是这个 cost  值这么大不正常吧。
