### ISSUE TITLE
web console 在部分浏览器中的效果有问题

### ISSUE THREAD

**Issue by GISwilson** [alibaba/arthas#1792]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.0
* Arthas 版本: 3.5.0
* 操作系统版本: Ubuntu 18.04
* 目标进程的JVM版本: JDK8
* 执行`arthas-boot`的版本: 3.5.0
*  chrome浏览器版本：最新版本： 90.0.4430.93（正式版本） （64 位）

### 重现问题的步骤

1. web console连接上某个agentId
2. 输入thread（为了模拟信息占满屏幕的情况），会默认展示线程相关信息，
3. 输入回车或Ctrl +C
4. 输入任何字符，在我的笔记本（windows）上光标会在最下方，但是在台式机（Ubuntu）上，会自动调到命令界面的最上方。导致体验很差，基本没法干活。详见如下gif：
 ![Peek 2021-05-11 11-53](https://user-images.githubusercontent.com/11484101/117755878-ac6e4380-b24f-11eb-9bb6-ffde3f9f50b1.gif)

### 期望的结果
能兼容浏览器的情况，修复该问题，或者说明如何配置浏览器才能正常不跳转到界面最上面。

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by GISwilson** [comment]
> 检查下是不是有装了 chrome插件引起的。试下把插件都禁用。
插件都禁用也是一样的效果。

**Comment by davidricardo1026** [comment]
我的也一样,我是linux系统,是不是和字体有关系.
使用的字体,有些系统没有,然后表现就很怪异

**Comment by davidricardo1026** [comment]
![image](https://user-images.githubusercontent.com/89175910/145189402-f76a572f-40fe-44dc-ba89-90a879320428.png)
就是这样,宽度和长度都有问题,和楼主的一模一样.
我的操作系统是manjaro
chrome是96.0.4664.45 (Official Build) (64-bit)
