### ISSUE TITLE
删掉过时的 shutdown 命令

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#1799]
stop 命令已经用过好久了。

**Comment by RLin2015New** [comment]
这里通过新定义一个废弃命令的标签实现怎么样~
粗略想法是，
1.新定义一个废弃命令的标签@DeprecatedCommand(“shutdown command is deprecated，please use stop command”)
2.指令注册记录时，标记一下哪些指令是废弃的，替代指令是什么
3.指令执行时，如果是废弃指令，则提示desc信息
4.指令废弃后1-2个版本可以做针对废弃代码做物理删除

**Comment by RLin2015New** [comment]
当然第二个方案是直接把shutdown 做物理删除（目前stop好像直接调的shutdown，那做一下代码迁移和相关检查）~

@hengyunabc 你觉得哪个方式更好

**Comment by hengyunabc** [comment]
@RLin2015New 不需要这么复杂，直接删掉就好了。 现在还没提交代码里，是因为可能影响别的pr，所以还没处理。

**Comment by RLin2015New** [comment]
> @RLin2015New 不需要这么复杂，直接删掉就好了。 现在还没提交代码里，是因为可能影响别的pr，所以还没处理。

哦哦~
