### ISSUE TITLE
window启动报错binary operator expected

### ISSUE THREAD

**Issue by fangdong116** [alibaba/arthas#180]
Arthas script version: 3.0.2
./as.sh: line 89: [: C:\Program: binary operator expected
./as.sh: line 92: [: C:\Program: binary operator expected
illegal ENV, please set $JAVA_HOME to JDK6+

bash -x as.sh 输出：
=================================================================
$ bash -x as.sh
+ ARTHAS_HOME=/c/Users/Administrator.XKZCNO/.arthas
+ ARTHAS_LIB_DIR=/c/Users/Administrator.XKZCNO/.arthas/lib
+ TMP_DIR=/tmp
+ ARTHAS_VERSION=
+ ARTHAS_SCRIPT_VERSION=3.0.2
+ ARTHAS_REMOTE_VERSION_URL='http://search.maven.org/solrsearch/select?q=g:%22co                                                                                                                m.taobao.arthas%22+AND+a:%22arthas-packaging%22'
+ ARTHAS_REMOTE_DOWNLOAD_URL='http://search.maven.org/classic/remotecontent?file                                                                                                                path=com/taobao/arthas/arthas-packaging'
+ SO_TIMEOUT=5
+ DEFAULT_TARGET_IP=127.0.0.1
+ DEFAULT_TELNET_PORT=3658
+ DEFAULT_HTTP_PORT=8563
+ JVM_OPTS=
+ BATCH_MODE=false
+ ATTACH_ONLY=false
+ BATCH_SCRIPT=
+ ARTHAS_OPTS=-Djava.awt.headless=true
+ main
+ echo 'Arthas script version: 3.0.2'
Arthas script version: 3.0.2
+ check_permission
+ '[' '!' -w /c/Users/Administrator.XKZCNO ']'
+ reset_for_env
+ mkdir -p /c/Users/Administrator.XKZCNO/.arthas/lib
+ '[' -z 'C:\Program' 'Files\Java\jdk1.8.0_77' ']'
as.sh: line 89: [: C:\Program: binary operator expected
+ '[' '!' -d 'C:\Program' 'Files\Java\jdk1.8.0_77' ']'
as.sh: line 92: [: C:\Program: binary operator expected
++ 'C:\Program' 'Files\Java\jdk1.8.0_77/bin/java' -version
++ awk -F '"' '$2>"1.5"{print $2}'
+ local JAVA_VERSION_STR=
+ [[ ! -x C:\Program Files\Java\jdk1.8.0_77 ]]
+ [[ -z '' ]]
+ exit_on_err 1 'illegal ENV, please set $JAVA_HOME to JDK6+'
+ [[ ! -z illegal ENV, please set $JAVA_HOME to JDK6+ ]]
+ echo 'illegal ENV, please set $JAVA_HOME to JDK6+'
illegal ENV, please set $JAVA_HOME to JDK6+
+ exit 1

**Comment by hengyunabc** [comment]
可能是空格的原因，尝试把 89行改为：

```bash
    # init ARTHAS' lib
    mkdir -p "${ARTHAS_LIB_DIR}" \
        || exit_on_err 1 "create ${ARTHAS_LIB_DIR} fail."

```

**Comment by hengyunabc** [comment]
#212

**Comment by hengyunabc** [comment]
目前 as.sh 已经兼容 git bash/MinGw/Cygwin 了，可以再测试下。 https://github.com/alibaba/arthas/blob/master/bin/as.sh
