### ISSUE TITLE
tomcat8.5.53 vmtool

### ISSUE THREAD

**Issue by anylys** [alibaba/arthas#1812]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.5.1
* Arthas 版本: 3.5.1
* 操作系统版本: windows10
* 目标进程的JVM版本: OpenJDK 1.8
* 执行`arthas-boot`的版本: xxx
* tomcat8.5.53

### 重现问题的步骤

 vmtool --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext                     
 

### 实际运行的结果

 vmtool error: E:\java\apache-tomcat-8.5.53\temp\ArthasJniLibrary5047835573419684488.tmp: %1 不是有效? Win32 应用程序?

```
 vmtool error: E:\java\apache-tomcat-8.5.53\temp\ArthasJniLibrary5047835573419684488.tmp: %1 不是有效? Win32 应用程序?
```

**Comment by hengyunabc** [comment]
具体cpu架构是什么样的？

可以重新启动应用，试下加上这个参数，显式指定 dll 路径： `--libPath  /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll`

**Comment by anylys** [comment]
> 具体cpu架构是什么样的？
> 
> 可以重新启动应用，试下加上这个参数，显式指定 dll 路径： `--libPath /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll`

(英特尔)Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz(2694 MHz 
系统是64位

**Comment by anylys** [comment]
> 具体cpu架构是什么样的？
> 
> 可以重新启动应用，试下加上这个参数，显式指定 dll 路径： `--libPath /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll`

我的是tomcat  启动spring应用， `--libPath /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll` 这个参数具体怎么用？

**Comment by hengyunabc** [comment]
下载arthas的全量包，解压之后就可以找到这个 dll了。或者在 `~/.arthas/lib` 目录下面找。

```
vmtool --libPath /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext

```

**Comment by anylys** [comment]
> 下载arthas的全量包，解压之后就可以找到这个 dll了。或者在 `~/.arthas/lib` 目录下面找。
> 
> ```
> vmtool --libPath /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext
> ```

不行。
我执行的是
vmtool --libPath  E:\\java\\**\\arthas-bin\\lib\\libArthasJniLibrary-x64.dll --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext

结果:
```
 我已经在 issues 里搜索，没有重复的issue。
环境信息
arthas-boot.jar 或者 as.sh 的版本：3.5.1
Arthas 版本: 3.5.1
操作系统版本: windows10
目标进程的JVM版本: OpenJDK 1.8
执行arthas-boot的版本: xxx
tomcat8.5.53
重现问题的步骤
vmtool --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext

期望的结果

vmtool error: E:\java\apache-tomcat-8.5.53\temp\ArthasJniLibrary5047835573419684488.tmp: %1 不是有效? Win32 应用程序?
```


> 下载arthas的全量包，解压之后就可以找到这个 dll了。或者在 `~/.arthas/lib` 目录下面找。
> 
> ```
> vmtool --libPath /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext
> ```

我执行的

> 下载arthas的全量包，解压之后就可以找到这个 dll了。或者在 `~/.arthas/lib` 目录下面找。
> 
> ```
> vmtool --libPath /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext
> ```

我执行的是
 我已经在 issues 里搜索，没有重复的issue。
环境信息
arthas-boot.jar 或者 as.sh 的版本：3.5.1
Arthas 版本: 3.5.1
操作系统版本: windows10
目标进程的JVM版本: OpenJDK 1.8
执行arthas-boot的版本: xxx
tomcat8.5.53
重现问题的步骤
vmtool --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext

期望的结果
实际运行的结果
vmtool error: E:\java\apache-tomcat-8.5.53\temp\ArthasJniLibrary5047835573419684488.tmp: %1 不是有效? Win32 应用程序?

 vmtool error: E:\java\apache-tomcat-8.5.53\temp\ArthasJniLibrary5047835573419684488.tmp: %1 不是有效? Win32 应用程序?

> 下载arthas的全量包，解压之后就可以找到这个 dll了。或者在 `~/.arthas/lib` 目录下面找。
> 
> ```
> vmtool --libPath /tmp/3.5.1/arthas/lib/libArthasJniLibrary-x64.dll --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext
> ```

我执行的是
vmtool --libPath  E:\\java\\xx\\arthas-bin\\lib\\libArthasJniLibrary-x64.dll --action getInstances --classLoaderClass org.apache.catalina.loader.ParallelWebappClassLoader --className org.springframework.context.ApplicationContext

结果还是:
```
vmtool error: E:\java\apache-tomcat-8.5.53\temp\ArthasJniLibrary5047835573419684488.tmp: %1 不是有效? Win32 应用程序?
```

**Comment by dragon-zhang** [comment]
@anylys open jdk是不是32位的？

**Comment by hengyunabc** [comment]
参考： #1833 ，可以测试下这个包，解压使用： https://github.com/alibaba/arthas/issues/1833#issuecomment-874756245
