### ISSUE TITLE
代码中sql过慢之后导致的性能问题查不到

### ISSUE THREAD

**Issue by nsl1065539573** [alibaba/arthas#1813]
情况是这样的，代码里有一条sql，表比较大，然后sql没有写好，在两表左连接时没有加where，用了and，所以是一条有问题的sql。之后每次请求接口都会导致服务器鸭梨太大而服务down掉。在排查问题的时候，我分别使用了watch和trace方法来跟踪这个接口，但是都没有输出，还以为是接口的切面有问题导致了没有进入方法，但其实这个时候已经进入了方法并且在执行sql时没有返回导致超时了。
ps:持久化框架是jooq 
sql语句大概类似这种：
`select * from testA a left join testB b  on a.id = b.id and b.age=10`

**Comment by hengyunabc** [comment]
这个本质上是某个函数超时了，要先确认：watch/trace的函数是不是对的。

默认情况下 watch是函数返回才打印信息，可以配置在函数入口时打印信息。https://arthas.aliyun.com/doc/watch
