### ISSUE TITLE
方法重载的时候，如何过滤指定方法

### ISSUE THREAD

**Issue by caoxingsheng** [alibaba/arthas#1819]
public class A {
    public String test2(String name) {
        return name;
    }

    public int test2(int age) {
        return age;
    }

    public int test2(Person person) {
        return person.age;
    }
    
    @Data
    class Person {
        String name;
        int age;
    }
}

trace A test2的时候，三个方法都追踪到了，如果只想监听到test2(int age)或者test2(Person person) 该怎么过滤?

```

**Comment by hengyunabc** [comment]
https://arthas.aliyun.com/doc/faq.html#id3
