### ISSUE TITLE
arthas与spring cloud gateway的结合

### ISSUE THREAD

**Issue by JunTaoYuan80** [alibaba/arthas#1825]
通过arthas，监控gateway的路由接口，找到各个链路的耗时。gateway服务的监控入口是什么？
例如：后端服务可以通过xx.xx.controller list 的方式作为入口

**Comment by hengyunabc** [comment]
参考： 

* 《Arthas实践--快速排查Spring Boot应用404/401问题》https://mp.weixin.qq.com/s/11uu8hesbrKCmyInQXctYg
* 《Arthas实践：是哪个Controller处理了请求？》https://mp.weixin.qq.com/s/UTFcppfuaz-gzxU0xAzrAA
