### ISSUE TITLE
使用vmtool命令出现的问题

### ISSUE THREAD

**Issue by Tonynkpdqz** [alibaba/arthas#1828]
控制台输入：

```
vmtool --action getInstances --className org.springframework.context.ApplicationContext --express 'instances[0].getBeanDefinitionNames()'
```

结果：Found more than one class: [interface org.springframework.context.ApplicationContext, interface org.springframework.context.ApplicationContext].

**Comment by hengyunabc** [comment]
有多个classloader，要指定具体的。参考wiki。
