### ISSUE TITLE
使用vmtool中遇到的问题

### ISSUE THREAD

**Issue by Tonynkpdqz** [alibaba/arthas#1829]
使用vmtool执行方法时，
vmtool --action getInstances --classLoaderClass org.springframework.boot.loader.LaunchedURLClassLoader --className org.springframework.context.ApplicationContext --express 'instances[0].getBean("carService").queryLoadingCar()'
queryLoadingCar方法入参里一个复杂对象，怎么使用ognl表达式表达一个复杂对象作为方法入参呢？

**Comment by hengyunabc** [comment]
ognl本身可以创建简单的java bean，复杂的不支持。参考ognl本身文档。
