### ISSUE TITLE
我下的最新版本3.0.4 只能监控jdk1.7环境下开发的项目吗？

### ISSUE THREAD

**Issue by Junkerss** [alibaba/arthas#183]

**Comment by hengyunabc** [comment]
支持jdk 6+ ，把具体信息贴出来

**Comment by Junkerss** [comment]
![image](https://user-images.githubusercontent.com/20221187/46256208-235cd080-c4da-11e8-83cd-37580993de04.png)

**Comment by Junkerss** [comment]
> 支持jdk 6+ ，把具体信息贴出来

![image](https://user-images.githubusercontent.com/20221187/46256224-4be4ca80-c4da-11e8-9e1f-60e44ac0122f.png)

**Comment by Junkerss** [comment]
> > 支持jdk 6+ ，把具体信息贴出来
> 
> ![image](https://user-images.githubusercontent.com/20221187/46256224-4be4ca80-c4da-11e8-9e1f-60e44ac0122f.png)

不能在jdk1.8环境上监控吗？

**Comment by hengyunabc** [comment]
先要安装 telnet ，搜索 windows 安装  telnet。
