### ISSUE TITLE
trace 命令增加参数控制标红输出

### ISSUE THREAD

**Issue by Machaing** [alibaba/arthas#1830]
- [ √] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.1
* 操作系统版本: win10 

### 期望的结果

使用trace命令时，能定义标红规则。比如如下命令，
trace someClass someMethod -markRed  cost>100  total>200

1  -- [1000ms] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2       -- [1ms] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
3       -- [min=1ms,max=5ms,total=400ms,count=200] xxxxxxxxxxxxxxxxxx
4       -- [min=2ms,max=101ms,total=103ms,count=2] xxxxxxxxxxxxxxxxxx
5       -- [101ms] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

此时 1、3、4、5  方括号中的文本标红

**Comment by hengyunabc** [comment]
这个太复杂了，感觉收益不大。
