### ISSUE TITLE
webconsole safari websocket 报错

### ISSUE THREAD

**Issue by wangxufire** [alibaba/arthas#1832]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本:3.5.1
* 操作系统版本: macos12
* 目标进程的JVM版本: 16
* 执行`arthas-boot`的版本: 3.5.1

### 重现问题的步骤

1. 启动 arthas-boot
2. 用 safari 访问 webconsole

### 期望的结果

可以正常使用 webconsole

### 实际运行的结果

无法使用webconsole

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/6488465/123229602-0b8acd80-d509-11eb-8f24-861386120374.png">
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/6488465/123229620-0e85be00-d509-11eb-88cc-ab7b27f3ab0d.png">

**Comment by hengyunabc** [comment]
用 chrome 有问题不？

**Comment by wangxufire** [comment]
> 用 chrome 有问题不？

没有 但不计划支持safari吗？

**Comment by hengyunabc** [comment]
* safari版本 14.0.3 
* macos 11.2.3

我测试没有问题😂。

![image](https://user-images.githubusercontent.com/1683936/124535127-339ef880-de48-11eb-935a-6d46e756ef2e.png)

**Comment by wangxufire** [comment]
> * safari版本 14.0.3 
> 
> * macos 11.2.3
> 
> 
> 
> 我测试没有问题😂。
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1683936/124535127-339ef880-de48-11eb-935a-6d46e756ef2e.png)
> 
> 

我是
macos 12.0
safari 15.0
可能beta不稳定吧 不过其它网站页面ws没问题

**Comment by hengyunabc** [comment]
先 close掉了，后续有反馈再打开。
