### ISSUE TITLE
vmtool 问题

### ISSUE THREAD

**Issue by jilliss** [alibaba/arthas#1845]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：  3.5.2
* Arthas 版本:  3.5.2
* 操作系统版本: 7
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.5.2

### 重现问题的步骤

1. 我使用arthas排查文件占用的问题
2. 执行命令为 ` vmtool --action getInstances --className java.io.FileInputStream  -x 2 -l -1 | grep xlsx  -A5`
3. 我看不到父类的对象，还是说我的使用方法不对
4. 而且我的`options print-parent-fields` 也是`true`
### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
![image](https://user-images.githubusercontent.com/30598952/124747587-a85f5900-df54-11eb-91ed-414a8ae35bd2.png)
![image](https://user-images.githubusercontent.com/30598952/124748336-916d3680-df55-11eb-990d-01846666903b.png)

**Comment by hengyunabc** [comment]
InputStream是抽象类

```
class FileInputStream extends InputStream
public abstract class InputStream implements Closeable
```

没看懂grep后面是要做啥。

**Comment by jilliss** [comment]
就是 我们在运行的tomcat中 发现 有一部分文件删不掉 一直被tomcat占用，必须每次停掉tomcat 才能删掉
我们就是想排查下到底是那个类的对象占用了这些文件
初步的思路就是有没有其他地方的文件流没关
我看vmtool就是查找对象的，所以就用了这个命令
后面的grep 就是过滤 属性里面包含 xlsx 的

**Comment by hengyunabc** [comment]
> 我看不到父类的对象，还是说我的使用方法不对

这个和父类没啥关系啊。

**Comment by jilliss** [comment]
> > 我看不到父类的对象，还是说我的使用方法不对
> 
> 这个和父类没啥关系啊。

哦，那该如何排查呢？大佬

**Comment by hengyunabc** [comment]
。。可能你想说的是引用吧， heapdump后分析。heapdump分析软件都有查找引用功能。

**Comment by hengyunabc** [comment]
heapdump里查找分析，可以参考： https://mp.weixin.qq.com/s/lWvJlW5lse3FQajRKOlAAA
