### ISSUE TITLE
关于以javaagent启动arthas参数bug

### ISSUE THREAD

**Issue by wochidaxiangchang** [alibaba/arthas#1850]
以javaagent启动arthas参数是以英文分号分隔拆分，arthas源码如下
![image](https://user-images.githubusercontent.com/47874534/124853144-fbc6bb00-dfd7-11eb-8125-dc7b5061e592.png)
在win下可以正常使用，
![image](https://user-images.githubusercontent.com/47874534/124853472-814a6b00-dfd8-11eb-9a5c-7c5f0e203157.png)

但是在linux上，Java的args中包含英文分号，会导致args无法正常解析
![image](https://user-images.githubusercontent.com/47874534/124853419-6ed03180-dfd8-11eb-8cf1-f0dd886d93ab.png)

**Comment by hengyunabc** [comment]
用符号包围起来， `-javaagent:"xxxxx;yyy"` 。
