### ISSUE TITLE
arthas-tunnel-server退出路径问题

### ISSUE THREAD

**Issue by zhuyouzhufu** [alibaba/arthas#1851]
### 环境信息

* Arthas 版本: 3.5.2
* 操作系统版本: Windows10

### 重现问题的步骤
服务端包：arthas-tunnel-server-3.5.2-fatjar
arthas-output登出后能不能跳转到他初始访问的url。如：localhost:8080，而不是http://localhost:8080/proxy/xxxxxx/arthas-output/

### 期望的结果
http://localhost:8080

### 实际运行的结果
http://localhost:8080/proxy/xxxxxx/arthas-output/

**Comment by zhuyouzhufu** [comment]
![image](https://user-images.githubusercontent.com/34908518/124858696-1fdaca00-dfe1-11eb-84f2-f3cfc03849ea.png)

**Comment by hengyunabc** [comment]
`arthas-output登出` 是指什么？

**Comment by zhuyouzhufu** [comment]
![image](https://user-images.githubusercontent.com/34908518/124880292-b79be080-e000-11eb-84ad-453bf3af52e0.png)

**Comment by hengyunabc** [comment]
😂，我知道 Arthas Output 是在这里。我想知道所谓的`登出`是什么。把具体问题一步步描述清楚。

**Comment by zhuyouzhufu** [comment]
这个按钮不是退出当前的控制台吗？如果不是那我可能误解这个按钮功能的意思了。因为在微服务中有可能我一开始排查的是A服务，然后发现A服务并没有问题，点击右上角的这个按钮（我理解为登出）。应该是要跳转到初始界面的。然后我在这个页面就可以登录B服务的控制台了。这样的话就不用用户再去输入初始页面的URL的地址。方便一点

**Comment by hengyunabc** [comment]
这个是查看火焰图的链接： https://arthas.aliyun.com/doc/profiler#arthas-outputprofiler
