### ISSUE TITLE
jad 反编译 如何寻找类

### ISSUE THREAD

**Issue by 553899811** [alibaba/arthas#1859]
jad 反编译 如何寻找类 呢？
假如 我在项目中存在类路径 相同的两个完全的 实体类，maven 聚合项目，分在不同的模块里
项目启动的时候类加载就是随机的，jad 反编译 寻找类 也是随机的吗 ？

**Comment by hengyunabc** [comment]
jad反编译的是jvm内部加载到的类。jvm自身接口提供的。 具体怎么加载，加载到哪一个是 应用ClassLoader 的事情。jad不知道，也不相关。
