### ISSUE TITLE
htt接口执行vmtool命令返回结果不符合预期

### ISSUE THREAD

**Issue by cc19931002** [alibaba/arthas#1865]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.2
* Arthas 版本: 3.5.2
* 操作系统版本: xxx
* 目标进程的JVM版本: 1.9
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 启动任意进程
2. 执行./as.sh挂载agent
3. 执行 curl -Ss -XPOST http://localhost:8563/api -d '
{
  "action":"exec",
  "command":"vmtool --action getInstances --className com.alibaba.arms.es.EsController --express 'instances[0]'"
}
'
挂载agent

### 期望的结果

有指定类的实例信息

### 实际运行的结果

{"body":{"command":"vmtool --action getInstances --className com.alibaba.arms.es.EsController --express instances[0]","jobId":1,"jobStatus":"TERMINATED","results":[{"jobId":1,"statusCode":0,"type":"status"}],"timeExpired":false},"sessionId":"8c385ec3-ef35-4680-95b5-d813a55dfe05","state":"SUCCEEDED"}

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/commit/4faefc44a0ca2c1ef5267ca489a010b61013b863
