### ISSUE TITLE
arthas会导致堆溢出吗？

### ISSUE THREAD

**Issue by bengalm** [alibaba/arthas#1866]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
因为线上环境和我本地执行不一致 怀疑是代码未更新 所以使用arthas 反编译了一个类 
第二天早上 发现OOM了
然后我在Java VIsualVM中查看到实列有对ArthasBootstrap的引用 就怀疑起来了
![VisualVM](https://user-images.githubusercontent.com/26118214/126425660-d350dc9b-6e34-41a5-bc35-3d0f420e5d6a.PNG)
### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.2
* Arthas 版本: 3.5.2
* 操作系统版本: centos7
* 目标进程的JVM版本: jdk1.8.0_181
* 执行`arthas-boot`的版本: 3.5.2

### 重现问题的步骤

1. 运行java -jar arthas-boot.jar 选择我的应用程序
2. jad xx.xx.xx 反编译
3.第二天早上发现程序不提供服务了  查看日志OOM了

我的启动参数
java -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/jvm.dump -XX:+PrintGCDetails -XX:+PrintHeapAtGC -Xloggc:/root/gc-%t.log -jar -Dspring.profiles.active=prod xxx.jar

**Comment by hengyunabc** [comment]
要分析具体引用了什么，或者被什么引用了。 参考： 

* https://blog.csdn.net/hengyunabc/article/details/103047101
* https://blog.csdn.net/hengyunabc/article/details/80879404

**Comment by bengalm** [comment]
好的
