### ISSUE TITLE
TunnelServer每分钟轮询一次，如果发现client不存活，会移除agentInfoMap，如果是因为网络波动，刚好这个点没连上，那么对应服务将无法通过tunnel访问了

### ISSUE THREAD

**Issue by qq928389526** [alibaba/arthas#1868]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.5.2
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？
可以加入类似熔断的方式，隔一段时间针对曾今检测不存活的服务，再次对他发起检测。
tunnel上找不到曾今注册的客户端该如何解决？除了重启tunnel或者客户端还有别的方式吗

### 实际运行的结果

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
客户端应该会定时重连的，重新连接上应该就会看到。

**Comment by qq928389526** [comment]
客户端重连的方法在哪呢？我只看到启动的时候会去连接。

**Comment by hengyunabc** [comment]
> 客户端重连的方法在哪呢？我只看到启动的时候会去连接。

https://github.com/alibaba/arthas/blob/arthas-all-3.5.2/tunnel-client/src/main/java/com/alibaba/arthas/tunnel/client/TunnelClient.java#L50

**Comment by qq928389526** [comment]
我是以starter方式启动的

<dependency>
--
  | <groupId>com.taobao.arthas</groupId>
  | <artifactId>arthas-spring-boot-starter</artifactId>
  | <version>${arthas.version}</version>
  | </dependency>
并没有这个类，文档也没说需要额外再引入这个包
https://arthas.aliyun.com/doc/spring-boot-starter.html

**Comment by hengyunabc** [comment]
starter启动会包含完整的arthas。检查 ~/logs/arthas/arthas.log  ，看有没有重连日志

**Comment by qq928389526** [comment]
只有刚开始的启动日志，没有重连日志。除非重启tunnel server端，才会有重连日志

**Comment by hengyunabc** [comment]
> 只有刚开始的启动日志，没有重连日志。除非重启tunnel server端，才会有重连日志

如果能复现的话，用 netstat 之类的工具，检查下和 tunnel server之间的socket连接有没有中断，然后检查网络有没有问题。
