### ISSUE TITLE
在线的环境只安装了JRE，没有JDK

### ISSUE THREAD

**Issue by hohobird** [alibaba/arthas#187]
# ./as.sh
Arthas script version: 3.0.4
/usr/lib/jvm/jre/lib/tools.jar does not exist, arthas could not be launched!

JRE下面没有tools.jar 又不方便再按照JDK，如何破？

**Comment by hengyunabc** [comment]
https://alibaba.github.io/arthas/install-detail.html  jdk8及以下 tools.jar是必需的，可以自己在服务器找下，然后 尝试 手动拼接命令行启动 。

**Comment by hohobird** [comment]
hi 多谢， JDK 下面是有的，JRE下面是没有的， 我找个JDK的相同版本，找打tools。jar， 然后拷贝到JRE下面，居然可以用。。。。。。。。。。。。
不错。
