### ISSUE TITLE
watch入参是抽象类的时候 抽象类的字段不会打印出来

### ISSUE THREAD

**Issue by maobo** [alibaba/arthas#1872]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.5.2
* Arthas 版本: 3.5.2
* 操作系统版本: macos11.4 (20F71)
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.5.2

### 重现问题的步骤

 watch cn.xxx name "{params,returnObj}" -x 2

### 期望的结果

打印实际的入参

### 实际运行的结果

 没有打印抽象类的入参，有可能因为入参是抽象类

```
 
```

**Comment by hengyunabc** [comment]
有没有可复现的demo?  `options`命令里有一个 `print-parent-fields` 的配置项，这个默认是true，应该是会打印所有的field的。
