### ISSUE TITLE
watch命令的两个小需求

### ISSUE THREAD

**Issue by weiyue888999** [alibaba/arthas#1876]
提两个小需求：

# 同时watch多类的方法

研究正在开发的中台系统，发现有时候中台会接受其他系统发来的mq消息，有时候其他系统发起rpc调用来调用这个中台系统的对外api接口方法，如果能同时watch多个类的方法就好了，能够非常全面的看系统的运行状态。

# 后台watch

能够提供gdb那样的断点功能，下一个断点之后，还能够继续下断点。这样下watch一直处于不断变化的状态，而不是一直hold住那里一直等方法调用。

**Comment by hengyunabc** [comment]
watch可以支持匹配多个类/函数，也支持以 listenerId 的方式不断增加新的匹配。仔细看watch文档： https://arthas.aliyun.com/doc/watch

**Comment by hengyunabc** [comment]
watch可以支持匹配多个类/函数，也支持以 listenerId 的方式不断增加新的匹配。仔细看watch文档： https://arthas.aliyun.com/doc/watch
