### ISSUE TITLE
版本有误

### ISSUE THREAD

**Issue by xsllvip** [alibaba/arthas#188]
-bash-4.1$ cd arthas-arthas-all-3.0.4
-bash-4.1$ cd bin
-bash-4.1$ bash -x ./as.sh
+ ARTHAS_HOME=/opt/ppm/ppm/.arthas
+ ARTHAS_LIB_DIR=/opt/ppm/ppm/.arthas/lib
+ TMP_DIR=/tmp
+ ARTHAS_VERSION=
+ ARTHAS_SCRIPT_VERSION=3.0.2
输出的是3.0.2

**Comment by hengyunabc** [comment]
这个是打包里的脚本版本，执行这个下载的是 3.0.4的：

`curl -L https://alibaba.github.io/arthas/install.sh | sh`
