### ISSUE TITLE
日志的输出 是否可以通过配置项进行配置？

### ISSUE THREAD

**Issue by fushengruomengzhang** [alibaba/arthas#1887]
#### 未找到相关配置说明文档
期望：
 * 给出配置项，自定义日志 logs/arthas[arthas-cache] 输出位置
 * 允许 日志 不输出到文件系统，仅在控制台显示

**Comment by hengyunabc** [comment]
1. 下载全量包，解压配置 logback.xml
2. 如果配置 logback输出到 stdout，就会打印到应用自身的标准输出了。不能打印到arthas的窗口里。
