### ISSUE TITLE
arthas关联的netty内存池PoolChunk对象过多

### ISSUE THREAD

**Issue by seanchen1993** [alibaba/arthas#1888]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-spring-boot-starter` 的版本： 3.5.2
* Arthas 版本: 3.5.2
* 操作系统版本: linux
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.5.2

### 重现问题的步骤

项目通过引入arthas-spring-boot-starter的方式进行在线诊断，通过heapdump --live导出堆快照发现Netty PoolChunk对象占了接近100M内存，对于我们服务而言100M应该算占用很大的内存了。对netty的池化技术不太熟悉，想请问下这里是否存在内存泄漏的风险？

### 期望的结果

内存占用有点多，有没有可能减小？

### 实际运行的结果
使用MAT工具分析的结果如下：
![741628871233_ pic_hd](https://user-images.githubusercontent.com/88898639/129390581-9517acfb-310a-42a4-9d3b-429e6fc590d5.jpg)

**Comment by hengyunabc** [comment]
启动时就占用了这么多内存？还是执行完命令之后？最好有具体重现步骤。

**Comment by seanchen1993** [comment]
我这个服务接入arthas之后我印象中都没诊断过，只是昨天晚上使用过heapdump命令导出过堆快照，就发现上面说的内存问题了，不太清楚是否有内存泄漏，所以向您问问。 @hengyunabc
