### ISSUE TITLE
Can't get the arthas.log

### ISSUE THREAD

**Issue by xsllvip** [alibaba/arthas#189]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: linux
* Java version of target JVM: 1.7
* Java version of JVM used to attach: xxx

### Steps to reproduce this issue

```
Attaching to 17757 using version <!DOCTYPE html PUBLIC "-...
Error: Unable to access jarfile /opt/ppm/ppm/.arthas/lib/<!DOCTYPE html PUBLIC "-/arthas/arthas-core.jar
attach to target jvm (17757) failed, check /opt/ppm/ppm/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
```

**Comment by hengyunabc** [comment]
Try to run `bash -x ./as.sh`

**Comment by ralf0131** [comment]
I think your arthas is not installed correctly.

**Comment by Hearen** [comment]
@xsllvip https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#local-installation
