### ISSUE TITLE
小白求教，tunnel server集群部署时从redis中读取agent信息是不是就能解决Agent和Web Console的连接问题了？

### ISSUE THREAD

**Issue by seanchen1993** [alibaba/arthas#1893]
### 问题

tunnel server 部署集群 ，Agent和Web Console如何进行消息流转？
长连接不在一个服务器上怎么处理？

### 期望
直接读取redis中的agent信息是否可行？

**Comment by hengyunabc** [comment]
要在nginx上配置，保证访问同一个tunnel server，文档上有写： https://arthas.aliyun.com/doc/tunnel.html#id3

**Comment by seanchen1993** [comment]
我们这边应用的流量分发是平台自己做的，我们应用方应该没法控制，哪这个咋搞，小白求教。😳 @hengyunabc

**Comment by hengyunabc** [comment]
或者最简单办法，只部署一台 tunnel server😂，加大点内存，支持几千个节点应该没啥问题。
