### ISSUE TITLE
profiler后执行stop, 过几秒后jvm崩溃

### ISSUE THREAD

**Issue by jacinchan** [alibaba/arthas#1895]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.3
* Arthas 版本: 3.5.3
* 操作系统版本: Linux EulerOS 4.19.36 aarch 64
* 目标进程的JVM版本: jdk1.8.0_292
* 执行`arthas-boot`的版本: 3.5.3

### 重现问题的步骤

1. profiler -b 10000000 -d 10 start
2. profiler 完成后，stop 退出arthas
过几秒后jvm崩溃

### 期望的结果

退出arthas, jvm仍正常运行

### 实际运行的结果
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffff5a9a61ac, pid=268723, tid=0x0000ffff6973f1e0
#
# JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-Cloud_Compiler_JDK_V100R003C20SPC290B002-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-aarch64 compressed oops)
# Problematic frame:
# C  0x0000ffff5a9a61ac
```

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
😂，这个需要向上游报告，3.5.3版本实际用的 async-profiler 1.8.6 
* https://github.com/jvm-profiling-tools/async-profiler/
