### ISSUE TITLE
IDEA运行源码 输入命令无效

### ISSUE THREAD

**Issue by Pluto-zZ-zZ** [alibaba/arthas#1914]
本地CMD启动可以正常使用：
![image](https://user-images.githubusercontent.com/68190554/132490043-470f389e-22f5-472a-b53c-c46940bccda4.png)

IDEA启动源码，输入任何命令均无反应：
![image](https://user-images.githubusercontent.com/68190554/132490221-13bab9c4-cfa8-46c5-8ad9-ba22deb54afa.png)

大佬，Help！！！

**Comment by hengyunabc** [comment]
idea自身问题，用系统的terminal来启动。

**Comment by Pluto-zZ-zZ** [comment]
emmm，有什么办法能解决下吗？因为想debug调试学习下源码，terminal启动的无法打断点啊

**Comment by hengyunabc** [comment]
参考这个： https://github.com/webx/citrus/issues/48

**Comment by zerodayZHOUXUTIAN** [comment]
> emmm，有什么办法能解决下吗？因为想debug调试学习下源码，terminal启动的无法打断点啊

你解决了吗

**Comment by zerodayZHOUXUTIAN** [comment]
> 参考这个： [webx/citrus#48](https://github.com/webx/citrus/issues/48)

这个好像不太行，不是同一问题。使用junit的是可以输入的。
