### ISSUE TITLE
引用对象如果在方法内改变值后用watch方法监控到的是改变后的值而不是传入时候的值

### ISSUE THREAD

**Issue by kuhnyang** [alibaba/arthas#1916]
在使用watch方法监控方法的params和returnObj的时候发现，如果方法的入参(params)如果是引用类型的对象的话，在方法内部改变对象的属性的值，那么用watch监控到的方法的params是改变后的值而不是改变之前的值

**Comment by hengyunabc** [comment]
仔细看watch的wiki，对于什么时候打印有具体说明。
