### ISSUE TITLE
Idea 中 运行调试 com.taobao.arthas.core.Arthas 的main方法 参数应该传什么？

### ISSUE THREAD

**Issue by sanxun0325** [alibaba/arthas#193]

**Comment by earayu** [comment]
可以参考LocalDebugTest，注意jar包实际路径。

**Comment by hengyunabc** [comment]
调试参考 https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#debug-1 ， `LocalDebugTest` 准备删除掉。
