### ISSUE TITLE
tt -t 增强类之后会把函数的参数名给抹除,reset也没用

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [alibaba/arthas#1969]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.0
* Arthas 版本: 3.5.0
* 操作系统版本: xxx
* 目标进程的JVM版本: openjdk 1.8.0_272
* 执行`arthas-boot`的版本: 3.5.0

### 重现问题的步骤

![image](https://user-images.githubusercontent.com/7438737/135210799-96b9fbfe-138b-42c3-963d-130481af6077.png)

ognl -c xxx '@某个类@class.getMethods()[0].getParameters()' -- 正常
tt -t 某个类 *
ognl -c xxx '@某个类@class.getMethods()[0].getParameters()' -- 参数名丢失

### 期望的结果

What do you expected from the above steps？
参数名保持正常 至少reset之后能恢复正常
### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
jdk自身的bug，参考： https://github.com/alibaba/arthas/issues/2800
