### ISSUE TITLE
No class or method is affected when trying command like trace or watch

### ISSUE THREAD

**Issue by ralf0131** [alibaba/arthas#198]
0. 先确认Arthas已经挂载到正确的Java进程里面了，检查Arthas连上时输出的PID，确认是想要挂载的目标进程ID(和 ps -ef 的结果比对)
1. 先用sc或者sm搜索对应的类和方法，确认已经被JVM加载
2. 在`~/logs/arthas/arthas.log`中查找有没有Method code too large的异常
3. 存在该异常时，尝试用`reset class_name`命令对类进行恢复，再进行trace，watch等操作
4. 系统级别的类默认不能进行增强，需要增强是请参考[这里](https://alibaba.github.io/arthas/options.html)的`unsafe`开关，增强系统类时请谨慎操作

## English version

0. Please confirm that Arthas is attached to the correct JVM. Check the PID Arthas output when connection has established with the actual process id (using ps -ef)
1. Check the class has been loaded by this JVM by using `sc` or `sm` command.
1. Check whether there is `Method code too large` exception in `~/logs/arthas/arthas.log`
2. If there is such exception, try to use `reset class_name` to eliminate the modified byte code and try again.
3. Enhancing classes begin with java.* are disabled by default, please refer to [this](https://alibaba.github.io/arthas/options.html) to opt-in.

**Comment by ahzpc007** [comment]
@ralf0131 
hi，有个问题请教下
自己写的demo程序，本地启动后，能通过arthas找到该进程
 [5]: 23737 com/study/atm/Demo
使用watch命令后，提示
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
使用sc命令
$ sc com/study/atm/Demo
Affect(row-cnt:0) cost in 47 ms.
看样子似乎没有被JVM加载，这一点比较奇怪，因为程序已经跑起来，而且arthas也能查到此进程。

**Comment by Hearen** [comment]
@ahzpc007 Would you elaborate your question help us to **re-produce** your issue?

**Comment by ahzpc007** [comment]
> 思路很清晰，重点是需要找对pid，看看自己进入的是哪一个

目前只是在本地出现过一次，测试或线上环境都能正常使用，
可能是确实是pid选择问题。

**Comment by szlzhm** [comment]
我这里也遇到这样的问题，我的java编译用java1.8.0_161，运行环境是java1.8.0_181，ubuntu 16.0 64位，springboot应用。下面是命令好相关故障：
命令：trace com.kc.Compare compare
故障输出：
Press Ctrl+c to abort
Affect(class-cnt:1, method-cnt:1) cost in 183 ms.

然后就没有输出了。
我这个命令本来是有输出的，运行了多次后，就不论怎样都没有输出了。

**Comment by beigekaoke** [comment]
> 我这里也遇到这样的问题，我的java编译用java1.8.0_161，运行环境是java1.8.0_181，ubuntu 16.0 64位，springboot应用。下面是命令好相关故障： 命令：trace com.kc.Compare compare 故障输出： Press Ctrl+c to abort Affect(class-cnt:1, method-cnt:1) cost in 183 ms.
> 
> 然后就没有输出了。 我这个命令本来是有输出的，运行了多次后，就不论怎样都没有输出了。 我的PID选择没有错误，使用的版本是3.0.5, 打开unsafe也没用

这个解决了吗？

**Comment by bf109f** [comment]
抽象的父类中的方法 使用子类该如何追踪？
