### ISSUE TITLE
monitor命令的-E选项报错

### ISSUE THREAD

**Issue by setamv** [alibaba/arthas#2009]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.5.4
* Arthas 版本: 3.5.4
* 操作系统版本: 
   Linux version 4.20.13-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Wed Feb 27 10:02:05 EST 2019
* 目标进程的JVM版本: 
   [18:13:26][root@192:1.0]# java -version
    java version "1.8.0_261"
    Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
* 执行`arthas-boot`的版本: 3.5.4

### 重现问题的步骤

1. 启动测试代码
2. 使用`java -jar arthas-boot.jar`启动arthas，并选中第一步中启动的Java进程
3. 执行profiler命令如下报错：
    ```
    [arthas@24241]$ monitor -E com.alibaba.fastjson.JSON  writeJSONString|parseObject
    The argument 'method-pattern' is required, description: Method of Pattern Matching
    ```
    

### 期望的结果
    可以正确执行monitor命令

### 实际运行的结果
报错：The argument 'method-pattern' is required, description: Method of Pattern Matching

**Comment by yqxzy** [comment]
你需要在monitor -E 后面加参数1，表示采用正则匹配。但是感觉这要的设置不太方便，我稍微修改了一下源码。
