### ISSUE TITLE
Is this a bug while debugging TelnetConsole

### ISSUE THREAD

**Issue by Hearen** [alibaba/arthas#202]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: 16.04.1-Ubuntu 2018 x86_64 x86_64 x86_64 GNU/Linux
* Java version of target JVM: jdk1.8.0_144
* Java version of JVM used to attach: jdk1.8.0_144

### Steps to reproduce this issue

1. follow this to create the demo first: https://github.com/Hearen/arthas/blob/doc-with-consistent-demo/site/src/site/sphinx/en/quick-start.md
1. start Arthas server: `bin/as.sh debug 13328`
2. start TelnetConsole in IntelliJ with program arguments: localhost -p 3658 -c getstatic demo.Demo$Counter count -w 500 -h 300
3. Start it by **debug**

> I tried the command directly in `asthas`, which works as expected. 

```
$ getstatic demo.Demo$Counter count
field: count
@AtomicInteger[
    serialVersionUID=@Long[6214790243416807050],
    unsafe=@Unsafe[sun.misc.Unsafe@6ec96bdb],
    valueOffset=@Long[12],
    value=@Integer[3140],
]

```

### Error:

```
$ Disconnected from the target VM, address: '127.0.0.1:38919', transport: 'socket'
getstatic | plaintext
The argument 'class-pattern' is required
```

### Expected Result

the command not fully properly parsed (only the first token parsed). 

### Other Questions

interactive commands as `dashboard` will not print anything since it's interactive. 

Commands work as expected now are only **non-interactive** and **single** ones as: `thread`, `jvm` and `sysprop`, which I suppose is so limited. 

Is this designed with other concerns or design mistake only? 

@hengyunabc @ralf0131

**Comment by hengyunabc** [comment]
The old version TelnetConsole maybe have some problem. please try the new version code.
