### ISSUE TITLE
尝试在docker宿主机上通过http api的形势获取容器内arthas版本信息报错command not found

### ISSUE THREAD

**Issue by SuperSt0ne** [alibaba/arthas#2020]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.5.4
* 操作系统版本: xxx
* 目标进程的JVM版本: 1.8.0_211
* 执行`arthas-boot`的版本: 3.3.3

### 重现问题的步骤
尝试在docker宿主机上通过http api的形势获取容器内arthas版本信息报错command not found，使用的是官方文档中获取Arthas版本号的例子
```
curl -Ss -XPOST http://localhost:9001/api -d '
{
  "action":"exec",
  "command":"version"
}
'
```

### 期望的结果

同官方文档中一样获取到容器内arthas的版本

### 实际运行的结果
![image](https://user-images.githubusercontent.com/55782596/139644526-48106926-4667-4adb-9d55-561842019618.png)

**Comment by 1057Sc** [comment]
后来是咋解决的？

**Comment by NeilJGChen** [comment]
咋解决的？
