### ISSUE TITLE
使用 ./as-package.sh打包时报错

### ISSUE THREAD

**Issue by 1057Sc** [alibaba/arthas#2041]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
* Arthas 版本: arthas-all-3.5.5)
* 操作系统版本: macos 12.01
* arch: "x86_64"

### 重现问题的步骤
使用如下命令打包
`$ ./as-package.sh` 

### 期望的结果
期望可以打包成功

### 实际运行的结果

```
[ERROR] Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-alpha-11:compile (javah) on project arthas-vmtool: Error executing command line. Exit code:1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :arthas-vmtool
```

**Comment by 1057Sc** [comment]
又翻了翻日志，好像是找不到xcode导致的，我先安装下xcode试下

**Comment by aresLD** [comment]
vmtool模块，估计是你本地编译jni的C++代码失败了

**Comment by 1057Sc** [comment]
> 
是这里，昨天看了下日志，目测是没有装xcode导致的，我之前用的gcc

**Comment by 1057Sc** [comment]
> vmtool模块，估计是你本地编译jni的C++代码失败了

是这里，昨天看了下日志，目测是没有装xcode导致的，我之前用的gcc

**Comment by 1057Sc** [comment]
问题已解决
1. 安装xcode, 并且通过`xcode-select --install` 安装xcode commline-line-tool
2. 接下来会提示找不到libstdc++ 问题，clone如下https://github.com/quantum6/xcode-missing-libstdcpp链接，仔细阅读install.sh脚本作用
3. 理解install.sh的作用后，建议将c++目录复制，因为不知道为什么我这ln -s 到`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr` 会提示权限不足，用root也没用，下面附上我在理解install.sh脚本的作用后改过的脚本
```shell
#!/usr/bin/env bash

set -e

DEST_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr
# 这里注释掉是因为我复制过去了，没有使用ln -snf 命令
#sudo ln -snf \
#    $PWD/include/c++ \
#    ${DEST_DIR}/include/

sudo ln -snf \
    $PWD/lib/libstdc++.6.0.9.tbd \
    $PWD/lib/libstdc++.6.tbd \
    $PWD/lib/libstdc++.tbd \
    ${DEST_DIR}/lib/

```
