### ISSUE TITLE
静态内部类NopSpy存在的必要？

### ISSUE THREAD

**Issue by aresLD** [alibaba/arthas#2045]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.4
* Arthas 版本: 3.5.4
* 操作系统版本: windows10
* 目标进程的JVM版本: jdk8对应的hotspot
* 执行`arthas-boot`的版本: 3.5.4

### 重现问题的步骤
java -jar arthas-boot.jar pid
stop
jmap histo:live pid
### 期望的结果
stop后所有arthas侵入引入的实例都应卸载完毕

### 实际运行的结果
654:             1             16  java.arthas.SpyAPI$NopSpy

```
### 补充说明:
NoSpy存在的意义是什么？
```

**Comment by hengyunabc** [comment]
如果在SpyAPI的代码里抛出异常，对应用来说是非常严重的。整个应用都可能不可用。NopSpy是个保底方案，保证在arthas本身代码出错时，或者stop不干净时，应用还能正常运行。
