### ISSUE TITLE
无法kill arthas进程，只能kill application的进程

### ISSUE THREAD

**Issue by csdn-ss** [alibaba/arthas#205]
无法kill arthas进程，只能kill application的进程
使用命令行启动后，如果监控某个application，想切换监控另一个application
arthas 无法shutdown， ps -ef 也找不到对应的进程号
通过telnet后 看到的pid是其实是application的pid
将application kill掉 arthas才能kill

**Comment by earayu** [comment]
arthas是没有独立进程的，它是被应用进程加载后在应用进程中运行的，所以arthas和应用进程的pid相同。
如果想关闭arthas的话，可以使用`shutdown`命令

**Comment by iceqing** [comment]
如果不进入arthas如何关闭，或者说如何利用shell脚本关闭呢? @earayu @earayu

**Comment by hengyunabc** [comment]
> 如果不进入arthas如何关闭，或者说如何利用shell脚本关闭呢? @earayu @earayu

java -jar arthas-boot.jar pid -c 'shutdown'
