### ISSUE TITLE
apps.html 这个页面没有登陆也可以访问和看到数据，是否合理

### ISSUE THREAD

**Issue by 350226401** [alibaba/arthas#2055]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.5
* Arthas 版本: 3.5.5
* 操作系统版本: windows10
* 目标进程的JVM版本: java1.8
* 执行`arthas-boot`的版本: 3.5.5

### 重现问题的步骤

1. apps.html 这个页面没有登陆也可以访问，此现象是否合理？是否需要优化

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
默认是没有权限控制的，需要结合自己公司做开发。wiki页有提到。

**Comment by 350226401** [comment]
***@***.***】的邮箱。您的邮件，我已经收到。
