### ISSUE TITLE
Arthas在获取对象的成员变量的值的时候是否会有多线程可见性的问题

### ISSUE THREAD

**Issue by Aitozi** [alibaba/arthas#2059]
没有实际碰到这种问题，只是好奇我们再使用arthas的`vmtool`的工具去查看对象的变量时，是否会受到多线程修改变量而导致变量值不可见的问题？

**Comment by dragon-zhang** [comment]
您是指执行`vmtool`的时候，还是执行`vmtool`之后？

**Comment by Aitozi** [comment]
@dragon-zhang 执行`vmtool`的时候，就是`vmtool`看到的值是否是最新的，会有这种保障吗？

**Comment by dragon-zhang** [comment]
有保障的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/arthas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 晚上11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/arthas] Arthas在获取对象的成员变量的值的时候是否会有多线程可见性的问题 (Issue #2059)





 
@dragon-zhang 执行vmtool的时候，就是vmtool看到的值是否是最新的，会有这种保障吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aitozi** [comment]
好的, 谢谢
