### ISSUE TITLE
JUL in thread command doc

### ISSUE THREAD

**Issue by Hearen** [alibaba/arthas#206]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce this issue

1. open doc link for `thread` command: https://alibaba.github.io/arthas/en/thread.html#thread-b-locate-the-blocking-threads
2. search for `JUL`;

### Expected Result

What's the meaning of this `JUL`? I've been searching google and wiki but still no clue what specifically does it mean? 

F.Y.I

the whole sentence:

> Attention: only synchronized blocked threads can be located for now, JUL not supported yet.

**Comment by ralf0131** [comment]
JUL stands for java.util.concurrent.Lock interface, maybe should be JUC lock. The thread command currently does not support JUC lock interface.

**Comment by Hearen** [comment]
#228
