### ISSUE TITLE
使用命令行无法执行retransform

### ISSUE THREAD

**Issue by zhangleiasj** [alibaba/arthas#2062]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.0
* Arthas 版本: 3.5.4
* 操作系统版本: CentOS release 6.9 (Final)
* 目标进程的JVM版本: java-1.7.0-openjdk-1.7.0.261.x86_64

### 重现问题的步骤

1. 运行下面命令报错
`sh /data/arthas/as.sh 97012 -c retransform -l`
2. 通过交互命令直接执行【retransform -l】可以正常显示

### 期望的结果
命令行也可以正确显示retransform结果

### 实际运行的结果
![image](https://user-images.githubusercontent.com/17452894/147195790-23077301-80c9-4320-a0e7-d1aa641200e6.png)

![image](https://user-images.githubusercontent.com/17452894/147196043-5b12ab16-be8a-4134-ba5f-2aa1c9fc1905.png)

**Comment by wwulfric** [comment]
sh /data/arthas/as.sh 97012 -c "retransform -l"
