### ISSUE TITLE
一个领取bug任务的网站被我忘记了。。。。

### ISSUE THREAD

**Issue by StarfishW** [alibaba/arthas#2063]
我记得几个月前，看到了一个bug汇总领取的网站，也看到了arthas的bug
里面还有简单，中等，困难的等级划分
但是被我忘记了，请问有知道这个网站的吗
类似这种
![image](https://user-images.githubusercontent.com/56779281/147344533-15568332-d898-49cd-94ea-d316f81d8be5.png)

**Comment by 2219160052** [comment]
> 

找到了吗
