### ISSUE TITLE
Try to attach process 9 一直在这个界面，没有报错信息

### ISSUE THREAD

**Issue by anson88616425** [alibaba/arthas#2066]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* 操作系统版本: openjdk:8-jdk-alpine
* 目标进程的JVM版本: openjdk:8-jdk-alpine
* 执行`arthas-boot`的版本: arthas-boot version: 3.5.5

### 重现问题的步骤

1. docker exec -it bi-backend /bin/sh -c "java -jar /opt/arthas/arthas-boot.jar"
2. 输入数字1

### 期望的结果

希望attach成功

### 实际运行的结果

* [1]: 9 bi-backend-1.0.jar
1
[INFO] arthas home: /opt/arthas
[INFO] Try to attach process 9

```
没有报错信息，一直卡在Try to attach process 9这里
```

**Comment by littleyg** [comment]
遇到同样的问题

**Comment by myesn** [comment]
I had the same problem, here is part of my Dockerfile:

```Dockerfile
FROM openjdk:8-jdk-alpine

COPY --from=hengyunabc/arthas:latest /opt/arthas /opt/arthas

...
```

Then I built the image and successfully started the container,  I go inside the container of serviceA and start arthas, finally, I entered the container of serviceA and started arthas. When I entered `1` and pressed the `Enter` key, the Java program in the container of serviceA stopped running, and the container was also in `Exit 131` state, like this:

```
ubuntu@ubuntu:~/shenyu/shenyu-master$ docker-compose exec shenyu-admin sh
/opt/shenyu-admin # java -jar /opt/arthas/arthas-boot.jar
[INFO] arthas-boot version: 3.6.0
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 34 org.apache.shenyu.admin.ShenyuAdminBootstrap
1
[INFO] arthas home: /opt/arthas
[INFO] Try to attach process 34
ubuntu@ubuntu:~/shenyu/shenyu-master$ docker-compose ps
      Name                    Command                  State                        Ports
-----------------------------------------------------------------------------------------------------------
shenyu-admin       /bin/sh entrypoint.sh            Exit 131
```
