### ISSUE TITLE
timestamp in Arthas is so inhuman - un-readable

### ISSUE THREAD

**Issue by Hearen** [alibaba/arthas#207]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

Environment
Arthas version: 3.0.4
Operating System version: 15.6.0 Darwin Kernel Version 15.6.0
Java version of target JVM: jdk1.8.0_73
Java version of JVM used to attach: jdk1.8.0_73

### Steps to reproduce this issue

1. follow this to start Arthas: https://github.com/Hearen/arthas/blob/doc-with-consistent-demo/site/src/site/sphinx/en/quick-start.md
2. select the demo to monitor

### Expected Result

A human readable time instead of a timestamp based on milliseconds.

### Actual Result

```
Connected to localhost.
Escape character is '^]'.
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki: https://alibaba.github.io/arthas
version: 3.0.5.20181010215221
pid: 1545
timestamp: 1539181308855
```

**Comment by ralf0131** [comment]
Yes, please enhance it by sending a pull request!

**Comment by Hearen** [comment]
> Yes, please enhance it by sending a pull request!

@ralf0131 I am starting a MR to replace the `unreadable` timestamp to [ZonedDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html).

**Comment by Hearen** [comment]
@ralf0131 #213
