### ISSUE TITLE
服务器启动了多个应用,选择不同的进程进入,最终进入的都是同一个进程

### ISSUE THREAD

**Issue by leoalasiga** [alibaba/arthas#2078]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.1
* Arthas 版本: arthas-packaging-3.1.1
* 操作系统版本: aliyun ecs
* 目标进程的JVM版本: java version "1.8.0_144"
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. 当前服务器起了多台应用
![image](https://user-images.githubusercontent.com/39647836/148896963-6e36fbc7-9cfc-42f9-b15e-f18c49437bd7.png)

2. 启动arthas,随便选择一个序号进入
![image](https://user-images.githubusercontent.com/39647836/148897055-e07aae80-8187-4a72-9086-cb98d6c5f444.png)

3. 使用jad反编译,报错无指定文件
4. 排查发现无论选择那个序号进入,最终arthas都是进入同一个应用

### 期望的结果

What do you expected from the above steps？
```
期望进入之后,arthas进入指定的应用
```

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
1. 先执行`stop`/`shutdown`命令彻底退出
1. 最好用最新版本

https://arthas.aliyun.com/doc/stop
