### ISSUE TITLE
jad 的 http api 返回格式不是合法 json

### ISSUE THREAD

**Issue by wwulfric** [alibaba/arthas#2081]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.5
* Arthas 版本: 3.5.5
* 操作系统版本: 无关
* 目标进程的JVM版本: 无关
* 执行`arthas-boot`的版本: 3.5.5

### 重现问题的步骤

1.
```shell
curl -Ss -XPOST http://localhost:8563/api -d @- << EOF
{
  "action":"exec",
  "execTimeout": 30000,
  "command":"jad org.apache.log4j.Logger"
}
EOF
```

返回的结果的mappings 是：
```json
{25:135,29:117,33:104,37:155,41:188,42:189,44:192,45:193,50:166,51:167,53:170,54:171,60:30,68:205,69:206,71:209,75:40}
```

### 期望的结果

key 是 string

### 实际运行的结果

key 是 int

**Comment by hengyunabc** [comment]
fastjson的问题，已修复。
