### ISSUE TITLE
Arthas Spring Boot Starter 是否支持配置鉴权

### ISSUE THREAD

**Issue by mrssz** [alibaba/arthas#2092]
当前版本的Arthas Spring Boot Starter(3.5.5) 当前在 Arthas Properties中不支持配置username、password，那么Arthas Spring Boot Starter使用方式下，应该如何鉴权

**Comment by hengyunabc** [comment]
实际上是传一个map进去的，可以直接配置上，只不过没有IDE的自动提示。 可以看下starter代码里怎么注入配置的。

**Comment by mrssz** [comment]
done，感谢大神解答~
