### ISSUE TITLE
类里引用带有泛型的类，mc编译报错

### ISSUE THREAD

**Issue by flw123456** [alibaba/arthas#2098]
- [√ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.5.5
* 操作系统版本: win10
* 目标进程的JVM版本: jdk8

### 重现问题的步骤

1.Controller类的返回是类A，A里含有泛型字段，然后mc编译的时候报错
[arthas@6]$ mc -c 60addb54 /tmp/RedEnvelopController.java -d /tmp
Memory compiler error, exception message: Compilation Error
message: incompatible types: inference variable T has incompatible bounds
    equality constraints: xxxxxx.RedEnvelopSendRespVO
    lower bounds: java.lang.Object , line: 107 , 
message: incompatible types: inference variable T has incompatible bounds
    equality constraints: xxxxxx.RedEnvelopeGrabRecordRespVO
    lower bounds: java.lang.Object , line: 116 , 
message: incompatible types: inference variable T has incompatible bounds
    equality constraints: xxxxxx.RedEnvelopeSendRecordResponse
    lower bounds: java.lang.Object , line: 125 , 
message: incompatible types: inference variable T has incompatible bounds
    equality constraints: xxxxxx.RedEnvelopeGrabRespVO
    lower bounds: java.lang.Object , line: 134 , 
message: incompatible types: inference variable T has incompatible bounds
    equality constraints: xxxxxx.RedEnvelopeMainRespVO
    lower bounds: java.lang.Object , line: 141 , 
, please check $HOME/logs/arthas/arthas.log for more details.

### 期望的结果

可以编译成功

### 实际运行的结果

编译失败

**Comment by hengyunabc** [comment]
不支持泛型。
