### ISSUE TITLE
vmtool javah java9+ 上会编译失败

### ISSUE THREAD

**Issue by 1994** [alibaba/arthas#2105]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.5.5
* 目标进程的JVM版本: java 9 +

### 重现问题的步骤

java9+ 删除了javah ，https://github.com/mojohaus/maven-native/issues/17

**Comment by dragon-zhang** [comment]
看下 https://github.com/alibaba/arthas/issues/1920
```shell
javac -h . Main.java
# 两个命令都可以，但是从JDK10开始javah被废弃
# 因此推荐使用上面的命令
javah Main
```

**Comment by hengyunabc** [comment]
目前需要编译target为 jdk 6，所以最好只用jdk 8来编译，更新了文档： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#%E5%BC%80%E5%8F%91%E8%80%85%E7%9B%B8%E5%85%B3
