### ISSUE TITLE
arthas jad反编译class文件看起来相同，但是执行结果却大不相同

### ISSUE THREAD

**Issue by john1337** [alibaba/arthas#2109]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.5.5
* 操作系统版本: ubuntu20.04
* 目标进程的JVM版本: jdk1.8.0_321

arthas jad反编译class文件看起来相同，但是执行结果却大不相同，不知有没有什么其他方式排查这个问题？

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/763

**Comment by john1337** [comment]
> 参考这个： #763

用dumpclass导出的class文件还是看不出有什么差别，且出现了this.operationComplete<invokedynamic>这类的代码

**Comment by hengyunabc** [comment]
要对比字节码文件。jad 反编译结果可能会有部分识别不到的会忽略掉。

**Comment by john1337** [comment]
> 要对比字节码文件。jad 反编译结果可能会有部分识别不到的会忽略掉。

不知还有什么排查方式么，因为字节码文件对比起来很不方便

**Comment by hengyunabc** [comment]
有没有具体的示例demo。
