### ISSUE TITLE
-E regex matching sub-class error or something else?

### ISSUE THREAD

**Issue by Hearen** [alibaba/arthas#211]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

No answer and details provided in #96 

More details provided here to **re-produce** the issue.

Environment
Arthas version: 3.0.4
Operating System version: 15.6.0 Darwin Kernel Version 15.6.0
Java version of target JVM: jdk1.8.0_73
Java version of JVM used to attach: jdk1.8.0_73

### Steps to reproduce this issue

1. follow this to start Arthas: https://github.com/Hearen/arthas/blob/doc-with-consistent-demo/site/src/site/sphinx/en/quick-start.md
2. select the demo to monitor
4. using command `sc` to locate class `demo.Demo$Counter`.

### Expected

```
$ sc demo.Demo$Counter
demo.Demo$Counter
Affect(row-cnt:1) cost in 1 ms.

$ sc -E demo\.Demo\$Counter
demo.Demo$Counter
Affect(row-cnt:1) cost in 11 ms.
```

### Actual Result

```
$ sc demo.Demo$Counter
demo.Demo$Counter
Affect(row-cnt:1) cost in 1 ms.

$ sc -E demo\.Demo\$Counter
Affect(row-cnt:0) cost in 2 ms.

$ sc -E demo\.Demo\\$Counter
demo.Demo$Counter
Affect(row-cnt:1) cost in 3 ms.

$ sc -E demo.Demo\\$Counter
demo.Demo$Counter
Affect(row-cnt:1) cost in 3 ms.
```

### Questions

1. Why require `\\` instead of a single `\` here? Unlike this escaping rule https://github.com/alibaba/arthas/issues/71#issuecomment-422699741 and `sc -E demo\.Demo\$Counter` didn't work?
2. Why `sc -E demo.Demo\\$Counter` worked? Shouldn't it be `sc -E demo\.Demo\$Counter`?

**Comment by hengyunabc** [comment]
Refer to #302
