### ISSUE TITLE
http 请求vmtool命令没有输出结果

### ISSUE THREAD

**Issue by bjdaijun** [alibaba/arthas#2119]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.5/3.5.3
* Arthas 版本: 3.5.5
* 操作系统版本: windows/linux
* 目标进程的JVM版本: jdk11/jdk8
* 执行`arthas-boot`的版本: 3.5.5

### 重现问题的步骤

1. java -jar arthas-boot.jar
2. postman 提交请求 
```{
  "action": "exec",
  "command": "vmtool --action getInstances --className  java.lang.String",
  "execTimeout": "10000"
}
```

### 期望的结果
@String[][

]
What do you expected from the above steps？

### 实际运行的结果

{
    "body": {
        "command": "vmtool --action getInstances --className java.lang.String",
        "jobId": 7,
        "jobStatus": "TERMINATED",
        "results": [
            {
                "jobId": 7,
                "statusCode": 0,
                "type": "status"
            }
        ],
        "timeExpired": false
    },
    "sessionId": "bfff66ee-fe79-4093-b251-347c39768804",
    "state": "SUCCEEDED"
}

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/commit/4faefc44a0ca2c1ef5267ca489a010b61013b863
