### ISSUE TITLE
手动更新arthas后版本号还是旧的版本号

### ISSUE THREAD

**Issue by lenggggg** [alibaba/arthas#2121]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.5.5
* 操作系统版本: xxx
* 目标进程的JVM版本: 1.7
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. arthas连接到目标进程
2. 执行stop退出arthas
3. 删除~/.arthas下的文件夹并上传版本更高的arthas
4. arthas连接到目标进程还是显示旧的版本号
5. 需要重启目标进程才显示新的版本号

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
arthas启动时，会打印出 arthas home，看具体arthas是从哪里加载到的。

**Comment by lenggggg** [comment]
你好，你的邮件已收到

**Comment by lenggggg** [comment]
打印出来是/root/.arthas/lib/3.5.5/arthas，上传新版本的arthas时我会将这个文件夹删掉，再在该路径上传一个新的。
另：上传的arthas是我运行as-package.sh重新打包的，拿的是3.5.5xxxx最高版本的那一个。

**Comment by hengyunabc** [comment]
直接把zip解压到某个目录，比如 /tmp/arthas_xxx ，然后 cd 进去，再启动 ./as.sh 就可以了。 不要自己手动操作 ~/.arthas 目录。
