### ISSUE TITLE
【需求】vmtool统计内存中对象的数量

### ISSUE THREAD

**Issue by linhaijing** [alibaba/arthas#2130]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 最新版本
* Arthas 版本: 最新
* 操作系统版本: mac os

### 重现问题的步骤

想要统计某个类某个方法中，定义的局部变量对象的个数

### 期望的结果

想要统计某个类某个方法中，定义的局部变量对象的个数

### 实际运行的结果

无

**Comment by hengyunabc** [comment]
不支持。可能需要自己写个asm分析的工具，分析有多少new的行为。
