### ISSUE TITLE
mc 编译失败

### ISSUE THREAD

**Issue by sipherhern** [alibaba/arthas#2138]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.5
* Arthas 版本: 3.6.0
* 操作系统版本: linux
* 目标进程的JVM版本: 1.8.0_152
* 执行`arthas-boot`的版本: 3.5.5

### 重现问题的步骤

1. jad反编译生成源代码，正常
2. 修改源代码，仅增加logger.info日志
3. sc -d | grep classLoader 查找类的加载器
4. mc -c 指定类加载器 编译字节码文件

### 期望的结果

期望编译成功

### 实际运行的结果

```
Memory compiler error, exception message: Compilation Error
message: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.alibaba.securitysdk.logging.api.processor.ModifiedMethodLoggerProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/sun/tools/javac/tree/JCTree$Visitor , line: -1 ,
, please check $HOME/logs/arthas/arthas.log for more details.
```

**Comment by hengyunabc** [comment]
看 mc wiki， mc不保证一定成功。
