### ISSUE TITLE
vmtool --action sumInstanceSize 不支持吗

### ISSUE THREAD

**Issue by GentleSong** [alibaba/arthas#2140]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

3.5.4 版本

### 重现问题的步骤

如题：
vmtool --action sumInstanceSize --className
提示错误：
The value 'sumInstanceSize' is not accepted by 'action'

**Comment by dragon-zhang** [comment]
是的，现在command里应该只封装了`getInstance`和`forceGC` 2个方法，如果您有兴趣的话，可以跟@hengyunabc 讨论下。

**Comment by GentleSong** [comment]
> 是的，现在command里应该只封装了`getInstance`和`forceGC` 2个方法，如果您有兴趣的话，可以跟@hengyunabc 讨论下。

我看你们源码有啊 为什么不开放啊
<img width="451" alt="image" src="https://user-images.githubusercontent.com/6212847/160868104-53d187be-f7bd-4168-ba58-c3546252579e.png">

**Comment by dragon-zhang** [comment]
现在`sumInstanceSize`没有对类实例做限制，一下子会把指定类的所有实例取出来，这是比较损耗性能的(比如传个`Object`，一次性把`几百万`的实例取出来)。

**Comment by dragon-zhang** [comment]
> > 是的，现在command里应该只封装了`getInstance`和`forceGC` 2个方法，如果您有兴趣的话，可以跟@hengyunabc 讨论下。
> 
> 我看你们源码有啊 为什么不开放啊 <img alt="image" width="451" src="https://user-images.githubusercontent.com/6212847/160868104-53d187be-f7bd-4168-ba58-c3546252579e.png">

具体原因，还是@hengyunabc 来解释下，其实从`3.5.1`开始，`sumInstanceSize`底层就实现了的。

**Comment by dragon-zhang** [comment]
> 现在`sumInstanceSize`没有对类实例做限制，一下子会把指定类的`所有实例`取出来，这是比较损耗性能的(比如传个`Object`，一次性把`几百万`的实例取出来)。

个人观点

**Comment by GentleSong** [comment]
> > > 是的，现在command里应该只封装了`getInstance`和`forceGC` 2个方法，如果您有兴趣的话，可以跟@hengyunabc 讨论下。
> > 
> > 
> > 我看你们源码有啊 为什么不开放啊 <img alt="image" width="451" src="https://user-images.githubusercontent.com/6212847/160868104-53d187be-f7bd-4168-ba58-c3546252579e.png">
> 
> 具体原因，还是@hengyunabc 来解释下，其实从`3.5.1`开始，`sumInstanceSize`底层就实现了的。

好的 谢谢 ！ 我看底层在 jni-library.cpp 都写了 但是没对外开放

**Comment by hengyunabc** [comment]
> sumInstanceSize

这个太容易误用了，容易出事，所以不开放。如果还是要调用这个，可以用 ognl表达式。
