### ISSUE TITLE
Both Arthas and the container stopped running

### ISSUE THREAD

**Issue by myesn** [alibaba/arthas#2142]
- [X] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.6.0
* Operating System version: Alpine Linux 3.9.4 (`openjdk:8-jdk-alpine` image)
* Java version of target JVM: 1.8.0_212 (`openjdk:8-jdk-alpine` image)
* Java version of JVM used to attach: 1.8.0_212 (`openjdk:8-jdk-alpine` image)

### Steps to reproduce this issue

Here is part of my Dockerfile:

```Dockerfile
FROM openjdk:8-jdk-alpine

COPY --from=hengyunabc/arthas:latest /opt/arthas /opt/arthas

...
```

1. Build an image and start the container based on that image.
2. Go inside the container and start arthas.
3. Follow the prompts to enter 1 and press Enter,
4. The java program exits and the container stops running.

### Expected Result

1. Java programs within the container do not exit.
2. Make arthas works, thanks.

### Actual Result

```
ubuntu@ubuntu:~/shenyu/shenyu-master$ docker-compose exec shenyu-admin sh
/opt/shenyu-admin # java -jar /opt/arthas/arthas-boot.jar
[INFO] arthas-boot version: 3.6.0
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 34 org.apache.shenyu.admin.ShenyuAdminBootstrap
1
[INFO] arthas home: /opt/arthas
[INFO] Try to attach process 34
ubuntu@ubuntu:~/shenyu/shenyu-master$ docker-compose ps
      Name                    Command                  State                        Ports
-----------------------------------------------------------------------------------------------------------
shenyu-admin       /bin/sh entrypoint.sh            Exit 131
```

**Comment by hengyunabc** [comment]
jvm进程可能crash了，检查下容器具体日志。
