### ISSUE TITLE
无法执行生成火焰图

### ISSUE THREAD

**Issue by zwb993** [alibaba/arthas#2143]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.0
* Arthas 版本:  3.6.0
* 操作系统版本:  CentOS Linux release 7.9.2009
* 目标进程的JVM版本: 8
* 执行`arthas-boot`的版本: 8

### 重现问题的步骤

1. profiler start

### 期望的结果

可以执行

### 实际运行的结果

报错了

实际运行结果：

```
AsyncProfiler error: /tmp/ArthasJniLibrary549953581832185186.tmp: /tmp/ArthasJniLibrary549953581832185186.tmp: failed to map segment from shared object: Operation not permitted
```

**Comment by hengyunabc** [comment]
可能要到原项目提issue: https://github.com/jvm-profiling-tools/async-profiler

**Comment by Daydreamer-ia** [comment]
hi, 我遇到一样的问题，请问你怎么解决的呢？

**Comment by SnipeSword** [comment]
请问如何解决的？

**Comment by 243300852** [comment]
请问如何解决的

**Comment by 243300852** [comment]
1. 检查并修改 /tmp 目录挂载选项
Arthas 默认会将其 JNI 库提取到 /tmp 目录。如果 /tmp 目录被挂载为 noexec（禁止执行），就会导致此问题。

检查 /tmp 挂载选项：
在终端执行：

bash
mount | grep /tmp
如果输出中包含 noexec，例如 rw,noexec,nosuid,nodev，则这就是问题所在。

重新挂载 /tmp 目录（临时生效，重启后失效）：

bash
sudo mount -o remount,exec /tmp
注意：这可能会降低系统安全性，因为任何用户都可以在 /tmp 执行文件。操作后请尝试再次启动 Arthas。

为 Arthas 设置其他临时目录（更安全推荐）：
如果不想修改 /tmp 的挂载选项，可以为当前终端会话指定一个新的临时目录：

bash
export TMPDIR=/your/custom/tmp/dir  # 设置为一个用户有读写执行权限的目录
mkdir -p $TMPDIR
java -jar arthas-boot.jar
这样 Arthas 会使用 $TMPDIR 来存放临时库文件。

2. 检查文件和目录权限
确保当前用户对 Arthas 生成的临时 JNI 库文件及其所在目录有读、写、执行权限。

检查 /tmp 目录的权限通常是 drwxrwxrwt。

检查 Arthas 临时文件（如 /tmp/ArthasJniLibrary*.tmp）的权限。确保它们有执行权限 (x)。如果有问题，可以尝试：

bash
chmod +x /tmp/ArthasJniLibrary*.tmp
但请注意，每次启动 Arthas 生成的临时文件名不同，此方法可能更适用于一次性的情况。根本解决还需依赖上述修改挂载选项或设置 TMPDIR。

3. 清理临时文件并重试
有时旧的、损坏的临时文件也可能引发冲突。尝试手动清理 /tmp 目录下与 Arthas 相关的旧临时文件后重启 Arthas：

bash
rm -f /tmp/ArthasJniLibrary*.tmp
rm -f /tmp/arthas-*
