### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jmilktea** [alibaba/arthas#2149]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.5.0

### 重现问题的步骤
如下执行语句：
ognl -c 49c2faae '#context=@com.my.util.ApplicationContextUtils@getContext(),#context.getBean("redisTemplate").opsForHash().size("abc")'
会报错：
Failed to execute ognl, exception message: java.lang.ArrayIndexOutOfBoundsException: 2, please check $HOME/logs/arthas/arthas.log for more details
如果换成：
'#context=@com.my.util.ApplicationContextUtils@getContext(),#context.getBean("redisTemplate").opsForList().size("abc")'
就是正常的，其它数据类型都是正常的。hash opsForHash()所有执行方法都会报错，如opsForHash().size("abc")，opsForHash().keys("abc")
### 期望的结果
能返回结果

### 实际运行的结果
```
Failed to execute ognl, exception message: java.lang.ArrayIndexOutOfBoundsException: 2, please check $HOME/logs/arthas/arthas.log for more details
```

**Comment by LY1806620741** [comment]
that look like ognl's error. I use old version `3.0.6` has the same problem. but ognl 3.3.3 solve it.

**Comment by jmilktea** [comment]
How to check the version of ognl in arthas, whether upgrading the version of ognl needs to upgrade the version of arthas
@LY1806620741

**Comment by hengyunabc** [comment]
arthas使用旧版本的ognl，主要是为了支持 jdk6。

**Comment by LY1806620741** [comment]
@jmilktea 我只是指出ognl老版本在匹配重载方法的时候可能会报这个错误，你可以试试自己编译升级一下，可能会解决这个问题，我没有在arthas中更新过ognl。
The old version of ognl may report this error when matching overloaded methods. You can try compiling and upgrading yourself, which may solve this problem. I haven't updated ognl in Arthas.(From Baidu Translate )
