### ISSUE TITLE
No need to download the remote in local debug

### ISSUE THREAD

**Issue by Hearen** [alibaba/arthas#216]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.5.2018101114330
* Operating System version: ubuntu 16.04
* Java version of target JVM: jdk1.8.0_144
* Java version of JVM used to attach: jdk1.8.0_144

### Steps to reproduce this issue
```
$ rm -rf ~/.arthas/lib/*
$ ./as-package.sh 

$ bin/as.sh

# select any java progress
```
### Expected Result

Arthas will just use the latest local version to boot the server. 

### Actual Result

Arthas will download the remote version first and then boot the server with the latest version.

**Comment by Hearen** [comment]
@ralf0131 @hengyunabc It's silly to me to download the `remote` while I am trying to debug local. 

I am planning to move the `get_remote` after the `check_local`. 

Unless the `check_local` failed, try to `get_remote`. 

Sounds good?

**Comment by hengyunabc** [comment]
@Hearen  I will process this in #130 .
