### ISSUE TITLE
Arthas redefine command invalid after using Skywalking Agent

### ISSUE THREAD

**Issue by malversation** [alibaba/arthas#2183]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.1
* Arthas 版本:3 .5.1
* 操作系统版本: linux
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: jdk1.8

### 重现问题的步骤

1. 使用skywalking agent后，arthas redefine命令执行成功，但是jvm中class没有变化

Skywalking OAP Server Version: 9.0.0
Skywalking Agent Version: 8.10.0

### 期望的结果

期望redefine命令有效

### 实际运行的结果

![1653009290(1)](https://user-images.githubusercontent.com/26448842/169429174-722e69d6-367d-43db-b472-49bb0cf82bd9.png)

```
把异常信息贴到这里
```
无异常信息

**Comment by hengyunabc** [comment]
用最新版本，用这个： https://arthas.aliyun.com/doc/retransform

**Comment by malversation** [comment]
> 用最新版本，用这个： https://arthas.aliyun.com/doc/retransform

使用Skywalking agent后一个类在jvm中会被生成多个带$**的类，使用这个命令重新加载，确定类可以生效吗？如果生效，那么skywalking agent还起作用吗？谢谢。

**Comment by malversation** [comment]
> 用最新版本，用这个： https://arthas.aliyun.com/doc/retransform

命令执行报错了
![image](https://user-images.githubusercontent.com/26448842/169726561-a8dc78f1-cf2e-4ac3-9be5-3b9757793501.png)

**Comment by malversation** [comment]
> 用最新版本，用这个： https://arthas.aliyun.com/doc/retransform

![image](https://user-images.githubusercontent.com/26448842/169726670-77a95494-22b5-4fd4-9226-591394ee95b2.png)
使用Skywalking agent后一个类会生成多个

**Comment by wangkang4** [comment]
大佬  我也遇到这个问题了  请问这个问题你是如何解决的
