### ISSUE TITLE
如果用appClassLoader启动arthas会有什么影响

### ISSUE THREAD

**Issue by zinking** [alibaba/arthas#2184]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.6.1
* 操作系统版本: linux 3.10
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤
某些特殊的trace情况下， 将Arthas随程序一起启动在线上观测依赖的一些情况， 直接用appClassLoader构造了arthas这种情况有什么问题么？

具体的场景是把arthas嵌入在zeppelin之类的笔记本， 手动启动

这块的Arthas加载应该怎么处理？

**Comment by hengyunabc** [comment]
arthas本身打包了不少依赖，容易和应用自身的依赖冲突。不确定什么时候就出问题了。

**Comment by zinking** [comment]
谢谢断岭恢复
遇到一些类没有发现的情况， arthas对要增强的类的加载class loader是不是有什么要求
