### ISSUE TITLE
arthas 依赖的fastjson存在安全漏洞

### ISSUE THREAD

**Issue by SAM2O2O** [alibaba/arthas#2191]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 重现问题的步骤

1. 安全漏洞问题：https://github.com/alibaba/fastjson/wiki/security_update_20220523

### 期望的结果

能过修复其中使用的fastjson漏洞

**Comment by hengyunabc** [comment]
master分支已经升到1.2.83了。
