### ISSUE TITLE
HttpAPI怎样支持跨域访问

### ISSUE THREAD

**Issue by ms143014** [alibaba/arthas#2194]
curl -Ss -XPOST http://localhost:8563/api -d '
{
  "action":"exec",
  "command":"version"
}
'
我想在浏览器用js xhr访问，如果访问的是其它ip，则会报跨域问题。

**Comment by hengyunabc** [comment]
这个应该是浏览器的问题，可以试下本地加一层代理。通常的web开发对接后端时，都会自己本地搭一个统一代理。
