### ISSUE TITLE
Could not find or load main class com.taobao.arthas.boot.Bootstrap

### ISSUE THREAD

**Issue by kgdngitfk** [alibaba/arthas#2200]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.6.2
* 操作系统版本: Ubuntu 22.04 LTS
* 目标进程的JVM版本: java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
* 执行`arthas-boot`的版本: 3.6.2

### 重现问题的步骤
切换到另一个用户后
java -jar arthas-boot.jar 
Error: Could not find or load main class com.taobao.arthas.boot.Bootstrap

### 期望的结果
能正常运行，在切换后的用户shell环境中java, javac，jps命令都是可以正常执行的

### 实际运行的结果

Error: Could not find or load main class com.taobao.arthas.boot.Bootstrap

```
Error: Could not find or load main class com.taobao.arthas.boot.Bootstrap
```

**Comment by hengyunabc** [comment]
可能是另一个用户没权限读到 某些文件。 

或者试下用 as.sh， `bash -x ./as.sh` 看具体哪一行执行失败。

**Comment by kgdngitfk** [comment]
> 可能是另一个用户没权限读到 某些文件。
> 
> 或者试下用 as.sh， `bash -x ./as.sh` 看具体哪一行执行失败。
已经解决了，确实如此，使用了一个无法shell登录，且没有家目录的用户启动了arthas,报的错误却是找不到类，通过.as脚本启动就提示了正确的信息，没有目录，创建目录后就好了
