### ISSUE TITLE
阿里开源的jdk特性wisp不支持thread操作,麻烦兼容下呗

### ISSUE THREAD

**Issue by r67yfyt** [alibaba/arthas#2203]
如题

**Comment by r67yfyt** [comment]
dragonwell11版本

**Comment by hengyunabc** [comment]
这个估计有难度。因为wisp有自己的api，在arthas不合适引用特定平台/发行版 专有的API。 可以试下用 `ognl`命令执行下wisp api。

**Comment by zhengb0** [comment]
您好，您的信件已经收到，会尽快回复您的，谢谢。
