### ISSUE TITLE
Katacoda关闭以后是不是没法尝试在线教程了

### ISSUE THREAD

**Issue by CuriousRookie** [alibaba/arthas#2204]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的 issue。

### 环境信息

1. 浏览器 Microsoft Edge 102.0.1245.41 (正式版本) (64 位)

### 重现问题的步骤

1. 打开 [https://arthas.aliyun.com/doc/arthas-tutorials.html?language=cn](https://arthas.aliyun.com/doc/arthas-tutorials.html?language=cn) 在线教程

### 期望的结果

能根据提示正常操作

### 实际运行的结果

无法交互

[https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html)

大概就是 Katacoda 网站要关闭不再公开了，所以 arthas 的在线教程也没法用了？

**Comment by hengyunabc** [comment]
😭，试了下，的确不可用了。Katacoda的确很容易被各种利用。

可以试下阿里云上的在线教程，可能不是很完整： https://start.aliyun.com/handson-lab?category=arthas

**Comment by shalk** [comment]
阿里云上的在线教程 貌似也不行了。。。
