### ISSUE TITLE
windows11 java.lang.IllegalArgumentException: telnet: command not found

### ISSUE THREAD

**Issue by a364176773** [alibaba/arthas#2208]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.2
* Arthas 版本: 3.6.2
* 操作系统版本: windows11
* 目标进程的JVM版本: jdk8
* 执行`arthas-boot`的版本: 3.6.2
windows11 确认是安装了telnet,通过控制面板已经启用
### 重现问题的步骤

1. java -jar .\arthas-boot.jar
2. java -jar .\arthas-boot.jar 启动另一个
3. 在第二个中telnet localhost 3658

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
[arthas@6912]$ telnet 127.0.0.1 3658
java.lang.IllegalArgumentException: telnet: command not found
[arthas@6912]$ telnet localhost 3658
java.lang.IllegalArgumentException: telnet: command not found
```

**Comment by hengyunabc** [comment]
`[arthas@6912]$ telnet 127.0.0.1 3658`  这里是在 arthas shell里执行命令了。。  不是在系统的shell里执行的。
