### ISSUE TITLE
/proc/xx/status和 dashboard 查出来的结果 gap 太大

### ISSUE THREAD

**Issue by jundaodao** [alibaba/arthas#2223]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: arthas-all-3.6.3
* 操作系统版本: Linux 4.15.0-54-generic x86_64
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: curl -O https://arthas.aliyun.com/arthas-boot.jar 下载下来的

### 重现问题的步骤

1. cat /proc/6/status
查出来
VmHWM:   8951500 kB
VmRSS:   8951500 kB

2. 通过 arthas 的 dashboard 命令查出来结果
Memory                                     used          total             max           usage        GC                                                                                      
heap                                          2345M      7505M        7505M       31.26%       gc.ps_scavenge.count                           247                                         
ps_eden_space                         759M        1631M         1733M       43.82%       gc.ps_scavenge.time(ms)                     15505                                       
ps_survivor_space                    411M         412M          412M          99.89%       gc.ps_marksweep.count                       5                                           
ps_old_gen                                1174M       5461M        5461M       21.51%        gc.ps_marksweep.time(ms)                  1932                                        
nonheap                                    162M        166M          -1                97.46% 

### 期望的结果
期望能直接通多 dashboard 看到的就是进程实际使用的内存VmRSS。
或者 dashboard 上面那些数据加起来能构成/proc/xx/status 查询出来的VmRSS

### 实际运行的结果
没有报错，就是/proc/xx/status 取到的真实内存和 dashboard 获取的堆内存 gap 太大导致。

```
把异常信息贴到这里
<img width="707" alt="image" src="https://user-images.githubusercontent.com/43141311/179683395-1c1c0162-d269-4698-88ee-aed35a477685.png">

```

**Comment by jundaodao** [comment]
找到 gap 的原因了，两者取数逻辑不一致。jdk 只能监控自身垃圾回收器的内存，对于堆外内存是无法统计的。

**Comment by astilt322** [comment]
要看total，不是used。
