### ISSUE TITLE
注入Arthas时有打印Thread Dump信息

### ISSUE THREAD

**Issue by blareck** [alibaba/arthas#2225]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.6.0
* 操作系统版本: centos7.5
* 目标进程的JVM版本: jdk8

### 重现问题的步骤

1. 启动tomcat8.5
2.注入内存马防御工具
3. 启动Arthas

### 期望的结果

tomcat管理后台正常打印业务信息

### 实际运行的结果

Tomcat后台有打印Thread Dump，由于涉及到业务敏感原因，无法贴出Dump信息。
经过测试在有过其他 Attach注入行为后，再注入Arthas检测，Tomcat都有打印Thread Dump信息，请问这种情况如何避免呢？

**Comment by hengyunabc** [comment]
具体还是要看哪里打印的日志。参考下这个： https://blog.csdn.net/hengyunabc/article/details/83593182
