### ISSUE TITLE
新版文档中的 star/fork 数量不正确

### ISSUE THREAD

**Issue by drtrang** [alibaba/arthas#2235]
![2022-08-03 10 55 55](https://user-images.githubusercontent.com/13851701/182514453-63269322-39b0-44b0-a22d-b0b186be3f33.gif)

如图，文档中的 star/fork 数量无限上涨，非必现，但刷新页面时大概率复现

**Comment by hengyunabc** [comment]
@Fatpandac 麻烦看下这个

**Comment by Fatpandac** [comment]
> @Fatpandac 麻烦看下这个

👌
