### ISSUE TITLE
是否能支持idea java reference表达式，例如 com.xxx.XXXClass#methodName

### ISSUE THREAD

**Issue by LY1806620741** [alibaba/arthas#2240]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 期望的结果

在`watch` \ `tt` 实际使用中我认为这样的表达式更为方便，直接在idea中ctrl+alt+shift+c就可以获取方法信息，
当没有重载时是这样的`com.xxx.XXXClass#methodName`,
当有重载时会加上参数信息`com.xxx.XXXClass#methodName(long, java.lang.String, java.util.Map<java.lang.String,java.lang.String>)`

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/81
