### ISSUE TITLE
关于jps -l 和 jps -ml

### ISSUE THREAD

**Issue by PlayerOnly** [alibaba/arthas#2241]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.6.2
* 操作系统版本: xxx
* 目标进程的JVM版本: 1.7
* 执行`arthas-boot`的版本: xxx

### 期望的结果
加入jps -ml 选项，输出启动类和main方法参数

### 实际运行的结果
Map<Long, String> com.taobao.arthas.boot.ProcessUtils.listProcessByJps(boolean v)
        if (v) {
            command = new String[] { jps, "-v", "-l" };
        } else {
            command = new String[] { jps, "-l" };
        }

jps -v -l 参数太长，jps -l太过于精简，可否加入jps -ml 选项呢，实际生产环境中可能出现相同启动类但参数不同的情况
目前使用的是jps -l
只输出了主类的全名
```
把异常信息贴到这里
Map<Long, String> com.taobao.arthas.boot.ProcessUtils.listProcessByJps(boolean v)

**Comment by hengyunabc** [comment]
好像很少有这个需求，把args打印出来，显示会很长。为一个很少的需求单独增加一个选项好像不值得。
