### ISSUE TITLE
arthas全量包版本有问题

### ISSUE THREAD

**Issue by imguang** [alibaba/arthas#2253]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 重现问题的步骤

1. 从官网下载最新的离线包：
https://arthas.aliyun.com/doc/install-detail.html#%E4%BD%BF%E7%94%A8as-sh
![image](https://user-images.githubusercontent.com/12031110/185086758-07c712e3-f498-4718-bda8-7ec109eeb9f8.png)

发现包内修改日期有问题：
![image](https://user-images.githubusercontent.com/12031110/185086857-1e5d7feb-20a8-4182-b6f0-602f6f757fb5.png)

在服务器上运行后，发现版本也有问题：
![image](https://user-images.githubusercontent.com/12031110/185086977-56c71031-7296-4b17-a49e-4ec39e0a7445.png)

2. 从https://github.com/alibaba/arthas/releases 中下载，也都是旧的版本

### 期望的结果

可以下载到最新的arthas离线包

**Comment by hengyunabc** [comment]
显示的修改日期的确不对，这个还要看下原因。但文件是新的，可以看下 as.sh 里的内容，里面有日期。

另外服务器上显示是 3.5.2，这个可以连上去执行 stop之后，再重新 attach。可能是以前有人用旧版本attach过。

**Comment by imguang** [comment]
> 显示的修改日期的确不对，这个还要看下原因。但文件是新的，可以看下 as.sh 里的内容，里面有日期。
> 
> 另外服务器上显示是 3.5.2，这个可以连上去执行 stop之后，再重新 attach。可能是以前有人用旧版本attach过。

嗯，确实是没有stop。包没有问题，不好意思。
