### ISSUE TITLE
macos 无法退出 dashboard 界面

### ISSUE THREAD

**Issue by Cocowwy** [alibaba/arthas#2256]
### 环境信息

![image](https://user-images.githubusercontent.com/63331147/186135336-96d2f629-dc18-4788-9f52-49d49df32382.png)

### 重现问题的步骤

在dashboard界面使用command无法退出 

### 期望的结果
正常退出dashboard

**Comment by hengyunabc** [comment]
`ctrl +c ` 或者输入`q` 。
