### ISSUE TITLE
是否存在Arthas的transformer会remove失败的场景

### ISSUE THREAD

**Issue by zjutkz** [alibaba/arthas#2257]
最近在研究Arthas源码的时候想到一个问题，操作步骤：

1. 在一个运行的程序中启动Arthas，并执行watch/trace等需要transform class的命令。
2. 这个时候外部又有一个其他的JavaAgent attach上来，并且自己也有一个transform的动作，做完之后会导致Instrumentation的retransformClasses失败。
3. Arthas使用完毕，ctrl+C退出watch/trace，这个时候根据源码，会调用TransformerManager的remove方法将对应命令的transformer删除掉.
4. exit退出Arthas，这个时候会重新调用一遍Instrumentation的retransformClasses方法做增强类的重置。

根据以上步骤，因为在步骤二中已经会导致retransformClasses失败，所以步骤四的重置也就失败了，这种情况下，是不是就会导致Arthas的重置增强类失效呢？这样就会让Arthas的增强效果一直保留，直到下一次retransformClasses成功，会不会有安全以及性能等问题呢？

**Comment by hengyunabc** [comment]
jvm只是顺序回调各个transformer。 单个transformer是否成功，不影响是否调下一个transformer，影响的是传给下一个transformer的 byte[]。

所谓重置增强类，本质上是arthas的transformer已经删掉了，没有对 byte[] 增强的过程了。不会出现重置失败。
