### ISSUE TITLE
中文

### ISSUE THREAD

**Issue by mtz1992** [alibaba/arthas#2265]
您好,请问,就比如我想查看这个函数,
watch com.xiaomi.data.recommend.recaller.BaseRecaller function '{params[2]. requestContext}' 'params[2].rec_type.equals("中文")' -n 1 -x 2
这里输入"中文"总是乱码且查不出什么内容来
那我应该怎样输入呢

**Comment by hengyunabc** [comment]
前一个issue回复文档了： `ognl '@java.lang.System@out.println("Hello \u4e2d\u6587")'`

用 `\u`的方式，搜索下 java unicode字符表示 相关的。
