### ISSUE TITLE
docker公共镜像最新版本是arm64的？为啥不是amd64?

### ISSUE THREAD

**Issue by nickfan** [alibaba/arthas#2267]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

![image](https://user-images.githubusercontent.com/100613/187329153-f4ac26e6-2da7-4b69-b1e8-e9962f9af160.png)

https://hub.docker.com/r/hengyunabc/arthas/tags

### 期望的结果

最新的amd64的版本还停留在3.6.2，不得不指定版本使用

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by nickfan** [comment]
相信大部分人员的服务器还没进化到用arm的server,难道人人都用mac m1?

**Comment by hengyunabc** [comment]
不好意思，我的锅，最近换了构建环境。 重新push了，现在支持 arm64和 amd64 了。

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/1683936/187352995-02d4b854-6f6f-4512-8622-239ae97efbbf.png">
