### ISSUE TITLE
通过arthas获得bean的属性

### ISSUE THREAD

**Issue by badBoy-art** [alibaba/arthas#2268]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 的版本： 3.5.6
* Arthas 版本: xxx
* 操作系统版本: linux
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.5.6

### 重现问题的步骤

1. `ognl -c 7357a011 '#context=@com.***.SpringContextHolder@applicationContext,#context.getBean("controller").env'`
2. 
```
    @Value("${DEPLOY_ENV}")
     private String env;
```
### 期望的结果
`@String[boe]`
### 实际运行的结果
null
###

当env有get方法时，通过上边的ognl就可以获得期望的结果

**Comment by hengyunabc** [comment]
参考这个： https://github.com/hengyunabc/spring-boot-inside/tree/master/demo-Transactional-NullPointerException

spring aop生成的对象 field 就是可能是 null 。

**Comment by funnylog** [comment]
这个该直接获取静态环境变量
