### ISSUE TITLE
方法不执行完毕不打印日志会误导人以为请求没有进来

### ISSUE THREAD

**Issue by zhaoyuasd** [alibaba/arthas#2272]
目前遇到一个问题，用trace、或者 stack 去监听方法的时候，始终不打印日志，但是用watch -b 会打印参数，所以我这边有个疑问 trace和watch是不是 非要等监听的方法 返回后 才打印日志，可不可以 执行一行方法 打印一行，不然总以为是 请求没有进来，就去排查别的问题了，但是实际上请求已经进来，只不过到了某一行执行不下去了

**Comment by hengyunabc** [comment]
trace , watch都有一个 -v 参数，可以在进入时就打印信息。
