### ISSUE TITLE
watch - cost 耗时条件筛选无效

### ISSUE THREAD

**Issue by elitegrey** [alibaba/arthas#2275]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.5
* Arthas 版本: 3.3.2

### 重现问题的步骤

1. curl -O https://arthas.aliyun.com/math-game.jar
2. java -jar math-game.jar
3. watch demo.MathGame run '#cost > 10'

![image](https://user-images.githubusercontent.com/112773505/188281249-b72061a8-bb23-4938-b28e-74ed1506d1d2.png)

### 期望的结果

What do you expected from the above steps？
获取耗时超过10ms的执行

### 实际运行的结果
耗时过滤没生效

**Comment by hengyunabc** [comment]
仔细看文档，这个参数是 结果表达式，后面的才是条件表达式。可以试下加上 -v 参数。

`watch demo.MathGame run  params   '#cost > 10'`
