### ISSUE TITLE
quit或者exit命令

### ISSUE THREAD

**Issue by QiuZiXian** [alibaba/arthas#2287]
3.6.6版本
使用quit或者exit，暂时退出，怎么重连
没有持续连接。

java -jar arthas-boot.jar
仍然可以运行。
但是无法监控对应程序，会报错如下
[ERROR] The telnet port 3658 is used by process 26082 instead of target process 45852, you will connect to an unexpected process.
[ERROR] 1. Try to restart arthas-boot, select process 26082, shutdown it first with running the 'stop' command.
[ERROR] 2. Or try to stop the existing arthas instance: java -jar arthas-client.jar 127.0.0.1 3658 -c "stop"
[ERROR] 3. Or try to use different telnet port, for example: java -jar arthas-boot.jar --telnet-port 9998 --http-port -1

arthas-client.jar又是啥。

希望quit或者exit的attach有更好的提示

**Comment by hengyunabc** [comment]
`[ERROR] 1. Try to restart arthas-boot, select process 26082, shutdown it first with running the 'stop' command.`

这个提示就很清楚。
