### ISSUE TITLE
去掉com.taobao.arthas.core.Arthas里反射调用 com.sun.tools.attach.VirtualMachine 的代码，改为直接调用

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#23]
`com.taobao.arthas.core.Arthas` 

增加一个依赖，因为里面带有`com.sun.tools.attach.VirtualMachine` api，打包 fat jar时，并不会打进去，只是编绎用：

```xml
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-javaagent</artifactId>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>
```

不使用`tools.jar`，是因为jdk9之后没有这个jar包了。

**Comment by ted-wq-x** [comment]
这个api没用，在debug的时候还是需要引入tools.jar。虽然jdk9之后没有这个jar，但是依然有VirtualMachine这个api，我觉得只要在开发文档中注明就好，所以删除这个jar好点。

**Comment by hengyunabc** [comment]
jdk8编绎引用tools.jar 要引入 maven system path ，然后在jdk8以上，又要去掉，需要maven profiles配置。
我再考虑下，debug时用到 VirtualMachine 是很少的。
