### ISSUE TITLE
[Question]程序包java.lang.invoke不存在

### ISSUE THREAD

**Issue by leopardrota** [alibaba/arthas#2310]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 源码master分支
* 操作系统版本: win7 32位
* JVM版本: jdk9

### 重现问题的步骤

1. 源码运行com.taobao.arthas.boot.Bootstrap#main()

### 期望的结果

运行成功

### 实际运行的结果

运行失败，报错：找不到java的包

![image](https://user-images.githubusercontent.com/55968645/195979052-c7655ded-23a1-4598-8b93-897db7cd9c59.png)

### 疑问
idea会提示修改language level（因为像java.lang.invoke.MethodHandles确实是从jdk1.7开始的）
![1665825643988](https://user-images.githubusercontent.com/55968645/195979077-cbd84a8d-f178-472f-90f4-626a937e2001.png)
按提示操作后，就会自动修改pom文件中maven编译插件的配置
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <source>1.6改成了7</source>
        <target>1.6改成了7</target>
        <encoding>UTF-8</encoding>
        <showDeprecation>true</showDeprecation>
    </configuration>
</plugin>
```

**这种情况是属于源码pom文件的bug？还是我开发环境配置哪里有欠缺导致？**

**Comment by hengyunabc** [comment]
看 https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md 

这是一个常见的编程技巧，代码编译时要用 jdk8，生成的字节码格式是 1.6的。这个代码可以同时在jdk6/jdk8下执行。 只不过在 jdk8下面有些执行路径是jdk8的代码。
