### ISSUE TITLE
2022 Arthas社区征文章/视频/资料活动开启！

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#2317]
## 投稿地址

现在知识传播方式非常丰富，希望大家可以用自己擅长的方式创作Arthas相关作品。 可以是文章/视频/资料（比如思维导图等）。

* http://arthas-open.mikecrm.com/IqTcXyG

## 奖品说明

获奖同学将获得 Arthas 社区背包（总量100个）。

![001](https://user-images.githubusercontent.com/1683936/196685418-7fd4ead8-2345-40dd-9ab8-3d4e1c515a2e.JPG)
![002](https://user-images.githubusercontent.com/1683936/196685430-fe2efa63-7c82-4f9e-b773-883876d88af6.JPG)

## 投稿作品要求

* 作品层次结构及逻辑清晰且必须是原创；
* 禁止发布广告类内容信息；
* 禁止发布涉政、暴恐、违禁等敏感内容。

## 内容建议

* 使用 Arthas 排查过的问题
    可以将你使用 Arthas 排查的问题整理成一篇文章，分享你在排查问题中的得到的经验与思考，为更多的开发者提供一份“避坑指南”；
* 对 Arthas 进行源码解读
    你可以找几个最感兴趣的功能点切入，从源码来分析设计与实现原理，然后整理成稿投稿给我们，基于对 Arthas 的源码解读来和众多开发者们“隔空对话”，来一场思想上的碰撞；
* 对 Arthas 提出建议
    如果你希望能够更多地参与到 Arthas 社区中来，可以提出你对 Arthas 的建议或者说出你对 Arthas 未来的期待并将其整理成文；
* 不限，其它与 Arthas 有关的内容
    例如，你是如何接触到 Arthas 的？你会选择把 Arthas 推荐给更多的开发者吗？或者只是简单记录一次 Arthas 的使用实践等等均可。

## 特别说明

* Arthas比较缺少英文相关的分享，欢迎大家创作英文相关作品
* 优秀作品作者将获得 arthas cherry 定制键盘（总量10个）

## 往期优秀征文参考

* [是谁在调用我？使用arthas+jprofiler做复杂链路分析](https://mp.weixin.qq.com/s/RUKof-bYwzuPIQ2I8NKJXQ)
* [Arthas实践: 定位修复Redisson连接池问题](https://mp.weixin.qq.com/s/iXiz-5wZC2zZ56H2phk9MQ)
* [Arthas实践：解决由于druid版本造成的慢sql问题](https://mp.weixin.qq.com/s/1c7w5BfNllTwfB8Bf1R1hw)

**Comment by benjijun** [comment]
出于对arthas实现的好奇，自己录制的源码分析视频: https://space.bilibili.com/1010796812/channel/seriesdetail?sid=2865687
基于最新版本：3.6.7, 主要分析了
1. 流程启动过程
2. 命令的执行过程 包括建立链接 命令处理 结果输出
3. 常用命令的分析 包括thread trace(字节码增长+内存目录树) monitor等 
希望对想了解arthas的人有点帮助
