### ISSUE TITLE
本地编辑arthas项目报错

### ISSUE THREAD

**Issue by spilledyear** [alibaba/arthas#2333]
我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
本地java环境 1.8
![image](https://user-images.githubusercontent.com/24663965/199898168-f67d404a-53e1-479e-b205-f219f1ed8815.png)

### 问题
在IDEA中 执行   **mvn clean package -DskipTests -P full**   报错

[ERROR] /Users/admin/workspace/arthas/core/src/main/java/com/taobao/arthas/core/command/basic1000/JFRCommand.java:[14,1] 程序包jdk.jfr不存在

![image](https://user-images.githubusercontent.com/24663965/199898456-67b80bf3-1f8e-43b7-bc0c-7737dc705140.png)

![image](https://user-images.githubusercontent.com/24663965/199898013-437e608e-801f-4c19-9ae6-942c8c07e69c.png)

**Comment by hengyunabc** [comment]
使用最新版本的 jdk8 或者使用 jdk11 。

**Comment by spilledyear** [comment]
> 使用最新版本的 jdk8 或者使用 jdk11 。

我将jdk更新到 JDK 8u351 还是报一样的错，提示 jfr.jdk.xx 找不到；

如果将jdk更新到11， 则报错 javah 命令不存在

**Comment by spilledyear** [comment]
> 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
> 
> ### 环境信息
> 本地java环境 1.8 ![image](https://user-images.githubusercontent.com/24663965/199898168-f67d404a-53e1-479e-b205-f219f1ed8815.png)
> 
> ### 问题
> 在IDEA中 执行 **mvn clean package -DskipTests -P full** 报错
> 
> [ERROR] /Users/admin/workspace/arthas/core/src/main/java/com/taobao/arthas/core/command/basic1000/JFRCommand.java:[14,1] 程序包jdk.jfr不存在
> 
> ![image](https://user-images.githubusercontent.com/24663965/199898456-67b80bf3-1f8e-43b7-bc0c-7737dc705140.png)
> 
> ![image](https://user-images.githubusercontent.com/24663965/199898013-437e608e-801f-4c19-9ae6-942c8c07e69c.png)

JfrCommadn 是3.6.5 开始支持的，这个应该是依赖 java8+

**Comment by hengyunabc** [comment]
用高版本 jdk8是肯定可以的，github action 三个平台都用jdk8编译： https://github.com/alibaba/arthas/blob/master/.github/workflows/build-vmtool.yaml

**Comment by leopardrota** [comment]
> 用高版本 jdk8是肯定可以的，github action 三个平台都用jdk8编译： https://github.com/alibaba/arthas/blob/master/.github/workflows/build-vmtool.yaml

https://github.com/alibaba/arthas/blob/537209a4ee1f52eb26c9d5789cdae6f2fe0b003b/.github/workflows/build-vmtool.yaml#L1
https://github.com/alibaba/arthas/blob/537209a4ee1f52eb26c9d5789cdae6f2fe0b003b/.github/workflows/build-vmtool.yaml#L21
https://github.com/alibaba/arthas/blob/537209a4ee1f52eb26c9d5789cdae6f2fe0b003b/.github/workflows/build-vmtool.yaml#L38
https://github.com/alibaba/arthas/blob/537209a4ee1f52eb26c9d5789cdae6f2fe0b003b/.github/workflows/build-vmtool.yaml#L55
这些是不是只针对arthas-vmtool编译？那确实没问题，但是编译不了arthas-core。

**Comment by leopardrota** [comment]
> > 使用最新版本的 jdk8 或者使用 jdk11 。
> 
> 我将jdk更新到 JDK 8u351 还是报一样的错，提示 jfr.jdk.xx 找不到；
> 
> 如果将jdk更新到11， 则报错 javah 命令不存在

是的，我也遇到过。虽然[官方](https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#developer)坚持`It is recommended to use JDK8 to compile, and you will encounter problems when using a higher version.`，但是jdk8确实不行，因为jdk.jfr是jdk9引入的。这就导致源码构建不了，而且还是源码中核心部分arthas-core。

javah.exe是从jdk10开始移除的。

所以用jdk9才行。

**Comment by hengyunabc** [comment]
> 这些是不是只针对arthas-vmtool编译？那确实没问题，但是编译不了arthas-core。

。。是整个工程执行`./mvnw package`。 后面的`path`只是收集编译生成的文件。

**Comment by leopardrota** [comment]
是的，虽然[官方](https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#developer)说`It is recommended to use JDK8 to compile, and you will encounter problems when using a higher version.`，但是jdk8确实不行，因为jdk.jfr是jdk9引入的。这就导致源码构建不了，而且还是源码中核心部分arthas-core。

javah.exe是从jdk10开始移除的。

所以用jdk9才行。

**Comment by leopardrota** [comment]
那希望官方能提供下**需要jdk8具体哪个版本或更高版本**才行，Oracle官网jdk8最高版本8u351已经搞不定了。

**Comment by MissingNone** [comment]
可以使用amazon corretto jdk8 352版本
https://github.com/corretto/corretto-8/releases
打包编译使用项目中的as-package.sh，如果中间有什么模块出问题暂时打包不了。将脚本中的36行修改，先排除部分模块的打包。
![image](https://user-images.githubusercontent.com/24592613/200209850-758a2b4c-dd02-4eae-9eb0-a214586355bb.png)
@spilledyear

**Comment by spilledyear** [comment]
@MissingNone

**Comment by hengyunabc** [comment]
更新说明了： https://github.com/alibaba/arthas/commit/221ddd7c5380d7bff2a09816720217558729e7ea

**Comment by spilledyear** [comment]
> 更新说明了： [221ddd7](https://github.com/alibaba/arthas/commit/221ddd7c5380d7bff2a09816720217558729e7ea)
> 
> * 如果遇到jfr相关问题，建议使用`8u262`及之后的高版本 openjdk8 或者zulu jdk8， https://mail.openjdk.org/pipermail/jdk8u-dev/2020-July/012143.html

大佬，能加下你联系方式吗？ 有些问题想请教一下

**Comment by hengyunabc** [comment]
> > 更新说明了： [221ddd7](https://github.com/alibaba/arthas/commit/221ddd7c5380d7bff2a09816720217558729e7ea)
> > 
> > * 如果遇到jfr相关问题，建议使用`8u262`及之后的高版本 openjdk8 或者zulu jdk8， https://mail.openjdk.org/pipermail/jdk8u-dev/2020-July/012143.html
> 
> 大佬，能加下你联系方式吗？ 有些问题想请教一下

加arthas钉钉群，或者qq群，或者在公众号里加。

**Comment by spilledyear** [comment]
> 更新说明了： [221ddd7](https://github.com/alibaba/arthas/commit/221ddd7c5380d7bff2a09816720217558729e7ea)
> 
> * 如果遇到jfr相关问题，建议使用`8u262`及之后的高版本 openjdk8 或者zulu jdk8， https://mail.openjdk.org/pipermail/jdk8u-dev/2020-July/012143.html

这时候其实对 编译时和运行时 JDK版本都有要求吧

**Comment by xhyflowcloud** [comment]
> 更新说明了： [221ddd7](https://github.com/alibaba/arthas/commit/221ddd7c5380d7bff2a09816720217558729e7ea)
> 
> * 如果遇到jfr相关问题，建议使用`8u262`及之后的高版本 openjdk8 或者zulu jdk8， https://mail.openjdk.org/pipermail/jdk8u-dev/2020-July/012143.html

用zuzu可以
