### ISSUE TITLE
com.sun.tools.attach.AgentInitializationException:Agent JAR loaded but agent failed to initialize

### ISSUE THREAD

**Issue by wildfirexie** [alibaba/arthas#2337]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 的版本： 3.6.6
* Arthas 版本: xxx
* 操作系统版本: centos
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. curl -O https://arthas.aliyun.com/arthas-boot.jar
2. java -jar arthas-boot.jar
3. [1]: 16451 org.elasticsearch.bootstrap.Elasticsearch

### 期望的结果

可以正常启动

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

[INFO] arthas-boot version: 3.6.6
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
* [1]: 16451 org.elasticsearch.bootstrap.Elasticsearch
1
[INFO] Start download arthas from remote server: https://arthas.aliyun.com/download/3.6.6?mirror=aliyun
[INFO] File size: 12.89 MB, downloaded size: 416.53 KB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 1.05 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 2.51 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 3.52 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 4.78 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 5.68 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 6.52 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 8.00 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 9.85 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 11.12 MB, downloading ...
[INFO] File size: 12.89 MB, downloaded size: 12.57 MB, downloading ...
[INFO] Download arthas success.
[INFO] arthas home: /home/app/.arthas/lib/3.6.6/arthas
[INFO] Try to attach process 16451
Picked up JAVA_TOOL_OPTIONS: 
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:122)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:161)
[ERROR] attach fail, targetPid: 16451

把异常信息贴到这里
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:122)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:161)
[ERROR] attach fail, targetPid: 16451

**Comment by hengyunabc** [comment]
参考：https://github.com/alibaba/arthas/search?q=Elasticsearch&type=issues

**Comment by wildfirexie** [comment]
已经解决了。

**Comment by huangpeng0817** [comment]
请问是怎么解决的呀。现在使用碰到了，不知道咋解决

> 已经解决了。

**Comment by JMTiantd** [comment]
并没有解决呀，最新版本的依旧有这个问题
