### ISSUE TITLE
增加docker编译支持

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#2338]
目前Arthas的编译有点复杂了，考虑增加docker环境，用户可以自行用docker来编译。

欢迎社区提供支持。

**Comment by hengyunabc** [comment]
@changren-wcr 欢迎提交pr，可能是一个dockerfile，用户在本地编译时，通过共享的方式，共享本地的代码目录，这样编译后本地也可以直接访问到编译结果。

**Comment by topsuder** [comment]
干
