### ISSUE TITLE
项目中用了自定义了ClassLoader，arthas-boot启动后连接报Unable to add JAR file to system class path

### ISSUE THREAD

**Issue by Ezi1h** [alibaba/arthas#2343]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，发现了这个 #1307 ，看了下好像和我的情况应该不符合，没找到如何解决的方法。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.6
* Arthas 版本: 3.6.6
* 操作系统版本: Centos 7.5
* 目标进程的JVM版本: jdk1.8, Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
* 执行`arthas-boot`的版本: jdk1.8 , Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

用arthas连的这个项目是个公司的老web项目(非spring boot)，项目中用的是内嵌的tomcat(有点类似spring boot...)，不是部署到单独的tomcat中的，jvm参数里加了`-Djava.system.class.loader`，为自定义的ClassLoader继承了URLClassLoader，里面加载了项目根目录lib下的所有jar，需要的话我可以贴下这个ClassLoader的代码，猜测是这个的问题引起的。

还有这个项目编译打包后构建了个二进制安装文件，是用的**installAnyWhere**打的，然后安装完就类似于解压缩出各种lib目录之类的，实际启动应该是调用的installAnyWhere中的一个类启动的，不知道有没有大佬了解这东西，应该也是很古老的东西...

下面arthas连接选项中的`com.zerog.lax.LAX`这个并不是我的启动类，应该是**installAnyWhere**中的类，实际上应该是这个类又读取了一个文件，找到的我项目中的实际的启动类反射调用(这步里才用到自定义ClassLoader)才拉起的服务。

本机开发环境是没有使用自定义的ClassLoader的，直接idea中指定的启动类main方法启动的，可以连上的；但是服务器的部署环境就报下面的错了，所以猜测是ClassLoader引起的。

请教下有没有大佬给解惑下如何解决这个问题？

### 重现问题的步骤

1. java -jar  arthas-boot.jar 启动
2. 选择要连接的进程然后就报错了

### 期望的结果

打包安装的部署环境能够正常使用

### 实际运行的结果

 
```shell
[root@vm4-3pc4-51 arthas-3.6.6]# java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.6.6
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
*[1]: 8413 com.zerog.lax.LAX
1
[INFO] arthas home: /opt/arthas-3.6.6
[INFO] Try to attach process 8413
Picked up JAVA_TOOL_OPTIONS:
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentLoadException: Unable to add JAR file to system class path
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:119)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:122)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:27)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:161)
[ERROR] attach fail, targetPid: 8413
```

**Comment by hengyunabc** [comment]
这个报错是很明确的，要看下那个自定义实现的ClassLoader，是否支持 add jar。打开 URLClassLoader 的代码，可以看到有这个函数，估计jdk也是调这个函数。

```java
    /**
     * Appends the specified URL to the list of URLs to search for
     * classes and resources.
     * <p>
     * If the URL specified is {@code null} or is already in the
     * list of URLs, or if this loader is closed, then invoking this
     * method has no effect.
     *
     * @param url the URL to be added to the search path of URLs
     */
    protected void addURL(URL url) {
        ucp.addURL(url);
    }
```
