### ISSUE TITLE
钉钉2群能否扩充一下人数?

### ISSUE THREAD

**Issue by luutqf** [alibaba/arthas#2346]
现在群全满了, 扩一下叭

**Comment by havenBoy** [comment]
QQ群也加入不了。问题是软件的第一个小写字母，难道不是a吗 ？  我的理解有问题 ？

**Comment by hengyunabc** [comment]
钉钉群满了，新建了一个 3群：17605006847 

@havenBoy QQ 1群现在加不了，可以加2群。

**Comment by hengyunabc** [comment]
文档已经更新了。

**Comment by havenBoy** [comment]
> 钉钉群满了，新建了一个 3群：17605006847
> 
> @havenBoy QQ 1群现在加不了，可以加2群。

qq2群加不了  @hengyunabc

**Comment by hengyunabc** [comment]
@havenBoy 新建了qq3群，可以加

![3](https://user-images.githubusercontent.com/1683936/204968477-9188bb28-73e4-4200-b63d-bf9f8e73aaef.JPG)
