### ISSUE TITLE
maven仓库上面的几乎所有的arthas项目的HomePage链接都是无效链接

### ISSUE THREAD

**Issue by meiMingle** [alibaba/arthas#2348]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

无需环境信息

### 重现问题的步骤

1.打开https://mvnrepository.com/artifact/com.taobao.arthas/arthas-packaging/3.6.7
arthas-common
arthas-spring-boot-starter
arthas-memorycompiler
arthas-spy
arthas-demo
等等都是如此

2. 点击HomePage链接
![屏幕截图 2022-11-18 102707](https://user-images.githubusercontent.com/39942874/202603792-ba486352-94a2-4910-8e68-ee94da1e7f4f.png)

### 期望的结果

正常跳转到有效的HomePage

### 实际运行的结果
页面不存在
![image](https://user-images.githubusercontent.com/39942874/202603542-091d63e0-f4a0-4da6-95f2-01fef492f720.png)
```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
这个应该是 flatten-maven-plugin 自动展开的结果，arthas因为历史原因，代码目录命令和 artifactId不一致，所以这里会打开失败。

这个应该影响不大。要修复的话，需要修改目录名，目前必要性不大。

**Comment by hengyunabc** [comment]
尽管有点麻烦，全都手动指定url了😂
