### ISSUE TITLE
need help for watch command ognl expression

### ISSUE THREAD

**Issue by goynam** [alibaba/arthas#2361]
如何在 watch 命令中打印 returnObj 的属性。
watch 命令给 returnObj 一个用户列表。我只想打印用户对象的“名称”字段。

**Comment by MissingNone** [comment]
watch com.xxx.XXXX 监控方法名 "returnObj.{名称}"
例如:
watch com.example.Test test "returnObj.{name}"

**Comment by goynam** [comment]
但是 returnObj 是 List 的一个对象。如何迭代并仅打印名称字段？

**Comment by MissingNone** [comment]
> 
按照我之前给的命令输出的，是不是你想要的结果?
![image](https://user-images.githubusercontent.com/24592613/205782357-1fec6c41-bebc-4fde-8cea-580c02177bdf.png)

**Comment by goynam** [comment]
所以，如果我尝试这个命令：

观看 com.demo.UserDetailsS​​ervice getUser“{params,returnObj.name}”

我收到以下错误：

ognl.NoSuchPropertyException: java.util.ArrayList.name，访问 /dev/null/logs/arthas/arthas.log 了解更多详情。

**Comment by goynam** [comment]
watch com.xxx.XXXX 监控方法名 "returnObj.{名称}"
例如:
watch com.example.Test test "returnObj.{name}"

这实际上有效，非常感谢。只是一个天真的问题，我如何使用 watch 命令扩展我想打印的对象树的深度。当前限制为 4，是否有打印更多嵌套结构的方法。还有在文件中输出 watch 命令日志的方法吗？
