### ISSUE TITLE
arthas可以对集群部署的应用做监控吗

### ISSUE THREAD

**Issue by zoutuo** [alibaba/arthas#2372]
如题，例如虚机部署有10台，或k8s中存在10个pod，那么我该如何使用？谢谢！

**Comment by RaymondLam1** [comment]
* The principle of arthas is bytecode enhancement. Monitoring the cluster means that each container running a service needs to install arthas. Maybe you can refer to [phlare](https://grafana.com/docs/phlare/latest/) and [grafana](https://grafana.com/) which have open source code.
