### ISSUE TITLE
Arthas Docker镜像使用问题

### ISSUE THREAD

**Issue by MentosL** [alibaba/arthas#2375]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 问题

1. 在docker hub中的arthas会包含jdk的基础镜像吗？
2. 如果包含jdk基础镜像，那么我现在想要arthas那部分，去除jdk镜像打包的，是该如何实现呢？

**Comment by RaymondLam1** [comment]
# Solution
It is a easy problem, you can refer to [how to use Arthas in docker](https://arthas.aliyun.com/doc/docker.html#%E9%80%9A%E8%BF%87-docker-%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8).

**Comment by hengyunabc** [comment]
最简单是自己 wget下载。或者用docker镜像里no-jdk 的。

https://hub.docker.com/layers/hengyunabc/arthas/3.6.7-no-jdk/images/sha256-24df201d8a4809426a00f805a5cf1a7126cef38b9a6c79007d23b574b6b0eb27?context=explore
