### ISSUE TITLE
arthas有办法监听某个方法的参数，并实时修改吗？

### ISSUE THREAD

**Issue by greatyy** [alibaba/arthas#2377]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

例如有以下方法
```
public class User {
      public void cmdEval(String cmd) {
        Runtime.getRuntime().exec(cmd)
    }
}
```
出于测试的目的， 我希望在cmd传入的时候，自动修改为我想要的payload
请问这种有方法可以实现吗？

**Comment by WowYouCanReallyDance** [comment]
> - [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
> 
> 例如有以下方法
> ```
> public class User {
>       public void cmdEval(String cmd) {
>         Runtime.getRuntime().exec(cmd)
>     }
> }
> ```
> 出于测试的目的， 我希望在cmd传入的时候，自动修改为我想要的payload
> 请问这种有方法可以实现吗？
> 
> 

那不就是jad反编译改代码然后再编译再redefine换class吗？

**Comment by hengyunabc** [comment]
如果入参是一个object，是可以直接修改它的 field， 或者调用它的函数的。但不建议这样做，容易出问题。
