### ISSUE TITLE
仅拥有IPV6的机器，无法使用

### ISSUE THREAD

**Issue by RichurLiu** [alibaba/arthas#2381]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 的版本： 3.6.7
* Arthas 版本: 3.6.7
* 操作系统版本: linux
* 目标进程的JVM版本: jdk1.8.0_181
* 执行`arthas-boot`的版本: 3.6.7

### 重现问题的步骤
curl -O https://arthas.aliyun.com/arthas-boot.jar
java -jar arthas-boot.jar
[INFO] JAVA_HOME: /xxx/xxx/jdk/jdk1.8.0_181/jre
[INFO] arthas-boot version: 3.6.7
[INFO] Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
[1]: xxx-1.0.0-SNAPSHOT.jar
1
[ERROR] Can not read arthas version from: https://arthas.aliyun.com/api/latest_version
[ERROR] Can not find Arthas under local: /root/.arthas/lib and remote repo mirror: aliyun
[ERROR] Unable to download arthas from remote server, please download the full package according to wiki: https://github.com/alibaba/arthas

### 期望的结果

正常启动

### 实际运行的结果

报错，未正常启动，错误信息如下

```
[ERROR] Can not read arthas version from: https://arthas.aliyun.com/api/latest_version
[ERROR] Can not find Arthas under local: /root/.arthas/lib and remote repo mirror: aliyun
[ERROR] Unable to download arthas from remote server, please download the full package according to wiki: https://github.com/alibaba/arthas
```

**Comment by hengyunabc** [comment]
可能要调试下，代码没有特别的地方。

https://github.com/alibaba/arthas/blob/arthas-all-3.6.7/boot/src/main/java/com/taobao/arthas/boot/DownloadUtils.java#L35

**Comment by chenqx33** [comment]
jdk8默认是ipv4，可以手动指定ipv6
java -Djava.net.preferIPv6Addresses=true -jar arthas-boot.jar 599

**Comment by RichurLiu** [comment]
感谢 @chenqx33 ，指定ipv6可以解这个问题
