### ISSUE TITLE
jdk8和jdk11均编译报错

### ISSUE THREAD

**Issue by jwrwst** [alibaba/arthas#2382]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 最新版本tag3.7.6和master分支都一样
* 操作系统版本: windows
* 目标进程的JVM版本: 1.8 

### 重现问题的步骤

![image](https://user-images.githubusercontent.com/24490695/208837773-adddb8f6-44a7-499c-9d66-8af06811acbc.png)

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
![image](https://user-images.githubusercontent.com/24490695/208837817-ab073132-f007-4621-b885-707cd49d9339.png)

**Comment by cxshun** [comment]
arthas用的是openjdk，你这里的是oracle jdk（它的jfr在另外一个包，就是你截图下面的oracle.jrocket.jfr里面，如果你想要编译没问题，重新下一个openjdk就好了。

## 附图
+ oracle jdk
![image](https://user-images.githubusercontent.com/1651036/209042045-7b5241bb-9585-4bea-8e3a-218fe55ad722.png)
+ openjdk
![image](https://user-images.githubusercontent.com/1651036/209042204-14d9de52-08b1-4797-88b7-49d589d5ae28.png)
