### ISSUE TITLE
arthas dump操作无法实时跟踪目标程序运行时类字节码的变动情况

### ISSUE THREAD

**Issue by yaokuku123** [alibaba/arthas#2389]
- [✅ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.7
* Arthas 版本: 3.6.7
* 操作系统版本: mac m1 13.0.1
* 目标进程的JVM版本: 1.8.0_211
* 执行`arthas-boot`的版本: 3.6.7

### 重现问题的步骤

1.启动目标SpringBoot程序
2.分别通过arthas和dumpclass.jar的dump操作得到修改前类ApplicationFilterChain的字节码
3.通过agent的retransformClasses修改ApplicationFilterChain类的doFilter方法，更改全局过滤器，使得可以在web上操作目标程序的linux服务器
<img width="547" alt="image" src="https://user-images.githubusercontent.com/34773171/210122735-dd6f45a2-3273-474d-90fe-3b16e1078905.png">
4.再次分别通过arthas和dumpclass.jar的dump操作得到修改后类ApplicationFilterChain的字节码
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/34773171/210122743-6bd36812-49c0-496d-be1d-2d1275394cb9.png">

5.最终结果，arthas前后字节码没有变化，dumpclass前后字节码有变化
<img width="681" alt="image" src="https://user-images.githubusercontent.com/34773171/210122748-4001a620-987f-4000-bcbd-8d63149353f6.png">

### 期望的结果

期望arthas dump操作得到的运行时类字节码前后有变化。

### 实际运行的结果

实际arthas dump操作得到的结果前后无变化

**Comment by RaymondLam1** [comment]
# Soulution
You can see code as blow from `com/taobao/arthas/core/GlobalOptions.java` , it may play a part.
```java
/**
 * 是否支持dump被增强的类<br/>
 * 这个开关打开这后，每次增强类的时候都将会将增强的类dump到文件中，以便于进行反编译分析
 */
@Option(level = 1,
        name = "dump",
        summary = "Option to dump the enhanced classes",
        description =
                "This option enables the enhanced classes to be dumped to external file " +
                        "for further de-compilation and analysis."
)
public static volatile boolean isDump = false;
```
You can download Arthas source code from [Arthas github](https://github.com/alibaba/arthas) and change `isDump` to `true`. Please reference to [how to contribute to Arthas](https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md).

**Comment by yaokuku123** [comment]
Thank you for your answer. I will test later.😊
