### ISSUE TITLE
AsyncProfiler error: No AllocTracer symbols found. Are JDK debug symbols installed?

### ISSUE THREAD

**Issue by piglingcn** [alibaba/arthas#2391]
使用docker镜像openjdk:8-jdk-alpine 
https://github.com/alibaba/arthas/blob/master/Dockerfile

进入容器，然后执行profiler start --event alloc
[arthas@7]$  profiler start --event alloc
AsyncProfiler error: No AllocTracer symbols found. Are JDK debug symbols installed?

**Comment by RaymondLam1** [comment]
* Maybe you can give one demo that will help us reproduce your problem.

**Comment by hengyunabc** [comment]
需要安装jdk相关的库，到 https://github.com/jvm-profiling-tools/async-profiler 搜下
