### ISSUE TITLE
arthas tunnel    web-console 界面 服务运行一段时间后 界面就无法显示命令信息了

### ISSUE THREAD

**Issue by xu5102782** [alibaba/arthas#2395]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.`   的版本： 		
* <dependency>
			<groupId>com.taobao.arthas</groupId>
			<artifactId>arthas-spring-boot-starter</artifactId>
			<version>3.6.1</version>
		</dependency>
* Arthas-thnnel  版本: 3.6.6
 

### 重现问题的步骤

1. 登录arthas-tunnel 管理界面  选择某一服务（服务正常运行了 一段时间后大约半个月-一个月）进入
2. 界面显示连接成功  但是命令输入的 光标
3. 
 

### 期望的结果

期望能这样正常显示 命令光标。 执行各种arthas 命令 而不是黑屏

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

![image](https://user-images.githubusercontent.com/32054129/211492367-5a8802a8-bf13-45ff-9805-7fd9936abb6e.png)

```
把异常信息贴到这里
```
![image](https://user-images.githubusercontent.com/32054129/211492182-5a3134e3-73e6-4f42-b292-a99e835275c9.png)

**Comment by xu5102782** [comment]
实际运行的结果：这个是 服务刚启动 几天内 可以正常访问 的截图
把异常信息贴到这里： 这个是 要描述的问题的 截图。 没有可执行命令的光标的位置

**Comment by xudaotutou** [comment]
你好，能否截屏查看浏览器调试台，方便了解是连接不上还是单纯的前端bug
