### ISSUE TITLE
 thread do not exist 

### ISSUE THREAD

**Issue by iszhangsc** [alibaba/arthas#2402]
- [ √] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar`
* Arthas 版本: 3.6.7
* 操作系统版本: mac os 10.13.6
* 目标进程的JVM版本: 11
* 执行`arthas-boot`的版本: 3.6.7

### 重现问题的步骤
执行 `thread` 后能够看到id 为15的线程，但是执行 `thread 15 ` 的时候，提示： ` thread do not exist` 
![image](https://user-images.githubusercontent.com/41824454/211961787-98f28e49-e658-446b-b4dc-98e63a206261.png)

### 期望的结果

可以看到 id 为 15的线程

### 实际运行的结果
thread do not exist! id: 15

```
把异常信息贴到这里
```

**Comment by wuxuanqicn** [comment]
你看到的15实际是15X
已知，但尚未修复问题，见[链接](https://github.com/alibaba/arthas/issues/2239)
当前可以通过 `java -jar arthas-boot.jar --width=120` 加宽ttl宽度，看到完整信息
