### ISSUE TITLE
Arthas tunnel server 占用端口

### ISSUE THREAD

**Issue by haojiesong** [alibaba/arthas#2414]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.7
* Arthas 版本: 3.6.7
* 操作系统版本: Windows 11
* 目标进程的JVM版本: Java8
* 执行`arthas-boot`的版本: 3.6.7

### 重现问题的步骤

1. 运行Arthas tunnel server: _java -jar arthas-tunnel-server-3.6.7-fatjar.jar_
2. 通过TCPView查看端口情况：
![image](https://user-images.githubusercontent.com/74333/214548893-c876fcab-665a-4df8-8135-d9eda141951b.png)

### 期望的结果

只占用最少需要的端口，比如默认端口：7777，8080

### 实际运行的结果

占用了很多无关端口。

**Comment by hengyunabc** [comment]
。。这个可能要仔细看下TCPView 的说明。 Listen 状态的才是侦听的端口。
