### ISSUE TITLE
帮助信息的提示优化建议

### ISSUE THREAD

**Issue by Hitvz** [alibaba/arthas#2416]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.6.7

这是非bug疑问，只是想提一个提示语优化。
help里面的帮助信息：
stop         Stop/Shutdown Arthas server and exit the console.
这一句，我下意识以为可以用Shutdown命令执行，就用了Shutdown执行，机器关机 了，这个描述最好改成Stop/Exit表达比较好。

**Comment by hengyunabc** [comment]
。。 就算是执行 shutdown ，这个也还是在 arthas shell ，并不会关机。

**Comment by Hitvz** [comment]
反正我就是敲了命令关机了，，可能我离开后才执行的。
