### ISSUE TITLE
怎样结束一个thread

### ISSUE THREAD

**Issue by fredeason** [alibaba/arthas#2434]
比方说有一个thread处于阻塞的状态,或者一个需要运行很久的thread,,我通过thread命令能查到,但是怎么终止这个thread的运行呢

**Comment by Larry0091** [comment]
skill -9

**Comment by hengyunabc** [comment]
最新的 vmtool 支持 interrupt 指定 thread 。

**Comment by LeePui** [comment]
> 最新的 vmtool 支持 interrupt 指定 thread 。

试了下，如果线程是死循环的状态，执行`vmtool --action interruptThread -t 线程id` 并不能杀掉线程
