### ISSUE TITLE
options json_format=true后使用vmtool命令存在问题

### ISSUE THREAD

**Issue by zqw961025** [alibaba/arthas#2445]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.7
* Arthas 版本: 3.6.7

### 重现问题的步骤

1：options json_format=false 执行指令vmtool --action getInstances --className org.springframework.web.servlet.handler.AbstractHandlerMethodMapping 放回结果如下：
  @AbstractHandlerMethodMapping[][
    @RequestMappingHandlerMapping[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping@7a35b0f5],
    @ControllerEndpointHandlerMapping[org.springframework.boot.actuate.endpoint.web.servlet.ControllerEndpointHandlerMapping@34f6515b],
    @AdditionalHealthEndpointPathsWebMvcHandlerMapping[org.springframework.boot.actuate.endpoint.web.servlet.AdditionalHealthEndpointPathsWebMvcHandlerMapping@2462cb01],
    @WebMvcEndpointHandlerMapping[org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping@6c61a903],
]

2：options json_format=true 执行指令vmtool --action getInstances --className org.springframework.web.servlet.handler.AbstractHandlerMethodMapping 放回结果如下：
    
ERROR DATA!!! object class: class [Lorg.springframework.web.servlet.handler.AbstractHandlerMethodMapping;, exception class: class java.lang.StackOverflowError, exception message: null

**Comment by hengyunabc** [comment]
本质上是这些类/对象，用 FastJSON toString 会出错。
