### ISSUE TITLE
获取http header值全为NULL

### ISSUE THREAD

**Issue by yanyouqiang1** [alibaba/arthas#2446]
**背景**
线上排查问题时，想观察调用请求的http header值的所有内容。
**使用方法**
DispatcherServlet.doDispatch 方法的第一个参数可以获取到HttpServletRequest对象，该对象有getHeaderNames()获取到迭代name，再使用其getHeader()获取值。

1、使用命令查找header name
`watch org.springframework.web.servlet.DispatcherServlet doDispatch '(#req=params[0],#names=#req.getHeaderNames().{#this.toString()},#names)'  -n 5  -x 3`
可以列举出header名称为ArrayList
2、使用命令，获取header value
`watch org.springframework.web.servlet.DispatcherServlet doDispatch '(#req=params[0],#names=#req.getHeaderNames().{#this.toString()},#names.{#req.getHeader(#this)})'  -n 5  -x 3`
**获取值的内容全部为NULL**
3、使用命令，获取指定header value
watch org.springframework.web.servlet.DispatcherServlet doDispatch '(#req=params[0],#names=#req.getHeaderNames().{#this.toString()},#names.{#req.getHeader("version")})'  -n 5  -x 3
可以获取到值，（version为某个具体的header）

**问题是，为什么在步骤2的时，获取的值全部为NULL呢？**

**Comment by hengyunabc** [comment]
可以自己本地启个工程，然后打断点调试下，确定下要怎样调用。
