### ISSUE TITLE
Suggestion: 看到好多人因为没有安装 telnet 来提问，为何不考虑把 telnet 的安装自动进去？

### ISSUE THREAD

**Issue by wanaright10** [alibaba/arthas#245]
如题

**Comment by hengyunabc** [comment]
1. telnet 本身对于程序员来说是必备的
2. 在linux/mac上telnet也是必备的

没有telnet，最主要是windows或者 cygwin环境下。

后续考虑

1. 当没有telnet时，直接以java方式连接

**Comment by PatrickRoot** [comment]
Mac 10.14  Mojava，不带 telnet
网上说 brew install telnet，非常简单，然而没有
网上找半天说，用inetutils，brew install inetutils，仍然没有，简直要疯了

**Comment by hengyunabc** [comment]
@PatrickRoot attach成功之后，可以用http来访问： https://alibaba.github.io/arthas/web-console.html

**Comment by hengyunabc** [comment]
最新的 as.sh 已经加了没有安装 telnet 的提示。 另外下个版本的 `arthas-boot.jar` 自带一个java telnet。参考： #272
