### ISSUE TITLE
在k8s的pod容器中 使用arthas生成火焰图 命令报错？

### ISSUE THREAD

**Issue by chiyanan** [alibaba/arthas#2451]
![image](https://user-images.githubusercontent.com/20013223/225830787-24df4955-98aa-4848-a4cf-84fdb097b2d6.png)

请问是何原因，在Linux主机下是好使的 容器不行

**Comment by hengyunabc** [comment]
需要安装依赖，到 https://github.com/async-profiler/async-profiler/ 里搜下。
