### ISSUE TITLE
sc -d className 没结果

### ISSUE THREAD

**Issue by cjy5066** [alibaba/arthas#2454]
[arthas@3421]$ sc -d com.xxxxx.xxxx.MeteoInfoSimpleComp
Affect(row-cnt:0) cost in 19 ms.
![image](https://user-images.githubusercontent.com/68627359/226503517-604e12ba-fc6d-43e4-937e-c2d420c40ff1.png)

这个类是存在的。

**Comment by cjy5066** [comment]
正常是应该返回他的加载信息才对；为什么会出现这种情况勒？

**Comment by RaymondLam1** [comment]
* 你的JVM可能还未加载这个类

**Comment by cjy5066** [comment]
> * 你的JVM可能还未加载这个类

明白了，
