### ISSUE TITLE
使用arthas 导致线上频繁GC

### ISSUE THREAD

**Issue by xujialun986** [alibaba/arthas#2456]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

`arthas-boot.jar` 3.1.0
jdk：1.8

线上环境使用arthas 的watch 命令查看指定方法的入参和返回参数，持续一段时间后发现docker 容器输入指令很卡顿，通过top命令发现线上cpu 100%，查看原因是因为FGC频繁，用jstat 查看堆使用情况如下：
![image](https://user-images.githubusercontent.com/54424470/226532755-b70dad4c-f88b-432e-aa0c-4c3bc49fd85b.png)
通过jmap 命令打印出top 20 的大对象，发现arthas 下占用了很多对象，
![image](https://user-images.githubusercontent.com/54424470/226532199-edbaffbe-4f9c-4769-a1be-d8e6cbccb735.png)
，发现服务器上有2个arthas 进程正在运行中，
![image](https://user-images.githubusercontent.com/54424470/226533232-024fdb1f-c99c-4c45-a982-90f0573dc475.png)
我杀死arthas 指定的进程，但是JVM还是频繁GC。

期望得到解决。

**Comment by kimmking** [comment]
1、不建议线上用。
2、如果线上用，每次用完stop清理Enhance数据。

**Comment by wywl99** [comment]
> 这工具不就是线上用的吗，内网或者测试环境有必要用这个吗

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/44#issuecomment-569007710

**Comment by tangjoey** [comment]
> Enhance

怎么清理的呢
