### ISSUE TITLE
容器使用profiler start 命令报错，请给我解释一下，这个

### ISSUE THREAD

**Issue by zhuyixiang** [alibaba/arthas#2457]
AsyncProfiler error: No access to perf events. Try --fdtransfer or --all-user option or ‘sysctl kern

据说是需要一个权限，但是这个权限是不是很高，不应该随便给到容器。
docker-compose.yml 里增加
cap_add:
- SYS_ADMIN

**Comment by zhuyixiang** [comment]
AsyncProfiler error: No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'

麻烦有空看看

**Comment by hengyunabc** [comment]
https://github.com/async-profiler/async-profiler/ 到原项目搜下。
