### ISSUE TITLE
stop 命令无法解除所有的资源占用

### ISSUE THREAD

**Issue by toohandsome** [alibaba/arthas#2460]
![image](https://user-images.githubusercontent.com/46422252/227445885-90a4203e-38d6-46c7-94d3-6b3cb5632844.png)

这是stop 命令的描述，但是我测试发现执行stop 后， 
```
arthas-agent.jar
arthas-core.jar
arthas-spy.jar
```
这三个包仍然是被占用的，无法被移动，删除， 除非重启被注入的程序

**Comment by hengyunabc** [comment]
可能是 windows ？ 

* arthas-spy.jar 这个 append 到 bootstrap classloader里，的确是不能移除的
* arthas-agent.jar , arthas-core.jar 等 jvm gc 之后，应该可以删掉。
