### ISSUE TITLE
[profiler 火焰图报错] Could not find VMThread bridge. Unsupported JVM?

### ISSUE THREAD

**Issue by xiangtianyu** [alibaba/arthas#2461]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.6
* Arthas 版本: 3.6.6
* 操作系统版本: macos m1
* 目标进程的JVM版本: openj9 1.8
* 执行`arthas-boot`的版本: openj9 1.8

### 重现问题的步骤

启动OpenJ9应用使用arthas attach之后，执行profiler start就会有报错

```
[arthas@17920]$ profiler start
AsyncProfiler error: Could not find VMThread bridge. Unsupported JVM?
```

### 期望的结果

正常输出不报错

### 实际运行的结果

报错如下
```
[arthas@17920]$ profiler start
AsyncProfiler error: Could not find VMThread bridge. Unsupported JVM?
```

经过排查应该是async profiler版本太老了不支持OpenJ9，当前版本为2.6.6，但是实际上在2.7以后才陆陆续续添加了OpenJ9的支持，希望arthas可以升级profiler的版本来更好支持OpenJ9应用。

**Comment by kimmking** [comment]
good idea
