### ISSUE TITLE
class redefinition failed: attempted to change the schema (add/remove fields)

### ISSUE THREAD

**Issue by catalpa-tree** [alibaba/arthas#2467]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

* Arthas 版本: 3.6.7
docker部署springboot项目
jdk版本：1.8.0_202

使用任何命令都报
Affect(class count: 1 , method count: 1) cost in 292 ms, listenerId: 1
Enhance error! exception: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
error happens when enhancing class: class redefinition failed: attempted to change the schema (add/remove fields), check arthas log: /home/logs/arthas/arthas.log
日志信息：
![image](https://user-images.githubusercontent.com/69246580/228510726-0add0ff5-c232-4185-998a-3e5f137ea744.png)
![image](https://user-images.githubusercontent.com/69246580/228510992-411c1e9d-7099-4582-9bf1-16a2666f84a9.png)

jad 反编译代码没有任何修改

对Controller中的类、方法操作都不行吗，但对service层的操作都没问题，如下：一般是什么情况？
![image](https://user-images.githubusercontent.com/69246580/228511250-081ddfec-5f38-45f4-a83a-eda27326927b.png)

**Comment by wulangcode** [comment]
提示很清楚了，一般是被字节码插桩了吧，例如用了`skywalking`之类的插件。你的jad反编译也没提供截图啊。

**Comment by catalpa-tree** [comment]
> 提示很清楚了，一般是被字节码插桩了吧，例如用了`skywalking`之类的插件。你的jad反编译也没提供截图啊。

嗯 引了sky，应该被sky改了。这sky怎么还入侵业务代码，直接改了Controller字节码
![image](https://user-images.githubusercontent.com/69246580/229749425-a1ac8039-0564-42ff-95f9-dfa9424ec8aa.png)
