### ISSUE TITLE
启动./as.sh监听的pid和实际监听的pid不一致

### ISSUE THREAD

**Issue by freedomdym** [alibaba/arthas#247]
[jbossadm@release3 arthas-packaging-3]$ ./as.sh 25509
Arthas script version: 3.0.2
Calculating attach execution time...
Attaching to 25509 using version 3.0.4...
Current VM java version: 1.8 do not match target VM java version: 1.7, attach may fail.
Target VM JAVA_HOME is /app/JAVA/jdk1.7.0_79/jre, try to set the same JAVA_HOME.

real	0m0.390s
user	0m0.493s
sys	0m0.054s
Attach success.
Connecting to arthas server... current timestamp is 1539914469
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki: https://alibaba.github.io/arthas
version: 3.0.4
pid: 27305
timestamp: 1539914469329

启动监听的是25509，而实际监听的是27305，为什么会出现这种情况？

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/90
