### ISSUE TITLE
arthas加载的jvm里面的class信息不全

### ISSUE THREAD

**Issue by zhyusgethup** [alibaba/arthas#2479]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.7
* Arthas 版本: 3.6.7
* 操作系统版本: red hat 6.4
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.6.7

我们这边是用arthas 查看一个Resin4进程, 里面是泛微的oa系统。
当使用了watch命令检测一个class时,发现了class不存在。经过再三测试确认线上class一定是存在的，jvm也是加载到了能执行逻辑的..

**Comment by hengyunabc** [comment]
watch命令可能跳过一些 lambda 类，去 ~/logs/arthas/arthas.log  里查看。

用 sc 命令查找类。
