### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by nextboa** [alibaba/arthas#248]
自己实际装来用了一下，但是发现过程中使用命令得到的结果，很多属性都没有对应解释都不知道什么意思？能不能完善一下呢？

**Comment by hengyunabc** [comment]
为什么不写清楚什么不清楚。有改进可以提交pr。 https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md

**Comment by Hearen** [comment]
@nextboa Actually you can check the English version: https://alibaba.github.io/arthas/en/ Most of the terms are explained and enclosed with proper links for further details.
