### ISSUE TITLE
数据回报没有agentId。希望可以添加

### ISSUE THREAD

**Issue by codeleep** [alibaba/arthas#2480]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 的版本： 3.6.7
* Arthas 版本: 3.6.7
* 操作系统版本: macos
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.6.7

### 重现问题的步骤

1. 数据回报没有agentId

### 期望的结果

希望添加AgentId。因为在容器化部署下，IP可能会被分配给不同的应用。导致无法确定该命令历史的唯一性。

### 实际运行的结果

只有IP，但IP可能会被分配其他应用

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
欢迎提交PR。

**Comment by codeleep** [comment]
> 欢迎提交PR。

请问大概多久会打包发布一次。因为希望快速用到该功能。由于希望尽可能通过社区渠道更新，不侵入社区代码。所以咨询一下

**Comment by hengyunabc** [comment]
@codeleep 3.6.9 已经发布，带上了这个功能。
