### ISSUE TITLE
在部署了skyworking的容器中使用跑步起来

### ISSUE THREAD

**Issue by gzqdust** [alibaba/arthas#2486]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.8
* Arthas 版本: 3.6.8
* 操作系统版本: centos7
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: 3.6.8

### 重现问题的步骤

1. 在运行了JAVA_TOOL_OPTIONS=skyworking代理的环境下运行失败

### 期望的结果

正常运行

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
![image](https://user-images.githubusercontent.com/71931120/234164765-c50b8218-99f5-48e3-9930-eacd20deb5c8.png)
把异常信息贴到这里
一致在显示输入JAVA_TOOL_OPTIONS：的页面

**Comment by hengyunabc** [comment]
。。在执行命令前 unset 掉 JAVA_TOOL_OPTIONS 。
