### ISSUE TITLE
怎么在本地修改源码，然后编译运行自己修改的效果

### ISSUE THREAD

**Issue by anze1314** [alibaba/arthas#2489]
- [ √] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.7
* Arthas 版本: 3.6.7
* 操作系统版本: windows10,64位
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 1.8

### 重现问题的步骤

1. 本地拉取分支，改动arthas-sore中的代码，比如给Trace加个自定义参数
2. 本地配置环境，install package均成功
3. 启动\arthas\boot\target\arthas-boot-jar-with-dependencies.jar，
4. 运行jad com.taobao.arthas.core.command.monitor200.TraceCommand  

### 期望的结果

1、结果里面，TraceCommand代码，是自己改动的样子

### 实际运行的结果

1、和远程代码一致
2、是因为打包时自动拉取了远程代码吗？需要我怎么改呢？还是我的启动方式有问题？求解。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#%E5%BC%80%E5%8F%91%E8%80%85%E7%9B%B8%E5%85%B3
