### ISSUE TITLE
win7启动，加上pid，仍旧报错，启动不了

### ISSUE THREAD

**Issue by sliver1001** [alibaba/arthas#249]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: win7
* Java version of target JVM: jdk1.7
* Java version of JVM used to attach: 1.7

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
![default](https://user-images.githubusercontent.com/41311567/47212404-a206a880-d3ca-11e8-9615-08df99e9a996.png)

**Comment by ralf0131** [comment]
Unable to attach to 64-bit process. Could you make sure the JVM used to attach is built on 64-bit Windows or 32-bit window?

Please show us the JAVA_HOME you used to run as.bat.
