### ISSUE TITLE
arthas trace 不能分析方法上自定义注解的耗时，有啥好的办法吗

### ISSUE THREAD

**Issue by fangyufan123** [alibaba/arthas#2494]

**Comment by hengyunabc** [comment]
把问题描述清楚。假定是 aop，aop也有实现回调类，去找相关的实现类。

**Comment by fangyufan123** [comment]
> 把问题描述清楚。假定是 aop，aop也有实现回调类，去找相关的实现类。

你好，我的意思是 arthas有没有便捷的命令去识别方法上的自定义注解的耗时，我现在是利用trace去监测aop的回调类的耗时

**Comment by dolphin-w** [comment]
`---[100.00% 1973.3282ms ] org.springframework.cglib.proxy.MethodInterceptor:intercept()

我。。。有人告诉我这怎么弄吗
