### ISSUE TITLE
脚本启动报错

### ISSUE THREAD

**Issue by jadetang** [alibaba/arthas#25]

**Comment by hengyunabc** [comment]
什么环境？用的什么shell？ 还有把具体的 as.sh 内容贴下。

**Comment by hengyunabc** [comment]
貌似是 sh 和bash的区别：https://askubuntu.com/questions/141928/what-is-difference-between-bin-sh-and-bin-bash

你可以先试下把 as.sh 的第一行改为： `#!/bin/bash`

**Comment by jadetang** [comment]
好，我回家试试

best regards
Sicheng

横云断岭 <notifications@github.com> 于 2018年9月14日周五 17:09写道：

**Comment by jadetang** [comment]
改成 bash 就好了

**Comment by hengyunabc** [comment]
`as.sh` 文件头改为`#!/usr/bin/env bash`，尽量保持能在ubuntu或者默认是 posix sh的OS下面可以工作。
