### ISSUE TITLE
Arthas 是主要用于dev环境、test环境、pro环境中的哪一个环境呀？

### ISSUE THREAD

**Issue by sliver1001** [alibaba/arthas#250]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: xxx
* Operating System version: xxx
* Java version of target JVM: xxx
* Java version of JVM used to attach: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by hengyunabc** [comment]
https://alibaba.github.io/arthas/ 文档上很清楚写着：

`线上遇到某个用户的数据处理有问题，但线上同样无法 debug，线下无法重现！`
