### ISSUE TITLE
arthas-client 支持动态获取某些配置。如：tunnelServer

### ISSUE THREAD

**Issue by codeleep** [alibaba/arthas#2506]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.6.7
* 操作系统版本: 无关
* 目标进程的JVM版本: 五官
* 执行`arthas-boot`的版本: 3.6.7

### 重现问题的步骤

目前arthas配置都只在启动时生效，存储在内存中。在使用中，我们发现了如下问题：

tunnelServer 如果机器挂掉，无法及时更换到一个正常的机器。

虽然可以通过域名+nginx解决。实践过程中，发生很多阻碍。
1. nginx 的keepalive_timeout配置，导致不断的重连。如果添加心跳机制，看起来又不是那么优雅

如果让tunnelServer在断开重连时，可以根据外部接口更改，那就可以直接点到点建连，这不仅仅释放nginx资源，也使响应更快。

### 期望的结果

支持在tunnelServer重连时，从外部更新该配置

### 实际运行的结果

无法更新

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
参考下这个： https://github.com/alibaba/arthas/issues/2340#issuecomment-1314728733
