### ISSUE TITLE
API接口调用，thread命令返回数据有误

### ISSUE THREAD

**Issue by spewmeps** [alibaba/arthas#2507]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： arthas-3.6.7
* Arthas 版本: arthas-3.6.7
* 操作系统版本:  ubuntu 22.04
* 目标进程的JVM版本: 1.8.0_302
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. api调用接口执行命令：thread -n -1 -all --lockedMonitors --lockedSynchronizers

### 期望的结果

What do you expected from the above steps？

程序存在ReentrantReadWriteLock锁，希望能在lockedSynchronizers字段中显示，但是没有

### 实际运行的结果
线程json：
{
                "name": "ReadWriteLock-ReadThread-deadlock",
                "id": 46,
                "time": 0,
                "state": "WAITING",
                "blockedTime": -1,
                "waitedCount": 2,
                "lockOwnerId": -1,
                "deltaTime": 0,
                "blockedCount": 0,
                "cpu": 0.0,
                "interrupt": false,
                "inNative": false,
                "priority": 5,
                "suspended": false,
                "daemon": true,
                "group": "main",
                "lockedMonitors": [],
                "lockedSynchronizers": [],
                "stackTrace": [
                    "\"ReadWriteLock-ReadThread-deadlock\" Id=46 cpuUsage=0.0% deltaTime=0ms time=0ms WAITING on java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@1061211224",
                    "    at jdk.internal.misc.Unsafe.park(Native Method)",
                    "    -  waiting on java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@1061211224",
                    "    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)",
                    "    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)",
                    "    at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:959)",
                    "    at com.huawei.simulate.JavaBugSimulator.handle.ThreadProblemHandle.write(ThreadProblemHandle.java:36)",
                    "    at com.huawei.simulate.JavaBugSimulator.handle.ThreadProblemHandle.read(ThreadProblemHandle.java:26)",
                    "    at com.huawei.simulate.JavaBugSimulator.handle.ThreadProblemHandle.lambda$generateReadWriteLockDeadlock$0(ThreadProblemHandle.java:77)",
                    "    at com.huawei.simulate.JavaBugSimulator.handle.ThreadProblemHandle$$Lambda$714/0x0000000801151220.run(null:-1)",
                    "    at java.lang.Thread.run(Thread.java:833)"
                ],
                "lockInfo": "{\"identityHashCode\":1061211224,\"className\":\"java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync\"}"
            },

ReentrantLock锁是有的：
 {
                "name": "http-nio-8080-Acceptor",
                "id": 28,
                "time": 9,
                "state": "RUNNABLE",
                "blockedTime": -1,
                "waitedCount": 0,
                "lockOwnerId": -1,
                "deltaTime": 0,
                "blockedCount": 0,
                "cpu": 0.0,
                "interrupt": false,
                "inNative": true,
                "priority": 5,
                "suspended": false,
                "daemon": true,
                "group": "main",
                "lockedMonitors": [],
                "lockedSynchronizers": [
                    "{\"identityHashCode\":1966021842,\"className\":\"java.util.concurrent.locks.ReentrantLock$NonfairSync\"}"
                ],
                "stackTrace": [
                    "\"http-nio-8080-Acceptor\" Id=28 cpuUsage=0.0% deltaTime=0ms time=9ms RUNNABLE",
                    "    at sun.nio.ch.Net.accept(Native Method)",
                    "    at sun.nio.ch.ServerSocketChannelImpl.implAccept(ServerSocketChannelImpl.java:425)",
                    "    at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:391)",
                    "    at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:521)",
                    "    at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)",
                    "    at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:128)",
                    "    at java.lang.Thread.run(Thread.java:833)",
                    " ",
                    "    Number of locked synchronizers = 1",
                    "    - java.util.concurrent.locks.ReentrantLock$NonfairSync@1966021842"
                ],
                "lockInfo": null
            },
实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
ReentrantReadWriteLock 不支持。
