### ISSUE TITLE
应用崩溃，进程消失

### ISSUE THREAD

**Issue by piaochunyu** [alibaba/arthas#2510]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.5.3
* 操作系统版本: CentOS Linux release 7.4.1708 (Core)
* 目标进程的JVM版本: 17

### 重现问题的步骤

1.trace ContextUtil dumpDetailFilterItemResult "params[5].mHotelId=12345678"
2. 执行请求

### 期望的结果

打印调用链

### 实际运行的结果

无异常、无信息、arthas直接退出，并且伴随的我的java应用进程消失。

参数对象的成员变量【    public int mHotelId = -1;】

**Comment by hengyunabc** [comment]
`=` 是赋值，`==` 才是判断是否相等。
