### ISSUE TITLE
是否支持自己指定/home/hadoop/这个路径？

### ISSUE THREAD

**Issue by lujuliang** [alibaba/arthas#2511]
你好，由于服务器权限设置因素，home 目录没有修改权限，所有以下目录不能生成，也不能手动创建，请问程序是否支持自己指定/home/hadoop/这个路径？
[ERROR] Can not find Arthas under local: /home/hadoop/.arthas/lib/arthas/arthas and remote repo mirror: aliyun

**Comment by hengyunabc** [comment]
下载全量包，解压使用。
