### ISSUE TITLE
关于OkHttpClient 在高并发报java.lang.OutOfMemoryError unalbe to create new native thread，使用arthas的优化解决方案

### ISSUE THREAD

**Issue by v24342317** [alibaba/arthas#2521]
# 解决使用OkHttpClient 在高并发下java.lang.OutOfMemoryError: unalbe to create new native thread错误

|  版本  | 作者 | 项目组 |   日期   |
| :----: | :--: | :----: | :------: |
| V1.0.0 | 乔亮 | 盛事通 | 23-03-03 |

# 背景

盛事通APP使用私有百度OCR服务，近期百度升级人脸识别服务从原来的CPU更换成GPU服务器。我们写了一个简单的demo来做压测看看实际新提供的人脸识别服务比使用CPU的人脸识别提升有多少。

实例代码如下：

```java
private static JSONObject compareFaceImage(CompareFaceBo compareFaceBo) {
	//创建数据
    List<Map> list = new ArrayList();
    Map mapTemp = new HashMap();
    mapTemp.put("image", faceString);
    mapTemp.put("image_type", "BASE64");
    mapTemp.put("face_type", "LIVE");
    mapTemp.put("quality_control","NONE");
    mapTemp.put("liveness_control", "NONE");
    
    list.add(mapTemp);
    Map mapTemp1 = new HashMap();
    mapTemp1.put("image", faceString);
    mapTemp1.put("image_type", "BASE64");
    mapTemp1.put("face_type", "LIVE");
    mapTemp1.put("quality_control", "NONE");
    mapTemp1.put("liveness_control", "NONE");
    list.add(mapTemp1);
    
    //创建请求
    MediaType mediaType = MediaType.parse("application/json");
    RequestBody body = RequestBody.create(mediaType, JSONUtil.toJsonStr(list));
    Request request = (new Request.Builder()).url("http://IP:port/face-api/v3/face/match?appid=" + compareFaceBo.getAppId()).method("POST", body).addHeader("Content-Type", "application/json").build();

    OkHttpClient client = (new OkHttpClient()).newBuilder().connectTimeout(1, TimeUnit.SECONDS).readTimeout(2, TimeUnit.SECONDS).writeTimeout(1, TimeUnit.SECONDS).build();
    try {
        Response response = client.newCall(request).execute();
        String res = response.body().string();
        return JSONUtil.parseObj(res);
    } catch (IOException var12) {
        throw new CustomException("百度人脸比对接口调用异常！" + var12.getMessage());
    } finally {
        list = null;
    }
}
```

# 压测环境说明

>网络环境：内网压测没有任何防火墙
>服务器环境：使用的阿里云k8s,pod限制为4CPU,8G内存
>jmeter配置说明：1秒200并发循环100次，相当于1分40秒每秒200并发
>java环境：使用的功能内部架构，代码做了混淆各种封装没有使用文档。 -Xms2g -Xmx6g -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -Xmn2g 

# 没有优化前压测结果
<img width="1024" alt="没优化聚合报告" src="https://github.com/alibaba/arthas/assets/11605947/98757e75-0d18-4e9f-a490-7df856944c56">
<center>（图1）</center>

![没优化察看结果树](https://github.com/alibaba/arthas/assets/11605947/35f7c207-c78e-4ddf-83dd-3906a90a7d82)
<center>（图2）</center>

从图1可以看出错误率和99%响应时间等关键参数都非常高，吞掉量才有86个每秒

图2里截取一个异常请求的返回值,返回的内容不是实例代码编写的自定义异常，该异常是公司内部框架封装处理，开发人员完全不知道具体发什么了说明错误，大大的增加了排除错误的难度。

# 优化过程

# 第一次压测

在压测过程中使用arthas的thread命令查看线程

![没优化压测完成速秒后等待线程一直不释放](https://github.com/alibaba/arthas/assets/11605947/2df1a916-d56e-4197-8373-561f5ad7831d)

观察容器情况
![没优化压测完成速秒后cpu占用率居高不下](https://github.com/alibaba/arthas/assets/11605947/b9c9689e-0518-4517-8ff4-595aaa70371f)

##### 分析

在压测过程中观察容器硬件资源使用情况，过程中都没有发现超过限定的硬件资源，再次查看线程情况发现TIMED_WAITING总是为16055个。

# 第二次压测
使用arthas的thread --all --state TIMED_WAITING
<img width="1746" alt="大量超时线程" src="https://github.com/alibaba/arthas/assets/11605947/ed450d47-c294-448a-a59a-3b470a45f57e">

使用arthas的monitor观察压测接口返回情况
<img width="1104" alt="没优化monitor" src="https://github.com/alibaba/arthas/assets/11605947/2252a657-99b9-4dbf-96cc-883f5efc6033">

使用arthas的wacth查看接口具体异常
<img width="1120" alt="没优化阻塞线程具体错误" src="https://github.com/alibaba/arthas/assets/11605947/ef358a03-3c86-4990-967a-1df523fad0ff">

arthas挂了，再次启动报错，运行命令报错
![1677923651098](https://github.com/alibaba/arthas/assets/11605947/d70811c7-e558-4144-9ef6-b8f340539234)

在容器中使用ps -efL | grep java | wc -l 查看java一共创建多少线程
<img width="630" alt="容器查看线程" src="https://github.com/alibaba/arthas/assets/11605947/a3cf9414-e58f-4662-bcea-44c55cdc7c55">

##### 分析

发现大量的OkHttp计时等待线程有压积现象出现占用了大量的系统线程，使用monitor命令观察几次压测出现问题的规律，发现在压测工程中80秒以后接口开始出现并发量下降，错误增多的情况！使用watch查看异常线程发现具体的接口报错的错误，由于大量的线程挤压容器内部的arthas、系统命令全部报错！

# 优化

```java
private static JSONObject compareFaceImage(CompareFaceBo compareFaceBo) {
	//创建数据
    List<Map> list = new ArrayList();
    Map mapTemp = new HashMap();
    mapTemp.put("image", faceString);
    mapTemp.put("image_type", "BASE64");
    mapTemp.put("face_type", "LIVE");
    mapTemp.put("quality_control","NONE");
    mapTemp.put("liveness_control", "NONE");
    
    list.add(mapTemp);
    Map mapTemp1 = new HashMap();
    mapTemp1.put("image", faceString);
    mapTemp1.put("image_type", "BASE64");
    mapTemp1.put("face_type", "LIVE");
    mapTemp1.put("quality_control", "NONE");
    mapTemp1.put("liveness_control", "NONE");
    list.add(mapTemp1);
    
    //创建请求
    MediaType mediaType = MediaType.parse("application/json");
    RequestBody body = RequestBody.create(mediaType, JSONUtil.toJsonStr(list));
    Request request = (new Request.Builder()).url("http://IP:port/face-api/v3/face/match?appid=" + compareFaceBo.getAppId()).method("POST", body).addHeader("Content-Type", "application/json").build();
    
    try {
        // todo 添加优代码
        Response response = MyOkHttpUtil.getOkHttpClient().newCall(request).execute();
        String res = response.body().string();
        return JSONUtil.parseObj(res);
    } catch (IOException var12) {
        throw new CustomException("百度人脸比对接口调用异常！" + var12.getMessage());
    } finally {
        list = null;
    }
}
```

使用单例模式OkHttpClient解决之前大量创建ConnectionPool问题，优化完成！

# 结果
<img width="1024" alt="优化后400并发报自定义错误" src="https://github.com/alibaba/arthas/assets/11605947/a53fa3fc-bce0-4ef9-ac41-b9803b12424d">

模拟1秒400并发出现的12%的错误，查看具体错误都是代码定义的百度OCR超时
<img width="1024" alt="优化后400并发排除我们自定义错误" src="https://github.com/alibaba/arthas/assets/11605947/1cb004c4-eed4-4063-9a81-4fcdd9c01ec6">

模拟1秒400并发排除自定义错误后的报告，没有任何错误
<img width="879" alt="优化后查看thread" src="https://github.com/alibaba/arthas/assets/11605947/bd223095-9288-4d83-a357-50b5a1743833">

查看总线数也没有发现原来TIMED_WAITING没有挤压情况
<img width="1024" alt="优化后300并发报自定义错误" src="https://github.com/alibaba/arthas/assets/11605947/6e6d0a96-cad5-4bc5-a5f2-7ac96c367051">

优化后300并发报自定义错误
<img width="1024" alt="优化后200并发报自定义错误" src="https://github.com/alibaba/arthas/assets/11605947/a56b56b2-002b-4b7e-9d81-883a65fc41c6">

优化后200并发报自定义错误

# 待解决问题(已解决)

1. docker创建线程数限制问题！

   在网上查询相关资料基本都是调整容器的线程限制（ulimit -a）都没有解决限制问题。线程总数到16300以后任何操作都出现bash: fork: retry: Resource temporarily unavailable错误。
   
<img width="1108" alt="查看POD最大线程数" src="https://github.com/alibaba/arthas/assets/11605947/efa2f7e3-3289-4c80-9fba-b993089e0a7e">

调整阿里云k8s pod最大线程

```shell
vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
```

# 为什么生产谨慎地记录日志

在排查OOM unalbe to create new native thread问题的时候发现还有线程阻塞现象
<img width="1760" alt="没优化前还发现大量的线程阻塞" src="https://github.com/alibaba/arthas/assets/11605947/35012a27-16fd-4dd0-a54e-a99592153b31">

使用arthas的thread -b查询阻塞原因
<img width="1760" alt="没优化查看线程阻塞是因为log4j" src="https://github.com/alibaba/arthas/assets/11605947/2b9ed58c-f97d-4b8b-9dbf-53f705eaf31c">

发现我们的base工程里使用Log4j打印日志，在高并发下经常出现线程阻塞情况。这就是为什么在《阿里巴巴Java开发手册(嵩山版)v1.7.0》里日志规约第11条要谨慎地记录日志的原因吧！

>【推荐】谨慎地记录日志。生产环境禁止输出 debug 日志；有选择地输出 info 日志；如果使用warn 来记录刚上线时的业务行为信息，一定要注意日志输出量的问题，避免把服务器磁盘撑爆，并记得及时删除这些观察日志。
>
>说明：大量地输出无效日志，不利于系统性能提升，也不利于快速定位错误点。记录日志时请思考：这些日志真的有人看吗？看到这条日志你能做什么？能不能给问题排查带来好处？

**Comment by cgerx** [comment]
看到标题就猜到问题原因了😄
不要每次new OkHttpClient哦，要用单例的OkHttpClient复用， OkHttpClient为了实现连接复用，new OkHttpClient后会初始化一个连接池，连接池中的链接5分钟后才会断开。这样就算这次请求结束了，连接池中的对象和TCP链接也不会释放。
