### ISSUE TITLE
arthas-spring-boot-starter 需要支持 spring boot3

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#2524]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#building-jars-with-maven-shade-plugin-and-gradle-shadow-plugin

配置文件需要改为：

`META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`

**Comment by hengyunabc** [comment]
因为还没有发新版本，spring boot3 的用户可以暂时在代码里，使用 `@Import` 来引用 Arthas的两个 Configuration 类。

```
  com.alibaba.arthas.spring.ArthasConfiguration
  com.alibaba.arthas.spring.endpoints.ArthasEndPointAutoConfiguration
```

**Comment by liufor** [comment]
`
import com.alibaba.arthas.spring.ArthasConfiguration;
import com.alibaba.arthas.spring.endpoints.ArthasEndPointAutoConfiguration;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

/**
 * 在 Arthas 4.x 发版前，手写@Import以支持 Spring Boot 3.x ,
 * {@see https://github.com/alibaba/arthas/issues/2524#issuecomment-1547378659}.
 *
 * TODO Arthas 4.x 发版后，删除本类.
 */
@Configuration
@Import({ ArthasConfiguration.class, ArthasEndPointAutoConfiguration.class })
public class ArthasSupportSpringboot3Configuration {

}

`
