### ISSUE TITLE
telnet: connect to address 127.0.0.1: Connection refused

### ISSUE THREAD

**Issue by liugdxd** [alibaba/arthas#253]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: Linux host-172-18-231-87 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Java version of target JVM: 1.8.0_45
* Java version of JVM used to attach: 1.8.0_45

### Steps to reproduce this issue

1. as.sh
2. 6
3. telnet: connect to address 127.0.0.1: Connection refused
See below for details
![image](https://user-images.githubusercontent.com/26314788/47267883-0e74d980-d57c-11e8-91c3-c32f09b79ab9.png)

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by liugdxd** [comment]
My program runs in the docker.The programs running not in the container are normal.

**Comment by hengyunabc** [comment]
Refer to : https://github.com/alibaba/arthas/issues/156

**Comment by wangkai93** [comment]
我遇到的是在用arthas的抓elasticsearch的时候遇到这问题，解决这个问题需要两步：

1. 在java运行时的java.policy中加入如下授权
  vi $JAVA_HOME/jre/lib/security/java.policy
```
grant {
    permission java.security.AllPermission;
    permission java.lang.RuntimePermission "*";
    permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
    permission java.net.NetPermission "*";
    permission java.net.SocketPermission "localhost:0","resolve,listen";
    permission java.net.URLPermission "http:*","*:*";
    permission java.net.URLPermission "https:*","*:*";
    permission org.elasticsearch.ThreadPermission "modifyArbitraryThreadGroup";
};
```
2. 在elasticsearch 的配置文件下加上如下授权
   2.1  vi $ES_HOME/config/java.policy
```
  grant codeBase "file:${user.home}/.arthas/lib/-" {
    permission java.io.FilePermission "${user.home}/.arthas/-", "read,write";
    permission java.io.FilePermission "${user.home}/logs/arthas/-", "read,write,delete";
    permission java.lang.RuntimePermission "createClassLoader";
    permission java.lang.RuntimePermission "getClassLoader";
    permission java.lang.RuntimePermission "modifyThreadGroup";
    permission java.lang.RuntimePermission "modifyThread";
    permission java.lang.RuntimePermission "shutdownHooks";
    permission java.lang.RuntimePermission "accessClassInPackage.sun.reflect";
    permission java.lang.RuntimePermission "accessClassInPackage.sun.net.www.protocol.http";
    permission java.lang.RuntimePermission "accessClassInPackage.sun.net.www.http";
    permission java.net.SocketPermission "127.0.0.1:3658", "listen,resolve";
    permission java.net.SocketPermission "127.0.0.1:8563", "listen,resolve";
    permission java.net.SocketPermission "*", "accept";
};
```
 2.2 修改elasticsearch的jvm参数
   vi $ES_HOME/config/jvm.options
     在最后一行添加 -Djava.security.policy=file:///$ES_HOME/config/java.policy
2.3 重启es进程即可
