### ISSUE TITLE
Arthas无法加载容器启动的spring项目？

### ISSUE THREAD

**Issue by eden214** [alibaba/arthas#254]
我们的项目是用resin启动的，不是直接java启动，用`ps aux | grep java`看到的pid也是resin的pid，然后加载之后无法看到项目的类和方法，用通配符也不行，不知道是因为项目使用了resin还是使用了spring导致的

**Comment by ralf0131** [comment]
Maybe you connected to the wrong process. Please check if there are other process running, and make sure Arthas has been shut down.

**Comment by eden214** [comment]
之前是先用`ps aux |  grep java |  grep '项目名'`找到pid，然后运行arthas附加上去，使用`sc -E .*?Controller.*?`看返回的结果里面没有项目相关的类，但是刚才又试了一下好像又可以了，可能是二楼说的情况我之前看错pid了吧。。。另外试了试好像watch的-x深度只能到4？ @hengyunabc @ralf0131

**Comment by eden214** [comment]
还有就是如何调整断开时间？现在好像5分钟就自动断开了

**Comment by hengyunabc** [comment]
超时参考这里： #296

**Comment by lovelyesz** [comment]
我也遇到了这个问题，但是过一段时间再次启动就没问题了，确定第一次启动的时候没有选择错进程
