### ISSUE TITLE
如何利用logger 修改指定某个类的日志级别？

### ISSUE THREAD

**Issue by jianghebo** [alibaba/arthas#2545]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 版本： 3.6.7

### 重现问题的步骤
如何利用logger 修改指定某个类的日志级别？ 日志依赖使用为： logback

### 期望的结果

可以修改指定类的日志打印级别

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

如法修改指定类的，可以修改整个项目
![7](https://github.com/alibaba/arthas/assets/17865919/ac0b1996-ea37-44f9-a97c-6d161cc8d55d)

把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
使用 logger 命令，或者自己仔细写 ognl 表达式。
