### ISSUE TITLE
是否可增加反编译工具自由选择

### ISSUE THREAD

**Issue by suichangyin** [alibaba/arthas#2546]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：xxx
* Arthas 版本: 3.6.9
* 操作系统版本: xxx
* 目标进程的JVM版本: 8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤
1. 使用jad进行代码反编译
2. CFR反编译结果部分与源代码差距较大

### 期望的结果
反编译结果与源代码差距较小

当前使用jad进行反编译时，不能选择反编译工具，仅支持CFR进行反编译，但反编译出来的代码部分与源代码相差较大，期望能内置多种反编译工具，自由选择使用合适的反编译工具。

**Comment by hengyunabc** [comment]
有一个论文评估过，cfr是评分最好的。增加其它的方式会增加打包体积，不现实。 可以dump 下来，自己再用其它方式反编译。
