### ISSUE TITLE
Arthas Doc网站报错‘Scenario not found. Please check your embedding code configuration.’

### ISSUE THREAD

**Issue by Shadow-Java** [alibaba/arthas#2551]
- [ X] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

无

### 重现问题的步骤
浏览器：Chrome 版本 111.0.5563.65（正式版本） （64 位）、Microsoft Edge  113.0.1774.42 (正式版本) (64 位)
访问点击Arthas Doc网站https://arthas.aliyun.com/doc
1. 点击入门教程或者基础命令

### 期望的结果

能够正常访问页面，没有报错信息

### 实际运行的结果
在Chrome和Microsoft Edge都是如此显示

![1685697768522](https://github.com/alibaba/arthas/assets/41174157/aa11e8f7-2c70-4347-ae02-288c0ecb53a0)

![image](https://github.com/alibaba/arthas/assets/41174157/5c58eef8-a9ca-41f6-828e-dbee22a7e7ff)

```
只有报错信息Scenario not found. Please check your embedding code configuration
```

**Comment by l2280212** [comment]
我也是这样，有发现是什么原因吗？

**Comment by hengyunabc** [comment]
在线教程是基于 katacoda的，源网站已经关闭了，所以不能显示。目前在找新的替代方案。
