### ISSUE TITLE
JEP451 准备默认禁止动态加载agent

### ISSUE THREAD

**Issue by LeePui** [alibaba/arthas#2557]
Hi，看到jdk21中这个提议：[JEP451](https://openjdk.org/jeps/451)，大致意思是`在将代理动态加载到正在运行的 JVM 中时发出警告。这些警告旨在让用户为将来的版本做好准备默认不允许动态加载代理，以便在默认情况下[提高完整性](https://openjdk.org/jeps/8305968)。在启动时加载代理的功能功能工具不会导致在任何版本中发出警告。`
arthas也是需要动态attach到应用上的，应该也是会受到影响吧？是否后面也需要改成premain的方式呢？
后续arthas这方面的计划是怎样呢？

**Comment by hengyunabc** [comment]
arthas 目前就支持 premain 。我理解jvm团队为了安全的做法，估计完全禁止还有很长时间，并且这个也没什么大影响。
