### ISSUE TITLE
使用高版本的arthas，arthas-boot启动后显示版本又是低版本了

### ISSUE THREAD

**Issue by angjuLin** [alibaba/arthas#2568]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.5.6
* Arthas 版本: xxx
* 操作系统版本: mac/linu都试过
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

就是启动arthas，看到版本信息

### 期望的结果

希望使用3.5.6启动的，显示的版本也是3.5.6

### 实际运行的结果

都是显示了3.4.X的版本

```
把异常信息贴到这里
```
![image](https://github.com/alibaba/arthas/assets/86584636/7fccca6c-a6e0-4c34-b5a0-0015325cd17c)
![image](https://github.com/alibaba/arthas/assets/86584636/01a4542e-5f9f-4621-aae1-165083dc1015)

**Comment by angjuLin** [comment]
因为我想使用vmtool命令，但是一直启动的是低版本，没发使用

**Comment by hengyunabc** [comment]
要先 stop 掉，参考wiki。

**Comment by angjuLin** [comment]
> 要先 stop 掉，参考wiki。

原来这样。
