### ISSUE TITLE
adviceWeaver中加入的防止自己递归调用，应该不起作用

### ISSUE THREAD

**Issue by whywhy24** [alibaba/arthas#259]
![image](https://user-images.githubusercontent.com/2622153/47332397-c0fa8880-d6b1-11e8-9caa-29e4a871e288.png)

**Comment by hengyunabc** [comment]
最好提供一个可重现的demo，还有重现的步骤。

**Comment by whywhy24** [comment]
这个看下代码逻辑就知道的吧，除非你在methodOnBegin中调用当前的业务方法，但是会存在这种情况吗？

**Comment by oldmanpushcart** [comment]
这个是起作用的
