### ISSUE TITLE
官网访问不了，看不了

### ISSUE THREAD

**Issue by cocodroid** [alibaba/arthas#2602]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
URL：https://arthas.aliyun.com/doc/arthas-tutorials.html?language=cn&id=arthas-basics
![image](https://github.com/alibaba/arthas/assets/11642752/f0e0c5b8-f418-4d6b-bd81-2df2cf2fc27e)
****

**Comment by WangJi92** [comment]
@cocodroid  官方网站的教程正在改版中，要想先体验一下可以访问 https://killercoda.com/arthas ，还没全部处理完成

**Comment by cocodroid** [comment]
> @cocodroid  官方网站的教程正在改版中，要想先体验一下可以访问 https://killercoda.com/arthas ，还没全部处理完成

thanks

**Comment by chenyidao** [comment]
arthas 在线教程用不了吗？进去的时候显示Unable to load scenario

点相关的命令要我登录，选择登录方式时又拒绝
