### ISSUE TITLE
Http api 重定向符号失效

### ISSUE THREAD

**Issue by iwangjie** [alibaba/arthas#2605]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 2.7.0
* 操作系统版本: xxx
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 2.7.0

### 重现问题的步骤

curl --location --request POST 'http://127.0.0.1:8563/api' \
--header 'Content-Type: application/json' \
--data-raw '{
  "action": "exec",
  "command": "echo 21321321321 > /Users/xxx/1.txt"
}
'

### 期望的结果

内容写出到文件

### 实际运行的结果

没有写出到文件

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
http api 只支持单个命令

**Comment by jameszjca** [comment]
> http api 只支持单个命令

這只是陳述事實，並沒有解決問題，"echo 21321321321 > /Users/xxx/1.txt"這樣的指令API有任何等價的單個命令辦法能做到嗎？做不到就是擺爛。
