### ISSUE TITLE
查看环境变量的 sysenv 能否优化一下？

### ISSUE THREAD

**Issue by toutzhang** [alibaba/arthas#2619]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.7.0
* Arthas 版本: 3.7.0
* 目标进程的JVM版本: 1.8

### 期望的结果
全量输出环境变量时，最好能按 KEY 进行排序显示。

### 实际运行的结果
没有排序，不容易查看。

**Comment by RaymondLam1** [comment]
可以在下个版本中加入可选排序参数，来优化体验
