### ISSUE TITLE
为什么没有官方群？window环境出现异常了，有帮忙看看的吗？

### ISSUE THREAD

**Issue by xmt1139057136** [alibaba/arthas#262]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Window环境

* Arthas version: 最新
* Operating System version: Window7
* Java version of target JVM: jdk8
* Java version of JVM used to attach: 如下：

启动异常如下：

![www.xttblog.com](https://user-images.githubusercontent.com/41311567/47212404-a206a880-d3ca-11e8-9615-08df99e9a996.png)

有问题的可以加我(xmtxtt，备注：arthas)，我见一个微信群，方便交流！

**Comment by hengyunabc** [comment]
arthas的交流都在 github issue上，没有群。

你的图里已经有异常信息了，直接在issue里可以搜索到： https://github.com/alibaba/arthas/search?q=64-bit&type=Issues

**Comment by xmt1139057136** [comment]
> arthas的交流都在 github issue上，没有群。
> 
> 你的图里已经有异常信息了，直接在issue里可以搜索到： https://github.com/alibaba/arthas/search?q=64-bit&type=Issues

搞个微信群吧

**Comment by hengyunabc** [comment]
群里的讨论没有价值： https://github.com/alibaba/arthas/issues/7
