### ISSUE TITLE
自动升级下载很慢，可以关闭自动升级吗

### ISSUE THREAD

**Issue by tomatofrommars** [alibaba/arthas#2635]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.6.9
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: 3.6.9

### 重现问题的步骤
自动升级下载速度很慢，虽然公司网速并不慢。

### 期望的结果
可以关闭自动升级

### 实际运行的结果
![企业微信截图_677179b4-f314-4e63-8145-2a68c0b95b83](https://github.com/alibaba/arthas/assets/16113120/3b5c425f-aca9-4694-be5c-22ef7ca8463e)

**Comment by hengyunabc** [comment]
`-h` 查看帮助，用 `--use-version` 可以指定版本。
