### ISSUE TITLE
文档上说不支持查看JUL锁阻塞的线程，冒昧的问一句，什么是JUL锁，谷歌也百度了不过没找到。。

### ISSUE THREAD

**Issue by horo99** [alibaba/arthas#265]
![image](https://user-images.githubusercontent.com/22970981/47409598-c9c48a80-d795-11e8-8c0c-9d716b183e94.png)

**Comment by Hearen** [comment]
@horo99 Please check the English version: https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/en/thread.md#thread--b-locate-the-blocking-threads

@hengyunabc Would you please update the **site**? It's not updated quite long since I corrected some issues.

**Comment by horo99** [comment]
Thank you! @Hearen

**Comment by hengyunabc** [comment]
@horo99 @Hearen The page updated: https://alibaba.github.io/arthas/thread.html 

Auto build website: #266
