### ISSUE TITLE
arthas启动慢

### ISSUE THREAD

**Issue by hao031410** [alibaba/arthas#2667]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

启动很慢，打出JAVA_HOME之后就卡住了，几分钟之后启动完成
有什么排查思路吗

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.7.1
* Arthas 版本: 3.7.1
* 操作系统版本: xxx
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 

### 重现问题的步骤

1. 下载arthas
2. jps
3. ./ah.sh pid

### 期望的结果

正常启动

### 实际运行的结果
卡在如下步骤
arthas.log没有看到关键的信息

![image](https://github.com/alibaba/arthas/assets/35653811/79d45055-fb38-49e7-8962-08239e2bcec6)

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
可能是执行 netstat 查找listen 端口的进程导致的。可以直接指定 pid ，就会跳过。

**Comment by youtiaoguagua** [comment]
应该是由于`lsof`命令导致的，如果`lsof`非常慢，可能是由于linux的文件描述符的设置过大导致的，可以使用` ulimit -n  10000`和`ulimit -Hn 10000`临时设置一下最大值，或者通过修改linux设置来缩小
