### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by wqwq2112** [alibaba/arthas#267]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.04
* Operating System version: win7
* Java version of target JVM: Java 8
* Java version of JVM used to attach:Java 8

### Steps to reproduce this issue

1. tt -i 去看详情时，中文参数乱码
2.jad 去反编译线上代码，中文log为Unicode

```

```

**Comment by xushujin** [comment]
![image](https://user-images.githubusercontent.com/5311716/50062716-a50ff080-01e3-11e9-976c-e552cf2e45a9.png)
在监听某个类函数接收参数时，如果参数为中文，监听日志显示乱码

**Comment by hengyunabc** [comment]
参考： #376
