### ISSUE TITLE
指定pid无效

### ISSUE THREAD

**Issue by bigbenfather** [alibaba/arthas#268]
当选定了一个pid之后，再exit或者quit退出。
然后再进入，选择任何pid都是无效的（或者 as.sh pid命令），都是关联到上次的pid，除非退出时用了shutdown命令。

这个问题对于刚接触的人不是太友好

**Comment by liuxuzxx** [comment]
确实是这个问题，我说，我选择了号码，或者是加着pid都是原先exit退出来的时候的java进程，还是shutdown比较暴力简单

**Comment by ayuan-smile** [comment]
hi buddy，I also encountered this problem, thanks

**Comment by ralf0131** [comment]
@bigbenfather This is by design. Do you have any suggestion for a better user experience?

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/171 ，已经加了已经占用端口的检测，可以试下最新的 as.sh
