### ISSUE TITLE
关于heapdump命令生成的文件无法打开

### ISSUE THREAD

**Issue by kilsoul** [alibaba/arthas#2708]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
我有个java进程，总的堆内存大小大概4G，占用90+%时heapdump文件发现dump文件打开报错，dump文件4G左右。

* `arthas-boot.jar` 或者 `as.sh` 的版本： curl安装的最新版
* Arthas 版本: curl安装的最新版
* 操作系统版本: Alpine docker image (k8s pod运行)
* 目标进程的JVM版本: openjdk8
* 执行`arthas-boot`的版本: curl安装的最新版

### 重现问题的步骤

1. `java -jar arthas-boot.java`
2. `heapdump /xxx/dump.hprof`
3. 使用MAT工具打开dump文件报错
4. 使用Jprofiler工具打开dump文件也报错

### 期望的结果
能正常打开并分析
What do you expected from the above steps？

### 实际运行的结果
1. MAT打开报错，
![image](https://github.com/alibaba/arthas/assets/11747456/ba846c5f-eb1d-4c4f-85ee-188360172c68)

3. Jprofiler打开报错，`root type not found 0`
![image](https://github.com/alibaba/arthas/assets/11747456/f574696c-1e46-468f-8e50-c458ad48d6a8)

![image](https://github.com/alibaba/arthas/assets/11747456/66dd45e2-2ba7-4d7a-b1cf-e4884a680cc0)

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
这个实际上是调用 jvm 的 MBean 来 heapdump的，出错的话，arthas也没有太好的办法。 可以尝试一些命令行工具，或者 jvisualvm 。
