### ISSUE TITLE
async-profiler报错

### ISSUE THREAD

**Issue by shihuili1218** [alibaba/arthas#2709]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

生成火烧图，报错：AsyncProfiler error: Could not set dlopen hook. Unsupported JVM?

async-profiler的bug：https://github.com/async-profiler/async-profiler/issues/610

目前在async-profiler:2.10已修复，async-profiler:2.9仍然存在这个bug

**Comment by shihuili1218** [comment]
搁这呢。https://github.com/async-profiler/async-profiler/releases/tag/v2.10

**Comment by hengyunabc** [comment]
> 搁这呢。https://github.com/async-profiler/async-profiler/releases/tag/v2.10

这个是 `Draft Release `

**Comment by shihuili1218** [comment]
哈哈哈，捉急了
