### ISSUE TITLE
可以dump下被增强过的class文件吗

### ISSUE THREAD

**Issue by deipss** [alibaba/arthas#2723]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
 
使用dump命令下载的class文件，不是最新的。
如
**org/apache/dubbo/rpc/filter/GenericImplFilter extends org/apache/dubbo/rpc/ListenableFilter.class**
使用ASM增强后，dump 下来的字节码和没有增强前一样的。

**Comment by hengyunabc** [comment]
issue 搜 jad反编译 原理
