### ISSUE TITLE
how to change the port 8563

### ISSUE THREAD

**Issue by libinglong** [alibaba/arthas#273]
the org.jetbrains.idea.maven.server.RemoteMavenServer in IntelliJ IDEA will use port 8563.I must kill it before starting arthas which also use 8563 .any way to change the port 8563?
by the way,this condition will make the telnet error like this:
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host

**Comment by libinglong** [comment]
I find the answer in as.sh
usage()
{
    echo "
Usage:
    $0 [-b [-f SCRIPT_FILE]] [debug] [--use-version VERSION] [--attach-only] <PID>[@IP:TELNET_PORT:HTTP_PORT]
    [debug]         : start the agent in debug mode
    <PID>           : the target Java Process ID
    [IP]            : the target's IP
    [TELNET_PORT]   : the target's PORT for telnet
    [HTTP_PORT]     : the target's PORT for http
    [-b]            : batch mode, which will disable interactive process selection.
    [-f]            : specify the path to batch script file.
    [--attach-only] : only attach the arthas agent to target jvm.
    [--use-version] : use the specified arthas version to attach.
    [--versions]    : list all arthas versions.

**Comment by HUTchengxi** [comment]
修改http连接对应端口：java -jar arthas-boot.jar --http-port 1234
修改telnet连接对应端口：java -jar arthas-boot.jar --telnet-port 2345
