### ISSUE TITLE
加了扰码后的应用程序可以使用吗

### ISSUE THREAD

**Issue by wangmin-xidian** [alibaba/arthas#275]
从公众号文章看到在推这个工具，很赞呀。
想请教个问题：Guide中有看到jad进行反编译，那我的应用程式在正式上线的时候是加过扰码的，使用arthas会有什么问题吗？

**Comment by hengyunabc** [comment]
1. arthas里实际上是用一个 [ClassFileTransformer](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/ClassFileTransformer.html) ，来获取字节码，所以并不保证和真正jvm运行的字节码一致。但99%情况下是一致的。
2. 如果想要获取确切的jvm运行的字节码，可以用这个工具：[dumpclass](https://github.com/hengyunabc/dumpclass)

**Comment by wangmin-xidian** [comment]
谢谢解答。
下载体验了一下，还不错，使用简单，但还需要掌握更多的命令才好。也会去用一下你提到的tool，再次感谢！
