### ISSUE TITLE
manual install package can not run

### ISSUE THREAD

**Issue by coffin5257** [alibaba/arthas#276]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: Docker image java:8u111-jdk
* Java version of target JVM: 1.8
* Java version of JVM used to attach: 1.8

### Steps to reproduce this issue

1. manual install followed by the document https://alibaba.github.io/arthas/en/manual-install.html

If there is an exception, please attach the exception trace:

```
# wget https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/3.0.4/arthas-packaging-3.0.4-bin.zip

# unzip arthas-packaging-3.0.4-bin.zip -d arthas/
Archive:  arthas-packaging-3.0.4-bin.zip
  inflating: arthas/arthas-spy.jar
  inflating: arthas/install-local.sh
  inflating: arthas/as.sh
  inflating: arthas/arthas-core.jar
  inflating: arthas/arthas-agent.jar
  inflating: arthas/as.bat
  inflating: arthas/arthas-client.jar

# ./install-local.sh
install to local successed.

# ./as.sh
./as.sh: 93: ./as.sh: Syntax error: "(" unexpected (expecting "fi")
```

as.sh content, seems like incorrect version info:
```
#!/bin/sh

# program : Arthas
#  author : Core Engine @ Taobao.com
#    date : 2017-3-27
# version : 3.0.3

# define arthas's home
ARTHAS_HOME=${HOME}/.arthas

# define arthas's lib
ARTHAS_LIB_DIR=${ARTHAS_HOME}/lib

# define arthas's temp dir
TMP_DIR=/tmp

# last update arthas version
ARTHAS_VERSION=

# current arthas script version
ARTHAS_SCRIPT_VERSION=3.0.2
```

I have tried the package from the maven central repo, it's the same result.

**Comment by hengyunabc** [comment]
Try the new version: https://github.com/alibaba/arthas/blob/master/bin/as.sh

**Comment by coffin5257** [comment]
> Try the new version: https://github.com/alibaba/arthas/blob/master/bin/as.sh

Yes, this worked for the 3.0.4 manual-installed package.

**Comment by coffin5257** [comment]
I have checked the package `https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/3.0.4/arthas-packaging-3.0.4-bin.zip`, it's still not working. Will you fixed it ?

**Comment by hengyunabc** [comment]
@coffin5257 Next release will contain the new version `as.sh`: https://github.com/alibaba/arthas/milestone/2
