### ISSUE TITLE
ognl调用单例对象的同一个方法可以并行吗？

### ISSUE THREAD

**Issue by seyoatda** [alibaba/arthas#2767]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.7.1
* Arthas 版本: 3.7.1
* 操作系统版本: win10

### 重现问题的步骤

1. 使用 ognl 表达式执行一个单例对象的方法。在断点处挂起。
2. 再执行一次同样的表达式，不会启动一个新的线程，只有当断点恢复后才会执行

arthas 是只能串行执行ognl 吗，每条表达式不能并行？

**Comment by hengyunabc** [comment]
idea 默认断点会挂起jvm。
