### ISSUE TITLE
【咨询】 arthas watch 命令返回了 jacoco 注入的字段 jacocoData，这个字段是synthetic，有没有办法默认 watch 不打印这个字段

### ISSUE THREAD

**Issue by lossend** [alibaba/arthas#2772]
![image](https://github.com/alibaba/arthas/assets/49791601/c05382e5-0b9b-40d4-b330-448f67b5ed8a)

**Comment by hengyunabc** [comment]
arthas 作为一个诊断工具，不太可能专门忽略掉某个字段，这样子排查可能无效化了。

**Comment by lossend** [comment]
这个字段是synthetic， https://www.eclemma.org/jacoco/trunk/doc/faq.html 这个文档里，建议是忽略这个字段的

**Comment by lossend** [comment]
![image](https://github.com/alibaba/arthas/assets/49791601/05d5d78b-0de5-4e84-ba45-29eb868a3f5d)
