### ISSUE TITLE
skywalking监控的服务使用arthas的热加载命令失败

### ISSUE THREAD

**Issue by wangkang4** [alibaba/arthas#2773]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
1.arthas-boot.jar版本3.7.1；
2.skywalking的java-agent版本9.0.0；
3.操作系统：Mac的M1
4.jdk版本：1.8.0_372

### 重现问题的步骤

1. 服务使用skywalking监控
2. 设置了skywalking的is_cache_enhanced_class和class_cache_mode配置
3. 使用arthas的redefine命令成功，但是外部class文件没有生效，使用retransform命令报错
4. 使用jad命令查看文件，发现skywalking代理新增了其他属性和方法

### 期望的结果

skywalking监控的服务可以使用arthas热加载命令加载外部class文件

### 实际运行的结果

```
retransform error! java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
```

**Comment by geyaandy** [comment]
你好，邮件我已收到~！祝你的生活越来越好..........

**Comment by kiwi-field** [comment]
@hengyunabc 你好这个问题怎么解决的，我也遇到了。
![image](https://github.com/alibaba/arthas/assets/30741355/4afdd10e-1546-4de2-b8ad-8b13654cdda5)

**Comment by geyaandy** [comment]
你好，邮件我已收到~！祝你的生活越来越好..........
