### ISSUE TITLE
maven 仓库版本错误

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/arthas#279]
使用地址： <https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/3.0.4/arthas-packaging-3.0.4-bin.zip> 下载的包，解压后打开 as.sh，发现备注的版本是3.0.2，代码里面Arthas_Version=3.0.3

**Comment by hengyunabc** [comment]
as.sh有自己单独的版本号，3.0.4里的确没有改。具体策略可以参考： https://github.com/alibaba/arthas/issues/4
