### ISSUE TITLE
profiler 内存热力图疑问

### ISSUE THREAD

**Issue by mousans** [alibaba/arthas#2797]
我们在排查吸纳上oom的时候想要使用使用arthas来对堆外内存进行监控(什么线程调用了什么函数开了多少内存)，但实际使用profiler命令的alloc发现其应该不是统计的malloc，mmap等函数吧？还有很多堆内内存使用也统计了。想请问下现状arthas能只统计非堆内存的热力图吗

**Comment by hengyunabc** [comment]
参考： https://github.com/async-profiler/async-profiler
