### ISSUE TITLE
pom文件描述的jdk版本是1.6，但是缺少类，无法编译

### ISSUE THREAD

**Issue by ted-wq-x** [alibaba/arthas#28]
缺少的类如`java.lang.management.BufferPoolMXBean`、`java.util.concurrent.ThreadLocalRandom`。同时建议添加jdk版本描述

**Comment by hengyunabc** [comment]
具体用什么版本jdk编绎的，看下是不是9以上的

**Comment by ted-wq-x** [comment]
1.6, 按照pom文件描述的

**Comment by hengyunabc** [comment]
可以按文档用 mvnw 跑下： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md
