### ISSUE TITLE
mac下安装提示没有telnet

### ISSUE THREAD

**Issue by loveluckystar** [alibaba/arthas#280]
mac下安装好后，启动发现
Connecting to arthas server... current timestamp is 1541337408
./as.sh: line 423: type: telnet: not found
'telnet' is required.

telnet一定需要吗？因为mac下一般使用lsof来替代telnet，这个对mac似乎不太友好

**Comment by edagarli** [comment]
不会吧，mac一般都内置telnet的

**Comment by edagarli** [comment]
好吧，10.13 好像去掉了telnet，https://forums.developer.apple.com/thread/79056
需要brew安装。

**Comment by edagarli** [comment]
因为as.sh脚本做了判断，理论上你安装应该会报错
`if ! [ -x "$(command -v telnet)" ]; then
  echo 'Error: telnet is not installed.' >&2
  exit 1
fi`

**Comment by hengyunabc** [comment]
@loveluckystar 对开发人员来说，telnet基本是必备工具，mac可以用 brew 来安装下。 下个版本当没有telnet时，会用java telnet client来连接。

**Comment by loveluckystar** [comment]
好，我已经安装了，只是提个醒
