### ISSUE TITLE
明明有对应的getXXX方法 却提示NoSuchPropertyException

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#281]
Arthas version 3.0.4
代码
```
public Object foo(HttpServletRequest request, HttpServletResponse response, @RequestParam String callback)
```

Arthas terminal
```
$ watch com.mycom.app.controller.ManagementController foo "{params[0].headers}" -x 2
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 89 ms.
watch failed, condition is: null, express is: {params[0].headers}, ognl.NoSuchPropertyException: org.apache.catalina.connector.RequestFacade.headers, visit /root/logs/arthas/arthas.log for more details.
```
但是明明有啊
```
$ sm org.apache.catalina.connector.RequestFacade
org.apache.catalina.connector.RequestFacade->getHeaders
```

**Comment by hengyunabc** [comment]
最好提供一个可以重现的demo

**Comment by zhugw** [comment]
@hengyunabc 已提供demo
https://github.com/zhugw/arthas_issue_demo

**Comment by hengyunabc** [comment]
有`getHeaderNames`这个函数，getHeaders是要传参数的：`org.apache.catalina.connector.RequestFacade.getHeaders(String)`
```
$ watch com.example.demo.FooController foo "{params[0].headerNames}" -x 2
```

**Comment by Dr-wgy** [comment]
vmtool --action getInstances --className com.alibaba.nacos.client.naming.cache.ServiceInfoHolder --express 'instances[*].serviceInfoMap' -x 3
Failed to execute ognl, exception message: ognl.NoSuchPropertyException: [Lcom.alibaba.nacos.client.naming.cache.ServiceInfoHolder;.serviceInfoMap, please check $HOME/logs/arthas/arthas.log for more details. 


vmtool --action getInstances --className com.alibaba.nacos.client.naming.cache.ServiceInfoHolder --express 'instances[1].serviceInfoMap'
@ConcurrentHashMap[

这个统配符获取 的逻辑 和 固定下标有区别吗
