### ISSUE TITLE
windows环境，已开启telnet，无法启动，没有报错信息

### ISSUE THREAD

**Issue by sevnape** [alibaba/arthas#285]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: windows server2012
* Java version of target JVM: 1.8
* Java version of JVM used to attach: 1.8

您好，启动arthas脚本后无响应，一直卡在如下界面。
确认已开启telent服务，请问如何解决？谢谢！
![image](https://user-images.githubusercontent.com/11360419/48175538-7cc0e680-e347-11e8-82c1-ad61f1fa9201.png)

**Comment by hengyunabc** [comment]
https://alibaba.github.io/arthas/install-detail.html 试下“手动拼接命令行启动”

**Comment by sevnape** [comment]
> https://alibaba.github.io/arthas/install-detail.html 试下“手动拼接命令行启动”

您好，感谢您的建议，问题已解决！
