### ISSUE TITLE
火焰图 profiler start：AsyncProfiler error: Can not find libasyncProfiler so, please check the arthas directory.

### ISSUE THREAD

**Issue by smile677** [alibaba/arthas#2864]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 的版本： 3.7.2
* Arthas 版本: xxx
* 操作系统版本: Linux version 3.10.0-957.21.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue Jun 18 16:35:19 UTC 2019
* 目标进程的JVM版本:
  java version "1.8.0_411"
  Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
  Java HotSpot(TM) Client VM (build 25.411-b09, mixed mode)
* 执行`arthas-boot`的版本: 3.7.2

### 重现问题的步骤

1. 启动 arthas-boot： java -jar arthas-boot.jar 监控已经启动的进程
2. 输入命令：profiler start
3. 报错：AsyncProfiler error: Can not find libasyncProfiler so, please check the arthas directory.‘’
4. 网上提供的解决方案是基于Docker容器的，而我没有使用Docker

### 期望的结果

What do you expected from the above steps？
如何解决？

**Comment by TulanCN** [comment]
我在某台海光x86的机器上遇到过这问题，最后发现是用户目录下的.arthas文件夹内没有对应的so文件。
推测可能是系统权限问题之类的。
最后解决方式，就是把arthas的async-profiler文件夹(其中有so文件)拷贝至`.arthas/lib/3.7.2/arthas`目录下。
