### ISSUE TITLE
为什么文档中有memory命令，在实际使用中无法找到memory命令呢？help中也没有看到

### ISSUE THREAD

**Issue by yk5215947** [alibaba/arthas#2885]
[root@host-1-3-1-221 arthas]# java -jar arthas-boot.jar 
[INFO] JAVA_HOME: /usr/local/java/jdk1.8.0_301/jre
[INFO] arthas-boot version: 4.0.0

$ help
 NAME         DESCRIPTION                                                                                  
 help         Display Arthas Help                                                                          
 keymap       Display all the available keymap for the specified connection.                               
 sc           Search all the classes loaded by JVM                                                         
 sm           Search the method of classes loaded by JVM                                                   
 classloader  Show classloader info                                                                        
 jad          Decompile class                                                                              
 getstatic    Show the static field of a class                                                             
 monitor      Monitor method execution statistics, e.g. total/success/failure count, average rt, fail rate 
              , etc.                                                                                       
 stack        Display the stack trace for the specified class and method                                   
 thread       Display thread info, thread stack                                                            
 trace        Trace the execution time of specified method invocation.                                     
 watch        Display the input/output parameter, return object, and thrown exception of specified method  
              invocation                                                                                   
 tt           Time Tunnel                                                                                  
 jvm          Display the target JVM information                                                           
 ognl         Execute ognl expression.                                                                     
 mc           Memory compiler, compiles java files into bytecode and class files in memory.                
 redefine     Redefine classes. @see Instrumentation#redefineClasses(ClassDefinition...)                   
 dashboard    Overview of target jvm's thread, memory, gc, vm, tomcat info.                                
 dump         Dump class byte array from JVM                                                               
 options      View and change various Arthas options                                                       
 cls          Clear the screen                                                                             
 reset        Reset all the enhanced classes                                                               
 version      Display Arthas version                                                                       
 shutdown     Shutdown Arthas server and exit the console                                                  
 session      Display current session information                                                          
 sysprop      Display, and change the system properties.                                                   
 sysenv       Display the system env.                                                                      
 history      Display command history                                                                      
 cat          Concatenate and print files                                                                  
 pwd          Return working directory name                                                                
 mbean        Display the mbean information

**Comment by RaymondLam1** [comment]
尝试了下，最新的 4.0.0 中，是有 memory 命令的。尝试清理下 arthas 的工作目录（~/.arthas）。如果依然没有解决，可以尝试做个 demo 复现问题，方便排查。

**Comment by yk5215947** [comment]
> 尝试了下，最新的 4.0.0 中，是有 memory 命令的。尝试清理下 arthas 的工作目录（~/.arthas）。如果依然没有解决，可以尝试做个 demo 复现问题，方便排查。

谢谢，找到原因了，是我之前版本较低，更新后没有关闭原来的arthas，应该先stop命令关闭arthas然后再重启
