### ISSUE TITLE
windows启动后 关闭启动窗口后 无法停止arthas

### ISSUE THREAD

**Issue by Yuxiao97** [alibaba/arthas#289]
如题 arthas启动后 无法停止 只能杀掉进场来停止arthas?

**Comment by hengyunabc** [comment]
telnet 127.0.0.1 3658 执行 shutdown 。

**Comment by Yuxiao97** [comment]
>           telnet 127.0.0.1 3658 执行 shutdown 。
是的 发完就发现了 感谢

**Comment by asdf2014** [comment]
@yuxiao97  @hengyunabc  如果用 telnet 发送了 shutdown 命令之后，连 telnet 都卡住了怎么破 :sweat_smile:

```bash
telnet localhost 3658
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
shutdown
```

**Comment by asdf2014** [comment]
@hengyunabc 等了十来分钟，终于 shutdown 成功了，但是原进程直接卡死了，连 jstack 都打不出来了

**Comment by hengyunabc** [comment]
> @hengyunabc 等了十来分钟，终于 shutdown 成功了，但是原进程直接卡死了，连 jstack 都打不出来了

进程负载高的话，没啥办法。毕竟arthas也是java代码在跑。
