### ISSUE TITLE
使用ognl更改日志信息失败

### ISSUE THREAD

**Issue by mitht** [alibaba/arthas#2896]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
Arthas script version: 4.0.0

### 重现问题的步骤

1.使用 logger打印出日志框架信息
2.通过ognl更改日志输出信息

### 期望的结果

日志输出格式变成动态修改的格式输出

### 实际运行的结果

<img width="954" alt="image" src="https://github.com/user-attachments/assets/51744a84-c949-45da-9522-965b1346398c">

```

ognl '@ch.qos.logback.classic.Logger@getLogger("ROOT").getAppender("CONSOLE").getEncoder().setPattern("%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg [traceId: %mdc{trace_id}] [spanId: %mdc{span_id}]%n")'

ognl '@ch.qos.logback.classic.Logger@getLogger("ROOT").getLoggerContext().reset()'
```
执行ognl命令后,日志输出格式没有变化

**Comment by hengyunabc** [comment]
和这个应该是类似的原因： https://github.com/alibaba/arthas/issues/2892 

可以直接试下 arthas logger 命令。
