### ISSUE TITLE
recursive trace

### ISSUE THREAD

**Issue by pixystone** [alibaba/arthas#292]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

有时候查问题要找到耗时热点的方法，需要好几层递归地去trace。
有没有计划提供递归的方式，递归地统计更深的方法调用耗时？

**Comment by pixystone** [comment]
比如考虑只看topN呢？

**Comment by hengyunabc** [comment]
得先trace，才能来topN。。
