### ISSUE TITLE
[需求] 发布文件中带上 VERSION 文件

### ISSUE THREAD

**Issue by yjqg6666** [alibaba/arthas#2934]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息
不涉及

### 重现问题的步骤
![image](https://github.com/user-attachments/assets/258d9ff0-63d5-490c-9c49-aec9b03989f0)
现有的发版文件压缩包中无法获取agent的版本信息， 只能安装jre环境后运行才能查看到agent的版本信息。

### 期望的结果

压缩包中存在一个VERSION的文件包含agent版本信息，或在arthas.properties文件中包含版本信息。

### 实际运行的结果
无法直接获取版本信息。

**Comment by hengyunabc** [comment]
在 arthas-core.jar 文件里有。可以看 version 命令的实现。

**Comment by yjqg6666** [comment]
这个要查看版本就必须要有个jre环境， 并运行java -jar xxx跑起来才能看到版本了。

**Comment by meiMingle** [comment]
可以读取arthas-core.jar里面的`/META-INF/MANIFEST.MF`这个文件，这是个文本文件，啥语言都能读。文件中的 `Implementation-Version: 4.0.2`应该可以作为版本号
