### ISSUE TITLE
有计划支持 jdk11 吗？

### ISSUE THREAD

**Issue by whitelilis** [alibaba/arthas#294]
在 jdk11 下试了一下，sm 可以看到方法名，但是 monitor 说找不到

**Comment by hengyunabc** [comment]
Arthas支持jdk11。 

你的问题和jdk11没关系，仔细检查表达式是否写对了。

**Comment by whitelilis** [comment]
上图为证
![image](https://user-images.githubusercontent.com/1090230/48384764-bff3ce80-e726-11e8-9e65-75b1d6fb7537.png)

[bruce@d297aba2fdad rt]$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

**Comment by whitelilis** [comment]
https://github.com/whitelilis/Chronicle-Queue-jdk11-utf8-bug
这个 demo， 在 jdk11 下，直接运行 Reader， 用 as.sh 跟踪测试如下：

![image](https://user-images.githubusercontent.com/1090230/48593524-1b70c700-e988-11e8-8c24-44d85e6630e2.png)

**Comment by hengyunabc** [comment]
实测没有问题：

```bash
$ /tmp/arthas/bin/as.sh
Arthas script version: 3.0.4
JAVA_HOME: /Users/hengyunabc/.sdkman/candidates/java/11.0.0-open
Found existing java process, please choose one and hit RETURN.
* [1]: 88577 Test
  [2]: 90548 Reader
  [3]: 35542
2
Calculating attach execution time...
Attaching to 90548 using version 3.0.4...

real	0m2.420s
user	0m0.876s
sys	0m0.102s
Attach success.
telnet connecting to arthas server... current timestamp is 1542557183
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'


wiki: https://alibaba.github.io/arthas
version: 3.0.4
pid: 90548
timestamp: 1542557184084

$ monitor -c 3 Reader onBlob
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 121 ms.
$ sysprop java.version
java.version=11
$
```

**Comment by moviewang** [comment]
> 实测没有问题：
> 
> ```shell
> $ /tmp/arthas/bin/as.sh
> Arthas script version: 3.0.4
> JAVA_HOME: /Users/hengyunabc/.sdkman/candidates/java/11.0.0-open
> Found existing java process, please choose one and hit RETURN.
> * [1]: 88577 Test
>   [2]: 90548 Reader
>   [3]: 35542
> 2
> Calculating attach execution time...
> Attaching to 90548 using version 3.0.4...
> 
> real	0m2.420s
> user	0m0.876s
> sys	0m0.102s
> Attach success.
> telnet connecting to arthas server... current timestamp is 1542557183
> Trying 127.0.0.1...
> Connected to 127.0.0.1.
> Escape character is '^]'.
>   ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.
>  /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'
> |  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.
> |  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |
> `--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'
> 
> 
> wiki: https://alibaba.github.io/arthas
> version: 3.0.4
> pid: 90548
> timestamp: 1542557184084
> 
> $ monitor -c 3 Reader onBlob
> Press Ctrl+C to abort.
> Affect(class-cnt:1 , method-cnt:1) cost in 121 ms.
> $ sysprop java.version
> java.version=11
> $
> ```

大佬 实测的jdk版本和出现问题的版本并不一致啊
同是 openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
版本 出现问题

**Comment by hengyunabc** [comment]
> OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
> 版本 出现问题

具体什么问题，详细信息，异常日志

**Comment by moviewang** [comment]
ok 我重新提个issue吧

**Comment by hengyunabc** [comment]
参考 #425 , #450
