### ISSUE TITLE
jackson 漏洞 PRISMA-2023-0067

### ISSUE THREAD

**Issue by wwulfric** [alibaba/arthas#2946]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 4.0.2

### 重现问题的步骤

安全漏洞：PRISMA-2023-0067，参见 https://issues.apache.org/jira/browse/KAFKA-15000
需要升级 jackson。

jackson的依赖是termd引入的，我尝试在arthas-all pom 里添加了 jackson databind 的依赖，并提高了版本到2.15以上。（当然还需要升级shade plugin 的版本，因为jackson 的jar里包含了 jdk 11, 17, 21 的 class 文件，老版本的 shade plugin 无法支持）

这个 issue 主要咨询一下，官方想要怎么修复这个 issue， 是改 termd 还是直接在 arthas 里改版本。如果能接受上述做法的话，我可以提一个pr

**Comment by hengyunabc** [comment]
在上游 termd 里升级更合理： https://github.com/alibaba/termd

**Comment by hengyunabc** [comment]
arthas 实际运行时，貌似并没有使用到 jackson 相关的类/功能。 考虑在 maven 里直接把 jackson 排除掉。

**Comment by hengyunabc** [comment]
测试了下，主要是 termd 里 websocket 相关处理 json 时，有使用 jackson 。考虑替换为 fastjson 。

**Comment by hengyunabc** [comment]
已替换为 fastjson2。
