### ISSUE TITLE
新版本watch的params在被用于其他方法的入参的时候会直接变成null

### ISSUE THREAD

**Issue by deadpoolssr** [alibaba/arthas#2953]
例如想把一个入参通过json序列化出来看，这样直接返回null，即使确认params[0]肯定不是null，watch com.alibaba.xxxx serialize "{@com.alibab.GsonUtil@toJson(params[0])}" "params[0]!=null"

**Comment by hengyunabc** [comment]
ognl 升级版本导致： https://github.com/alibaba/arthas/issues/2954
