### ISSUE TITLE
启动连不上。。。

### ISSUE THREAD

**Issue by grindwheel** [alibaba/arthas#297]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: linux
* Java version of target JVM: 1.8
* Java version of JVM used to attach: 1.8

![image](https://user-images.githubusercontent.com/10232714/48387996-def85d80-e732-11e8-9da6-81a95cc9fd28.png)
启动一直连不上，是怎么回事

**Comment by hengyunabc** [comment]
试下 jstack 可以连上进程不，可能进程已经僵死状态了

**Comment by hengyunabc** [comment]
arthas本身会判断是否已经有实例在跑。没有shutdown的话，连接上的是之前attach成功的server。

如果可以稳定重现，后续再跟进。

**Comment by hankthon** [comment]
![image](https://user-images.githubusercontent.com/7488536/48748065-8257ee00-ecb0-11e8-8948-44f93658764c.png)
端口被占用

**Comment by hankthon** [comment]
![image](https://user-images.githubusercontent.com/7488536/48749017-ecbe5d80-ecb3-11e8-9c10-de3843b764d3.png)

**Comment by hengyunabc** [comment]
3.0.5 版本已经增加端口检测了。
