### ISSUE TITLE
Windows 使用 Java 代码创建 Arthas 进程无法输入命令

### ISSUE THREAD

**Issue by IceOfSummer** [alibaba/arthas#2970]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： `4.0.4`
* Arthas 版本: `4.0.4`
* 操作系统版本: `Windows 11 23H2`
* 目标进程的JVM版本: `java version "17.0.8" 2023-07-18 LTS`
* 执行`arthas-boot`的版本: `java version "17.0.8" 2023-07-18 LTS`

### 重现问题的步骤

1. 运行下面的代码
```java
Process process = new ProcessBuilder(
        "java",
        "-jar",
        "D:\\DevelopmentTool\\arthas\\arthas-boot.jar"
).inheritIO().redirectErrorStream(true).start();

process.waitFor();
```

2. 选择进程 attach
3. attach成功后输入任意命令并且回车

### 期望的结果

响应回车，打印相应的结果。

### 实际运行的结果

控制台输入回车没有反应。

![屏幕截图 2024-12-09 234304](https://github.com/user-attachments/assets/0d380805-1c63-4859-9775-abd416cc6aac)

---

尝试过：修改编码为 GBK、降级到3.7.3。

代码在 Linux 上是可用的(`Ubuntu 22.04 server 64bit`)，按回车有反应。。。

**Comment by IceOfSummer** [comment]
用 `commons-net` 的 `TelnetClient` 连接可以正常输入输出。

**Comment by S1mploo** [comment]
降级到3.7.3可以解决吗老哥

**Comment by vudsen** [comment]
> 降级到3.7.3可以解决吗老哥

windows上用只能用telnet连，linux上可以直接连。不过还是有bug，输入长度超64了会乱行
