### ISSUE TITLE
3.0.2无法启动 unexpected (expecting "fi")

### ISSUE THREAD

**Issue by jasonyp** [alibaba/arthas#30]
刚刚安装无法运行。
./as.sh: 93: ./as.sh: Syntax error: "(" unexpected (expecting "fi")

**Comment by hhxx1994** [comment]
问题应该和https://github.com/alibaba/arthas/issues/25 一致

**Comment by ralf0131** [comment]
This is a duplication, please refer to #25 . I am closing it now.
