### ISSUE TITLE
tt -s 命令执行出错

### ISSUE THREAD

**Issue by qq271859852** [alibaba/arthas#303]
参照官方文档：https://alibaba.github.io/arthas/tt.html
执行 tt -s method.name=="printAddress" 命令
但却返回
```
ognl.NoSuchPropertyException: com.taobao.arthas.core.advisor.Advice.printAddress, visit /home/xxxxx/logs/arthas/arthas.log for more detail
Affect(row-cnt:0) cost in 1 ms.
```

这是BUG吗？

version:3.0.4

**Comment by hengyunabc** [comment]
最好提供一个可重现的demo

**Comment by hengyunabc** [comment]
tt 的文档更新了： https://alibaba.github.io/arthas/tt.html

**Comment by KeZhimin** [comment]
可以试试使用``tt -s "method.name.equals('queryPage')"``
