### ISSUE TITLE
tomcat信息没有在dashboard中显示

### ISSUE THREAD

**Issue by hbprotoss** [alibaba/arthas#309]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.4
* Operating System version: Linux 4.14.0-deepin2-amd64
* Java version of target JVM: 1.8
* Java version of JVM used to attach: 1.8

### Steps to reproduce this issue

1. dashboard

### Expected Result

右下角显示tomcat

### Actual Result

右下角没显示tomcat

**Comment by hengyunabc** [comment]
这个在ali内部的tomcat才会有显示。后续考虑把这个从dashboard去掉，或者做一个单独的命令。
