### ISSUE TITLE
linux启动as.sh选择pid失败了

### ISSUE THREAD

**Issue by xushjiang** [alibaba/arthas#310]
root@iZ25hez9no9Z:/# ./as.sh 15301
Arthas script version: 3.0.4
Calculating attach execution time...
Attaching to 15301 using version 3.0.4...

real    0m0.221s
user    0m0.331s
sys     0m0.033s
Attach success.
Connecting to arthas server... current timestamp is 1542619405
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'

wiki: https://alibaba.github.io/arthas
version: 3.0.4
pid: 3779
timestamp: 1542619405438

![image](https://user-images.githubusercontent.com/39685678/48699936-9acef680-ec25-11e8-827b-4869fe1f70f7.png)
我的系统里有多个tomcat，其中第一个tomcat pid是3779。我选择pid为15301的tomcat启动的却是3779的jvm。有人知道原因吗？

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/90
