### ISSUE TITLE
使用trace命令报错,No class or method is affected

### ISSUE THREAD

**Issue by GavinTianYang** [alibaba/arthas#311]
$ sm xxx.xxx.xxxFacade add 
Affect(row-cnt:1) cost in 16 ms.

$ trace xxx.xxx.xxxFacade add 
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. visit middleware-container/arthas/issues/278 for more detail

同一个方法，sm可以得到结果，trace、monitor、watch都获得上诉异常。
对于一些类会出现这个状况，一些类却能正常工作。

环境:
1. jdk-10.0.2
2. arthas 3.0.2
3. linux

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/198

**Comment by hengyunabc** [comment]
最好提供可重现的 Demo

**Comment by GavinTianYang** [comment]
> 最好提供可重现的 Demo

发现问题是因为我的代码编译级别是10,换到9或9以下就没有这个问题了

**Comment by GavinTianYang** [comment]
> 最好提供可重现的 Demo

**Comment by szlzhm** [comment]
我这里也遇到这样的问题，我的java编译用java1.8.0_161，运行环境是java1.8.0_181，ubuntu 16.0 64位，springboot应用。

**Comment by pluto-tu** [comment]
一样的问题 
........
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 296 ms, listenerId: 4
然后就没有对应的trace 链路。

**Comment by pluto-tu** [comment]
> 我这里也遇到这样的问题，我的java编译用java1.8.0_161，运行环境是java1.8.0_181，ubuntu 16.0 64位，springboot应用。下面是命令好相关故障： 命令：trace com.kc.Compare compare 故障输出： Press Ctrl+c to abort Affect(class-cnt:1, method-cnt:1) cost in 183 ms.
> 
> 然后就没有输出了。 我这个命令本来是有输出的，运行了多次后，就不论怎样都没有输出了。

因为你没有发送这个请求 请求一次 就会有trace打印出来了
