### ISSUE TITLE
下载arthas-packaging-3.0.4-bin.zip，离线解压运行报错

### ISSUE THREAD

**Issue by zaghost** [alibaba/arthas#314]
- [Y] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

* Arthas version: 3.0.4
* Operating System version: CentOS7
* Java version of target JVM:  JDK1.7
* Java version of JVM used to attach:  1.7

$ pwd
/home/appuser/arthas
$ ll
total 10484
-rw-r--r-- 1 appuser appuser     8015 Sep 14 18:52 arthas-agent.jar
-rw-r--r-- 1 appuser appuser   103660 Sep 14 18:52 arthas-client.jar
-rw-r--r-- 1 appuser appuser 10590270 Sep 14 18:52 arthas-core.jar
-rw-r--r-- 1 appuser appuser     2949 Sep 14 18:51 arthas-spy.jar
-rw-r--r-- 1 appuser appuser     2430 Sep 14 18:49 as.bat
-rwxr-xr-x 1 appuser appuser    14456 Sep 14 18:49 as.sh
-rwxr-xr-x 1 appuser appuser      633 Sep 14 18:49 install-local.sh
$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
$ ./as.sh 5086
Arthas script version: 3.0.2
Calculating attach execution time...
...aching to 5086 using version <html>
`/arthas/arthas-core.jar jarfile /home/appuser/.arthas/lib/<html>`
attach to target jvm (5086) failed, check /home/appuser/logs/arthas/arthas.log or stderr of target jvm for any exceptions.

启动时生成一个乱码的目录

$ tree ~/.arthas/
/home/appuser/.arthas/
└── lib
    └── `<html>\r`

2 directories, 0 files

手动运行
$ /app/java/jdk1.7.0_79/bin/java -Xbootclasspath/a:/app/java/jdk1.7.0_79/lib/tools.jar \
 -jar /home/appuser/arthas/arthas-core.jar -core /home/appuser/arthas/arthas-core.jar -agent /home/appuser/arthas/arthas-agent.jar \
 -pid 5086
Start arthas failed, exception stack trace: 
java.lang.IllegalStateException: as.sh is too old to support web console, please run the following command to upgrade to latest version:
curl -sLk https://alibaba.github.io/arthas/install.sh | sh
	at com.taobao.arthas.core.Arthas.parse(Arthas.java:46)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:96)

`curl -sLk --connect-timeout 5 'http://search.maven.org/solrsearch/select?q=g:%22com.taobao.arthas%22+AND+a:%22arthas-packaging%22'`返回异常数据时(网页而非json)有问题

**Comment by zaghost** [comment]
手动运行，没有指定target-ip参数时，报错信息不准确

**Comment by hengyunabc** [comment]
最新版本`as.sh`里已经修复。
