### ISSUE TITLE
Telnet and HTTP use one port

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#316]
Currently, telnet and HTTP use the different ports, use one port will be better.

**Comment by sjha2048** [comment]
@hengyunabc can you please let me know, how many issues do I have to claim for submitting the proposal?

**Comment by hengyunabc** [comment]
@sjha2048 Only this issue. May need to write a netty handler to support this feature.

**Comment by masteryhx** [comment]
@hengyunabc Hi,I have sent the proposal to your gmail. But I have a submit problem as you can see in the email content. Could you help me with the problem? Thanks!
