### ISSUE TITLE
Test for 3.0.5/测试 3.0.5 版本

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#317]
目前 3.0.5版本开发差不多了，改进了很多用户体验问题。请求支援测试。

有几个点：

* 不同版本的jdk， jdk6 / jdk11 等
* 不同的平台，比如windows, git bash / mingw/cygw
* 测试新加的 arthas-boot.jar 模块。它的功能和 `as.sh`类似，但是是全平台通用的。

    `java -jar arthas-boot.jar` 就可以启动。 
    `java -jar arthas-boot.jar -h` 打印所有参数。 
* 测试 as.sh 新加的各种参数。 `./as.sh -h` 打印所有参数
* 测试 windows下面as.bat
* web console的展示。改进了IE下的字体，填充等。

---

欢迎大家测试并反馈。有问题的话，请回复具体的OS版本，jdk版本，重现的步骤。  

下载： 
[arthas-3.0.5-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/2610232/arthas-3.0.5-SNAPSHOT-bin.zip)

**Comment by xujunhua555** [comment]
redefine error! java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)   redefine貌似不行啊
