### ISSUE TITLE
win10 找不到或无法加载主类

### ISSUE THREAD

**Issue by drduan** [alibaba/arthas#32]
![image](https://user-images.githubusercontent.com/7875572/45602556-fbd62480-ba52-11e8-96c1-04c871e1948e.png)

**Comment by ralf0131** [comment]
Please try to specify the pid:

```
as.bat $PID
```

**Comment by hengyunabc** [comment]
windows安装说明已更新，可以试下新版本： https://alibaba.github.io/arthas/install-detail.html#windows
