### ISSUE TITLE
windows环境下Attach到目标进程时提示tools.jar包找不到

### ISSUE THREAD

**Issue by Json-X** [alibaba/arthas#332]
环境：windows10/java1.8.0.19
环境变量(设置的是JDK)：JAVA_HOME=C:\Program Files\Java\jdk1.8.0_91
异常信息：Exception in thread "main" java.lang.IllegalArgumentException: Can not find tools.jar under java home: C:\Program Files\Java\jre1.8.0_91
![62fc53637da0e4abb4d86f593b64a50](https://user-images.githubusercontent.com/26082470/49350498-2d719a00-f6ea-11e8-8f7a-88e143d82266.png)
![280c77db93a361540bf365fe97148d8](https://user-images.githubusercontent.com/26082470/49350499-2fd3f400-f6ea-11e8-90fb-3bd2182eaa09.png)

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/325 

可以在启动时，用jdk下面的 java来启动，这样子就可以找到tools.jar了。 把jdk/bin 目录设置到系统的 PATH里

**Comment by cuijd** [comment]
我安装的JAVA_HOME和提示的位置不一致是为什么？然后也报找不到tools.jar
![image](https://user-images.githubusercontent.com/32664321/49430956-457b1380-f7e7-11e8-94c7-2210880824d9.png)
![image](https://user-images.githubusercontent.com/32664321/49430978-53c92f80-f7e7-11e8-9b6f-89cfe55227a9.png)

**Comment by Json-X** [comment]
> 我安装的JAVA_HOME和提示的位置不一致是为什么？然后也报找不到tools.jar
> ![image](https://user-images.githubusercontent.com/32664321/49430956-457b1380-f7e7-11e8-94c7-2210880824d9.png)
> ![image](https://user-images.githubusercontent.com/32664321/49430978-53c92f80-f7e7-11e8-9b6f-89cfe55227a9.png)

这个问题的临时解决办法是：运行jar包的时候指定自己java的目录，比如：java -jar arthas-boot.jar -Djava.home="C:\Program Files\Java\jdk1.8.0_91"
但最终还是得在代码解决这个问题才行

**Comment by hengyunabc** [comment]
> 我安装的JAVA_HOME和提示的位置不一致是为什么？然后也报找不到tools.jar
> ![image](https://user-images.githubusercontent.com/32664321/49430956-457b1380-f7e7-11e8-94c7-2210880824d9.png)
> ![image](https://user-images.githubusercontent.com/32664321/49430978-53c92f80-f7e7-11e8-9b6f-89cfe55227a9.png)

试下用全路径来启动java。比如 `C:\program\ Files\Java\jdk\bin/java -jar arthas-boot.jar`

**Comment by cuijd** [comment]
> > 我安装的JAVA_HOME和提示的位置不一致是为什么？然后也报找不到tools.jar
> > ![image](https://user-images.githubusercontent.com/32664321/49430956-457b1380-f7e7-11e8-94c7-2210880824d9.png)
> > ![image](https://user-images.githubusercontent.com/32664321/49430978-53c92f80-f7e7-11e8-9b6f-89cfe55227a9.png)
> 
> 试下用全路径来启动java。比如 `C:\program\ Files\Java\jdk\bin/java -jar arthas-boot.jar`

我切到我JAVA_HOME目录bin下执行就行了

**Comment by cuijd** [comment]
> > 我安装的JAVA_HOME和提示的位置不一致是为什么？然后也报找不到tools.jar
> > ![image](https://user-images.githubusercontent.com/32664321/49430956-457b1380-f7e7-11e8-94c7-2210880824d9.png)
> > ![image](https://user-images.githubusercontent.com/32664321/49430978-53c92f80-f7e7-11e8-9b6f-89cfe55227a9.png)
> 
> 试下用全路径来启动java。比如 `C:\program\ Files\Java\jdk\bin/java -jar arthas-boot.jar`

我切到我JAVA_HOME目录bin下执行就行了 3q
