### ISSUE TITLE
原理问题：monitor/watch/trace相关

### ISSUE THREAD

**Issue by zhenglzh** [alibaba/arthas#333]
monitor/watch/trace相关 都通过字节码增强技术来实现的，会在指定类的方法中插入一些切面来实现数据统计和观测。
在使用spring 中，如果类已经加载到spring 容器中，这些监控还能用吗？如果是可以的话那又是怎么处理的
，或者说是通过什么来实现的

**Comment by ralf0131** [comment]
It does not do any business with Spring. All the magic has been done by byte code instrumentation. As long as you know the class, you can do monitor/watch/trace.

**Comment by zhenglzh** [comment]
java agent的原理必须得通过jvm这层，在线上 类已经加载到内存中，没有new class，也可以吗

**Comment by wangzh1205** [comment]
请教一下，watch命令支持，多参数，有响应，针对某个string参数进行条件过滤监控吗？ 如果支持的话，具体脚本怎么写呢

**Comment by hengyunabc** [comment]
> 请教一下，watch命令支持，多参数，有响应，针对某个string参数进行条件过滤监控吗？ 如果支持的话，具体脚本怎么写呢

比如第二个参数是String， `params[1] == "abc"`  。不能解决的话， 建一个单独的 issue，提交一个完整的demo，不要在各个issue下面回复。
