### ISSUE TITLE
Arthas运行依赖包的路径中如果有中文名，会运行错误

### ISSUE THREAD

**Issue by Json-X** [alibaba/arthas#335]
环境：windows10/java1.8.0_91

问题描述：
Arthas运行依赖包的路径中如果有中文名，会运行错误，一直提示
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException: Connection refused: connect
查看日志后发现：
Arthas server agent start...
Agent jar file does not exist: C:\Users\ÏôÑ×\.arthas\lib\3.0.5\arthas\arthas-core.jar
路径中如果有中文，无法识别。

问题解决：
修改为英文名后，运行成功

建议：
如果能够支持中文最好

**Comment by hengyunabc** [comment]
这个问题有点难搞，因为在arthas-boot里是需要新启动一个java进程去attach，然后需要把文件路径传过去。在传的时候，编码是是不受控制的。可以尝试下转义，但不一定能工作。

**Comment by hengyunabc** [comment]
考虑加一个判断，如果路径有中文，或者非asscii字符，抛异常提示。

**Comment by hengyunabc** [comment]
可以用这个版本测试下： https://github.com/alibaba/arthas/issues/571#issuecomment-472838421
