### ISSUE TITLE
 Can not read maven-metadata.xml

### ISSUE THREAD

**Issue by zhangbaomin** [alibaba/arthas#345]
[ERROR] Can not read maven-metadata.xml from: https://repo1.maven.org/maven2/com/taobao/arthas/arthas-packaging/maven-metadata.xml
[ERROR] Can not find Arthas under local: /home/app_rdu/.arthas/lib and remote: center

**Comment by zhangbaomin** [comment]
代理 ？

**Comment by hengyunabc** [comment]
用aliyun的镜像 `java -jar arthas-boot.jar --repo-mirror aliyun --use-http` ，或者全量安装

https://alibaba.github.io/arthas/install-detail.html

**Comment by Knight-Wu** [comment]
你好, 已经使用了全量安装的方法, 并使用java -jar arthas-demo.jar 启动, 但是到了选择应用的时候报了这个错, 如下图所示: 
![image](https://user-images.githubusercontent.com/20329409/51660484-e8326000-1fe8-11e9-98ad-e7e2881ea6db.png)

**Comment by zhangbaomin** [comment]
arthas-boot.jar  ， 您看是不是用错jar包了 ；；可以参考https://alibaba.github.io/arthas/install-detail.html【全量安装】

**Comment by Knight-Wu** [comment]
不好意思是打错了, 的确是arthas-boot.jar, 如图: 
![image](https://user-images.githubusercontent.com/20329409/51715739-f5952c00-2074-11e9-98e8-6f61cf26d6c8.png)

**Comment by hengyunabc** [comment]
@Knight-Wu 全量安装是指下载 10M左右的zip包，然后解压出来得到 arthas-boot.jar 。从你的图里，好像不是下载的10M的zip包。

**Comment by yosaku01** [comment]
使用3.1.0版本启动后，仍然无法读取maven-metadata.xml文件，错误显示
Can not read maven-metadata.xml from: https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/maven-metadata.xml

**Comment by hengyunabc** [comment]
> 使用3.1.0版本启动后，仍然无法读取maven-metadata.xml文件，错误显示
> Can not read maven-metadata.xml from: https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/maven-metadata.xml

检查机器的网络，或者用文档里的 全量安装 方式

**Comment by yosaku01** [comment]
@hengyunabc 机器的网络没有问题的，我设置了http_proxy和https_proxy代理的。
我用全量安装的方式再试一下

**Comment by hengyunabc** [comment]
> @hengyunabc 机器的网络没有问题的，我设置了http_proxy和https_proxy代理的。
> 我用全量安装的方式再试一下

arthas-boot是java代码，识别不到 http_proxy和https_proxy。 试下用 as.sh

**Comment by yosaku01** [comment]
@hengyunabc 在windows环境下如何使用代理？

**Comment by hengyunabc** [comment]
> @hengyunabc 在windows环境下如何使用代理？

不清楚，直接用 全量安装 的方式吧

**Comment by zhangbaomin** [comment]
> @hengyunabc 在windows环境下如何使用代理？
参考这个试试 ？
https://www.cnblogs.com/james23dong/p/8467015.html

windows环境下全量安装肯定是可以的，

**Comment by jiangwh** [comment]
```
java -jar arthas-boot.jar
```
的方式启动，选择仓库地址是根据主机的时区决定的。如果时区在+8区（中国/上海），那么就使用aliyun。如果没有主机时区不在+8区，那么会访问```https://repo1.maven.org/maven2/```。公司可能网络有屏蔽，导致无法下载这个cent仓库的jar包。

**Comment by JohnYehyo** [comment]
实测 全量安装即可解决, 控制台的返回信息中其实也已经指明了"........arthas/lib" 这个包是空的
