### ISSUE TITLE
arthas如何锁定某个pid的服务具体接口信息

### ISSUE THREAD

**Issue by xuyixun21** [alibaba/arthas#346]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* 运行`arthas-boot.jar` 
* Arthas 版本: xxx
linux环境

我想锁定某个pid的服务，获取该pid服务下某个具体接口信息，怎么获取

**Comment by hengyunabc** [comment]
help sc

**Comment by xuyixun21** [comment]
我的意思是    比如我有两个服务进程A和B，方法名都是一样的，我需要锁定到A下面的某个接口，我怎么锁定到A进程下面

**Comment by hengyunabc** [comment]
`锁定`是指什么。 把想要的步骤，结果都描述清楚。

**Comment by xuyixun21** [comment]
比如  有两个相同的服务 分别放在pid为A和pid为B的进程下运行，我想观察pid为B的服务下面的Y方法，同时pid为A的服务下面也有个Y方法，我通过monitor命令怎么监控pid为B的服务下面的Y方法

**Comment by xuyixun21** [comment]
而不是pid为A的服务下面的Y方法
