### ISSUE TITLE
Unable to open socket file: target process not responding or HotSpot VM not loaded

### ISSUE THREAD

**Issue by 11238390** [alibaba/arthas#347]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5
* Arthas 版本: 3.0.5
* 操作系统版本: CentOS release 6.9 
* Java版本: 1.8.0_151

```
[root@localhost arthas]# java -jar arthas-boot.jar 
* [1]: 2705 jar
  [2]: 40018 jar
  [3]: 105193 jar
  [4]: 3036 Bootstrap
  [5]: 39807 jar
2
[INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 40018
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:72)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:99)
[ERROR] Start arthas failed, exception stack trace: 
[ERROR] attach fail, targetPid: 40018

```

**Comment by hengyunabc** [comment]
试下 jstack 看能连接到进程上不

**Comment by Europeafin** [comment]
有同样的问题，sudo也不行，但是每次试图连接的时候，demo进程会触发一次thread dump。
然后jstack无法连接，提示是一样的，进程确实是活着的

```
finyu@finyu-nb0:/mnt/c/Users/finyu/Downloads$ java -jar arthas-boot.jar
* [1]: 208 jar
1
[INFO] arthas home: /home/finyu/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 208
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:72)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:99)
[ERROR] attach fail, targetPid: 208
```

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/359

**Comment by Europeafin** [comment]
> 参考这个： #359

但是我demo都不行呀，那个上面也没提出什么解决方法吧

**Comment by hengyunabc** [comment]
> > 参考这个： #359
> 
> 但是我demo都不行呀，那个上面也没提出什么解决方法吧

如果是进程负载高，没响应，这个无解。只能heapdump来分析。

arthas-demo如果不行的话，可以试下换个环境，换个jdk来试下。

**Comment by 11238390** [comment]
我也是 jstack  -F 才能连上

**Comment by hengyunabc** [comment]
* 关于jstack的实现，可以参考： https://zhuanlan.zhihu.com/p/36224094

* jstack -F 是通过`Java ServiceabilityAgent`来实现的，类似debug。可以参考这个pdf：
[java_web_serviceability_agent.pdf](https://github.com/alibaba/arthas/files/2711669/java_web_serviceability_agent.pdf)

**Comment by zhao41654828** [comment]
> * `jstack`和`arthas`，都是普通的`java agent`。所以如果`jstack`不能连接到进程上，`arthas`基本也不能成功。
> * 关于`jstack`的实现，可以参考： https://zhuanlan.zhihu.com/p/36224094
> * `jstack -F`实现原理和普通的`jstack`不一样，是通过`Java ServiceabilityAgent`来实现的，类似debug。可以参考这个pdf：
>   [java_web_serviceability_agent.pdf](https://github.com/alibaba/arthas/files/2711669/java_web_serviceability_agent.pdf)

请问，arthas是否可以添加类似的 -F 选项？
有些场景，可能只有 -F 才能执行成功.

大佬可以评估一下，需要的话，我这边很有兴趣去研究实现一个，提供一个pr

**Comment by hengyunabc** [comment]
> > * `jstack`和`arthas`，都是普通的`java agent`。所以如果`jstack`不能连接到进程上，`arthas`基本也不能成功。
> > * 关于`jstack`的实现，可以参考： https://zhuanlan.zhihu.com/p/36224094
> > * `jstack -F`实现原理和普通的`jstack`不一样，是通过`Java ServiceabilityAgent`来实现的，类似debug。可以参考这个pdf：
> >   [java_web_serviceability_agent.pdf](https://github.com/alibaba/arthas/files/2711669/java_web_serviceability_agent.pdf)
> 
> 请问，arthas是否可以添加类似的 -F 选项？
> 有些场景，可能只有 -F 才能执行成功.
> 
> 大佬可以评估一下，需要的话，我这边很有兴趣去研究实现一个，提供一个pr

是两种不同的机制，我个人感觉是没办法实现的。如果可以实现，非常欢迎提PR :)

**Comment by monocc** [comment]
> 可能是你Tomcat启动程序是用普通用户启动，但是执行arthas使用root用户执行的。 意见仅做参考

这个才是对头

**Comment by Paleish** [comment]
用jstack也不能连，jstack -F看了下没有死锁，服务器进程打印的日志看起来没什么问题，服务器的资源消耗也不大，启动服务器和arthas都是root用户起的，现在生产环境进程不能停，会因为访问人数下降服务器负载降低后能重新attach吗。

**Comment by bbccaaac** [comment]
我也遇到同样问题，arthas是root用户，应用是其他用户，使用root用户的arthas或jstack attach就报这个错，使用与应用相同用户attach就正常，这是什么原因？

**Comment by qixiaobo** [comment]
这是java原生的机制 利用socket通信 这个是在用户级别的

**Comment by livem** [comment]
> 可能是你Tomcat启动程序是用普通用户启动，但是执行arthas使用root用户执行的。 意见仅做参考

@hengyunabc 

那解决办法呢？
一般服务器上的 tomcat 或者 resin 等等都是已 nobody 用户运行的
一般刚开始使用的新手，应该都遇到这个问题的哈

**Comment by xlxomg** [comment]
我这边应用是work, arthas-boot.jar是root,  然后修改arthas-boot.jar权限为work就可以了

**Comment by kuangxianxi** [comment]
自测的时候还有个注意的地方，不要用**debug**的方式暂停线程，这样也会出现这个错误。可以采取`Thread.sleep`。

**Comment by qixiaobo** [comment]
> 自测的时候还有个注意的地方，不要用**debug**的方式暂停线程，这样也会出现这个错误。可以采取`Thread.sleep`。

Maybe you can use thread debug
![image](https://user-images.githubusercontent.com/2881751/93841930-b5fa6980-fcc7-11ea-9bd7-49e42970f9a2.png)

**Comment by MicroWiller** [comment]
> 可能是你Tomcat启动程序是用普通用户启动，但是执行arthas使用root用户执行的。 意见仅做参考

nice

**Comment by FS-J** [comment]
我这边也遇到了同样的问题
![image](https://user-images.githubusercontent.com/34810819/128449119-1c497830-936a-44b3-883f-730bcaa30552.png)
但是我这里不管使用jstack还是jmap都是  Unable to open socket file: target process not responding or HotSpot VM not loaded
The -F option can be used when the target process is not responding

**Comment by ieayoio** [comment]
> 可能是你Tomcat启动程序是用普通用户启动，但是执行arthas使用root用户执行的。 意见仅做参考

我的tomcat是root用户启动的，arthas也是root用户，但是也报了这个错误，很无奈
![image](https://user-images.githubusercontent.com/7099604/142381401-44b248d7-a3a7-4213-903d-faa2ae1474eb.png)
![image](https://user-images.githubusercontent.com/7099604/142381518-00a8921e-63fe-4917-bbce-cf399100d609.png)

**Comment by FS-J** [comment]
我的问题找到了，是因为linux 服务器定时清掉了tmp下面的套接字的问题，谢谢您的回复

> > 可能是你Tomcat启动程序是用普通用户启动，但是执行arthas使用root用户执行的。 意见仅做参考
> 
> 我的tomcat是root用户启动的，arthas也是root用户，但是也报了这个错误，很无奈 ![image](https://user-images.githubusercontent.com/7099604/142381401-44b248d7-a3a7-4213-903d-faa2ae1474eb.png) ![image](https://user-images.githubusercontent.com/7099604/142381518-00a8921e-63fe-4917-bbce-cf399100d609.png)

**Comment by slankka** [comment]
接楼上

OpenJDK实现：
[findSocketFile](https://cr.openjdk.java.net/~sla/7132199/webrev.00/src/solaris/classes/sun/tools/attach/LinuxVirtualMachine.java.lhs.html#anc2)

套接字应该是在进程的`java.io.tmpdir`下，Linux 在/tmp。

具体不清楚为什么不存在`.java_pid<pid>`

**Comment by Notoodman** [comment]
> 试下 jstack 看能连接到进程上不


> * [ ]  我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
> 
> ### 环境信息
> * `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5
> * Arthas 版本: 3.0.5
> * 操作系统版本: CentOS release 6.9
> * Java版本: 1.8.0_151
> 
> ```
> [root@localhost arthas]# java -jar arthas-boot.jar 
> * [1]: 2705 jar
>   [2]: 40018 jar
>   [3]: 105193 jar
>   [4]: 3036 Bootstrap
>   [5]: 39807 jar
> 2
> [INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
> [INFO] Try to attach process 40018
> com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
> 	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
> 	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
> 	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
> 	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:72)
> 	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
> 	at com.taobao.arthas.core.Arthas.main(Arthas.java:99)
> [ERROR] Start arthas failed, exception stack trace: 
> [ERROR] attach fail, targetPid: 40018
> ```

大佬，你的这个问题解决了吗？求助

**Comment by Notoodman** [comment]
> 我这边也遇到了同样的问题 ![image](https://user-images.githubusercontent.com/34810819/128449119-1c497830-936a-44b3-883f-730bcaa30552.png) 但是我这里不管使用jstack还是jmap都是 Unable to open socket file: target process not responding or HotSpot VM not loaded The -F option can be used when the target process is not responding jstack -F 打印出来也没发现死锁什么的

我的也是，大佬，你的问题解决了吗

**Comment by swh0318** [comment]
解决：在对应JAVA进程启动时添加JVM参数 -XX:+StartAttachListener

**Comment by mushao999** [comment]
我也遇到了上述问题。解决办法是以 su xxx -g root的方式切换到进程启动用户xxx下，然后再执行arthas即可

**Comment by ChenSino** [comment]
> 我的问题找到了，是因为linux 服务器定时清掉了tmp下面的套接字的问题，谢谢您的回复
> 
> > > 可能是你Tomcat启动程序是用普通用户启动，但是执行arthas使用root用户执行的。 意见仅做参考
> > 
> > 
> > 我的tomcat是root用户启动的，arthas也是root用户，但是也报了这个错误，很无奈 ![image](https://user-images.githubusercontent.com/7099604/142381401-44b248d7-a3a7-4213-903d-faa2ae1474eb.png) ![image](https://user-images.githubusercontent.com/7099604/142381518-00a8921e-63fe-4917-bbce-cf399100d609.png)

+1，重启服务测试可用

**Comment by iamgd67** [comment]
> 接楼上
> 
> OpenJDK实现： [findSocketFile](https://cr.openjdk.java.net/~sla/7132199/webrev.00/src/solaris/classes/sun/tools/attach/LinuxVirtualMachine.java.lhs.html#anc2)
> 
> 套接字应该是在进程CWD，或者`java.io.tmpdir`下，Linux 在/tmp。
> 
> `.java_pid<pid>` 这个文件 是被 systemd-tmpfiles 这个程序定时清理掉的。
> 
> 如需要彻底解决这个问题：
> 
> 以Centos 7（其他发型版可参考） 修改`/usr/lib/tmpfiles.d/tmp.conf`，添加
> 
> ```
> x /tmp/.java*
> ```
> 
> 以排除Java生成的套接字。

针对tmp下`.java_pid<pid>` 删除的问题，升级jdk应该也可以，没有文件会重新补充化。 [8u401](https://bugs.openjdk.org/browse/JDK-8225690)

**Comment by adocool** [comment]
亲测，是这个问题，ls -al /tmp | grep java_pid，能查到进程就能连
