### ISSUE TITLE
请教一下，在web项目，想直接集成arthas，有什么思路么？

### ISSUE THREAD

**Issue by w279805299** [alibaba/arthas#355]
因为服务端只暴露一个端口，不能用nginx进行代理，有什么好思路么？

**Comment by hengyunabc** [comment]
arthas是有问题时，再去诊断。 集成具体是指什么？d

**Comment by w279805299** [comment]
嗯，说的没错，但是在容器里。开发和运维不是随时都可以进去的，所以想把这个功能集成到页面来，问题就是刚才所描述的，只能暴露一个端口，方便从页面上直接进行操作。

**Comment by anjia0532** [comment]
如果是服务化场景，并且同服务，实例很多。这种时候最好还是用Ansible比较好，因为你保不准你的请求会发给哪个实例。其实可以分两步走的 ，构建镜像时预留出arthas端口，比如`EXPOSE 8081 8563`, 有需要时，UI配置镜像名或者服务名，ansible 各个主机列表 `docker ps | grep 服务名` 然后`docker exec 容器id /bin/sh -c 'xxxx'` 安装arthas,并附加到jvm上，web-console 填IP就行

如果不在意构建的镜像里包含10M左右的arthas包的话，还可以构建镜像时，直接打进去。`EXPOSE 8081 8563`

如果不介意更hacker一点，可以注册一个cron 定时扫描某个目录下的文件，当成一个switch，业务端继承一个基础包，基础包暴露一个endpoint，有请求后打开switch，arthas就启动了，用完后，再调用endpoint，关闭switch，cron 关闭arthas并清理战场，完活。

这样就不需要ansible了

还有更geeker一点的，写个agent,用来执行一些操作，打到镜像里，干的跟cron一样的活。就不需要业务继承基础jar了，也不需要事前安装arthas包了。

**Comment by hengyunabc** [comment]
最近有一个新想法，提供一个maven依赖，然后应用可以调用来 attach 自身。应用比如自己有一个web admin之类的接口，可以很容易集成。并且提供一个 servlet 配置，可以在应用本身的 web admin上连接到 arthas的 web socket端口上。

**Comment by jiangwh** [comment]
从servlet标准的角度，拦截某个filter，注册处理自己的路径，应该可以做到公用端口

**Comment by Roger3581321** [comment]
另一种方案开发一个controller，传入两个参数一个命令名字，另一个参数列表，java里通过telnet通信，返回telnet命令行（放入json返回值），用户可以通过xterm.js（和arthas相同）开发自定义前端页面。

**Comment by cookiejoo** [comment]
参考这个文章试试
https://blog.csdn.net/caodegao/article/details/106622430

**Comment by hengyunabc** [comment]
现在可以用 arthas-spring-boot-starter 和 tunnel server。
