### ISSUE TITLE
启动没有3658端口

### ISSUE THREAD

**Issue by 595979101** [alibaba/arthas#358]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 
* Arthas 版本:3.0.5
* 操作系统版本:linux
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本:3.0.5

![image](https://user-images.githubusercontent.com/38642570/49782827-a9a35780-fd52-11e8-88e6-393017c37921.png)
启动后并没有server3658端口服务

**Comment by luyuanwan** [comment]
Me too

**Comment by hengyunabc** [comment]
@595979101 用 jstack 看下能不能连上目标进程。

**Comment by 595979101** [comment]
@luyuanwan @hengyunabc 日志上可以看出attach成功了，但是就是arthas-server没完整启动起来并暴露服务端口。后来我换了台机器，就可以了。估计是我服务器环境导致的。那台服务器确实有点乱
