### ISSUE TITLE
attach process 卡主

### ISSUE THREAD

**Issue by Echo009** [alibaba/arthas#359]
### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.0.5
* Arthas 版本: 3.0.5
* 操作系统版本: Linux version 3.10.0-862.11.6.el7.x86_64 
* 目标进程的JVM版本: Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
* 执行`arthas-boot`的版本: 3.0.5

### 实际运行的结果

启动 arthas 尝试 attach 进程，一直卡在 try to attach process xxx 这一步骤，没有其他任何输出。
这种现象可能是什么原因？

**Comment by hengyunabc** [comment]
> 没有 -F 连接不上，进程状态比较差指的是？

进程负载比较高，不能响应正常的attach。

**Comment by Echo009** [comment]
谢谢

**Comment by 347154468** [comment]
尝试切换用户解决此问题
