### ISSUE TITLE
ArthasClassloader和其他字节码增强冲突，greys不冲突

### ISSUE THREAD

**Issue by houseyoung** [alibaba/arthas#360]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5
* Arthas 版本: 3.0.5
* 操作系统版本: Red Hat Enterprise Linux Server 7.2 (Maipo)
* 目标进程的JVM版本: 1.8.0_101
* 执行`arthas-boot`的版本: 3.0.5

### 重现问题的步骤
我们的项目使用了自己开发的基于字节码增强的调用链跟踪器，ArthasClassloader在载入一些被我们增强过的类时，会执行到我们的transform方法中，从而变为被我们增强过的类（以ch.qos.logback.classic.Logger为例）：
![image](https://user-images.githubusercontent.com/7338409/49861029-f0b64900-fe35-11e8-8511-f269f0aa7e2d.png)
然而我们增强过的类中，调用了一些自定义的类：
![image](https://user-images.githubusercontent.com/7338409/49861304-7fc36100-fe36-11e8-97d0-69474cfe71a1.png)
这些类在AppClassLoader中：
![image](https://user-images.githubusercontent.com/7338409/49861403-b600e080-fe36-11e8-8db6-236b483c1b15.png)
ArthasClassloader里的Logger调用不到，故而报错。

经研究，是因为Arthas使用了和Greys不同的Classloader生成方式，Arthas为：
    public ArthasClassloader(URL[] urls) {
        super(urls, ClassLoader.getSystemClassLoader().getParent());
    }
Greys为直接通过jar包地址：
    public AgentClassLoader(final String agentJar) throws MalformedURLException {
        super(new URL[]{new URL("file:" + agentJar)});
    }
Greys的这种方式不会产生如上的问题。

请教为何Greys的方式不会走到transform方法中？以及为何要Arthas中为何要做这样的改动？

**Comment by hengyunabc** [comment]
> * [x]  我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
> 
> ### 环境信息
> * `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5
> * Arthas 版本: 3.0.5
> * 操作系统版本: Red Hat Enterprise Linux Server 7.2 (Maipo)
> * 目标进程的JVM版本: 1.8.0_101
> * 执行`arthas-boot`的版本: 3.0.5
> 
> ### 重现问题的步骤
> 我们的项目使用了自己开发的基于字节码增强的调用链跟踪器，ArthasClassloader在载入一些被我们增强过的类时，会执行到我们的transform方法中，从而变为被我们增强过的类（以ch.qos.logback.classic.Logger为例）：
> ![image](https://user-images.githubusercontent.com/7338409/49861029-f0b64900-fe35-11e8-8511-f269f0aa7e2d.png)
> 然而我们增强过的类中，调用了一些自定义的类：
> ![image](https://user-images.githubusercontent.com/7338409/49861304-7fc36100-fe36-11e8-97d0-69474cfe71a1.png)
> 这些类在AppClassLoader中：
> ![image](https://user-images.githubusercontent.com/7338409/49861403-b600e080-fe36-11e8-8db6-236b483c1b15.png)
> ArthasClassloader里的Logger调用不到，故而报错。
> 
> 经研究，是因为Arthas使用了和Greys不同的Classloader生成方式，Arthas为：
> public ArthasClassloader(URL[] urls) {
> super(urls, ClassLoader.getSystemClassLoader().getParent());
> }
> Greys为直接通过jar包地址：
> public AgentClassLoader(final String agentJar) throws MalformedURLException {
> super(new URL[]{new URL("file:" + agentJar)});
> }
> Greys的这种方式不会产生如上的问题。
> 
> 请教为何Greys的方式不会走到transform方法中？以及为何要Arthas中为何要做这样的改动？

URLClassLoader不指定parent，默认的parent是System ClassLoader。arthas里把parent设置为ext class loader，防止加载到System ClassLoader里的类。

**Comment by houseyoung** [comment]
> > * [x]   我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
> > 
> > ### 环境信息
> > 
> > * `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5
> > * Arthas 版本: 3.0.5
> > * 操作系统版本: Red Hat Enterprise Linux Server 7.2 (Maipo)
> > * 目标进程的JVM版本: 1.8.0_101
> > * 执行`arthas-boot`的版本: 3.0.5
> > 
> > ### 重现问题的步骤
> > 我们的项目使用了自己开发的基于字节码增强的调用链跟踪器，ArthasClassloader在载入一些被我们增强过的类时，会执行到我们的transform方法中，从而变为被我们增强过的类（以ch.qos.logback.classic.Logger为例）：
> > ![image](https://user-images.githubusercontent.com/7338409/49861029-f0b64900-fe35-11e8-8511-f269f0aa7e2d.png)
> > 然而我们增强过的类中，调用了一些自定义的类：
> > ![image](https://user-images.githubusercontent.com/7338409/49861304-7fc36100-fe36-11e8-97d0-69474cfe71a1.png)
> > 这些类在AppClassLoader中：
> > ![image](https://user-images.githubusercontent.com/7338409/49861403-b600e080-fe36-11e8-8db6-236b483c1b15.png)
> > ArthasClassloader里的Logger调用不到，故而报错。
> > 经研究，是因为Arthas使用了和Greys不同的Classloader生成方式，Arthas为：
> > public ArthasClassloader(URL[] urls) {
> > super(urls, ClassLoader.getSystemClassLoader().getParent());
> > }
> > Greys为直接通过jar包地址：
> > public AgentClassLoader(final String agentJar) throws MalformedURLException {
> > super(new URL[]{new URL("file:" + agentJar)});
> > }
> > Greys的这种方式不会产生如上的问题。
> > 请教为何Greys的方式不会走到transform方法中？以及为何要Arthas中为何要做这样的改动？
> 
> URLClassLoader不指定parent，默认的parent是System ClassLoader。arthas里把parent设置为ext class loader，防止加载到System ClassLoader里的类。

请教一下为何Greys的方式不会走到transform方法中？

**Comment by hengyunabc** [comment]
@houseyoung 

#### 这个问题本质上应该是这样的：

* 你的agent修改了arthas里的代码，插入了自己的类，比如A
* 有可能这个类A就加载不到了，因为新attach的agent jar实际上是被加到System ClassLoader urls里的

#### greys的类不会走到transform方法。

这个我感觉不太可能。仔细检查下是否多次attach，最好每次都新启动进程来测试。

#### 彻底完善的agent要怎么处理

* transform修改jdk ClassLoader loacClass的代码，当遇到要加载自己的agent类时，特殊处理

#### ArthasClassLoader 是否要加上找不到类时，从SystemClassLoader来加载的代码

这点我感觉是保持目前现状。尽管agent jar是加在SystemClassLoader urls里的，但是一个ClassLoader应该是允许不加载SystemClassLoader里的类的。

而且，最终选择从SystemClassLoader加载的话，有可能会引起一些奇怪的问题。比如getResource，本来在Arthas里找不到的，最终从SystemClassLoader里加载到了应用的。

**Comment by houseyoung** [comment]
@hengyunabc 
你说的对，greys的方式同样会走到transform增强，只是它从appclassloader中载入了我自定义的Global类，所以执行没问题而已。
确实应当维持arthas当前的方式，不允许加载appclassloader中的类。

我们现在的解决方法，是在我们的transform中判断了进来的classloader是不是arthasclassloader，是则不增强，这样相对简单。

多谢指教！
