### ISSUE TITLE
Add jmx command

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#367]
Add a command `jmx` to read jmx value.

**Comment by Zhang-Jin-Hua** [comment]
认领一下

**Comment by xuzhiyiYoh** [comment]
需要实现哪些功能？类似 [#549](https://github.com/alibaba/arthas/issues/549#issuecomment-467841662) 提到的这些MBean的观察？

**Comment by xuzhiyiYoh** [comment]
需要实现哪些功能？类似 [#549](https://github.com/alibaba/arthas/issues/549#issuecomment-467841662) 提到的这些MBean的观察？

**Comment by hengyunabc** [comment]
@xuzhiyiYoh 就是操作MBean ，list/get/set 调用MBean函数等。

**Comment by xuzhiyiYoh** [comment]
简单实现了几个功能：
1、mbean  (list所有mbean)
![image](https://user-images.githubusercontent.com/48389485/56584887-4e8e4500-660f-11e9-9f36-6b0e7420e95a.png)

2、mbean -m java.lang:type=Memory (mbean的metainfo)
![image](https://user-images.githubusercontent.com/48389485/56584947-6bc31380-660f-11e9-91c5-273ef103d7de.png)

3、mbean com.alibaba.druid.pool:name=dataSource,type=DruidDataSource （查看所有attribute）
![image](https://user-images.githubusercontent.com/48389485/56585088-b5abf980-660f-11e9-903b-4a997489c8c3.png)

4、mbean com.alibaba.druid.pool:name=dataSource,type=DruidDataSource *Count  (匹配attribute，支持正则)
![image](https://user-images.githubusercontent.com/48389485/56585200-f277f080-660f-11e9-90a2-9deda14aba64.png)

5、mbean -i 500 com.alibaba.druid.pool:name=dataSource,type=DruidDataSource *Count (固定时间间隔刷新值)

6、mbean --invoke java.lang:type=Memory gc （调用mbean的方法）
    问题：难点复杂参数需要支持哪些，怎么传，怎么解析好？

不知以上功能是否符合预期?

@hengyunabc

**Comment by hengyunabc** [comment]
@xuzhiyiYoh 我觉得很不错，可以提个PR哈。

invoke这个我觉得不用勉强，毕竟通过ongl命令都可以达到。如果不理想，可以不实现invoke。

我本身很少用JMX功能，我觉得目前的功能很不错了。
