### ISSUE TITLE
sudo 执行 as.sh 找不到 java 进程

### ISSUE THREAD

**Issue by LiZhenNet** [alibaba/arthas#369]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： as.sh
* Arthas 版本: 3.0.5.1
* 操作系统版本: macos 10.14.1
* 目标进程的JVM版本: jdk1.8.0_181
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤
使用sudo  Error: no available java process to attach.
不使用的话可以。

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
直接执行 jps ，看有没有进程。
