### ISSUE TITLE
Need a new LOGO/需要一个新的LOGO

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#371]
目前已经设计出3个LOGO，分别是 Plan A/B/C ，请大家在喜欢的Plan的右上角 👍  投票，欢迎提出建议。

**Comment by hengyunabc** [comment]
@mirzazulfan Thank you very much anyway. 
There is an Alibaba designer designing a new LOGO. It will be posted at this issue later, and everyone can vote.

**Comment by hengyunabc** [comment]
支持Plan C，请在右上角 👍 :

![arthas-05](https://user-images.githubusercontent.com/1683936/51510705-21c46900-1e39-11e9-9e08-ef4985712835.jpg)

**Comment by asdf2014** [comment]
666

**Comment by Famiover** [comment]
支持Plan A   觉得把下划线换成Plan B的更好些

**Comment by Skqing** [comment]
Plan B 更稳重

**Comment by cvictory** [comment]
A， 但是觉得颜色太骚。 字体的颜色全部黑的，下划线用B的？？

**Comment by beiwei30** [comment]
还是 B 比较专业一点。A 花了点

**Comment by VanXD** [comment]
可以参与么?
![arthas-logo 2](https://user-images.githubusercontent.com/9159171/51519097-e044b580-1e5a-11e9-9af8-80725b7f35bc.png)

**Comment by hengyunabc** [comment]
> 可以参与么?

非常欢迎参与 👍

**Comment by foamfish** [comment]
A的辨识度能高些， B非英语母语，放眼瞧去就是RTHS

**Comment by yunzhongniao** [comment]
能不能再浪一点。感觉字体太死板了。

**Comment by jiayeee** [comment]
设计感有点差啊

**Comment by asdf2014** [comment]
喜大普奔~

**Comment by hengyunabc** [comment]
新LOGO已上线。

**Comment by asdf2014** [comment]
@hengyunabc 您好，不知道能否在博客里面引用下 Arthas 的 logo 呀？如果不可以的话，我这边会立即删除。

![image](https://user-images.githubusercontent.com/8108788/57700834-516bdb00-768d-11e9-87a5-36e2eb0d3a97.png)

**Comment by hengyunabc** [comment]
@asdf2014 引用LOGO完全OK。

**Comment by asdf2014** [comment]
@hengyunabc 哈哈 了解，多谢啦~
