### ISSUE TITLE
关于使用redefineClasses的问题

### ISSUE THREAD

**Issue by humiao8sz** [alibaba/arthas#374]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

我看到arthas中大量使用了Instrumentation的redefineClasses方法，之前我们在线上产品使用的时候有遇到过
redefineClasses后CPU飙升至100%的情况，不知道arthas使用后有没有这方面的隐患的，你们有没有遇到过这类问题的？

**Comment by hengyunabc** [comment]
arthas内部基本没有用 redefine ，除了 redefine 命令本身。 可以留意是不是 redefine 改的逻辑引起的问题。
