### ISSUE TITLE
Now the arthus-boot.jar is recommended.Is there any way to debug arthus with the jar?

### ISSUE THREAD

**Issue by libinglong** [alibaba/arthas#377]
I tried the guide of #222 but failed in case of starting with "java -jar arthus-boot.jar"
when I tried to fix #376 ,I wonder how to stop the program at IOUtil.readWrite?
much appreciation for your some advice
@hengyunabc

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/222#issuecomment-448097088
