### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by minioreo** [alibaba/arthas#384]
1. 从idea中选中类的方法，然后copy reference，得到的是类名#方法名的格式，在arthas中watch monitor之类的命令中，需要使用类名[空格]方法名。能否都统一用#，这样就不用粘贴过去再修改了。
2. 在arthas的trace命令中，找到一层子方法A调用耗时特别高，方法A是用类名#方法名来展示的，想直接拷贝粘贴来进一步trace，也得把#修改为空格。能否统一用#.

**Comment by hengyunabc** [comment]
参考这个： #81
