### ISSUE TITLE
Shutdown wildfly server in centos 7.0 when connecting with arthas

### ISSUE THREAD

**Issue by VAGGELIS** [alibaba/arthas#387]
- [ ] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and cannot find in english any answer. 
The issue is similar to this one: https://github.com/alibaba/arthas/issues/347

I'm trying to connect to a wildfly server with arthas running both in centos 7.0.

The server crashes.

The same happens if i run jstack wildfly-pid
it doesn't  crashes if i run jstack -F wildfly-pid

any help?

### Environment

* Arthas version: 3.0.5
* Operating System version: centos 7.0
* Java version of target JVM: jdk 1.8.092
* Java version of JVM used to attach: 1.8.092

**Comment by hengyunabc** [comment]
Both jstack and arthas use agent attach.

It seems a JDK bug. My personal experience, after the JDK 1.8.0_112 version, it is easy to crash when using the agent attach, it is not clear what the problem is.
