### ISSUE TITLE
当使用了arthas的其它指令时，jad出来的是原始的源码还是被增强过的？

### ISSUE THREAD

**Issue by houseyoung** [alibaba/arthas#390]
当使用了arthas的其它指令时，jad出来的是原始的源码还是被增强过的？

**Comment by houseyoung** [comment]
我们在调试的时候，担心注入的代码可能影响业务代码，所以想要看到注入后的结果。现在jad不支持的话，除了改arthas-core.jar然后手动输出class文件，就别无他法了。

**Comment by houseyoung** [comment]
发现原来arthas自带了自动dump下来class文件的功能，只要把globaloptions的isdump调成true就可以了。

**Comment by hengyunabc** [comment]
> 发现原来arthas自带了自动dump下来class文件的功能，只要把globaloptions的isdump调成true就可以了。

https://alibaba.github.io/arthas/dump.html ，这个不一定完全准确，参考上面的说明。

需要绝对准确的dump，可以用上面的 dumpclass 工具。

**Comment by wuwuback1234** [comment]
不执行jad,直接执行watch也是一样的。
会不会是下面2个参数的设置问题？ 需要特别设置吗？我测试的是servlet
 --telnet-port <value>       The target jvm listen telnet port, default 3658
 --http-port <value>         The target jvm listen http port, default 8563
