### ISSUE TITLE
请教Enhancer.spy方法中，为何又要init一次Spy？

### ISSUE THREAD

**Issue by houseyoung** [alibaba/arthas#403]
在启动的时候AgentBootstrap中已经调用了Spy.initForAgentLauncher来初始化Spy，为何要在Enhancer.spy方法再次调用Spy.init来再次初始化一次？初始化的时候，代码如下：

>
        Method initMethod = spyClass.getMethod("init", ClassLoader.class, Method.class,
                Method.class, Method.class, Method.class, Method.class, Method.class);
        initMethod.invoke(null, arthasClassLoader,
                FieldUtils.getField(spyClass, "ON_BEFORE_METHOD").get(null),
                FieldUtils.getField(spyClass, "ON_RETURN_METHOD").get(null),
                FieldUtils.getField(spyClass, "ON_THROWS_METHOD").get(null),
                FieldUtils.getField(spyClass, "BEFORE_INVOKING_METHOD").get(null),
                FieldUtils.getField(spyClass, "AFTER_INVOKING_METHOD").get(null),
                FieldUtils.getField(spyClass, "THROW_INVOKING_METHOD").get(null));

这段代码我理解是把Spy中Field的值（即AdviceWeaver中对应的Method），再次init回Spy中的对应Field，请问这样做的目的何在？

Greys这段代码的注释是：
        // 无论从哪里取到spyClass，都需要重新初始化一次
        // 用以兼容重新加载的场景
        // 当然，这样做会给渲染的过程带来一定的性能开销，不过能简化编码复杂度
Arthas这段代码的注释是：
        // 初始化间谍, AgentLauncher会把各种hook设置到ArthasClassLoader当中
        // 这里我们需要把这些hook取出来设置到目标classloader当中
我都没有看明白具体是什么意思…请赐教！

**Comment by hengyunabc** [comment]
应该是一个预防的逻辑，正常来说`Spy`是要被bootstrap classloader加载到的，所以其它ClassLoader在加载时，也是加载到同一个类。如果有极端情况下，某些ClassLoader从自己的classpath下面加载到了Spy，则这个`Spy`是不同的类对象，则需要另外init一下。

**Comment by houseyoung** [comment]
@hengyunabc 我理解这种情况应该很罕见吧……绝大多数应用都不会扫到Spy然后加载进去吧？

**Comment by houseyoung** [comment]
@hengyunabc
spy是在bootstrapclasaloader中加载的，其他classloader加载类前，都会先检查bootstrapclasaloader中有没有加载过，有的话就不加载吧？这样spy是没有机会被其他classloader加载吧。

**Comment by hengyunabc** [comment]
> @hengyunabc
> spy是在bootstrapclasaloader中加载的，其他classloader加载类前，都会先检查bootstrapclasaloader中有没有加载过，有的话就不加载吧？这样spy是没有机会被其他classloader加载吧。

不同的ClassLoader实现不一样，可能有各种实现的加载顺序，各种诡异问题都会有。把`Spy`的包名设置为`java.arthas.Spy`也是一定程度避免这个问题。

**Comment by OrezzerO** [comment]
按我的理解,无论Spy由哪个类加载器加载,下面这段代码都是把 这个 Spy 的属性设置成自己属性,感觉没有意义.
```java
Method initMethod = spyClass.getMethod("init", ClassLoader.class, Method.class,
            Method.class, Method.class, Method.class, Method.class, Method.class);
    initMethod.invoke(null, arthasClassLoader,
            FieldUtils.getField(spyClass, "ON_BEFORE_METHOD").get(null),
            FieldUtils.getField(spyClass, "ON_RETURN_METHOD").get(null),
            FieldUtils.getField(spyClass, "ON_THROWS_METHOD").get(null),
            FieldUtils.getField(spyClass, "BEFORE_INVOKING_METHOD").get(null),
            FieldUtils.getField(spyClass, "AFTER_INVOKING_METHOD").get(null),
            FieldUtils.getField(spyClass, "THROW_INVOKING_METHOD").get(null));
```

不知道我的理解哪里有问题? @hengyunabc

**Comment by hengyunabc** [comment]
@OrezzerO 是设置当前ClassLoader加载的Spy类的钩子，纠结这个没有太多意义。
