### ISSUE TITLE
增加开发者视角文档，怎么在idea里面debug arthas? 

### ISSUE THREAD

**Issue by zonghaishang** [alibaba/arthas#41]
想深入研究，后面方便深度参与

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md

**Comment by ralf0131** [comment]
This is divided into several cases:

* If you would like to debug arthas agent, arthas has a debug option in as.sh, it will listen to 8888 by default.
* If you would like to debug arthas core during execution, you have to ensure the target jvm is debuggable. When your target JVM is ready for a debugger to connect, just connect to that JVM using remote debug feature provided by the IDE.
