### ISSUE TITLE
dashboard/watch/monitor/tt/stack/trace support press Q to exit

### ISSUE THREAD

**Issue by zhao41654828** [alibaba/arthas#410]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5.2
* Arthas 版本: 3.0.5
* 操作系统版本:  linux 4.9.0-39-custom
* 目标进程的JVM版本: 1.8.0_112-b15
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤
* dashboard退出

按下 ctrl+c 键之后，直接退出挂载，回到终端
![v02 7c5o 8 809 tqqq gr](https://user-images.githubusercontent.com/4076590/50479310-d91fb880-0a10-11e9-9500-a5f31784303f.png)

我的shell类型：
```
andy@test-udb-03:~$ echo $SHELL
/bin/bash
```

### 期望的结果

期望回到arthas的命令界面。
建议不使用ctrl+c的方式退出，而是使用类似top命令的 输入q的方式来优雅退出，回到arthas命令界面。

**Comment by huanqingdong** [comment]
@ @zhao41654828 是不是trace命令执行后,也存在相同的问题,没有方式退出?
