### ISSUE TITLE
怎么看内存使用情况

### ISSUE THREAD

**Issue by YaoZhichao** [alibaba/arthas#411]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by huluBrother** [comment]
dashboard -n 1 （只显示一次，不然跳动太频繁了）
![image](https://user-images.githubusercontent.com/18010792/50507682-7c2c0d00-0ab9-11e9-829a-7cc5d14cd5d1.png)

heap  堆内存 
ps_eden_space :    对象被创建的时候首先存放的区域
ps_survivor_space :    eden space内存区域中经过垃圾回收后没有被回收的对象
ps_old_gen:     存放新生代中经过多次垃圾回收仍然存活的对象(上面两个都是新生代)
nonheap：   非堆内存(通常说的栈内存)
code_cash:    存放JIT所编译的机器码
metaspace： 永久代

不过这些内存信息似乎不能帮助追踪程序运行时候的数据

**Comment by justein** [comment]
> dashboard -n 1 （只显示一次，不然跳动太频繁了）
> ![image](https://user-images.githubusercontent.com/18010792/50507682-7c2c0d00-0ab9-11e9-829a-7cc5d14cd5d1.png)
> 
> heap 堆内存
> ps_eden_space : 对象被创建的时候首先存放的区域
> ps_survivor_space : eden space内存区域中经过垃圾回收后没有被回收的对象
> ps_old_gen: 存放新生代中经过多次垃圾回收仍然存活的对象(上面两个都是新生代)
> nonheap： 非堆内存(通常说的栈内存)
> code_cash: 存放JIT所编译的机器码
> metaspace： 永久代
> 
> 不过这些内存信息似乎不能帮助追踪程序运行时候的数据

nonheap 怎么能是 栈内存 呢？
