### ISSUE TITLE
thread -n 1 | grep 'main('  文档介绍中，这句话没有和预期不一样呢

### ISSUE THREAD

**Issue by huluBrother** [alibaba/arthas#412]
thread -n 1 | grep 'main(' 
中 ( 是什么意思

![image](https://user-images.githubusercontent.com/18010792/50505297-cb6c4080-0aad-11e9-9f57-e78fbed2103d.png)

[文档](https://alibaba.github.io/arthas/quick-start.html)

**Comment by huluBrother** [comment]
为什么我感觉是他们的文档描述错误呢？

**Comment by hengyunabc** [comment]
你启动的是 arthas-demo ，还是别的进程？

`thread -n 1` 是列出线程 id 是1的线程栈。 `grep main(` 就是找main函数。

没有的话，单独执行 `thread -n 1`，看结果是什么。

**Comment by huluBrother** [comment]
> 你启动的是arthas-demo，还是别的进程？
> 
> `thread -n 1`是列出线程id是1的线程栈。`grep main(`就是找主函数。
> 
> 没有的话，单独执行`thread -n 1`，看结果是什么。

我启动的是 arthas-demo 程序， 
thread | grep ‘main' 查找的是主函数，
thread -n 1 显示的是一个其他的线程
不过执行 thread -n 1 | grep 'main' 却没有任何返回
当然我觉得官网的文档描述出了问题（thread -n 1 | grep 'main(' ）,不过即使我添加了( 依旧没有任何回显，我操作的截图在我的问题中

**Comment by hengyunabc** [comment]
@huluBrother 单独执行 `thread -n 1` 的结果，上面没有。

**Comment by huluBrother** [comment]
> @huluBrother 单独执行 `thread -n 1` 的结果，上面没有。

![image](https://user-images.githubusercontent.com/18010792/50508661-c31c0180-0abd-11e9-82f0-038058326c06.png)

**Comment by spadan** [comment]
> > 你启动的是arthas-demo，还是别的进程？
> > `thread -n 1`是列出线程id是1的线程栈。`grep main(`就是找主函数。
> > 没有的话，单独执行`thread -n 1`，看结果是什么。
> 
> 我启动的是 arthas-demo 程序，
> thread | grep ‘main' 查找的是主函数，
> thread -n 1 显示的是一个其他的线程
> 不过执行 thread -n 1 | grep 'main' 却没有任何返回
> 当然我觉得官网的文档描述出了问题（thread -n 1 | grep 'main(' ）,不过即使我在 main 后面添加了( 字符，依旧没有任何回显，我操作的截图在我的问题中

thread -n 1 按文档说明不是指id为1的线程，而是最繁忙的一个线程；运行 arthas-demo程序要找到main函数，正确命令应该是"thread -n -l | grep main"或"thread 1 | grep main"

**Comment by hengyunabc** [comment]
> > > 你启动的是arthas-demo，还是别的进程？
> > > `thread -n 1`是列出线程id是1的线程栈。`grep main(`就是找主函数。
> > > 没有的话，单独执行`thread -n 1`，看结果是什么。
> > 
> > 
> > 我启动的是 arthas-demo 程序，
> > thread | grep ‘main' 查找的是主函数，
> > thread -n 1 显示的是一个其他的线程
> > 不过执行 thread -n 1 | grep 'main' 却没有任何返回
> > 当然我觉得官网的文档描述出了问题（thread -n 1 | grep 'main(' ）,不过即使我在 main 后面添加了( 字符，依旧没有任何回显，我操作的截图在我的问题中
> 
> thread -n 1 按文档说明不是指id为1的线程，而是最繁忙的一个线程；运行 arthas-demo程序要找到main函数，正确命令应该是"thread -n -l | grep main"或"thread 1 | grep main"

的确是我搞错了 😂，可以提交一个PR来改正这个错误不？

**Comment by huluBrother** [comment]
问题被close 了


zhanghx@smzy.cc
 
发件人： hengyunabc
发送时间： 2019-01-07 10:37
收件人： alibaba/arthas
抄送： huluBrother; Manual
主题： Re: [alibaba/arthas] thread -n 1 | grep 'main(' 文档介绍中，这句话没有和预期不一样呢 (#412)
你启动的是arthas-demo，还是别的进程？
thread -n 1是列出线程id是1的线程栈。grep main(就是找主函数。
没有的话，单独执行thread -n 1，看结果是什么。
我启动的是 arthas-demo 程序，
thread | grep ‘main' 查找的是主函数，
thread -n 1 显示的是一个其他的线程
不过执行 thread -n 1 | grep 'main' 却没有任何返回
当然我觉得官网的文档描述出了问题（thread -n 1 | grep 'main(' ）,不过即使我在 main 后面添加了( 字符，依旧没有任何回显，我操作的截图在我的问题中
thread -n 1 按文档说明不是指id为1的线程，而是最繁忙的一个线程；运行 arthas-demo程序要找到main函数，正确命令应该是"thread -n -l | grep main"或"thread 1 | grep main"
的确是我搞错了 ????，可以提交一个PR来改正这个错误不？

**Comment by hengyunabc** [comment]
我再看了下。文档是没有问题的。 文档里的是 `thread -n -1` ，并不是 `thread -n 1` 。

`thread -n -1` 的意思是，把所有的线程栈都打印出来。
