### ISSUE TITLE
arthas shutdown不会卸载arths加载的类

### ISSUE THREAD

**Issue by sqtds** [alibaba/arthas#415]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.0.6
* 操作系统版本: macOS
* 目标进程的JVM版本: JDK8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. attach到进程
2.然后shutdown
3. 然后再attach同一个进程

### 期望的结果

What do you expected from the above steps？
shutdown的时候卸载arthas加载的类

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
![image](https://user-images.githubusercontent.com/1983203/50536521-4b6ad700-0b90-11e9-98aa-07c50a4a6b35.png)

![image](https://user-images.githubusercontent.com/1983203/50536519-44dc5f80-0b90-11e9-8df3-27c09a3d15ae.png)

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/319

**Comment by sqtds** [comment]
thanks ，明白了
