### ISSUE TITLE
ognl 执行静态方法执行代码报NPE

### ISSUE THREAD

**Issue by moviewang** [alibaba/arthas#417]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.0.5
* 操作系统版本: Linux 4.9.0-0.bpo.6-amd64 
* 目标进程的JVM版本: 1.8.0_60
* 执行`arthas-boot`的版本:3.0.5

### 重现问题的步骤

1. ognl '@com.xx.app.media.web.resp.WrappedResult@success()'
Failed to get static, exception message: java.lang.NullPointerException, please check $HOME/logs/arthas/arthas.log for more details.
2.  sm com.bilibili.app.media.web.resp.WrappedResult success
com.bilibili.app.media.web.resp.WrappedResult->success
3. 

### 期望的结果

返回一个对象信息

### 实际运行的结果

throw NPE

```
把异常信息贴到这里
```
![image](https://user-images.githubusercontent.com/7558849/50572006-207fbd80-0df2-11e9-8940-e7d7fbc25eeb.png)

**Comment by moviewang** [comment]
Okay! the ClassLoader is not right tks! the default classloader SystemClassLoader!

**Comment by leiy88** [comment]
有解决办法吗？ 怎么就关闭了呢？

**Comment by leiy88** [comment]
ClassLoader的问题，需要指定。
解决方法:
ognl @yourclass@yourmethod() -c classloader hash
