### ISSUE TITLE
docker里运行  如果主机jvm运行其他进程 会attach到主机进程 而不是docker的jvm进程

### ISSUE THREAD

**Issue by hezudaopp** [alibaba/arthas#418]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.0.5
* 操作系统版本: Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 GNU/Linux
* 目标进程的JVM版本: 
  1. 主机：java version "1.8.0_181"
  2. docker: openjdk version "1.8.0_111"
* 执行`arthas-boot`的版本: 3.0.5.2

### 重现问题的步骤

1. 主机运行canal-server 1.0.22
2. docker运行自定义java程序和arthas-boot，arthas-boot放在/app/arthas-boot.jar
3. 在docker中执行java -jar /app/arthas-boot.jar --repo-mirror aliyun --use-http

### 期望的结果
[INFO] arthas-boot version: 3.0.5.2
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 1 /app/order-service.jar

[INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 1
[INFO] Attach process 1 success.
[INFO] arthas-client connect 127.0.0.1 3658
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki: https://alibaba.github.io/arthas
version: 3.0.5
**pid: 1**
time: 2019-01-02 14:45:08

### 实际运行的结果

[INFO] arthas-boot version: 3.0.5.2
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 1 /app/order-service.jar

[INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 1
[INFO] Attach process 1 success.
[INFO] arthas-client connect 127.0.0.1 3658
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki: https://alibaba.github.io/arthas
version: 3.0.5
**pid: 16251**
time: 2019-01-02 14:35:07

注意加粗的两个pid，host机子停掉canal-server之后，arthas-boot才能attach到pid为1的java进程上。

**Comment by hengyunabc** [comment]
docker 里执行参考下这个：https://alibaba.github.io/arthas/docker.html

**Comment by hezudaopp** [comment]
> docker 里执行参考下这个：https://alibaba.github.io/arthas/docker.html

嗯 就是参考该文档的  只是在docker里运行有以上bug，望能跟进修复。

**Comment by hengyunabc** [comment]
有具体重现的步骤不？

可能和这个issue有关联： https://github.com/alibaba/arthas/issues/362

貌似当java进程pid是1时，在docker里 attach不上。

可以试下用 jstack 可以连接到进程上不。

**Comment by hengyunabc** [comment]
先close掉，有需要再打开

**Comment by tandaly** [comment]
![image](https://user-images.githubusercontent.com/3762187/60633845-26a53400-9e3f-11e9-8c9f-3fd5ac722e05.png)
也遇到同样问题，实际pid是20，运行时是3265，pid 20是docker中的，pid 3265是宿主机的

**Comment by hengyunabc** [comment]
@tandaly 试下先在 3265 的session里执行 shutdown，再重新attach。 如果之前已经有attach成功的话，会直接连接之前的 3658端口。所以看起来是attach错了。

**Comment by tandaly** [comment]
> ![image](https://user-images.githubusercontent.com/3762187/60633845-26a53400-9e3f-11e9-8c9f-3fd5ac722e05.png)
> 也遇到同样问题，实际pid是20，运行时是3265，pid 20是docker中的，pid 3265是宿主机的
![image](https://user-images.githubusercontent.com/3762187/60637398-d9c85a00-9e4c-11e9-96a5-87c8340cbb1e.png)
解决了，要先shutdown结束3265的arthas，再重新进入docker就正确
