### ISSUE TITLE
dump support output directory/dump 指令指定文件存储路径

### ISSUE THREAD

**Issue by nickChenyx** [alibaba/arthas#419]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5

### 新功能

**当前使用:**
```
$ dump java.lang.String
 HASHCODE  CLASSLOADER  LOCATION

 null                   /root/logs/arthas/classdump/java/lang/String.class
```

**希望改进:** 

`dump` 指令可以到处文件到指定目录, 比如我想导出到 `/tmp/classdump` 路径下

**Comment by hengyunabc** [comment]
后面计划重新设计`>`重定向，目前的重定向不太合理。
