### ISSUE TITLE
WebSphere 获取不到 java 进程

### ISSUE THREAD

**Issue by tcsecchen** [alibaba/arthas#426]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： v3.0.5
* Arthas 版本: v3.0.5
* 操作系统版本: Windows10 专业版
* 目标进程的JVM版本: IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit）
* 执行`arthas-boot`的版本: 1. java1.8.0_181  2. IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit）

### 重现问题的步骤

1. 我使用IBM WebSphere，想用arthas进行相关调试，以下为websphere java进程
![default](https://user-images.githubusercontent.com/25191604/50680239-f15f8b00-1041-11e9-9d34-3883a94997a5.png)

2. 执行 arthas-boot.jar，没有相应的java进程，使用IBM自带的java执行arthas-boot.jar也没有
![default](https://user-images.githubusercontent.com/25191604/50680279-13f1a400-1042-11e9-8ac2-2e694b1d2f60.png)

![default](https://user-images.githubusercontent.com/25191604/50680331-40a5bb80-1042-11e9-9989-0c937b1b0aef.png)

### 期望的结果

What do you expected from the above steps？
期望可以获取到websphere的java进程

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by tcsecchen** [comment]
根据 #365 ，我试了一下，tomcat是可以找到对应的进程的
websphere 单独执行jps 找不到对应的pid

**Comment by Hkwaynewing** [comment]
jps找不到websphere的pid有人解决了吗？

**Comment by tcsecchen** [comment]
> 
> 
> jps找不到websphere的pid有人解决了吗？

我暂时还没找到解决方案，Oracle jdk 在bin目录下可以找到 jps 这个东西，但是websphere用的IBM jvm，在它的bin目录下找不到 jps

**Comment by Hkwaynewing** [comment]
https://github.com/alibaba/arthas/issues/426#issuecomment-527026642
是的网上看到的好像IBM 不支持jps. 但是又好像确实有人能在was 上使用arthas
https://github.com/alibaba/arthas/issues/693

**Comment by tcsecchen** [comment]
> 
> 
> [#426 (comment)](https://github.com/alibaba/arthas/issues/426#issuecomment-527026642)
> 是的网上看到的好像IBM 不支持jps. 但是又好像确实有人能在was 上使用arthas
> #693

我看了一下，arthas3.1.1下载后会有as.bat 或者 as.sh，这两个脚本后面可以加进程id。

**Comment by Hkwaynewing** [comment]
> > [#426 (comment)](https://github.com/alibaba/arthas/issues/426#issuecomment-527026642)
> > 是的网上看到的好像IBM 不支持jps. 但是又好像确实有人能在was 上使用arthas
> > #693
> 
> 我看了一下，arthas3.1.1下载后会有as.bat 或者 as.sh，这两个脚本后面可以加进程id。

你试过了可以吗？我试了一下还是不行
`as.bat 13780
JAVA_HOME: C:\Program Files\Java\jdk1.8.0_131
telnet port: 3658
http port: 8563
[ERROR] Start arthas failed, exception stack trace:
java.lang.InternalError: Remote thread failed for unknown reason
        at sun.tools.attach.WindowsVirtualMachine.enqueue(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.execute(WindowsVirtualMachine.java:96)
        at sun.tools.attach.HotSpotVirtualMachine.executeCommand(HotSpotVirtualMachine.java:261)
        at sun.tools.attach.HotSpotVirtualMachine.getSystemProperties(HotSpotVirtualMachine.java:144)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:78)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:113)`
