### ISSUE TITLE
使用trace命令获取方法的执行时间信息，请问每行信息的开头的"+"号有什么特殊意义吗

### ISSUE THREAD

**Issue by keasonsun** [alibaba/arthas#430]
2019-01-07 09:09:20.186
`---ts=2019-01-07 09:09:20;thread_name=main;id=1;is_daemon=false;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@73d16e93
    `---[1.568308ms] com.arthas.Test:method()
        +---[0.09014ms] com.arthas.Test:uuid()
        +---[0.033361ms] com.arthas.Test:getStudent()
        +---[0.001284ms] com.arthas.Student:<init>()
        +---[0.010907ms] com.arthas.Student:getAge()
        `---[0.047155ms] com.arthas.Test:uuidNew()

如上：
"+---" 的"+"号有什么意义吗

**Comment by hengyunabc** [comment]
没啥特殊意义，就是tree的输出。和普通网页上的tree node差不多。
