### ISSUE TITLE
如何使用trace命令对方法进行递归监控

### ISSUE THREAD

**Issue by keasonsun** [alibaba/arthas#437]
trace命命令是否只能监控本方法对**其他方法**调用的耗时，能不能更深一层的监控，显示**其他方法**的调用耗时

**Comment by xuzhiyiYoh** [comment]
**I'm developing a feature that supports smart tracking. Find the max-time-cost method in each trace and tracing it next time. I think it's very convenient.**
Like this :
`trace demo.MathGame run`

![image](https://user-images.githubusercontent.com/48389485/55326296-f9508f00-54b9-11e9-81de-79d49132275f.png)

@hengyunabc
