### ISSUE TITLE
是否进行过性能评估，attach之后对原进程性能有多大的影响呢

### ISSUE THREAD

**Issue by yingqin678** [alibaba/arthas#44]
较多生产环境对性能要求较高，attach之后，对生产的性能影响有没有过分析对比呢？比如这两种场景，对性能影响分别是多少？
>1.只查看进程运行状态
2.查看某个方法或参数值

**Comment by nzomkxia** [comment]
arthas的定位是诊断问题排查，不会长时间attach在进程上，也不会作用在集群，不需要太多考虑对性能的开销

**Comment by ralf0131** [comment]
> 1.只查看进程运行状态

Do you mean the `dashboard` or `thread`  command?  This should be fine, just fetch some information from the system.

> 2.查看某个方法或参数值

If you are watching/tracing a high throughput method, you should expect sudden cpu surge. Since Arthas is going to change the byte code of the method, the JIT compiler of JVM will de-optimized the byte code from native code to interpreting mode, once it detect that change. The actual overhead depends on the concurrency of your method. Otherwise the overhead should be tiny.

**Comment by yingqin678** [comment]
> > 1.只查看进程运行状态
> 
> Do you mean the `dashboard` or `thread` command? This should be fine, just fetch some information from the system.
> 
> > 2.查看某个方法或参数值
> 
> If you are watching/tracing a high throughput method, you should expect sudden cpu surge. Since Arthas is going to change the byte code of the method, the JIT compiler of JVM will de-optimized the byte code from native code to interpreting mode, once it detect that change. The actual overhead depends on the concurrency of your method. Otherwise the overhead should be tiny.

okay，the explaination is understandability，get it!!

**Comment by hengyunabc** [comment]
关于JIT的参考： 

* http://ifeve.com/hotspot-jit/
* https://www.infoq.cn/article/OpenJDK-HotSpot-What-the-JIT

Arthas在执行`trace/watch/tt/monitor` 等命令时，本质上是在method的前后插入代码，会导致原来JVM里JIT编译生成的代码无效，需要退回原来的代码，再重新JIT编译。所以对于并发高的函数调用会调起抖动。

**所以要避免一次性`trace/watch`大量的类。**

建议在线上环境时，集群里选一台负载低的机器来执行分析，如果是只有一台机器，则要小心使用。

**Comment by nihongye** [comment]
事实上，arthas attach时，默认就增强所有的classloader（arthas.properties的arthas.enhanceLoaders=java.lang.ClassLoader），将引起未attach过的JVM进程的JIT失效。所以在负载较高的进程上，在第一次使用arthas attach进程时，可能看到系统负载飙升的现象。

**Comment by hengyunabc** [comment]
> 事实上，arthas attach时，默认就增强所有的classloader（arthas.properties的arthas.enhanceLoaders=java.lang.ClassLoader），将引起未attach过的JVM进程的JIT失效。所以在负载较高的进程上，在第一次使用arthas attach进程时，可能看到系统负载飙升的现象。

默认只增强 `java.lang.ClassLoader#loadClass`这个函数。这个增强是一次性的，考虑到大部分应用都不会在运行时高频调用，所以做了默认处理。 参考：https://github.com/alibaba/arthas/issues/1596

后续如果有更多反馈的话，考虑把这个去掉。

**Comment by fangwentong** [comment]
> 事实上，arthas attach时，默认就增强所有的classloader（arthas.properties的arthas.enhanceLoaders=java.lang.ClassLoader），将引起未attach过的JVM进程的JIT失效。所以在负载较高的进程上，在第一次使用arthas attach进程时，可能看到系统负载飙升的现象。

@hengyunabc  线上系统在使用最近版本的arthas时，也遇到了这个问题：arthas attach就会触发CPU使用率的飙升，服务响应时长、超时问题陡增。原因是RedefineClasses会触发JIT Depotimization，，建议把默认增强ClassLoader的配置给去掉

参考 [VM_RedefineClasses::flush_dependent_code](https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/jdk-11.0.10+7/src/hotspot/share/prims/jvmtiRedefineClasses.cpp#L3864)

```
// Deoptimize all compiled code that depends on this class.
//
// If the can_redefine_classes capability is obtained in the onload
// phase then the compiler has recorded all dependencies from startup.
// In that case we need only deoptimize and throw away all compiled code
// that depends on the class.
//
// If can_redefine_classes is obtained sometime after the onload
// phase then the dependency information may be incomplete. In that case
// the first call to RedefineClasses causes all compiled code to be
// thrown away. As can_redefine_classes has been obtained then
// all future compilations will record dependencies so second and
// subsequent calls to RedefineClasses need only throw away code
// that depends on the class.
/```

**Comment by mapcoding-cn** [comment]
如果以agent的方式启动,会对原生进程产生多大的影响呢?

**Comment by davidzzw** [comment]
> 如果以agent的方式启动,会对原生进程产生多大的影响呢?

为什么没人回答

**Comment by hengyunabc** [comment]
> 如果以agent的方式启动,会对原生进程产生多大的影响呢?

取决于最终执行了哪些命令，影响了哪些class。 如果纯启动，它就是一个 java netty server，基本没什么影响。

**Comment by hexuxu110** [comment]
官方怎么也不给一个性能评估的一个报告 咋没有官方人出来回答

**Comment by kimmking** [comment]
> 官方怎么也不给一个性能评估的一个报告 咋没有官方人出来回答

这是一个复杂问题，不是简单的”用arthas性能会影响xx%“能解释的。

**Comment by qsLI** [comment]
> > 事实上，arthas attach时，默认就增强所有的classloader（arthas.properties的arthas.enhanceLoaders=java.lang.ClassLoader），将引起未attach过的JVM进程的JIT失效。所以在负载较高的进程上，在第一次使用arthas attach进程时，可能看到系统负载飙升的现象。
> 
> @hengyunabc 线上系统在使用最近版本的arthas时，也遇到了这个问题：arthas attach就会触发CPU使用率的飙升，服务响应时长、超时问题陡增。原因是RedefineClasses会触发JIT Depotimization，由于ClassLoader是底层依赖，带来的Depotimization影响面特别大，导致服务性能瞬间降低，建议把默认增强ClassLoader的配置给去掉
> 
> 参考 [VM_RedefineClasses::flush_dependent_code](https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/jdk-11.0.10+7/src/hotspot/share/prims/jvmtiRedefineClasses.cpp#L3864)
> 
> ```
> // Deoptimize all compiled code that depends on this class.
> //
> // If the can_redefine_classes capability is obtained in the onload
> // phase then the compiler has recorded all dependencies from startup.
> // In that case we need only deoptimize and throw away all compiled code
> // that depends on the class.
> //
> // If can_redefine_classes is obtained sometime after the onload
> // phase then the dependency information may be incomplete. In that case
> // the first call to RedefineClasses causes all compiled code to be
> // thrown away. As can_redefine_classes has been obtained then
> // all future compilations will record dependencies so second and
> // subsequent calls to RedefineClasses need only throw away code
> // that depends on the class.
> /```
> ```

首次attach agent，增强类时，由于依赖关系没有记录完全，会flush所有的nmethod，然后重新编译，这个是导致cpu上涨的原因？这个跟增强classloader是不是关系不大？

另外新版本的JDK，要增加-XX:+AlwaysRecordEvolDependencies可以在启动的时候就记录依赖关系
[[JDK-8324241] Always record evol\_method deps to avoid excessive method flushing - Java Bug System](https://bugs.openjdk.org/browse/JDK-8324241)
