### ISSUE TITLE
Arthas如何进行远程连接

### ISSUE THREAD

**Issue by keasonsun** [alibaba/arthas#441]
例如：
 在机器上A 开启arthas依附java程序
如何在机器B上进行远程连接arthas进行操作

**Comment by hengyunabc** [comment]
attach时把 `target-ip` 指定为 `0.0.0.0`，然后就可以远程连接了。可以在其它机器上 `telnet remoteIP 3658`

**Comment by keasonsun** [comment]
> attach时把 `target-ip` 指定为 `0.0.0.0`，然后就可以远程连接了。可以在其它机器上 `telnet remoteIP 3658`

这种方式试过， 依附成功但是连接失败
报错
Connect to telnet server error: 0.0.0.0 3658
java.net.ConnectException :Connection refused

**Comment by cendaifeng** [comment]
你好，想请问 `target-ip` 能否指定一个同环境的内网 ip ，例如：`172.16.0.1`。背景是安全问题，想限制只能在某台虚拟机上操作 Arthas 的功能。 @hengyunabc
