### ISSUE TITLE
trace 命令调用栈没有完全输出整个路径

### ISSUE THREAD

**Issue by ziwenxie** [alibaba/arthas#443]
我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的 issue。

### 环境信息

* Arthas 版本: 3.0.4
* 操作系统版本: Linux version 2.6.32-754.3.5.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Tue Aug 14 20:46:41 UTC 2018
* 目标进程的JVM版本: jdk 1.8

### 问题描述

![image](https://user-images.githubusercontent.com/24546717/51094205-e3e69580-17e5-11e9-8928-c74011d50171.png)

```
$ trace com.keep.personal.data.rpc.provider.SportStatsServiceProvider getTotalStats '#cost>100'
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 153 ms.
`---ts=2019-01-14 10:14:26;thread_name=DubboServerHandler-172.20.1.138:20882-thread-182;id=159;is_daemon=true;priority=5;TCCL=org.springframework.boot.loader.LaunchedURLClassLoader@1e730495
    `---[356.702509ms] com.keep.personal.data.rpc.provider.SportStatsServiceProvider:getTotalStats()
        +---[0.004492ms] org.apache.commons.lang.StringUtils:isEmpty()
        +---[0.003068ms] java.lang.Boolean:valueOf()
        +---[0.256595ms] org.slf4j.Logger:info()
        `---[356.345003ms] com.keep.personal.data.service.datacenter.v3.DataCenterService:getAllTotalStats()
```

### 期望的结果

DataCenterService 下面还有很多逻辑，但是 trace 没有打印出 DataCenterService 下的输出。

![image](https://user-images.githubusercontent.com/24546717/51094227-142e3400-17e6-11e9-8039-29a698f5b01d.png)

**Comment by hengyunabc** [comment]
trace的是`getTotalStats`，自然不会打印`getAllTotalStats`里的调用细节。

**Comment by ziwenxie** [comment]
> trace的是`getTotalStats`，自然不会打印`getAllTotalStats`里的调用细节。

`trac` 定义应该是用来分析整个调用栈中哪个步骤慢？如果整个栈不打印出来，下面具体哪个步骤慢还是不清楚，`getAllTotalStats` 也有可能被很多地方调用。

是不是可以考虑提供一个打印整个调用栈的选项呢？

**Comment by hengyunabc** [comment]
> > trace的是`getTotalStats`，自然不会打印`getAllTotalStats`里的调用细节。
> 
> `trace` 定义应该是用来分析整个调用栈中哪个步骤慢？如果整个栈不打印出来，下面具体哪个步骤慢还是不清楚，`getAllTotalStats` 也有可能被很多地方调用。
> 
> 是不是可以考虑提供一个打印整个调用栈的选项呢？

trace是代价比较贵的，不能随意trace多层。

可以用正则表匹配路径上的多个类和函数。比如：

```
trace -E com.test.ClassA|org.test.ClassB method1|method2|method3
```

**Comment by ziwenxie** [comment]
> > > trace的是`getTotalStats`，自然不会打印`getAllTotalStats`里的调用细节。
> > 
> > 
> > `trace` 定义应该是用来分析整个调用栈中哪个步骤慢？如果整个栈不打印出来，下面具体哪个步骤慢还是不清楚，`getAllTotalStats` 也有可能被很多地方调用。
> > 是不是可以考虑提供一个打印整个调用栈的选项呢？
> 
> trace是代价比较贵的，不能随意trace多层。
> 
> 可以用正则表匹配路径上的多个类和函数。比如：
> 
> ```
> trace -E com.test.ClassA|org.test.ClassB method1|method2|method3
> ```

好的谢谢，请问比如这样写，含义只是一个调用必须包含 `get` 或者 `getFromHBase`。请问有没有办法能正则匹配到这样的结果：想一个调用同时包含 `get` 和 `getFromHbase` 才将其输出？

`trace -E com.keep.personal.data.service.base.impl get|getFromHBase`

![image](https://user-images.githubusercontent.com/24546717/51095190-e77e1a80-17ed-11e9-8eaa-4de479f70cdb.png)

**Comment by wushengxuan** [comment]
![Uploading image.png…]()
确实不方便啊 不知道是按照什么规则来获取调用栈 底下很多业务逻辑的接口没有打印出来啊

**Comment by useraddZYB** [comment]
> > trace的是`getTotalStats`，自然不会打印`getAllTotalStats`里的调用细节。
> 
> `trace` 定义应该是用来分析整个调用栈中哪个步骤慢？如果整个栈不打印出来，下面具体哪个步骤慢还是不清楚，`getAllTotalStats` 也有可能被很多地方调用。
> 
> 是不是可以考虑提供一个打印整个调用栈的选项呢？

这个可以打印整个调用栈
https://github.com/useraddZYB/time-tracker

**Comment by wupflove** [comment]
> > > trace的是`getTotalStats`，自然不会打印`getAllTotalStats`里的调用细节。
> > 
> > 
> > `trace` 定义应该是用来分析整个调用栈中哪个步骤慢？如果整个栈不打印出来，下面具体哪个步骤慢还是不清楚，`getAllTotalStats` 也有可能被很多地方调用。
> > 是不是可以考虑提供一个打印整个调用栈的选项呢？
> 
> 这个可以打印整个调用栈
> https://github.com/useraddZYB/time-tracker

这个Sample 和说明不详细，运行不起来呢

**Comment by useraddZYB** [comment]
> > > > trace的是`getTotalStats`，自然不会打印`getAllTotalStats`里的调用细节。
> > > 
> > > 
> > > `trace` 定义应该是用来分析整个调用栈中哪个步骤慢？如果整个栈不打印出来，下面具体哪个步骤慢还是不清楚，`getAllTotalStats` 也有可能被很多地方调用。
> > > 是不是可以考虑提供一个打印整个调用栈的选项呢？
> > 
> > 
> > 这个可以打印整个调用栈
> > https://github.com/useraddZYB/time-tracker
> 
> 这个Sample 和说明不详细，运行不起来呢

time-tracker readme文档里有我的联系方式，可以加一下细聊

**Comment by ZaynJiang** [comment]
确实很不方便，有时候调用链很复杂，内部可能多个组件都可能耗时长，trace一下就是想知道哪个步骤慢了，这还要一个一个试哪个步骤导致的
