### ISSUE TITLE
arthas-spring-boot-starter

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#444]
1. Support spring boot endpoint, provide a  way to integrate Arthas. 
0. When user send request to `endpoint/arthas/attach`, `arthas-spring-boot-starter` dynamic attach itself.
0. The user can visit Arthas Web Console through the endpoint.

---

starte的工作方式：

1. 应用本身依赖 arthas-agent.jar
1. 利用 `ByteBuddyAgent.install()`取得 `Instrumentation` 对象，然后调用 AgentBootstrap 来初始化
1. 允许用户在spring env里配置变量，比如 arthas.home , arthas.tunnnelServer 等
1. arthas zip 包怎么获取到？ 修复 arthas-packing里的 jar，让它包含整个 arthas zip?

**Comment by superheizai** [comment]
Great idea

**Comment by VancySavoki** [comment]
实现类似 [bistoury](https://github.com/qunarcorp/bistoury)，但 bistoury 的实现方案略重了。

arthas-spring-boot-starter 是个不错的提议，我之前也想做这个，但一直没有时间。如果官方能支持就最好了

**Comment by kezhenxu94** [comment]
@hengyunabc is there anyone already working on this? I'd like to help on this feature, do we have more details about this new feature?

**Comment by Roger3581321** [comment]
麻烦问一下这个功能点是否都实现，还有哪里需要开发？
