### ISSUE TITLE
使用watch命令 没有任何方法调用的相关信息返回 也没报错

### ISSUE THREAD

**Issue by wuwuback1234** [alibaba/arthas#446]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 使用以下地址安装的：
Windows
最新版本，点击下载
https://alibaba.github.io/arthas/manual-install.html
* Arthas 版本:3.0.5
* 操作系统版本: win7 64位
* 目标进程的JVM版本: 
java version "1.6.0_81"
Java(TM) SE Runtime Environment (build 6.1.071)
SAP Java Server VM (build 6.1.071 24.55-b08, Sep 28 2014 00:29:59 - 61_REL - opt
U - windows amd64 - 6 - bas2:226310 (mixed mode))

* 执行`arthas-boot`的版本: 3.0.5

### 重现问题的步骤

1. 执行as.bat 进程编号
2. 执行watch 监测某个方法的返回值
3.在浏览器中测试该方法，无监测结果显示

### 期望的结果

希望能看到方法调用的相关信息

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
没有看到异常信息
```

**Comment by hengyunabc** [comment]
没有输出，说明函数没有被调用。 可以先试下“快速入门”里的`arthas-demo`  https://alibaba.github.io/arthas/quick-start.html

**Comment by wuwuback1234** [comment]
1.试过了，demo中使用demo中以下watch命令是有返回结果的：watch demo.MathGame primeFactors returnObj
2.运行java -jar arthas-boot.jar看不到要监测的java进程ID，但使用as.bat 进程ID，可以attach成功。执行watch如下：
$ watch com.aac.me.client.sfc.ProcessCardPrintServlet doPost params
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually ex

ists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. visit https://github.com/alibaba/arthas/issues/47 for more details.
$ sm com.aac.me.client.sfc.ProcessCardPrintServlet doPost
Affect(row-cnt:0) cost in 3 ms.
$ watch com.aac.me.client.sfc.ProcessCardPrintServlet doPost params
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually ex

ists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. visit https://github.com/alibaba/arthas/issues/47 for more details.
$

**Comment by wuwuback1234** [comment]
执行jad报错：
$ jad com.aac.me.client.sfc.ProcessCardPrintServlet
No class found for: com.aac.me.client.sfc.ProcessCardPrintServlet
Affect(row-cnt:0) cost in 2 ms.
$

**Comment by wuwuback1234** [comment]
![watch](https://user-images.githubusercontent.com/46664002/51102022-3e98e500-1818-11e9-937b-2a890f1ca2cd.png)

**Comment by wuwuback1234** [comment]
jad不报错了，但watch没结果返回，我有测试监测的方法

**Comment by hengyunabc** [comment]
jad和watch有可能冲突，参考这个： https://github.com/alibaba/arthas/issues/390
