### ISSUE TITLE
如何查询资源文件加载路径？

### ISSUE THREAD

**Issue by JerryChin** [alibaba/arthas#447]
下午好，

请问有没有命令可以列出某个资源的加载路径？ 比如：日志配置文件 log4j2.xml

有时候会遇到第三方Jar 打包的日志配置文件被错误加载进来，定位很久才能找到原因。

**Comment by hengyunabc** [comment]
用 `classloader`命令： https://alibaba.github.io/arthas/classloader.html#classloaderresource

**Comment by JerryChin** [comment]
无比感谢。
