### ISSUE TITLE
Can't tell which JVM to debug by looking at the main class name

### ISSUE THREAD

**Issue by JerryChin** [alibaba/arthas#448]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.0.5.2
* Operating System version: Alibaba Cloud Enterprise Linux Server release 17.01.2 (Golden Toad)
* Java version of target JVM: Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
* Java version of JVM used to attach: as above

### Steps to reproduce this issue

1. run `java -jar arthas-boot.jar`

### Expected Result
JVMs which share a common main class name can be distinguished from each other by showing the full path to the application's JAR file.

### Actual Result
* [1]: 2522 com.xxxx.xxxx.Main.Main
  [2]: 1932 com.xxxx.xxxx.Main.Main

Can't tell which JVM to debug.

**Comment by hengyunabc** [comment]
Try to run `java -jar arthas-boot.jar -v'

**Comment by JerryChin** [comment]
@hengyunabc  It's a cool trick!
