### ISSUE TITLE
可否检测方法中任意一行代码的返回值

### ISSUE THREAD

**Issue by a252937166** [alibaba/arthas#449]
watch目前只能检测方法的入参和返回值，trace只能监测执行时间

之后可否会加入查看任意一行代码返回数据的功能呢？

**Comment by generalthink** [comment]
这个就类似于debug ?

**Comment by hengyunabc** [comment]
单行插入，从代码和功能上都是可以支持的。 arthas在考虑做4.0版本，会在字节码操纵上提供更强大的功能。

目前版本可以用 redefine 。

关联的issue： #118
