### ISSUE TITLE
tt命令无法解析到第一个参数为Enum的值

### ISSUE THREAD

**Issue by generalthink** [alibaba/arthas#454]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5.2
* Arthas 版本: 3.0.5.2
* 操作系统版本: Linux 3.10.0-862.9.1.el7.x86_64
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.0.5.2

### 重现问题的步骤

1.  tt -t -n 2 full_controller_name method_name
2. request url in google : http://localhost:8080/notification/TODAY/123456/list?country=ID
3. tt -i index
发现无法确认第一个参数的值具体是哪个枚举值

部分代码:
```java
@Controller
@RequestMapping("/notification")
public class NotificationController {
@RequestMapping(value = "/{category}/{mid}/list", method = RequestMethod.GET)
    @ResponseBody
    public BaseResponse getNotifications(@PathVariable("category") NotificationCategory category, @PathVariable("mid") String mid,@RequestParam(value="country") String country) {

        //返回值并不重要
        return ResonseUtil.success();
    }

}

public enum NotificationCategory {
    RESERVED,
    UGC,
    TODAY,
    ALL;

    public static final NotificationCategory values[] = values();
}

```

但是watch命令可以观察到第一个参数的值
![image](https://user-images.githubusercontent.com/14296063/51242540-2e6d3b00-19bb-11e9-93ae-c32711798f1c.png)

### 期望的结果
希望可以定位到参数到底是哪个枚举

### 实际运行的结果
![image](https://user-images.githubusercontent.com/14296063/51241564-15638a80-19b9-11e9-82c0-c418e4ba04b8.png)

**Comment by hengyunabc** [comment]
目前是当Object输出了，所以把所有的field都输出了。 可以加个`.toString()` ，或者 `.ordinal()` 来获取具体的值。

下个版本支持打印enum。
