### ISSUE TITLE
3.0.5 和 3.0.6-SNAPSHOT  trace,monitor,watch 在openjdk 11下不可用，但sc,sm,jad,jvm 可用

### ISSUE THREAD

**Issue by xindoo** [alibaba/arthas#459]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* 版本： 3.0.5 和 3.0.6-SNAPSHOT
* Arthas 版本: 3.0.5 和 3.0.6-SNAPSHOT均不行 
* 操作系统版本: Linux 2.6.32-279.23.1.mi5.el6.x86_64 
* 目标进程的JVM版本: openjdk version "11" 2018-09-25, OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
* 执行`arthas-boot`的版本: 3.0.5 和 3.0.6-SNAPSHOT

### 重现问题的步骤
sc,sm,jad,jvm 运行正常，但trace monitor watch 提示 No class or method is affected 

### 实际运行的结果
![wechatimg22](https://user-images.githubusercontent.com/3211189/51310626-085e9e00-1a82-11e9-9a3a-ec656fb9c6f3.jpeg)

**Comment by hengyunabc** [comment]
提供一个可执行的demo?

**Comment by xindoo** [comment]
> 提供一个可执行的demo?

不好意思，公司业务代码，不是很方便提供。

**Comment by hengyunabc** [comment]
> > 提供一个可执行的demo?
> 
> 不好意思，公司业务代码，不是很方便提供。

可以构造一个简单demo 。或者在工程里另外写一个简单的类测试下。

**Comment by xindoo** [comment]
EnhancerCommand都不能用，但AnnotatedCommand都用，肯定是增强失败了

**Comment by hengyunabc** [comment]
@xindoo 之前的代码没有 catch asm exception，参考： #462 

可以试下这个版本，如果有异常的话，会在 `~/logs/arthas/arthas.log` 打印出来。

[arthas-3.0.6-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/2771886/arthas-3.0.6-SNAPSHOT-bin.zip)

**Comment by xindoo** [comment]
@hengyunabc   

![2019-01-18 3 40 55](https://user-images.githubusercontent.com/3211189/51372256-7f09a300-1b37-11e9-9fd0-1f5735659d1a.png)

**Comment by xindoo** [comment]
已解决，arthas中写死了使用ASM5，jdk11下需要ASM7。
