### ISSUE TITLE
查看实时对象内存数据的功能

### ISSUE THREAD

**Issue by hehuang139** [alibaba/arthas#465]
如题，是否能获取对象的实时内存数据，可能的做法
dump class -d n -c n  -a -o,可以获取实时的java实例数据，由于一个class的类实例可能会很多，默认只打印一定量的数据，但是可以指定，-a就可以全部打印，-o 可以输出到一个文件上，
输出可以按watch的对象实例输出方式即可

**Comment by LoveFancy** [comment]
同样的需求，求实现。

**Comment by hengyunabc** [comment]
dump只是dump字节码，并不能dump对象。 没有太好的办法可以直接知道jvm里某个类有哪些实例的，除非heapdump。

目前可行的有几种思路：

* watch/trace/monitor/tt 等捕获到参数，返回值等
* 利用ongl表达式来执行一些`static`函数来获取对象。比如dubbo里有很多`static`函数和对象，可以再进一进拿到其它对象
* 利用tt捕获到spring context，然后利用`getBean`来拿到spring bean

**Comment by hehuang139** [comment]
3Q
