### ISSUE TITLE
需求：watch的输出是否可以加上线程名信息？

### ISSUE THREAD

**Issue by hehuang139** [alibaba/arthas#466]
如题，这是一个需求，目前的watch只能查看出入参的值，这已经很不错了，但是如果能加上对应的线程名就更好了，因为经常要定位的问题，不是所有线程都有问题，是个别线程出问题了，这时候就需要输出上有对应的线程名，用来定位特殊线程到底除了什么问题，可以考虑有两种做法
1. 在入参指定的时候可以考虑指定线程名的模式 -t http*
2. 在输出的时候输出对应的线程名信息，第一行可以添加，默认可以不输出，加上一个参数 -s t 显示线程信息这样

**Comment by hengyunabc** [comment]
直接在 watch的表达式里获取到thread即可：

```bash
$ watch demo.MathGame * '{params, @java.lang.Thread@currentThread()}'
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:5) cost in 63 ms.
ts=2019-02-08 03:07:22; [cost=0.207997ms] result=@ArrayList[
    @Object[][isEmpty=false;size=1],
    @Thread[Thread[main,5,main]],
]
```
