### ISSUE TITLE
Trace, watch等命令无法找到对应的类和方法

### ISSUE THREAD

**Issue by ralf0131** [alibaba/arthas#47]
1. 先用sc或者sm搜索对应的类和方法，确认已经被JVM加载
2. 在`$HOME/logs/arthas/arthas.log`中查找有没有Method code too large的异常
3. 存在该异常时，尝试用reset class_name命令对类进行恢复，再进行trace，watch等操作
4. 系统级别的类默认不能进行增强，需要增强是请参考[这里](https://alibaba.github.io/arthas/options.html)的unsafe开关，增强系统类时请谨慎操作
5. 连错了进程，如果之前连过别的进程，且没有shutdown退出，则下次连别的进程时，默认还会连到之前连的进程上。

**Comment by ralf0131** [comment]
另外，数组类、接口类、枚举类以及java.lang.Class/java.lang.Integer/java.lang.reflect.Method等类都是不能进行增强的

**Comment by wh654759860** [comment]
找类需要加报名，如：com.xxx.xxx.xxxController

**Comment by Hearen** [comment]
@ralf0131 cc @hengyunabc 

The funniest thing here is that I am actually using the [watch](https://alibaba.github.io/arthas/en/watch.html) command guide. 

```
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
public class Demo {
    static class Counter {
        private static AtomicInteger count = new AtomicInteger(0);
        public static void increment() {
            count.incrementAndGet();
        }
        public static int value() {
            return count.get();
        }
    }

    public static void main(String[] args) throws InterruptedException {
        while (true) {
            Counter.increment();
            System.out.println("counter: " + Counter.value());
            TimeUnit.SECONDS.sleep(3);
        }
    }
}
```

I can search using `sc Demo*`: 

![image](https://user-images.githubusercontent.com/10859176/45912479-b0f24d80-be54-11e8-8bc4-44565cf56a58.png)

but I cannot use `sc Demo&Counter` or `sc Demo.Counter` as: 

![image](https://user-images.githubusercontent.com/10859176/45912486-d97a4780-be54-11e8-8967-277785e20c1d.png)


And of course, as expected I won't use `watch Demo.Counter value`: 

![image](https://user-images.githubusercontent.com/10859176/45912495-0169ab00-be55-11e8-8658-7453d68147a5.png)

**Comment by ralf0131** [comment]
If you would like to search for an inner class, you have to use `sc outer-class$inner-class`.
查找内部类，需要按照如下格式进行 `sc outer-class$inner-class`

**Comment by Crossoverrr** [comment]
直接 sc *Controller*就行

**Comment by ralf0131** [comment]
Need to add English translation.

**Comment by ougyou** [comment]
private methd没法traec到啊    难道得我找到私有方法下想要监控的public method用正则进行一次trace

**Comment by ougyou** [comment]
![image](https://user-images.githubusercontent.com/4386093/50873503-5842c280-13fb-11e9-9600-2e664eec7539.png)
![image](https://user-images.githubusercontent.com/4386093/50873590-8de7ab80-13fb-11e9-94c1-6cc2592fd4ae.png)

reset后又trace还是提示相同的错误，日志还是提示该类还是无法增强，
### **PS：该类有13k行左右。**

**Comment by hengyunabc** [comment]
> ### **PS：该类有13k行左右。**

这个没有办法。JVM本身有限制。

**Comment by ougyou** [comment]
> > ### **PS：该类有13k行左右。**
> 
> 这个没有办法。JVM本身有限制。

这个场景描述的真好，难道jvm在针对我？ 
这个场景和我的问题的区别在哪？  
![image](https://user-images.githubusercontent.com/4386093/50875393-0f8f0780-1403-11e9-8040-199e14fa51e8.png)

**Comment by xiqicode** [comment]
jad: fail to decompile class，caused by java.lang.VerifyError
![image](https://user-images.githubusercontent.com/15064909/54064943-aa199480-4254-11e9-98b3-1ea50f5302f5.png)

**Comment by hengyunabc** [comment]
> jad: fail to decompile class，caused by java.lang.VerifyError

有没有可以重现的Demo

**Comment by xiqicode** [comment]
> > jad: fail to decompile class，caused by java.lang.VerifyError
> 
> 有没有可以重现的Demo

我试试能不能把这个类分离出来

**Comment by hengyunabc** [comment]
@xiqicode 参考这个： https://github.com/alibaba/arthas/issues/675#issuecomment-487856710

**Comment by gong1989313** [comment]
我的类明明有的，为什么用arthas找到类。
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. check arthas log: /home/tomcat/logs/arthas/arthas.log
4. visit https://github.com/alibaba/arthas/issues/47 for more details.

**Comment by deathxlent** [comment]
日常机器可以trace，线上和预发就一直Method code too large，这个怎么理解

**Comment by orclight** [comment]
问题：问啥会链接另外一个进程？pid 确认没有问题

背景：在这台机器上部署了多个程序。

开始能找到，后边过一段时间后找不到了。最后发现连接到了另外一个进程
使用sc *controller*  发现了另外一个进程的类

**Comment by hengyunabc** [comment]
> 问题：问啥会链接另外一个进程？pid 确认没有问题
> 
> 背景：在这台机器上部署了多个程序。
> 
> 开始能找到，后边过一段时间后找不到了。最后发现连接到了另外一个进程
> 使用sc _controller_ 发现了另外一个进程的类

先 shutdown ，或者指定另外的端口。不然会直接连接到之前进程 listen的端口。

**Comment by orclight** [comment]
我把2个进程都重启，解决了

**Comment by orclight** [comment]
> > 问题：问啥会链接另外一个进程？pid 确认没有问题
> > 背景：在这台机器上部署了多个程序。
> > 开始能找到，后边过一段时间后找不到了。最后发现连接到了另外一个进程
> > 使用sc _controller_ 发现了另外一个进程的类
> 
> 先 shutdown ，或者指定另外的端口。不然会直接连接到之前进程 listen的端口。

多谢

**Comment by 18251850675** [comment]
使用watch命令时，怎么区分同一个类中的同名方法呢？
比如demoMethod(String)和demoMethod(String,String)

**Comment by hengyunabc** [comment]
> 使用watch命令时，怎么区分同一个类中的同名方法呢？
> 比如demoMethod(String)和demoMethod(String,String)

参考： https://github.com/alibaba/arthas/issues/434

**Comment by supAllen** [comment]
请问长度限制是多少？我两个controller加起来不到200行。。。

No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. check arthas log: /home/momobot/logs/arthas/arthas.log
4. visit https://github.com/alibaba/arthas/issues/47 for more details.

**Comment by HelloJRay** [comment]
想要使用watch命令监控第三方包内的方法，但是一直找不到该类。请问这种情况是什么问题导致的，可以怎么解决？

具体执行命令详情如下：
$ sm *InfluxDB*
org.influxdb.InfluxDB$LogLevel <init>(Ljava/lang/String;I)V
org.influxdb.InfluxDB$LogLevel values()[Lorg/influxdb/InfluxDB$LogLevel;
org.influxdb.InfluxDB$LogLevel valueOf(Ljava/lang/String;)Lorg/influxdb/InfluxDB$LogLevel;
org.influxdb.InfluxDB setConnectTimeout(JLjava/util/concurrent/TimeUnit;)V
org.influxdb.InfluxDB setReadTimeout(JLjava/util/concurrent/TimeUnit;)V
org.influxdb.InfluxDB setWriteTimeout(JLjava/util/concurrent/TimeUnit;)V
org.influxdb.InfluxDB enableBatch(IILjava/util/concurrent/TimeUnit;)Lorg/influxdb/InfluxDB;
org.influxdb.InfluxDB disableBatch()V
org.influxdb.InfluxDB setLogLevel(Lorg/influxdb/InfluxDB$LogLevel;)Lorg/influxdb/InfluxDB;
org.influxdb.InfluxDB ping()Lorg/influxdb/dto/Pong;
org.influxdb.InfluxDB createDatabase(Ljava/lang/String;)V
org.influxdb.InfluxDB deleteDatabase(Ljava/lang/String;)V
org.influxdb.InfluxDB describeDatabases()Ljava/util/List;
org.influxdb.InfluxDB write(Lorg/influxdb/dto/BatchPoints;)V
org.influxdb.InfluxDB write(Ljava/lang/String;Ljava/lang/String;Lorg/influxdb/dto/Point;)V
org.influxdb.InfluxDB query(Lorg/influxdb/dto/Query;)Lorg/influxdb/dto/QueryResult;
org.influxdb.InfluxDB query(Lorg/influxdb/dto/Query;Ljava/util/concurrent/TimeUnit;)Lorg/influxdb/dto/QueryResult;
org.influxdb.InfluxDB version()Ljava/lang/String;
org.influxdb.InfluxDBFactory <init>(Ljava/lang/String;I)V
org.influxdb.InfluxDBFactory values()[Lorg/influxdb/InfluxDBFactory;
org.influxdb.InfluxDBFactory valueOf(Ljava/lang/String;)Lorg/influxdb/InfluxDBFactory;
org.influxdb.InfluxDBFactory connect(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/influxdb/InfluxDB;
Affect(row-cnt:22) cost in 74 ms.
$ watch org.influxdb.InfluxDB query "{returnObj}" -x 2
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. check arthas log: /root/logs/arthas/arthas.log
4. visit https://github.com/alibaba/arthas/issues/47 for more details.

**Comment by gitzhoujw** [comment]
5000多行的类，还有子类，报too large了

**Comment by hengyunabc** [comment]
jdk8后的default 函数参考： https://github.com/alibaba/arthas/issues/1105

**Comment by wangliguang517** [comment]
[arthas@25752]$ watch java.util.concurrent.ThreadPoolExecutor isTerminated "{params,returnObj}" -x 2
No class or method is affected, try:
1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
2. reset CLASS_NAME and try again, your method body might be too large.
3. check arthas log: /home/jboss/logs/arthas/arthas.log
4. visit https://github.com/alibaba/arthas/issues/47 for more details.
[arthas@25752]$ sm java.util.concurrent.ThreadPoolExecutor isTerminated
java.util.concurrent.ThreadPoolExecutor isTerminated()Z
Affect(row-cnt:1) cost in 12 ms.

**Comment by yjqg6666** [comment]
> [arthas@1768]$ watch com.company.login.servlet.LoginValidServlet info
> Affect(class count: 0 , method count: 0) cost in 29 ms, listenerId: 2
> No class or method is affected, try:
> 1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
> 2. reset CLASS_NAME and try again, your method body might be too large.
> 3. check arthas log: /home/user/logs/arthas/arthas.log
> 4. visit https://github.com/alibaba/arthas/issues/47 for more details.

> [arthas@1768]$ sc com.company.login.servlet.LoginValidServlet
>com.company.login.servlet.LoginValidServlet
> Affect(row-cnt:1) cost in 12 ms.

> [arthas@1768]$ sm com.company.login.servlet.LoginValidServlet
> com.company.login.servlet.LoginValidServlet <init>()V
> com.company.login.servlet.LoginValidServlet service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V
> com.company.login.servlet.LoginValidServlet info(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V
> com.company.login.servlet.LoginValidServlet init()V
> Affect(row-cnt:9) cost in 14 ms.



log:
> 2020-09-14 19:14:07 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class com.company.login.servlet.LoginValidServlet]
> 2020-09-14 19:14:07 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -the classloader can not load SpyAPI, ignore it. classloader: org.apache.catalina.loader.ParallelWebappClassLoader, className: com/company/login/servlet/LoginValidServlet
> 2020-09-14 19:14:07 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -Success to batch transform classes: [class com.company.login.servlet.LoginValidServlet]

**Comment by wangyufei123** [comment]
2020-11-15 22:55:57 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -Success to batch transform classes: [class weaver.login.VerifyLogin]
2020-11-15 23:05:27 [arthas-command-execute] INFO  c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class weaver.login.VerifyLogin]
2020-11-15 23:05:27 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -the classloader can not load SpyAPI, ignore it. classloader: com.caucho.loader.EnvironmentClassLoader, className: weaver/login/VerifyLogin

你好，在使用monitor的时候有这样的一个问题

**Comment by hengyunabc** [comment]
> 2020-11-15 22:55:57 [arthas-command-execute] INFO c.t.arthas.core.advisor.Enhancer -Success to batch transform classes: [class weaver.login.VerifyLogin]
> 2020-11-15 23:05:27 [arthas-command-execute] INFO c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class weaver.login.VerifyLogin]
> 2020-11-15 23:05:27 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -the classloader can not load SpyAPI, ignore it. classloader: com.caucho.loader.EnvironmentClassLoader, className: weaver/login/VerifyLogin
> 
> 你好，在使用monitor的时候有这样的一个问题

这是因为 com.caucho.loader.EnvironmentClassLoader 不支持加载 append 到 bootstrap classloader里的jar，是它的实现问题。后面arthas会尝试支持这种情况，目前不支持。

**Comment by y3030434** [comment]
> > 2020-11-15 22:55:57 [arthas-command-execute] INFO c.t.arthas.core.advisor.Enhancer -Success to batch transform classes: [class weaver.login.VerifyLogin]
> > 2020-11-15 23:05:27 [arthas-command-execute] INFO c.t.arthas.core.advisor.Enhancer -enhance matched classes: [class weaver.login.VerifyLogin]
> > 2020-11-15 23:05:27 [arthas-command-execute] ERROR c.t.arthas.core.advisor.Enhancer -the classloader can not load SpyAPI, ignore it. classloader: com.caucho.loader.EnvironmentClassLoader, className: weaver/login/VerifyLogin
> > 你好，在使用monitor的时候有这样的一个问题
> 
> 这是因为 com.caucho.loader.EnvironmentClassLoader 不支持加载 append 到 bootstrap classloader里的jar，是它的实现问题。后面arthas会尝试支持这种情况，目前不支持。

我这里报的是 the classloader can not load SpyAPI, ignore it. classloader: org.eclipse.jetty.webapp.WebAppClassLoader, className: com/xxx$

请问也是因为.jetty.webapp.WebAppClassLoader 不支持加载append 到 bootstrap classloader里的jar的原因吗？

**Comment by hengyunabc** [comment]
> 我这里报的是 the classloader can not load SpyAPI, ignore it. classloader: org.eclipse.jetty.webapp.WebAppClassLoader, className: com/xxx$
> 
> 请问也是因为.jetty.webapp.WebAppClassLoader 不支持加载append 到 bootstrap classloader里的jar的原因吗？

是的

**Comment by holylinlhl** [comment]
请问，如果要watch的方法的包名里包含了中文字符，arthas控制台会显示乱码，从而无法监控此类的方法，怎么办？

**Comment by xiezhaokun** [comment]
不能直接这样使用吗？
```
trace --skipJDKMethod false java.text.SimpleDateFormat initialize
```

**Comment by hengyunabc** [comment]
> 不能直接这样使用吗，jdk的类都不能trace吗？
> 
> ```
> trace --skipJDKMethod false java.text.SimpleDateFormat initialize
> ```

仔细看issue里的说明，要打开 unsafe 开关。

**Comment by Likes123** [comment]
![image](https://user-images.githubusercontent.com/27464148/114208506-216c0600-9990-11eb-9a67-75c53cc01816.png)

**Comment by LancCJ** [comment]
resolve my question, point 5

**Comment by Code1157** [comment]
> 我的类明明有的，为什么用arthas找到类。 No class or method is affected, try:
> 
> 1. sm CLASS_NAME METHOD_NAME to make sure the method you are tracing actually exists (it might be in your parent class).
> 2. reset CLASS_NAME and try again, your method body might be too large.
> 3. check arthas log: /home/tomcat/logs/arthas/arthas.log
> 4. visit [No class or method is affected/Trace, watch等命令无法找到对应的类和方法 #47](https://github.com/alibaba/arthas/issues/47) for more details.

![image](https://user-images.githubusercontent.com/42890567/205230947-8dbb29dd-ecfd-4c9d-8dd2-a0f27de84017.png)
你可以使用这条命令启动arthas，注意最后面的是服务ID（不是端口号）。在cmd用你启动的项目的port去查服务ID，而不是直接使用IDEA的服务ID，那样没有用。

**Comment by zhougit86** [comment]
stack sun.misc.Unsafe allocateMemory.   是不是native. 方法不能监控

**Comment by hengyunabc** [comment]
pinpoint 里的类参考：

https://github.com/alibaba/arthas/issues/2452

**Comment by hanbert** [comment]
[arthas@1105]$ sm -d com.alibaba.common.lang.enumeration.Enum createEnum
process class failed: com.iwallet.biz.core.enums.InstitutionEnum, error: java.lang.NoClassDefFoundError: com/alibaba/common/resourcebundle/ResourceBundle

类已经确认被加载了，但是确认某个方法的时候，报错了。。。

2024-01-24 21:59:40 [arthas-command-execute] ERROR c.t.a.c.c.k.SearchMethodCommand -process class failed: com.iwallet.biz.core.enums.InstitutionEnum, error: java.lang.NoClassDefFoundError: com/alibaba/common/resourcebundle/ResourceBundle
java.lang.NoClassDefFoundError: com/alibaba/common/resourcebundle/ResourceBundle
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
        at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2727)
        at com.taobao.arthas.core.command.klass100.SearchMethodCommand.process(SearchMethodCommand.java:138)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:385)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.alibaba.common.resourcebundle.ResourceBundle
        at com.alipay.sofa.loader.fast.FastURLClassLoader.findClass(FastURLClassLoader.java:128)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at com.alipay.sofa.loader.fast.FastLaunchedURLClassLoader.loadClass(FastLaunchedURLClassLoader.java:116)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 15 common frames omitted

**Comment by gg159753** [comment]
trace org.mybatis.spring.transaction.SpringManagedTransaction getConnection  -n 5 --skipJDKMethod false
在应用重启后  mybatis下的很多类不能被trace/watch  。看了下也不是动态代理。
只要执行过一次相关代码  就可以trace到了  很奇怪

**Comment by zijiacj** [comment]
01 2026-02-06 14:52:08.040 WARN [as-command-execute-daemon:arthas] [] [] [] transform loader[org.springframework.boot.loader.launch.LaunchedClassLoader@9807454]:class[com/oceanbase/odc/service/session/util/DBSchemaExtractor] failed.
java.lang.IllegalArgumentException: Unsupported class file major version 61
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
        at com.taobao.arthas.core.advisor.Enhancer.transform(Enhancer.java:117)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
        at com.taobao.arthas.core.advisor.Enhancer.enhance(Enhancer.java:304)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.enhance(EnhancerCommand.java:111)
        at com.taobao.arthas.core.command.monitor200.EnhancerCommand.process(EnhancerCommand.java:66)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:370)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
01 2026-02-06 14:52:08.188 INFO [as-command-execute-daemon:arthas] [] [] [] Success to batch transform classes: [class com.oceanbase.odc.service.session.util.DBSchemaExtractor]
老师，帮忙看下，我这个trace失败的原因是啥
