### ISSUE TITLE
输入编号后 ssh 断开连接

### ISSUE THREAD

**Issue by toohandsome** [alibaba/arthas#471]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.0.5.2
* 操作系统版本: Alpine 3.7
* 目标进程的JVM版本: openjdk 1.8

### 重现问题的步骤

1. 运行 java -jar arthas-boot.jar
2. 选择编号
3. ssh 断开
[![kkMbA1.png](https://s2.ax1x.com/2019/01/22/kkMbA1.png)](https://imgchr.com/i/kkMbA1)
### 期望的结果

正常运行

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
bxfxgkpt-yhd:~# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.0.5.2
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 3296 xxx1.jar
  [2]: 2913 xxx2.jar
  [3]: 2882 xxx3.jar
  [4]: 3459 xxx4.jar
  [5]: 3427 xxx5.jar
  [6]: 3207 xxx6.jar
  [7]: 3081 xxx7.jar
  [8]: 2794 xxx8.jar
  [9]: 3371 xxx9.jar
  [10]: 2703 xxx10.jar
  [11]: 3151 xxx11.jar
  [12]: 2834 xxx12.jar
  [13]: 3989 xxx13.jar
  [14]: 2748 xxx14.jar
14
[INFO] arthas home: /root/.arthas/lib/3.0.5/arthas
[INFO] Try to attach process 2748

Connection closed by foreign host.

Disconnected from remote host(192.168.2.29:22) at 16:53:39.

Type `help' to learn how to use Xshell prompt.
[c:\~]$ 

```

**Comment by hengyunabc** [comment]
参考下这个： https://github.com/alibaba/arthas/issues/362 ，可能是docker里的进程1号进程直接退出了，然后整个docker退出了。

**Comment by toohandsome** [comment]
> 参考下这个： #362 ，可能是docker里的进程1号进程直接退出了，然后整个docker退出了。

你好，我未使用docker

**Comment by hengyunabc** [comment]
试下 `as.sh` ，查看下 ~/logs/arthas 下面的日志。

**Comment by toohandsome** [comment]
> 试下 `as.sh` ，查看下 ~/logs/arthas 下面的日志。

bxfxgkpt-yhd:~/.arthas/lib/3.0.5/arthas# sh as.sh 
as.sh: line 16: syntax error: bad substitution
Error: telnet is not installed. Try to use java -jar arthas-boot.jar
bxfxgkpt-yhd:~/.arthas/lib/3.0.5/arthas#

**Comment by hengyunabc** [comment]
@toohandsome Alpine 3.7 ，这个一般是docker里的？ 另外，Alpine下面的sh不支持一些bash语法，所以`as.sh`跑不了😂 

建议换一个新环境，试下arthas-demo： https://alibaba.github.io/arthas/quick-start.html

或者docker下试下这个： https://alibaba.github.io/arthas/docker.html

**Comment by toohandsome** [comment]
> @toohandsome Alpine 3.7 ，这个一般是docker里的？ 另外，Alpine下面的sh不支持一些bash语法，所以`as.sh`跑不了😂
> 
> 建议换一个新环境，试下arthas-demo： https://alibaba.github.io/arthas/quick-start.html
> 
> 或者docker下试下这个： https://alibaba.github.io/arthas/docker.html

我们虚拟机是这个系统的，没有用docker. 但是有些可以，初步推测。springcloud 项目会断开，springboot 项目可以运行。

**Comment by hengyunabc** [comment]
先close掉，有需要的话再重新打开
