### ISSUE TITLE
k8s下主项目的Pid为1，arthas无法进入这个pid

### ISSUE THREAD

**Issue by l308718280** [alibaba/arthas#474]
### 环境信息

* K8s
* 主进程PID：1

### 重现问题的步骤

* java -jar arthas-boot.jar
* 输入PID：1

### 期望的结果

* 进入并且可以监听

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
![image](https://user-images.githubusercontent.com/29219230/51668282-d22e9a80-1ffc-11e9-937a-5b69f8fa75ab.png)

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/362
