### ISSUE TITLE
windows 上启动 报错  [INFO] Can not find java process.

### ISSUE THREAD

**Issue by yancheng199287** [alibaba/arthas#475]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

执行命令java -jar arthas-boot.jar
报错
$ java -jar arthas-boot.jar
[INFO] Can not find java process. Try to pass pid in command line.
Please select an avaliable pid.

**Comment by yancheng199287** [comment]
我已经启动我的java程序了

**Comment by hengyunabc** [comment]
用 jps ，找不到就没办法了。  参考这个： https://github.com/alibaba/arthas/issues/365

**Comment by huijava** [comment]
安装java-1.X.X-openjdk-devel这个包，找到jps就不会报这个错了
