### ISSUE TITLE
arthas实践 -- sbt Missing scala-library.jar

### ISSUE THREAD

**Issue by x334085347** [alibaba/arthas#477]
+ 在使用sbt构建一个spark 的项目的时候 遇到一个很奇怪的问题 Missing scala-library.jar 如下图. 按理来说如果少jar包sbt 会自动去下载的 这个就很奇怪了. 
![](https://upload-images.jianshu.io/upload_images/12185580-d25c1947c42cd595.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

+ 于是想到用arthas 看一下.首先在arthas中用jad反编译了下scala.sys.pachage\$ 的代码 .
```
$ jad -c 42a57993 "scala.sys.package$"

ClassLoader:
+-sun.misc.Launcher$AppClassLoader@42a57993
  +-sun.misc.Launcher$ExtClassLoader@10d307f1

Location:
/usr/local/Cellar/sbt/1.2.8/libexec/bin/sbt-launch.jar

/*
 * Decompiled with CFR 0_132.
 */
package scala.sys;

import scala.runtime.Nothing$;
import scala.sys.SystemProperties;

public final class package$ {
    public static final package$ MODULE$;

    private package$() {
        MODULE$ = this;
    }

    static {
        new scala.sys.package$();
    }

    public static SystemProperties props() {
        return new SystemProperties();
    }

    public static Nothing$ error(String string) {
        throw new RuntimeException(string);
    }
}

Affect(row-cnt:1) cost in 361 ms.
```
+  这里的error只是抛了个异常 没有其他的东西. 那只能在堆栈中往上继续找. 看到sbt.Defaults\$.file\$1这个方法比较像. 继续反编译看下代码
这块反编译代码比较长 , 所以可以将结果是保存到一个文件中
```
$ jad "sbt.Defaults$" >> &
job id  : 10
cache location  : /Users/.../logs/arthas-cache/27659/10
```
在logs/arthas-cache/27659/10文件中找到file$1这个方法
```
 841     private static final File file$1(String id, ConfigurationReport toolReport$1) {
 842         return (File)Defaults$.files$1(id, toolReport$1).headOption().getOrElse(() -> package$.MODULE$.error(new StringContext((Seq)Predef$.MODULE$.wrapRefArray(new String[]     {"Missing ", ".jar"})).s((Seq)Predef$.MODULE$.genericWrapArray(new Object[]{id}))));
 843     }
```
+ 上面这块代码粗略一看 是找文件, 如果文件没找到就会抛出一个missing 的异常 . 
+ 于是 使用下面的命令看一下传的入参
```
watch -b -x 4 "sbt.Defaults$" "file$1" params
```
+ 果然在参数中找到了scala-library字样 并且还有这个jar包路径.
![](https://upload-images.jianshu.io/upload_images/12185580-bca402e641b9fad8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

+ 那继续我们去这个路径下看下 , 如下图确实少了jar文件. 但是目录是有的. 这很有可能是以前下载jar文件时中断了, 导致jar包没有但是目录还在
![](https://upload-images.jianshu.io/upload_images/12185580-c4f53a55fe429281.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

+ 那处理就很简单. 把这个目录删掉. 重新构建. 重新构建 sbt就会自动下载jar包了 问题解决了...
![](https://upload-images.jianshu.io/upload_images/12185580-9c87c2a6d54fadb8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

[原文链接](https://www.jianshu.com/p/064dc8cf9eb0)

**Comment by ChetWang** [comment]
实践是好实践。
但貌似解决这个问题绕了地球一大圈。

**Comment by x334085347** [comment]
> 但貌似解决这个问题绕了地球一大圈

有什么更好的办法 , 也可以交流下

**Comment by ChetWang** [comment]
一般maven或sbt报找不到jar或class，不都应该第一时间去下载目录核对一下么？

**Comment by x334085347** [comment]
是的 , 你看我解决问题的步骤就是 删掉那个无效的目录.   然后sbt 就会自动去下载了

**Comment by hengyunabc** [comment]
个人愚见，排查问题的过程，是一个不断学习的过程。积累的经验对以后查问题很有帮助。每个人都有自己的知识图谱，都有自己不同的解决问题思路，互相学习也很有好处。😄

**Comment by zhoushuo19850509** [comment]
本文内容：通过arthas jad /watch命令解决一个jar包依赖缺失的问题。这个问题我们之前碰到过很多次了：maven下载某个依赖的过程中，发生了异常，比如IDE关闭、机器重启、依赖版本不对，等等，导致依赖目录创建了、各种索引文件也下载成功了，但是依赖jar包没有下载完整的问题。这会导致后续这个版本的依赖死活没法下载、应用没法正常编译的问题。解决方案也很直接，直接删除这个jar包所在的目录，然后重新编译就行了。
虽然这个问题本身不难，依托我们之前的编译经验能够直接解决。但是，本文通过arthas jad /watch命令实践，提供了一套解决疑难杂症的思路：反编译+监控方法参数；同时，还触及了sbt/maven工具下载依赖的实现逻辑，还是很有收获的。
