### ISSUE TITLE
为什么不支持对 method 的全限定名进行 watch 呢，`class + method` 的方式没法区分重载的 method 啊

### ISSUE THREAD

**Issue by asdf2014** [alibaba/arthas#478]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： latest
* Arthas 版本:  latest
* 操作系统版本:  linux
* 目标进程的JVM版本: jdk8
* 执行`arthas-boot`的版本: latest

### 重现问题的步骤

A#a(int)
A#a(String)

1. watch A a 无法区分 #a(int) 还是 A#a(String)

### 期望的结果

使用全限定名进行 watch，例如 watch A#a(int)

### 实际运行的结果

无

**Comment by hengyunabc** [comment]
参考这个： #434
