### ISSUE TITLE
如何输出elasticsearchTemplate.client.settings的信息？

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#479]
**背景**
一台服务器上有两个应用 ES同样的配置（但es客户端版本不一样）  一个可以 一个报错：NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.28.70.38}{10.28.70.38:9300}]]

**需求**
想直接通过arthas对比两个应用的org.springframework.data.elasticsearch.core.ElasticsearchTemplate的配置到底哪里不一样

<img width="602" alt="screen shot 2019-01-26 at 15 09 46" src="https://user-images.githubusercontent.com/4953871/51784233-90c6f800-2180-11e9-8a60-13ed48368936.png">

（正常的那个应用中没有这一项：`client.transport.sniff`）
问： 如何输出elasticsearchTemplate.client.settings的信息？

**Comment by hengyunabc** [comment]
参考: https://github.com/alibaba/arthas/issues/11
