### ISSUE TITLE
watch 命令可以观察方法内的局部变量吗？

### ISSUE THREAD

**Issue by liermao12** [alibaba/arthas#486]

**Comment by hengyunabc** [comment]
目前是函数的入参，返回值，异常。想看局部变量，可以用 `redefine` 命令热更新代码。

**Comment by cxmshine** [comment]
> 目前是函数的入参，返回值，异常。想看局部变量，可以用 `redefine` 命令热更新代码。

请问大佬，您这里说的通过redefine命令热更新代码来观察方法内的局部变量，是指加一句类似log.info("当前操作人operator:{}", operator); 这样的代码，再去查看日志吗？我查看了redefine命令，似乎无法像watch命令那样，直接观测？

**Comment by hengyunabc** [comment]
> > 目前是函数的入参，返回值，异常。想看局部变量，可以用 `redefine` 命令热更新代码。
> 
> 请问大佬，您这里说的通过redefine命令热更新代码来观察方法内的局部变量，是指加一句类似log.info("当前操作人operator:{}", operator); 这样的代码，再去查看日志吗？我查看了redefine命令，似乎无法像watch命令那样，直接观测？

是的，直接加一行 `System.out.println("");`，本地编译后，把新的 `.class`传到服务器上，再redefine。看redefine的wiki。
