### ISSUE TITLE
WebConsole怎样修改默认的ip 127.0.0.1

### ISSUE THREAD

**Issue by squestc** [alibaba/arthas#488]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by squestc** [comment]
comment

**Comment by hengyunabc** [comment]
目前没有办法，下个版本会支持从 url 传递ip

**Comment by hengyunabc** [comment]
目前 js 已经支持从url里取ip和port里： https://github.com/alibaba/termd/tree/master/src/main/resources/io/termd/core/http

但是代码里没有正确取到path：

https://github.com/alibaba/termd/commit/1dd5c8e74e3fc4747dd884c0750f1e9fe01afea5 

所以目前，需要这个功能支持，可以自己部署一个静态http服务器就可以了。

**Comment by squestc** [comment]
> 目前 js 已经支持从url里取ip和port里： https://github.com/alibaba/termd/tree/master/src/main/resources/io/termd/core/http
> 
> 但是代码里没有正确取到path：
> 
> [alibaba/termd@1dd5c8e](https://github.com/alibaba/termd/commit/1dd5c8e74e3fc4747dd884c0750f1e9fe01afea5)
> 
> 所以目前，需要这个功能支持，可以自己部署一个静态http服务器就可以了。
最新的版本还是不支持呀，上述的http服务怎么和webconsole关联起来

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/678

**Comment by qixiaobo** [comment]
--target-ip
