### ISSUE TITLE
在idea里启动dubbo的provider demo, arthas attach失败

### ISSUE THREAD

**Issue by zhaixiaoxiang** [alibaba/arthas#490]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

![image](https://user-images.githubusercontent.com/11908486/52038279-a8c9bd80-256c-11e9-8f86-58e0582ada8d.png)

**Comment by zhaixiaoxiang** [comment]
不是debug, 是run模式启动的(debug更是不行)

**Comment by zhaixiaoxiang** [comment]
搞定了,  要先shutdown之前的, 然后在attach, 比如这个例子里应该执行
- java -jar arthas-boot.jar 85041 (或者./as.sh 85041) , 进入85041进程
- 然后再执行shutdown
- 再正常执行 java -jar arthas-boot.jar 或./as.sh就没有问题了

有个小建议, arthas的提示信息里, 能不能详细一点, 从提示里完全不知道怎么做, 我还是网上搜了很多别人写的博客才知道怎么做的.

如下是错误信息, 再贴上来供后来人参考:

[INFO] arthas-boot version: 3.0.5.2
[INFO] Process 85041 already using port 8563
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 85041 
  [2]: 99952 com.alibaba.dubbo.demo.provider.Provider
  [3]: 34663 org.apache.zookeeper.server.quorum.QuorumPeerMain
  [4]: 99951 org.jetbrains.jps.cmdline.Launcher
2
[ERROR] Target process 99952 is not the process using port 8563, you will connect to an unexpected process.
[ERROR] If you still want to attach target process 99952, Try to set a different http port by using --http-port argument.
[ERROR] Or try to shutdown the process 85041 using the http port first.

**Comment by hengyunabc** [comment]
😂，这个提示信息很明确了啊。或者需要怎样再改进下。
