### ISSUE TITLE
how to get nested map value by getstatic?

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#502]
There is a static variable in a class
```
private static Map<Short, Map<String, Foo>> realTimeCache;
```
I want to get the value of `realTimeCache.get(1).get("123006")` How to implement it? 

```
$ getstatic com.foo.bond.cache.BondCache realTimeCache '???'
```

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/11

**Comment by hengyunabc** [comment]
Use `ognl` commnad will be better.
