### ISSUE TITLE
Call for document translation

### ISSUE THREAD

**Issue by ralf0131** [alibaba/arthas#51]
The current document is written only in Chinese.
I am planning to translate them into English. 

Any volunteer who is willing to help on this? 

|Table of content|  Assignee |    Status |
| -------------- | --------- | --------- |
|README|@ralf0131|   DONE|
|Installatoin|  @Hearen| DONE|
|Quick start   |@Hearen| DONE|
|Advanced usage| @Hearen| DONE|
|Commands|  @Hearen| DONE|
|Commands/dashboard    |@Hearen| DONE|
|Commands/thread   |@Hearen| DONE|
|Commands/jvm      |@Hearen| DONE|
|Commands/sysprop      |@Hearen| DONE|
|Commands/getstatic        |@Hearen| DONE|
|Commands/sc       |@Hearen| DONE|
|Commands/sm       |@Hearen| DONE|
|Commands/dump     |@Hearen| DONE|
|Commands/jad      |@Hearen| DONE|
|Commands/classloader      |@Hearen| DONE|
|Commands/redefine     |@Hearen| DONE|
|Commands/monitor      |@Hearen| DONE|
|Commands/watch        |@Hearen| DONE|
|Commands/trace        |@Hearen| DONE|
|Commands/stack        |@Hearen| DONE|
|Commands/tt       |@Hearen| DONE|
|Commands/options      |@alfredzouang|   DONE|
|Commands/Basic commands       |@Hearen| DONE|
User cases        
|Release note      |@Hearen| Done #138 |
Questions and Answers     
|CONTRIBUTING    |@Hearen| Done #139 |

**Comment by alaptseu** [comment]
Great idea, seems like a cool tool

**Comment by ralf0131** [comment]
@alaptseu Welcome, please give it a try and provide your feedback. I am happy to help!

**Comment by Hearen** [comment]
@ralf0131 It looks cool, shall we split up`the translation` work for efficiency? I'd like to have a try too :smile:

**Comment by ralf0131** [comment]
I have a concern that not all the users in China could have access to Google spreadsheet. Let's stay on Github.

**Comment by Hearen** [comment]
@ralf0131 Please let us know ***HOW*** when it's ready, let's do it :sunglasses:

**Comment by hengyunabc** [comment]
Hi, English doc directory is `site/src/site/sphinx/en`, Translation PR is welcome. see also #56

**Comment by hengyunabc** [comment]
@Hearen The pages can be visited in https://alibaba.github.io/arthas/ need translate. Other pages do not need, such as `TODO`.

**Comment by Hearen** [comment]
@hengyunabc Got it, I will start from the `Installation` section first.

**Comment by Hearen** [comment]
@hengyunabc To whom it may concern, I am translating the *Quick Start* now.

**Comment by Hearen** [comment]
- [x] [README](https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/README.md)
- [x] [installation](https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/install-detail.md) 
- [x] [quick-start](https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/quick-start.md)

**Comment by muescha** [comment]
Please also for FAQ ( [Questions and answers](https://github.com/alibaba/arthas/labels/question-answered) )

**Comment by hengyunabc** [comment]
Now English website can be visited: https://alibaba.github.io/arthas/en/ , but there are still some commands that need to be translated.

**Comment by ralf0131** [comment]
Please comment if you would like take the any of the translation tasks.

**Comment by alfredzouang** [comment]
Hi, I can take some of the translation tasks, please assign more to me. Thanks.

**Comment by Hearen** [comment]
> Hi, I can take some of the translation tasks, please assign some to me. Thanks.

@alfredzouang 😎 How about start from this: https://alibaba.github.io/arthas/options.html and backwards?

**Comment by richardeee** [comment]
> > Hi, I can take some of the translation tasks, please assign some to me. Thanks.
> 
> @alfredzouang 😎 How about starting from this: https://alibaba.github.io/arthas/options.html and backwards?
> 
> ### Soft Reminder:
> 1. Once you have a `MR`, you record it here to remind others about your progress
> 2. Each file/page be an [independent](https://github.com/alibaba/arthas/pull/88#issuecomment-423037114) `MR`.

Hi @Hearen , I've translated options.md, but don't know how to commit, could you please help? Thanks.

**Comment by Hearen** [comment]
> The current document is written only in Chinese.
> I am planning to translate them into English.
> 
> Any volunteer who is willing to help on this?
> 
> Table of content	Assignee	Status
> README	@ralf0131	DONE
> Installatoin	@Hearen	DONE
> Quick start	@Hearen	DONE
> Advanced usage	@Hearen	DONE
> Commands	@Hearen	DONE
> Commands/dashboard	@Hearen	DONE
> Commands/thread	@Hearen	DONE
> Commands/jvm		@Hearen	DONE
> Commands/sysprop		@Hearen	DONE
> Commands/getstatic		@Hearen	DONE
> Commands/sc		@Hearen	DONE
> Commands/sm		@Hearen	DONE
> Commands/dump		@Hearen	DONE
> Commands/jad		@Hearen	DONE
> Commands/classloader		@Hearen	DONE
> Commands/redefine		@Hearen	DONE
> Commands/monitor		@Hearen	DONE
> Commands/watch		@Hearen	DONE
> Commands/trace		@Hearen	DONE
> Commands/stack		@Hearen	DONE
> Commands/tt		@Hearen	DONE
> Commands/options		@Hearen	DONE
> Commands/Basic commands		@Hearen	DONE
> User cases		
> Release note		
> Questions and Answers		
> CONTRIBUTING

@ralf0131

**Comment by dongqiangqiang** [comment]
I like it ,I want to try

**Comment by Hearen** [comment]
> I like it ,I want to try

@dongqiangqiang Perhaps you can start with **User cases** :smile:

**Comment by anand1st** [comment]
The index.md needs some work. I would like to make some grammatical corrections.

**Comment by hengyunabc** [comment]
The translation work is almost complete, very grateful to every contributor involved in the translation work: @0xflotus, @Hearen, @Huxing Zhang, @beiwei30, @LHearen, @Nithyanandan, @Nitish, @bohr.qiu, @garenchan, @静宏, @alfredzouang, @dongqiangqiang, @anand1st, and many contributors not mentioned.
Special thanks to @Hearen, who translated most of the documentation and made a lot of improvements.
