### ISSUE TITLE
watch 命令下的 条件表达式 -e 与 throwExp是否存在冲突

### ISSUE THREAD

**Issue by CjqDy** [alibaba/arthas#510]
在最新的 3.1.0版本下  -e 似乎不是100%可用
官方提供的demo下
 watch demo.MathGame primeFactors "{params[0],throwExp}" -x 2
不加 -e  见接性也会捕获到抛出的异常信息，
加了 -e  100%捕获到抛出的异常信息

在自己的demo项目中
不加 -e 基本上都是可以捕获异常信息的

所以加不加 -e 似乎没有起到决定的作用

**Comment by hengyunabc** [comment]
这个选项的说明不太对。你测试的是对的。

`-e` 是表示，当抛出异常时才回调。所以加上就是 100% 打印。

但是，不加 `-e`，不管怎样，都会打印。区别是 有一些打印结果里 exception信息是 null
