### ISSUE TITLE
使用3.1.0的arthas发现监控信息无法输出到日志文件，查看arthas.log也没有任务错误。。

### ISSUE THREAD

**Issue by keasonsun** [alibaba/arthas#513]

**Comment by hengyunabc** [comment]
具体什么操作步骤，期望什么结果。 还有旧版本是否符合期望。

**Comment by keasonsun** [comment]
> 具体什么操作步骤，期望什么结果。 还有旧版本是否符合期望。
具体命令如下：
trace -j com.xxx.Class1 helloworld >> Class-helloworld.log &
想让trace的信息输出到log文件中，但是发现~/logs/arthas-catche中并没有日志文件

**Comment by keasonsun** [comment]
@hengyunabc 
具体命令如下：
trace -j com.xxx.Class1 helloworld >> Class-helloworld.log &
想让trace的信息输出到log文件中，但是发现~/logs/arthas-catche中并没有日志文件

**Comment by hengyunabc** [comment]
> @hengyunabc
> 具体命令如下：
> trace -j com.xxx.Class1 helloworld >> Class-helloworld.log &
> 想让trace的信息输出到log文件中，但是发现~/logs/arthas-catche中并没有生成日志文件

新版本里修改了重定向的行为，会直接写到路径所在的文件里。

执行 `pwd` 可以获取到当前路径。 执行 `cat Class-helloworld.log` ，可以查看内容。

**Comment by keasonsun** [comment]
@hengyunabc  是的！找到了，谢谢！
