### ISSUE TITLE
watch  特殊用法 中 ognl不存在size()的方法

### ISSUE THREAD

**Issue by CjqDy** [alibaba/arthas#515]
在查看watch特殊用法的章节中
针对参数的size()方法提示报错
watch failed, condition is: null, express is: params[0].size(), ognl.MethodFailedException: Method "size" failed for object 0 [java.lang.NoSuchMethodException: java.lang.Integer.size()]
官方文档上是没有问题的
$ watch com.taobao.container.Test test "params[0].size()"
Press Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 22 ms.
@Integer[40]

**Comment by hengyunabc** [comment]
这个是文档错误，我更新下。应该是 `params.size()`

**Comment by hengyunabc** [comment]
具体在哪个文档里？我搜索了下没找到

**Comment by hengyunabc** [comment]
额，我理解了。 params 是一个数组，可以用 `params.length` 来获取它的大小。 

#71 的是指 params[0] 它是一个集合，比如函数参数的第一个是一个List，那就可以 `params[0].size()` 知道它的大小。
