### ISSUE TITLE
监控jar包程序启动报错

### ISSUE THREAD

**Issue by zhangyd-c** [alibaba/arthas#52]
```
[root@iz2ze3cbj61sjk0brcnz opt]# ./as.sh 
Arthas script version: 3.0.4
Found existing java process, please choose one and hit RETURN.
* [1]: 1376 xxx.jar
  [2]: 9137 xxx.jar
  [3]: 9163 xxx.jar
2
Calculating attach execution time...
Attaching to 9137 using version 3.0.4...
Error: Unable to access jarfile /root/.arthas/lib/3.0.4/arthas/arthas-core.jar
attach to target jvm (9137) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
```

```
[root@iz2ze3cbj61sjk0brcnz opt]# ./as.sh debug 9137
Arthas script version: 3.0.4
Calculating attach execution time...
Attaching to 9137 using version 3.0.4...
Error: Unable to access jarfile /root/.arthas/lib/3.0.4/arthas/arthas-core.jar
attach to target jvm (9137) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
```

**Comment by ralf0131** [comment]
Please paste if there are any exceptions in `/root/logs/arthas/arthas.log`

**Comment by zhangyd-c** [comment]
@ralf0131 
```
cat: /root/logs/arthas/arthas.log: No such file or directory
```

**Comment by sckghost** [comment]
@ralf0131 我也出现了这种情况
![image](https://user-images.githubusercontent.com/7287929/45661994-83469500-bb32-11e8-9616-01009d79d3cc.png)

**Comment by sckghost** [comment]
1.排查发现/home/confluence/.arthas/lib/3.0.4/下面没有arthas目录 
sudo mkdir -p /home/confluence/.arthas/lib/3.0.4/arthas/
sudo cp /root/.arthas/lib/3.0.4/arthas/arthas-core.jar /home/confluence/.arthas/lib/3.0.4/arthas/
2.再次启动程序报错

# sudo -u confluence -EH ./as.sh
Arthas script version: 3.0.4
Found existing java process, please choose one and hit RETURN.
* [1]: 24055 org.apache.catalina.startup.Bootstrap
1
Calculating attach execution time...
Attaching to 24055 using version 3.0.4...
Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentLoadException: Agent JAR not found or no Agent-Class attribute
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:117)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:84)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:96)
attach to target jvm (24055) failed, check /home/confluence/logs/arthas/arthas.log or stderr of target jvm for any exceptions

**Comment by ralf0131** [comment]
@sckghost Please do not only copy arthas-core.jar, there is a lot more jars which need to be used.

Please try switching to user `confluence` and install Arthas again.

**Comment by ralf0131** [comment]
@zhangyd-c Please check if  `/root/.arthas/lib/3.0.4/arthas/arthas-core.jar` exist, or show me what `/root/.arthas` directory looks like.
