### ISSUE TITLE
使用arthas检测的堆大小和使用visualVM检测的堆大小不一....

### ISSUE THREAD

**Issue by HyattJobs** [alibaba/arthas#522]
![image](https://user-images.githubusercontent.com/19741934/52895440-8a62f380-31f5-11e9-916b-fd161152a004.png)
目测检测的堆的大小不一致(不论是总大小还是已使用).这个是怎么回事?

**Comment by hengyunabc** [comment]
要看具体的API调用的是什么。Arthas里的可以看 DashboardCommand.java 里的。
