### ISSUE TITLE
Windows环境命令窗口经常卡死

### ISSUE THREAD

**Issue by zzzxdm** [alibaba/arthas#523]
使用java -jar arthas-boot.jar 启动，选择任意一个指定的进程。输入任意命令，操作一段时间之后，命令行窗口就卡死，无法输入任何内容。

**Comment by hengyunabc** [comment]
试下 arthas-demo ? 还有具体的jdk版本， os信息等

**Comment by zzzxdm** [comment]
OS: Windows 10
java version "1.8.0_20"


| |
771668756@qq.com
|
|
zzz59687310@163.com
|
签名由网易邮箱大师定制
在2019年2月17日 10:37，hengyunabc<notifications@github.com> 写道：

试下 arthas-demo ? 还有具体的jdk版本， os信息等

**Comment by hengyunabc** [comment]
试下 3.0.5 版本，看有没有问题。 https://github.com/alibaba/arthas/releases/download/arthas-all-3.0.5/arthas-3.0.5-bin.zip

**Comment by zzzxdm** [comment]
> 试下 3.0.5 版本，看有没有问题。 https://github.com/alibaba/arthas/releases/download/arthas-all-3.0.5/arthas-3.0.5-bin.zip

这个版本操作了一段时间，暂没有出现卡死啊
