### ISSUE TITLE
spring boot 项目新增类文件，没法扫描出来

### ISSUE THREAD

**Issue by CjqDy** [alibaba/arthas#531]
在spring boot 项目中新增 Test 类
再三确认 编译成功  生层了对应的class文件
但是通过arthas命令找不到

sc com.example.demo.controller.*
com.example.demo.controller.DemoController
com.example.demo.controller.DemoController$$EnhancerBySpringCGLIB$$8b14f6f4

controller目录下缺少新增的Test.class

**Comment by hengyunabc** [comment]
可能是没加载。试下用 `classloader` 命令来加载： `classloader -c 3d4eac69 --load demo.MathGame`
