### ISSUE TITLE
Arthas的热加载功能redefine安全问题咨询

### ISSUE THREAD

**Issue by weixin6688** [alibaba/arthas#532]
咨询类问题
如题，Arthas的功能非常强大，介绍上来看，通过jad，mc，redefine一套命令的结合，可以直接修改内存的值。但是在生产环境，会有很大的风险。
想咨询一下，有没有什么方法，可以规避掉这类风险？比如能否禁用mc、redefine命令？或者在阿里是如果规避这类风险的？

**Comment by hengyunabc** [comment]
比如，线上应用启动帐号是 admin，当用户可以切换到admin，那么

* 用户可以修改，获取到应用的任意内存值（不管是否java应用）
* 用户可以attach jvm
* attach jvm之后，利用jvm本身的api可以redefine class

所以：

* 安全主要靠用户权限本身的管理
* arthas主要是让jvm redefine更容易了。用户也可以利用其它工具达到同样的效果
* redefine后面会增加日志，输出到 `~/logs/arthas/arthas.log`里
