### ISSUE TITLE
Use apt-get or yum to install Arthas

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#533]
Currently, many users can not download Arthas, they have to send the zip file to their machine.

* [Fedora 新软件维护者指南](https://fedoraproject.org/wiki/Fedora_%E6%96%B0%E8%BD%AF%E4%BB%B6%E7%BB%B4%E6%8A%A4%E8%80%85%E6%8C%87%E5%8D%97)

**Comment by xindoo** [comment]
Arthas目前必须依赖jdk才能运行，应该不会把jdk打到包里把。 这样的话就应该考虑怎么让用户以最低的学习成本指定JAVA_HOME了。

**Comment by sjha2048** [comment]
@hengyunabc I have submitted my proposal, can you please review it?

**Comment by Manas-kashyap** [comment]
I would like to work on this project i have past experience of Debian packaging , so can i work on this ?

**Comment by sjha2048** [comment]
@Manas-kashyap I'll be working on this issue under my Ali SOC project, so can you please look for an another one?

**Comment by Manas-kashyap** [comment]
sure , but let me know if i can help with something ?

**Comment by sjha2048** [comment]
Yeah, sure I can do that, what do you think what would be the best
strategy/way to package a java project, any starting points?

**Comment by Manas-kashyap** [comment]
Well, the first starting point is getting clear with the packaging concepts, for Debian you should know about building packages and testing it with the help of different build tools.

**Comment by Manas-kashyap** [comment]
https://manas-kashyap.github.io/jekyll/2018/11/11/Basic-Guide-for-Debian-Packaging/ , here is a blog on packaging node modules, you can have a test look on how we use tools for packaging things and what is the way of making a package to Debian archive.
