### ISSUE TITLE
关于mc获取classpath的问题

### ISSUE THREAD

**Issue by publisherfk** [alibaba/arthas#535]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1
* 操作系统版本: win7
* 目标进程的JVM版本: jdk1.7
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 有点好奇我们开发人员是怎么获取到classpath的，我看了下classLoader是可选项，猜测应该是通过classLoader获取到URLclassLoader，然后就可以拿到环境变量了。
2. 看过源码，貌似不是这样，用的使jdk的compiler，没怎么看懂。
3. 我们的系统是OSGI架构的，我通过sc获取到了指定类的classloaderhash，然后再用这个classloader去mc，发现编译时，依然报有些类找不到。

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
mc有点复杂，主要功能是 jdk本身的compiler提供的。

对编绎本身来说，它只需要知道这个class的签名，有时还需要method的签名，或者field的签名就可以了。它并不需要某个class本身的源码。

上面提到的三点都是可以通过ClassLoader获取到`Class`对象来知道的。不需要通过`URLclassLoader`来获取的。

**Comment by DeanXW** [comment]
我也是3.1 版本 jdk 1.8  今天进行 内存编译的时候出现Couldn't find a type mirror for class interface javax.validation.Valid ， 是因为 classloader不对吗 ？classLoaderHash是用sc获取到的

**Comment by publisherfk** [comment]
也就是说，没有用到classpath去编译么

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/661
