### ISSUE TITLE
Arthas实践--jad/mc/redefine线上热更新一条龙

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#537]
## 背景

尽管在生产环境热更新代码，并不是很好的行为，很可能导致：热更不规范，同事两行泪。

但很多时候我们的确希望能热更新代码，比如：

> 线上排查问题，找到修复思路了，但应用重启之后，环境现场就变了，难以复现。怎么验证修复方案？

又比如：

> 本地开发时，发现某个开源组件有bug，希望修改验证。如果是自己编译开源组件再发布，流程非常的长，还不一定能编译成功。有没有办法快速测试？

Arthas是阿里巴巴开源的Java应用诊断利器，深受开发者喜爱。

下面介绍利用Arthas 3.1.0版本的 `jad`/`mc`/`redefine` 一条龙来热更新代码。

* Arthas: https://github.com/alibaba/arthas
* jad命令：https://alibaba.github.io/arthas/jad.html
* mc命令：https://alibaba.github.io/arthas/mc.html
* redefine命令：https://alibaba.github.io/arthas/redefine.html

## Arthas在线教程

下面通过Arthas在线教程演示热更新代码的过程。

* [Arthas进阶教程](https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-advanced)

![arthas-online-hotswap](https://user-gold-cdn.xitu.io/2019/2/19/16904b4f7c9ea047?w=1038&h=555&f=png&s=199194)

在例子里，访问 `curl http://localhost/user/0`，会返回500错误：

```js
{
    "timestamp": 1550223186170,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "java.lang.IllegalArgumentException",
    "message": "id < 1",
    "path": "/user/0"
}
```

下面通过热更新代码，修改这个逻辑。

## jad反编译代码

反编译`UserController`，保存到 `/tmp/UserController.java`文件里。

```bash
jad --source-only com.example.demo.arthas.user.UserController > /tmp/UserController.java
```

## 修改反编绎出来的代码

用文本编辑器修改`/tmp/UserController.java`，把抛出异常改为正常返回：

```java
    @GetMapping(value={"/user/{id}"})
    public User findUserById(@PathVariable Integer id) {
        logger.info("id: {}", (Object)id);
        if (id != null && id < 1) {
            return new User(id, "name" + id);
            // throw new IllegalArgumentException("id < 1");
        }
        return new User(id.intValue(), "name" + id);
    }
```

## sc查找加载UserController的ClassLoader

```bash
$ sc -d *UserController | grep classLoaderHash
 classLoaderHash   1be6f5c3
```

可以发现是spring boot的 `LaunchedURLClassLoader@1be6f5c3` 加载的。

## mc内存编绎代码

保存好`/tmp/UserController.java`之后，使用mc(Memory Compiler)命令来编译，并且通过`-c`参数指定`ClassLoader`：

```bash
$ mc -c 1be6f5c3 /tmp/UserController.java -d /tmp
Memory compiler output:
/tmp/com/example/demo/arthas/user/UserController.class
Affect(row-cnt:1) cost in 346 ms
```

## redefine热更新代码

再使用redefine命令重新加载新编译好的`UserController.class`：

```bash
$ redefine /tmp/com/example/demo/arthas/user/UserController.class
redefine success, size: 1
```

## 检验热更新结果

再次访问 `curl http://localhost/user/0`，会正常返回：

```js
{
    "id": 0,
    "name": "name0"
}
```

## 总结

Arthas里 `jad`/`mc`/`redefine` 一条龙来线上热更新代码，非常强大，但也很危险，需要做好权限管理。

比如，线上应用启动帐号是 admin，当用户可以切换到admin，那么

* 用户可以修改，获取到应用的任意内存值（不管是否java应用）
* 用户可以attach jvm
* attach jvm之后，利用jvm本身的api可以redefine class

所以：

* 应用的安全主要靠用户权限本身的管理
* Arthas主要是让jvm redefine更容易了。用户也可以利用其它工具达到同样的效果

最后，Arthas提醒您： **诊断千万条，规范第一条，热更不规范，同事两行泪**。

## Arthas实践系列

* [Alibaba Arthas实践--获取到Spring Context，然后为所欲为](http://hengyunabc.github.io/arthas-spring-context/)
* [Arthas实践--快速排查Spring Boot应用404/401问题](http://hengyunabc.github.io/arthas-spring-boot-404-401/)
* [当Dubbo遇上Arthas：排查问题的实践](http://hengyunabc.github.io/dubbo-meet-arthas/)
* [Arthas实践--使用redefine排查应用奇怪的日志来源](http://hengyunabc.github.io/arthas-redefine-case/)
* [使用Arthas抽丝剥茧排查线上应用日志打满问题](http://hengyunabc.github.io/arthas-logger-problem/)
* [深入Spring Boot：利用Arthas排查NoSuchMethodError](http://hengyunabc.github.io/spring-boot-arthas-NoSuchMethodError/)

**Comment by hengyunabc** [comment]
如果有一些类比较复杂，那么有可能`jad`命令反编绎失败。那么后面的`mc`命令也会失败。

这时，可以在本地修改代码，然后把`.class`文件上传到服务器上。

有一些服务器的权限比较严格，不允许直接上传文件，那么可以用一些技巧来绕过。比如传用`base64`命令：

1. 在本地先转换`.class`文件为base64，再保存为result.txt

```bash
base64 < Test.class > result.txt
```

2. 到服务器上，新建result.txt，复制本地的内容，粘贴再保存

3. 把服务器上的 result.txt还原为`.class`

```
base64 -d < result.txt > Test.class
```

4. 用md5命令计算哈希值，校验是否一致

**Comment by CjqDy** [comment]
mc 内存编译的时候会根据类所在的包路径在服务器生成指定路径，是这样吧？
redefine也是根据这个路径同步更新包里的class文件的

**Comment by hengyunabc** [comment]
> mc 内存编译的时候会根据类所在的包路径在服务器生成指定路径，是这样吧？
> redefine也是根据这个路径同步更新包里的class文件的

mc 不指定输出目录，默认就是target进程的工作目录。可以用`pwd`命令来查看。

**Comment by hengyunabc** [comment]
> mc 内存编译的时候会根据类所在的包路径在服务器生成指定路径，是这样吧？
> redefine也是根据这个路径同步更新包里的class文件的

mc 不指定输出目录，默认就是target进程的工作目录。可以用`pwd`命令来查看。

**Comment by hengyunabc** [comment]
> mc 内存编译的时候会根据类所在的包路径在服务器生成指定路径，是这样吧？
> redefine也是根据这个路径同步更新包里的class文件的

mc 不指定输出目录，默认就是target进程的工作目录。可以用`pwd`命令来查看。

**Comment by VanXD** [comment]
> 如果有一些类比较复杂，那么有可能`jad`命令反编绎失败。那么后面的`mc`命令也会失败。
> 
> 这时，可以在本地修改代码，然后把`.class`文件上传到服务器上。
> 
> 有一些服务器的权限比较严格，不允许直接上传文件，那么可以用一些技巧来绕过。比如传用`base64`命令：
> 
> 1. 在本地先转换`.class`文件为base64，再保存为result.txt
> 
> ```shell
> base64 < Test.class > result.txt
> ```
> 
> 1. 到服务器上，新建result.txt，复制本地的内容，粘贴再保存
> 2. 把服务器上的 result.txt还原为`.class`
> 
> ```
> base64 -d < result.txt > Test.class
> ```
> 1. 用md5命令计算哈希值，校验是否一致

本地修改较为复杂的情况, 检查class是否能热更新可在idea中按ctrl+shift+f9

**Comment by xiexingguang** [comment]
nice

**Comment by wanglei134** [comment]
编译一个类 但是这个类import了其他jar包的类 会报错该怎么办呢

![image](https://user-images.githubusercontent.com/7628014/112341014-0779c480-8cfc-11eb-850f-624983ad8fb9.png)

**Comment by hengyunabc** [comment]
@wangdonghello 看wiki，本地编译上传

**Comment by gaochengyidlmu** [comment]
@hengyunabc 
现在遇到泛型擦除的问题，通过 jad 反编译得到的java文件中，原本是 List<XXXX> para1 的变量，变成了 ArrayList para1，之后 mc 时，就会报错  
Memory compiler error, exception message: Compilation Error
message: incompatible types: java.lang.Object cannot be converted to XXX

这个有没有什么办法可以处理，我现在想通过 arthas 的这个功能，进行批量操作，所以本地编译class行不通。

**Comment by Contentsearch** [comment]
![image](https://github.com/alibaba/arthas/assets/51782090/a0ae4bb5-bfe5-4b25-a492-efda05c03e87)
执行jad 反编译文件返回的是null 什么情况

**Comment by aa57255621** [comment]
> ![image](https://user-images.githubusercontent.com/51782090/251628216-a0ae4bb5-bfe5-4b25-a492-efda05c03e87.png) 执行jad 反编译文件返回的是null 什么情况

写入指定文件不要用./   如果指定目录直接使用绝对地址，如果不指定就不要填

**Comment by MaidSG** [comment]
<img width="637" alt="image" src="https://github.com/user-attachments/assets/be96e964-5737-43b2-9e2e-6d9b2ed3a345">
按流程操作未碰到问题，但是最后验证时并未变更是什么原因，用到了lombok的@Builder注解，编译时生成了两个文件
