### ISSUE TITLE
与greys和jvm-sandbox的区别

### ISSUE THREAD

**Issue by arebya** [alibaba/arthas#54]
在线上问题定位方面，与greys或者jvm-sandbox有什么区别和优势呢

**Comment by ralf0131** [comment]
Thanks for asking, I am planing to add docuemention to explain it.

#### Comparison to Greys

Arthas is derived from Greys, we thank very much for the previous work done by Greys. In Alibaba we made several enhancement:

* Better user experience, e.g. auto complete, command history, auto suggestion, it works more like a **real** terminal. 
* Support both telnet and websocket, they both share the same experience. You can diagnostic both on the command line and on the browser.
* More functionality: e.g. JAD, dashboard, thread, classloader.
* Improved stability: It has been widely used inside Alibaba's production system for 2~3 years, and it is proven to be stable. We've fixed couple of issues found with Greys. Some of them are fixed also by greys (e.g. memory leak when using groovy scripts, we use ognl to replace groovy scripts), some of them are not (e.g. classloader leak issue). And we have done a lot of work to protect Arthas from harming your JVM (e.g. limit the size of output, ensure the resouce are gracefully released after Arthas shutdown, performance optimization and etc.)

**Comment by edagarli** [comment]
Greys have a powerful command call ptrace, which is the combination of trace and tt, while Arthas does not.

why not support  ptrace？

**Comment by edagarli** [comment]
Performance considerations ？

**Comment by shiliang-star** [comment]
Comparison to JVM-sandbox有后续吗?文档链接在哪里?
