### ISSUE TITLE
类里面会有多个实体的对象或者引用，Memory Compiler 如何只对单个java文件进行编译

### ISSUE THREAD

**Issue by CjqDy** [alibaba/arthas#540]
linux环境下  ，  在用到jad和mc配合使用的时候 
反编译出来的java文件在linux环境无法再编译成class文件
里面依赖了多个实体
Memory compiler error, exception message: Compilation Error
line: 85 , message: incompatible types: java.lang.Object cannot be converted to com.example.demo.pojo.SysProvince , 
line: 87 , message: incompatible types: java.lang.Object cannot be converted to com.example.demo.pojo.SysCity , 
line: 89 , message: incompatible types: java.lang.Object cannot be converted to com.example.demo.pojo.SysArea , 
line: 159 , message: incompatible types: java.lang.Object cannot be converted to com.example.demo.pojo.TestReport , 
, please check $HOME/logs/arthas/arthas.log for more details. 

对于线上的现实情况 如果更快的进行修改和热更新

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/535

**Comment by hengyunabc** [comment]
还有这个： https://github.com/alibaba/arthas/issues/537#issuecomment-465496617

**Comment by CjqDy** [comment]
单独的类反编译后再mc是没什么问题
但正常情况下 ，反编译出来的结果会有很多class类找不到，像这种情况怎么处理
这是反编译出来的文件的头部
/*
 * Decompiled with CFR 0_132.
 *
 * Could not load the following classes:
 *  com.example.demo.util.RequestMsg
 *  com.example.demo.util.ResponseMsg
 *  org.aopalliance.aop.Advice
 *  org.springframework.aop.Advisor
 *  org.springframework.aop.SpringProxy
 *  org.springframework.aop.TargetClassAware
 *  org.springframework.aop.TargetSource
 *  org.springframework.aop.framework.Advised
 *  org.springframework.aop.framework.AopConfigException
 *  org.springframework.cglib.core.ReflectUtils
 *  org.springframework.cglib.core.Signature
 *  org.springframework.cglib.proxy.Callback
 *  org.springframework.cglib.proxy.Dispatcher
 *  org.springframework.cglib.proxy.Factory
 *  org.springframework.cglib.proxy.MethodInterceptor
 *  org.springframework.cglib.proxy.MethodProxy
 *  org.springframework.cglib.proxy.NoOp
 */

像这样是没法再mc的

**Comment by CjqDy** [comment]
1.我看文档上说的是复杂的类可能无法反编译成功，这里的复杂有稍微具体的解释吗？
2.正常线上情况是单台部署spring boot项目，如果要热更新一个class文件 如何操作，之前好像说过不支持jar包内的类的热更新？

**Comment by hengyunabc** [comment]
高级教程里有spring boot的例子： https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-advanced

**Comment by CjqDy** [comment]
在对jar包里的class文件，目前测试下来确实无法进行热更新，以后会不会有办法实现？
问题是否就在于redefine无法找到jar里的文件路径

**Comment by hengyunabc** [comment]
> 在对jar包里的class文件，目前测试下来确实无法进行热更新，以后会不会有办法实现？
> 问题是否就在于redefine无法找到jar里的文件路径

jar包 unzip下。
