### ISSUE TITLE
日志执行到 [DEBUG] Repo mirror:aliyun 程序卡主几分钟过去才能attach success

### ISSUE THREAD

**Issue by iceqing** [alibaba/arthas#542]
### 环境信息

* `arthas-boot.jar` 
* Arthas 版本: 3.1.0
* 操作系统版本:  CentOS release 6.3 (Final)
* 目标进程的JVM版本: JDK 8

启动arthas

`java -jar /tmp/arthas/arthas-boot.jar -v --telnet-port 59001 3856`

日志如下：
```
[INFO] arthas-boot version: 3.1.0
[DEBUG] Repo mirror:aliyun
```

每次都会在此处`[DEBUG] Repo mirror:aliyun`卡主1-3分钟，看日志是不是因为请求Repo mirror: aliyun的原因？

**Comment by hengyunabc** [comment]
也有可能是执行 netstat 去查找端口导致的。

**Comment by iceqing** [comment]
有可能，我刚刚抓包，确实没有下载访问接口，可是为何查端口号这么慢？有没有什么解决的方法？

**Comment by hengyunabc** [comment]
在java代码里是调用 `lsof -t -s TCP:LISTEN -i TCP:3658` 来查找已经使有端口的进程。可能这个命令要解析dns，比较慢。

**Comment by iceqing** [comment]
确实执行这个命令接近arthas的启动时间，启动慢的原因应该在这里.

**Comment by hengyunabc** [comment]
考虑做一个改进，异步执行`lsof`，如果超过3秒，就kill掉。

还有一种改进：

* attach成功之后，listen 端口成功的进程，把信息写到某个目录下面，比如`~/.arthas/pid`，记录端口，进程的关系。如果shutdown就把这个文件删除掉。

**Comment by iceqing** [comment]
@hengyunabc 我试着在lsof加入-n参数，停止dns解析，可是还是很慢。
有没有必要切换到ss命令？ss命令很快，几乎1s之内
```
time ss -lptn 'sport = :19235'
Recv-Q Send-Q                                                                    Local Address:Port                                                                      Peer Address:Port 
0      100                                                                           127.0.0.1:19235                                                                                *:*      users:(("java",31723,526))

real	0m0.622s
user	0m0.047s
sys	0m0.375s

```

**Comment by hengyunabc** [comment]
> @hengyunabc 我试着在lsof加入-n参数，停止dns解析，可是还是很慢。
> 有没有必要切换到ss命令？ss命令很快，几乎1s之内
> 
> ```
> time ss -lptn 'sport = :19235'
> Recv-Q        Send-Q      Local Address:Port       Peer Address:Port 
> 0        100                 127.0.0.1:19235      *:*      users:(("java",31723,526))
> 
> real	0m0.622s
> user	0m0.047s
> sys	0m0.375s
> ```

用 lsof 主要是兼容性好。目前没有太好的办法，先 close掉。
