### ISSUE TITLE
增强类在arthas退出后如何还原

### ISSUE THREAD

**Issue by Yuanxiangz** [alibaba/arthas#544]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

如题请问某个类被arthas增强后，等arthas退出应该将这个增强类再还原回原来的代码是吧  我最近在看源码没有看到是如何被还原的  请问在哪儿

**Comment by xindoo** [comment]
字节码还原是调用的Enhancer.reset()方法

**Comment by Yuanxiangz** [comment]
3Q!
