### ISSUE TITLE
arthas-agent support premain

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#550]
https://docs.oracle.com/javase/8/docs/api/java/lang/instrument/package-summary.html

* Premain-Class

> When an agent is specified at JVM launch time this attribute specifies the agent class. That is, the class containing the premain method. When an agent is specified at JVM launch time this attribute is required. If the attribute is not present the JVM will abort. Note: this is a class name, not a file name or path.

**Comment by chenshun00** [comment]
支持 `javaagent` 主要是解决那些痛点。

**Comment by hengyunabc** [comment]
已经支持了。
