### ISSUE TITLE
arthas attach 32位的 jvm报错

### ISSUE THREAD

**Issue by zhenoo123** [alibaba/arthas#552]
1. attach 32位的 jvm

异常信息如下：
com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 32-bit process running under WOW64
![image](https://user-images.githubusercontent.com/5175167/53556125-34d80080-3b7e-11e9-8f34-9fd5e072f277.png)

**Comment by hengyunabc** [comment]
cd 到精确的jdk目录下执行。或者用全路径指定。  `/xxx/jdk64/bin/java -jar arthas-boot.jar`
