### ISSUE TITLE
arthas基础教程跳转404

### ISSUE THREAD

**Issue by justlikeliuen** [alibaba/arthas#553]
### 重现问题的步骤

1. https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-basics
2. 基础教程八个步骤走完以后跳转到404

What do you expected from the above steps？

跳转到进阶教程

### 实际运行的结果
404

**Comment by hengyunabc** [comment]
😂 ，因为没找到 kata在哪里配这个 next。如果有知道的同学，麻烦告知下。

源文件在这里： https://github.com/hengyunabc/katacoda-scenarios/

**Comment by hengyunabc** [comment]
这个貌似无解，先close掉。
