### ISSUE TITLE
2019-03-21 [阿里云峰会-北京]Java诊断利器Arthas排查问题实践 

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#559]
活动链接：

https://yunqi.youku.com/2019/beijing/meeting?spm=a2c4e.11165380.1317296.1#322-16 

北京的同学可以去围观实践下。

**Comment by guohao** [comment]
本次分享的PDF： [Java诊断利器Arthas排查问题实践.PDF](https://github.com/guohao/arthas-demo/blob/master/Java%E8%AF%8A%E6%96%AD%E5%88%A9%E5%99%A8Arthas%E6%8E%92%E6%9F%A5%E9%97%AE%E9%A2%98%E5%AE%9E%E8%B7%B5_%E9%83%AD%E6%B5%A9.pdf)
本次分享的DEMO工程：[arthas-demo](https://github.com/guohao/arthas-demo)
