### ISSUE TITLE
原理问题:redefine怎么处理已实例化的对象?

### ISSUE THREAD

**Issue by reenWYJ** [alibaba/arthas#563]
这是一个关于arthas的问题请教

看了源码,得知redefine是调用 instrumentation.redefine()实现的
在重定义替换class文件后, 是怎么处理之前已经实例化的对象的?

谢谢

**Comment by hengyunabc** [comment]
JVM 本身的功能，看jdk本身的javadoc。`redefine` 只是替换了代码，并不能改变内存，增加field/method之类的。和对象是否实例化没关系。
