### ISSUE TITLE
通过Cloud Toolkit插件使用Arthas一键诊断远程服务器

### ISSUE THREAD

**Issue by nileader** [alibaba/arthas#570]
Cloud Toolkit是一个IDE 插件，帮助开发者更高效地开发、测试、诊断并部署应用。
使用本插件，开发者能够方便地将本地应用一键部署到任意机器，或 ECS、EDAS、Kubernetes；
并支持高效执行终端命令和 SQL 等。

本文介绍在Cloud Tookit插件里使用Arthas来实现一键远程诊断功能。

- <a href='https://www.aliyun.com/product/cloudtoolkit?spm=arthas-site.0.0.0' target="_blank">Cloud Toolkit</a>
- <a href='https://github.com/alibaba/arthas' target="_blank">Arthas</a>

## 插件预览

![arthas](https://user-images.githubusercontent.com/1683936/54509839-e9975d80-4985-11e9-9d34-3abb7a12bf07.gif)

Arthas 的 IntelliJ IDEA 和 Eclipse 插件已经正式发布了，在 IDE 内，提前配置好机器信息，实现对远程机器上的 Java 进程一键诊断。<a href='https://www.aliyun.com/product/cloudtoolkit?spm=arthas-site.0.0.0' target="_blank">了解更多</a>

## IntelliJ IDEA 插件安装

<font color='red' size='1'>因 JetBrains 插件市场服务器在海外，如遇访问缓慢无法下载安装的，请加入 [Arthas 钉钉交流群](https://alibaba.github.io/arthas/contact-us.html)，获取离线包安装</font>

**确保 IntelliJ 在 2018.1 或更高版本**

**第 1 步**：打开 Intellij 的 Settings ( Windows下 ) 或 Preferences（ Mac下 ）窗口

**第 2 步**：进入 Plugins 选项，搜索“Alibaba Cloud Toolkit”，并安装即可，如下图：

![idea1](https://user-images.githubusercontent.com/1683936/54509651-3890c300-4985-11e9-8b11-7a7cf218304b.png)

### 结果确认
插件安装成功后，重启 Intellij，您可以在工具栏看到 Alibaba Cloud Toolkit 的图标。

![idea2](https://user-images.githubusercontent.com/1683936/54509658-3e86a400-4985-11e9-95e2-70df79772c69.png)

## Eclipse插件安装

**第 1 步**：在 Eclipse 菜单栏中选择 Help > Install New Software

**第 2 步**：在 Work with 文本框输入 URL http://toolkit.aliyun.com/eclipse/

**第 3 步**：勾选需要的组件

![eclipse1](https://user-images.githubusercontent.com/1683936/54509759-902f2e80-4985-11e9-9c46-4b6d9396e44e.png)

### 结果确认
插件安装成功后，重启 Eclipse，您可以在工具栏看到 Alibaba Cloud Toolkit 的图标。

![eclipse2](https://user-images.githubusercontent.com/1683936/54509767-96250f80-4985-11e9-8935-b535d508cea3.png)

**Comment by dajiating182** [comment]
![image](https://user-images.githubusercontent.com/22051986/58236071-af2ab200-7d74-11e9-8bc0-837e45294db2.png)

**Comment by sean417** [comment]
厉害

**Comment by nileader** [comment]
@dajiating182  你好，请问你可以联系我们吗？帮你排查下 https://yq.aliyun.com/articles/656292

**Comment by iceqing** [comment]
跳板机支持吗？

**Comment by nileader** [comment]
跳板机已经支持了。https://yq.aliyun.com/articles/656292 也可以加入到我们的官网交流群保持关注，谢谢

**Comment by mingjunChan** [comment]
图片挂了看不到

**Comment by vijay-pj** [comment]
希望插件可以支持可以直接编辑服务器上的文件，服务器上vim编辑太痛苦了

**Comment by 514513669** [comment]
看的云里雾里~ 文档挺low的

**Comment by zq99299** [comment]
> 看的云里雾里~ 文档挺low的

确实，不知道讲了个啥，就讲了个如何安装 Cloud Toolkit？ 然后链接到服务器？
