### ISSUE TITLE
zip

### ISSUE THREAD

**Issue by 360CodeSafe** [alibaba/arthas#575]
您好：
在我们的开源代码审计项目中，发现arthas中存在zip条目覆盖漏洞，详细信息如下：
在IOUtils.java中提供了unzip()对zip文件进行解压
![图片](https://user-images.githubusercontent.com/39950310/54417050-093b4580-473c-11e9-8d2c-43f0a12c953e.png)
但解压过程中没有对zip文件的条目名做校验，导致攻击者可以构造带有../的条目名的zip文件，解压时将会覆盖根目录之外的文件

**Comment by nanolikeyou** [comment]
标记为误报吧，下载的文件来源于镜像的文件，版本可控。
![image](https://user-images.githubusercontent.com/30281131/54918378-0b21b780-4f39-11e9-84c1-4d3f5a89f594.png)

**Comment by 360CodeSafe** [comment]
哦哦，如果确定unzip函数不会在其他地方被调用，那就没问题了

**Comment by nanolikeyou** [comment]
是的，同https://github.com/alibaba/arthas/issues/576用途一样从仓库下载包和二进制文件。
但是需要注意的是启动时为了加快下载速度arthas提供了--use-http参数，如果被中间人攻击了，是存在该场景可以利用漏洞的可能的。

**Comment by nanolikeyou** [comment]
dns缓存投毒也可行。

**Comment by hengyunabc** [comment]
😂 默认用 https 已经最大可能保证安全了。下载的文件能被篡改的话，直接改`.class`就任意代码执行了。不需要这么麻烦。

**Comment by nanolikeyou** [comment]
360代码卫士代怎么没有发现代码里解析/com/taobao/arthas/arthas-packaging/maven-metadata.xml  有xxe的问题？还是已经标记为误报了？

**Comment by 360CodeSafe** [comment]
> 
> 
> 360代码卫士代怎么没有发现代码里解析/com/taobao/arthas/arthas-packaging/maven-metadata.xml 有xxe的问题？还是已经标记为误报了？

我怎么没找到这个文件  您是说的这个地方吗
![图片](https://user-images.githubusercontent.com/39950310/55456351-63cc1100-5619-11e9-8962-35bd32005742.png)

**Comment by 360CodeSafe** [comment]
话说我还提了一个ssrf的问题 你们确认了吗

**Comment by nanolikeyou** [comment]
> > 360代码卫士代怎么没有发现代码里解析/com/taobao/arthas/arthas-packaging/maven-metadata.xml 有xxe的问题？还是已经标记为误报了？
> 
> 我怎么没找到这个文件 您是说的这个地方吗
> ![图片](https://user-images.githubusercontent.com/39950310/55456351-63cc1100-5619-11e9-8962-35bd32005742.png)

是的

**Comment by 360CodeSafe** [comment]
引擎报了，但是我没找到输入点  且我以为该xml是写死的
