### ISSUE TITLE
ssrf

### ISSUE THREAD

**Issue by 360CodeSafe** [alibaba/arthas#576]
DownloadUtils.java中的openURLConnection方法中
![图片](https://user-images.githubusercontent.com/39950310/54417749-05a8be00-473e-11e9-92d2-e89ef6e0e425.png)
http中host头是用户可控，攻击者可以替换成内网ip进行ssrf攻击

**Comment by nanolikeyou** [comment]
使用者执行调试就是在内网，所以是内网ssrf内网？这个url其实就是用来在maven仓库下载arthas的二进制文件的。所以从技术上来说不是误报，从使用上来说没有办法利用。

**Comment by hengyunabc** [comment]
😂，通过 https 访问某个网址，就代表信任了。攻击者要能改这个返回值，基本相当于网络劫持了。
