### ISSUE TITLE
使用trace命令监听类的方法调用耗时，如果方法名相同的该如何区分

### ISSUE THREAD

**Issue by chenshinan** [alibaba/arthas#577]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
你好
使用trace命令监听类的方法调用耗时，如果方法名相同的该如何区分

**Comment by LuoXiaoyi** [comment]
目前在 Arthas 中还没有支持对重载方法的区分

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/434

**Comment by chenshinan** [comment]
> 参考这个： #434

tks, I get that

**Comment by chenshinan** [comment]
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190318143448.png)
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190318143509.png)
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190318143534.png)
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190318143605.png)
你好 为什么我无法捕获到execute这个方法

**Comment by chenshinan** [comment]
@hengyunabc

**Comment by hengyunabc** [comment]
@chenshinan 你图里显示已经trace到9个类，2个函数。仔细检查表达式，或者检查是否函数被调用了。

**Comment by chenshinan** [comment]
@hengyunabc 我使用stack可以，而trace捕获不到，我前端执行的是同一个调用，这让我很疑惑
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190318145824.png)
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190318145858.png)

**Comment by chenshinan** [comment]
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190318152729.png)
@hengyunabc 我通过调试发现，由于XWikiAction继承Action类，Action.execute()方法根本没执行到，而实际执行的是XWikiAction.execute()方法，而在代码中其实是没有显式调用XWikiAction.execute()，大概是通过传参或反射的方式调用的，所以trace捕获不到，像这种情况，我还有什么办法捕获到它的耗时吗？

**Comment by hengyunabc** [comment]
@chenshinan stack和trace的工作原理不一样。 stack是匹配到单个method，然后插入字节码获取到调用栈。

trace是跟踪某个函数内的 **子函数** 调用的耗时。

**Comment by chenshinan** [comment]
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190319102100.png)
![image](https://csn-images.oss-cn-shenzhen.aliyuncs.com/markdown/20190319102139.png)
@hengyunabc 你好，为什么我监听不到execute1方法，我应该如何监听到

**Comment by chenshinan** [comment]
我前端调用的都是同一个方法
