### ISSUE TITLE
jad反编译源码无效

### ISSUE THREAD

**Issue by xuguangwu** [alibaba/arthas#580]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.0
* Arthas 版本: 3.1.0
* 操作系统版本: Linux 3.10.0-514.26.2.el7.x86_64 
* 目标进程的JVM版本: 25.111-b14 
* 执行`arthas-boot`的版本: 

### 重现问题的步骤

**$ jad com.clear.hotel.controller.HotelInfoController**
Affect(row-cnt:0) cost in 16 ms.
**$ jad com.clear.hotel.controller.HotelInfoController**
com.clear.hotel.controller.HotelInfoController$$Lambda$788/663746894  com.clear.hotel.controller.HotelInfoController                       
com.clear.hotel.controller.HotelInfoController$$Lambda$789/830968676  com.clear.hotel.controller.HotelInfoController$$Lambda$787/1638371568
com.clear.hotel.controller.HotelInfoController$$Lambda$769/1799410578 com.clear.hotel.controller.HotelInfoController$$Lambda$768/181234280 
com.clear.hotel.controller.HotelInfoController$$Lambda$786/726917399  com.clear.hotel.controller.HotelInfoController$$Lambda$766/1002213976

**$ jad com.clear.hotel.controller.HotelInfoController$$Lambda$788/663746894** 

ClassLoader:                                                                                                                                                                                                
+-org.springframework.boot.loader.LaunchedURLClassLoader@6433a2                                                                                                                                             
  +-sun.misc.Launcher$AppClassLoader@7f31245a                                                                                                                                                               
    +-sun.misc.Launcher$ExtClassLoader@19b843ba                                                                                                                                                             

Location:                                                                                                                                                                                                   
file:/app.jar!/BOOT-INF/classes!/                                                                                                                                                                           

/*
 * Decompiled with CFR 0_132.
 * 
 * Could not load the following classes:
 *  com.clear.hotel.controller.HotelInfoController
 *  com.clear.hotel.controller.HotelInfoController$$Lambda$788
 *  com.clear.supplier.entity.CityEntity
 */
package com.clear.hotel.controller;

import com.clear.hotel.controller.HotelInfoController;
import com.clear.supplier.entity.CityEntity;
import java.lang.invoke.LambdaForm;
import java.util.List;
import java.util.function.Consumer;

final class HotelInfoController$$Lambda$788
implements Consumer {
    private final List arg$1;

    private static Consumer get$Lambda(List list) {
        return new HotelInfoController$$Lambda$788(list);
    }

    private HotelInfoController$$Lambda$788(List list) {
        this.arg$1 = list;
    }

    @LambdaForm.Hidden
    public void accept(Object object) {
        HotelInfoController.lambda$null$0((List)this.arg$1, (CityEntity)((CityEntity)object));
    }
}

### 期望的结果
我希望能够直接查看 jad com.clear.hotel.controller.HotelInfoController 后的源码

### 实际运行的结果
只返回了Affect(row-cnt:0) cost in 16 ms.

```
把异常信息贴到这里
```
![image](https://user-images.githubusercontent.com/8604167/54504250-d1b3df80-496d-11e9-9dba-3e7a436380de.png)

**Comment by hengyunabc** [comment]
提供可重现的demo？

**Comment by gangqiangwang** [comment]
同遇到此问题，借楼同问

**Comment by hengyunabc** [comment]
@gangqiangwang 提供demo啊，没demo很难查问题

**Comment by gangqiangwang** [comment]
我自己的demo可以，但公司工程不行，公司代码不敢提到这上面来

**Comment by hengyunabc** [comment]
参考： https://github.com/alibaba/arthas/issues/675
