### ISSUE TITLE
Logger API for 4.0

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#589]
* 提供一层Logger API，去掉以前的 `logger.api`依赖
* 提供Nop的实现
* 提供输出到stdout的功能
* 提供repackage的logback实现

**Comment by hengyunabc** [comment]
在使用logback的情况下，repackage logback是有必要的。因为有可能别的修改字节码的工具，会对logback进行修改，那么可以agent之间会相互影响。

改掉 package 名字，则匹配不到了。

**Comment by hengyunabc** [comment]
好像可以直接用 slf4j api , logback里可以使用一个 System properties来绕过。 在初始化 logger之前，先设置下这个值，初始化完logger之后，再重新设置回来。

或者考虑在 repackage时，能不能修改掉这个值。

`ch.qos.logback.classic.util.ContextInitializer#CONFIG_FILE_PROPERTY`

```java
public class ContextInitializer {
    final public static String CONFIG_FILE_PROPERTY = "logback.configurationFile";
```

**Comment by hengyunabc** [comment]
repackage 需要去掉一些文件，比如： `META-INF/services/javax.servlet.ServletContainerInitializer`

**Comment by hengyunabc** [comment]
#593

**Comment by xuzhiyiYoh** [comment]
4.0中repackage是否应该成为独立的module，不然repackage无法使用reducedPom，依然会直接依赖asm和logback。
![image](https://user-images.githubusercontent.com/48389485/56077875-f6d42a80-5e13-11e9-8780-5318f6c4df5f.png)

**Comment by hengyunabc** [comment]
@xuzhiyiYoh 先单独执行 `mvn clean install -DskipTests`

**Comment by xuzhiyiYoh** [comment]
已经执行过，依然有问题，你那边OK？ 
我理解的是如果在相同modeles里，就相当于arthas-repackage-asm的pom会传递给arthas-bytekit，而arthas-bytekit应该依赖的是reduced pom。打包后的pom如下：
![image](https://user-images.githubusercontent.com/48389485/56083096-53a30580-5e53-11e9-9ce0-ac07f53196d2.png)

**Comment by hengyunabc** [comment]
logger.api 已经去掉了。
