### ISSUE TITLE
attach to target jvm (*) failed

### ISSUE THREAD

**Issue by Sidneyxt** [alibaba/arthas#59]
error info:
![image](https://user-images.githubusercontent.com/20471875/45669030-45a53480-bb51-11e8-9b5c-8078789e4f47.png)
java -version:
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

elasticsearch version : 6.0.0

**Comment by Sidneyxt** [comment]
$JAVA_HOME=/usr/java/jdk1.8.0_172

**Comment by ted-wq-x** [comment]
The log of this part of the code is located `${HOME}/logs/.arthas/arthas.log`

**Comment by Sidneyxt** [comment]
![image](https://user-images.githubusercontent.com/20471875/45671784-f531d500-bb58-11e8-899b-0abed6216fd0.png)
not found

**Comment by ted-wq-x** [comment]
actually, `${HOME}` is `/home/elasticsearch/`

**Comment by ralf0131** [comment]
@Sidneyxt Please use text instead of pic. Pictures are not searchable.

**Comment by ralf0131** [comment]
1. check `/home/elasticsearch/logs/arthas/arthas.log` for any exception
2. check standard output of your target JVM for any exception. For example, Tomcat output standard output to catalina.out.

**Comment by lazycece** [comment]
@ralf0131  I also have this problem, the same as it, as follow:

===========================================
root@cc-server:/home# ./as.sh 
Arthas script version: 3.0.4
Found existing java process, please choose one and hit RETURN.
* [1]: 3792 Demo
1
Calculating attach execution time...
Attaching to 3792 using version 3.0.4...
Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:69)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:25)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:96)

real	0m5.381s
user	0m0.181s
sys	0m0.029s
attach to target jvm (3792) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.
root@cc-server:/home# find / -name arthas.log
/root/logs/arthas/arthas.log
root@cc-server:/home# cat /root/logs/arthas/arthas.log 
root@cc-server:/home# 
root@cc-server:/home# 
root@cc-server:/home# 
root@cc-server:/home# java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit 
===========================================

and the file "/root/logs/arthas/arthas.log " not be find  after appear the exception, so i'm create the file by myself, but also cannot find info from it after appear the excption , it is a empty file.

so , how to solve this problem?  can get help?

**Comment by netbuffer** [comment]
也遇到了这个问题
![error](https://user-images.githubusercontent.com/7599915/46646005-4f531280-cbba-11e8-8b46-42583d13685f.png)

**Comment by ralf0131** [comment]
@netbuffer Your Java environment is JRE not JDK please make sure you have installed JDK first.

**Comment by netbuffer** [comment]
> 
> 
> @netbuffer Your Java environment is JRE not JDK please make sure you have installed JDK first.
我确定jdk肯定是安装了的，是哪里配置有问题么，还请指点下哈

**Comment by hengyunabc** [comment]
@netbuffer  bash -x ./as.sh 看下哪里出错了

**Comment by netbuffer** [comment]
![_20181011194919](https://user-images.githubusercontent.com/7599915/46802140-1ae47f80-cd8f-11e8-9a51-25d840065c9b.png)

@hengyunabc 麻烦看下是否能看出问题

**Comment by hengyunabc** [comment]
@netbuffer 看下 `~/logs/.arthas` 目录下面有没有日志，注意仔细看是 `.arthas`，因为之前有个bug，日志可能输出错了。

另外，检查要attach的进程，是否已经挂了。可以启一个最简单的进程。 另外，贴日志贴完整的文本，不要贴图。

**Comment by XUZHOUWANG** [comment]
尝试jstack the pid，假如出现同样问题。搜索jstack相关的问题

**Comment by demonhunter416** [comment]
[root@测试-订单系统-01:admin]# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.1.0
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 11446 com.aliyun.tianji.cloudmonitor.Application
  [2]: 22598 org.apache.catalina.startup.Bootstrap
2
[INFO] Start download arthas from remote server: https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/3.1.0/arthas-packaging-3.1.0-bin.zip
[INFO] Download arthas success.
[INFO] arthas home: /root/.arthas/lib/3.1.0/arthas
[INFO] Try to attach process 22598
[ERROR] Start arthas failed, exception stack trace: 
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:73)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:100)
[ERROR] attach fail, targetPid: 22598

**Comment by demonhunter416** [comment]
[root@测试-订单系统-01:~]# java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by demonhunter416** [comment]
[root@测试-订单系统-01:admin]# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.1.0
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 11446 com.aliyun.tianji.cloudmonitor.Application
  [2]: 22598 org.apache.catalina.startup.Bootstrap
  [3]: 23965 arthas-demo.jar
3
[INFO] arthas home: /root/.arthas/lib/3.1.0/arthas
[INFO] Try to attach process 23965
[INFO] Attach process 23965 success.
[INFO] arthas-client connect 127.0.0.1 3658
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki: https://alibaba.github.io/arthas
version: 3.1.0
pid: 23965
time: 2019-04-09 17:08:40

$

**Comment by demonhunter416** [comment]
1，3 均可以Attach成功。2却不可以。报错
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
at sun.tools.attach.LinuxVirtualMachine.(LinuxVirtualMachine.java:106)
at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:73)
at com.taobao.arthas.core.Arthas.(Arthas.java:26)
at com.taobao.arthas.core.Arthas.main(Arthas.java:100)
[ERROR] attach fail, targetPid: 22598

**Comment by lpl606606** [comment]
兄弟，这个问题的原因找到了吗？我也遇到这个问题，你能指导下吗？

**Comment by demonhunter416** [comment]
Vx  578669024到公司了看一下


发自我的 iPhone
