### ISSUE TITLE
获取实例属性值

### ISSUE THREAD

**Issue by HoraceDH** [alibaba/arthas#598]
求问，怎么获得实例对象的属性值？

**Comment by hengyunabc** [comment]
用 `.`就可以。参考ognl表达式的说明： https://commons.apache.org/proper/commons-ognl/

**Comment by HoraceDH** [comment]
我看了文档
https://commons.apache.org/proper/commons-ognl/

但是怎么获得对象呢，有对象才能用.来访问吧？可以给个例子吗

**Comment by HoraceDH** [comment]
> 用 `.`就可以。参考ognl表达式的说明： https://commons.apache.org/proper/commons-ognl/

我看了文档
https://commons.apache.org/proper/commons-ognl/

但是怎么获得对象呢，有对象才能用.来访问吧？可以给个例子吗

**Comment by hengyunabc** [comment]
> > 用 `.`就可以。参考ognl表达式的说明： https://commons.apache.org/proper/commons-ognl/
> 
> 我看了文档
> https://commons.apache.org/proper/commons-ognl/
> 
> 但是怎么获得对象呢，有对象才能用.来访问吧？可以给个例子吗

把在线教程跑一遍： https://alibaba.github.io/arthas/arthas-tutorials?language=cn
