### ISSUE TITLE
参考链接不全，麻烦填充一下

### ISSUE THREAD

**Issue by yingqin678** [alibaba/arthas#60]
![image](https://user-images.githubusercontent.com/10692769/45674950-b738af00-bb60-11e8-8406-55ca9bf35b8d.png)

**Comment by yingqin678** [comment]
再加一个，这句话前后没有上下文，不太理解advice在watch命令中体现在哪里？  
![image](https://user-images.githubusercontent.com/10692769/45675479-08956e00-bb62-11e8-841a-ed22a2f38539.png)

**Comment by yingqin678** [comment]
同trace

**Comment by ralf0131** [comment]
Hi, 

Would you please send a  pull request?
