### ISSUE TITLE
关闭退出命令是否可以换一个呢，不要用shutdown？

### ISSUE THREAD

**Issue by celesky** [alibaba/arthas#607]
每次用shutdown我的心都要颤抖一下，慌得很，跟服务器关机一个命令，万一看错就尴尬了

**Comment by hengyunabc** [comment]
😂没有收到任何因为执行 shutdown 而关掉服务器的报告。并且 linux 自身的 shutdown 命令是有提示的，并不会真的马上 shutdown。

**Comment by celesky** [comment]
好的大佬！

**Comment by netroby** [comment]
+1， shutdown 太闹心了。

**Comment by lpl606606** [comment]
有些生产上静止使用shutdown指令，建议还是将shutdown指令该别名，毕竟该指令一旦关闭服务器影响大
