### ISSUE TITLE
频繁创建com.taobao.arthas.agent.ArthasClassloader类加载器实例

### ISSUE THREAD

**Issue by hanboyuan** [alibaba/arthas#608]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.0
* Arthas 版本: 3.1.0
* 操作系统版本: centos6.5
* 目标进程的JVM版本: jdk1.8.0_60
* 执行`arthas-boot`的版本: 3.1.0

### 重现问题的步骤

1. 开启arthas
2. 关闭arthas
频繁重复1,2步骤

### 期望的结果

com.taobao.arthas.agent.ArthasClassloader类加载器实例销毁
源码
```
        com.taobao.arthas.agent.AgentBootstrap
	/**
	 * 让下次再次启动时有机会重新加载
	 */
	public synchronized static void resetArthasClassLoader() {
		arthasClassLoader = null;
	}
```
源码有该内容，并未有地方调用，并说明下次再启动有机会重新加载，可是测试发现的现象是，来回关闭arthas服务，开启arthas服务，逻辑走到if (arthasClassLoader == null) 每次都进行了new类加载器的操作，导致AgentBootstrap类加载器实例一直在增加。
### 实际运行的结果
```
$ classloader
 name                                                                                numberOfInstances  loadedCountTotal                                        
 com.taobao.arthas.agent.ArthasClassloader                                           7                  9377   

```
每开启一次arthas，就会创建一个ArthasClassloader，多次开启关闭arthas，ArthasClassloader类加载器实例数量一直增，导致内存使用增加，开启关闭次数越多，影响越大。导致目标进程OOM

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/319

**Comment by hanboyuan** [comment]
> #319

java对象等待GC回收，我这7个类加载器实例，原则上早应该没有用被回收了。来回开启关闭，原则上只会用最后生效的那个classLoader，之前的会被很快回收，但是却没有。。。arthasClassLoader = null不是更快被回收么。。。

**Comment by hengyunabc** [comment]
。。只能 full gc 才会回收类。要显式用 jvisualvm 来触发。#319 的 issue 说很清楚了。 不是设置 `= null`就会被回收的。
