### ISSUE TITLE
Can options command support complete options-name?

### ISSUE THREAD

**Issue by xuzhiyiYoh** [alibaba/arthas#611]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.1.0
* Operating System version: Mac OS X
* Java version of target JVM: 1.8.0_172
* Java version of JVM used to attach: 1.8.0_172

### Steps to reproduce this issue

1. use options command
2. use tab to complete

### Expected Result

List all configurable options-name.

such as
`unsafe             dump               batch-re-transform json-format        disable-sub-class  debug-for-asm      save-result        job-timeout`

### Actual Result

Only show the usage of options.

**Comment by xuzhiyiYoh** [comment]
Considering that configuration items are hard to remember, I hope to be able to complete them.
If possible, I can try to develop this feature.

**Comment by hengyunabc** [comment]
@xuzhiyiYoh Pull requests are welcome. 😄
