### ISSUE TITLE
 需要监控31299 进程，输入 2 回车后，监控到了 1进程  23873

### ISSUE THREAD

**Issue by WuZhiCheng** [alibaba/arthas#617]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
 需要监控31299 进程，输入 2 回车后，监控到了 1进程  23873
[root@XXX]# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.1.0
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 23873 org.apache.catalina.startup.Bootstrap
  [2]: 31299 org.apache.catalina.startup.Bootstrap
  [3]: 10760 org.apache.catalina.startup.Bootstrap
  [4]: 16858 org.apache.catalina.startup.Bootstrap
  [5]: 16139 org.apache.catalina.startup.Bootstrap
  [6]: 1660 com.aliyun.tianji.cloudmonitor.Application
  [7]: 10700 org.apache.catalina.startup.Bootstrap
  [8]: 10718 org.apache.catalina.startup.Bootstrap
2
[INFO] arthas home: /root/.arthas/lib/3.1.0/arthas
[INFO] Try to attach process 31299
[INFO] Attach process **31299** success.
[INFO] arthas-client connect 127.0.0.1 3658
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki: https://alibaba.github.io/arthas
version: 3.1.0
**pid: 23873**
time: 2019-04-03 15:46:18

**Comment by hengyunabc** [comment]
先 shutdown 旧的进程，再重新 attach
