### ISSUE TITLE
能否解释下 源码com.taobao.arthas.core.ArthasConsole找不到这个类？

### ISSUE THREAD

**Issue by edagarli** [alibaba/arthas#62]
else
        # for compatibility
        # use default console
        ARGS="${TARGET_IP} ${TELNET_PORT}"
        if [ ${BATCH_MODE} = true ]; then
            ARGS="$ARGS -b"
        fi
        if [ ! -z ${BATCH_SCRIPT} ]; then
            ARGS="$ARGS -f $BATCH_SCRIPT"
        fi
        eval ${JAVA_HOME}/bin/java ${ARTHAS_OPTS} \
            -cp ${arthas_lib_dir}/arthas-core.jar \
            com.taobao.arthas.core.ArthasConsole \
            ${ARGS}
    fi

这个com.taobao.arthas.core.ArthasConsole我在源码里面找不到，所以不理解这个怎么起作用？

**Comment by ralf0131** [comment]
Hi, I think this is an legacy issue.

In Arthas 2.0 when Arthas has a rich client, this class is part of the logic.

However in Arthas 3.0, we have chosen to replace rich client with telnet/websocket. So there is no client code any more.

These code is for compatibility purpose to run the script with Arthas 2.0 client.

I believe they can be removed. 

Would you mind send a pull request?
