### ISSUE TITLE
arthas貌似存在内存泄露？

### ISSUE THREAD

**Issue by wang4ever** [alibaba/arthas#622]

**Comment by wang4ever** [comment]
我在使用arthas诊断phoenix时，发现arthas日志打印了netty的buf泄露日志

**Comment by wang4ever** [comment]
日志信息：
01 2019-04-05 16:02:28.671 INFO [as-command-execute-daemon:arthas] [] [] [] Success to reset classes: []
01 2019-04-05 16:02:28.675 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Session f6aecb17-f4cb-48db-a74a-5aea315260d3 closed, so terminate foreground job, id: 18, line: shutdown
01 2019-04-05 16:02:28.694 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x9f583b6c, L:/127.0.0.1:3658] UNREGISTERED
01 2019-04-05 16:02:28.694 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x2e660e29, L:/127.0.0.1:8563] CLOSE
01 2019-04-05 16:02:28.694 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x2e660e29, L:/127.0.0.1:8563] UNREGISTERED
01 2019-04-05 16:02:28.696 INFO [as-command-execute-daemon:arthas] [] [] [] as-server destroy completed.
Arthas server agent start...
Arthas start to bind...
01 2019-04-05 16:03:08.624 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.1.0
01 2019-04-05 16:03:08.743 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad] REGISTERED
01 2019-04-05 16:03:08.745 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad] BIND: /127.0.0.1:3658
01 2019-04-05 16:03:08.746 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad, L:/127.0.0.1:3658] ACTIVE
01 2019-04-05 16:03:08.747 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0xe5989266] REGISTERED
01 2019-04-05 16:03:08.747 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0xe5989266] BIND: /127.0.0.1:8563
01 2019-04-05 16:03:08.748 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0xe5989266, L:/127.0.0.1:8563] ACTIVE
01 2019-04-05 16:03:08.748 INFO [arthas-binding-thread:arthas] [as-server listening on network=3658;telnet=8563;http=6000;timeout={};] [] [] 127.0.0.1
01 2019-04-05 16:03:08.750 INFO [arthas-binding-thread:arthas] [] [] [] as-server started in 149 ms
Arthas server bind success.
01 2019-04-05 16:03:08.823 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad, L:/127.0.0.1:3658] READ: [id: 0x82bd72fa, L:/127.0.0.1:3658 - R:/127.0.0.1:34586]
01 2019-04-05 16:03:08.824 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad, L:/127.0.0.1:3658] READ COMPLETE
01 2019-04-05 16:03:08.847 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-04-05 16:03:26.782 ERROR [nioEventLoopGroup-2-2:i.n.u.ResourceLeakDetector] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
        io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.lang.Thread.run(Thread.java:748)

**Comment by wang4ever** [comment]
01 2019-04-05 16:01:03.124 INFO [as-command-execute-daemon:arthas] [] [] [] Success to reset classes: []
01 2019-04-05 16:02:11.197 INFO [as-command-execute-daemon:arthas] [] [] [] Success to batch transform classes: [class org.apache.phoenix.coprocessor.GroupedAggregateRegionObserver]
01 2019-04-05 16:02:26.160 INFO [as-command-execute-daemon:arthas] [] [] [] Success to reset classes: [class org.apache.phoenix.coprocessor.GroupedAggregateRegionObserver]
01 2019-04-05 16:02:28.671 INFO [as-command-execute-daemon:arthas] [] [] [] Success to reset classes: []
01 2019-04-05 16:02:28.675 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Session f6aecb17-f4cb-48db-a74a-5aea315260d3 closed, so terminate foreground job, id: 18, line: shutdown
01 2019-04-05 16:02:28.694 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x9f583b6c, L:/127.0.0.1:3658] UNREGISTERED
01 2019-04-05 16:02:28.694 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x2e660e29, L:/127.0.0.1:8563] CLOSE
01 2019-04-05 16:02:28.694 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x2e660e29, L:/127.0.0.1:8563] UNREGISTERED
01 2019-04-05 16:02:28.696 INFO [as-command-execute-daemon:arthas] [] [] [] as-server destroy completed.
Arthas server agent start...
Arthas start to bind...
01 2019-04-05 16:03:08.624 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.1.0
01 2019-04-05 16:03:08.743 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad] REGISTERED
01 2019-04-05 16:03:08.745 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad] BIND: /127.0.0.1:3658
01 2019-04-05 16:03:08.746 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad, L:/127.0.0.1:3658] ACTIVE
01 2019-04-05 16:03:08.747 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0xe5989266] REGISTERED
01 2019-04-05 16:03:08.747 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0xe5989266] BIND: /127.0.0.1:8563
01 2019-04-05 16:03:08.748 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0xe5989266, L:/127.0.0.1:8563] ACTIVE
01 2019-04-05 16:03:08.748 INFO [arthas-binding-thread:arthas] [as-server listening on network=3658;telnet=8563;http=6000;timeout={};] [] [] 127.0.0.1
01 2019-04-05 16:03:08.750 INFO [arthas-binding-thread:arthas] [] [] [] as-server started in 149 ms
Arthas server bind success.
01 2019-04-05 16:03:08.823 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad, L:/127.0.0.1:3658] READ: [id: 0x82bd72fa, L:/127.0.0.1:3658 - R:/127.0.0.1:34586]
01 2019-04-05 16:03:08.824 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x675e45ad, L:/127.0.0.1:3658] READ COMPLETE
01 2019-04-05 16:03:08.847 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-04-05 16:03:26.782 ERROR [nioEventLoopGroup-2-2:i.n.u.ResourceLeakDetector] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
        io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.lang.Thread.run(Thread.java:748)

**Comment by hengyunabc** [comment]
提交一个可重现的 demo ？

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/679
