### ISSUE TITLE
The memory compiler (mc) seems to do nothing

### ISSUE THREAD

**Issue by loicmathieu** [alibaba/arthas#624]
- [ X] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.1.0
* Operating System version: Ubuntu 18.04
* Java version of target JVM: 11.0.2
* Java version of JVM used to attach: 11.0.2

### Steps to reproduce this issue

1. Use jad to decompile a class to the local filesystem
jad my.package.MyClass > /tmp

2. Modify the class (add a System.out.println for exemple)

3. Use mc to compile the class
mc /tmp/MyClass.java -d /tmp

The command return without error but the class file is not generated

### Expected Result

The class file should be created in the /tmp directory

### Actual Result

No class file is generated

**Comment by xuzhiyiYoh** [comment]
What does  command `mc /tmp/MyClass.java -d /tmp` return?

**Comment by loicmathieu** [comment]
Nothing except the time taken ...

**Comment by xuzhiyiYoh** [comment]
Please check has any logs in arthas.log.
Path: ${HOME}/logs/arthas/arthas.log

**Comment by loicmathieu** [comment]
Hi,

I just tested it again with the arthas-demo.jar :
```
$ jad demo.MathGame --source-only > /tmp/arthas/MathGame.java
$ mc -d /tmp/arthas /tmp/arthas/MathGame.java
Memory compiler output:
Affect(row-cnt:0) cost in 703 ms.
```

Still no .class generated in /tmp/arthas.

There is no error in the log file following the command mc but there is an error when loading Arthas, I don't know if it's related.
```
01 2019-04-05 14:23:00.355 ERROR [nioEventLoopGroup-2-2:i.n.u.ResourceLeakDetector] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:528)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:482)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xuzhiyiYoh** [comment]
seems like [#622](https://github.com/alibaba/arthas/issues/622)
Try shutdown arthas and start again. And provide more details.

**Comment by loicmathieu** [comment]
Already try to shutdown and start again, still unable to make the memory compiler working

**Comment by hengyunabc** [comment]
The error output in stderr:

```
Fatal Error: Unable to find package java.lang in classpath or bootclasspath
```

```
致命错误: 在类路径或引导类路径中找不到程序包 java.lang
```

**Comment by hengyunabc** [comment]
jdk11下面的问题，已经修复，可以用这个测试包验证下： https://github.com/alibaba/arthas/issues/661#issuecomment-485692176

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/662
