### ISSUE TITLE
watch 函数无法监控 scala编写的代码？

### ISSUE THREAD

**Issue by y3030434** [alibaba/arthas#639]
arthas： 3.1.0
代码编写语言：scala

首次尝试使用 watch函数监控 函数的入参
发现半天没有任何提示，确认监控的函数有被调度

发现用scala编写的class，后面都会有$ 这个符号，这个应该是scala编译成java代码过程中生成的。

**Comment by hengyunabc** [comment]
watch命令会打印出匹配到的类和method数量，看有没有匹配到。 是否scala没关系，都是对jvm类的匹配。

试下加上 `''`，把参数包起来。
