### ISSUE TITLE
arthas watch命令的-x参数能否支持过滤？因为通常被监控方法入参（bean）嵌套深，实际上只想看入参bean的某个属性值

### ISSUE THREAD

**Issue by wang4ever** [alibaba/arthas#640]

**Comment by hengyunabc** [comment]
用 `.fieldName` 访问

**Comment by wang4ever** [comment]
多谢，有没相关示例命令？ 我不知道是 watch com.xx.MyClass myMethod "{params.myFieldName}" -x 3
还是  watch com.xx.MyClass myMethod "{params.myBean.myChildBean.myFieldName}" -x 3

**Comment by hengyunabc** [comment]
`params[0].fieldName`

**Comment by wang4ever** [comment]
多谢
