### ISSUE TITLE
与唯品会开源vjtop的实现原理区别？

### ISSUE THREAD

**Issue by YaoZhichao** [alibaba/arthas#642]
唯品会开源工具：https://github.com/vipshop/vjtools/blob/master/vjtop/README.md
3. 原理
3.1 进程区数据来源
从/proc/PID/* 文件中获取进程数据, 详见proc filesystem
从JDK的PerfData文件中获取JVM数据(JDK每秒写入/tmp/hsperfdata_$userid/$pid文件的统计数据)
使用目标JVM的JMX中获取JVM数据（如果目标JVM还没启动JMX，通过attach方式动态加载）
如果数据同时在PerfData和JMX存在，优先使用PerfData。 网络流量数据在/proc/PID/*中未能按进程区分，因此不再监控。

3.2 线程区数据来源
使用ThreadMxBean操作：

getAllThreadIds()获得所有Thread Id
getThreadCpuTime(tids)获得所有线程的CPU时间 (以及SYS CPU，内存分配)
排序后，用getThreadInfo(tids)获得前10名线程的信息，因为不取线程的StackTrace，不会堵塞应用。

想了解一下我们的工具监控数据的来源？

另外一个问题：我是否能在部署服务的机器上一直开启arthas进程？这个进程在监控或是获取数据的时候是否会影响正常服务的运行？？

**Comment by hengyunabc** [comment]
看 https://github.com/alibaba/arthas/blob/master/core/src/main/java/com/taobao/arthas/core/command/monitor200/DashboardCommand.java 的代码，可以一直开启。 获取CPU使用时间是调用`ThreadMxBean`的函数。
