### ISSUE TITLE
非root账号不能正常使用？

### ISSUE THREAD

**Issue by apjkern** [alibaba/arthas#643]
![QQ截图20190415162008](https://user-images.githubusercontent.com/9425032/56117269-50666180-5f9a-11e9-9b54-84642e85afb9.png)

![QQ截图20190415162035](https://user-images.githubusercontent.com/9425032/56117279-54927f00-5f9a-11e9-8cf2-d12790483f26.png)

**Comment by hengyunabc** [comment]
使用和目标进程一样的用户。
