### ISSUE TITLE
执行结果存日志不能正常工作

### ISSUE THREAD

**Issue by hidva** [alibaba/arthas#645]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.2-20190403
* Arthas 版本: 3.1.0
* 操作系统版本: Linux, 3.10.0-327;
* 目标进程的JVM版本:  1.8
* 执行`arthas-boot`的版本: 1.8

### 重现问题的步骤

![image](https://user-images.githubusercontent.com/17427025/56267495-8da92b80-6121-11e9-9054-6d1713ac0f9a.png)

### 期望的结果

存放执行结果的日志文件不存在.

### 实际运行的结果

存放执行结果的日志文件并未存在, 而且没有报错..

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/694

**Comment by hengyunabc** [comment]
可以试下这个测试包，应该修复了： https://github.com/alibaba/arthas/issues/694#issuecomment-492128743
