### ISSUE TITLE
[RFC] 能否把shutdown命令换一个名字，比如stoparthas

### ISSUE THREAD

**Issue by netroby** [alibaba/arthas#651]
shutdown是linux系统命令，会关闭系统
```
root@min:~# shutdown
Shutdown scheduled for Thu 2019-04-18 08:23:36 CST, use 'shutdown -c' to cancel.

```

能否把arthas的shutdown命令改个名字

如果万一搞错了，把生产服务器关掉了，不就出大漏子了吗？

能不能改成 stoparthas

减少无意犯错的概率

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/607
