### ISSUE TITLE
[RFC]能否给shutdown命令，加一个二次确认

### ISSUE THREAD

**Issue by netroby** [alibaba/arthas#652]
调试了许久，意外shutdown了，之前的工作区就全退出了。感觉很不友好，能不能做二次确认，确认无误才关闭

![Screenshot_2019-04-18_08-28-13](https://user-images.githubusercontent.com/278153/56328952-f04b0780-61b3-11e9-98ea-50a78e1de077.png)

**Comment by hengyunabc** [comment]
默认session是 30分钟过期，可以在启动时，指定 session timeout

**Comment by netroby** [comment]
执行shutdown 命令，能加个二次确认不？

**Comment by hengyunabc** [comment]
二次确认会带来很多麻烦。 shutdown 机器基本是不可能出现的。

1. 用户很粗心
2. 用户是 root
3. 执行 shutdown之后，自己不看提示，没有取消 shutdown
