### ISSUE TITLE
能否给trace命令增加调用时间戳以及增加执行轨迹所在的行号？

### ISSUE THREAD

**Issue by wang4ever** [alibaba/arthas#653]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by wang4ever** [comment]
![image](https://user-images.githubusercontent.com/29530154/56333180-ac60fe00-61c5-11e9-806d-571d32a000cd.png)

**Comment by hengyunabc** [comment]
这个实现上有困难，并且价值不大。

**Comment by wang4ever** [comment]
我觉得在比较大型复杂的项目加上行号，排查问题起来还是有方便的，我没太清楚你所指的实现困难 是不是因为arthas attach了字节码，实际源码的行号被破坏了？

**Comment by xuzhiyiYoh** [comment]
> 我觉得在比较大型复杂的项目加上行号，排查问题起来还是有方便的，我没太清楚你所指的实现困难 是不是因为arthas attach了字节码，实际源码的行号被破坏了？

arthas不会改变LineNumberTable, 行号不会被破坏。

**Comment by wang4ever** [comment]
好的 多谢
