### ISSUE TITLE
为何不直接引用sandbox的jar包？

### ISSUE THREAD

**Issue by haola334** [alibaba/arthas#658]
看了下源码，很多逻辑基本是从sandbox拷过来稍微改了下逻辑，问一下为何不直接用sandbox？

**Comment by oldmanpushcart** [comment]
arthas出现要在jvm-sandbox之前，arthas和jvm-sandbox真正的源头在greys，而greys的思路来自于HouseMD的指点。

万物有始有终，HouseMD来自于阿里中间件员工空闲的作品，greys受益于阿里中间件最终又能以arthas的身份回馈回阿里中间件，完成这款软件的一个轮回。

开源，我们选择了开放的思想，毕竟指望他挣玛莎拉蒂的钱太过遥远。任何人都是在别人的基础上不停的完成他的一个又一个轮回。

期待能有一天，这种思路能给你的工作带来新的启发，或者这款软件能真正帮助到你。

**Comment by chrootweili** [comment]
开源社区就是要众人拾柴火焰高啊，我理解除非出现重大分歧，否则另起炉灶不好吧
受益于ta，回馈于ta
