### ISSUE TITLE
as.sh不支持jdk11

### ISSUE THREAD

**Issue by spongedog** [alibaba/arthas#660]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.0
* Arthas 版本: 3.1.0
* 操作系统版本: CentOS Linux release 7.4.1708 (Core)
* 目标进程的JVM版本: oracle jdk 11.0.1
* 执行`arthas-boot`的版本: 3.1.0

### 重现问题的步骤

1. curl -L https://alibaba.github.io/arthas/install.sh | sh
2. ./as.sh

### 期望的结果

运行成功

### 实际运行的结果

Arthas script version: 3.1.0
tools.jar was not found, so arthas could not be launched!

**Comment by hengyunabc** [comment]
`bash -x ./as.sh` ，把JAVA_HOME设置为 jdk11的。

**Comment by spongedog** [comment]
++ tr '\r' '\n'
+ local 'lines=Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000060bc00000, 526385152, 0) failed; error='\''Not enough space'\'' (errno=12)

看来是我的jvm的问题
