### ISSUE TITLE
Improve the mechanism of the mc command to search for java packages and classes

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#661]
* support JPMS in JDK9/10/11
* better way to search in specified ClassLoader

**Comment by hengyunabc** [comment]
Package to test: [arthas-3.1.1-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/3106525/arthas-3.1.1-SNAPSHOT-bin.zip)

**Comment by hnlsping** [comment]
arthas-3.1.1-SNAPSHOT-bin.zip  使用这个版本启动报：
错误日志提示：Arthas server agent start...
Agent jar file does not exist: %2Froot%2F.arthas%2Flib%2F3.1.1%2Farthas%2Farthas-core.jar
![image](https://user-images.githubusercontent.com/23652811/56941708-dcef5300-6b48-11e9-886e-160b5bc8eef8.png)
这个路径可配吗？

**Comment by hengyunabc** [comment]
@hnlsping 你是什么环境的shell？操作系统是什么？ 怎么执行的？

**Comment by hnlsping** [comment]
我是阿里云ECS linux centos 6.5
直接 java -jar arthas-boot.jar

在 2019-04-30 14:42:57，"hengyunabc" <notifications@github.com> 写道：


@hnlsping 你是什么环境的shell？操作系统是什么？ 怎么执行的？

**Comment by hnlsping** [comment]
系统里面是存在两个版本的 3.1.0跟这个3.1.1  ，  3.1.0正常运行没问题， 3.1.1才会出现这个问题

**Comment by hengyunabc** [comment]
@hnlsping 具体怎么执行的？解压之后，cd到目录里，再执行 `java -jar arthas-boot.jar`

**Comment by hnlsping** [comment]
先解压到  /root/.arthas/lib/3.1.1/arthas 目录
然后cd 到 /root/.arthas/lib/3.1.1/arthas 目录
执行  java -jar arthas-boot.jar

**Comment by hengyunabc** [comment]
@hnlsping 直接在 /tmp 目录解压呢？ 解压到 `~/.arthas` 目录可能判断有问题。

**Comment by hnlsping** [comment]
直接在/tmp目录解压是一样的问题
log日志：
Arthas server agent start...
Agent jar file does not exist: %2Ftmp%2Farthas-core.jar

At 2019-04-30 16:21:01, "hengyunabc" <notifications@github.com> wrote:


@hnlsping 直接在 /tmp 目录解压呢？ 解压到 ~/.arthas 目录可能判断有问题。

**Comment by hengyunabc** [comment]
@hnlsping 原来的进程可能要重启下。或者试下启动 arthas-demo来测试下。

**Comment by hengyunabc** [comment]
因为 `arthas-agent.jar` 它是被 `AppClassLoader` 加载的，它是agent的入口，之前attach过之后，它会一直被使用。即使用户使用新版本，重新attach，还是用的最开始的版本。

因为新版本修改了 AgentBootstrap 的逻辑，所以需要重启应用才能生效。

```
$ sc -d com.taobao.arthas.agent.AgentBootstrap
 class-info        com.taobao.arthas.agent.AgentBootstrap
 code-source       /Users/hengyunabc/.arthas/lib/3.1.0/arthas/arthas-agent.jar
 name              com.taobao.arthas.agent.AgentBootstrap
 isInterface       false
 isAnnotation      false
 isEnum            false
 isAnonymousClass  false
 isArray           false
 isLocalClass      false
 isMemberClass     false
 isPrimitive       false
 isSynthetic       false
 simple-name       AgentBootstrap
 modifier          public
 annotation
 interfaces
 super-class       +-java.lang.Object
 class-loader      +-sun.misc.Launcher$AppClassLoader@3d4eac69
                     +-sun.misc.Launcher$ExtClassLoader@1e8e3531
 classLoaderHash   3d4eac69
```

**Comment by hnlsping** [comment]
重启原有应用就可以了，非常感谢~~~

在 2019-04-30 17:08:29，"hengyunabc" <notifications@github.com> 写道：


因为 arthas-agent.jar 它是被 AppClassLoader 加载的，它是agent的入口，之前attach过之后，它会一直被使用。即使用户使用新版本，重新attach，还是用的最开始的版本。

因为新版本修改了 AgentBootstrap 的逻辑，所以需要重启应用才能生效。

$ sc -d com.taobao.arthas.agent.AgentBootstrap

 class-info        com.taobao.arthas.agent.AgentBootstrap

 code-source       /Users/hengyunabc/.arthas/lib/3.1.0/arthas/arthas-agent.jar

 name              com.taobao.arthas.agent.AgentBootstrap

 isInterface       false

 isAnnotation      false

 isEnum            false

 isAnonymousClass  false

 isArray           false

 isLocalClass      false

 isMemberClass     false

 isPrimitive       false

 isSynthetic       false

 simple-name       AgentBootstrap

 modifier          public

 annotation

 interfaces

 super-class       +-java.lang.Object

 class-loader      +-sun.misc.Launcher$AppClassLoader@3d4eac69

                     +-sun.misc.Launcher$ExtClassLoader@1e8e3531

 classLoaderHash   3d4eac69
