### ISSUE TITLE
Error during processing the command: null

### ISSUE THREAD

**Issue by hnlsping** [alibaba/arthas#669]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： arthas-boot.jar
* Arthas 版本: 3.1.0
* 操作系统版本: linux
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 1.8

### 重现问题的步骤

1. 执行options save-result true  或  false
2. Error during processing the command: null   报错信息   且不能正常退出

$ options save-result false
 NAME         BEFORE-VALUE  AFTER-VALUE                                                                                                                                 
----------------------------------------                                                                                                                                
 save-result  true          false                                                                                                                                       
Error during processing the command: null

**Comment by hengyunabc** [comment]
`~/logs/arthas/arthas.log` 里的异常信息是什么？

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/517

**Comment by hnlsping** [comment]
修复后的3.1.1版本哪里有正式版下载吗？  需要自己拉代码编译么？

**Comment by hengyunabc** [comment]
可以自己编绎，或者这里有一个版本： https://github.com/alibaba/arthas/issues/661#issuecomment-485692176
