### ISSUE TITLE
tt -t recording execution exceeds limit

### ISSUE THREAD

**Issue by wings27** [alibaba/arthas#670]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.1.0
* Operating System version: CentOS 6.0
* Java version of target JVM: 1.7
* Java version of JVM used to attach: 1.7

### Steps to reproduce this issue

1. tt -n3 -t xxx.XxxClass xxxMethod

**Given that the QPS of xxxMethod is (approximately) greater than 30k**

### Expected Result

Expecting that tt records 3 executions.

### Actual Result

tt recorded more than 3 executions, the actual number may vary, 10+ in my case.

With the following output:

`Command execution times exceed limit: 3, so command will exit. You can set it with -n option.`

**Comment by hengyunabc** [comment]
可以提供重现有demo不？

**Comment by Roger3581321** [comment]
Environment
Arthas version: 3.1.7
Operating System version: Windows
Java version of target JVM: 1.8
Java version of JVM used to attach: 1.8

Steps to reproduce this issue
tt -n3 -t xxx.XxxClass xxxMethod

Following the steps above, the issue can not be reproduced.
![Capture](https://user-images.githubusercontent.com/23419065/73056716-b4736a00-3eca-11ea-9cd3-b2a7eab9d146.JPG)
