### ISSUE TITLE
cfr 0.132 已经找不到了

### ISSUE THREAD

**Issue by XhinLiang** [alibaba/arthas#672]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* 操作系统版本: macOS 10.13
* 目标进程的JVM版本: JDK 1.8

### 重现问题的步骤

mvn clean compile -U

### 期望的结果

编译成功

### 实际运行的结果

编译失败

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#%E5%AE%89%E8%A3%85%E5%88%B0%E6%9C%AC%E5%9C%B0

**Comment by netroby** [comment]
本地构建arthas，确实遇到cfr 0.132找不到的情况。请核实一下。

建议，升级一下依赖，至少到0.135，官方mvn repo提供0.135

**Comment by netroby** [comment]
我用的JDK是12， 然后我换成JDK 8， 问题解决。后续希望提升一下对JDK 9 - 12后续的版本的兼容性
