### ISSUE TITLE
刚接触arthas诊断工具  我在linux上以jar包的形式发布了一个springboot项目，使用thread找不到main函数？

### ISSUE THREAD

**Issue by lvpenghua** [alibaba/arthas#673]
linux发布的springboot.jar项目 找不到启动类的main函数，使用官网提供的demo项目是可以的，想请问一下高手这是什么问题。

**Comment by newbirdking** [comment]
me too

**Comment by hengyunabc** [comment]
spring boot fat jar启动时，main函数启动完就退出了。所以 main 函数所在的线程找不到。

fat jar的main class是： org.springframework.boot.loader.JarLauncher

可以参考： http://hengyunabc.github.io/spring-boot-application-start-analysis/
