### ISSUE TITLE
公司安全查的严，强制要把 cat 功能去除（该功能封掉）

### ISSUE THREAD

**Issue by njqaaa** [alibaba/arthas#684]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 场景
公司安全查的严，强制要把cat功能去除

### 思路
修改源码，禁用该功能。

### 操作过程
1、删除core/src/main/java/com/taobao/arthas/core/command/basic1000/CatCommand.java
2、删除core/src/main/java/com/taobao/arthas/core/command/BuiltinCommandPack.java中
第3行：import com.taobao.arthas.core.command.basic1000.CatCommand;
第90行：commands.add(Command.create(CatCommand.class));
然后./mvn clean package -U -Dmaven.test.skip=true （./mvnw clean package -U -Dmaven.test.skip=true也试过）
最后编译出来的文件为./boot/target/arthas-boot-jar-with-dependencies.jar（md5值的确与之前的不一致）

### 结果
使用到是telnet方式
输入help依然出现cat选项
直接 cat /tmp/test，依然可以正常使用

求大神抽空回答下。

**Comment by hengyunabc** [comment]
😂 本质上，使用 `ognl`表达式也可以达到 cat的效果。所以禁掉cat基本作用不大。建议控制下登陆机器权限。

如果真的想删掉，看打包出来的结果在 `packaging/target/`下面。 

参考： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md

**Comment by njqaaa** [comment]
@hengyunabc 
使用的telnet方式，不需要登录服务器的
