### ISSUE TITLE
java.io.IOException: premature EOF when attaching to weblogic

### ISSUE THREAD

**Issue by palmskij** [alibaba/arthas#687]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.1.0
* Operating System version: redflag
* Java version of target JVM: jdk1.6.0_31
* Java version of JVM used to attach: jdk1.6.0_31

### Steps to reproduce this issue

1. start weblogic server
2. run as.sh, and attach it to "weblogic.server" process
3. error reached: [ERROR] Start arthas failed, exception stack trace:
java.io.IOException: premature EOF
...

**Comment by hengyunabc** [comment]
看 `~/logs/arthas/arthas.log` 里的信息。

**Comment by palmskij** [comment]
"attach to target jvm failed, check /home/xxx/logs/arthas/arthas.log or stderr ..."
no arthas.log generated, neither arthas folder.

**Comment by hengyunabc** [comment]
1. Try to use `jstack`
2. Try to switch to the same user
3. Try to run `bash -x ./as.sh`

**Comment by palmskij** [comment]
weblogic server use jrockit jdk

**Comment by hengyunabc** [comment]
Arthas is a java agent, it is only tested under hotspot JDK. Not sure if jrockit JDK is supported.

**Comment by palmskij** [comment]
it seems that arthas works well under jrockit jdk, we've tested this scenario using arthas demo

**Comment by palmskij** [comment]
so the fact is arthas does not support weblogic server, no matter what kind of jdk it runs on.

**Comment by hengyunabc** [comment]
Please show the complete exception stack. 

Try `Full installation`:
https://alibaba.github.io/arthas/en/install-detail.html#full-installation

**Comment by palmskij** [comment]
full installation does not work either
full exception stack:
![image](https://user-images.githubusercontent.com/34704801/57357671-0db53500-71a6-11e9-8c80-3d05a8549209.png)
