### ISSUE TITLE
请问没有internet环境可以使用吗

### ISSUE THREAD

**Issue by jezhang** [alibaba/arthas#688]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.0
* Arthas 版本: 3.1.0
* 操作系统版本:  Suse-Linux
* 目标进程的JVM版本: suse
* 执行`arthas-boot`的版本: 3.1.0

### 重现问题的步骤

1. java -jar arthas-boot.ja <pid>
2. output
[INFO] arthas-boot version: 3.1.0
[ERROR] Can not read maven-metadata.xml from: https://repo1.maven.org/maven2/com/taobao/arthas/arthas-packaging/maven-metadata.xml
[ERROR] Can not find Arthas under local: /app/cos/.arthas/lib and remote: center

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
[INFO] arthas-boot version: 3.1.0
[ERROR] Can not read maven-metadata.xml from: https://repo1.maven.org/maven2/com/taobao/arthas/arthas-packaging/maven-metadata.xml
[ERROR] Can not find Arthas under local: /app/cos/.arthas/lib and remote: center

```

**Comment by hengyunabc** [comment]
用全量安装： https://alibaba.github.io/arthas/install-detail.html
