### ISSUE TITLE
Error: Unable to access jarfile /root/.arthas/lib/3.0.4/arthas/arthas-core.jar

### ISSUE THREAD

**Issue by 20170415** [alibaba/arthas#69]
Start arthas failed, exception stack trace:

Calculating attach execution time...
Attaching to 24029 using version 3.0.4...
Error: Unable to access jarfile /root/.arthas/lib/3.0.4/arthas/arthas-core.jar
attach to target jvm (24029) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.

and where's the log?

**Comment by hengyunabc** [comment]
`check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.`

或者尝试手动拼接命令行启动： https://alibaba.github.io/arthas/install-detail.html#

**Comment by ralf0131** [comment]
First, please ensure `/root/.arthas/lib/3.0.4/arthas/arthas-core.jar` does exist.

**Comment by hanlu09** [comment]
> 
> 
> First, please ensure `/root/.arthas/lib/3.0.4/arthas/arthas-core.jar` does exist.

this jar is not exist , why?
