### ISSUE TITLE
windows环境下jad输出成功后，mc不了该文件

### ISSUE THREAD

**Issue by programmerming** [alibaba/arthas#690]
![image](https://user-images.githubusercontent.com/15026346/57359255-d6488780-71a9-11e9-9482-260509c42ded.png)

**Comment by hengyunabc** [comment]
贴出具体执行了哪些命令，最好有可重现的demo。

**Comment by yi121013215** [comment]
![截图](https://user-images.githubusercontent.com/10719426/57515151-89e57f00-7344-11e9-84ca-06b120b8a9f6.PNG)
找不到相关的包，目前有解决办法吗

**Comment by hengyunabc** [comment]
@yi121013215  试下这个版本： https://github.com/alibaba/arthas/issues/661#issuecomment-485692176

**Comment by yi121013215** [comment]
试了，感觉不行，控制台启动arthas还是3.1.0版本的，mc也还是那个问题
