### ISSUE TITLE
2019 Alibaba Summer of Code/2019 阿里巴巴编程之夏

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#691]
## 2019 Alibaba Summer of Code

Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience software development in the real world. Alibaba Summer of code will begin between June 28th and September 20th. Students can use the summertime to participate in the open source project and work with the core members of the project.

## What you can get?

On this exclusive developer journey, students will have the opportunity to:

* Participate in the top projects of the International Open Source Foundation;
* Get a scholarship from Alibaba;
* Obtain an open source contributor certificate;
* Get a fast pass of Alibaba Internship/recruitment;
* Get your code adopted and used by the open source project！

## Our Mentor

Chen ZhiXuan
GitHub ID: [hengyunabc](https://github.com/hengyunabc)
Alibaba Cloud Senior Engineer

## Apply Now! 

You can click on this link to apply directly:

* https://github.com/alibaba/arthas/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Ffeature-request

full list of Alibaba Summer of Code Projects：

* https://developer.aliyun.com/special/summerofcode2019en
* https://developer.aliyun.com/special/summerofcode2019

## Timeline⏳

![timeline](https://user-images.githubusercontent.com/1683936/57366197-16633680-71b9-11e9-9eaa-c16cf9414bbc.png)

## Contact us!

Email Address: aliopensource@alibabacloud.com

**Comment by MikeoPerfect** [comment]
that looks very good. is there any room for communication, such as gitter or irc?

**Comment by hengyunabc** [comment]
@MikeoPerfect https://alibaba.github.io/arthas/contact-us.html

**Comment by sjha2048** [comment]
What are the next steps @hengyunabc ?

**Comment by hsluoyz** [comment]
Why ASoC 2020 is not held any more?

**Comment by grumpyAmber** [comment]
> Why ASoC 2020 is not held any more?
ASoC 2020 will come soon…Will keep you guys updated

**Comment by uinstinct** [comment]
### Which website should we keep a track of for updates?

**Comment by jack870131** [comment]
> > Why ASoC 2020 is not held any more?
> 
> ASoC 2020 will come soon…Will keep you guys updated
> 
> 

@grumpyAmber So the ASoC 2020 is sure to be held this year, right?

**Comment by sjha2048** [comment]
Yes, it will be held this year for sure.

**Comment by kylixs** [comment]
:rocket: Please check the SoC 2020 page  https://github.com/alibaba/arthas/issues/1198
