### ISSUE TITLE
关于使用场景的疑问和建议

### ISSUE THREAD

**Issue by useraddZYB** [alibaba/arthas#692]
工具太多，每个工具做一点功能，但是对于全局接口定位问题其实需要整合这些所有trace watch..等工具到一起才有用。这里发下我的一个进程内trace方案，供思路参考，很简单但是能够诊断历史或实时接口级别完整到链路数据：https://github.com/useraddZYB/time-tracker

**Comment by hengyunabc** [comment]
arthas有自己的定位： https://alibaba.github.io/arthas/arthas-tutorials?language=cn
