### ISSUE TITLE
IBM WebSphere stack 报错

### ISSUE THREAD

**Issue by gyfxo195** [alibaba/arthas#693]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0.5
* Arthas 版本: 3.0.5
* 操作系统版本: xxx
* 目标进程的JVM版本:IBM J9 VM（build 2.6 JRE 1.6.0）
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. stack class method

### 期望的结果

成功

### 实际运行的结果

Error during processing the command: adding retransformable transformers is not supported in this environment

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
参考下这个： https://github.com/oldmanpushcart/greys-anatomy/issues/113

**Comment by xutao6936** [comment]
我加了-Dwas.debug.mode=true  没用 还是报这个错

**Comment by hengyunabc** [comment]
试下 arthas-demo，如果arthas-demo可以，那可能是 WebSphere的设置问题。

ibm的j9好像开源了，可以试下给他们提issue 😂

**Comment by xutao6936** [comment]
多谢！
was 启动添加下面命令就ok了
-Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n

**Comment by Hkwaynewing** [comment]
请问你是如何用arthas找到websphere进程的？https://github.com/alibaba/arthas/issues/426
