### ISSUE TITLE
java -jar arthas-boot.jar  报Agent JAR loaded but agent failed to initialize

### ISSUE THREAD

**Issue by zhouxihua0311** [alibaba/arthas#698]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:88)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:26)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:100)

**Comment by hengyunabc** [comment]
试下 arthas-demo 。 看下 ~/logs/arthas/arthas.log 的内容。 试下启动一个新的进程再来attach。

**Comment by zhouxihua0311** [comment]
下面是 ~/logs/arthas/arthas.log 的内容，
Arthas server agent start...
Arthas start to bind...
01 2019-05-14 21:25:00.757 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.1.0
01 2019-05-14 21:25:00.943 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f] REGISTERED
01 2019-05-14 21:25:00.946 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f] BIND: /127.0.0.1:3658
01 2019-05-14 21:25:00.949 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f, L:/127.0.0.1:3658] ACTIVE
01 2019-05-14 21:25:00.952 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x25b5983e] REGISTERED
01 2019-05-14 21:25:00.952 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x25b5983e] BIND: /127.0.0.1:8563
01 2019-05-14 21:25:00.952 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x25b5983e, L:/127.0.0.1:8563] ACTIVE
01 2019-05-14 21:25:00.953 INFO [arthas-binding-thread:arthas] [as-server listening on network=3658;telnet=8563;http=6000;timeout={};] [] [] 127.0.0.1
01 2019-05-14 21:25:00.959 INFO [arthas-binding-thread:arthas] [] [] [] as-server started in 239 ms
Arthas server bind success.
01 2019-05-14 21:25:01.071 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f, L:/127.0.0.1:3658] READ: [id: 0xf6db2923, L:/127.0.0.1:3658 - R:/127.0.0.1:61265]
01 2019-05-14 21:25:01.072 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f, L:/127.0.0.1:3658] READ COMPLETE
01 2019-05-14 21:25:01.110 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
Arthas server agent start...
Arthas start to bind...
01 2019-05-14 21:36:51.401 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.1.0
01 2019-05-14 21:36:52.037 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba] REGISTERED
01 2019-05-14 21:36:52.040 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba] BIND: /127.0.0.1:3658
01 2019-05-14 21:36:52.061 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] ACTIVE
01 2019-05-14 21:36:52.064 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x77983c74] REGISTERED
01 2019-05-14 21:36:52.064 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x77983c74] BIND: /127.0.0.1:8563
01 2019-05-14 21:36:52.064 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x77983c74, L:/127.0.0.1:8563] ACTIVE
01 2019-05-14 21:36:52.067 INFO [arthas-binding-thread:arthas] [as-server listening on network=3658;telnet=8563;http=6000;timeout={};] [] [] 127.0.0.1
01 2019-05-14 21:36:52.071 INFO [arthas-binding-thread:arthas] [] [] [] as-server started in 744 ms
Arthas server bind success.
01 2019-05-14 21:36:52.204 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] READ: [id: 0x1d77dd2e, L:/127.0.0.1:3658 - R:/127.0.0.1:61509]
01 2019-05-14 21:36:52.206 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] READ COMPLETE
01 2019-05-14 21:36:52.266 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-05-14 21:42:50.768 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] READ: [id: 0x80236b48, L:/127.0.0.1:3658 - R:/127.0.0.1:61662]
01 2019-05-14 21:42:50.768 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] READ COMPLETE
01 2019-05-14 21:42:50.770 INFO [nioEventLoopGroup-2-3:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-05-14 21:43:32.119 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Session 5dcbeab3-a7b5-488d-8eee-1279f2dd99f9 closed, so terminate foreground job, id: 1, line: trace
01 2019-05-14 21:44:50.510 INFO [as-shutdown-hooker:arthas] [] [] [] as-server destroy completed.

这是我本地应用启的是sofaweb,attach报错日志
Exception in thread "Attach Listener" java.lang.ClassNotFoundException: com.taobao.arthas.agent.AgentBootstrap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at com.alipay.sofa.runtime.test.classloader.FwkClassLoader.findClass(FwkClassLoader.java:139)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Agent failed to start!

**Comment by zhouxihua0311** [comment]
> 试下 arthas-demo 。 看下 ~/logs/arthas/arthas.log 的内容。 试下启动一个新的进程再来attach。

下面是 ~/logs/arthas/arthas.log 的内容，
Arthas server agent start...
Arthas start to bind...
01 2019-05-14 21:25:00.757 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.1.0
01 2019-05-14 21:25:00.943 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f] REGISTERED
01 2019-05-14 21:25:00.946 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f] BIND: /127.0.0.1:3658
01 2019-05-14 21:25:00.949 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f, L:/127.0.0.1:3658] ACTIVE
01 2019-05-14 21:25:00.952 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x25b5983e] REGISTERED
01 2019-05-14 21:25:00.952 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x25b5983e] BIND: /127.0.0.1:8563
01 2019-05-14 21:25:00.952 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x25b5983e, L:/127.0.0.1:8563] ACTIVE
01 2019-05-14 21:25:00.953 INFO [arthas-binding-thread:arthas] [as-server listening on network=3658;telnet=8563;http=6000;timeout={};] [] [] 127.0.0.1
01 2019-05-14 21:25:00.959 INFO [arthas-binding-thread:arthas] [] [] [] as-server started in 239 ms
Arthas server bind success.
01 2019-05-14 21:25:01.071 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f, L:/127.0.0.1:3658] READ: [id: 0xf6db2923, L:/127.0.0.1:3658 - R:/127.0.0.1:61265]
01 2019-05-14 21:25:01.072 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x655f4f6f, L:/127.0.0.1:3658] READ COMPLETE
01 2019-05-14 21:25:01.110 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
Arthas server agent start...
Arthas start to bind...
01 2019-05-14 21:36:51.401 INFO [arthas-binding-thread:arthas] [] [] [] arthas version: 3.1.0
01 2019-05-14 21:36:52.037 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba] REGISTERED
01 2019-05-14 21:36:52.040 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba] BIND: /127.0.0.1:3658
01 2019-05-14 21:36:52.061 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] ACTIVE
01 2019-05-14 21:36:52.064 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x77983c74] REGISTERED
01 2019-05-14 21:36:52.064 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x77983c74] BIND: /127.0.0.1:8563
01 2019-05-14 21:36:52.064 INFO [nioEventLoopGroup-3-1:i.n.h.l.LoggingHandler] [id: 0x77983c74, L:/127.0.0.1:8563] ACTIVE
01 2019-05-14 21:36:52.067 INFO [arthas-binding-thread:arthas] [as-server listening on network=3658;telnet=8563;http=6000;timeout={};] [] [] 127.0.0.1
01 2019-05-14 21:36:52.071 INFO [arthas-binding-thread:arthas] [] [] [] as-server started in 744 ms
Arthas server bind success.
01 2019-05-14 21:36:52.204 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] READ: [id: 0x1d77dd2e, L:/127.0.0.1:3658 - R:/127.0.0.1:61509]
01 2019-05-14 21:36:52.206 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] READ COMPLETE
01 2019-05-14 21:36:52.266 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-05-14 21:42:50.768 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] READ: [id: 0x80236b48, L:/127.0.0.1:3658 - R:/127.0.0.1:61662]
01 2019-05-14 21:42:50.768 INFO [nioEventLoopGroup-2-1:i.n.h.l.LoggingHandler] [id: 0x016a1eba, L:/127.0.0.1:3658] READ COMPLETE
01 2019-05-14 21:42:50.770 INFO [nioEventLoopGroup-2-3:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-05-14 21:43:32.119 INFO [nioEventLoopGroup-2-2:arthas] [] [] [] Session 5dcbeab3-a7b5-488d-8eee-1279f2dd99f9 closed, so terminate foreground job, id: 1, line: trace
01 2019-05-14 21:44:50.510 INFO [as-shutdown-hooker:arthas] [] [] [] as-server destroy completed.

这是我本地应用启的是sofaweb,attach报错日志
Exception in thread "Attach Listener" java.lang.ClassNotFoundException: com.taobao.arthas.agent.AgentBootstrap
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at com.alipay.sofa.runtime.test.classloader.FwkClassLoader.findClass(FwkClassLoader.java:139)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Agent failed to start!

**Comment by hengyunabc** [comment]
这个是实现方的`FwkClassLoader`代码问题，需要处理agent jar。

**Comment by LichFaker** [comment]
我也遇到了类似的问题，该怎么解决呢
```
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
	at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:104)
	at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
	at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[ERROR] attach fail, targetPid: 19937
```

**Comment by wa-ooo** [comment]
+1  请问怎么解

**Comment by rockythd** [comment]
**环境信息**
arthas-boot.jar 或者 as.sh 的版本： 3.2.0
Arthas 版本: 3.2.0
操作系统版本: CentOS 6.7
目标进程的JVM版本: 1.6.0_27 64Bit
**错误说明及截图**
     需要诊断的进程ID是19178，加载报错；但其父进程 19137可以正常加载！希望这个信息能有所帮助
![error-info](https://user-images.githubusercontent.com/10040226/81464626-ccf75e00-91f5-11ea-86b6-0c103651537c.jpg)

**Comment by nanquxiaozu** [comment]
我遇到类似的问题，原因是的arthas路径带中文了，换到其他路径就可以了

**Comment by 2631451206** [comment]
这个就是 com.alipay.sofa.runtime.test.classloader.FwkClassLoader这个加载器的问题，一个是提给官方修改，还有一个下策如下：Field[] fields = FwkClassLoader.class.getDeclaredFields();
        for (Field field : fields) {
            // 通过反射修改常量值
            if ("delegateJdkPackage".equals(field.getName())) {
                field.set(null, new String[] {"com.sun", "sun", "你要加载的类"});
            }
        }
这个加载器中delegateJdkPackage字段是由应用类加载器加载的

**Comment by youyanghuang** [comment]
+1 请问怎么解

**Comment by side-wipe** [comment]
+1

**Comment by gogodjzhu** [comment]
+1
