### ISSUE TITLE
关于logs日志目录配置

### ISSUE THREAD

**Issue by zhaoshaoquan** [alibaba/arthas#699]
我现在在mac上使用，我想写脚本把项目提交到brew仓库中，但是目前关于logs日志目录不能手动配置，在后续的版本中可以增加日志目录的配置项吗？

**Comment by hengyunabc** [comment]
目前在arthas 3里，日志是依赖 logger api来打印的，它是固定在user home下面打印的：https://github.com/alibaba/logger.api 

目前没有太好的办法。后面的版本里会考虑移除掉 logger api。

**Comment by gMan1990** [comment]
是否可以便携化？arthas-boot.jar文件在哪个目录，配置，日志，依赖就放在哪个目录

**Comment by drtrang** [comment]
+1

**Comment by waterystone** [comment]
+1

**Comment by hengyunabc** [comment]
已经支持。
