### ISSUE TITLE
whether arthas support list all loaded class

### ISSUE THREAD

**Issue by Lemonjing** [alibaba/arthas#701]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.1.1
* Operating System version: MacOS X 10.14.4
* Java version of target JVM: 1.8
* Java version of JVM used to attach: 1.8

### Steps to reproduce this issue

NO

### Expected Result

NO

### Actual Result

NO

Hi, does arthas support list all loaded class? for example, same as jmap. Or currently it just support search a lonely one jvm class? (use sc -d command)

**Comment by hengyunabc** [comment]
`classloader -h`

**Comment by Lemonjing** [comment]
@hengyunabc got it. thanks
