### ISSUE TITLE
用户体验调优问题，希望能给予关注

### ISSUE THREAD

**Issue by konser** [alibaba/arthas#706]
希望增加多项表达式功能用-E制定的太范了
watch -E 'com.xxx.common.net.protoc.codec.ProtocCodecUtil|io.netty.buffer.PooledHeapByteBufX' 'toPooledHeapByteBufX|release' 'params[0] == 1'
我希望A表达式有A的条件，B表达式有B的条件，可以跟踪多个类似
watch -E 'com.xxx.common.net.protoc.codec.ProtocCodecUtil' 'toPooledHeapByteBufX' 'params[0] == 1' -E “io.netty.buffer.PooledHeapByteBufX” ‘release’ ‘params[0] == 150’

**Comment by hengyunabc** [comment]
匹配多个类： https://github.com/alibaba/arthas/issues/71#issuecomment-422699741
