### ISSUE TITLE
不能够完整的输出信息

### ISSUE THREAD

**Issue by xsllvip** [alibaba/arthas#709]
version   3.1.1  
Window 10

$ stack com.xxx.ControlFilter doFilter
Press Q or Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 208 ms.

$ trace com.xxx.ControlFilter doFilter
Press Q or Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 190 ms.

$ tt -t com.xxx.ControlFilter doFilter
Press Q or Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:1) cost in 166 ms.

**Comment by hengyunabc** [comment]
没有请求就不会有输出，试下在线教程： https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-advanced

**Comment by smallYellowCat** [comment]
[arthas@29466]$ watch xxx queryReportDatas "{params,returnObj}" -x 3
Press Q or Ctrl+C to abort.
Affect(class-cnt:1 , method-cnt:2) cost in 708 ms.


watch不应该是阻塞等待到有请求吗？
