### ISSUE TITLE
classloader排查类加载器泄露使用疑问

### ISSUE THREAD

**Issue by bababababamulovedrink** [alibaba/arthas#711]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

```
文档上提到：使用Classloader了解当前系统中有多少类加载器，以及每个加载器加载的类数量，帮助您判断是否有类加载器泄露。
```
请问如何定义类加载器泄露呀？我的项目中创建了1300+个sun.reflect.DelegatingClassLoader，每个类加载器只加载了一个类。设置了MaxMetaspaceSize=256M，jvm发生metaspace oom。但不知道如何定位是哪里出了问题。

**Comment by bababababamulovedrink** [comment]
1、下图是我的所有类加载器，sun.reflect.DelegatingClassLoader非常多。

![image](https://user-images.githubusercontent.com/23279527/58172668-bfd31d80-7ccb-11e9-85ef-b4a9b7f267fa.png)

2、下图是我的所有类加载器，按照加载的类的总大小排序，前20个。
![image](https://user-images.githubusercontent.com/23279527/58172745-fad55100-7ccb-11e9-8199-d319f6349c0d.png)

**Comment by hengyunabc** [comment]
sun.reflect.DelegatingClassLoader 是反射生成的。检查具体生成的ClassLoader加载的是什么类，再找是哪里的反射调用。

heapdump可以找个GUI的软件分析下。
