### ISSUE TITLE
使用tt跟踪BufferedReader.readLine()方法，cost为负数？

### ISSUE THREAD

**Issue by achu2000** [alibaba/arthas#714]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.0
* Arthas 版本: 3.11
* 操作系统版本: win 10 x64
* 目标进程的JVM版本: java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
* 执行`arthas-boot`的版本: 3.11

### 重现问题的步骤

1、启动Demo应用
2、as连接pid
3、在as console上输入
options unsafe true
tt -t java.io.BufferedReader readLine params.length==0 -n 10000 >> BufferedReader.out &
4、调用Demo应用中读取文件的api
### 期望的结果
BufferedReader.out中输出的cost大于等于0

### 实际运行的结果

参考附件，前半部分正常，后半部分的cost出现小于0的情况
[BufferedReader.out.txt](https://github.com/alibaba/arthas/files/3214892/BufferedReader.out.txt)

**Comment by hengyunabc** [comment]
目前多线程情况下，cost计数的确有可能错乱。并且这个cost太小了，可以忽略。

**Comment by achu2000** [comment]
cost小不等于可以忽略好么，而且，我这边可是单线程

**Comment by hengyunabc** [comment]
有没有可以重现的Demo？

**Comment by achu2000** [comment]
`try {
				BufferedInputStream bis = new BufferedInputStream(new FileInputStream(fileName), ReadFileConst.IO_BUF_SIZE);
				BufferedReader reader = new BufferedReader(new InputStreamReader(bis, StandardCharsets.UTF_8),
						ReadFileConst.READ_BUF_SIZE);
				int lineCount = 0;
				LOGGER.info("begin read file :" + fileName);
				while (reader.readLine() != null) {
					lineCount++;
				}
				LOGGER.info(lineCount + " lines readed");
				bis.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}`
fileName对应的txt文件大约在1G左右。

**Comment by hengyunabc** [comment]
参考: #746

**Comment by netroby** [comment]
@hengyunabc It a bug. should be fix .
