### ISSUE TITLE
options dump 结果出现error和指令集是什么呢

### ISSUE THREAD

**Issue by GitCrazyLin** [alibaba/arthas#716]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### options dump配置为true后dump出来的文件显示error和指令集  使用上没有影响

1. 配置options dump值为true
2.对置顶的类CaptchaSlideController做watch操作
3.dump目录下查看CaptchaSlideController.class出现下图所示的指令集没有对应的语句信息

### 期望的结果
希望看到增强后的类的字节码信息
What do you expected from the above steps？

### 实际运行的结果 这是其中的一部分内容
```
// ERROR //
  public CaptchaSlideController()
  {
    // Byte code:
    //   0: aload_0
    //   1: invokespecial 1	com/bj58/zhaopin/jianli/wf/common/controllers/BaseControllers:<init>	()V
    //   4: aconst_null
    //   5: iconst_0
    //   6: iconst_1
    //   7: swap
    //   8: swap
    //   9: pop2
    //   10: pop
    //   11: getstatic 182	java/arthas/Spy:ON_BEFORE_METHOD	Ljava/lang/reflect/Method;
    //   14: aconst_null
    //   15: bipush 7
```

**Comment by hengyunabc** [comment]
反编译不一定能成功，特别是使用lambda时。
