### ISSUE TITLE
jad命令的原理是什么？

### ISSUE THREAD

**Issue by iamwx** [alibaba/arthas#717]
jad命令的原理是什么？

**Comment by aqqwiyth** [comment]
看看这篇文章 http://hengyunabc.github.io/dumpclass/  

源码估计是这个  https://github.com/hengyunabc/dumpclass

**Comment by hengyunabc** [comment]
Arthas源码分析--jad反编译原理: https://mp.weixin.qq.com/s/rK3qR6vpbr83dRThfLutsg
