### ISSUE TITLE
如何在sprint boot中根据当下应用tomcat的pid来attach之后，redefine class

### ISSUE THREAD

**Issue by winsun** [alibaba/arthas#718]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 期望的结果

sprint boot的应用里：
 ProcessBuilder pb = new ProcessBuilder();
 pb.command("java","-jar","/Users/winsun/arthas-boot.jar",pid);
 通过pb.start来启动arthas attach当前应用。
然后，如何才能做 redefine 功能呢？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
arthas目前是一个命令行工具，不是自动化工具。具体什么需求？

**Comment by aqqwiyth** [comment]
ProcessBuilder获取到输入输出流.   根据响应内容 把你的PID打进去注入到对应的jvm . redefine即可吧
