### ISSUE TITLE
arthas不能redefine枚举类

### ISSUE THREAD

**Issue by liweiyuan** [alibaba/arthas#719]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* 操作系统版本: windows
* 目标进程的JVM版本: oracle jdk 1.8
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. controller调用一个service获取枚举类的值
  原来的枚举类
  `public enum EnumType {
    HELLO("hello"),
    HI("hi");
    private String say;
    EnumType(String say) {
        this.say = say;
    }
    public String getSay() {
        return say;
    }
    public void setSay(String say) {
        this.say = say;
    }
}`
2. 启动后通过jad,sc,mc,redefine替换枚举类(热替换)，替换后的class文件如下
 `public enum EnumType {
    HELLO("hello"),
    HI("hahaha");
    private String say;

    private EnumType(String var3) {
        this.say = var3;
    }

    public void setSay(String var1) {
        this.say = var1;
    }

    public String getSay() {
        return this.say;
    }
}`
3. 第一次与第二次两次调用EnumType.HI.getSay();输出的结果都是一样的，都是"hi"

### 期望的结果
未替换之前是hi
替换后是hahaha

### 日志显示替换成功
![image](https://user-images.githubusercontent.com/26542900/58409490-bfa79900-80a2-11e9-8fa7-1a3744de7417.png)

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
这个貌似是jdk本身的限制，忘记在哪里有看到过

**Comment by liweiyuan** [comment]
这个问题，我已经知道了，是jdk的限制
Instrumentation.redefineClasses()方法有详细的描述
