### ISSUE TITLE
参与贡献章节-调试arthas挂不上

### ISSUE THREAD

**Issue by zonghaishang** [alibaba/arthas#72]
文章：https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md
里面指引调试arthas无效

**Comment by Hearen** [comment]
Would you please elaborate your case: what tried? what occurred?

b.t.w. your link is `incorrect`, it should be https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md

**Comment by ralf0131** [comment]
Hi, 

Agree with @Hearen Please provide more details.

What steps did you do? What do you expect? What actually happened?

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/222
