### ISSUE TITLE
希望能提供rest接口，方便集成到公司内部系统。

### ISSUE THREAD

**Issue by lyghzh** [alibaba/arthas#720]

**Comment by lpl606606** [comment]
同求

**Comment by paulinsider** [comment]
+1  同求

**Comment by papalian** [comment]
同求
但这个我觉得是不是也可以自己另外写程序实现，REST接口 对接 服务器上的Arthas指令， 输出执行结果并返回到REST接口

**Comment by konglz** [comment]
阿里要卖钱吧？
社区版本只有最基本的功能；附加功能应该会放在阿里云上卖。
利用社区培养用户，打出知名度；利用阿里云实现商业盈利。
貌似是这个套路。。。

**Comment by hengyunabc** [comment]
在 4.0的规划里： https://github.com/alibaba/arthas/issues/558
