### ISSUE TITLE
如何直接查看成员变量的值呢？

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#724]
有时候想看一下成员变量的值 如
```
	private String IP ;
	private int PORT;
```

可以通过watch一个方法来实现 如 
```
watch demo.MathGame primeFactors 'target'
```
不知道有没更直接的方式呢 如 
```
ognl 'demo.MathGame.IP'
```
似乎ognl只支持静态变量

**Comment by hengyunabc** [comment]
想看非 static 字段，只能考虑捕获到一个对象再获取。 没有神奇的想看任意对象值的功能。

**Comment by haerxiong** [comment]
https://blog.csdn.net/haerxiong/article/details/105785391

**Comment by hfutatzhanghb** [comment]
> 只能考虑捕获到一个对象再获取

@hengyunabc 大佬，怎么用arthas捕捉到一个对象呀。

**Comment by jieqiyue** [comment]
为什么不能出一个这种功能呢    应该都可以做吧

**Comment by WangJi92** [comment]
> 

[vmtool 执行表达式](https://arthas.aliyun.com/doc/vmtool.html#%E6%89%A7%E8%A1%8C%E8%A1%A8%E8%BE%BE%E5%BC%8F)   这个应该满足你的需求 看看

**Comment by fcfang123** [comment]
获取某个对象中变量的值
vmtool --action getInstances --className com.xxx.xxx.className  --express 'instances[0].variableName'
执行某个对象中的方法
vmtool --action getInstances --className com.xxx.xxx.className  --express 'instances[0].method("xxx")'
