### ISSUE TITLE
getstatic 可以获取到静态变量内容，但是ognl 却提示ClassNotFoundException

### ISSUE THREAD

**Issue by liugddx** [alibaba/arthas#727]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: Linux version 2.6.32-642.el6.x86_64
* 目标进程的JVM版本: 1.8.0_45
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. getstatic demo.ServiceUrlMapping handlerMethodCache
![image](https://user-images.githubusercontent.com/48236177/58812892-49340980-8655-11e9-8aff-3fcc07058546.png)
2. ognl '@demo.ServiceUrlMapping@handlerMethodCache'
![image](https://user-images.githubusercontent.com/48236177/58812961-72549a00-8655-11e9-8d12-01f2e807aee6.png)
3. getstatic 可以获取到静态变量内容，但是ognl 却提示ClassNotFoundException

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
最好有可执行的demo，不然很难定位问题。

**Comment by zuohongda** [comment]
你可以尝试使用`sc`的`-d`参数查看`demo.ServiceUrlMapping`的`classLoaderHash`。然后使用`ognl` 的 `-c` 参数指定你静态类`demo.ServiceUrlMapping`的`classLoaderHash`，例如：
```
$ ognl -c 18b4aac2 '@demo.ServiceUrlMapping@handlerMethodCache'
```

**Comment by li24361** [comment]
thanks !this issue solved my problem!!
