### ISSUE TITLE
linux输入中文乱码

### ISSUE THREAD

**Issue by yyyyfan** [alibaba/arthas#738]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar`的版本： 3.1.1
* Arthas 版本: arthas-3.1.1
* 操作系统版本: Aliyun Linux release 2.1903
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 1.8

![图片](https://user-images.githubusercontent.com/26210716/59587126-2276d800-9117-11e9-9417-013311d3d79e.png)
![图片](https://user-images.githubusercontent.com/26210716/59587149-2dca0380-9117-11e9-80dd-c45dfaa99fa5.png)
![图片](https://user-images.githubusercontent.com/26210716/59587164-3c181f80-9117-11e9-9c7b-ce7d31c023ad.png)

**Comment by hengyunabc** [comment]
这个感觉和shell的环境配置有关，可以试下 telnet 127.0.0.1 3658

**Comment by hunangangli** [comment]
用telnet并不行

**Comment by hengyunabc** [comment]
@hunangangli 原生telnet不行，可以要设置 shell的环境编码为 utf8

**Comment by huaxiaoer** [comment]
@yyyyfan 遇到同样的问题， 能说下怎么解决的吗？

**Comment by hengyunabc** [comment]
> @yyyyfan 遇到同样的问题， 能说下怎么解决的吗？

https://arthas.aliyun.com/doc/faq.html#unicode

**Comment by huaxiaoer** [comment]
> > @yyyyfan 遇到同样的问题， 能说下怎么解决的吗？
> 
> https://arthas.aliyun.com/doc/faq.html#unicode

多谢
