### ISSUE TITLE
下载节点就不能提供一个国内的吗？

### ISSUE THREAD

**Issue by xanderma** [alibaba/arthas#74]
使用curl -L https://alibaba.github.io/arthas/install.sh | sh下载，好吧，一进去就要更新，半天更新不好，挂VPN也更新不上。
提供离线下载是吧，一看maven.org链接，本地下半天下不下来，挂VPN也下不下来。
真是搞不懂，都提供中文文档了，就不能提供一个能快速下载的链接？
我能力不够，那我不用这个工具行了吧

**Comment by hengyunabc** [comment]
中央仓库下载不到，就找个国内的镜像，比如阿里云：http://maven.aliyun.com/mvn/search 。或者尝试用  http://mvnrepository.com/artifact/com.taobao.arthas/arthas-packaging

**Comment by hengyunabc** [comment]
如果下载速度比较慢，可以尝试用[阿里云的镜像仓库](https://maven.aliyun.com/)。
比如要下载`3.x.x`版本（替换`3.x.x`为最新版本），下载的url是：

    https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/3.x.x/arthas-packaging-3.x.x-bin.zip
