### ISSUE TITLE
linux 环境下，无法attach到tomcat

### ISSUE THREAD

**Issue by qianjiaxiang** [alibaba/arthas#740]
我已经在 issues 里搜索，没有重复的issue。
环境信息
arthas-boot.jar
Arthas 版本: 3.1.0
操作系统版本: 3.10.0-957.5.1.el7.x86_64
目标进程的JVM版本: 1.8
执行arthas-boot的版本:3.1.0
重现问题的步骤
执行java -jar arthas-boot.jar, Can not find java process. Try to pass in command line.
Please select an available pid.
期望的结果
项目中以tomcat形式运行了war包，但是无法获取到任何的java process，期望结果是可以显示出tomcat的进程，并attatch
实际运行的结果

**Comment by qianjiaxiang** [comment]
**我已经在 issues 里搜索，没有重复的issue。**
**环境信息**
arthas-boot.jar 
Arthas 版本: 3.1.0
操作系统版本: 3.10.0-957.5.1.el7.x86_64
目标进程的JVM版本: 1.8
执行arthas-boot的版本:3.1.0
**重现问题的步骤**
执行java -jar arthas-boot.jar, Can not find java process. Try to pass <pid> in command line.
Please select an available pid.
**期望的结果**
项目中以tomcat形式运行了war包，但是无法获取到任何的java process，期望结果是可以显示出tomcat的进程，并attatch
**实际运行的结果**
![image](https://user-images.githubusercontent.com/16290983/59656644-d4bea600-91d0-11e9-878d-ba2c40a55ca7.png)

**Comment by lovelyesz** [comment]
ps -ef|grep java

**Comment by qianjiaxiang** [comment]
> ps -ef|grep java

![image](https://user-images.githubusercontent.com/16290983/59662641-f2473c00-91df-11e9-9671-24ca5830b5cb.png)
这方法试过了，可以查看到java进程，但是attatch不了

**Comment by hengyunabc** [comment]
用同样用户名，JVM路径。

试下 jstack

**Comment by qianjiaxiang** [comment]
> 用同样用户名，JVM路径。
> 
> 试下 jstack

这个是java的命令监控，现在我主要目的是为了能够使用arthas进行监控

**Comment by hengyunabc** [comment]
> > 用同样用户名，JVM路径。
> > 试下 jstack
> 
> 这个是java的命令监控，现在我主要目的是为了能够使用arthas进行监控

试下 jstack 能找到你的java进程不。或者执行下jps，arthas实际上是找到jps，然后执行来获取进程信息。

`java -jar arthas-boot.jar -v' 可以打印更多信息。

**Comment by qianjiaxiang** [comment]
> > > 用同样用户名，JVM路径。
> > > 试下 jstack
> > 
> > 
> > 这个是java的命令监控，现在我主要目的是为了能够使用arthas进行监控
> 
> 试下 jstack 能找到你的java进程不。或者执行下jps，arthas实际上是找到jps，然后执行来获取进程信息。
> 
> `java -jar arthas-boot.jar -v' 可以打印更多信息。

![image](https://user-images.githubusercontent.com/16290983/59668944-f24d3900-91eb-11e9-8e80-ffe2950beb2e.png)
在运行 java -jar arthas-boot.jar -v 后输出上述图片，这个还没能解决我的问题，还请多指教

**Comment by zhaopa** [comment]
想要attach Tomcat试试直接在启动arthas时指定Tomcat运行的PID。
