### ISSUE TITLE
找不到容器里的java的process

### ISSUE THREAD

**Issue by baikeh** [alibaba/arthas#741]
![1](https://user-images.githubusercontent.com/32256469/59658429-2c134500-91d6-11e9-9cec-ef460b2f6f0e.jpg)

找不到容器里的java的process， 怎么解决？ 谢谢

**Comment by baikeh** [comment]
在宿主机上， 切换到和java process用户相同的用户执行，也是无法列出相应的java进程。。

**Comment by hengyunabc** [comment]
只执行 `exec -it /bin/bash ` 启动bash，再进去用同样的用户名，jvm，来启动 arthas-boot.jar 。

试下在容器里执行 jstack。

在宿主机当然是找不到容器里的java进程。

**Comment by baikeh** [comment]
哦，好的，谢谢，在宿主机上也能看到容器里的java的process，以为也可以。。
找到问题了，问题是容器里的是jre，不是jdk 😓
