### ISSUE TITLE
Arthas 在线教程的小调查

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#742]
目前在线教程有两部分：基础和进阶

* https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-basics
* https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-advanced

想调查的是：

1. 您有执行过在线教程吗？
2. 在线教程是否太长，需要再划分小节？
3. 在线教程的内容是否要更丰富/详细？
3. 在线教程是否卡顿？（因为katacoda服务器在国外）
4. 在线教程是否需要放在更明显的位置/提示？
5. 在线教程对您使用Arthas，排查问题有帮助？

更多对在线教程的建议请留言回复。

**Comment by netroby** [comment]
执行过。还是蛮有用的。


我现在已经不仅在用，而且试图发现一些问题，并动手解决。也提交过两个PR，

希望能多一些教程，比如怎么参与贡献开发。怎么编译打包，本地怎么测试之类的教程（arthas项目本身）

**Comment by lqixv** [comment]
首先说，这个教程太棒了！！！
我试 了一下前面的大部分内容，都挺给力的。中间发生了一些小问题，可能 别人也容易犯下的错误：
1、有部分操作要在新的窗口执行，但没注意到，结果老是不行，还以为是写错了，再仔细看文档才发现是要在新窗口执行。所以建议，部分关键字可以用加粗或其他颜色重点标识。
2、后面的springboot教程，要访问web页面，无法打开
最后想说，非常感谢你们的无私奉献！

**Comment by yesterday11** [comment]
很酷，之前看过基础教程，奈何没有配套的环境试用，自己配环境又太麻烦，现在这都不是事儿了

**Comment by zhuliangcai** [comment]
非常给力，希望再有更多的示例

**Comment by GreedyPirate** [comment]
arthas是我见过最棒的在线教程，省去了用户对linux环境的依赖，鼠标点击就可以实时看效果，连demo都写好了，降低大家的学习成本

**Comment by airfer** [comment]
教程很棒，关于进阶部分，希望示例再多一些，再详细一些~

**Comment by superheizai** [comment]
教程很棒，其实这种工具缺少的就是实践

**Comment by xuyuanzhi051** [comment]
教程很棒，但是进阶部分会出现浏览器打不开的情况

**Comment by hengyunabc** [comment]
已上线全新版本： https://arthas.aliyun.com/doc/arthas-tutorials.html?language=cn
