### ISSUE TITLE
watch无法监控返回实体父类的相关信息

### ISSUE THREAD

**Issue by snwing** [alibaba/arthas#743]
使用命令watch xxx.controller {returnObj} -x 3
返回的展示结果没有显示出返回实体父类的属性值.
返回实体继承的父类来自其他jar包.
求教该怎么操作才能看到父相关的值

**Comment by hengyunabc** [comment]
`returnObj.parentFieldName`

**Comment by rqrtqqpqi5** [comment]
> `returnObj.parentFieldName`

没有更好的解决办法了吗，如果父类属性很多的话，returnObj.parentFieldName 这个办法很麻烦
