### ISSUE TITLE
tt time cost less than zero

### ISSUE THREAD

**Issue by netroby** [alibaba/arthas#746]
- [ x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: 3.1.1
* 目标进程的JVM版本: 3.1.1
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. run `tt -t com.domain.* * `
2. see the result, time cost may less than zero

### 期望的结果

cost time should not be less than zero

### 实际运行的结果

![Screenshot from 2019-06-20 08-40-26](https://user-images.githubusercontent.com/278153/59810336-54ff1b80-9337-11e9-9f85-537e197e2643.png)

**Comment by hengyunabc** [comment]
有没有可以重现的demo？ 也可能是浮点数算法的问题。

**Comment by netroby** [comment]
![Screenshot from 2019-06-20 14-45-27](https://user-images.githubusercontent.com/278153/59826975-16368900-936a-11e9-9064-02e42dabc9a5.png)

**Comment by netroby** [comment]
@hengyunabc I submit a PR, see #748

**Comment by hengyunabc** [comment]
这两个函数生成的字节码从流程上来说是一致的：

```java
	public long cost() {
		return (System.nanoTime() - timestampRef.get());
	}

	public long cost2() {
		long ct = System.nanoTime();
		return (ct - timestampRef.get());
	}
```

```
  public long cost();
    descriptor: ()J
    flags: ACC_PUBLIC
    Code:
      stack=4, locals=1, args_size=1
         0: invokestatic  #27                 // Method java/lang/System.nanoTime:()J
         3: aload_0
         4: getfield      #19                 // Field timestampRef:Ljava/lang/ThreadLocal;
         7: invokevirtual #47                 // Method java/lang/ThreadLocal.get:()Ljava/lang/Object;
        10: checkcast     #33                 // class java/lang/Long
        13: invokevirtual #51                 // Method java/lang/Long.longValue:()J
        16: lsub
        17: lreturn
      LineNumberTable:
        line 17: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      18     0  this   LThreadLocalWatch;

  public long cost2();
    descriptor: ()J
    flags: ACC_PUBLIC
    Code:
      stack=4, locals=3, args_size=1
         0: invokestatic  #27                 // Method java/lang/System.nanoTime:()J
         3: lstore_1
         4: lload_1
         5: aload_0
         6: getfield      #19                 // Field timestampRef:Ljava/lang/ThreadLocal;
         9: invokevirtual #47                 // Method java/lang/ThreadLocal.get:()Ljava/lang/Object;
        12: checkcast     #33                 // class java/lang/Long
        15: invokevirtual #51                 // Method java/lang/Long.longValue:()J
        18: lsub
        19: lreturn
      LineNumberTable:
        line 21: 0
        line 22: 4
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      20     0  this   LThreadLocalWatch;
            4      16     1    ct   J
```

区别是cost2函数多了 

```
         3: lstore_1
         4: lload_1
```

两个函数实际是一样的。 #748 ，用了`ThreadLocalWatch`，这个消耗比较大，掩盖了问题。问题根本还没确定。

**Comment by hengyunabc** [comment]
@netroby 出现负数时，右边完整信息是什么？

**Comment by netroby** [comment]
3楼我贴的图你看下。就是这个简单的测试，就暴露出来了问题。
ThreadLocalWatch 比较慢，所以获取的时间，要滞后一些。
只调用System.nanoTime() 反而获取了更早的时间。

但是如果多了一个赋值，开销就大了一些，降低了计算差值为负数的机率，经过我测试，基本上不会出现负数了


如果你们打算继续用ThreadLocalWatch. 那么这个负数的问题会一直有。

一个可以接受的方案，就是加一行赋值，人为制造一下开销。让时间至少不为负数差值

**Comment by netroby** [comment]
@hengyunabc  I just update my pr. and test it . works good

**Comment by hengyunabc** [comment]
### ThreadLocalWatch的代码

```java
public class ThreadLocalWatch {

    private final ThreadLocal<Long> timestampRef = new ThreadLocal<Long>() {
        @Override
        protected Long initialValue() {
            return System.nanoTime();
        }
    };

    public long start() {
        final long timestamp = System.nanoTime();
        timestampRef.set(timestamp);
        return timestamp;
    }

    public long cost() {
        return (System.nanoTime() - timestampRef.get());
    }

    public double costInMillis() {
        return (System.nanoTime() - timestampRef.get()) / 1000000.0;
    }

    public void clear() {
        timestampRef.remove();
    }

}
```

### 复现的Demo

```java
    public static void main(String[] args) {
        ThreadLocalWatch watch = new ThreadLocalWatch();

        watch.start();
        watch.start();

        double cost1 = watch.costInMillis();

        watch.clear();

        double cost2 = watch.costInMillis();

        System.err.println("cost1: " + cost1);
        System.err.println("cost2: " + cost2);
    }
```

结果：

```
cost1: 0.004864
cost2: -0.022215
```

### 原因一：clear掉ThreadLocal的值，导致要重新执行`initialValue()`

从上面的代码可以看到，执行了`watch.clear();`之后，再执行 `double cost2 = watch.costInMillis();` 。

那么为什么这个行为会出现负数呢？

因为clear之后，`timestampRef` 需要重新执行`initialValue()`函数。所以在执行 `watch.costInMillis()`时，调用到 `timestampRef.get()`，需要调用`initialValue()` 重新获取 `System.nanoTime()`。

所以 `return (System.nanoTime() - timestampRef.get()) / 1000000.0;` 执行的结果是负数。


### 原因二：为什么会出现上面的时序，`clear()`出现在两个`watch.costInMillis()`调用之间

首先目前tt命令是怎么工作的：

1. 在函数的入口执行 `watch.start();`
2. 在函数的结尾执行 `watch.costInMillis(); ` ，再执行 `watch.clear();`

具体代码在 `TimeTunnelAdviceListener`里。

正常来说，这个流程里不会出现 `costInMillis()`, `clear()`, `costInMillis()` 的时序的。

但是对于Spring AOP修改过的类，会出现上面的时序。

因为Spring AOP是生成一个子类，它实现了父类一样的函数。

**所以 tt命令在执行时，会匹配到两个类，并且对两个类都做了增强处理。**

以一个被aop处理过的`test()`函数为例，时序是：

1. 进入 proxy.test()
1. threadLocalWatch.start()
1. 进入 test()
1. threadLocalWatch.start()
1. threadLocalWatch.costInMillis(), threadLocalWatch.clear()
1. 结束 test()
1. threadLocalWatch.costInMillis(), threadLocalWatch.clear()
1. 结束 proxy.test()

所以出现负数的案例里，都是 spring aop的bean。

**Comment by netroby** [comment]
@hengyunabc 跟spring boot 没关系，图三，是单独跑的demo，已经抛去了所有的干扰。
