### ISSUE TITLE
trace命令是否支持跟踪lamda表达式的方法？

### ISSUE THREAD

**Issue by NevilleYeung** [alibaba/arthas#747]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.1
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

###方法堆栈
        at org.apache.servicecomb.common.rest.AbstractRestInvocation.lambda$scheduleInvocation$0(AbstractRestInvocation.java:159)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hengyunabc** [comment]
给出一个具体的demo。

lambda动态生成的类里，有一些是不可修改的，所以trace可能会失败。

**Comment by Rfiy** [comment]
+---[0.001954ms] java.util.List:stream() #41
+---[0.001122ms] java.util.stream.Stream:map() #41
+---[0.001052ms] java.util.stream.Stream:filter() #50
+---[0.001076ms] java.util.stream.Collectors:toList() #50
`---[112.377283ms] java.util.stream.Stream:collect() #50
lambda里面的方法确实不能trace到，而且反应出来的时间和实际也不准确呢，有方法能够支持lambda吗？现在被lambda包裹的代码也很常见呢。

**Comment by Xue2015** [comment]
lambda里面的方法确实不能trace到，而且反应出来的时间和实际也不准确呢，有方法能够支持lambda吗？现在被lambda包裹的代码也很常见呢。请问这个问题现在解决了吗，我也遇到这个问题了

**Comment by kylixs** [comment]
请参考这个: https://github.com/alibaba/arthas/issues/270
根据生成lambda方法命名规则，可以这么匹配：
`trace class_name *method_name*`

**Comment by hplegend** [comment]
可以先用字节码工具看到lambda表达式内部生成的名称，如：lambda$new$1,lambda$new$2，后面的序号1，2并不是按照lambda表达式书写的顺序生成，具体看字节码即可。

然后用trace命令跟踪: trace 包名.类名  lambda$new$n。lambda$new$n需要自行在字节码中查找。
