### ISSUE TITLE
疑似功能缺失 .class中的类无法找到

### ISSUE THREAD

**Issue by taojiaenx** [alibaba/arthas#749]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

*  `as.sh` 的版本： 
* Arthas 版本: 3.1.1
* 操作系统版本: linux
* 目标进程的JVM版本: 1.8.0_45
* 执行`arthas-boot`的版本: .as.sh

### 重现问题的步骤

我们这边的服务又很多代码是放在.class文件中的
存放的格式为
source-path/com/xxx/busineessa1/a.class
source-path/com/xxx/busineessa2/b.class

执行 sc发现无法找到 a类和b类，但是位于jar中的类是可以找到的
### 期望的结果

执行sc可以找打目标类

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。
./as.sh PID
sc **busuiness1**
Affect(row-cnt:0) cost in 23 ms.

**Comment by hengyunabc** [comment]
找不到的类，说明没有被加载到jvm里。

**Comment by taojiaenx** [comment]
这个是差不多是个contorller， 如果没有被加载，这个节点都无法对外提供服务，
而且确认了进程号没有错，我这边还直接kill了一些，确认无误
目前发现的情况是
jar中提供的类都可以找到，
如果我把源代码以jar的形式部署，那之前找不到的类也同样可以找到
只是在以.class文件散列的形式部署，就会找不到对应的类
我这边再看一下。。。

**Comment by taojiaenx** [comment]
同步一下目前的情况，
我通过jmap可以找到的类，命令为
jmap -histo  PID | fgrep 'BusinessA'
但是通过sc找不到  BusinessA

**Comment by hengyunabc** [comment]
arthas里是通过 `java.lang.instrument.Instrumentation#getInitiatedClasses` 来获取到所有类的，所以JVM已加载到的类都会找到。 可以看下 `SearchClassCommand`的代码。

**Comment by taojiaenx** [comment]
感谢， 我这先看一下

**Comment by taojiaenx** [comment]
问题解决了
发现的原因是
HTTP_PORT 8563
TELNET_PORT 3658 被占用
