### ISSUE TITLE
cfr has it's own mvn repository. arthas should using upstream instead include an jar package.

### ISSUE THREAD

**Issue by netroby** [alibaba/arthas#750]
cfr has it's own mvn repository. arthas should using upstream instead include an jar package.
The current arthas has include an jar (0.132)
which has it's own mvn repository now, so we can just follow upstream

**Comment by hengyunabc** [comment]
查了一下 http://search.maven.org/classic/#search%7Cgav%7C1%7Cg%3A%22org.benf%22%20AND%20a%3A%22cfr%22 ， cfr是18年11月开始发到maven仓库里的。arthas开源时还没放到仓库里。
