### ISSUE TITLE
mc 编译使用 lombok 的类失败

### ISSUE THREAD

**Issue by e23s5678** [alibaba/arthas#759]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.1
* 操作系统版本: Linux
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. jad后 mc 找不到方法和依赖
2. 不jad 直接mc源java文件 也缺依赖 找不到log @Slf4j 注解的log.warn

### 期望的结果
1、不说了
2、直接mc应该可以吧 

### 实际运行的结果
2 也缺依赖 找不到log @Slf4j 注解的log.warn
实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
1的异常
![image](https://user-images.githubusercontent.com/14970076/60262049-dfcfaf80-990f-11e9-8b2b-5b3fdfe4d28a.png)

```
2的异常
![image](https://user-images.githubusercontent.com/14970076/60261999-c169b400-990f-11e9-80b3-4e4fc5136206.png)

**Comment by hengyunabc** [comment]
。。用 lombok 的编译不了，先看下 lombok的工作原理。

**Comment by dev-techmoe** [comment]
把delombok的操作加到你输出新java代码的过程就ok了。

https://projectlombok.org/features/delombok

idea右键delombok一样效果。
