### ISSUE TITLE
spring aop

### ISSUE THREAD

**Issue by hyqkuku** [alibaba/arthas#760]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

spring一次请求可能会有多个aop被触发执行，有没有哪个命令能够监测到哪些aop被触发以及每个aop执行耗时的命令？

**Comment by hengyunabc** [comment]
没有这么神奇的命令。artahs可以 trace指定的函数。应用的profile的话，可以下载一些专业的profile工具。
