### ISSUE TITLE
tt 将会把redefine后的类的重设

### ISSUE THREAD

**Issue by andxu** [alibaba/arthas#762]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: Windows 10 1809
* 目标进程的JVM版本: Oracle jdk 8
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. 打开MathGame工程， 修改print代码里的最后一条打印语句，改成`System.out.println("tttttt@" + sb);`
2. 启动MathGame和arthas,`java -cp xxx demo.MathGame`,  `java -jar arthas-boot.jar`
3. 在arthas的console里执行 `tt -t demo.MathGame print`
4. 这个时候在console里能看到 `tttttt@`开头的log
5. 按q结束掉tt命令，再编辑tttttt@为llllll@，
6. 在console里运行redefine语句：redefine demo\\target\\classes\\demo\\MathGame.class
7. 这个时候在console里能看到 `llllll@`开头的log
8. 在arthas的console里执行 `tt -t demo.MathGame print`
9. 这个时候log换成了一开始的tttttt@

### 期望的结果

step 9上仍然输出 llllll@

### 实际运行的结果
step 9上仍然输出 tttttt@

**Comment by hengyunabc** [comment]
参考下这个： https://github.com/alibaba/arthas/issues/763

触发了 retransform 之后，redefine的修改就会没了。
