### ISSUE TITLE
arthas-boot.jar 不能捕捉 java 进程

### ISSUE THREAD

**Issue by githublms** [alibaba/arthas#768]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: xxx
* 操作系统版本: centos7
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤
官网下载arthas-boot.jar与arthas-demo.jar 启动两个jar包，不能捕捉java进程

### 期望的结果
捕捉java进程
What do you expected from the above steps？

### 实际运行的结果
不能捕捉java进程
实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
[@localhost arthas_test]$ ps -aux | grep arthas-demo.jar
      7197  0.5  1.2 2892428 23796 pts/0   Sl   13:44   0:00 java -jar arthas-demo.jar
        7325  0.0  0.0 112720   996 pts/0    S+   13:44   0:00 grep --color=auto arthas-demo.jar
[@localhost arthas_test]$ java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.1.1
[INFO] Can not find java process. Try to pass <pid> in command line.
Please select an available pid.

**Comment by hengyunabc** [comment]
要用 jdk来启动，用jre找不到 tools.jar，找不到进程。

**Comment by blackstar-baba** [comment]
@githublms `java -jar arthas-boot.jar <pid> `试试，可以提示具体异常信息
