### ISSUE TITLE
使用arthas捕捉java进程，java基础项目和web项目需要什么条件或者其他内容？

### ISSUE THREAD

**Issue by githublms** [alibaba/arthas#769]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？
我有一个javaweb项目，我想使用arthas捕捉这个java进程，java环境和虚拟机环境正常，但是捕捉不到？我想问这个web项目中是否需要加一些固定的代码还是其他的什么内容。？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
* 使用同样的jvm，使用jdk而不是 jre。 
* 用jps能列出来，用arthas也能attach上去

**Comment by luojianjianjun** [comment]
参考一下我这个案例，项目的部署情况 vmare -> cnetos7->tomcat->javaweb
1.启动项目（admin用户）
2.启动arthas（admin用户）
3.发现arthas无法绑定到tomcat进程
4.提升admin用户权限到root
5.再次运行arthas发现可以绑定到tomcat进程
