### ISSUE TITLE
arthas 可以修改静态文件吗？

### ISSUE THREAD

**Issue by githublms** [alibaba/arthas#771]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.1
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

我想实现arthas来修改静态的html，js，application.yml等文件，请问应该怎样操作？
我想根据路径去找到对应的源码进行查看或其他操作，应该怎么操作？

**Comment by hengyunabc** [comment]
直接登陆机器修改就可以了。 arthas没有这样的功能。
