### ISSUE TITLE
<ctrl+L>清屏快捷键不能使用

### ISSUE THREAD

**Issue by iportman** [alibaba/arthas#776]
平时使用的时候经常要清屏，cls不方便，使用ctrl+l方便而且符合普通shell用户的习惯
是否可以增加

**Comment by hengyunabc** [comment]
试了下在  `core/src/main/resources/com/taobao/arthas/core/shell/term/readline/inputrc` 增加：

```
"\C-l": clear-screen
```

发现不生效，可能需要在termd里增加支持。 termd的代码里本身有一些 clear-screen 的内容，但貌似不生效。

**Comment by iportman** [comment]
我看了一下termd的源代码，在下面这个地方加个判断就可以解决<ctrl+L>的问题，我提个pull request给com.alibaba.middleware:termd吧

**Comment by iportman** [comment]
termd的pull request已提交
https://github.com/alibaba/termd/pull/17

**Comment by iportman** [comment]
清屏功能持续改善：ctrl-l清屏保留当前行输入字符
https://github.com/alibaba/termd/pull/18
