### ISSUE TITLE
trace不能追踪被Spring代理的方法

### ISSUE THREAD

**Issue by yun-yun** [alibaba/arthas#780]
最深只追踪到org.springframework.cglib.proxy.MethodInterceptor:intercept() #0
![image](https://user-images.githubusercontent.com/29945346/61433902-1d4fb780-a967-11e9-9dd6-b605bb008d71.png)

**Comment by yun-yun** [comment]
可能是因为这个方法体太长，因此不显示

**Comment by tengwei-lewis** [comment]
有什么解决办法没？

**Comment by lianyuteng** [comment]
是因为方法体太长，但是怎么解决哦
