### ISSUE TITLE
jad 和 redefine没有生效，可能是什么原因呢

### ISSUE THREAD

**Issue by zhuliangcai** [alibaba/arthas#781]
$ redefine /tmp/xx/xxx/XXX.class
redefine success, size: 1

请问下有redefine成功了，但是用jad再次反编译后发现改过的代码并没有加上是怎么回事呢？

**Comment by zhuliangcai** [comment]
多次redefine之后报错了，元空间内存溢出<_>
01 2019-07-18 19:48:16.173 INFO [nioEventLoopGroup-2-3:arthas] [] [] [] Loaded arthas keymap file from com/taobao/arthas/core/shell/term/readline/inputrc
01 2019-07-18 19:49:19.912 WARN [as-command-execute-daemon:arthas] [] [] [] Memory compiler error
java.lang.OutOfMemoryError: Metaspace
01 2019-07-18 19:49:21.219 ERROR [nioEventLoopGroup-2-3:arthas] [] [] [] completion error
java.lang.OutOfMemoryError: Metaspace
01 2019-07-18 19:51:29.308 ERROR [nioEventLoopGroup-2-3:i.t.c.io_error] Reported io error => closing
java.lang.OutOfMemoryError: Metaspace

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/390

https://github.com/alibaba/arthas/issues/763 

redefine 和jad是两套不同的机制，会冲突。
