### ISSUE TITLE
shutdown命令后，应用程序报空指针异常

### ISSUE THREAD

**Issue by baimoer** [alibaba/arthas#783]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 最新版本
* Arthas 版本: 最新版本
* 操作系统版本: windows
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 最新版本

### 重现问题的步骤

进入arthas后，trace 一个方法后，执行 shutdown 命令，应用程序中止，报空指针异常

Exception in thread "main" java.lang.NullPointerException
	at jie.lombok.PersonTest.run(PersonTest.java:22)
	at jie.lombok.PersonTest.main(PersonTest.java:9)

### 期望的结果

正常结束，不影响应用程序

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
package jie.lombok;

import java.util.Random;

public class PersonTest {

    public static void main(String[] args) {
        while (true){
            run();
        }
    }

    private static void run(){
        Random r = new Random();
        int i = r.nextInt(2000);
        try {
            Thread.sleep(i);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("hello:" + i);
    }


}

```
trace jie.lombok.PersonTest run
```

```

```
Exception in thread "main" java.lang.NullPointerException
	at jie.lombok.PersonTest.run(PersonTest.java:22)
	at jie.lombok.PersonTest.main(PersonTest.java:9)
```

```
把异常信息贴到这里
```

**Comment by lihe2011** [comment]
嗯。 我也遇到了同样的问题。

**Comment by lihe2011** [comment]
执行一下 reset 命令，再执行shutdown就不会报NullPointerException了。

**Comment by Roger3581321** [comment]
您好,@baimoer ,按照提供的复现步骤,在trace方法后,执行shutdown方法,会抛出NullPointerException,截图如下:
![Capture](https://user-images.githubusercontent.com/23419065/74409923-ccf3f600-4e72-11ea-9cd5-98b2df1dba76.JPG)
![Capture1](https://user-images.githubusercontent.com/23419065/74409991-fdd42b00-4e72-11ea-9be9-05e82ac63cdf.JPG)

**Comment by hengyunabc** [comment]
这个应该修复掉了。
