### ISSUE TITLE
reset无效与jad自动触发一次redefine

### ISSUE THREAD

**Issue by aqqwiyth** [alibaba/arthas#788]
### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: OSX
* 目标进程的JVM版本: java8
* 执行`arthas-boot`的版本: 3.1.1

主要是想调试线上环境agent中的一个逻辑.发现jad/redefine都不好使了. 

本地测试环境背景介绍
java  -javaagent:agent.jar -jar xxxxx.jar
      ---> agent.jar
		--> XX.java

##### redefine  XX.class
> redefine success, size: 1

-----目标进程控制台输出-------
>redefine first
>redefine first
>redefine first....

#####  reset
> Affect(class-cnt:0 , method-cnt:0) cost in 2 ms.

-----目标进程控制台输出-------
>redefine first
>redefine first
>redefine first....
**触发: BUG**

shutdown无效

##### 第二次 redefine     XX类中指定任意方法   System.out.println("redefine second");

-----目标进程控制台输出变化-------
>redefine first
>redefine first
>redefine first 
> 第二次 redefine
>redefine second
>redefine second
>redefine second....

#####  jad XX   输出的是 redefine 1时候的代码,紧接着自动redefine了...
**触发BUG 2:  使用一次的代码**

-----目标进程控制台输出-------
>redefine first
>redefine first
>redefine first....

shutdown无效.

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/390

https://github.com/alibaba/arthas/issues/763 

redefine 和jad是两套不同的机制，会冲突。

**Comment by aqqwiyth** [comment]
BUG 1  是否是跟  BootstrapClassLoader 与Instrumentation的机制有关

**Comment by hengyunabc** [comment]
shutdown不能去掉 redefine的效果。
