### ISSUE TITLE
json

### ISSUE THREAD

**Issue by initpassion** [alibaba/arthas#789]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by initpassion** [comment]
请问下, 现在能将一些结果序列化成json格式吗, 比如 使用了gatstatic **.cache CACHE_MAP  'entrySet().iterator.{? #this.key=="code"}'之后 希望得到一个json话的数据

**Comment by hengyunabc** [comment]
https://alibaba.github.io/arthas/options.html?highlight=json
