### ISSUE TITLE
as-package.sh无法使用，一直阻塞

### ISSUE THREAD

**Issue by zonghaishang** [alibaba/arthas#79]
mac 10.13.3, 拉取最新代码执行 ./as-package.sh无法执行，一直阻塞，我看了变更：

```
#get_local_maven_project_version()
#{
#    $DIR/mvnw org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -e '^[^\[]' | cut -b 1-5
#}

#CUR_VERSION=$(get_local_maven_project_version)

和

# $DIR/mvnw clean package -Dmaven.test.skip=true -f $DIR/pom.xml \
```

我把这部分代码还原回去正常打包

**Comment by hengyunabc** [comment]
检查网络，单独在命令行里执行 

```
./mvnw org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -e '^[^\[]' | cut -b 1-5
```

**Comment by zonghaishang** [comment]
@hengyunabc 执行报错：
```
➜  arthas git:(master) ✗ ./mvnw org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -e '^[^\[]' | cut -b 1-5
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.apache.maven.wrapper.Installer.unzip(Installer.java:161)
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:78)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)

```

**Comment by zonghaishang** [comment]
@hengyunabc 大兄弟帮忙看下这个问题？issue先打开吧，好跟踪

**Comment by hengyunabc** [comment]
> @hengyunabc 执行报错：
> 
> ```
> ➜  arthas git:(master) ✗ ./mvnw org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -e '^[^\[]' | cut -b 1-5
> Exception in thread "main" java.util.zip.ZipException: error in opening zip file
>         at java.util.zip.ZipFile.open(Native Method)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:225)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:155)
>         at java.util.zip.ZipFile.<init>(ZipFile.java:169)
>         at org.apache.maven.wrapper.Installer.unzip(Installer.java:161)
>         at org.apache.maven.wrapper.Installer.createDist(Installer.java:78)
>         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
>         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)
> ```

这个明显是maven wrapper下载到的 zip包有问题，检查下载到哪里了，清理掉，重新跑
