### ISSUE TITLE
能否结合ganglia监控

### ISSUE THREAD

**Issue by sleeeeeeper** [alibaba/arthas#791]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

我们试图将arthas和ganglia结合完成jvm信息的监控，但是找不到程序的接口， 要怎么才能自动获取jvm的信息到ganglia呢？

**Comment by hengyunabc** [comment]
arthas主要是出问题是诊断，不是运行时监控。可以找下其它的一些监控工具。

**Comment by sleeeeeeper** [comment]
其实并不需要用arthas来进行监控，比如说我想要dashboard出来的数据，有没有什么接口可以让我通过脚本或者其他方法可以拿到这个数据，或者用脚本跟arthas互动的方法有没有呢




------------------ 原始邮件 ------------------
发件人: "hengyunabc"<notifications@github.com>;
发送时间: 2019年7月30日(星期二) 下午3:10
收件人: "alibaba/arthas"<arthas@noreply.github.com>;
抄送: "111"<2290085762@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/arthas] 能否结合ganglia监控 (#791)




arthas主要是出问题是诊断，不是运行时监控。可以找下其它的一些监控工具。

**Comment by hengyunabc** [comment]
一般的监控平台都会有一个agent来执行脚本，通过jmx获取jvm监控数据，比如 zabbix 就有java监控相关的脚本。
