### ISSUE TITLE
集群管理问题

### ISSUE THREAD

**Issue by papalian** [alibaba/arthas#796]
我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

我有个疑问，不知能否得到解答。
1. 我打算在生产服务器集群(001-100) , 架构为(公网>F5>NGINX集群>TOMCAT集群),  里面使用Arthas；
2. 因生产线运维与研发是权限分离的，安装Arthas是为了方便研发排查问题，但是不能有变更生产环境代码的权限；
2. 按目前的支持，应该是需要给每台服务器商上都安装Arthas；
3. 因为安全问题，我只能在灰度服务器001上开放公网入口(NGINX加IP白名单限制访问)，让技术可以在指定IP网络下访问生产Arthas；
目前的问题是：
1. 是否只要001-100的网络互通，就可以在001机器上通过Web console 访问各机器的Arthas
2. 我想做好安全控制，如何在web console页面加上登录限制(账号密码方式)；
3. 我想屏蔽Arthas的某些危险命令(例如:redefine)，应该在哪里进行配置？
4. 如何方便的操作各个服务器上Arthas的启动和退出

**Comment by hengyunabc** [comment]
可以考虑用最新的 tunnel server来做管理。 

https://alibaba.github.io/arthas/web-console.html#arthas-tunnel-serverarthas

**Comment by chenshun00** [comment]
@hengyunabc 安装文档安装下载的，没有连接上去 ，agentId都没有

**Comment by hengyunabc** [comment]
@chenshun00 具体启动的参数是什么，另外有没有自己跑 tunnel server

**Comment by chenshun00** [comment]
@hengyunabc  启动参数是 `java -jar -Dserver.port=19992 arthas-tunnel-server-3.1.4.jar` , 从文档的下载链接下载的。https://github.com/alibaba/arthas/releases

as.sh  :  `./as.sh --tunnel-server 'ws://127.0.0.1:7777/ws'` 

然后出现的结果就是上边那个截图

**Comment by hengyunabc** [comment]
@chenshun00 

首先这个启动就会失败。。 `java -jar -Dserver.port=19992 arthas-tunnel-server-3.1.4.jar ` ，应该是

`java -Dserver.port=19992 -jar  arthas-tunnel-server-3.1.4.jar ` 

另外，查看 `~/logs/arthas/arthas.log`里的内容。 或者试下连测试的服务器： https://alibaba.github.io/arthas/web-console.html#arthas-tunnel-serverarthas

**Comment by chenshun00** [comment]
@hengyunabc  那个也是可以启动的

**Comment by chenshun00** [comment]
@hengyunabc  好的，现在知道了 👍
