### ISSUE TITLE
内存分析

### ISSUE THREAD

**Issue by BarryIsIronMan** [alibaba/arthas#80]
我用了一下没看到内存分配方面的监控，可以接入类似aprof这种插件吗？

**Comment by ralf0131** [comment]
Currently the memory related diagnostics is not supported.
Arthas currently is mainly focusing on help user easier to trouble-shooting business-logic.

Can you provide link to aprof? I'd like to do some investigation on it.

**Comment by BarryIsIronMan** [comment]
https://github.com/Devexperts/aprof    this is the link

**Comment by ralf0131** [comment]
@BarryIsIronMan Thanks for sharing, I will take a look.

**Comment by ralf0131** [comment]
Hi I took a quick look at aprof, it looks interesting. The idea behind is similar to what Arthas does, which modifies the byte code of specified method. But I am wondering the performance impact. 

Did you try it out? Do you have some feedback on it?

**Comment by BarryIsIronMan** [comment]
Difference between Arthas and Aprof is that Aprof made a detailed memory analysis ,nor do Arthas.
I just have tired to use Aprof to test the performance of SDKs offline  install of application online,so performance loss is just my imagination.
I know Arthas watch runtime status application,does it can provide a offline version which integrate some heavy plugins for middleware Sdks :-)
