### ISSUE TITLE
如何对匿名内部类的方法watch

### ISSUE THREAD

**Issue by zuodengchao** [alibaba/arthas#809]
LinkKit.getInstance().init(params, new ILinkKitConnectListener() {
            public void onError(AError aError) {
                ALog.e(TAG, "Init Error error=" + aError);
            }

            public void onInitDone(InitResult initResult) {
                ALog.i(TAG, "onInitDone result=" + initResult);
                executeScheduler(deviceInfoData);
            }
        });

如何对 onError方法进行trace 或者 watch

**Comment by hengyunabc** [comment]
`OuterClass$InnerClass`
