### ISSUE TITLE
[疑问]用完需要清理现场吗？

### ISSUE THREAD

**Issue by konglz** [alibaba/arthas#812]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

全部版本

### 问题

1. 在生产环境挂着arthas跑，只增强3~5个方法，只用trace，有多大性能损耗？
2. 用完需要清理现场吗？是否需要 执行shutdown 甚至 重启应用进程？
3. 执行shutdown对性能损耗较大，只增强了1个方法的时候，执行2次shutdown把cpu打满了。

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/44
