### ISSUE TITLE
阿里云无法下载依赖的情况

### ISSUE THREAD

**Issue by aqqwiyth** [alibaba/arthas#813]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: xxx
* 操作系统版本: xxx
* 目标进程的JVM版本: xxx
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤
[nobody@aliyun-APP-103-152 ~]$ wget https://alibaba.github.io/arthas/arthas-boot.jar
--2019-08-13 11:50:57--  https://alibaba.github.io/arthas/arthas-boot.jar
正在解析主机 alibaba.github.io... 185.199.111.153, 185.199.109.153, 185.199.108.153, ...
正在连接 alibaba.github.io|185.199.111.153|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：98637 (96K) [application/java-archive]
正在保存至: “arthas-boot.jar”
2019-08-13 11:51:11 (9.38 KB/s) - 已保存 “arthas-boot.jar” [98637/98637])

[nobody@aliyun-APP-103-152 ~]$ ll
总用量 100
-rw-r--r-- 1 nobody nobody 98637 5月  16 11:43 arthas-boot.jar
[nobody@aliyun-APP-103-152 ~]$ java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.1.1
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 4268 org.apache.catalina.startup.Bootstrap
[ERROR] Can not read maven-metadata.xml from: http://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/maven-metadata.xml
[ERROR] Can not find Arthas under local: /tmp/.arthas/lib and remote: aliyun
[nobody@aliyun-APP-103-152 ~]$ ping maven.aliyun.com
PING tyjr-common-cn-beijing.aliyun.com (182.92.29.16) 56(84) bytes of data.
64 bytes from 182.92.29.16: icmp_seq=1 ttl=46 time=5.35 ms
64 bytes from 182.92.29.16: icmp_seq=2 ttl=46 time=5.34 ms
64 bytes from 182.92.29.16: icmp_seq=3 ttl=46 time=5.31 ms
^C
--- tyjr-common-cn-beijing.aliyun.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2641ms
rtt min/avg/max/mdev = 5.313/5.334/5.351/0.085 ms

### 实际运行的结果

```
java -jar arthas-boot.jar   
[INFO] arthas-boot version: 3.1.1
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 4268 org.apache.catalina.startup.Bootstrap
-> 1

[ERROR] Can not read maven-metadata.xml from: http://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/maven-metadata.xml
[ERROR] Can not find Arthas under local: /tmp/.arthas/lib and remote: aliyun
```
据说是阿里云的仓库有变更手动绑定host即可 
59.110.144.164 maven.aliyun.com

**Comment by hengyunabc** [comment]
你的机器网络不通，到安装文档里 下载离线的zip包。
