### ISSUE TITLE
websocket对接Arthas，每5s发心跳包会在1-2min左右断开，请问Arthas的超时是多久

### ISSUE THREAD

**Issue by wangzxnpu** [alibaba/arthas#826]
想通过websocket做个小工具和Arthas对接，也开了线程每5s发个心跳包{"action":"read","data":""}。但是还是最在1-2分钟左右断开websocket连接，请问Arthas的超时是多久。谢谢！

**Comment by hengyunabc** [comment]
心跳应该是netty里的 websocket默认有实现和处理。 https://github.com/alibaba/termd/blob/termd-core-1.1.7.4/src/main/java/io/termd/core/http/netty/TtyServerInitializer.java


termd协议里的心跳可能要看下相关的文档，或者js库里的实现。
