### ISSUE TITLE
Can't match the correct method.

### ISSUE THREAD

**Issue by sofkyle** [alibaba/arthas#827]
- [x] I have searched the [issues](https://github.com/alibaba/arthas/issues) of this repository and believe that this is not a duplicate.

### Environment

* Arthas version: 3.1.1
* Operating System version: centos7 3.10.0-957.5.1.el7.x86_64
* Java version of target JVM: 1.8.0_151
* Java version of JVM used to attach: 1.8.0_151

### Steps to reproduce this issue

1. execute the **sm** command:   
> sm java.util.zip.ZipFile getEntry params 'params[0].class.name=="java.lang.String"'  
2. the result is:  
![image](https://user-images.githubusercontent.com/7426860/63495048-abccd100-c4f1-11e9-88be-e24999659f75.png)  

### Expected Result

Only print the line:  
**java.util.zip.ZipFile getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry;**

### Actual Result

I referred to the solution in #434 about overload, but redundant results still be printed.

**Comment by hengyunabc** [comment]
`sm` do not support  `expression`.   


`sm -h`

**Comment by sofkyle** [comment]
> `sm` do not support `expression`.
> 
> `sm -h`

It's just convenient for description.  

In my case, the **watch** is also invalid:  
> watch java.util.zip.ZipFile getEntry params 'params[0].class.name=="java.lang.String"'  

![image](https://user-images.githubusercontent.com/7426860/63502091-62837e00-c4ff-11e9-896e-69e3e52075db.png)
