### ISSUE TITLE
trace命令，每个节点上耗时

### ISSUE THREAD

**Issue by w77996** [alibaba/arthas#830]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: linux
* 目标进程的JVM版本: jdk1.8
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. 进入arthas执行trace命令，没有跟踪到方法内每个节点上耗时
![image](https://user-images.githubusercontent.com/20549246/63512801-370c8d80-c517-11e9-8e18-bc94dafd2736.png)

### 期望的结果

希望输出trace正常的内容

**Comment by hengyunabc** [comment]
函数没有被调用
