### ISSUE TITLE
执行shutdown的注意事项 使得服务器关闭了

### ISSUE THREAD

**Issue by zhugw** [alibaba/arthas#838]
> 请注意，这些命令，都通过字节码增强技术来实现的，会在指定类的方法中插入一些切面来实现数据统计和观测，因此在线上、预发使用时，请尽量明确需要观测的类、方法以及条件，诊断结束要执行 `shutdown`

今天调试线上代码的时候 想执行shutdown退出arthas 结果没想到arthas已经退出了（可能是超时退出了） 于是直接执行了服务器的shutdown命令 导致服务器关闭 宕机了20分钟

真不应该用shutdown啊

**Comment by hengyunabc** [comment]
下个版本增加了 `stop`命令，并且arthas的提示符会改为 `arthas@pid` 。

**Comment by leemon9527** [comment]
使用非root用户的重要性体现出来了。
我今天也是这样，执行了shutdown,普通用户提示must be root,

**Comment by wayneliu91** [comment]
现在stop命令可以用了，但是文档上没有改，会有误导，我也是到这里搜了一下，才发现shutdown已经可以用stop代替了，希望文档上可以改一下。
