### ISSUE TITLE
使用arthas的-c 出现的问题

### ISSUE THREAD

**Issue by leemon9527** [alibaba/arthas#841]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` ： 3.1.1
* 操作系统版本: CentOS 7.4
* 目标进程的JVM版本: 1.8.0_131

### 重现问题的步骤

1. java -jar arthas-boot.jar -c shutdown 有机率卡死，一直不退出，目标java进程没有问题
2. 使用shell脚本取相关的信息会有机率取不到jvm相关的信息
#!/bin/bash
excuter="java -jar /home/common/arthas-boot.jar"
ps aux | grep java | grep -v grep | while read line ;do
    java_pid=`echo $line | awk '{print $2}'`
    java_name=`echo $line | awk '{print $NF}'`
    project_name=`basename ${java_name} | awk -F. '{print $1}'`
    echo $java_pid,$project_name
    ${excuter} $java_pid -c jvm --width 150 2>&1 | grep "^ HEAP-MEMORY-USAGE"
    sleep 5
    ${excuter} $java_pid -c shutdown 2>&1 > /dev/null
    sleep 5
done

**Comment by sky132333** [comment]
I also encountered this situation, which was avoided by the following methods ，set timeout time kill when timeout：
timeout -s 9 300s  $JAVA_HOME/bin/java -jar arthas-boot.jar  --http-port=-1 --telnet-port=$try_port -c "jvm"  $app_pid

**Comment by hengyunabc** [comment]
新版本应该解决了，可以试下。
