### ISSUE TITLE
在watch命令时，如何监控指定值

### ISSUE THREAD

**Issue by mynameislichengeng** [alibaba/arthas#844]
你好，我有这样一个需求。

```
public class SdkTokenServiceImpl{
     public List getList(String ak){
     
    }
}
```

常规使用是如下方式来监控：
          watch SdkTokenServiceImpl getList "{params[0]}"

问题就这里来了，我只想打印 变量 当ak="abcd"时的情况

**Comment by hengyunabc** [comment]
用 `redefine`命令

**Comment by AlexanderDong** [comment]
watch SdkTokenServiceImpl getList "{params[0]}" "'abcd'.equals(params[0])"
