### ISSUE TITLE
Provide a separate tutorial for each command/ Arthas在线教程重新编排，每个命令一个小教程

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#847]
There are currently two parts to the online tutorial: basic and advanced

https://alibaba.github.io/arthas/arthas-tutorials?language=en&id=arthas-basics
https://alibaba.github.io/arthas/arthas-tutorials?language=en&id=arthas-advanced

* Each little tutorial is longer, and adding new content will cause the tutorial to get longer and longer
Users tend to lose patience.
* It's hard to find what you need.
* More users want to see the usage of a command directly
So consider.

Provide a separate tutorial for each command, such as a separate tutorial for the `watch` command, so that many tips can be written in.

One tutorial per case to make it easier for users to learn to use Arthas.

What we need to:

1. Register an account here and write a tutorial for Arthas' single command: https://www.katacoda.com/.
2. Test the tutorial, then send the PR merge to https://github.com/alibaba/arthas/tree/master/tutorials/katacoda
3. Update the web packe： https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/_include_html/arthas-tutorials.html

---

目前在线教程有两部分：基础和进阶

* https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-basics
* https://alibaba.github.io/arthas/arthas-tutorials?language=cn&id=arthas-advanced

之前的一些调查结果： https://github.com/alibaba/arthas/issues/742

目前在线教程有两部分：基础 和 进阶。

* 每个小教程都是比较长，再增加新的内容会导致教程越来越长
* 用户容易失去耐心
* 不好找到需要的内容
* 更多的用户是想直接看某个命令的用法

---

所以考虑

* 每个命令一个教程，比如`watch`命令单独一个教程，这样子很多小技巧都可以写进去
* 每一个案例一个教程，方便用户对应问题学习

需要做的事情：

* 拆分教程
* 为单个命令提PR到： https://github.com/alibaba/arthas/tree/master/tutorials/katacoda
* 修改现有的web页面 ： https://github.com/alibaba/arthas/blob/master/site/src/site/sphinx/_include_html/arthas-tutorials.html

**Comment by HollowMan6** [comment]
您好，我对这个SoC2020项目感兴趣，希望能参与这个项目，请问应该如何与社区联系来进一步讨论项目细节？

**Comment by arteevraina** [comment]
@hengyunabc Can you add english translation for this idea. So I can get proper understanding of this idea.

**Comment by hengyunabc** [comment]
> 您好，我对这个SoC2020项目感兴趣，希望能参与这个项目，请问应该如何与社区联系来进一步讨论项目细节？

1. 可以在这里注册帐号，然后编写自己的教程： https://www.katacoda.com/ 。
2. 创建好示例，测试没有问题之后，再提PR合并到 https://github.com/hengyunabc/katacoda-scenarios

**Comment by hengyunabc** [comment]
> @hengyunabc Can you add english translation for this idea. So I can get proper understanding of this idea.

Updated.

**Comment by HollowMan6** [comment]
@hengyunabc 我已经按照要求将中文高级教程进行了初步拆分，并且提了一个PR [#2](https://github.com/hengyunabc/katacoda-scenarios/pull/2)，这是一个Demo，您看看这符不符合您的意思？

教程地址：https://www.katacoda.com/hollowman/courses/arthas-command-cn

English Version is still under construction.

如果您认为我这样可以的话我后面再把英文的按这样做了。

后面长期计划将[用户文档命令列表](https://alibaba.github.io/arthas/commands.html)里的命令进一步加入教程。

**Comment by arteevraina** [comment]
@hengyunabc Are these [commands](https://alibaba.github.io/arthas/en/commands.html) for which we need to create separate scenarios for? or Am I getting it wrong?

**Comment by HollowMan6** [comment]
> @hengyunabc Are these [commands](https://alibaba.github.io/arthas/en/commands.html) for which we need to create separate scenarios for? or Am I getting it wrong?

Well, I guess we have to create separate scenarios for each command, otherwise users can hardly find the specified command since you can't see what's included in the scenarios. And the requirements:

>So consider.
>Provide a separate tutorial for each command, such as a separate tutorial for the watch command, so that many tips can be written in.
>
>One tutorial per case to make it easier for users to learn to use Arthas.

**Comment by arteevraina** [comment]
@HollowMan6 It does makes complete sense. Thanks a bunch!

**Comment by arteevraina** [comment]
Yes! since the users require to find the specific command so it will better to create separate tutorials for each commands rather than creating a single tutorial and put all the commands in that which will make the :
- Tutorial longer.
- Difficult to trace the step for a specified command.

Your views @hengyunabc ?

**Comment by hengyunabc** [comment]
> Yes! since the users require to find the specific command so it will better to create separate tutorials for each commands rather than creating a single tutorial and put all the commands in that which will make the :
> 
> * Tutorial longer.
> * Difficult to trace the step for a specified command.
> 
> Your views @hengyunabc ?

Yes.

**Comment by arteevraina** [comment]
@hengyunabc Should I start contribution by adding small and separate tutorials for the `commands`?

**Comment by hengyunabc** [comment]
> @hengyunabc Should I start contribution by adding small and separate tutorials for the `commands`?

Yes, you can send small PR to https://github.com/hengyunabc/katacoda-scenarios .

**Comment by HollowMan6** [comment]
> 需要做的事情：
> 
> * 考虑能否把教程git仓库放在arthas本身，目前是在 https://github.com/hengyunabc/katacoda-scenarios

@hengyunabc 您好，在阅读了Katacoda的官方文档后，我完成了这个任务。详情请见[pull request](https://github.com/alibaba/arthas/pull/1229)

在你们合并后，使用拥有arthas仓库管理权限的账号对arthas仓库增加webhook即可。（配置教程：https://www.katacoda.community/author-profile.html#configuring-git-webhook-manually）

**Comment by HollowMan6** [comment]
@hengyunabc 

您好，目前我已经大致编写整理出了高级教程中英文案例，基础命令和ognl的用法。参见我的[PR](https://github.com/hengyunabc/katacoda-scenarios/pull/5)。

我现在是将所有案例单独放一个Scenario中，并给出了列表，便于用户遇到问题时查看。基础命令(见开发记录)由于用法较为简单，所以我将其单独放一个Scenario，便于刚入门用户查看。其它命令单独每个做成一个Scenario，每个Scenario中放置该命令详细用法和有关案例（如果可用）。

如果您觉得我这个设计布局合理，那我将开始写我的SoC2020申请书Proposal，以便于进一步讨论规划。

另外，案例在SoC2020工作期间我还可以继续编写补充。

**这是开发中的在线教程实时预览链接：**

[中文版](https://www.katacoda.com/hollowman/courses/arthas-cn)

[English Version](https://www.katacoda.com/hollowman/courses/arthas-en)

谢谢！

**Comment by hengyunabc** [comment]
Thanks to @HollowMan6 , the tutorials have been merged to master: https://github.com/alibaba/arthas/tree/master/tutorials/katacoda .

**Comment by HollowMan6** [comment]
@hengyunabc 您好，我提交了一个[PR](https://github.com/alibaba/arthas/pull/1235)，在解决了我在这个PR中所描述的问题后，就可以将这个仓库：https://github.com/hengyunabc/katacoda-scenarios 删除了。

**Comment by HollowMan6** [comment]
@hengyunabc 
您好，我已经将[原PR](https://github.com/hengyunabc/katacoda-scenarios/pull/5)进行了迁移：[PR](https://github.com/alibaba/arthas/pull/1239)。为方便您的review, 此PR我将直接复制原有教程的部分和自己改动的部分分开提交了commit，您只需要查看我commit消息中以finish开头的commit即可对我进行review。

另外我还对现有的web页面进行了改动，我增加了嵌套菜单，只有点击对应course后才会展开每个scenario，避免用户眼花缭乱。详情见[PR](https://github.com/alibaba/arthas/pull/1241).

我已经着手开始写我的SoC2020申请书Proposal，过些时间我会发送到您的邮箱（您Github资料显示的那个地址）。

谢谢！

**Comment by arteevraina** [comment]
@hengyunabc I think for the web part of this issue I would like to add mockups for it and then start working on them. Your views @hengyunabc ?

**Comment by HollowMan6** [comment]
> I think for the web part of this issue I would like to add mockups for it and then start working on them. Your views @hengyunabc ?

Well, ino, I don't think we have to do the design part, as there already exists a website and what you have to do is to add a few buttons linked to your tutorials to the menu.

**Comment by arteevraina** [comment]
> > I think for the web part of this issue I would like to add mockups for it and then start working on them. Your views @hengyunabc ?
> 
> Well, imo, I don't think we have to do the design part, as there already exists a website and what you have to do is to add a few buttons linked to your tutorials to the menu.

You are perfectly correct but I think mockup will help the team to understand what we are planning to implement in coding period since we would be coding most of the part in coding period. Right?

**Comment by HollowMan6** [comment]
> > > I think for the web part of this issue I would like to add mockups for it and then start working on them. Your views @hengyunabc ?
> > 
> > 
> > Well, imo, I don't think we have to do the design part, as there already exists a website and what you have to do is to add a few buttons linked to your tutorials to the menu.
> 
> You are perfectly correct but I think mockup will help the team to understand what we are planning to implement in coding period since we would be coding most of the part in coding period. Right?

Nope, I mean we only have to add buttons here:
![image](https://user-images.githubusercontent.com/43995067/83806888-15e1eb80-a6aa-11ea-8e59-dbcf7044c98e.png)

I'm not quite sure why we need mockup in this case? It's something already existed, unless you are going to build a new website.

**Comment by HollowMan6** [comment]
@hengyunabc 
您好！

我已经发出了我的Draft Proposal到您的邮箱，敬请查收。

谢谢！

**Comment by arteevraina** [comment]
@hengyunabc I have shared my draft proposal on your mail id. Looking forward to having your comments on it. Thanks! :)

**Comment by arteevraina** [comment]
@hengyunabc If I submit my proposal on Alibaba SOC official website today. Then Will I be able to edit it or will it be considered as my final submission?

**Comment by hengyunabc** [comment]
> @hengyunabc If I submit my proposal on Alibaba SOC official website today. Then Will I be able to edit it or will it be considered as my final submission?

It doesn't matter, it can be modified later.

**Comment by HollowMan6** [comment]
Do you think it's a good way to organize commands in categories like [this](https://alibaba.github.io/arthas/en/advanced-use.html) in the webpage part?

**Comment by tushar5526** [comment]
Hey @hengyunabc discovered ASOC today, are you guys still evaluating or done with evaluation can I still take part ?

**Comment by hengyunabc** [comment]
> Hey @hengyunabc discovered ASOC today, are you guys still evaluating or done with evaluation can I still take part ?

https://www.alibabacloud.com/zh/campaign/summerofcode2020

**Comment by hengyunabc** [comment]
> Do you think it's a good way to organize commands in categories like [this](https://alibaba.github.io/arthas/en/advanced-use.html) in the web page part?
> 
> I think it's better for users who want to find the links to these command-senarios. Otherwise the menu will be too long to find the exact command, users will feel confused.

At the beginning of the page, there will be a link to the command tutorial.


![image](https://user-images.githubusercontent.com/1683936/84756495-74399300-aff5-11ea-9a74-8575d326116a.png)

**Comment by HollowMan6** [comment]
> At the beginning of the page, there will be a link to the command tutorial.

Yeah, that's quite a good idea! But what I meant is related to this task #1241 :

> What we need to:
> 
> 3. Update the web packe： https://github.com/alibaba/arthas/blob/gh-pages/arthas-tutorials.html

I have made a demo according to what I want to express. Do you think it's better or not compared to the original way?

![深度截图_选择区域_20200616104507](https://user-images.githubusercontent.com/43995067/84759351-85b37880-afbe-11ea-849c-b7543b90594b.png)

**Comment by arteevraina** [comment]
@hengyunabc I submitted my proposal for this issue one week back. Will I receive any confirmation email for this? Actually I have not received any confirmation email regarding my participation.
