### ISSUE TITLE
Attach成功后没有进入Arthas命令行

### ISSUE THREAD

**Issue by c340c340** [alibaba/arthas#854]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: centos
* 目标进程的JVM版本: 1.7
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1. java -jar arthas-demo.jar
2.选择相应的进程

### 期望的结果
进入arthas命令行
What do you expected from the above steps？

### 实际运行的结果

attach成功，但是没有进入attach命令行，通过WebConsole发现仍成功attach

**Comment by hengyunabc** [comment]
贴出具体的出错信息。 查看 `~/logs/arthas/arthas.log` 里的内容。

**Comment by c340c340** [comment]
![avatar](https://ae01.alicdn.com/kf/Ha2533255a0ec4479a8ea051132c146b1v.png)
没有报错信息，就直接退出了arthas的命令行，arthas.log也没有什么报错信息

**Comment by hengyunabc** [comment]
arthas-boot 和 arthas的版本不匹配，删掉 `~/.arthas`目录下面旧的，或者下载全量的新版本的zip包
