### ISSUE TITLE
工程跟目录下的pom.xml缺少tunnel-server模块

### ISSUE THREAD

**Issue by jiangwh** [alibaba/arthas#856]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.2
* Arthas 版本: 3.1.2
* 操作系统版本: macos
* 目标进程的JVM版本: 无
* 执行`arthas-boot`的版本: tag 3.1.2 mater分支

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

在工程根目录的pom.xml建议增加 <module>tunnel-server</module>方便源代码的编译。
首次提交这类issue不知道如何使用该模版，请谅解～

**Comment by hengyunabc** [comment]
有的 https://github.com/alibaba/arthas/blob/arthas-all-3.1.2/pom.xml#L79
