### ISSUE TITLE
有没有计划提供 perf 或者 FrameGraph 类似的功能？

### ISSUE THREAD

**Issue by buptljy** [alibaba/arthas#859]
单独使用 perf 分析 java，需要使用 perf-java-map 类似的工程实现 kernel 和 java 的代码映射，能不能提供纯 java 的类似的工具，比如 FrameGraph 来看 cpu 的使用。

**Comment by hengyunabc** [comment]
FrameGraph 可以考虑增加，估计需要动态load native lib ，也可能有版本问题。

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/923
