### ISSUE TITLE
[window] maven打包的arthas相关包不能直接启动

### ISSUE THREAD

**Issue by DNGiveU** [alibaba/arthas#86]
在父级目录下打包构建(mvn clean install -Dmaven.test.skip=true)arthas出来的包放到%arthas%/bin目录后(去除了版本号, 与as.bat中的启动参数保持一致的), 启动./as.bat. 出现"没有清单列表". 是打包参数设置得有误么?

**Comment by ralf0131** [comment]
In Windows, you have to specify `./as.bat $PID`
