### ISSUE TITLE
为什么不能重新编译System呢？

### ISSUE THREAD

**Issue by Seifon** [alibaba/arthas#861]
$ mc /tmp/System.java -d /tmp
Memory compiler error, exception message: Compilation Error
line: 278 , message: incompatible types: java.lang.Enum[] cannot be converted to E[] , 
, please check $HOME/logs/arthas/arthas.log for more details. 
Affect(row-cnt:0) cost in 273 ms.

为什么不能重新编译System呢？

**Comment by hengyunabc** [comment]
mc 可能失败： https://alibaba.github.io/arthas/mc.html
