### ISSUE TITLE
spring boot项目，可以动态修改application.yml吗

### ISSUE THREAD

**Issue by Seifon** [alibaba/arthas#863]
如题，有的时候不想重启服务更新配置。请问，这个可以实现吗？

**Comment by hengyunabc** [comment]
不能。热更新配置，要Spirng自己识别，并重新加载，并不只是修改文件就可以的。

spring cloud 有一套 Refresh机制，可以搜索下相关的。

**Comment by wisdom-web** [comment]
搞个配置中心是最好的解决方法了，spring config  apollo 等等
