### ISSUE TITLE
在阿里云上运行arthas-demo，无法重现官方在线教程操作的效果

### ISSUE THREAD

**Issue by dengkang** [alibaba/arthas#864]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.3
* 操作系统版本: 
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core

* 目标进程的JVM版本: 
java version "1.8.0_161"
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
* 执行`arthas-boot`的版本: 3.1.3

### 重现问题的步骤

1.在阿里云上 
wget https://alibaba.github.io/arthas/arthas-boot.jar
wget https://alibaba.github.io/arthas/arthas-demo.jar
2. 启动
jar -jar arthas-demo.jar 
jar -jar arthas-boot.jar
3. 使用arthas命令
thread
sc -d *MathGame

### 期望的结果
在阿里云按照在线教程中的步骤操作，结果和在线教程中的效果一致。

### 实际运行的结果
官方在线教程 thread命令效果
 
![1](https://user-images.githubusercontent.com/6889856/65295837-335f3b80-db95-11e9-9ee2-50c58990a98c.png)

阿里云上运行 thread命令效果
![2](https://user-images.githubusercontent.com/6889856/65295846-3eb26700-db95-11e9-9b56-fffe772bd830.png)
thread 中没有 name 和 group 为main 的线程

![3](https://user-images.githubusercontent.com/6889856/65296228-5f2ef100-db96-11e9-84da-33d31a4bc9f6.png)

并且使用sc -d *MathGame 显示如上图，无法找到main函数的入口线程，jvm里也无法找到加载的demo.MathGame

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
可能 attach错进程了，或者之前 attach了其它的进程，然后再次连上去，连的是旧的进程。

**Comment by dengkang** [comment]
> 可能 attach错进程了，或者之前 attach了其它的进程，然后再次连上去，连的是旧的进程。

你是说在arthas-boot.jar 启动时选择进程错了吗，你可以看到我上传的第三张图片，arthas启动后的进程选项有三个端口和描述都很清楚，而且attach的过程细节也很清楚，所以并不是attach错进程

**Comment by hengyunabc** [comment]
检查是不是使用的jdk，而是jre。  https://github.com/alibaba/arthas/issues/820
