### ISSUE TITLE
reset 指令无效

### ISSUE THREAD

**Issue by Seifon** [alibaba/arthas#866]
通过redefine增强了一个类，然后用reset指令去还原，结果无效。

执行reset后，还是增强过的内容

另外，通过stop和shutdown指令，也不能还原增强的类

**Comment by Seifon** [comment]
```
[arthas@28374]$ redefine /tmp/RepaymentController_MoGui.class 
redefine success, size: 1
[arthas@28374]$ reset 
Affect(class-cnt:0 , method-cnt:0) cost in 1 ms.
```

**Comment by hengyunabc** [comment]
`reset`命令对`redefine`的类无效。如果想重置，需要`redefine`原始的字节码。

**Comment by Seifon** [comment]
> `reset`命令对`redefine`的类无效。如果想重置，需要`redefine`原始的字节码。

好的，谢谢了！看来是我产生了误解。另外，可以在文档里面，详细说明一下具体能对那些增强进行还原吗？
