### ISSUE TITLE
tt 命令 录制后导出记录

### ISSUE THREAD

**Issue by Seifon** [alibaba/arthas#867]
tt命令很好用，希望能够增加 录制后导出记录的功能。

有的情况，需要从生产录制现场，然后放在测试环境去重放问题。

**Comment by hengyunabc** [comment]
目前没有这样子的功能，需要很多外围的工作。

**Comment by Seifon** [comment]
> 目前没有这样子的功能，需要很多外围的工作。

希望能够纳入你们的开发计划，这个功能还是挺有必要的
