### ISSUE TITLE
无法使用tunnel-server连接到arthas的agent，因为arthas-agent在attach后无法打印agent-id

### ISSUE THREAD

**Issue by hp0632** [alibaba/arthas#868]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：as.sh 3.1.3版本
* Arthas 版本: 3.1.3
* 操作系统版本: mac
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: 3.1.3

### 重现问题的步骤

以下使用arthas的tunnel-server来远程连接arthas-agent。

根据文档中步骤
1. 首先启动arthas-tunnel-server，版本为3.1.3的jar包，启动成功
![image](https://user-images.githubusercontent.com/6867869/65408919-15a20880-de19-11e9-9d70-d2694308d8d3.png)

2. 然后进行arthas-agent的attach操作，利用了arthas-demo或者本地的一个demo（主要做一个循环打印）
![image](https://user-images.githubusercontent.com/6867869/65408991-3a967b80-de19-11e9-9fd9-023007f116eb.png)
运行成功，但是没有打印agent-id

3. 尝试使用session，也是没有agent-id打印
![image](https://user-images.githubusercontent.com/6867869/65409049-54d05980-de19-11e9-8112-f8f278148f1e.png)

### 期望的结果

期望的结果是有agent-id

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
查看 `~/logs/arthas/arthas.log` 。检查网络是不是通的。

**Comment by hp0632** [comment]
刚看了一下，确实是timeout，但有一个问题，他一直重连，关不掉，关掉arthas和tunnel-server都不能阻止重连，打开tunnel-server后还会打印重连原地址

**Comment by hp0632** [comment]
问题解决了，由于target的进程一直运行，而造成ws的进程无法进行关闭，一直重试连接tunnel-server，但是这个给人感觉是很奇怪的，因为链接命令进程都已经退出，为什么还要链接，不过已经解决。

**Comment by hengyunabc** [comment]
因为 agent是跑在 target进程里的，连接远程的 tunnel server的代码也是跑在 target进程里的。 一直重连是考虑网络可能稳定，断连之后要不断重连，不然在 tunnel server的 web console上连不到 agent上。
