### ISSUE TITLE
watch 怎么查看重载的方法的

### ISSUE THREAD

**Issue by YuanSim** [alibaba/arthas#878]
"{params,returnObj}" 怎么区分方法名称一样，不同参数的呢

**Comment by hengyunabc** [comment]
https://github.com/alibaba/arthas/issues/434

**Comment by YuanSim** [comment]
嗯 嗯。后来我找到以前有了




| |
陶龙都
|
|
邮箱：17730088312@163.com
|

签名由 网易邮箱大师 定制

在2019年09月26日 15:04，hengyunabc 写道：

Closed #878.
