### ISSUE TITLE
关于一些特殊情况的类不能排查

### ISSUE THREAD

**Issue by chenghm123** [alibaba/arthas#879]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.1
* Arthas 版本: 3.1.1
* 操作系统版本: Centos 7
* 目标进程的JVM版本: 7/8
* 执行`arthas-boot`的版本: 3.1.1

### 重现问题的步骤

1.  bootstrap classloader下面的类，tt -t等命令都无效，不能增强
2.  方法体过长的类不能增强

### 实际运行的结果
提示方法不存在 但是sc sm命令可以搜索到

**Comment by hengyunabc** [comment]
提示的信息很清楚了。 1/2/3/4。

要trace jdk里的类，打开 unsafe开关。 `options -h`。

**Comment by chenghm123** [comment]
谢谢、那么方法体过长的呢？

**Comment by hengyunabc** [comment]
> 谢谢、那么方法体过长的呢？

jvm本身限制，无解。试下 redefine
