### ISSUE TITLE
同一台物理机多docker jvm容器., arthas 最多只能监听一个. 

### ISSUE THREAD

**Issue by zhmeng** [alibaba/arthas#886]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：dockerhub hengyunabc/arthas 3.1.3
* Arthas 版本: dockerhub hengyunabc/arthas 3.1.3
* 操作系统版本: xxx
* 目标进程的JVM版本: openjdk 11.0.3
* 执行`arthas-boot`的版本: arthas 3.1.3

### 重现问题的步骤

1. docker-compose 启动几个 jvm容器，容器内有arthas
2. jvm容器内部的java进程号为 1
3. arthas attach到其中任何一台后，其他的容器运行arthas都报错，不能够启动监听的 3658.

### 期望的结果

每个容器内的arthas都可以attach到每个容器内pid为1的java进程.

### 实际运行的结果
第一个容器内的arthas 可以监听成功，其他的容器内的都失败. 

```
Attach porcess 1 success.
arthas-client connect  to 127.0.0.1:3658
Connect to telnet server error: 127.0.0.1 3658
java.net.ConnectException:  Connection Refused(..)

```

**Comment by zhmeng** [comment]
docker-compose 中的每个jvm容器都有自己的独立ip, 不明白为什么一个容器启动了arthas 会影响其他的容器内arthas的启动呢？ 望大神们不吝赐教.  @hengyunabc

**Comment by jiangwh** [comment]
1、检查下docker容器启动的网络，host模式应该是有问题，因为这种模式下是直接使用物理机器端口资源。

**Comment by zhmeng** [comment]
用的是bridge 的网络. @jiangwh

**Comment by zhmeng** [comment]
因为我的是内网环境，文件拷贝不出来。我简要写下docker-compose 内容

verision:"3"
services:
   personnelService:
      image: ..
      env_file:
      environment:
          --
      volumnes:
         --
      ports:
          --
其他没有设置什么特别的内容
用 docker network ls 命令 可以看到
networkId   NAME               DRIVER   SCOPE
43dd8..       smartloans..       bridge     local
用的是上面的网络

**Comment by zhmeng** [comment]
容器内部执行 ip a 命令
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKOWN group default qlen 1000
   link/looplock 00:00:00:00:00:00 brd 00:00:00:00:00
   inet 127.0.0.1/8 scope host lo
      valid_lft forever preferred_lft forever
```

**Comment by jiangwh** [comment]
> 容器内部执行 ip a 命令
> 
> ```
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKOWN group default qlen 1000
>    link/looplock 00:00:00:00:00:00 brd 00:00:00:00:00
>    inet 127.0.0.1/8 scope host lo
>       valid_lft forever preferred_lft forever
> ```

你这个容器少一个网络，这只是lo还有一个对外通信的。

**Comment by zhmeng** [comment]
@jiangwh  我更新了， 是我之将 lo 写，没有 eth0 ， eth0 都是有的。

**Comment by hengyunabc** [comment]
不是很清楚这个网络是怎样的。不过这个问题感觉和arthas本身没关系。 arthas attach成功之后，在目标进程里启动一个tcp server。

换另一种办法解决就是设置不同的 listen port， `./as.sh -h` 查看。

**Comment by zhmeng** [comment]
我也是认为不会有什么问题是 bridge 网络， 进程都隔离了.  每个容器也有自己的独立ip .
因为是内网机器，没有装 telnet . 所以 as.sh 会报  telnet 的错误，直接用 java -jar arthas-boot.jar 启动的. 
Dockerfile 的写法是
ENTRYPOINT exec java  -jar ...
容器内的 java 进程是最为 PID 为 1 启动的. 
在容器内启动 arthas-demo 没有问题， 估计是不是所有的  pid 都是 1 导致的？
tcpserver 在第一个容器内是可以正常启动的,  其他的容器 attach 后，就不会有启动相应的进程了.

**Comment by hengyunabc** [comment]
你可以自己写个简单的 java tcp server，listen同一个port，然后启动看会不会报错。 如果没有报错，可能是你执行 arthas时搞错了环境，并不是在容器内。

**Comment by zhmeng** [comment]
好的，我试试。

**Comment by zhmeng** [comment]
试了下， 不是端口冲突的问题。 用python写了个tcp server, 两个容器内都可以同时监听相同的端口.

**Comment by zhmeng** [comment]
我再试试是不是两个容器内相同的PID影响的， 大概率我认为是相同的PID影响的。

**Comment by hengyunabc** [comment]
https://alibaba.github.io/arthas/docker.html

**Comment by jiangwh** [comment]
pid应该不会影响，我们正常在k8s下面使用，一台server有多个docker很正常，一直没有出问题。

**Comment by zhmeng** [comment]
docker 容器内 java 进程的 PID 是 1 吗？ 测试发现由于PID是1导致出现问题的概率比较大.

**Comment by zhmeng** [comment]
不知道为啥，所有的容器内执行 jcmd 出现的都是第一台容器的jar包的名字. . 问题应该出现在这里.

**Comment by zhmeng** [comment]
谢谢 @hengyunabc @jiangwh

**Comment by zhmeng** [comment]
问题的原因排查结果是： docker容器的 /tmp 目录和宿主机的/tmp映射导致的.
