### ISSUE TITLE
java.io.IOException: 拒绝访问 when attaching to tomcat7

### ISSUE THREAD

**Issue by jiandanfeng** [alibaba/arthas#887]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* Arthas 版本: 3.1.4
* 操作系统版本: windows10
* 目标进程的JVM版本: jdk1.7.0_79

按照官方文档attach到demo是没问题的，但当我要attach到tomcat7的web项目就会报以下异常：
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 15180 org.apache.catalina.startup.Bootstrap
  [2]: 2668
1
[INFO] arthas home: C:\Users\chenjh3\Downloads\arthas-packaging-3.1.4-bin
[INFO] Try to attach process 15180
[INFO] Found java home from System Env JAVA_HOME: D:\develop\Java\jdk1.7.0_79
[ERROR] Start arthas failed, exception stack trace:
java.io.IOException: 拒绝访问。
        at sun.tools.attach.WindowsVirtualMachine.openProcess(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:56)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachProvider.java:193)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:255)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:85)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:123)
[ERROR] attach fail, targetPid: 15180

**Comment by hengyunabc** [comment]
查看 ~/logs/arhtas/arthas.log 里的内容。另外，如果是windows service attach不了，issue里搜索下。

**Comment by jiandanfeng** [comment]
> 查看 ~/logs/arhtas/arthas.log 里的内容。另外，如果是windows service attach不了，issue里搜索下。

你好，在arthas.log里面没有日志，还有我的tomcat7是在eclipse启动的，和这个有关吗？

**Comment by jiandanfeng** [comment]
我发现我在eclipse中通过run as java application，启动MathGame(那个官方demo），然后再去attach，也是报同样的错误。

**Comment by hengyunabc** [comment]
> 我发现我在eclipse中通过run as java application，启动MathGame(那个官方demo），然后再去attach，也是报同样的错误。

可能eclipse用的jdk和命令行的不一样，也可能eclipse用的是jre。

**Comment by jiandanfeng** [comment]
用的都是同样的jdk
![image](https://user-images.githubusercontent.com/24525960/66542506-54e48f00-eb65-11e9-977a-b983990970fa.png)
![image](https://user-images.githubusercontent.com/24525960/66542535-6f1e6d00-eb65-11e9-87b4-14b2d1aa98bd.png)



> > 我发现我在eclipse中通过run as java application，启动MathGame(那个官方demo），然后再去attach，也是报同样的错误。
> 
> 可能eclipse用的jdk和命令行的不一样，也可能eclipse用的是jre。

**Comment by hengyunabc** [comment]
试下 jstack 看能不能工作。 另外，下个jdk8看可以工作不。

**Comment by jiandanfeng** [comment]
找到问题所在了，按照error信息提示：[ERROR] Start arthas failed, exception stack trace:
java.io.IOException: 拒绝访问。是因为权限不全造成了，在任务管理器中发现eclipse.exe和eclipse启动的javaw.exe（uac虚拟化是灰的，得知这个跟权限有关），是本身该eclipse有问题造成的，重启电脑也解决不了，后来又重启打开了一个新的eclipse（同版本免安装版），然后再打开这个eclipse，在任务管理器中查看，发现默认uac虚拟化勾上了，后面再启动demo，用arthas-boot去attach，就正常；目前无法重现不能attach的问题。

**Comment by jiandanfeng** [comment]
当uac虚拟化是灰的，用管理员权限运行eclipse也是不起作用。
