### ISSUE TITLE
无法attach idea里启动的main程序

### ISSUE THREAD

**Issue by luliloveshe** [alibaba/arthas#888]
我在idea里面启动一个main方法的程序 在任务管理器里 也能看到相应进程 
使用命令 
D:\tools\arthas-packaging-3.1.1-bin>"D:\Program Files\Java\jdk1.8.0_51\bin\java"
 -jar arthas-boot.jar 1281444

却报错 
[INFO] arthas-boot version: 3.1.1
[INFO] arthas home: D:\tools\arthas-packaging-3.1.1-bin
[INFO] Try to attach process 1281444
java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Pr
ovider sun.tools.attach.WindowsAttachProvider could not be instantiated
[ERROR] Start arthas failed, exception stack trace:
com.sun.tools.attach.AttachNotSupportedException: no providers installed
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:203)
        at com.taobao.arthas.core.Arthas.attachAgent(Arthas.java:73)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:28)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:113)
[ERROR] attach fail, targetPid: 1281444

**Comment by hengyunabc** [comment]
试下在cmd下启动 arthas-demo.jar，再用 arthas-boot来attach。 

如果可以的话，可能就是idea和命令行的里的 jdk版本不一样，或者用的是jre之类的。

另外，最好用最新的版本。

**Comment by hengyunabc** [comment]
参考这个： https://github.com/alibaba/arthas/issues/887
