### ISSUE TITLE
trace计算的时间有不准的情况

### ISSUE THREAD

**Issue by terranhu** [alibaba/arthas#891]
下面的日志显示方法耗时310毫秒，但所有内部运行的方法的加起来肯定是各位数

`---ts=2019-10-10 19:08:19;thread_name=http-nio-9999-exec-555;id=330;is_daemon=true;priority=5;TCCL=org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader@2f238c1c
    `---[310.642333ms] com.yjh.mushroom.utils.spring.BeanUtils:copyPropertiesInternal()
        +---[0.001141ms] org.springframework.util.Assert:notNull() #318
        +---[8.55E-4ms] org.springframework.util.Assert:notNull() #319
        +---[0.00114ms] java.lang.Object:getClass() #321
        +---[0.00114ms] com.yjh.mushroom.utils.spring.BeanUtils:getPropertyDescriptors() #323
        +---[8.55E-4ms] java.util.Arrays:asList() #324
        +---[min=5.7E-4ms,max=8.56E-4ms,total=0.003991ms,count=5] java.beans.PropertyDescriptor:getWriteMethod() #327
        +---[min=8.55E-4ms,max=8.56E-4ms,total=0.003421ms,count=4] java.beans.PropertyDescriptor:getName() #328
        +---[min=8.55E-4ms,max=0.00114ms,total=0.003705ms,count=4] java.util.List:contains() #328
        +---[min=5.7E-4ms,max=8.56E-4ms,total=0.003136ms,count=4] java.lang.Object:getClass() #329
        +---[min=5.7E-4ms,max=8.56E-4ms,total=0.003136ms,count=4] java.beans.PropertyDescriptor:getName() #329
        +---[min=0.001141ms,max=0.001426ms,total=0.005419ms,count=4] com.yjh.mushroom.utils.spring.BeanUtils:getPropertyDescriptor() #329
        +---[min=8.55E-4ms,max=8.56E-4ms,total=0.003421ms,count=4] java.beans.PropertyDescriptor:getReadMethod() #331
        +---[min=0.00114ms,max=0.001141ms,total=0.004561ms,count=4] java.lang.reflect.Method:getParameterTypes() #332
        +---[min=5.71E-4ms,max=8.55E-4ms,total=0.003136ms,count=4] java.lang.reflect.Method:getReturnType() #333
        +---[min=8.56E-4ms,max=0.001425ms,total=0.004562ms,count=4] org.springframework.util.ClassUtils:isAssignable() #332
        +---[min=8.55E-4ms,max=8.56E-4ms,total=0.001711ms,count=2] java.lang.reflect.Method:getDeclaringClass() #335
        +---[min=8.56E-4ms,max=0.001141ms,total=0.001997ms,count=2] java.lang.Class:getModifiers() #335
        +---[min=8.56E-4ms,max=0.001141ms,total=0.001997ms,count=2] java.lang.reflect.Modifier:isPublic() #335
        +---[min=8.56E-4ms,max=0.001141ms,total=0.001997ms,count=2] java.lang.reflect.Method:invoke() #338
        +---[min=5.71E-4ms,max=5.71E-4ms,total=0.001142ms,count=2] java.lang.reflect.Method:getDeclaringClass() #339
        +---[min=8.55E-4ms,max=8.56E-4ms,total=0.001711ms,count=2] java.lang.Class:getModifiers() #339
        +---[min=8.55E-4ms,max=8.55E-4ms,total=0.00171ms,count=2] java.lang.reflect.Modifier:isPublic() #339
        `---[min=8.55E-4ms,max=0.001141ms,total=0.001996ms,count=2] java.lang.reflect.Method:invoke() #342

**Comment by hengyunabc** [comment]
trace本身也有消耗，并且函数里面还有一些代码不是函数调用。

**Comment by tianyaroad** [comment]
`---ts=2021-05-16 11:07:09;thread_name=DubboServerHandler-10.38.46.176:20880-thread-1399;id=61d;is_daemon=true;priority=5;TCCL=org.springframework.boot.loader.LaunchedURLClassLoader@4520ebad
    `---[2054.789403ms] dubbo代理()
        `---[2054.757843ms] org.springframework.cglib.proxy.MethodInterceptor:intercept() #57
            `---[0.053435ms] 自己方法()
                +---[0.003453ms] java.util.Objects:nonNull() #79
                +---[0.004464ms] com.google.common.cache.LoadingCache:get() #80
                +---[0.004463ms] 缓存方法 #81
                +---[0.002887ms] java.util.Objects:nonNull() #82
                +---[0.00342ms] org.apache.commons.collections4.MapUtils:isNotEmpty() #57
                +---[0.003203ms] java.util.Map:containsKey() #83
                `---[0.003266ms] java.util.Map:get() #84

**Comment by hengyunabc** [comment]
@tianyaroad 参考： https://arthas.aliyun.com/doc/trace#id10
