### ISSUE TITLE
arthas dashboard max_metaspace and max_nonheap return -1

### ISSUE THREAD

**Issue by slievrly** [alibaba/arthas#892]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.4
* Arthas 版本: 3.1.4
* 操作系统版本: Mac OS X 10.14.2
* 目标进程的JVM版本: 1.8.0_181
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

![image](https://user-images.githubusercontent.com/8758457/66620608-aba8a200-ec13-11e9-9939-82dec304ff35.png)
把异常信息贴到这里
![image](https://user-images.githubusercontent.com/8758457/66620650-cc70f780-ec13-11e9-86d5-86b9aee45c74.png)

**Comment by hengyunabc** [comment]
参考源码： https://github.com/alibaba/arthas/blob/arthas-all-3.1.4/core/src/main/java/com/taobao/arthas/core/command/monitor200/DashboardCommand.java 

图里的异常是稳定在dashboard命令里出现的？感觉关系不大。
