### ISSUE TITLE
多次使用redefine命令报错

### ISSUE THREAD

**Issue by wanchengqu** [alibaba/arthas#893]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx

### 重现问题的步骤

1.[arthas@12843]$ redefine /tmp/ApiPreFilter.class
redefine success, size: 1
2.[arthas@12843]$ redefine /tmp/ApiPreFilter.class
Error during processing the command: null

### 期望的结果
第一次使用redefine命令后显示成功，调试后发现修改没生效，重新修改后上传class文件，再次使用redefine报错，报错信息Error during processing the command: null

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
[arthas@12843]$ redefine /tmp/ApiPreFilter.class
Error during processing the command: null

**Comment by hengyunabc** [comment]
查看 `~/logs/arthas/arthas.log`

**Comment by zengxiaoliang** [comment]
我也遇到同样的问题，日志信息如下：


2020-05-27 18:59:49 [as-command-execute-daemon] ERROR c.t.a.c.s.system.impl.ProcessImpl -Error during processing the command:
java.lang.NullPointerException: null
        at com.taobao.arthas.core.command.klass100.RedefineCommand.process(RedefineCommand.java:117)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111)
        at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108)
        at com.taobao.arthas.core.shell.system.impl.ProcessImpl$CommandProcessTask.run(ProcessImpl.java:371)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by hengyunabc** [comment]
@zengxiaoliang 具体什么类，jdk版本，os版本，Artahs版本等信息

**Comment by zengxiaoliang** [comment]
> @zengxiaoliang 具体什么类，jdk版本，os版本，Artahs版本等信息

OS:
 OS                                                                  Linux
 ARCH                                                                amd64
 PROCESSORS-COUNT                                                    4
 LOAD-AVERAGE                                                        0.0
 VERSION                                                             3.10.0-957.5.1.el7.x86_64


arthas:


wiki      https://alibaba.github.io/arthas
tutorials https://alibaba.github.io/arthas/arthas-tutorials
version   3.2.0
pid       29568
time      2020-05-27 15:58:25




JDK

 MANAGEMENT-SPEC-VERSION                                             1.2
 SPEC-NAME                                                           Java Virtual Machine Specification
 SPEC-VENDOR                                                         Oracle Corporation
 SPEC-VERSION                                                        1.8
 VM-NAME                                                             Java HotSpot(TM) 64-Bit Server VM
 VM-VENDOR                                                           Oracle Corporation
 VM-VERSION                                                          25.60-b23

**Comment by hengyunabc** [comment]
@zengxiaoliang 具体执行了什么 命令，如果没有传 hashcode的话，不会抛异常。

java.util.HashMap 的classloader是 null，不会有 hashcode。 

你是不是传了 systemclassloader的 hashcode

**Comment by hengyunabc** [comment]
我测试没有问题： 

```
[arthas@22435]$ dump java.util.HashMap
 HASHCODE  CLASSLOADER  LOCATION
 null                   /Users/hengyunabc/logs/arthas/classdump/java/io/ExpiringCache$1.class
 null                   /Users/hengyunabc/logs/arthas/classdump/java/util/LinkedHashMap.class
 null                   /Users/hengyunabc/logs/arthas/classdump/java/util/HashMap.class
Affect(row-cnt:3) cost in 33 ms.
[arthas@22435]$ redefine /Users/hengyunabc/logs/arthas/classdump/java/util/HashMap.class
redefine success, size: 1
```

如果传了一个错误的 hashcode，就会出错：

```
[arthas@22572]$ redefine -c 18b4aac2 /Users/hengyunabc/logs/arthas/classdump/java/util/HashMap.class
Error during processing the command, exception type: java.lang.NullPointerException, message:null, please check $HOME/logs/arthas/arthas.log for more details.
```

**Comment by zengxiaoliang** [comment]
> @zengxiaoliang 具体执行了什么 命令，如果没有传 hashcode的话，不会抛异常。
> 
> java.util.HashMap 的classloader是 null，不会有 hashcode。
> 
> 你是不是传了 systemclassloader的 hashcode



感谢耐心指导， 不用-c 指定classloader 正常；应该是 classLoaderHashCode 不正确导致。
