### ISSUE TITLE
monitor  缺少字段

### ISSUE THREAD

**Issue by tonfay** [alibaba/arthas#896]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.4
* Arthas 版本: 3.1.4
* 操作系统版本: linux
* 目标进程的JVM版本: 1.8.14
* 执行`arthas-boot`的版本: 3.1.4

### 重现问题的步骤

1. monitor -c 5 a.b.c.Aaa test

### 期望的结果

timestamp            class          method        total  success  fail  avg-rt(ms)  fail-rate

### 实际运行的结果

timestamp            class          method 

```
为什么没有其它的字段呢?
```

**Comment by nanawe** [comment]
我这也偶尔这样，monitor重定向到文件缺少total success fail avg-rt(ms) fail-rate指标，只有timestamp class method

**Comment by hengyunabc** [comment]
@nanawe 窗口太小，类名，函数名太长，导致输出不全，可以把窗口拉大再重连。

**Comment by Ax1an** [comment]
@hengyunabc 你好，这个问题有计划解决吗？感觉体验不是很友好。

**Comment by hengyunabc** [comment]
@Ax1an 这个应该已经修复了，用最新的版本。

**Comment by Ax1an** [comment]
@hengyunabc 收到。感谢回复！
