### ISSUE TITLE
Debug Arthas Exception:The options [pid, core, agent] are required

### ISSUE THREAD

**Issue by ghost** [alibaba/arthas#904]
Debug Arthas Exception:The options [pid, core, agent] are required:
![image](https://user-images.githubusercontent.com/22359905/67579773-b74daa00-f777-11e9-9e92-7a4ef5671f3c.png)

I want to debug the arthas agent source code and followed the first part of this #222

can someone provider any advices?
thx:D

**Comment by felayman** [comment]
the way like this way(https://github.com/Hearen/arthas/issues/20) is ok.

I try it and succeed.

![image](https://user-images.githubusercontent.com/7543851/67660142-fdce1f00-f998-11e9-8840-2034bc8a6011.png)
