### ISSUE TITLE
如果使用trace命令监测各个方法节点耗时的多次平均值呢，

### ISSUE THREAD

**Issue by zhangtaochn** [alibaba/arthas#913]
在我们的项目当中，需要监测指定方法的耗时情况，但trace命令似乎只能实时更新每次调用的耗时，能不能监测调用某个方法的多次统计平均耗时情况呢，

**Comment by wupflove** [comment]
把监控记录保存下来，可以自己在外部分析

**Comment by useraddZYB** [comment]
https://github.com/useraddZYB/time-tracker

**Comment by useraddZYB** [comment]
> 在我们的项目当中，需要监测指定方法的耗时情况，但trace命令似乎只能实时更新每次调用的耗时，能不能监测调用某个方法的多次统计平均耗时情况呢，

https://github.com/useraddZYB/time-tracker
可以看平均 p50 p99
