### ISSUE TITLE
测试火焰图 和 http/telent 共用3658端口

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#925]
测试版本：

[arthas-3.1.5-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/3828761/arthas-3.1.5-SNAPSHOT-bin.zip)

### 火焰图

`profiler`命令。

`profiler start` 启动profiler，然后等一段时间，执行`profiler getSamples`，可以得到采样的数量，再执行`profiler stop`，可以看到输出结果：

```
[arthas@9422]$ profiler start
Started [cpu] profiling
[arthas@9422]$ profiler getSamples
9
[arthas@9422]$ profiler stop
profiler output file: /Users/hengyunabc/code/ali/est/arthas-output/20191111-014114.svg
OK
```

然后在浏览器里访问： http://localhost:3658/arthas-output/ ，可以看到profiler输出的结果：

![image](https://user-images.githubusercontent.com/1683936/68548144-aada7a00-0424-11ea-945c-c9034e0d1d04.png)

访问具体的结果，可以看到：

![image](https://user-images.githubusercontent.com/1683936/68548158-c6de1b80-0424-11ea-9789-7d0050b00b0a.png)

---

也可以输出为html结果：

```
profiler start
profiler stop --format html
```

默认情况下，输出到应用的`arthas-output`目录下。这个目录可以直接在浏览器里看到。也可以通过 `--file`参数指定输出文件。如果不指定format，那么自动按文件的后缀区分。

#### 对不同的event采样

proifler支持多种event，可以用 `profiler list` 命令列出来，比如在mac上：

```
[arthas@12281]$ profiler list
Basic events:
  cpu
  alloc
  lock
  wall
  itimer
```

在linux上，支持更多的event，比如：

```
[arthas@13519]$ profiler list
Basic events:
  cpu
  alloc
  lock
  wall
  itimer
Perf events:
  page-faults
  context-switches
  cycles
  instructions
  cache-references
  cache-misses
  branches
  branch-misses
  bus-cycles
  L1-dcache-load-misses
  LLC-load-misses
  dTLB-load-misses
  mem:breakpoint
  trace:tracepoint
```

可以通过 `profiler start --event page-faults` 这样的方式指定要采样的event。

**Comment by hengyunabc** [comment]
### http/telnet共用 3658端口

后续考虑统一使用一个端口3658同时支持 http/telnet，避免配置端口的麻烦。

在attach成功之后，可以直接访问 http://localhost:3658/ ，另外访问 http://localhost:3658/arthas-output/ 可以查看profiler的输出结果。

目前可能会遇到这个问题，使用chrome浏览器访问时：

![image](https://user-images.githubusercontent.com/1683936/68548350-e24a2600-0426-11ea-8d06-b9971b76877d.png)


* 判断具体什么协议，采用读tcp前面3个字节的方式，如果是`GET`，则认为是http协议
* 因为telnet协议在连接上之后，不会发送数据，所以目前判断是否telnet协议的办法是等待一秒，如果没有数据，则认为是 telnet协议
* chrome在连接时，会同时建立两个TCP连接，先连接成功的，发送http请求头。另一条tcp连接不发送任何数据。所以在连接arthas 3658时，会出现一条TCP连接发送了http请求头，会被正常处理。另一条TCP连接没发送任何数据，会被认为是telnet协议，然后返回 telnet的欢迎String，所以被认为是失败的http请求，然后显示“该网页无法正常运作”。

这个是chrome的特殊机制造成的，目前没有太好的解法，只能多刷新下。

**Comment by jiangwh** [comment]
火焰图可以正常生成了。发现 profiler execute有些不正常。
```
[arthas@41072]$ profiler start
Started [cpu] profiling
[arthas@41072]$ profiler execute 
```
jvm crash，具体原因还没有排查，应该跟libasyncProfiler.so有关。

**Comment by hengyunabc** [comment]
> 火焰图可以正常生成了。发现 profiler execute有些不正常。
> 
> ```
> [arthas@41072]$ profiler start
> Started [cpu] profiling
> [arthas@41072]$ profiler execute 
> ```
> 
> jvm crash，具体原因还没有排查，应该跟libasyncProfiler.so有关。
> 
> 还是要👍

可能是jni里没有处理null，我全部检查下空指针的地方。
