### ISSUE TITLE
修改注解Redefine成功，但实际执行未生效

### ISSUE THREAD

**Issue by hechuan73** [alibaba/arthas#926]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.4
* Arthas 版本: 3.1.4
* 操作系统版本: Cent OS 7
* 目标进程的JVM版本: openjdk-8
* 执行`arthas-boot`的版本: 3.1.4

### 重现问题的步骤

Spring boot工程中，修改@GetMapping("xxx")和@Query("xxx")不生效

1. jad --source-only classfile
2. 修改/删除@GetMapping("xxx")和@Query("xxx")
3. mc -c classloaderId xxx
4. redefine xxxx

### 期望的结果

输入URL，无法匹配报404，或者注解@Query的方法报找不到SQL。

### 实际运行的结果

应用正常运行，可以访问接口和进行数据库查询。

请教下：修改这种注解信息，是可以redefine成功的，但是实际上却没有生效，感觉注解的信息是在应用初始化时，就完成了解析和映射，动态替换class字节码后，好像没有重新映射和关联。问题：
1. 是否支持修改注解，重新redefine class？
2. redefine成功，但没有生效的大致原因？

谢谢！

**Comment by hengyunabc** [comment]
。。你自己尝试写个处理annotation的代码，就知道为什么不生效了。没有人会在每次处理请求时，重新解析annotation。

另外，jvm对于增加annotation，redefine是否生效，这个不清楚，估计比较复杂。

**Comment by hechuan73** [comment]
好的，谢谢！

**Comment by 546621120** [comment]
https://alibaba.github.io/arthas/redefine.html
中提到“redefine命令和jad/watch/trace/monitor/tt等命令会冲突。执行完redefine之后，如果再执行上面提到的命令，则会把redefine的字节码重置。 原因是jdk本身redefine和Retransform是不同的机制，同时使用两种机制来更新字节码，只有最后修改的会生效。”
但其实是之前的jad/watch/trace/monitor/tt把class做了缓存，所以导致再次执行jad/watch/trace/monitor/tt时之前缓存的class会把redefine的字节码重置，而不是文档中描述的直接由jdk本身redefine和Retransform是不同的机制引起的 ？

**Comment by hengyunabc** [comment]
> https://alibaba.github.io/arthas/redefine.html
> 中提到“redefine命令和jad/watch/trace/monitor/tt等命令会冲突。执行完redefine之后，如果再执行上面提到的命令，则会把redefine的字节码重置。 原因是jdk本身redefine和Retransform是不同的机制，同时使用两种机制来更新字节码，只有最后修改的会生效。”
> 但其实是之前的jad/watch/trace/monitor/tt把class做了缓存，所以导致再次执行jad/watch/trace/monitor/tt时之前缓存的class会把redefine的字节码重置，而不是文档中描述的直接由jdk本身redefine和Retransform是不同的机制引起的 ？

有没有缓存都不影响这个结论，看jdk本身的javadoc说明。
