### ISSUE TITLE
关于arthas-server统一管理的问题

### ISSUE THREAD

**Issue by queenns** [alibaba/arthas#937]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.4
* Arthas 版本: 3.1.4

### 重现问题的步骤

1. 单机器多java应用的情况
1).A机器arthas-server已经启动完成
2).B机器arthas启动后需要选择具体某一个java进程的pid
3).attach成功后arthas-server有了B机器arthas的注册信息，WebConsole根据agent_id可以远程控制
疑问:
a.我在B机器上启动了arthas那我就可以直接操作B机器了，arthas-server有啥用途？
b.我预期的是B机器arthas启动即可以注册到arthas-server，使用WebConsole登录到B机器的arthas，然后选择B机器具体的某个java进程开始使用
c.理解有问题，还是使用的有问题
2. 在k8s中的使用
1).如果pod中启动多java应用组成一个微服务,类似问题和单机多应用的情况相似，那我直接登录终端去操作
2).系统由多pod组成，理想中的是所有pod中的arthas注册到arthas-server,然后根据Spring Boot端点注册的信息，使用WebConsole去操作
疑问:
arthas-server不是想象中的一个注册中心和管理中心，根据注册信息即可选定某个机器上的某个java进程开始操作
arthas-server的作用到底是什么呢？

**Comment by hengyunabc** [comment]
1. 管理者本身，需要有一种手段去某台指定的机器上执行一些脚本。比如检查某个配置项，比如执行脚本启动arthas。 这个手段可能是一个agent来做，也可能可能是通用的ssh通道来做，取决于公司自身的设施。
2. 有这个执行脚本能力之后，先执行一个 jps，就可以得到java进程列表。然后用 户在web界面上选择进程号，然后再执行脚本启动arthas，并指定pid 和 tunnel-server。 这样子用户在web界面上就可以连接远程的arthas了。

**Comment by queenns** [comment]
1.不管是通过什么方式来做，都需要使用者根据自身情况去做一些处理
为什么不把arthas启动直接注册到arthas-server?
统一的arthas-server管理所以注册进来的arthas
并且可以自由选择某个arthas上的java进程
类似与整个arthas服务端和客户端是整体一套
现在是主要出于什么目的考量的呢？
2.web界面是没有jps后进程号选项连接的，所以需要开发者自己扩展吗？

**Comment by hengyunabc** [comment]
> 1.不管是通过什么方式来做，都需要使用者根据自身情况去做一些处理
> 为什么不把arthas启动直接注册到arthas-server?
> 统一的arthas-server管理所以注册进来的arthas
> 并且可以自由选择某个arthas上的java进程
> 类似与整个arthas服务端和客户端是整体一套
> 现在是主要出于什么目的考量的呢？
> 2.web界面是没有jps后进程号选项连接的，所以需要开发者自己扩展吗？

1. 只要你启动arthas加了 `--tunnel-server` 参数，启动就会连到 tunnel server上。通过 tunnel server上输入 agent id就可以连接上

2. tunnel server更多的功能要自己开发，每个公司都是不一样的。你凭空一个服务器，怎么远程执行jps。没有自己公司的管控手段结合是做不到的。

3. arthas本身是一个agent，它的大部分功能代码都跑在应用进程里。这个原因非常简单，实现方便。比如我想执行一下 `sysprops`，直接调java代码就行了。难不成这个实现还能跑在别的地方。

**Comment by queenns** [comment]
1.执行步骤:启动arthas向tunnel-server注册
# java -jar arthas-boot.jar --tunnel-server 'ws://ip:7777/ws' --agent-id 111
[INFO] arthas-boot version: 3.1.4
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 17616 a.jar
  [2]: 14704 b.jar
  [3]: 12726 c.jar
  [4]: 18874 d.jar
2.此时是还没有注册到tunnel-server,选定具体进程attach成功后才能注册成功
3.我以为此时arthas可以直接注册成功并将java进程也一并注册进去
4.之后tunnel-server就可以各种操作了

多谢大佬解答，大概流程我已经清楚了
