### ISSUE TITLE
trace命令 不打印每一行代码的耗时

### ISSUE THREAD

**Issue by chenguoku** [alibaba/arthas#941]
- [√] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

使用 trace -j com.xxx.service.cart.impl.ShopCartServiceImpl listGoods 命令，只输出方法耗时，没有输出每行代码的耗时

**Comment by hengyunabc** [comment]
这命令有问题。 3.1.5 版本要用 `-j true`
