### ISSUE TITLE
关于Tunnel Server连接Agent的问题

### ISSUE THREAD

**Issue by dearboll** [alibaba/arthas#946]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：3.1.4
* Arthas 版本:  3.1.4
* 操作系统版本:  centos 6.3
* 目标进程的JVM版本: 1.8.0_171-b11
* 执行`arthas-boot`的版本: 1.8.0_171-b11

### 重现问题的步骤
（整个部署环境在Kubernetes集群中，使用了内部域名）
1. 启动tunnel server，启动成功 （其内部域名为`tunnelserver.cluster.local`）。
2. 启动目标应用程序，启动成功（其集群内的虚拟ip 为192.168.1.1）。
3. 在目标应用程序的同一个容器内，启动arthas-boot。启动命令为`java -jar arthas-boot.jar --tunnel-server 'ws://tunnelserver.cluster.local:7777/ws' --agent-id abc ${pid}`  启动成功后，进入arthas控制界面，输入 session后显示如下： 
$ session 
 Name           Value                                                                                                                  
 JAVA_PID       15                                                                                                                     
 SESSION_ID     1d676b58-797c-4689-8ce4-eec9825f283a                                                                                   
 TUNNEL_SERVER  ws://tunnelserver.cluster.local:7777/ws
4. 在tunnel server的管理页面TUNNEL_SERVER_IP:8080/actuator/arthas没有显示任何clientConnections或者agents信息
5. 点开tunnel server的web console页面输入 **IP**  192.168.1.1 **Port** 7777 **agentId** abc 点击连接，弹窗显示 Connect error

### 期望的结果

  可以在Tunnel Server的web console页面连接到指定的agent上。

### 实际运行的结果

  点开tunnel server的web console页面输入 **IP**  192.168.1.1 **Port** 7777 **agentId** abc 点击连接，弹窗显示 Connect error
  tunnel-server没有打印异常日志。

感谢~

**Comment by hengyunabc** [comment]
这个应该是网络问题，检查网络的连通性。  `actuator/arthas` 没有数据，说明没有连接成功。

**Comment by Roger3581321** [comment]
考虑endpoint监控各种资源状态包括网络。
