### ISSUE TITLE
arthas在修改字节码的时候为什么使用retransformClasses而不是redefineClasses

### ISSUE THREAD

**Issue by ieven** [alibaba/arthas#949]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

arthas在修改字节码的时候为什么使用retransformClasses而不是redefineClasses

**Comment by hengyunabc** [comment]
因为可能有别的agent会增加了 Transformer，直接redefine会不会触发 Transformer的处理。参考jdk本身的文档说明。
