### ISSUE TITLE
windows下监控字符编码问题

### ISSUE THREAD

**Issue by Eric-yangzong** [alibaba/arthas#950]
- [1] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：  3.0
* Arthas 版本: 3.1.4
* 操作系统版本: window10
* 目标进程的JVM版本: 1.8.0_211
* 执行`arthas-boot`的版本: 3.1.4

### 重现问题的步骤
1.java -jar -Dfile.encoding=GBK arthas-boot.jar。
2. ![image](https://user-images.githubusercontent.com/31579322/69615618-2b79b700-1070-11ea-99c9-276d1b0320c5.png)

### 期望的结果

得到正常的GBK编码的字符 。

### 实际运行的结果
![image](https://user-images.githubusercontent.com/31579322/69615831-87dcd680-1070-11ea-9007-40245d24772e.png)

**Comment by kylixs** [comment]
这个问题是watch 方法参数值包含中文时，显示乱码
