### ISSUE TITLE
Alibaba Arthas 3.1.5版本支持火焰图，快速定位应用热点

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/arthas#951]
![Arthas](https://alibaba.github.io/arthas/_images/arthas.png)

`Arthas`是Alibaba开源的Java诊断工具，深受开发者喜爱。

* Github： https://github.com/alibaba/arthas
* 文档：https://alibaba.github.io/arthas

Arthas 3.1.5版本带来下面全新的特性：

* 开箱即用的Profiler/火焰图功能
* grep命令支持更丰富的选项
* monitor/tt/trace等命令提供更精确的时间统计
* telnet/http协议共用3658端口

## Profiler/Frame Graph/火焰图

火焰图的威名相信大家都有所耳闻，但可能因为使用比较复杂，所以望而止步。

在新版本的Arthas里集成了[async-profiler](https://github.com/jvm-profiling-tools/async-profiler)，使用`profiler`命令就可以很方便地生成火焰图，并且可以在浏览器里直接查看。

* profiler命令wiki: https://alibaba.github.io/arthas/profiler.html

`profiler` 命令基本运行结构是 `profiler action [actionArg]`。下面介绍如何使用。

### 启动profiler

```
$ profiler start
Started [cpu] profiling
```

> 默认情况下，生成的是cpu的火焰图，即event为`cpu`。可以用`--event`参数来指定。

### 获取已采集的sample的数量

```
$ profiler getSamples
23
```

### 查看profiler状态

```bash
$ profiler status
[cpu] profiling is running for 4 seconds
```

可以查看当前profiler在采样哪种`event`和采样时间。

### 生成svg格式结果

```
$ profiler stop
profiler output file: /tmp/demo/arthas-output/20191125-135546.svg
OK
```

默认情况下，生成的结果保存到应用的`工作目录`下的`arthas-output`目录里。

### 通过浏览器查看arthas-output下面的profiler结果

默认情况下，arthas使用3658端口，则可以打开： [http://localhost:3658/arthas-output/](http://localhost:3658/arthas-output/) 查看到`arthas-output`目录下面的profiler结果：

![](https://alibaba.github.io/arthas/_images/arthas-output.jpg)

点击可以查看具体的结果：

![](https://alibaba.github.io/arthas/_images/arthas-output-svg.jpg)

> 如果是chrome浏览器，可能需要多次刷新。

## grep命令支持更丰富的选项

标准的linux grep命令支持丰富的选项，可以很方便地定位结果的上下文等。

新版本的`grep`命令支持更多标准的选项，下面是一些例子:

```bash
sysprop | grep java
sysprop | grep java -n
sysenv | grep -v JAVA
sysenv | grep -e "(?i)(JAVA|sun)" -m 3  -C 2
sysenv | grep JAVA -A2 -B3
thread | grep -m 10 -e  "TIMED_WAITING|WAITING"
```

感谢社区里 @qxo 的贡献。

## telnet/http协议共用3658端口

默认情况下，Arthas的Telnet端口是3658，HTTP端口是8563，这个常常让用户迷惑。在新版本里，在3658端口同时支持Telnet/HTTP协议。

在浏览器里访问 http://localhost:3658/ 也可以访问到Web Console了。

在后续的版本里，考虑默认只侦听 3658端口，减少用户的配置项。

## monitor/tt/trace等命令提供更精确的时间统计

以前Arthas被诟病比较多的一个问题是，monitor/tt/trace等命令时间统计误差大。因为以前只使用了一个int来保存时间，所以不精确。

在新版本里，改用一个高效的stack来保存数据，时间的准确度大大提升，欢迎大家反馈效果。

感谢社区里 @huangjIT 的贡献。

### 总结

总之，`3.1.5`版本的Arthas引入了开箱即用的Profiler/火焰图功能，欢迎大家使用反馈。

* 火焰图的一个参考文章：https://openresty.org/posts/dynamic-tracing/
* Release Note: https://github.com/alibaba/arthas/releases/tag/arthas-all-3.1.5

最后，**Arthas 正在参加2019年度最受欢迎开源中国软件评选，急需大家宝贵的一票支持！！[查看](https://www.oschina.net/p/arthas)**

---

评论区抽奖两本图书：
![openshift](https://user-images.githubusercontent.com/1683936/69688713-cec6dc80-1101-11ea-8578-f8a77ca089df.jpg)

![data](https://user-images.githubusercontent.com/1683936/69688719-d1c1cd00-1101-11ea-9b5b-179462171c5d.jpg)

抽奖要求：

* 给Arthas抽票：https://www.oschina.net/p/arthas
* 评论里提供投票结果截图

**Comment by xwmm** [comment]
arthas真的是神器，解决了很多开发中遇到了问题，支持arthas！

**Comment by fengshanbieyuan** [comment]
支持arthas，神器！！！

**Comment by anjia0532** [comment]
火焰图，神器啊。更快速的定位问题，赞！！！！

**Comment by uzdz** [comment]
牛的已经没有啥特大更新了（画风突变）。

**Comment by LovingCat** [comment]
支持arthas

**Comment by fengshanbieyuan** [comment]
已在开源中国投了arthas，如此神器，好多人居然没有用过，还有不知道的。。。。。。

**Comment by RayneHwang** [comment]
希望尽快支持 agent 启动哈，这个特性对分析启动期问题非常有帮助

**Comment by SatanDaddy** [comment]
校招入职就开始用了，绩效的一半功劳都在这个工具上面 持续支持Arthas

**Comment by idelin** [comment]
支持了，已投票

![image](https://user-images.githubusercontent.com/23070481/69689422-ddae8e80-1103-11ea-99ba-484d37e1dd16.png)

**Comment by 917330831** [comment]
线上实时定位问题神器arthas，一直在用

**Comment by zyfsuzy** [comment]
so nice,  飞起 6666

**Comment by xiaocaoshangshen** [comment]
已投票支持！刚刚使用这个软件，希望能给我带来更多的帮助！感谢arthas！！！
![3601574823216_ pic_hd](https://user-images.githubusercontent.com/42339693/69689535-2ebe8280-1104-11ea-9994-5051c8d71693.jpg)

**Comment by sunlife95** [comment]
支持arthas

**Comment by kosmosr** [comment]
支持一波

**Comment by diege1984** [comment]
搞的俺想升级看看

**Comment by lov3r** [comment]
支持了，已投票
![image](https://user-images.githubusercontent.com/33676682/69690894-2a946400-1108-11ea-992b-453627996e11.png)

**Comment by legiorange** [comment]
已投票支持，从去年就关注arthas。曾用在开发中解决了棘手的问题，曾经也读过源码想贡献自己的力量，可惜我技术太垃圾。

另小马哥nacos重庆活动有小马哥亲笔签名Dubbo 纪念卫衣。

许愿openshift……

但这两本书我估计是得不到了，希望书能落到需要它的人手中。

**Comment by 18338739892** [comment]
![image](https://user-images.githubusercontent.com/23350605/69691039-a2628e80-1108-11ea-9483-a184e004aea3.png)
待俺升级一下,研究一下新功能,支持了噢。

**Comment by shterm** [comment]
支持arthas， 期待后续可以为arthas项目贡献自己的力量。

**Comment by pangjianhua** [comment]
强力支持，很好用

**Comment by shysnow** [comment]
定位利器,已经集成到我的产品工具包里,方便在线定位问题.

**Comment by anjia0532** [comment]
已投票 ![image](https://user-images.githubusercontent.com/15098916/69692730-e906b780-110d-11ea-9084-3658982b64a8.png)

**Comment by jianxia612** [comment]
此工具不错 继续完善和加油！

**Comment by hc24** [comment]
![{4B33CEDD-F60F-4A6B-812D-6C6B05089723}_20191127135352](https://user-images.githubusercontent.com/9858863/69697627-f1ff8500-111d-11ea-9c08-e29ff69fe19e.jpg)
一直在用，在线调试利器，专治各种疑难杂症

**Comment by mingduo** [comment]
给力

**Comment by zuowenmou** [comment]
🐂批！！！！！！！！！！！！！

**Comment by wickywe** [comment]
已投票支持，神器

**Comment by zshow** [comment]
![image](https://user-images.githubusercontent.com/16797829/69785613-753eda80-11f3-11ea-8a0c-a81a891889af.png)
试用中.

**Comment by X-rapido** [comment]
支持阿里巴巴，支持国产，给力！

**Comment by haihhhhh** [comment]
阿尔萨斯前一段助我解决生产环境上的重大性能问题，感谢！
![image](https://user-images.githubusercontent.com/20589674/69871897-f7f89000-12ee-11ea-804f-63275576c89e.png)

**Comment by hengyunabc** [comment]
钉钉群直播抽奖结果是： @idelin 和 @anjia0532  ，恭喜两位，可以加钉钉群或者QQ群里，联系群主。

**Comment by jiangwh** [comment]
很好用～～
