### ISSUE TITLE
profiler命令找不到

### ISSUE THREAD

**Issue by RuvikVan** [alibaba/arthas#953]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.5
* Arthas 版本: 3.1.4
* 操作系统版本: centos 7
* 目标进程的JVM版本: 1.8.144
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. xxx
2. xxx
3. xxx

### 期望的结果

What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```
java.lang.IllegalArgumentException: profiler: command not found

**Comment by hengyunabc** [comment]
3.1.5版本才有的功能，可以先 stop 掉，再下载 3.1.5版本的 attach。 也许要重启应用。

**Comment by RuvikVan** [comment]
> 3.1.5版本才有的功能，可以先 stop 掉，再下载 3.1.5版本的 attach。 也许要重启应用。

我就是从官网下载的3.1.5版本 但是里面的Arthas版本是3.1.4的

**Comment by hengyunabc** [comment]
> > 3.1.5版本才有的功能，可以先 stop 掉，再下载 3.1.5版本的 attach。 也许要重启应用。
> 
> 我就是从官网下载的3.1.5版本 但是里面的Arthas版本是3.1.4的

具体怎么操作的？中间详细的信息？

或者下载全量包： https://alibaba.github.io/arthas/download.html

**Comment by RuvikVan** [comment]
> > > 3.1.5版本才有的功能，可以先 stop 掉，再下载 3.1.5版本的 attach。 也许要重启应用。
> > 
> > 
> > 我就是从官网下载的3.1.5版本 但是里面的Arthas版本是3.1.4的
> 
> 具体怎么操作的？中间详细的信息？
> 
> 或者下载全量包： https://alibaba.github.io/arthas/download.html

[root@localhost software]# java -jar arthas-boot.jar 
[INFO] arthas-boot version: 3.1.5
[INFO] Process 20405 already using port 3658
[INFO] Process 20405 already using port 8563
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 20405 org.apache.catalina.startup.Bootstrap
1
[INFO] arthas home: /root/software
[INFO] The target process already listen port 3658, skip attach.
[INFO] arthas-client connect 127.0.0.1 3658
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki      https://alibaba.github.io/arthas                                      
tutorials https://alibaba.github.io/arthas/arthas-tutorials                     
version   3.1.4                                                                 
pid       20405                                                                 
time      2019-11-27 09:24:09

**Comment by hengyunabc** [comment]
@RuvikVan 执行 `stop` 命令，彻底停止原来的arthas，不然一直连的都是旧版本的。

**Comment by RuvikVan** [comment]
> @RuvikVan 执行 `stop` 命令，彻底停止原来的arthas，不然一直连的都是旧版本的。

killall命令尝试了不行，在重启服务器以后，可以了
