### ISSUE TITLE
arthas 的 thread 根据状态统计无法使用

### ISSUE THREAD

**Issue by xingguang2013** [alibaba/arthas#954]
arthas  版本 3.1.4
在进入某个 java 进程监控后，无法使用 thread --state RUNNABLE 方式按照状态统计线程，执行命令后报错 具体信息我明天再贴出来

**Comment by xingguang2013** [comment]
报错如下:
during processing the command : Cannot  inject value for argument '0'

**Comment by hengyunabc** [comment]
这个应该是 3.1.5版本才有的功能

**Comment by xingguang2013** [comment]
看 3.1.5 release note  中，没有提到，回去再试试，谢谢

**Comment by hengyunabc** [comment]
> 看 3.1.5 release note 中，没有提到，回去再试试，谢谢

的确漏掉了，更新release note了。
