### ISSUE TITLE
profiler在shutdown后，再次使用会报错

### ISSUE THREAD

**Issue by wenbeicai** [alibaba/arthas#961]
如果执行profiler start后，调用了shutdown，之后如果再次使用profiler start，会报错
![2019-12-02 17-53-36 的屏幕截图](https://user-images.githubusercontent.com/16438030/69952431-22865b00-1532-11ea-99fb-3f67e7399204.png)
原因应该是：so被重新load了两次，是不是可以处理一下。

**Comment by hengyunabc** [comment]
的确有这个问题，我看怎么处理下

```bash
$ profiler start
Native Library /Users/hengyunabc/.arthas/lib/3.1.5/arthas/async-profiler/libasyncProfiler-mac-x64.so already loaded in another classloader
```

**Comment by hengyunabc** [comment]
改为用SystemClassLoader来加载 one/profiler的类，这样子arthas多次attatch都是加载的SystemClassLoader里的async profiler.

修复测试版：

[arthas-3.1.6-SNAPSHOT-bin.zip](https://github.com/alibaba/arthas/files/3911284/arthas-3.1.6-SNAPSHOT-bin.zip)

**Comment by wenbeicai** [comment]
再问个问题，这个是BootstrapClassLoader，不是SystemClassLoader吧

**Comment by hengyunabc** [comment]
> 再问个问题，这个是BootstrapClassLoader，不是SystemClassLoader吧

放到了 arthas-spy.jar 里，的确是 BootstrapClassLoader 。

**Comment by wenbeicai** [comment]
感谢。
