### ISSUE TITLE
Arthas 的watch命令有没有“后遗症”

### ISSUE THREAD

**Issue by JackyZhangFuDan** [alibaba/arthas#964]
专家你好，watch命令能够让我们观察到一个方法执行中，执行后等时间点的参数状况，这很cool，同时让我想到了BTrace这个工具。

BTrace也可以达到类似的效果，但它有个问题是BTrace是‘侵入性’的把一些代码注入生产代码（的jvm环境），注入以后每次调用到目标方法时，jvm都会检测被注入代码需不需要执行，如果BTrace已经退出了那么不执行；如果没有那么就执行。这样难免让人担心它对性能带来的影响。

那么Arthas的Watch是什么机制呢？会不会也在执行后遗留东西在生产环境？

谢谢。

**Comment by oyealex** [comment]
可以用reset命令恢复被增强的类
