### ISSUE TITLE
对java8函数式接口方法进行trace会导致应用报错

### ISSUE THREAD

**Issue by IndiraFinish** [alibaba/arthas#968]
### 环境信息

* Arthas 版本: 3.1.7
* 操作系统版本: mac os
* 目标进程的JVM版本: java8
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

```
/**
 * Created by WangXW.
 * Date: 2019/11/13
 */
@FunctionalInterface
public interface Operation<T> {
    T operate();
}
```

对这个函数式接口进行trace会导致应用报错，不知道不是javaagent本身的问题
`Caused by: java.lang.NoClassDefFoundError: com/olayc/dispatcher/sms/AbstractSmsMessageDispatcher$$Lambda$920`

**Comment by hengyunabc** [comment]
例子更详细点？

**Comment by Roger3581321** [comment]
@IndiraFinish 您好，按照提供的步骤，尝试重现了一下java8函数接口trace的问题，无法重现，请确认下。

环境信息
Arthas 版本: 3.1.7
操作系统版本: windows
目标进程的JVM版本: java8
执行arthas-boot的版本: xxx

重现问题的步骤
```
@FunctionalInterface
public interface Consumer<T> {

    /**
     * Performs this operation on the given argument.
     *
     * @param t the input argument
     */
    void accept(T t);

```


```
public class ConsumerFunc {

	public static void main(String[] args) {
		for(;;) {
			run();
		}
	}
	
	public static void run() {
		Consumer<String> consumer = (arg) -> {
			System.out.println(arg);
		};
		consumer.accept("Hello World!");
	 }

}
```

arthas trace命令运行结果，如下图：
![Capture](https://user-images.githubusercontent.com/23419065/74103192-22838680-4b85-11ea-9679-ba2a3019a2a2.JPG)
