### ISSUE TITLE
redefine热更新报错

### ISSUE THREAD

**Issue by NathanPelli** [alibaba/arthas#969]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.4
* Arthas 版本: 3.1.4
* 操作系统版本: Red Hat 4.4.7
* 目标进程的JVM版本: 1.8.0_65
* 执行`arthas-boot`的版本: 3.1.4

### 重现问题的步骤

1. 本地ideal使用的jdk版本跟服务器上一样，都是1.8.0_65。服务器上项目正在运行，包含Test.class
2. Test.java文件没有修改任何地方(或者就加一行日志)，然后本地编译产生Test.class文件，将该class文件上传到服务器上
3. 执行代码热更新命令，redefine /tmp/Test.class

### 期望的结果

热更新成功，提示：redefine success

### 实际运行的结果

热更新失败提示：redefine error! java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)

**Comment by hengyunabc** [comment]
提示很清楚了 `attempted to change the schema (add/remove fields)`

https://alibaba.github.io/arthas/redefine.html

**Comment by hengyunabc** [comment]
看错了，把机器上的 `Test.class` 和 本地编译产生的 `Test.class`传上来？

机器上的，可以用这个工具获取： https://github.com/hengyunabc/dumpclass

**Comment by NathanPelli** [comment]
> 提示很清楚了 `attempted to change the schema (add/remove fields)`
> 
> https://alibaba.github.io/arthas/redefine.html

不是的，我是把本地对应的Test.java代码本地编译成class文件，然后上传到服务器，进行redefine热更新的时候报错提示的。但是我的Test.java源代码文件，没有任何改动。这是怎么回事呢？

**Comment by NathanPelli** [comment]
> 提示很清楚了 `attempted to change the schema (add/remove fields)`
> 
> https://alibaba.github.io/arthas/redefine.html

关键是我的源代码没有做任何修改，本地编译成class文件，进行redefine热更新为啥会报错呢？

**Comment by NathanPelli** [comment]
> 看错了，把机器上的 `Test.class` 和 本地编译产生的 `Test.class`传上来？
> 
> 机器上的，可以用这个工具获取： https://github.com/hengyunabc/dumpclass

**Comment by NathanPelli** [comment]
> > 看错了，把机器上的 `Test.class` 和 本地编译产生的 `Test.class`传上来？
> > 机器上的，可以用这个工具获取： https://github.com/hengyunabc/dumpclass

**Comment by hengyunabc** [comment]
参考这个： https://www.robberphex.com/lambda-causes-arthas-cant-redefine/

**Comment by JansonJo** [comment]
> 参考这个： https://www.robberphex.com/lambda-causes-arthas-cant-redefine/
dump了机器上的class文件和本地的class文件对比了一下，lambda方法名的后缀是一致的，但是从机器上dump下来的class文件除了Test.class还有一个Test$$EnhancerBySpringCGLIB$$dfcde552.class，CGLIB生成的class类中没有对应lambda方法，是不是因为这个原因导致class redefinition failed报错？
@hengyunabc
