### ISSUE TITLE
按照文档安装,启动过程中的错误

### ISSUE THREAD

**Issue by CalmnessJoy** [alibaba/arthas#97]
Error: Unable to access jarfile /root/.arthas/lib/3.0.4/arthas/arthas-core.jar
attach to target jvm (3010) failed, check /root/logs/arthas/arthas.log or stderr of target jvm for any exceptions.

**Comment by hengyunabc** [comment]
检查文件是否存在，尝试 bash -x ./as.sh 看下脚本具体在哪里出错。

**Comment by XUZHOUWANG** [comment]
可以查看/root/.arthas/lib/3.0.4/arthas/arthas-core.jar文件是否存在；可以手动安装https://alibaba.github.io/arthas/install-detail.html
