### ISSUE TITLE
release发布的能否提供gitee下载

### ISSUE THREAD

**Issue by lizhuangs** [alibaba/arthas#971]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 下载问题
我发现.jar可以在gitee下载，但是其它的release发布的比如.deb的就只能在github下载，网速感人。。。

**Comment by Issocala** [comment]
你可以自己配置一下你自己的hosts  避免每次都是米国那边找ip，这样网速可以达到几百K

**Comment by hengyunabc** [comment]
如果下载速度比较慢，可以尝试用[阿里云的镜像仓库](https://maven.aliyun.com/)，比如要下载`3.x.x`版本（替换`3.x.x`为最新版本），下载的url是：

https://maven.aliyun.com/repository/public/com/taobao/arthas/arthas-packaging/3.x.x/arthas-packaging-3.x.x-bin.zip

**Comment by lizhuangs** [comment]
@hengyunabc Tks!
