### ISSUE TITLE
跪求告知logo.txt的banner文字生成工具

### ISSUE THREAD

**Issue by weiyue888999** [alibaba/arthas#972]
最近我司在做一个webconsole工具，使用和参考了贵司arthas-core工程大部分代码，想知道arthas-core工程内src/main/resources/com/taobao/arthas/core/res/logo.txt 文件里面的内容是使用哪种工具生成的。

**Comment by hengyunabc** [comment]
以前在一个在线网站生成的，找不到了，直接 google online logo text 可以找到很多网站。
