### ISSUE TITLE
使用aliyun的镜像下载是什么意思

### ISSUE THREAD

**Issue by lizhuangs** [alibaba/arthas#973]
- [x] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 文档大约过了一下，有一处不太理解
如果下载速度比较慢，可以使用aliyun的镜像：
`java -jar arthas-boot.jar --repo-mirror aliyun --use-http`  
jar已经下载到本地了，看不懂这句话还要从aliyun下载什么？

**Comment by hengyunabc** [comment]
这个只是启动jar，还要下载10M的zip包。仔细看第一次启动的日志，会有下载的信息。
