### ISSUE TITLE
使用jad进行反编译没有成功

### ISSUE THREAD

**Issue by 348786639** [alibaba/arthas#977]
[arthas@25590]$ jad com.ding.service.IndexService
[arthas@25590]$ exit
[root@iZbp1cm2bsuv26lx7z97ycZ arthas]#   java -jar arthas-boot.jar
[INFO] arthas-boot version: 3.1.7
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 25590 org.apache.catalina.startup.Bootstrap
1
[INFO] arthas home: /root/.arthas/lib/3.1.7/arthas
[INFO] Try to attach process 25590
[INFO] Attach process 25590 success.
[INFO] arthas-client connect 127.0.0.1 3658
  ,---.  ,------. ,--------.,--.  ,--.  ,---.   ,---.                           
 /  O  \ |  .--. ''--.  .--'|  '--'  | /  O  \ '   .-'                          
|  .-.  ||  '--'.'   |  |   |  .--.  ||  .-.  |`.  `-.                          
|  | |  ||  |\  \    |  |   |  |  |  ||  | |  |.-'    |                         
`--' `--'`--' '--'   `--'   `--'  `--'`--' `--'`-----'                          
                                                                                

wiki      https://alibaba.github.io/arthas                                      
tutorials https://alibaba.github.io/arthas/arthas-tutorials                     
version   3.1.7                                                                 
pid       25590                                                                 
time      2019-12-16 16:52:32                                                   

[arthas@25590]$ jad com.ding.service.IndexService
Affect(row-cnt:0) cost in 51 ms.
[arthas@25590]$ jad com.ding.service.IndexService

没有反编译的代码输出

**Comment by hengyunabc** [comment]
检查 ~/logs/arthas/arthas.log 的日志

**Comment by 348786639** [comment]
@hengyunabc 
日志信息没有什么报错信息

[root@iZbp1cm2bsuv26lx7z97ycZ logs]# tail -fn 200 arthas/arthas.log 
Arthas server agent start...
Arthas start to bind...
Arthas server bind success.
Arthas server agent start...
Arthas server already bind.
Arthas server agent start...
Arthas server already bind.
Arthas server agent start...
Arthas server already bind.
Arthas server agent start...
Arthas server already bind.
Arthas server agent start...
Arthas start to bind...
Arthas server bind success.
Arthas server agent start...
Arthas start to bind...
Arthas server bind success.

**Comment by hengyunabc** [comment]
可以提供可重现的demo不？

**Comment by hengyunabc** [comment]
> @hengyunabc
> https://github.com/348786639/arthas_test

demo里没有 com.ding.service.IndexService 这个类啊？

**Comment by 348786639** [comment]
@hengyunabc 
使用这个IndexController也是一样的
jad com.ding.controller.IndexController

**Comment by hengyunabc** [comment]
@348786639 你使用的是什么jdk 和 tomcat，我本地jdk8, tomcat 8是可以的。

```
[arthas@91940]$ jad com.ding.controller.IndexController

ClassLoader:
+-ParallelWebappClassLoader
    context: blog
    delegate: false
  ----------> Parent Classloader:
  java.net.URLClassLoader@7a81197d

  +-java.net.URLClassLoader@7a81197d
    +-sun.misc.Launcher$AppClassLoader@55f96302
      +-sun.misc.Launcher$ExtClassLoader@7f560810

Location: /tmp0/wtpwebapps/blog/WEB-INF/classes/

/*
 * Decompiled with CFR.
 *
 * Could not load the following classes:
 *  org.springframework.stereotype.Controller
 *  org.springframework.web.bind.annotation.RequestMapping
 *  org.springframework.web.servlet.ModelAndView
 */
package com.ding.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

@Controller
@RequestMapping(value={"/index"})
public class IndexController {
    @RequestMapping(value={"/index"})
    public ModelAndView index(Long categoryId) {
        ModelAndView mv = new ModelAndView();
        mv.setViewName("index");
        return mv;
    }
}
```

---

另外，检查tomcat是否启动成功，tomcat如果启动失败，可能tomcat的 classloader有问题。

**Comment by 348786639** [comment]
@hengyunabc 
我的项目是可以访问的，所以是启动成功的
tomcat ： 8.5.40

我使用        dashboard 可以看到jdk版本                                                                                                                                                        
java.version                                                                   1.8.0_144                                                                      
java.home                                                                      /usr/local/jdk1.8.0_144/jre    

我尝试换下tomcat试下

**Comment by hengyunabc** [comment]
> @hengyunabc
> 我的项目是可以访问的，所以是启动成功的
> tomcat ： 8.5.40
> 
> 我使用 dashboard 可以看到jdk版本
> java.version 1.8.0_144
> java.home /usr/local/jdk1.8.0_144/jre
> 
> 我尝试换下tomcat试下

* 试下`sc` 命令能找到类不
* 试下配置 jdk 启动tomcat，而不是jre
* 还不行，可以试下debug arthas，参考： https://github.com/alibaba/arthas/blob/master/CONTRIBUTING.md#%E5%BC%80%E5%8F%91%E8%80%85%E7%9B%B8%E5%85%B3
