### ISSUE TITLE
使用arthas更新logger级别报错

### ISSUE THREAD

**Issue by xiajunhust** [alibaba/arthas#980]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.7
* 操作系统版本: 
* 目标进程的JVM版本: 
* 执行`arthas-boot`的版本: xxx

### 重现问题的步骤

1. 阿里内部sofaboot应用 不太好重现

### 期望的结果

What do you expected from the above steps？

能动态更新logger级别

### 实际运行的结果
报错， update logger level fail.

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
01 2019-12-21 14:57:18.784 ERROR [as-command-execute-daemon:arthas] [] [] [arthas] logger command update log4j2 level error
java.lang.ClassNotFoundException: com.taobao.arthas.core.command.logger.Log4j2Helper5558302f764c12b6
```

**Comment by hengyunabc** [comment]
`-c` 指定 classloader

**Comment by netbuffer** [comment]
我也遇到这个问题,按照楼上说的方法,使用-c classLoaderHash，修改成功了

**Comment by a5618555** [comment]
我修改成功了  然后就没有然后了  日志还是在正常打印  我使用的是logstash

**Comment by hengyunabc** [comment]
> 我修改成功了 然后就没有然后了 日志还是在正常打印 我使用的是logstash

只支持 log4j/log4j2/logback

**Comment by a5618555** [comment]
使用的是logback 直接加入了appender 这个也不行吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/arthas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月3日(星期四) 上午10:20
收件人:&nbsp;"alibaba/arthas"<arthas@noreply.github.com&gt;;
抄送:&nbsp;"我要换个网名。"<1027171565@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/arthas] 使用arthas更新logger级别报错 (#980)





  
我修改成功了 然后就没有然后了 日志还是在正常打印 我使用的是logstash
  
只支持 log4j/log4j2/logback

**Comment by hengyunabc** [comment]
> 使用的是logback 直接加入了appender 这个也不行吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/arthas" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月3日(星期四) 上午10:20 收件人:&nbsp;"alibaba/arthas"<arthas@noreply.github.com&gt;; 抄送:&nbsp;"我要换个网名。"<1027171565@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [alibaba/arthas] 使用arthas更新logger级别报错 (#980) 我修改成功了 然后就没有然后了 日志还是在正常打印 我使用的是logstash 只支持 log4j/log4j2/logback — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

另外开一个issue，写明具体的步骤，日志，最好有可以重现的demo。
