### ISSUE TITLE
建议将shutdown命令移除，完全用stop替代

### ISSUE THREAD

**Issue by Feixu2015** [alibaba/arthas#982]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： 3.1.7
* Arthas 版本: 3.1.7
* 操作系统版本: Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
* 目标进程的JVM版本: 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1. shutdown当前位于arthas命令行还是系统命令行难以区分，很容易以为是关闭arthas结果把操作系统关闭了。

### 期望的结果

直接将shutdown命令用stop代替，避免造成误操作

### 实际运行的结果

无

**Comment by hengyunabc** [comment]
的确可以考虑删掉了。不过还是很容易区分吧。

**Comment by qixiaobo** [comment]
防御操作 确实有风险 ~所以另可不执行shutdown了

**Comment by Feixu2015** [comment]
> 的确可以考虑删掉了。不过还是很容易区分吧。

把出错的概率降为0是最好的防御😃

**Comment by hengyunabc** [comment]
为了保持兼容性，hidden掉。
