### ISSUE TITLE
pass云上使用profiler问题

### ISSUE THREAD

**Issue by xiangqingyijiu** [alibaba/arthas#983]
我使用的是3.1.7版本 
我在pass云上使用profiler start 命令 
![1577262540054353324059](https://user-images.githubusercontent.com/33444581/71439215-b1eaec80-2733-11ea-9fe7-da700adcbe5d.jpg) 
执行默认的cpu报错，事件alloc可以成功，命令停止后，火焰图成的内容不对
![1577262773308337900001](https://user-images.githubusercontent.com/33444581/71439338-376e9c80-2734-11ea-9358-51f9eb5368bc.jpg)

**Comment by hengyunabc** [comment]
容器本身权限不够，参考： https://github.com/jvm-profiling-tools/async-profiler

**Comment by xiangqingyijiu** [comment]
容器本身权限不够？能具体一点吗？
根据看到的async-profiler文档，报错信息：
Perf events unavailble. See stderr of the target process.
perf_event_open()syscall失败。错误消息将打印到目标JVM的错误流。

典型原因包括：

/proc/sys/kernel/perf_event_paranoid 设置为受限模式（> = 2）。
seccomp禁用容器中的perf_event_open API。
操作系统在不虚拟化性能计数器的管理程序下运行。
该系统不支持perf_event_open API，例如WSL。

 线下服务器、云上 perf_event_paranoid 参数默认都是1
我在线下服务器上修改 perf_event_paranoid 参数为2
也会报和云上容器一样的问题，所以看起来和这个值无关。
经查，我们云上支持perf_event_open API

**Comment by hengyunabc** [comment]
@xiangqingyijiu 可以到 async-profiler 下面提issue，我这边没有环境，也无能为力。
