### ISSUE TITLE
Arthas home is not a directory, please delete it and retry.

### ISSUE THREAD

**Issue by aBlackAnt** [alibaba/arthas#984]
Arthas script version: 3.1.7
[INFO] JAVA_HOME: /usr/java/jdk1.6.0_31

运行./as.sh，提示如下
Arthas home: /root/.arthas/lib//arthas
Arthas home is not a directory, please delete it and retry.

删除路径/root/.arthas后，再次运行仍提示该信息

**Comment by hengyunabc** [comment]
贴出全部的日志，检查脚本是否下载zip包失败。  或者下载全量包解压使用。

**Comment by abelzyp** [comment]
我也遇到了同样的问题，全部日志如下：
$ sh as.sh 
Arthas script version: 3.3.7
[INFO] JAVA_HOME: /usr/local/jdk1.7.0_76
Found existing java process, please choose one and input the serial number of the process, eg : 1. Then hit ENTER.
\* [1]: 85952 hotel-goods-query-server.jar
1
Arthas home: /home/username/.arthas/lib//arthas
Arthas home is not a directory, please delete it and retry.

按照提示，我把/home/username/.arthas/lib//arthas删除，现在只剩下/home/username/.arthas/目录了，之后又运行了一次as.sh脚本，结果依然如上。求指教！

**Comment by hengyunabc** [comment]
@abelzyp 试下删掉原来的脚本和文件，下载最新的 as.sh

**Comment by abelzyp** [comment]
> @abelzyp 试下删掉原来的脚本和文件，下载最新的 as.sh

嗯嗯，我大概知道啥问题了。我们线上机器上没安装完全Arthas。感谢大佬！

**Comment by cc-a100** [comment]
你好,能具体说下原因吗,没安装完全是什么意思，我这边也遇到了同样的问题？
