### ISSUE TITLE
使用tunnel-server远程连接arthas页面显示问题

### ISSUE THREAD

**Issue by kaimeng110091** [alibaba/arthas#989]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.7
* 操作系统版本: win10
* 目标进程的JVM版本: 1.8.0_211
* 执行`arthas-boot`的版本: 3.1.7

### 重现问题的步骤

1. 使用tunnel连接上arthas后, 底部显示不完整, 无法查看输入的命令
2. xxx
3. xxx

### 期望的结果
请问可以使用xshell等远程连接工具连接tunnel然后远程连接arthas吗?
What do you expected from the above steps？

### 实际运行的结果

实际运行结果，最好有详细的日志，异常栈。尽量贴文本。

```
把异常信息贴到这里
```

**Comment by hengyunabc** [comment]
> 使用tunnel连接上arthas后, 底部显示不完整, 无法查看输入的命令

提供具体的截图，还有浏览器版本信息等。
