### ISSUE TITLE
Arthas 对于老项目一些方法很长报错问题

### ISSUE THREAD

**Issue by ezrio** [alibaba/arthas#993]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本：最新版本
* Arthas 版本: xxx
* 操作系统版本: centos
* 目标进程的JVM版本: 1.8
* 执行`arthas-boot`的版本: xxx

运行trace，watch ，statck 报错：No class or method is affected . 查看日志报错如下：
org.objectweb.asm.MethodTooLargeException:Method too large.
这个有什么后续能够兼容的处理嘛？还是必须要拆分方法？

**Comment by hengyunabc** [comment]
试下执行 reset 命令。 jdk本身的限制，无解。

**Comment by diligentdpf** [comment]
> 试下执行 reset 命令。 jdk本身的限制，无解。
reset 可以解决这个问题，我这边也是

**Comment by wupflove** [comment]
> * [ ]  我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。
> 
> ### 环境信息
> * `arthas-boot.jar` 或者 `as.sh` 的版本：最新版本
> * Arthas 版本: xxx
> * 操作系统版本: centos
> * 目标进程的JVM版本: 1.8
> * 执行`arthas-boot`的版本: xxx
> 
> 运行trace，watch ，statck 报错：No class or method is affected . 查看日志报错如下：
> org.objectweb.asm.MethodTooLargeException:Method too large.
> 这个有什么后续能够兼容的处理嘛？还是必须要拆分方法？

到底是多长的代码引发的呢？
